.circleci/config.yml
crates/apollo-router/Cargo.toml
crates/apollo-router/tests/integration_tests.rs
docker-compose.yml
xtask/src/commands/test.rs
xtask/src/federation_demo.rs

The integration tests have been disabled by #99 and broke (locally) by #111.

Re-enable integration tests in CI

---

docs/source/configuration.mdx

it was not matching the configuration loader
like #118 but without the jaeger credentials issue

fix configuration file in docs

---

docs/source/configuration.mdx

Docs contained `https` for `localhost` rather than the more common `http` in the CORS origins

docs: change protocol for localhost example

---

Cargo.lock
crates/apollo-router-core/Cargo.toml

fixes #121 
The latest commit reduces router-bridge compile times, and a couple of apollo_parser fixes allow us to handle invalid schemas better, as well as comments.

chore: bump federation and apollo_parser dependencies.

---

DEVELOPMENT.md
ROADMAP.md

When following the directions in `DEVELOPMENT.md` I found that the command for adding plugins to `asdf` to have deviated from the original writing of that document. Also found a stray typo while browsing the `ROADMAP.md`

docs: asdf syntax change for installing plugins

---

crates/apollo-router/src/configuration/mod.rs
crates/apollo-router/src/state_machine.rs

Fix #129 
it was set up so that the schema overrides the configuration file's
subgraph URLs. Since we're now working with everything coming from the
schema, and the configuration for additional options, we must invert
that behaviour

invert subgraph URL override logic

---

crates/apollo-router/src/configuration/otlp/mod.rs

Fix #149 
the endpoint address is often specified as host:port instead of a full
URL: https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md#getting-started
Unfortunately, the url crate would parse 'collector:4317' as an URL with
the 'collector' scheme and no host. It also will not recognize
'IP:port'.
This adds a layer to URl parsing to recognize those cases, and configure
the HTTPS scheme manually

parse OTLP endpoint address

---

.circleci/config.yml
Cargo.lock

Now that the CI uses various layers of cache to speed up build times, we want to make sure the cache size doesn't grow over time, which is exactly what this does:
- Wrap each cargo build / test / xtask command with cargo sweep -s and cargo sweep -f

chore: use cargo_sweep in CI

---

crates/apollo-router-core/src/federated.rs
crates/apollo-router-core/src/naive_introspection.rs
crates/apollo-router-core/src/response.rs

I noticed that we are cloning cached naiveintrospection values when we
don't need to. If we modify that behaviour to return a reference we can
avoid unnecessary work.
resolves #168

Reduce cloning in Response composition

---

crates/apollo-router/src/main.rs

The tracing logger outputs text by default. Configure the logger to
output JSON.
resolves #46

Switch the router from text to JSON logging

---

crates/apollo-router/src/http_subgraph.rs

Potential fix for #144 
related: #33 #80
with very large responses, we were looping over HTTP chunks by
accumulating them, trying to parse the JSON response, then go for
another iteration if it was not enough, so we end up parsing the same
data very frequently
This commit first accumulates the data entirely, then parses it
:warning: **this potentially breaks @stream:** the previous code was trying to recognize an entire json response, return it, then try parsing another json response if there's still some data, and return a stream of responses. From what I see the code could not handle stream responses anyway since multipart is expected: https://github.com/graphql/graphql-over-http/blob/main/rfcs/IncrementalDelivery.md#content-type-multipartmixed
We should investigate that
**Edit:** …

do not reparse JSON responses in a loop

---

.circleci/config.yml
xtask/src/federation_demo.rs

fixes #181, #178
This commit fixes a bug in the way `xtask test` was running, and changes the caching strategy.
Xtask test:
Xtask was running `npm install` instead of `npm clean-install`.
NPM install does update the package-lock.json file if it is able to find updates to a package that satisfy the version requirements defined in package.json.
However the CI caching strategy is looking for a key that contains the hash of `package-lock.json`.
In this scenario the cache would:
- search for a hash of the package-lock.json
- miss the cache
- run a clean npm install (thus updating package-lock.json)
- upload the build artefact under the hash of the new package-lock.json
Subsequent CI runs would look for the previous package-lock.json, and never hit.
Caching:
Given the .yml file might be hard to …

fixes: decrease CI cache size

---

Cargo.lock
DEVELOPMENT.md
about.toml
licenses.html
xtask/Cargo.toml
xtask/src/commands/all.rs
xtask/src/commands/check.rs
xtask/src/commands/mod.rs
xtask/src/commands/test.rs
xtask/src/main.rs

Local devs can now run `cargo xtask all` before opening a PR.
Xtask all does the following steps (that the CI does):
- check code format
- check against clippy lints
- check for CVEs and not allowed licenses.
- Make sure the licenses.html file is up to date.
- Start the subgraphs and run tests with the relevant features permutation for your OS.

feat: cargo xtask all

---

crates/apollo-router/src/files.rs
crates/apollo-router/src/lib.rs

fixes #60 
As explained in the [notify documentation](https://github.com/notify-rs/notify/blob/ded07f442a96f33c6b7fefe3195396a33a28ddc3/src/lib.rs#L413) the file Create event has a higher priority than the Write event.
However our tests create the file and almost immediately start writing to it. The watcher did not propagate Create events, which lead to flakiness in these tests.
I'm lacking context but given the  `tokio::time::sleep()`s in the tests, this issue might have been seen on Linux as well, and worked around.
This commit removes the sleep()s in the test write functions, allows us to listen to Create events as well as Write events, and re enables the tests on osx.

fix: osx file reload

---

crates/apollo-router-core/src/json_ext.rs
crates/apollo-router-core/src/naive_introspection.rs
crates/apollo-router-core/src/query_planner/model.rs
crates/apollo-router-core/src/response.rs

I see a small perf improvement here. With 10k concurrent clients (I'm working with saturated CPUs to see breaking point behaviours):
query:
```
query  {\products(limit: 5) {  upc  name  price  review { body }  } }
```
854MB res memory
```
Summary:                                                         
Total:        57.0660 secs                                     
Slowest:      6.7271 secs                                      
Fastest:      0.0017 secs                                      
Average:      0.5240 secs                                      
Requests/sec: 17523.5611                                       
Response time histogram:                                         
0.002 [1]     |                                                
0.674 …
```

avoid cloning entities when building the response

---

.cargo/config
xtask/src/commands/test.rs

- pass --locked to the xtask command, so we make sure the xtask cache kicks in
- remove "" from the features set in xtask test

chore: xtask and CI cleanup

---

crates/apollo-router-core/src/query_planner/model.rs
crates/apollo-router-core/src/query_planner/router_bridge_query_planner.rs
crates/apollo-router-core/src/request.rs
crates/apollo-router/src/apollo_router.rs

we had a performance regression in
44543703cabf20920b68c1092c7d9693c9772136, where the router was suddenly
spending a lot of time serializing data to JSON. This was due to
the #[tracing::instrument] annotation, that will generate by default a
span at INFO level, with a field for each argument and return value,
through debug printing.
The issue was already there before JSON logging was added, but it made
it much more expensive, enough to be noticeable
Now those spans are at the DEBUG or TRACE levels so they do not cost much

set a lower log level for tracing::instrument attributes

---

Cargo.lock
apollo-router-core/Cargo.toml
apollo-router-core/src/query_planner/model.rs
apollo-router/Cargo.toml
apollo-router/src/apollo_router.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/otlp/mod.rs
licenses.html

fix #180
related to #38
- a5b8581 sets default values for service name and namespace, to fix #180
- 26045c3 fixes a regression introduced in https://github.com/apollographql/router/commit/34f5f9ea64fdeb488e0c99a4420394cc066b7744: if reqwest-tracing uses a different tracing-opentelemetry version, tracing headers are not propagated
- 3bc699f fixes a regression introduced in 44840e4: the execute and format_response phases were appearing as their own root spans
26045c3 is temporary, I'll send a PR to reqwest-tracing to support the tracing-opentelemetry 0.16
we should get #38 implemented, to make sure those kinds of regressions do not happen

set OTLP service name and namespace

---

DEVELOPMENT.md
examples/config-jaeger.yml

This was enabled by default in the past. Even the doc still documents it as it should be enabled by default.
> Go to https://studio.apollographql.com/sandbox/explorer to make queries and http://localhost:16686/ to reach Jaeger.

Add jaeger for development again

---

apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
xtask/Cargo.toml

This will make the borrow checker easier with closures

Update Rust edition to 2021

---

CHANGELOG.md
Cargo.lock
RELEASE_CHECKLIST.md
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
deny.toml

> An alpha or beta release is in volatile, active development. The release might not be feature-complete, and breaking API changes are possible between individual versions.
- JSON log output
- Fix Open Telemetry Zipkin report errors [#180](https://github.com/apollographql/router/issues/180)

v.0.1.0-alpha.2

---

.circleci/config.yml

During the various iterations on the build pipeline, I ended up removing nodejs, and putting it back eventually. I unfortunately forgot to put it back in the release pipeline, which causes it to fail.
We have followup work in federation that shall remove the nodejs requirement eventually, but we're not there yet.

fix: Reinstall node in the circleCI release pipeline.

---

apollo-router/src/main.rs

fix #138 
small quality of life improvement for benchmarks. Limiting the number of cores used by the runtime makes it easier to saturate the router with traffic, and record comprehensive traces without storing too much data.
This is in an environment variables because we should not expose that to users

make the number of cores configurable

---

apollo-router/src/snapshots/apollo_router__warp_http_server_factory__tests__it_provides_health_status_body.snap
apollo-router/src/snapshots/apollo_router__warp_http_server_factory__tests__it_provides_health_status_header.snap
apollo-router/src/warp_http_server_factory.rs

Provide a health check endpoint which behaves in the same way as the
health check on the gateway.
https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-express/src/ApolloServer.ts#L85
At this point in time it always returns pass because we don't have a
different health status to set.
resolves: #54

Add a basic health check to the router

---

apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/otlp/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-4.snap
apollo-router/src/trace.rs
docs/source/configuration.mdx

follow up on #193
fix #228
* moves tracing configuration to the `apollo_router::trace` module

implement trace sampling

---

apollo-router/src/snapshots/apollo_router__warp_http_server_factory__tests__health_check.snap
apollo-router/src/snapshots/apollo_router__warp_http_server_factory__tests__it_provides_health_status_body.snap
apollo-router/src/snapshots/apollo_router__warp_http_server_factory__tests__it_provides_health_status_header.snap
apollo-router/src/warp_http_server_factory.rs

I approved the PR too fast I just wanted to comment on it and it got merge with silly changes like the use if insta for a single string:
```rust
assert_json_snapshot!(String::from_utf8_lossy(res.body()));
```
This makes no sense at all and I would have pointed it out if I did had the chance to make a second round of review. But this is my fault as I shouldn't have select "approve" in the first place.
Related to #252

Improve health checks

---

apollo-router-core/src/json_ext.rs
apollo-router-core/src/naive_introspection.rs
apollo-router-core/src/query_planner/mod.rs
apollo-router-core/src/query_planner/selection.rs
apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__router_bridge_query_planner__tests__plan.snap
apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__tests__query_plan_from_json.snap
apollo-router-core/src/response.rs
apollo-router/src/apollo_router.rs

Fix: #248
This PR gets rid of the response mutex and simplify response merging.
- separate tasks of `fetch_node` in different methods to extract the mutex usage more easily
- refactor `execute_recursively` to merge response data incrementally from smaller subsets of the response
- use `FuturesUnordered` to transform parallel queries in a stream of subgraph responses that are then merged one by one
- generate with representations data a path for each entity, so that we know exactly where to insert it in the response data. This fixes #248

Remove the response mutex, refactor fetch_node and fix response merging

---

Cargo.lock
apollo-router-core/Cargo.toml

Uses published version of `apollo-parser` instead of a git hash.
@abernix mentioned y'all wanted to move away from having to rely on a git hash, so I published a new version with recent fixes and updates.

chore: use apollo-parser 0.2.0

---

Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
licenses.html
xtask/Cargo.toml

selecting updates from #221 and #262.
tonic and prost cannot be updated until https://github.com/open-telemetry/opentelemetry-rust/pull/660 is merged

update dependencies and licenses file

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/warp_http_server_factory.rs
licenses.html

this adds a tower layer that creates a span covering the entire request,
from request line parsing to the end of sending the response.
This will give us better information than creating the span in the warp
service, where it covers from the moment the request is fully parsed, to
the moment the response is created (but the body is not sent yet)
Adding this dependency does not cost much since tower-service is already included by warp. And we will be able to use tower middlewares for other features like rate limiting.
~~**warning:** I have not tested yet if this messes with trace id propagation from client headers~~ good news: it does not affect trace id. bad news: trace propagation still needs some work :/

integrate tower-http and its TraceLayer

---

apollo-router-core/src/traits.rs
apollo-router/src/http_subgraph.rs
apollo-router/src/state_machine.rs
apollo-router/src/warp_http_server_factory.rs

the subgraph fetcher is going through unneeded steps to generate a `Bytes` of the response, we can avoid most of them.
This PR adds `async_trait` on the  `Fetcher` trait, this simplifies the code further.
Now this assumes that only one response will come from the subgraph, so that will need to be changed when we implement defer and stream, but since those will use multipart to separate the responses, the previous code was not complete either

Simplify fetcher

---

Cargo.lock
apollo-router-core/Cargo.toml
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-2.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-3.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-4.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_grpc-2.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_grpc.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_http-2.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_http.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_tls_config.snap
apollo-router/src/configuration/testdata/config_basic.yml
apollo-router/src/configuration/testdata/config_full.yml
apollo-router/src/configuration/testdata/config_opentelemetry_jaeger_basic.yml
apollo-router/src/configuration/testdata/config_opentelemetry_jaeger_full.yml
apollo-router/src/configuration/testdata/config_opentelemetry_otlp_tracing_grpc_basic.yml
apollo-router/src/configuration/testdata/config_opentelemetry_otlp_tracing_grpc_common.yml
apollo-router/src/configuration/testdata/config_opentelemetry_otlp_tracing_grpc_full.yml
apollo-router/src/configuration/testdata/config_opentelemetry_otlp_tracing_grpc_tls.yml
apollo-router/src/configuration/testdata/config_opentelemetry_otlp_tracing_http_basic.yml
apollo-router/src/configuration/testdata/config_opentelemetry_otlp_tracing_http_common.yml
apollo-router/src/configuration/testdata/config_opentelemetry_otlp_tracing_http_full.yml
apollo-router/src/configuration/testdata/invalid_url.yaml
apollo-router/src/http_subgraph.rs
apollo-router/src/lib.rs
apollo-router/src/state_machine.rs
apollo-router/tests/integration_tests.rs

the URL was carried as a string from the configuration file or the
schema, up to the subgraph fetcher, without any validation.
This will fail the schema or configuration file parsing if the subgraph
URL is invalid

parse the routing_url configuration option

---

Cargo.lock
Cargo.toml
apollo-router-core/Cargo.toml
apollo-router-core/src/error.rs
apollo-router-core/src/naive_introspection.rs
apollo-router-core/src/query_planner/mod.rs
apollo-router-core/src/query_planner/router_bridge_query_planner.rs
apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__router_bridge_query_planner__tests__empty_query_plan_should_be_a_planner_error.snap
apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__router_bridge_query_planner__tests__plan.snap
apollo-router-core/well_known_introspection_queries/graphql_js_introspection_query.graphql
apollo-router-core/well_known_introspection_queries/npx_diagnose_endpoint1.graphql
apollo-router-core/well_known_introspection_queries/npx_diagnose_endpoint2.graphql

Fixes https://github.com/apollographql/federation/issues/1320
Fix: router-bridge: Do not panic when serializing or deserializing to interact with deno-core
The router bridge used to panic under certain circumstances, one of them being when deserialization fails.
Gary has unfortunately found that the hard way, when querying an (unknown) introspection query against the router.
It turns out introspection queries return an empty query plan, because there is effectively not much to query downstream. We however thought the root node of a query plan was mandatory, which ended up in a panic on the plan() call.
This PR follows up on the federation counterpart: https://github.com/apollographql/federation/pull/1321
Federation PR TLDR: We now have one more layer of Result, indicating whether an …

fix: Introspection query panics

---

apollo-router-core/src/query_planner/mod.rs
apollo-router-core/src/query_planner/router_bridge_query_planner.rs
apollo-router/src/apollo_router.rs
licenses.html

the [telemetry ADR](https://github.com/apollographql/router/blob/main/adr/telemetry.md) specifies that we set skip_all on `#[tracing::instrument]` to avoid serializing arguments on every call

add the missing skip_all on instrument attributes

---

apollo-router-core/src/query_planner/mod.rs
apollo-router/src/http_subgraph.rs
apollo-router/src/warp_http_server_factory.rs

this PR puts light on the expensive operations of the router, it provides some context on the performance related PRs I sent recently. As an example, for the perf test currently used in CI, there are 5 subgraph responses, and here is a typical run:
entire query: 11.1ms
http-subgraph-request: 9.3ms = 2.01ms + 1.79ms + 1.85ms + 1.77ms + 1.88ms
=> time spent waiting on the subgraphs: 9.3ms
=> time spent by the router: 1.8ms
query_parsing (cached): 23μs
make_variables: 124μs = 6μs + 30μs + 26μs + 28μs + 34μs
aggregate_response_data: 175μs = 109μs + 10μs + 9μs + 9μs + 38μs
parse_subgraph_response: 414μs = 209μs + 20μs + 17μs + 18μs + 150μs
response_at_path: 60μs = 4μs + 5μs + 12μs + 21μs + 18μs
format_response: 216μs
serialize_response: 63μs
I am trying to reduce the time spent on low level …

add more spans for internal steps

---

apollo-router-core/src/naive_introspection.rs
apollo-router-core/well_known_introspection_queries/graphql_js_introspection_query_with_description.graphql

I didn't notice before but the graphql_js_introspection_query was actually an interpolated string with a ternary.
This commit:
Adds the introspection query body to the raised warning so we can track them down better
Creates two variants of the graphql_js_introspection_query with descriptions and without

fix: graphql_js_introspection_query

---

.circleci/config.yml

fixes #315
cargo-deny fetches its advisory database from 'https://github.com/rustsec/advisory-db.git.
Unfortunately CircleCI sets ssh override in ~/.gitconfig, which in turn fails the ssh authentication during git clone.
This commit disables the global override on CI before we run the compliance checks.

fix: check compliance CI fails

---

CHANGELOG.md
Cargo.lock
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
deny.toml

> An alpha or beta release is in volatile, active development. The release might not be feature-complete, and breaking API changes are possible between individual versions.
- Trace sampling [#228](https://github.com/apollographql/router/issues/228): Tracing each request can be expensive. The router now supports sampling, which allows us to only send a fraction of the received requests.
- Health check [#54](https://github.com/apollographql/router/issues/54)
- Schema parse errors [#136](https://github.com/apollographql/router/pull/136): The router wouldn't display what went wrong when parsing an invalid Schema. It now displays exactly where a the parsing error occured, and why.
- Various tracing and telemetry fixes [#237](https://github.com/apollographql/router/pull/237): The router …

release v0.1.0-alpha.3

---

apollo-router/src/trace.rs

If a configuration is updated which contains jaeger configuration, then
at some point a synchronous call to:
opentelemetry::global::set_tracer_provider()
will arise. Even though this call is made from a synchronous function,
the root context is asynchronous and it seems to cause the runtime to
mis-behave: i.e.: hang...
If we make the call from a newly spawned thread (no performance concerns
here because re-configuration is not hot code) then the problem goes
away.
fixes: #331

configs which contain jaeger config will hang the router when updated

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/tests/integration_tests.rs
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap
licenses.html

🔧 improvement: Test_span: add more powerful filtering capabilities, to remove non determinism in tests.
This PR bumps test-span to version 0.2.0 which allows us to add log level filters according to our dependencies; eg:
```rust
#[test_span(tokio::test)]
#[target(reqwest=tracing::Level::INFO)]
#[target(reqwest_tracing=tracing::Level::INFO)]
#[target(hyper::client=tracing::Level::INFO)]
```
etc.
This allows us to remove some deps logs that are non deterministic at the moment.

 improvement: Igni/test span bump

---

apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
licenses.html

To prevent accidental publishing to a package registry.
closes: #412

Cargo.toml: set publish = false in our crates

---

apollo-router-core/src/plugin.rs
apollo-router-core/src/query_planner/caching_query_planner.rs
apollo-router-core/src/query_planner/router_bridge_query_planner.rs
apollo-router-core/src/service_registry.rs
apollo-router-core/src/services/execution_service.rs
apollo-router-core/src/services/http_compat.rs
apollo-router-core/src/services/mod.rs
apollo-router-core/src/services/router_service.rs
apollo-router/src/http_server_factory.rs
apollo-router/src/reqwest_subgraph_service.rs
apollo-router/src/router_factory.rs
apollo-router/src/state_machine.rs
apollo-router/src/warp_http_server_factory.rs
apollo-router/tests/integration_tests.rs

The rationale behind this is that with the types as they were it was impossible to send a response payload of anything other than a graphql response. This would potentially cause issues for users wanting to send back specific error codes or messages for something such as auth.
The second reason is that there was some confusion around the types within the developers because sometimes a response was sent on the request side of a service and vice versa. This now is resolved with each type being used for one purpose only.
Before:
* RouterRequest
* PlannedRequest
* SubgraphRequest
* RouterResponse
Now:
* RouterRequest
* RouterResponse
* QueryPlannerRequest
* QueryPlannerResponse
* ExecutionRequest
* ExecutionResponse
* SubgraphRequest
* SubgraphResponse

Give each service its own set of request and response types.

---

docs/source/configuration.mdx

Minimal documentation to support spaceport configuration.

add documentation for spaceport

---

Cargo.lock
apollo-router-core/Cargo.toml

Iterating on avery's great work moving the rust parts of federation to a separate repository, we can now target the recently public federation-rs repository, which this commit achieves.

chore: use router bridge from federation-rs

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/apollo_telemetry.rs

This updates the router to depend on apollo-rs branch which was just
updated to main.
The test change is due to the improved GraphQL spec compliance in
apollo-rs.
closes: #454

chore: merge apollo-rs main back to branch garypen/66-usage-agent

---

apollo-router-core/src/json_ext.rs
apollo-router-core/src/query_planner/mod.rs
apollo-router-core/src/query_planner/selection.rs

Fix #451 
in the query plan's fetch nodes, for entities queries, we must create a list of
variables and paths at which they must be inserted in the final
response. In the previous version of the code, we were creating both
lists, then filtering the values depending on the query.
In the case where the entities are different types implementing the same
interface, provided by different subgraphs, we could have the
following query:
```graphql
query {
nodes(ids: ["UHJvZHVjdDox", "UmV2aWV3OjI="]) {
id
... on Product {
name
}
... on Review {
body
}
}
}
```
We would get the response
```json
[
{ "__typename": "Product", "id": "UHJvZHVjdDox"},
{"__typename": "Review", "id": "UmV2aWV3OjI="}
]
```
This would make a subquery to the products subgraph, and one to the
review subgraph.
The failing code …

filter paths with values

---

Cargo.lock
apollo-router-core/Cargo.toml

Specifically, to bring in the update which adds `validate` to `plan`:
- https://github.com/apollographql/federation-rs/pull/37

chore: Update router-bridge to latest version

---

CHANGELOG.md
Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
deny.toml
xtask/Cargo.toml

- **Apollo Studio usage reporting agent and operation-level reporting** ([PR #309](https://github.com/apollographql/router/pulls/309), [PR #420](https://github.com/apollographql/router/pulls/420))
While there are several levels of Apollo Studio integration, the initial phase of our Apollo Studio reporting focuses on operation-level reporting.
At a high-level, this will allow Apollo Studio to have visibility into some basic schema details, like graph ID and variant, and per-operation details, including:
- Overall operation latency
- The number of times the operation is executed
- [Client awareness] reporting, which leverages the `apollographql-client-*` headers to give visibility into _which clients are making which operations_.
This should enable several Apollo Studio features including …

release: v0.1.0-alpha.5

---

apollo-router/Cargo.toml

Add the "env-filter" feature to the Cargo.toml dependency.
fixes: #472

apollo-router tracing-subscriber features are missing "env-filter"

---

apollo-router-core/src/query_planner/mod.rs
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap

passing the query span explicitely as parent was messing up the traces.
Since we already have the "fetch" span wrapping everything, we should
use that one as info level query plan node

fix subfetch spans

---

docs/source/configuration.mdx

This recaptures some of the bits that I submitted too late on #445, and expands on it a bit too.  Feedback welcome.
Follows up: https://github.com/apollographql/router/pull/445
Follows up: https://github.com/apollographql/router/pull/309
Relates to: #66
Relates to: #444

docs: Spaceport docs formatting and editorial

---

apollo-router-core/src/plugin.rs
licenses.html

Quick fix to provide a better diagnostic error from the compiler. The `Deserialize` trait for the plugin's config is needed because when you're registering a plugin it uses `let plugin = $value::new(serde_json::from_value(configuration.clone())?)?;`  then I think the experience is better to directly have feedbacks from compiler on the Config trait bound instead of a weird error coming from the `register_plugin` macro.

fix(plugin): add required Deserialize trait bound on the plugin's config

---

apollo-router/src/apollo_telemetry.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-spaceport/README.md
apollo-spaceport/src/spaceport.rs
docs/source/configuration.mdx

Configure the listener to listen at 127.0.0.1 rather than 0.0.0.0 by
default.
fixes: #487

spaceport listener should be more secure by default

---

docs/source/configuration.mdx

This follows up on https://github.com/apollographql/router/pull/453 with a
pass at the documentation.

docs: Configuring headers sent to subgraphs

---

apollo-router-core/src/layers/forbid_http_get_mutations.rs
apollo-router-core/src/services/router_service.rs

This removes the need to box the forbid_http_get_mutations layer.
It took a bit of trial and error, but it seems to work, and also removes the hard requirement for BoxError.

Remove the need to box the layer for forbidding http_get_mutations.

---

apollo-router-core/src/layers/apq.rs

This will help if we move from BoxError to something else later.

Remove the explicit error type on APQ layer.

---

Cargo.lock
Cargo.toml
apollo-router/Cargo.toml
apollo-router/src/apollo_telemetry.rs
apollo-router/src/trace.rs
licenses.html

Fix #365 
At last we can remove the patch references for opentelemetry :partying_face:

update to opentelemetry 0.17

---

apollo-router-core/src/context.rs
licenses.html

resolves #476
Renamed `extensions()` and `extensions_mut()` with a prefix `lock_` to let users know they are locking the resources
Add common methods to context for extensions to avoid as much as possible to use `lock_extensions()` and `lock_extensions_mut()`

fix(context): change context methods about extensions to avoid deadlock

---

CHANGELOG.md
apollo-router/src/apollo_telemetry.rs
apollo-router/src/warp_http_server_factory.rs

When GraphQL operation names are not nececessary to execute an operation (i.e., when there is only a single operation in a GraphQL document) and the GraphQL operation is _not_ named (i.e., it is anonymous), the `operation_name` attribute on the trace spans that are associated with the request will no longer contain a single hyphen character (`-`) but will instead be an empty string.  This matches the way that these operations are represented during the GraphQL operation's life-cycle as well.
Fixes #481

fix: set `operation_name` tracing attribute to empty on unnamed, single-op requests

---

CHANGELOG.md
apollo-router-core/well_known_introspection_queries/homepage.graphql
apollo-router/resources/index.html
apollo-router/src/warp_http_server_factory.rs

Add the Studio Explorer boilerplate HTML

---

CHANGELOG.md
apollo-router/src/main.rs

This commit displays the Apollo Router version as an INFO when the router starts.

Feat: Display Apollo Router version on startup.

---

CHANGELOG.md
apollo-router-core/well_known_introspection_queries/graphql_js_introspection_query.graphql

Closes #531 
It turns out the Introspection query changed a little bit, which caused us to miss the Introspection cache.
The next studio release and this fix solve this.

Fix: Documentation missing in studio.

---

.circleci/config.yml
rust-toolchain.toml

Create `rust-toolchain.toml` with the rust version we want.
Add a better cache key to automatically invalidate the cache when upgrading rust version from rust-toolchain.

chore: add rust-toolchain.toml to have the same rust version everywhere

---

CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/lib.rs
apollo-router/src/plugins/reporting.rs
apollo-router/src/router_factory.rs

Also:
- Cleanup the SUBSCRIBER/DISPATCHER to store a Dispatch and clone
as required.
- Enable preserve_order in apollo-router to ensure that plugins
are processed in order (after Reporting)
fixes: #557

Ensure that Reporting plugin is processed ahead of other plugins

---

CHANGELOG.md
apollo-router-core/src/services/mod.rs
apollo-router-core/src/services/router_service.rs
apollo-router/tests/integration_tests.rs

Fixes #537
Our current service pipeline failed silently if a QueryPlanner or an Execution error occurred.
This commit turns them into graphql errors, so we don't miss them anymore.
We will probably follow up on this using concrete error types eventually.

Propagate errors on service operation.

---

CHANGELOG.md
apollo-router-core/src/layers/apq.rs
apollo-router-core/src/layers/ensure_query_presence.rs
apollo-router-core/src/layers/forbid_http_get_mutations.rs
apollo-router-core/src/layers/mod.rs
apollo-router-core/src/request.rs
apollo-router-core/src/services/checkpoint.rs
apollo-router-core/src/services/mod.rs
apollo-router-core/src/services/router_service.rs
apollo-router/src/router_factory.rs
apollo-router/src/warp_http_server_factory.rs
apollo-router/tests/integration_tests.rs

improvement: Introduce Checkpoint and Step mechanism.
Followup to our recent #537 investigations, we noticed Service layers were missing a straightforward way to let the service orchestrator know whether it shall make progress or bail out.
This Commit introduces `CheckpointLayer` and `CheckpointService` which take a `fn(Request) -> Step<Request, Response>` callback.
`Step` is an enum that contains two variants.
- `Step::Continue(Request)` notifies the CheckpointLayer it should resume calling downstream services.
- `Step::Return(Response)` notifies the CheckpointLayer it should "early return" the response, and not call downstream services.
Iterating on this concept we can now use this to create Layers:
- `EnsureQueryPresence` will Return with a `BAD_REQUEST` if no query is available after …

Allow for more granular error handling + refactor layers

---

Cargo.lock
apollo-router-core/Cargo.toml
apollo-router-core/src/error.rs
apollo-router-core/src/query_planner/router_bridge_query_planner.rs
apollo-router-core/src/query_planner/selection.rs
apollo-router-core/src/services/router_service.rs
apollo-router-core/src/spec/query.rs
apollo-router-core/src/spec/schema.rs
apollo-router-core/src/testdata/contract_schema.graphql
apollo-router/src/configuration/mod.rs
apollo-router/src/router_factory.rs
apollo-router/src/state_machine.rs
apollo-router/tests/fixtures/inventory.graphql
apollo-router/tests/fixtures/supergraph.graphql
apollo-router/tests/integration_tests.rs

Creating the api schema is done on parse, and blockingly calls out to deno. It should be OK because we load new schemas in the state machine and won't actually block the main request handlers.
Query shaping now operates against the api schema.
Introspection is performed against API schema on the Node side.
Fixed all the broken tests as we now require valid graphql schemas everywhere.
Related PR https://github.com/apollographql/federation-rs/pull/47
Fixes #573

Add api schema to schema.

---

Cargo.lock
apollo-router-core/Cargo.toml
apollo-router-core/src/layer.rs
apollo-router-core/src/layers/cache.rs
apollo-router-core/src/services/mod.rs
uplink/uplink.graphql

Previously concurrent cache calls would not dedup for downstream requests, this was a major downside compared to
the other cache implementations we have. Here we use a sentinel to avoid clone while also allowing dedup of
ongoing requests.
This could in future be used for subgraph response caching or even query planner caching, but for now it is a proof of concept.

Improve caching layer

---

CHANGELOG.md
Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
deny.toml
xtask/Cargo.toml

- **Request lifecycle checkpoints** ([PR #558](https://github.com/apollographql/router/pull/548) and [PR #580](https://github.com/apollographql/router/pull/548))
Checkpoints in the request pipeline now allow plugin authors (which includes us!) to check conditions during a request's lifecycle and circumvent further execution if desired.
Using `Step` return types within the checkpoint it's possible to influence what happens (including changing things like the HTTP status code, etc.).  A caching layer, for example, could return `Step::Return(response)` if a cache "hit" occurred and `Step::Continue(request)` (to allow normal processing to continue) in the event of a cache "miss".
These can be either synchronous or asynchronous.  To see examples, see:
- A [synchronous …

release: v0.1.0-alpha.8

---

CHANGELOG.md
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/reporting.rs
apollo-router/src/plugins/reporting/otlp/grpc.rs
apollo-router/src/plugins/reporting/otlp/http.rs
apollo-router/src/plugins/reporting/otlp/mod.rs

This is such a big part of the config that it's worth having.
Previously we were short circuiting the schema mechanism as there various types are reused from Otel and these do not have schema generation. 
It's possible that the schema is a little too lenient, and would allow invalid config for custom attributes or headers, but mostly it is OK.

Mostly fix json schema generation for otel config.

---

apollo-router/src/executable.rs
apollo-router/src/lib.rs
apollo-router/src/plugins/reporting.rs
apollo-router/src/reload.rs
apollo-router/src/subscriber.rs
examples/compose-your-graphql-router/src/main.rs

The "reload" layer which we added as part of the work to simplify
logging and tracing and introduce a tracing plugin, breaks the delicate
chain of downcasting which tracing and opentelemetry tracing expect to
exist.
This fix restores that chain by copying the Reload layer implementation
from tracing-subscriber into our codebase and adding support for
delegated downcasting.
I've also modified our RouterSubscriber to perform delegated downcasting
and recognise when it is being asked to downcast to itself.
I've also fixed a small bug which would have meant that tracing was not
disabled when configuration was set to turn off tracing.

Fix trace propagation across processes

---

CHANGELOG.md
apollo-router/src/warp_http_server_factory.rs

If we haven't already set a Content-Type header, then make sure that we
set one with a value of "application/json".
fixes: #636

Router should return Content-Type header

---

CHANGELOG.md
apollo-router-core/src/spec/field_type.rs
apollo-router-core/src/spec/query.rs
apollo-router-core/src/spec/schema.rs

Fix #655 
input objects were not parsed in the schema object, and output objects
were used for validation

implement input object validation

---

CHANGELOG.md
Cargo.lock
README.md
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
deny.toml
xtask/Cargo.toml

- **Header propagation configuration changes** ([PR #599](https://github.com/apollographql/router/pull/599))
Header manipulation configuration is now a core-plugin and configured at the _top-level_ of the Router's configuration file, rather than its previous location within service-level layers.  Some keys have also been renamed.  For example:
**Previous configuration**
```yaml
subgraphs:
products:
layers:
- headers_propagate:
matching:
regex: .*
```
**New configuration**
```yaml
headers:
subgraphs:
products:
- propagate:
matching: ".*"
```
- **Move Apollo plugins to top-level configuration** ([PR #623](https://github.com/apollographql/router/pull/623))
Previously plugins were all under the `plugins:` section of the YAML config.  However, these "core" plugins are now promoted to the …

release: v0.1.0-alpha.9

---

Cargo.lock
deny.toml

this is a DoS bug (by infinite loop) that only happens when parsing a
certificate containing an invalid key. The router is not using any
certificate yet so we're not affected, but we might be later if we call into untrusted subgraphs

update openssl-src to fix the openssl certificate parsing vulnerability

---

docs/source/config.json
docs/source/configuration/overview.mdx

This branch fixes broken docs builds by correcting table tags in the configuration overview article.

Remove extra table tags and remove comma from config.json

---

.gitattributes

Without this, our repository shows that it's 45% HTML in the language stats
because our licenses.html file is 600kB+.
Ref: https://github.com/github/linguist/blob/master/docs/overrides.md#using-gitattributes

Use `.gitattributes` to exclude licenses from "linguist" language stats

---

docs/source/config.json
docs/source/configuration/cors.mdx
docs/source/configuration/header-propagation.mdx
docs/source/configuration/opentelemetry.mdx
docs/source/configuration/overview.mdx
docs/source/configuration/spaceport.mdx
docs/source/managed-federation/setup.mdx
examples/async-auth/src/allow_client_id_from_file.rs
examples/context/src/main.rs
examples/forbid-anonymous-operations/src/forbid_anonymous_operations.rs
examples/forbid-anonymous-operations/src/main.rs
examples/hello-world/src/main.rs
examples/jwt-auth/src/jwt.rs
examples/jwt-auth/src/main.rs
examples/status-code-propagation/src/main.rs
examples/status-code-propagation/src/propagate_status_code.rs

This uses `router.yaml` in all locations, rather than other variations.
This commit also introduces a TODO for something that came to mind while I
was reading the docs (unexplained context for the configuration file itself)
and also renames the `open-telemetry.mdx` to `opentelemetry.mdx` for
consistency with other locations on our site (and arguably, the name of the
product anyhow).

docs: configuration file consistency

---

CHANGELOG.md
apollo-router/src/warp_http_server_factory.rs

fix: take the current path of the http request and put it into the router request #699

---

CHANGELOG.md
apollo-router-core/src/plugins/headers.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap

Previously `rename` and `default` values were required (even though they were correctly not flagged as required un the json schema).
The following will now work:
```yaml
headers:
all:
- propagate:
named: test
```
The fix is to mark the fields as defaulted.

Fix Header propagation by `name` only fixed

---

CHANGELOG.md
Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
deny.toml
xtask/Cargo.toml

For more information on what's expected at this stage, please see our [release stages](https://www.apollographql.com/docs/resources/release-stages/#preview).
- **Header propagation by `name` only fixed** ([PR #709](https://github.com/apollographql/router/pull/709))
Previously `rename` and `default` values were required (even though they were correctly not flagged as required in the json schema).
The following will now work:
```yaml
headers:
all:
- propagate:
named: test
```
- **Fix OTLP hang on reload** ([PR #711](https://github.com/apollographql/router/pull/711))
Fixes hang when OTLP exporter is configured and configuration hot reloads.

release: v0.1.0-preview.0

---

.gitignore
CHANGELOG.md
apollo-router-core/src/error.rs
apollo-router-core/src/query_cache.rs
apollo-router-core/src/query_planner/mod.rs
apollo-router-core/src/query_planner/router_bridge_query_planner.rs
apollo-router-core/src/services/reqwest_subgraph_service.rs
apollo-router-core/src/spec/query.rs
apollo-router/src/apollo_telemetry.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/http_server_factory.rs
apollo-router/src/lib.rs
apollo-router/src/plugins/override_url.rs
apollo-router/src/plugins/rhai.rs
apollo-router/src/plugins/telemetry.rs
apollo-router/src/router_factory.rs
apollo-router/src/state_machine.rs
apollo-spaceport/src/server.rs
apollo-spaceport/src/spaceport.rs
examples/context/src/context_data.rs
examples/forbid-anonymous-operations/src/forbid_anonymous_operations.rs
examples/jwt-auth/src/jwt.rs
fuzz/src/lib.rs

Rust style is no capital letter at the start of a sentence and no trailing punctuation.
https://github.com/rust-lang/api-guidelines/commit/201d9036dbe8640eef6054d2d9632ea0a0532ab6

Bring log and error message style in to line with rust guidelines

---

CHANGELOG.md
apollo-router/src/plugins/telemetry.rs

fixes #719
service.name and service.namespace did default correctly in jaeger configuration, but not in OTLP.
This PR fixes this.

fix: OTLP default service.name and service.namespace

---

CHANGELOG.md
apollo-router-core/src/services/router_service.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-2.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-3.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-4.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_grpc-2.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_grpc.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_http-2.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_http.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_tls_config.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__supergraph_config_serde.snap
apollo-router/src/router_factory.rs

Fix #564 
we might want to disable schema introspection on production systems, so here's an option in the yaml configuration for that

Add an option to deactivate introspection

---

CHANGELOG.md
apollo-router-core/src/json_ext.rs
apollo-router-core/src/query_planner/mod.rs
apollo-router-core/src/query_planner/selection.rs

Fix #298 
Fix #744
for federated subgraph queries, we encountered multiple issues:
- if we got a null entity from a previous call, selecting data from it
would return an error and fail the subgraph request. This is invalid,
because for a request like `query { topProducts { reviews { body } } }`
and a products subgraph returning `[ {"upc": 0}, null, { "upc": 2} ]`,
we should do a query to the reviews subgraph for the products 0 and 2
- if the list of representations to query a subgraph is empty, we were
still doing a HTTP request expecting an empty result
this PR fixes those issues by ignoring selection errors when
creating variables, then canceling the subgraph request if the
representations array is empty

relax variables selection for subgraph queries

---

CHANGELOG.md
apollo-router-core/src/layers/deduplication.rs
apollo-router-core/src/plugins/mod.rs
apollo-router-core/src/plugins/traffic_shaping.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/router_factory.rs
docs/source/config.json
docs/source/configuration/traffic-shaping.mdx
router.yaml

The experimental `traffic_shaping` plugin will be a central location where we can add things such as rate limiting and retry.
```yaml
plugins:
experimental.traffic_shaping:
all:
dedup: true # Enable dedup for all subgraphs.
subgraphs: 
products:
dedup: false # Disable dedup for products.
```

Move dedup to a traffic_shaping plugin

---

CHANGELOG.md
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
docs/source/configuration/cors.mdx
examples/async-auth/router.yaml
examples/context/router.yaml
examples/embedded/router.yaml
examples/forbid-anonymous-operations/router.yaml
examples/forbid_mutations/router.yaml
examples/hello-world/router.yaml
examples/jwt-auth/router.yaml

Fixes :#40
The Router now allows only the `https://studio.apollographql.com` origin by default, instead of any origin.

chore: CORS default Configuration

---

CHANGELOG.md
README.md
apollo-router/src/executable.rs
docs/source/configuration/overview.mdx
docs/source/migrating-from-gateway.mdx

fixes #766
The router now supports the HOT_RELOAD environment variable to watch for config and schema changes.

feat: Hot reload

---

CHANGELOG.md
Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
deny.toml
uplink/Cargo.toml
xtask/Cargo.toml

- **CORS default Configuration** ([#40](https://github.com/apollographql/router/issues/40))
The Router will allow only the https://studio.apollographql.com origin by default, instead of any origin.
This behavior can still be tweaked in the [YAML configuration](https://www.apollographql.com/docs/router/configuration/cors)
- **Hot reload flag** ([766](https://github.com/apollographql/router/issues/766))
The `--watch` (or `-w`) flag that enables hot reload was renamed to `--hr` or `--hot-reload`
- **Hot reload via en environment variable** ([766](https://github.com/apollographql/router/issues/766))
You can now use the `ROUTER_HOT_RELOAD=true` environment variable to have the router watch for configuration and schema changes and automatically reload.
- **Container images are now available** …

release: v0.1.0-preview.2

---

.gitignore
router.yaml

Prevent accidental commits of router.yaml in the root directory by adding to .gitignore.

Remove router.yaml.

---

dockerfiles/Dockerfile.router

Found bug in dockerfile during release process. The dockerfile copied
the default configuration from the wrong directory. By bad luck, it
found a configuration in the specified location, which meant the build
succeeded, but that config didn't work in docker (wrong listen address
for router).
This fix ensures that the correct config file is included in the docker
image.
We've re-issued the fixed docker files manually.

dockerfile example and publish on release to github (#764) (follow-up)

---

CHANGELOG.md
apollo-router-benchmarks/benches/basic_composition.rs
apollo-router-core/src/error.rs
apollo-router-core/src/plugin_utils/mock/mod.rs
apollo-router-core/src/plugin_utils/mock/subgraph.rs
apollo-router-core/src/plugin_utils/mod.rs
apollo-router-core/src/plugins/include_subgraph_errors.rs
apollo-router-core/src/plugins/mod.rs
apollo-router-core/src/query_planner/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
docs/source/config.json
docs/source/configuration/subgraph-error-inclusion.mdx

This works in a similar fashion to the headers plugin. You can configure
all to apply to all subgraphs and/or a subgraphs hashmap which overrides
the all specification on a per subgraph basis.
I've also migrated some of the benchmark mock code into
apollo-router-core since it's helpful for testing this kind of thing and
fixed the benchmarks (with help from geoffroy and jeremy).
fixes: #743

introduce new experimental plugin to allow subgraph error responses

---

.circleci/config.yml

two changes to CI cache keys:
- the checksum of Cargo.toml is not very useful, since we rarely change
it, and any change would appear in the Cargo.lock anyway
- if the cache key uses <prefix>-<branch>-<cargo.lock>, the first build
on any branch will restore the most recent cache matching <prefix>,
which will probably be a cache saved by another branch with possibly a
different set of dependencies. If instead we use
<prefix>-<Cargo.lock>-<branch>, we know that any PR that does not change
dependencies will reuse the right dependencies cache, independently from
the branch, and any change to Cargo.lock will instead reuse the most
recent cache

the lockfile should be present before the branch in the cache key

---

Cargo.lock
apollo-router-core/Cargo.toml
apollo-router-core/src/services/tower_subgraph_service.rs
examples/telemetry/README.md
licenses.html

hyper clients don't support TLS by default. We need TLS support to talk
to subgraphs securely. Use hyper-rustls crate and create a hyper client
capable of talking https or http.
(I have manually tested against https and http subgraphs.)

opensslectomy (follow-up)

---

apollo-router-core/src/services/mod.rs
apollo-router/src/warp_http_server_factory.rs

Deletion of `ResponseBody::RawString` because we don't use it and it's a duplicate of `ResponseBody::RawJSON(serde_json::Value)` with a `Value::String`

fix: delete useless ResponseBody::RawString

---

NEXT_CHANGELOG.md
apollo-router-core/src/json_ext.rs

fix #812 
the Value::from_path method is used to generate a json value by
inserting an object at a specific path, so the value has a certain
shape.
If we have { "c": 1 } and want to generate { "a": { "b": { "c": 1 } } },
we will call from_path with the path "/a/b". If we have a path in an
array element, it will contain the index, as follows: "/a/1/b".
In the case of federated queries, for each of the representations, we
generate a path at which the response will be inserted. But in the case
we could not select any representation, we avoid the subgraph query
(since it would return nothing) and return an empty value. This empty
value cannot be null, it has to match the expected shape (otherwise
we'll run into response formatting issues), so we use Value::from_path
with the current path and …

do not try to generate a JSON value on a "flatten" path

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router-core/Cargo.toml

chore: update router-bridge
Now that Federation 2.0 is available, we have updated the query planner to use the latest release (@apollo/query-planner v2.0.0).

Bump router-bridge dependency

---

CHANGELOG.md
Cargo.lock
NEXT_CHANGELOG.md
RELEASE_CHECKLIST.md
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
deny.toml
licenses.html
uplink/Cargo.toml
xtask/Cargo.toml

- **Telemetry simplification** [PR #782](https://github.com/apollographql/router/pull/782)
Telemetry configuration has been reworked to focus exporters rather than OpenTelemetry. Users can focus on what they are trying to integrate with rather than the fact that OpenTelemetry is used in the Apollo Router under the hood.
```yaml
telemetry:
apollo:
endpoint:
apollo_graph_ref:
apollo_key:
metrics:
prometheus:
enabled: true
tracing:
propagation:
zipkin: true
datadog: false
trace_context: false
jaeger: false
baggage: false
otlp:
endpoint: default
protocol: grpc
http:
..
grpc:
..
zipkin:
agent:
endpoint: default
jaeger:
agent:
endpoint: default
datadog:
endpoint: default
```
- **Datadog support** [PR #782](https://github.com/apollographql/router/pull/782)
Datadog support has been added via …

release: v0.1.0-preview.4

---

apollo-router/src/configuration/mod.rs
apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs

This fixes an issue where CORS wouldn't recognize the Apollo studio origin.
It also changes a tracing::info!() log into a debug!() one, since it will often happen and is pretty noisy.

fix: axum: CORS Studio fix.

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/router_factory.rs
apollo-router/src/testdata/invalid_supergraph.graphql

The root cause is that tracing providers MUST be flushed before drop. otherwise they hang. This is really nasty, but the fix needs to happen in Otel.
Flushing will happen automagically if a provider is set as the global for otel.
In the case of a plugin after the otel plugin failing to start up correctly, or even one of the subsequent methods inside the otel plugin fails then the provider is not set as the global and we must flush it.
Flushing must occur in a separate thread.
Flush will now happen when a telemetry plugin is dropped.

Fix telemetry shutdown in the case of a failed config update.

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/tracing/datadog.rs

Fix #851 
due to the way the endpoint URL is constructed in opentelemetry-datadog
( https://github.com/open-telemetry/opentelemetry-rust/issues/782 ), we
cannot set the agent endpoint to a URL with a trailing slash

remove trailing / in the datadog agent endpoint

---

apollo-router-core/src/request.rs
apollo-router/src/axum_http_server_factory.rs

In a get query, the operation name was extracted as if it had been a JSON payload.
We misstook this bug for an instrument related issue (we thought instrumentation had a bug when it wouldnt display the operation name).
this PR adds http get and http post tests to make sure query and operation name will always be extracted correctly from the http server.

fix: extract operation name correctly from a get query.

---

CHANGELOG.md
Cargo.lock
NEXT_CHANGELOG.md
RELEASE_CHECKLIST.md
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
deny.toml
docs/source/containerization/docker.mdx
uplink/Cargo.toml
xtask/Cargo.toml

[Helm](https://helm.sh) support provided by @damienpontifex.
The router will make a best effort to give line precise error reporting if the configuration was invalid.
```yaml
1. /telemetry/tracing/trace_config/sampler
telemetry:
tracing:
trace_config:
service_name: router3
sampler: "0.3"
^----- "0.3" is not valid under any of the given schemas
```
Added an install script that will automatically download and unzip the router into the local directory.
For more info see the quickstart documentation.
The query planner has been reworked to make sure concurrent plan requests will be dispatched to the relevant requester.
The telemetry plugin will now Drop cleanly when the Router service stack fails to build.
Extensions are now propagated following the configuration of the …

release: v0.1.0-preview.5

---

NEXT_CHANGELOG.md
apollo-router-core/src/query_planner/mod.rs
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/plugins/override_url.rs
apollo-router/tests/integration_tests.rs

fixes #865
A regression happened during our switch to Axum which would mark incoming POST requests as GET, thus triggering our forbid_http_mutations layer, and preventing mutations on the router.
This PR fixes this, and introduces some tests. More integration or axum oriented tests should follow.
When writing a unit test to assert subgraph requests are POST, I noticed the test would never fail. this is because withf only acts as a request router, and panicking (or in our case asserting) within wouldnt cause the router to fail.
This commit rewrites a couple of subgraph tests so they properly notify whether they completed successfully or failed.

fix: Correctly flag incoming POST requests. 

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs

fixes #883
Our axum rework caused the healthckeck route `/.well-known/apollo/server-health` to change. The route is now restored.

fix: Restore the health check route

---

CHANGELOG.md
Cargo.lock
NEXT_CHANGELOG.md
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
deny.toml
docs/source/containerization/docker.mdx
uplink/Cargo.toml
xtask/Cargo.toml

Axum rework caused the healthckeck route `/.well-known/apollo/server-health` to change. The route is now restored.
A regression happened during our recent switch to Axum that would propagate incoming POST requests as GET requests. Fixed and added regression tests.

release: v0.1.0-preview.6

---

.circleci/config.yml

Bump the  cache version because OSX builds are currently failing.
Skipped v4 and v5 because we also used them in other branches recently

Bump cache version

---

docs/source/config.json

This updates the sidebar docs URL to use the real path for the new location of these docs, rather than continuing to rely on a redirect — as supplied by #881. 
This follows-up on #782, which probably should have updated this originally when the page itself was moved to `apollo-telemetry` from `spaceport`.

docs: use true path of "apollo telemetry" in sidebar config

---

.circleci/config.yml

saving and restoring build artefacts is very expensive and significantly
increases CI times. This PR removes cargo-sweep and the target/ directory
cache, and only caches .cargo and the node_modules directory in tests,
since those will be small enough and take some time to download

remove build file caches

---

.circleci/config.yml

The new resource class for macOS instances introduced in November offer faster CPU options and could are expected to reduce our build times.
Ref: https://discuss.circleci.com/t/coming-soon-gen2-macos-resources/41886
Ref: https://circleci.com/docs/2.0/configuration-reference/#macos-executor
Fixes: https://github.com/apollographql/router/issues/903

chore: Update to use new CircleCI Gen2 Mac resources

---

apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/router_factory.rs

The test wasn't using the multi_thread executor, so eventually it would
trip over the bug in opentelemetry which we've hit in the past where the
runtime would hang for not fully understood reasons.
see: https://github.com/open-telemetry/opentelemetry-rust/issues/536
Using the multi_thread executor is the recommended work-around.
I've also remove the redundant thread spawn from the telemetry Drop
implementation, since I don't think it's required as well as the
spawn_blocking() call.
I've run this test in a tight loop for a couple of hours (on my M1
laptop) with no issues.

use the multi_thread executor to run the telemetry hang test

---

Cargo.lock
apollo-router/Cargo.toml

The author has released a new version (0.16.0) which fixes the issues in
0.15.2. Time to update.
fixes: #874

no need to keep jsonschema pinned at 0.15.1

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
docs/source/managed-federation/client awareness.mdx

Fix #127
The client awareness headers can be used by browser based applications,
and as such should be part of the headers allowed by CORS configuration.
This PR also adds a doc page about client awareness and indicates how to override the headers

add client awareness headers to CORS default configuration

---

NEXT_CHANGELOG.md
apollo-router-core/src/spec/query.rs
docker-compose-federation2.yml
fuzz/fuzz_targets/router.rs
fuzz/src/lib.rs
fuzz/supergraph-fed2.graphql
fuzz/supergraph.graphql

close #930 
I also added support of fed2 for fuzz targets, because we used fed1 before, it's better to target fed2.

fix unskipped fields at the root of the selection set #930

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/snapshots/apollo_router__axum_http_server_factory__tests__display_home_page.snap
apollo-router/src/snapshots/apollo_router__axum_http_server_factory__tests__health_check.snap
apollo-router/src/snapshots/apollo_router__axum_http_server_factory__tests__it_extracts_query_and_operation_name_on_get_requests.snap
apollo-router/src/snapshots/apollo_router__axum_http_server_factory__tests__response.snap

Telemetry spans where previously being created for the healthcheck requests which was creating noisy telemetry for users.

Prevent spans from being created for healthcheck requests.

---

NEXT_CHANGELOG.md
apollo-router-core/src/query_cache.rs
apollo-router-core/src/query_planner/mod.rs
apollo-router-core/src/spec/query.rs
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/tests/integration_tests.rs
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap

close #909 
I added `SpanKind` and `SpanStatusCode` to be compliant with the otel spec and also follow the same rules than the Gateway. 
I also added a `.instrument(...)` to be able to see the parsing of the query in our main trace, before it was considered as a standalone span because it's spawned with a `spawn_blocking`

add otel.kind and otel.status_code to follow otel spec

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/snapshots/apollo_router__axum_http_server_factory__tests__it_display_home_page.snap
apollo-router/src/snapshots/apollo_router__axum_http_server_factory__tests__it_extracts_query_and_operation_name_on_get_requests.snap
apollo-router/src/snapshots/apollo_router__axum_http_server_factory__tests__response.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap

Previously in test-span before the fix introduced here https://github.com/apollographql/test-span/pull/13 we were filtering too aggressively. So if we wanted to snapshot all `DEBUG` level if we encountered a `TRACE` span which had `DEBUG` children then these children were not snapshotted. It's now fixed and it's more consistent with what we could have/see in jaeger. 
close #942

upgrade test-span and then display more children spans in snapshots

---

NEXT_CHANGELOG.md
dockerfiles/Dockerfile.router

Users can now use `CONFIGURATION_PATH` to override this in docker compose/kubernetes config.

Dockerfile now specifies configuration path via env variable. 

---

apollo-router-core/Cargo.toml
apollo-router-core/src/services/tower_subgraph_service.rs

Configure the hyper-rustls crate to support both http1 and http2. Modify
the creation of the connector to enable both http1 and http2.
fixes: #952 
Note: It would be nice to add some tests to support this, but I can't think of a good way to do this right now.

add support for http2 to subgraph requests

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/config.rs
docs/source/configuration/tracing.mdx

for a better out of the box experience, the router should set a default
service name in opentelemetry, that can be overriden by the
configuration file or the OTEL_SERVICE_NAME environment variable
(otherwise the service name is set to `service_unknown` in jaeger or `OTLPRESOURCENOSERVICENAME` in zipkin)

set the service name if not specified in config or environment

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_bad_type.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_errors_after_first_field.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_inline_sequence.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_sequence.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__yaml__test__test.snap
apollo-router/src/configuration/yaml.rs

close #921 
What we had before for this kind of bad configuration:
```yaml
server:
listen: 127.0.0.1:4000
bad: "donotwork"
another_one: true
```
+ Previous report:
```
configuration had errors: 
1. /server
server:
listen: 127.0.0.1:4000
^-----> Additional properties are not allowed ('bad', 'another_one' were unexpected)
```
+ Here is the new report:
```
configuration had errors: 
1. /server
server:
┌   # The socket address and port to listen on
|   # Defaults to 127.0.0.1:4000
|   listen: 127.0.0.1:4000
|   bad: "donotwork"
|   another_one: true
└-----> Additional properties are not allowed ('bad', 'another_one' were unexpected)
```
We had a bug previously that only highlighted the first field of the map with unknown properties.

fix: improve the configuration error report

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/otlp.rs
apollo-router/src/plugins/telemetry/tracing/datadog.rs

endpoint configuration for Datadog and OTLP take a URL as argument, but
it is easy to make the mistake of setting a value of the format
"host:port". In that case, the URL parser will happily understand that
as "host" scheme and "port" path.
This PR instead transforms it to "http://host:port"

accept endpoint URL without scheme for telemetry

---

apollo-router-core/src/services/mod.rs

QueryPlan doesn't have a default implementation anymore, since any query plan will at least have an optional root and usage reporting.
This commit fixes the compile issue.

fix: Use QueryPlan::fake_new.

---

NEXT_CHANGELOG.md
apollo-router/src/executable.rs
dockerfiles/Dockerfile.router
docs/source/configuration/overview.mdx
docs/source/migrating-from-gateway.mdx

* `RUST_LOG` -> `APOLLO_ROUTER_LOG`
* `CONFIGURATION_PATH` -> `APOLLO_ROUTER_CONFIG_PATH`
* `SUPERGRAPH_PATH` -> `APOLLO_ROUTER_SUPERGRAPH_PATH`
* `ROUTER_HOT_RELOAD` -> `APOLLO_ROUTER_HOT_RELOAD`
* `APOLLO_SCHEMA_CONFIG_DELIVERY_ENDPOINT` -> `APOLLO_UPLINK_URL`
* `APOLLO_SCHEMA_POLL_INTERVAL`-> `APOLLO_UPLINK_POLL_INTERVAL`
Cmd line flag changes:
* `--apollo-schema-config-delivery-endpoint` -> `--apollo-uplink-url`
* `--apollo-schema-poll-interval` -> `--apollo-uplink-poll-interval`
Notes:
I checked the logic of tracing subscriber with respect to https://github.com/tokio-rs/tracing/issues/735#issuecomment-948076439 and I believe we are safe.
The issue is around `tracing_subscriber::fmt::init()` which has some logic that deals with `RUST_LOG`.
However, we are not currently using this, and …

Environment variables have been renamed for consistency:

---

NEXT_CHANGELOG.md
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
deny.toml

Since `Elastic-2.0` SPDX identifiers now exist in the [SPDX License List],
we can use them in place of the `license-file` that we had been using
previously, along with our license clarifications in our `deny.toml`
configuration.
[SPDX License List]: https://spdx.org/licenses/
Closes: https://github.com/apollographql/router/issues/418

chore: Update license identifiers to use `Elastic-2.0` SPDX identifier

---

apollo-router-core/src/spec/fragments.rs
apollo-router-core/src/spec/query.rs
apollo-router-core/src/spec/selection.rs

Impose a restriction on the amount of recursion that can be performed
during selection processing.

impose recursion limits on selection processing

---

Cargo.lock
examples/hello-world/Cargo.toml
examples/hello-world/router.yaml
examples/hello-world/src/hello_world.rs

Log/Print the supplied name configuration when router_service callback is
invoked.
Also: add a test which uses the new PluginTestHarness and prints
a configuration based message to stdout when the router_service callback
is invoked.
fixes: #961

Improve the hello world example

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/executable.rs
apollo-router/tests/integration_tests.rs

Previously panics would get swallowed. Now they are output to the logs.
Setting `RUST_BACKTRACE=1` or `RUST_BACKTRACE=full` enables the full backtrace to also be logged.
A warning is output to the logs on startup if `RUST_BACKTRACE` is set.

Panics now output to logs

---

NEXT_CHANGELOG.md
apollo-router/src/executable.rs

if we use std::env!, the router will not xompile when the environment variable is not present:
error: environment variable `RUST_BACKTRACE` not defined                                                               
--> apollo-router/src/executable.rs:283:25                                                                          
|                                                                                                                  
283 |     let backtrace_env = std::env!("RUST_BACKTRACE");                                                              
|                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                              
| …

do not require the RUST_BACKTRACE environment variable at compilation time

---

CHANGELOG.md
Cargo.lock
NEXT_CHANGELOG.md
RELEASE_CHECKLIST.md
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
docs/source/containerization/docker.mdx
docs/source/federation-version-support.mdx
uplink/Cargo.toml
xtask/Cargo.toml

Environment variables have been renamed for consistency:
* `RUST_LOG` -> `APOLLO_ROUTER_LOG`
* `CONFIGURATION_PATH` -> `APOLLO_ROUTER_CONFIG_PATH`
* `SUPERGRAPH_PATH` -> `APOLLO_ROUTER_SUPERGRAPH_PATH`
* `ROUTER_HOT_RELOAD` -> `APOLLO_ROUTER_HOT_RELOAD`
* `APOLLO_SCHEMA_CONFIG_DELIVERY_ENDPOINT` -> `APOLLO_UPLINK_ENDPOINTS`
* `APOLLO_SCHEMA_POLL_INTERVAL`-> `APOLLO_UPLINK_INTERVAL`
In addition, the following command line flags have changed:
* `--apollo-schema-config-delivery-endpoint` -> `--apollo-uplink-url`
* `--apollo-schema-poll-interval` -> `--apollo-uplink-poll-interval`
You are now able to declare your own GraphQL endpoint in the config like this:
```yaml
server:
listen: 127.0.0.1:4000
endpoint: /graphql
```
But we also deleted the `/graphql` endpoint by default, you will know have …

release: v0.9.0-rc.0

---

NEXT_CHANGELOG.md
docs/source/containerization/kubernetes.mdx
helm/chart/router/Chart.yaml
helm/chart/router/templates/deployment.yaml

and add support for prometheus metrics to our helm chart
I deployed a release of the router into our testing cluster using helm and ensured that I could read the prometheus statistics easily from the deployed router.
fixes: #958

improve our kubernetes example documentation

---

NEXT_CHANGELOG.md
apollo-router/Cargo.toml

fix #1017 
using the blocking reqwest client feature of opentelemetry-zipkin was
pankicing with this message: "Cannot drop a runtime in a context where
blocking is not allowed. This happens when a runtime is dropped from
within an asynchronous context."

fix a panic in zipkin telemetry configuration

---

NEXT_CHANGELOG.md
docs/source/configuration/overview.mdx

add documentation for the endpoint configuration in server

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/metrics/apollo.rs

When studio reporting is enabled the user is notified in the router logs that data is sent to Apollo.

Add usage reporting information to startup of apollo metrics.

---

docs/source/quickstart.mdx

This allows us to own the host that is used for installing the router and
mitigate outages if GitHub goes down.  For now, the URL just redirects to
the previous URL, but in the future we could have it try other locations in
the event of an outage.
It also looks much nicer!
Closes #962

use vanity URL for download instructions

---

docs/source/config.json

We have graduated to the GA release and are no longer in "preview"!

docs: Remove "(preview)" from docset switcher button

---

README.md

This badge is no longer necessary and always showing as failed right now.

Remove Netlify Badge from README

---

docs/source/configuration/header-propagation.mdx
docs/source/configuration/overview.mdx
docs/source/customizations/native.mdx
docs/source/migrating-from-gateway.mdx

(These aren't full-on broken, just the anchor part due to the previous docs PR)
Closes https://github.com/apollographql/router/issues/1051

Fix some broken links

---

docs/source/configuration/header-propagation.mdx

Along with a bit of explanatory text about rule ordering.
fixes: #1055

Add additional example to header propagation docs

---

NEXT_CHANGELOG.md
docs/source/configuration/metrics.mdx

doc: add metrics we have using Prometheus

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/configuration/testdata/tracing_apollo.router.yaml
apollo-router/src/executable.rs
apollo-router/src/plugins/telemetry/apollo.rs
docs/source/configuration/apollo-telemetry.mdx
docs/source/configuration/overview.mdx

Remove command line args `--apollo-key` and `--apollo-graph-ref`
Remove setting from telemetry.

APOLLO_KEY and APOLLO_GRAPH_REF can only be set via env variable.

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router-core/Cargo.toml

Bump apollo-parser. 
Hotfix for #1065 that would infinitely recurse when `\` is used in a `StringValue` as a first char.

Bump apollo-parser

---

docs/source/config.json
docs/source/configuration/csrf.mdx

Fixes https://github.com/apollographql/router/issues/1039
The plugin was added in https://github.com/apollographql/router/pull/1006
Docs are imported from [Apollo Server’s own docs](https://www.apollographql.com/docs/apollo-server/security/cors/#preventing-cross-site-request-forgery-csrf) and adapted.

Add docs for the CSRF prevention plugin

---

CHANGELOG.md
Cargo.lock
NEXT_CHANGELOG.md
RELEASE_CHECKLIST.md
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
docs/source/federation-version-support.mdx
helm/chart/router/Chart.yaml
uplink/Cargo.toml
xtask/Cargo.toml

Using these command lime options exposes sensitive data in the process list. Setting via environment variables is now the only way that these can be set.
In addition these setting have also been removed from the telemetry configuration in yaml.
The Schemars 0.8.9 causes compile errors due to it validating default types. Pin the version to 0.8.8.
See issue [#1074](https://github.com/apollographql/router/issues/1074)
During parsing of queries the use of `"` in a parameter value caused infinite recursion. This preliminary fix will be revisited shortly.
Add the list of metrics you can have using Prometheus

release v0.9.1

---

NEXT_CHANGELOG.md
apollo-router-core/src/context.rs
docs/source/customizations/native.mdx
examples/context/src/context_data.rs
examples/status-code-propagation/src/propagate_status_code.rs

Remove the `default` parameter and require upserted values to implement
Default.

modify Context::upsert()

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/configuration/testdata/tracing_apollo_env.router.yaml
apollo-router/src/configuration/testdata/tracing_datadog_env.router.yaml
apollo-router/src/configuration/testdata/tracing_jaeger_collector_env.router.yaml
apollo-router/src/configuration/testdata/tracing_otlp_grpc_basic_env.router.yaml
apollo-router/src/configuration/testdata/zipkin-url_env.router.yaml
apollo-router/src/plugins/telemetry/apollo.rs
apollo-router/src/plugins/telemetry/otlp.rs
apollo-router/src/plugins/telemetry/tracing/datadog.rs
apollo-router/src/plugins/telemetry/tracing/jaeger.rs

fix(configuration): let the user use the environment variable expansion

---

apollo-router-core/src/services/tower_subgraph_service.rs

Currently, we build a response from only the body of the subgraph
response. This change ensures that the parts from the subgraph response
(headers, status_code, version) are also preserved in the resulting
response from the router.
fixes: #1094

Preserve the parts from our subgraph response use in our response

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/plugins/telemetry/metrics/apollo.rs
apollo-router/src/plugins/telemetry/metrics/apollo/studio.rs
licenses.html

65536 is not a useful batch size because we will rarely reach it, and
with a 10s timeout, we need to wait for at least 10s to have a first
message sent to studio, which does not make a great local development
experience

 aggregate usage reports as they come and flush every 5 seconds to spaceport

---

NEXT_CHANGELOG.md
apollo-spaceport/Cargo.toml
apollo-spaceport/src/server.rs

follow up on #1066 
apollo-router is already handling report aggregation and sends the
report every 5s. Now spaceport will put the incoming reports in a
bounded queue and send them in order, with backpressure

remove the batching and timeout from spaceport

---

NEXT_CHANGELOG.md
dockerfiles/diy/build_docker_image.sh
dockerfiles/diy/dockerfiles/Dockerfile.release
dockerfiles/diy/dockerfiles/Dockerfile.repo
docs/source/containerization/docker.mdx

We build docker images when we release the router, but it would be nice
to have a mechanism which supported:
- building from source to arbitrary commit or tag
- building from released tarballs
This is now provided by build_docker_image.sh. If you don't like the
final image used (distroless), then change that image to whichever image
you prefer.
Note: You can only pull from GH branches which are known in the GH router repo. We could probably add some code to make the clone happen from local (checked out) repos if that's required.

Add support for building "diy" docker images on demand

---

CHANGELOG.md
Cargo.lock
NEXT_CHANGELOG.md
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-spaceport/Cargo.toml
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
docs/source/federation-version-support.mdx
helm/chart/router/Chart.yaml
uplink/Cargo.toml
xtask/Cargo.toml

Removes the `default` parameter and requires inserted values to implement `Default`.
The build_docker_image.sh script is now provided as a working example of how to build docker images from our GH release tarballs or from a commit hash/tag against the router repo.
When `__typename` is used at the top of the query in combination with other fields it was not returned in the output.
Do not put .exe for Windows in the name of the tarball when releasing new version
The metrics plugin was allocating chunks of usage reports to aggregate them right after, this was replaced by a streaming loop. The interval for sending the reports to spaceport was reduced from 10s to 5s.
Adds the ability to use environment variable expansion for the configuration of agent/collector endpoint for Jaeger, OTLP, …

release: v0.9.2

---

Cargo.lock
apollo-router-core/Cargo.toml

fixes #1096
The usage reporting functions have been refactored into the apollo-utils repository.

Use the new router bridge that generates usage reporting from the apollo_utils package

---

Cargo.lock
licenses.html
xtask/Cargo.toml
xtask/src/commands/package/mod.rs

we relied on its TARGET_ARCH and TARGET_PLATFORM values that were
removed in version 3
this replaces #900 where renovate tries again and again to update to an incompatible platforms version. We could also migrate to the [sysinfo](https://docs.rs/sysinfo) crate once it supports printing the OS type

remove the platforms crate

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/improvement.md

This will cause the `raised by user` label by default, in addition to `triage`.

chore: update github templates

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
examples/async-auth/Cargo.toml
examples/hello-world/Cargo.toml
examples/jwt-auth/Cargo.toml
examples/status-code-propagation/Cargo.toml
licenses.html

Fixes #1074
The Schemars 0.8.9 caused compile errors due to it validating default types.
This change has however been rolled back upstream.
We can now safely depend on schemars 0.8.10.

maintenance: Unpin schemars version.

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router-core/Cargo.toml
licenses.html

Moka has a dependency on Quanta which had an issue with AMD hardware. This is now fixed via [Moka-#119](https://github.com/moka-rs/moka/issues/119).

maintenance: Bump Moka to fix panics on AMD hardware.

---

NEXT_CHANGELOG.md
apollo-router-core/src/query_planner/mod.rs
apollo-router-core/src/services/tower_subgraph_service.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap

feat: add more information in spans

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
docs/source/configuration/health-checks.mdx

With this change, we can customize the health check path, 
By default is working as now, with the /.well-known/apollo/server-health

Allows to set a custom health check path

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs

If we do not create this `SocketAddr` it will use the default one and then listen on the same port than another test. Which means sometimes it will work, sometimes not because the port has already been used.

tests(axum): create SocketAddr to fix flappy test

---

Cargo.lock
examples/rhai-surrogate-cache-key/Cargo.toml
examples/rhai-surrogate-cache-key/src/main.rs

somehow the CI failed on https://github.com/apollographql/router/commit/8e0aedaf415b7a87f5e76bc33384f665fe346ca5 while it was ok on the PR :thinking:

fix the test in rhai surrogate cache key example

---

docs/source/configuration/csrf.mdx

… since plugins are indeed only invoked for GraphQL requests.
Fixes https://github.com/apollographql/router/issues/1081

docs: CSRF prevention is not applied to landing pages & health checks

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/configuration/mod.rs

Tower validates supplied router configuration and `asserts` that it is
valid to use. If it isn't, this results in a runtime panic which is not
a nice user experience.
This set of changes checks the CORS parameters before passing them to
tower and results in a manageable error if mis-configuration is
detected. It would be better if this was fixed in tower, but I imagine
there is a good reason to have the asserts. I'll file a ticket there
anyway, but in the meantime we can just have this function in our code.

CORS mis-configuration shouldn't cause a router panic

---

NEXT_CHANGELOG.md
apollo-router/src/router_factory.rs
apollo-router/src/services/mod.rs
apollo-router/src/services/subgraph_service.rs
apollo-router/src/services/tower_subgraph_service.rs
apollo-router/tests/integration_tests.rs
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap
examples/embedded/src/main.rs

close #1183 
+ Rename the `TowerSubgraphService` to `SubgraphService`

fix: Show a helpful error message when a subgraph does not return JSON or bad status code

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/context.rs
apollo-router/src/error.rs
apollo-router/src/http_server_factory.rs
apollo-router/src/introspection.rs
apollo-router/src/json_ext.rs
apollo-router/src/lib.rs
apollo-router/src/query_cache.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/query_planner/selection.rs
apollo-router/src/request.rs
apollo-router/src/response.rs
apollo-router/src/router.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/mod.rs
apollo-router/src/services/router_service.rs
apollo-router/src/services/subgraph_service.rs
apollo-router/src/spec/query.rs
apollo-router/src/state_machine.rs
apollo-router/src/traits.rs
apollo-router/tests/infrastructure_tests.rs
apollo-router/tests/integration_tests.rs

It had become the same as the crate root.
Fixes https://github.com/apollographql/router/issues/1214

Remove apollo_router::prelude::graphql reexports

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/error.rs
apollo-router/src/introspection.rs
apollo-router/src/plugins/headers.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/request.rs
apollo-router/src/response.rs
apollo-router/src/router.rs
apollo-router/src/services/mod.rs
apollo-router/src/services/subgraph_service.rs
apollo-router/src/spec/query.rs
apollo-router/tests/integration_tests.rs
licenses.html

All use of typed_builder has been removed.
Apart from making our code more consistent, it also give a minor improvement in usability for clients.

Remove typed builder. All builders use buildstructor.

---

apollo-router-scaffold/templates/plugin/src/plugins/{{snake_name}}.rs
apollo-router/src/layers/async_checkpoint.rs
apollo-router/src/layers/mod.rs
examples/async-auth/src/allow_client_id_from_file.rs

This change removes the requirement to `Box::pin()` arguments to the `ServiceBuilder::checkpoint_async()` fn.
The major impact is in the example module where I had to perform some substantial re-working of the code to avoid trying to return multiple closures from the handler function.
fixes: #1151

checkpoint_async() shouldn't require a boxed argument

---

NEXT_CHANGELOG.md
apollo-router/src/executable.rs
apollo-router/src/lib.rs
apollo-router/src/router.rs

The interfaces around the entry point have been improved for naming consistency and to enable reuse when customization is required. 
Most users will continue to use:
```rust
apollo_router::main()  
```
However, if you want to specify your own tokio runtime and or provide some extra customization to configuration/schema/shutdown then you may use `Executable::builder()` to override behavior. 
```rust
use apollo_router::Executable;
Executable::builder()
.runtime(runtime) // Optional
.router_builder_fn(|configuration, schema| ...) // Optional
.start()?
```

Remove rt_main 

---

CHANGELOG.md

Stream support was released in v0.9.4, which is a breaking change for our native plugin writers.
This Pull request moves the corresponding change to the breaking section of v0.9.4, and adds migration steps.

v0.9.4 steps to migrate native plugins 

---

NEXT_CHANGELOG.md
apollo-router/src/services/execution_service.rs

The `@defer` preliminary work has a surprising side effect: when using
methods like `RouterResponse::map_response`, they are
executed before the subgraph responses are received, because they work
on the stream of responses.
This commit goes back to the previous behaviour by awaiting the primary
response before creating the ExecutionResponse.
this will address issues like https://github.com/apollographql/router/discussions/1252#discussioncomment-2955415

create the ExecutionResponse after the primary response was generated

---

NEXT_CHANGELOG.md
apollo-router/src/executable.rs
apollo-router/src/router.rs

Turns out you can't blockingly call an async function from a sync function in an async context.
Make `Executable::builder()` async and move out runtime handling to `main()`.

Make Executable::builder() async

---

Cargo.lock
Cargo.toml
NEXT_CHANGELOG.md
apollo-router/src/plugins/rhai.rs
docs/source/customizations/rhai.mdx
examples/README.md
examples/cookies-to-headers/src/cookies_to_headers.rhai
examples/rhai-subgraph-request-log/Cargo.toml
examples/rhai-subgraph-request-log/README.md
examples/rhai-subgraph-request-log/router.yaml
examples/rhai-subgraph-request-log/src/main.rs
examples/rhai-subgraph-request-log/src/rhai_subgraph_request_log.rhai

to request.sub.headers
also:
- bring sub request access to same level as originating request
- add support to both for uri.host
- create a new example logging various request parameters
fixes: #1258

rename subgraph request.sub_headers

---

Cargo.lock
Cargo.toml
NEXT_CHANGELOG.md
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/src/lib.rs
apollo-router-scaffold/src/plugin.rs
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router-scaffold/templates/plugin/src/plugins/{{snake_name}}.rs

fixes #1247
Release v0.9.4 changed the way we deal with Response objects, which can now be streams.
This Pull request updates the scaffold template so it generates plugins that are compatible with the new Plugin API.

Fix: Update the scaffold template so it works with streams.

---

apollo-router/src/context.rs
apollo-router/src/plugins/csrf.rs

This fixes some of the warnings emitted by `cargo doc`.
Remaining warnings involve either making some types public, or removing mentions of them in public docs and in some cases making fields private. See: https://github.com/apollographql/router/issues/1150#issuecomment-1157692784

Fix some links in doc-comments.

---

apollo-router/src/cache.rs
apollo-router/src/context.rs
apollo-router/src/executable.rs
apollo-router/src/http_server_factory.rs
apollo-router/src/layers/cache.rs
apollo-router/src/lib.rs
apollo-router/src/plugin/utils/test/mock/canned.rs
apollo-router/src/plugins/telemetry/metrics/apollo.rs
apollo-router/src/plugins/telemetry/metrics/apollo/studio.rs
apollo-router/src/plugins/telemetry/metrics/mod.rs
apollo-router/src/plugins/telemetry/metrics/prometheus.rs
apollo-router/src/plugins/telemetry/otlp.rs
apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
apollo-router/src/plugins/telemetry/tracing/mod.rs
apollo-router/src/plugins/traffic_shaping/deduplication.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/reload.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/layers/allow_only_http_post_mutations.rs
apollo-router/src/services/layers/apq.rs
apollo-router/src/services/layers/ensure_query_presence.rs
apollo-router/src/services/router_service.rs
apollo-router/src/spec/mod.rs

Some reexports where recently removed, making some items unreachable from other crates as they are defined in private modules. This changes such items from `pub` to `pub(crate)` in order to better communicate the situation to human readers, and enables warnings for the `unreachable_pub` lint.
The diff is mostly generated by `cargo fix` with this lint.

Change unreachable `pub` items to be private to the create

---

dockerfiles/Dockerfile.router

the docker image needs a liz.so.1 now that we support compression in the router. Without one, it fails to execute.
We need a longer term solution, but this "hack" at least provides temporary relief.
Note: I've already updated the dockerfiles on github with images based on this change.

fix docker image

---

NEXT_CHANGELOG.md
apollo-router/src/spec/query.rs

Fix #1286
the fragment's type condition was not checked on interfaces, and instead
was verifying that the known current type (the Interface type, know from
parsing the query) is a known interface, instead of looking up the
interface used in the type condition (if it's an interface) and matching
that to the actual object type

fix fragment selection on interfaces

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/context.rs
apollo-router/src/http_server_factory.rs
apollo-router/src/lib.rs
apollo-router/src/plugin/mod.rs
apollo-router/src/plugin/test/mock/subgraph.rs
apollo-router/src/plugins/forbid_mutations.rs
apollo-router/src/plugins/headers.rs
apollo-router/src/plugins/rhai.rs
apollo-router/src/plugins/telemetry/metrics/mod.rs
apollo-router/src/plugins/telemetry/metrics/prometheus.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/traffic_shaping/deduplication.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/http_compat.rs
apollo-router/src/services/http_ext.rs
apollo-router/src/services/layers/allow_only_http_post_mutations.rs
apollo-router/src/services/mod.rs
apollo-router/src/services/router_service.rs
apollo-router/src/services/subgraph_service.rs
apollo-router/src/state_machine.rs
apollo-router/tests/integration_tests.rs
apollo-router/tests/rhai_tests.rs
examples/cookies-to-headers/src/main.rs

Summary:
- rename `http_compat` module to `http_ext`
- remove Request::mock()
- remove various wrapper fn and replace with explicit conversion using `From`
fix #1147

http_compat re-examined

---

NEXT_CHANGELOG.md
apollo-router/src/spec/query.rs

This PR is related to apollographql/federation-rs#140.
Introspection field `__typename` is introspection in runtime, which attaches the type name of the select documents. However, it is incorrectly identified as static introspection like `__schema` or `__type("...")` which is executed as a query with empty parameters. Since `__typename` is purely runtime, identifying queries with `__typename` selected as introspection queries and executing them as such almost never works, especially if the queries have non-null parameters and an operation name must be taken in case there are multiple operations present.
This PR strict the set to `__schema` and `__type` only, excluding `__typename` even though the GraphQL terminology classifies it as is because it is a dynamic introspection depending on …

Restrict static introspection to only __schema and __type

---

apollo-router-scaffold/src/lib.rs
apollo-router-scaffold/templates/plugin/src/plugins/{{snake_name}}.rs

This warning was introduced in https://github.com/apollographql/router/pull/1303

Fix a warning in a scaffold template and make test fail if we add more

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/mod.rs
apollo-router/src/plugins/include_subgraph_errors.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/router_factory.rs

prompted by the problems identified in #1184.
This isn't a complete fix to those issues, but a patching PR which
provides a temporary improvement until we have resolved how to best
to address the issue.
also:
- add support for redacting errors as well as responses
- add a log line noting when errors are redacted
- add comment to problem area in query planner processing
- remove unnecessary clone
The scope of this set of fixes has expanded to include plugin initialisation. Here's the explanation why from the commit message:
improve plugin initialization
Prompted by Bryn's previous comment about ordering, I looked further
into the plugin registration process and discovered bugs (which caused
plugins not to be ordered) and, in discussion with Bryn, identified
opportunities to improve plugin …

re-enable the include_subgraph_errors plugin

---

NEXT_CHANGELOG.md
apollo-router/src/spec/field_type.rs
apollo-router/src/spec/query.rs

close #1243 
The router is now following coercion rules for List regarding [the specs](https://spec.graphql.org/June2018/#sec-Type-System.List). Especially it fixes the case when for an input type `[Int]` only `1` was provided as a value. It's now working and it's coerced to `[1]`.

fix input coercion for type List

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__it_does_not_leak_env_variable_values.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_bad_type.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_errors_after_first_field_env_expansion.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_inline_sequence_env_expansion.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_sequence_env_expansion.snap
apollo-router/src/router_factory.rs
docs/source/configuration/overview.mdx

Environment expansion now covers the entire configuration file, and supports non string types.
This means that it is not possible to use environment variable in the server section of the yaml, and also in numeric and boolean fields.
Environment variables will always be shown in their original form in error messages preventing leakage of secrets.
These changes allow more of the configuration file to be validated via json schema, as previously we just skipped errors where fields contained env variables.
Broadly these are the changes:
1. Move env expansion from the point where we load plugins to where we validate config
2. Make env variable expansion coerce to primitive serde types by using serde_yaml on any expanded variables. (Prevents errors later during schema validation)
3. Make error …

Improve configuration validation and environment expansion

---

NEXT_CHANGELOG.md
apollo-router-scaffold/templates/plugin/src/plugins/{{snake_name}}.rs
apollo-router/src/plugin/mod.rs
apollo-router/src/plugin/test/mod.rs
apollo-router/src/plugins/forbid_mutations.rs
apollo-router/src/plugins/headers.rs
apollo-router/src/plugins/include_subgraph_errors.rs
apollo-router/src/plugins/override_url.rs
apollo-router/src/plugins/rhai.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/traffic_shaping/mod.rs
examples/context/src/context_data.rs
examples/cookies-to-headers/src/main.rs
examples/hello-world/src/hello_world.rs
examples/status-code-propagation/src/propagate_status_code.rs

the Plugin::*_service() methods were taking a &mut self as argument, but since
they work like a tower Layer, they can use &self instead. This change
then allows us to move from Buffer to service factories for the query
planner, execution and subgraph services

relax plugin api mutability

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/otlp.rs
apollo-router/src/plugins/telemetry/tracing/mod.rs

fixes: #1339
- adds a test for the specific issue
- centralises url processing into a function
- call shared function from deserialisation logic

improve configuration endpoint parsing

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
deny.toml
examples/cookies-to-headers/src/cookies_to_headers.rhai
licenses.html

We had been using a pinned git version to pull in a fix which geoffroy
had contributed.
I ran the full test suite and all the examples and all looks good.
I also updated one of the examples based on improvements I identified in
writing rhai script for another project.

chore: update rhai to latest release (1.8.0)

---

renovate.json5

Follows up on https://github.com/apollographql/router/pull/1336
The regex I used in the last PR turned out to be incorrect because the
(m)ultiline flag is not passed to the Renovate Regex-invocation.  Instead,
the match is processed against a "joined" string of the file contents.
I've also added a couple more files which were meant to be grouped into this
originally, now that I'm more confident in the behavior after reviewing the
[Renovate dashboard] and specified a branch name explicitly, to avoid the
`docker-` prefixing which was somewhat counter-intuiative.
[Renovate dashboard]: https://app.renovatebot.com/

renovate: correct rustc regex to not use line-boundaries

---

NEXT_CHANGELOG.md
apollo-router/src/spec/query.rs

Fix #1334 
Fragment type conditions were working on interfaces but not unions. This
simplifies the type matching and uses the schema's subtype map for
everything

fix fragment type conditions on unions

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/traffic_shaping/deduplication.rs

Related: #1343 (this PR might fix it, we don't know yet)
In its initial version, query deduplication was a layer directly above
the subgraph service, which has no requirements on `Service::poll_ready` calls.
Since its integration in the traffic shaping plugin, deduplication is
now a layer above a buffer above possibly other plugins then the
subgraph service.
[The Buffer service reserves slots in `poll_ready()` that are consumed when
`call()` is used](https://docs.rs/tower/latest/src/tower/buffer/layer.rs.html#25), and if `call()` is not used, those slots can take a
long time to drop and be reusable.
Since the query deduplication will prevent a lot of calls to the inner
service, it should not forward its `poll_ready` calls directly to the
underlying buffer, because that would hold a lot of …

reduce poll_ready calls in query deduplication

---

NEXT_CHANGELOG.md
apollo-router/src/query_planner/mod.rs
apollo-router/src/services/execution_service.rs

the query plan execution was done entirely in a spawned task to prepare
for the  `@defer` implementation, but we will not need to go that far:
the first response can be obtained directly, and append the receiver of
future responses that would be sent from tasks spawned inside query
planner execution

execute the query plan's first response directly

---

NEXT_CHANGELOG.md
apollo-router/src/spec/query.rs

A query with at the root only one selection field equals to `__typename` must be considered as an introspection query

fix(introspection): fix detection of an introspection query

---

apollo-router/resources/index.html

This PR renders the embeddable Sandbox by default in the router instead of the Apollo Server Landing Page as it did previously. 
**Why did we make this change?**
We are moving to rendering the embeddable Sandbox by default in Apollo Server, and want to keep this up to date. More more info on this decision see [this thread](https://apollograph.slack.com/archives/C032ZPPE5E1/p1653050271497329).
**Questions:** in Apollo Server, folks can can set `includeCookies` in their configuration options and that will be passed to the embedded Sandbox. We weren't passing this to the AS Landing Page before this PR, but I think we'd want to? Is that a config option in router? I couldn't find it

✨ render embedded Sandbox instead of landing page

---

CHANGELOG.md
Cargo.lock
NEXT_CHANGELOG.md
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
docs/source/federation-version-support.mdx
helm/chart/router/Chart.yaml
helm/chart/router/README.md
uplink/Cargo.toml
xtask/Cargo.toml

the `Plugin::*_service()` methods were taking a `&mut self` as argument, but since
they work like a tower Layer, they can use `&self` instead. This change
then allows us to move from Buffer to service factories for the query
planner, execution and subgraph services
By [@Geal](https://github.com/Geal) in https://github.com/apollographql/router/pull/1340 https://github.com/apollographql/router/pull/1289
Resources are almost like attributes but there are more globals. They are directly configured on the metrics exporter which means you'll always have these resources on each of your metrics. It could be pretty useful to set
a service name for example to let you more easily find metrics related to a specific service.
```yaml
telemetry:
metrics:
common:
resources:
service.name: "apollo-router" …
```

release: v0.11.0

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml

Fix #1386
Otherwise the HTTP exporter will not run

the opentelemetry-otlp crate needs a http-client feature

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
apollo-router/src/executable.rs
apollo-spaceport/Cargo.toml

Fix #1231 
argument parsing changed in clap 3.2, which resulted in the
`ArgMatches::value_of` method panicking when trying to downcast a
`PathBuf` to a `String`. This adds a special case to try and downcast to
`PathBuf` directly and uses non panicking methods

update clap and add a special case for PathBuf arguments

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router-benchmarks/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
examples/add-timestamp-header/Cargo.toml
examples/async-auth/Cargo.toml
examples/context/Cargo.toml
examples/cookies-to-headers/Cargo.toml
examples/embedded/Cargo.toml
examples/forbid-anonymous-operations/Cargo.toml
examples/hello-world/Cargo.toml
examples/jwt-auth/Cargo.toml
examples/op-name-to-header/Cargo.toml
examples/rhai-data-response-mutate/Cargo.toml
examples/rhai-error-response-mutate/Cargo.toml
examples/rhai-logging/Cargo.toml
examples/rhai-subgraph-request-log/Cargo.toml
examples/rhai-surrogate-cache-key/Cargo.toml
examples/status-code-propagation/Cargo.toml
fuzz/Cargo.toml
licenses.html
uplink/Cargo.toml
xtask/Cargo.toml

likely to improve performance with axum and tracing updates.
Dependency version requirements are not critical outside of the router
and the crates it uses, so we can relax the version requirements there
(example: in the benchmarks)

update dependencies and relax version requirements

---

NEXT_CHANGELOG.md
dockerfiles/Dockerfile.router
xtask/src/commands/package/mod.rs

Fix #1385
code extracted from rover's xtask command
I updated the URL in the Dockerfile, but that means it would not work until the next release, should that go into a separate PR instead?

insert the full target triplet in the package name

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/router_service.rs
apollo-router/src/state_machine.rs

Fix #1400
the StateMachine was holding a copy of the plugin list to extract the
custom endpoints registered by some of the plugins, like the prometheus
endpoint.
With the Tower refactoring, that plugin list was empty so the endpoints
were not registered.
This commit makes sure that the plugins are only held byt the
RouterServiceFactory instance, and that it implements a method to return
the list of endpoints, that can be used by the StateMachine instance

expose the custom endpoints from RouterServiceFactory

---

scripts/install.sh

This follows-up #1393 with the necessary changes to the install script which allows the installer to locate (and extract) the right binaries during the https://router.apollo.dev/ `curl`-based installer bits

update install script to use target triple formatted archive names

---

CHANGELOG.md
Cargo.lock
NEXT_CHANGELOG.md
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
dockerfiles/Dockerfile.router
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
docs/source/federation-version-support.mdx
helm/chart/router/Chart.yaml
helm/chart/router/README.md
scripts/install.sh
uplink/Cargo.toml
xtask/Cargo.toml
xtask/src/commands/package/mod.rs

You will need to update your YAML configuration file to use the correct name for `rhai` plugin.
```diff
- plugins:
-   experimental.rhai:
-     filename: /path/to/myfile.rhai
+ rhai:
+   scripts: /path/to/directory/containing/all/my/rhai/scripts (./scripts by default)
+   main: <name of main script to execute> (main.rhai by default)
```
You can now modularise your rhai code. Rather than specifying a path to a filename containing your rhai code, the rhai plugin will now attempt to execute the script specified via `main`. If modules are imported, the rhai plugin will search for those modules in the `scripts` directory. for more details about how rhai makes use of modules, look at [the rhai documentation](https://rhai.rs/book/ref/modules/import.html).
The simplest migration will be to set …

release: v0.12.0

---

.circleci/config.yml

The previous version is being removed by Circle-CI:
https://discuss.circleci.com/t/xcode-image-deprecation/44294
https://circleci.com/docs/testing-ios#supported-xcode-versions

CI: Upgrade the macOS image version

---

NEXT_CHANGELOG.md
apollo-router/src/context.rs
apollo-router/src/json_ext.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/services/execution_service.rs

* do not clone the client request during query plan execution (~19% perf improvement)
* do not clone the usage reporting (2-6% perf improvement)
* avoid path allocations when iterating over JSON values (1-3% perf improvement)
The benchmarks show that this PR gives a 23% gain in requests per second compared to main
I tried another possible optimization linked to variable deduplication: we always clone the entity returned by the subgraph, even when deduplication is not active. Unfortunately removing the clone slows down the router :thinking: (I'm pretty sure there's a way to get a perf gain there, maybe someone else will find it!)

small optimizations

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml

I've made a mistake in the 0.12.0 release and forgot to update the scaffold template correctly.
This commit fixes it

fix: update scaffold to use 0.12.0

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/rhai.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/services/mod.rs
apollo-router/src/services/router_service.rs

the query planner only uses the query, operation name and query plan
options, so the QueryPlannerRequest should only provide those fields
along with the context

remove the HTTP request from QueryPlannerRequest

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/telemetry/metrics/mod.rs
apollo-router/src/plugins/telemetry/mod.rs
docs/source/configuration/metrics.mdx

close #1434 
Add the ability to add custom attributes on errors:
```yaml
telemetry:
metrics:
prometheus:
enabled: true
common:
attributes:
subgraph:
all:
errors: # Only works if it's a valid GraphQL error
include_messages: true # Will include the error message in a message attribute
extensions: # Include extension data
- name: subgraph_error_extended_type # Name of the attribute
path: .type # JSON query path to fetch data from extensions
```

feat(telemetry): add error section in custom attributes configuration

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
docs/source/configuration/cors.mdx

Fixes #1425, #1448 and #1390
The router now supports regex based CORS rules, as explained in the [docs](https://www.apollographql.com/docs/router/configuration/cors)
It also supports the `allow_any_header` setting that will mirror client's requested headers.
```yaml title="router.yaml"
server:
cors:
match_origins:
- "https://([a-z0-9]+[.])*api[.]example[.]com" # any host that uses https and ends with .api.example.com
allow_any_header: true # mirror client's headers
```
The default CORS headers configuration of the router allows `content-type`, `apollographql-client-version` and `apollographql-client-name`.
By [@o0Ignition0o](https://github.com/o0ignition0o) in https://github.com/apollographql/router/pull/1444

Configure Regex based CORS rules

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/error.rs
apollo-router/src/executable.rs
apollo-router/src/json_ext.rs
apollo-router/src/layers/mod.rs
apollo-router/src/lib.rs
apollo-router/src/plugin/serde.rs
apollo-router/src/plugins/csrf.rs
apollo-router/src/plugins/mod.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/services/mod.rs
apollo-router/src/services/new_service.rs
apollo-router/src/services/router_service.rs
apollo-router/src/subscriber.rs
licenses.html

Enough minimal documentation so that we can reason more effectively
about what our API looks like. I've tried providing some very
rudimentary guidance for a notional plugin author.
I've also moved `NewService` from pub to pub(crate).

update buildstructor to 0.4.1 and add docs

---

apollo-router/src/query_planner/mod.rs

The execution is performed with recursive calls that share some
immutable arguments. To make the code easier to read, we assemble them
in a structure that can be passed unchanged

introduce an argument type for query plan execution

---

RELEASE_CHECKLIST.md
docs/source/containerization/kubernetes.mdx
helm/chart/router/README.md

also:
- generate helm-docs which I forgot to do for the last release
- improve the documentation link in kubernetes.mdx

improve the release notes a little based on release 0.14.0

---

NEXT_CHANGELOG.md
docs/source/configuration/cors.mdx

Fixes #1448 
This fixes a docs issue where we would set trailing slashes in the CORS `origins` section, which wouldn't work because CORS origins don't have the forward slash.
The docs full CORS example now displays the default settings.

docs: update CORS examples

---

apollo-router/src/error.rs
apollo-router/src/lib.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/services/mod.rs
apollo-router/src/spec/mod.rs

… that were only public through appearing in other APIs.
Part of https://github.com/apollographql/router/issues/1305

Give a reachable public path to some items

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
docs/source/configuration/cors.mdx

The router now mirrors client's `Access-Control-Request-Headers` by default.
The latest release (0.14.0) introduced an `allow_any_header` setting, which is now removed.
This is the default behavior, you can remove `allow_any_header` from your configuration.
You can provide a list of headers to allow by filling the `allow_headers` key:
```yaml title="router.yaml"
server:
cors:
allow_any_origin: true
allow_headers:
- Content-Type
- Authorization
- x-my-custom-header
```
By [@o0Ignition0o](https://github.com/o0ignition0o) in https://github.com/apollographql/router/pull/1480

CORS: Mirror client's requested headers by default

---

Cargo.lock
apollo-router/Cargo.toml
fuzz/Cargo.toml
licenses.html

This is the same as https://github.com/apollographql/router/pull/1002 but without `tracing`.   If we land this, then we can clean up this backlog and then configure the `renovate.json5` file to ignore the `tracing` crates.  The way it stands right now though, we're not merging any updates because they're lumped into the grouped PR.  (We can also disable the grouping, but we agreed a while back that we liked the grouping.)

fix(deps): update cargo pre-1.0 packages but not for `tracing*`

---

NEXT_CHANGELOG.md
xtask/src/commands/all.rs
xtask/src/commands/compliance.rs

This PR displays the `git diff` output if the license check failed in CI.
This will hopefully help us diagnose license check fails.
This pr also changes the order of the steps performed in `cargo xtask all` to run them from the fastest to the slowest.

chore: Display licenses.html diff if the license check failed in CI

---

apollo-router/src/services/http_ext.rs
apollo-router/src/services/mod.rs
examples/cookies-to-headers/src/main.rs

Follows up on https://github.com/apollographql/router/pull/1487#discussion_r944613174
Related to https://github.com/apollographql/router/issues/1219

Add {Router,Execution}Response::map_stream helper

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/expose_query_plan.rs

fixes https://github.com/apollographql/router/issues/1541, part of https://github.com/apollographql/router/issues/1545
This commit moves the ExposeQueryPlan behavior to the execution_service, while we're progressively removing query_planner_service from the api.

fix: ExposeQueryPlan: Move the plugin code to execution_service

---

apollo-router/src/axum_http_server_factory.rs
apollo-router/src/http_server_factory.rs
apollo-router/src/plugins/expose_query_plan.rs
apollo-router/src/plugins/include_subgraph_errors.rs
apollo-router/src/plugins/traffic_shaping/mod.rs
apollo-router/src/router.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/supergraph_service.rs
apollo-router/src/state_machine.rs
apollo-router/src/test_harness.rs
docs/source/customizations/native.mdx
docs/source/customizations/overview.mdx
examples/context/README.md
examples/status-code-propagation/README.md
examples/status-code-propagation/src/propagate_status_code.rs
examples/supergraph_sdl/README.md

Follow up to https://github.com/apollographql/router/pull/1534
This does not affect the public API

Rename RouterService to SupergraphService in various places

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/introspection.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/services/supergraph_service.rs

activate defer support in introspection

---

NEXT_CHANGELOG.md
apollo-router/src/services/supergraph_service.rs
apollo-router/tests/integration_tests.rs

fixes #1403
While the query planner would rightfully return an HTTP 400 if query validation fails, variable validation that occurred right after would return an HTTP 200.
This PR fixes it, and adds a test.

fix: return an HTTP 400 if variable validation fails.

---

NEXT_CHANGELOG.md
apollo-router/src/error.rs
apollo-router/src/response.rs
apollo-router/src/services/supergraph_service.rs
apollo-router/tests/integration_tests.rs
apollo-router/tests/snapshots/integration_tests__defer_path-2.snap
apollo-router/tests/snapshots/integration_tests__defer_path.snap
apollo-router/tests/snapshots/integration_tests__defer_path_in_array-2.snap
apollo-router/tests/snapshots/integration_tests__defer_path_in_array.snap

Fix #1548
deferred response should return payloads in an array in the response's
`incremental` field

support the incremental response field

---

NEXT_CHANGELOG.md
apollo-router/src/query_planner/caching_query_planner.rs

This bug was introduced with the cache on the query planner and then we didn't have any correct data for usage reporting.

fix(query_planner): put the USAGE_REPORTING back in the context if the query plan has been cached

---

NEXT_CHANGELOG.md
apollo-router/src/query_planner/mod.rs
apollo-router/src/services/execution.rs
apollo-router/src/services/query_planner.rs
apollo-router/src/spec/query.rs

Fixes https://github.com/apollographql/router/issues/1556

Make QueryPlan::usage_reporting and QueryPlannerContent private

---

.circleci/config.yml
RELEASE_CHECKLIST.md

For now we’ll run it for releases.

Disable check-compliance on CI as it is flaky

---

NEXT_CHANGELOG.md
apollo-router/src/plugin/mod.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/supergraph_service.rs
docs/source/customizations/native.mdx

fixes: #1549
also remove `plugin_muts()` from `PluggableSupergraphServiceBuilder` since the activate
functionality was the only consumer of this API.

remove activate() from the plugin API

---

NEXT_CHANGELOG.md
apollo-router/src/services/subgraph_service.rs

This fixes a typo in an error message that would add a closing parenthesis on HTTP errors from subgraphs.

fix(apollo-router): fix typo in error message

---

apollo-router/src/plugin/mod.rs

There's no need to require the whole trait to be Sized.
fixes: #1591

relax trait bound on Plugin

---

apollo-router/src/axum_http_server_factory.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap

This commit allows to disable ftv1 traces reporting.
It does so by:
Allowing the telemetry plugin to add a do not sample (bool) entry to the context.
Allowing the telemetry plugin to add a do not sample reason to the execution span.
Having those enabled will:
- Not propagate the ftv1 header to subgraphs.
- Not create an ftv1 trace
- log the reason why the trace is not being created in `debug`
The only reason at the moment is "query is defered" but we could add other eventually.

Disable ftv1 traces reporting on defered queries.

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/context.rs
apollo-router/src/http_ext.rs
apollo-router/src/plugin/test/mock/subgraph.rs
apollo-router/src/plugins/expose_query_plan.rs
apollo-router/src/plugins/headers.rs
apollo-router/src/plugins/rhai.rs
apollo-router/src/plugins/telemetry/metrics/mod.rs
apollo-router/src/plugins/traffic_shaping/deduplication.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/execution.rs
apollo-router/src/services/execution_service.rs
apollo-router/src/services/layers/allow_only_http_post_mutations.rs
apollo-router/src/services/subgraph.rs
apollo-router/src/services/subgraph_service.rs
apollo-router/src/services/supergraph.rs
apollo-router/src/services/supergraph_service.rs
apollo-router/src/state_machine.rs

Use types from the http crate instead in a number of places.
Part of https://github.com/apollographql/router/issues/1553

Make http_ext::Request and http_ext::Response private

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/rhai.rs

If we add a tracing span to our rhai plugin, we can now reason (from a tracing span point of view) about requests within our rhai plugin. See the screenshot for what this looks like in jaeger.
If your router doesn't have an active rhai script, then this trace won't appear.
I've set the trace at info level. I think that's reasonable, but happy to change that if people think that's the wrong level.
also: tidy up the rhai code a little to reflect recent renaming and to make this simpler.

instrument rhai requests

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs

Fix #1588
deferred responses come as multipart elements, send as individual HTTP
response chunks. When a client receives one chunk, it should contain the
next delimiter, so the client knows that the response can be processed,
instead of waiting for the next chunk to see the delimiter.
Side note: fixed the format of the last delimiter that was missing a
trailing --

add the next multipart delimiter at the end of the chunk

---

NEXT_CHANGELOG.md
RELEASE_CHECKLIST.md

We previously created a pattern where some of the manual version changes
that needed to be made were appearing in the "Prepare a Changelog (Full
release only)" section and some were in the "Start a release PR" section.
This wasn't the right organization and I found this to be counterintuiative
since many of the version bumps were actually important to make even for
non-full-releases and further challenging because they weren't about the
changelog but rather version bumps which were also happening in the other
section.
This puts all the (too many) steps in one ordered list.

infra: reorganize the `RELEASE_CHECKLIST` to group version change steps

---

NEXT_CHANGELOG.md
apollo-router/src/test_harness.rs
examples/add-timestamp-header/src/main.rs
examples/cookies-to-headers/src/main.rs
examples/op-name-to-header/src/main.rs
examples/rhai-logging/src/main.rs

The previous verbosity was not helpful

TestHarness: rename extra_*_plugin to *_hook

---

apollo-router/src/graphql.rs
apollo-router/src/json_ext.rs

They were already public since reachable through graphql::Error
Fixes https://github.com/apollographql/router/issues/1305.
I haven’t managed to reproduce scripts to reliably find if other items are reachable but not importable, but these are the only ones I found manually.

Give JsonPath and JsonPathElement an importable path

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/mod.rs
apollo-router/src/error.rs
apollo-router/src/executable.rs
apollo-router/src/graphql.rs
apollo-router/src/plugin/mod.rs
apollo-router/src/plugins/telemetry/config.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/request.rs
apollo-router/src/response.rs
apollo-router/src/router.rs
apollo-router/src/services/execution.rs
apollo-router/src/services/subgraph.rs
apollo-router/src/services/supergraph.rs
apollo-router/src/spec/mod.rs
apollo-router/tests/integration_tests.rs
examples/async-auth/src/allow_client_id_from_file.rs
examples/forbid-anonymous-operations/src/forbid_anonymous_operations.rs
examples/jwt-auth/src/jwt.rs

… with a few exceptions like `Location` and `PathElement`.
Relevant types are:
* Public enums
* Public structs without any private field
See https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute
This will allow us adding struct fields or enum variants without it being a breaking change.
Fixes https://github.com/apollographql/router/issues/1550

Add #[non_exhaustive] to relevant types

---

.circleci/config.yml
NEXT_CHANGELOG.md
apollo-router/src/http_ext.rs
apollo-router/src/lib.rs
apollo-router/src/services/execution.rs
apollo-router/src/services/mod.rs
apollo-router/src/services/supergraph.rs
examples/jwt-auth/src/jwt.rs

Changes to `IntoHeaderName` and `IntoHeaderValue`

---

apollo-router/src/lib.rs
apollo-router/src/query_planner/mod.rs

Its public items are already reexported in modules that use them in public APIs.

Make the query_planner module private

---

.tool-versions
Cargo.lock
NEXT_CHANGELOG.md
apollo-router-scaffold/templates/base/.tool-versions
apollo-router/Cargo.toml
apollo-router/src/graphql.rs
apollo-router/src/json_ext.rs

part of #491
We have published the `router-bridge` to crates.io, which removes the need for router developers to have nodejs installed.

chore: Use published `router-bridge`

---

NEXT_CHANGELOG.md
RELEASE_CHECKLIST.md
dockerfiles/Dockerfile.router
scripts/install.sh
xtask/src/commands/package/mod.rs

This is meant to reintroduce the [Target Triplet] pattern which was first introduced in https://github.com/apollographql/router/pull/1393 and the https://github.com/apollographql/router/pull/1405 follow-up, which were intentionally reverted prior to the 0.12.0 release because the existing installer script wouldn't correctly continue to pin the version in a way that wouldn't break existing users had we deployed that technique.  The reason that was challenging is that we hadn't fixed the underlying issue.
> This PR has meaningful individual commits that are worth reviewing.  The first two are literally cherry-picks from previous iterations, followed by other commits which solidify more durable behavior.  The previous installer should continue to work just fine, but as we're doing a major …

Future-proof installer script and re-introduce target triplets

---

Cargo.lock
Cargo.toml
NEXT_CHANGELOG.md

Fix #1572
async-compression is used in tower-http's CompressionLayer. Inside the
AsyncRead based compression code, if the underlying stream returns
Poll::Pending, it will be returned directly, while in the case of
deferred responses, the next one might come way later, so we want to
send whatever data we have available right now.
We will have to switch to an AsyncWrite interface instead, which will be
more flexible, but considering the timing of the release, this patch
will hold for now.
This uses the code from https://github.com/Nemo157/async-compression/pull/155

patch async-compression to compress responses in streaming

---

.circleci/config.yml
dockerfiles/Dockerfile.router
dockerfiles/diy/build_docker_image.sh
dockerfiles/diy/dockerfiles/Dockerfile.release

Following up on https://github.com/apollographql/router/pull/1433 which re-introduced target triplets and the installer to support it, this utilizes the installer in our Docker build steps.
This consists of:
- Switching our direct downloading of releases to go through our unified installer endpoint.
- Durably uses the installer script to download the right architecture for a particular release using the logic in the installer for that release.
- There is now a default `ROUTER_RELEASE` value of `latest` on the images, though the argument still works (and is used by our releasing pipeline)
- Simplifies some logic (e.g., transforming version numbers to remove `v`).
- Switching from `alpine` to `debian` since our installer doesn't support `alpine` and fails.  This is _not_ a material change …

Update Docker build artifacts to new installer pattern

---

apollo-router-benchmarks/Cargo.toml
apollo-router/Cargo.toml
apollo-router/src/plugins/telemetry/metrics/apollo.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/telemetry/tracing/apollo.rs
apollo-router/src/router.rs
apollo-router/src/router_factory.rs
apollo-spaceport/proto/agents.proto
apollo-spaceport/src/lib.rs
apollo-spaceport/src/spaceport.rs
deny.toml
uplink/Cargo.toml
uplink/src/lib.rs

- Use the now-available SPDX identifiers for all crates in this workspace
Since the `Elastic-2.0` SPDX identifier is now official, we can use it everywhere and should be able to remove this lingering dependency on an internal representation for it in our `cargo deny` implementation.
- Designate license key functionality clearly everywhere as ELv2
This also makes it possible to just search for ELv2 in the project and find all occurrences.

Use SPDX identifiers and designate license key functionality

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
docs/source/configuration/overview.mdx

This more accurately represents the behavior of the option which changes the
path at which your Router will respond to GraphQL requests.
The previous name gave the impression that it might be the full "endpoint"
which it was not (again, just a path!)
Closes https://github.com/apollographql/router/issues/1606

Rename `Server::endpoint` to `Server::graphql_path`

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/services/supergraph_service.rs
apollo-router/tests/integration_tests.rs
apollo-router/tests/snapshots/integration_tests__defer_query_without_accept.snap

Fix #1618 
Since deferred responses can come back as multipart responses, we must
check that the client supports that content type. This will allow older
clients to show a meaningful error message instead of a parsing error if
the `@defer` directive is used but they don't support it

queries with defer must have the Accept: multipart/mixed header

---

NEXT_CHANGELOG.md
apollo-router/src/state_machine.rs

This changes the verbosity of messages like `transitioned to starting` from
the `info` level to the `trace` level since messages about the state machine
aren't necessary user-facing information during normal operation.
I waffled a bit on whether this should be `trace` or `debug`.  To some degree this seems like deeper inards of the Router than most people should ever need to encounter.  Since I think debugging the state machine might be a a particularly detailed operation in the general sense, I chose to use `trace` since it's my undersatnding the user can still use other log/env filters to tune the scope of what they're receiving log messages for, even at the `trace` level.
Anyway, I'm happy to change it to `debug` — just say the word.
Closes …

Change verbosity of state machine logs to `trace`

---

Cargo.lock
Cargo.toml
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
deny.toml
uplink/Cargo.toml
xtask/Cargo.toml

This commit reverts part of https://github.com/apollographql/router/pull/1620's changes to the SPDX Identifiers until the ecosystem relies on spdx 0.9.0.

revert Using the new SPDX identifier

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/configuration/mod.rs
docs/source/configuration/cors.mdx

This changes the behaviour of the CorsLayer so that a default Vary
header is only set if not specified in a user plugin.
This means that a value can now be set from a plugin. When processing
the response (after all plugin processing is completed), if there is no
Vary header, then the router will insert one with a value of "origin".
fixes: #1297

add support for setting vary header in plugins

---

docs/source/_redirects

This PR fixes the redirect URL for the Client Awareness router doc to include the /docs/router/ path so that the redirect goes to the new URL. 
https://www.apollographql.com/docs/router/managed-federation/client%20awareness/
https://www.apollographql.com/managed-federation/client-awareness/
https://www.apollographql.com/docs/router/managed-federation/client-awareness/
`/managed-federation/client%20awareness/ /managed-federation/client-awareness/`
updated to
`/managed-federation/client%20awareness/ /docs/router/managed-federation/client-awareness/`

Fix for broken redirect: Client Awareness router doc URL

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml

this fixes a bug where a `@defer` directive's `if` argument was ignored

update router-bridge to 0.1.1

---

NEXT_CHANGELOG.md
apollo-router/src/services/subgraph_service.rs

Fix: Propagate graphql response regardless of the subgraph HTTP status code.
fixes: #1335, #1662
Subgraph service calls used to return an error when the received HTTP status code isn't 200.
There's however no mention in the GraphQL specification that leads us to assume any intent behind the HTTP status code returned by a GraphQL server.
This commit removes our HTTP status code check in the `subgraph_service`.

Fix: Propagate graphql response regardless of the subgraph HTTP status code.

---

NEXT_CHANGELOG.md
dockerfiles/Dockerfile.router
dockerfiles/diy/dockerfiles/Dockerfile.release
dockerfiles/diy/dockerfiles/Dockerfile.repo

- Use an absolute path for Dockerfile ENTRYPOINT
I'm running up `apollographql/router` by Docker Compose for my local development. And, I'm changing the working directory for the `router` image like below in order to mount my application repository:
```yaml
---
version: "3.8"
services:
router:
image: ghcr.io/apollographql/router:v1.0.0-alpha.0
volumes:
- .:/workspace:cached
working_dir: /workspace
command: --config router.yaml --supergraph schema.graphql
```
Since the current Dockerfile specifies a relative path (`./router`) for `ENTRYPOINT`, changing the working directory causes an error 
```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./router": stat ./router: no such file or directory: …
```

docker: Define ENTRYPOINT as absolute path

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/mod.rs

I found a bug in the current version of `opentelemetry-jaeger` which causes this bug #1488. [It has been fixed on main](https://github.com/open-telemetry/opentelemetry-rust/commit/cd3898d524937ec59ac7e240ae9f54232f6b76b9) but not released, I can't just take the commit to fix the bug because they break everything, the API is currently unstable. So .... the last release (the one we're using) has been released on January... I can't just fork it and fix it by myself or cherry-pick the commit because it means we would be blocked by this to release on crate.io. 
Then I wrote a workaround waiting for a proper release.
close #1488

fix(telemetry): fix telemetry propagation

---

.circleci/config.yml

It's 75 credits instead of 50, but the newer generation processor makes a huge difference in our build times, which are often getting to 20 minutes and are reduced downward to about 10 with this change.
This can be seen in the [Product] documentation and the [Docs].
This also bumps the cache key because I don't trust the cache from the old Mac architecture to build cleanly.
[Docs]: https://circleci.com/docs/configuration-reference#macos-execution-environment
[Product]: https://circleci.com/product/features/resource-classes/#macos

infra: use gen2 Mac machine resource class on CircleCI + bump cache key

---

CHANGELOG.md
Cargo.lock
NEXT_CHANGELOG.md
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
helm/chart/router/Chart.yaml
helm/chart/router/README.md
scripts/install.sh
uplink/Cargo.toml
xtask/Cargo.toml

> 👋 We're getting closer to our release candidate stages so there are far less breaking changes to the API in these versions, rather changes to configuration.  We'll have a bit more in the next releases, but nothing as bad as the bumps from 0.15.x, through 0.16.0 and on to v1.0.0-alpha.0.  Thanks for your feedback and cooperation! ✨
Add `service_name` and `service_namespace` in `telemetry.metrics.common` to reflect the same configuration than tracing.
```yaml
telemetry:
metrics:
common:
service_name: "apollo-router"
service_namespace: "apollo"
```
By @bnjjj in https://github.com/apollographql/router/pull/1492
Span context is now correctly propagated if you're trying to propagate tracing context to the router.
By @bnjjj in https://github.com/apollographql/router/pull/1701
At startup, the …

release: v1.0.0-alpha.2

---

NEXT_CHANGELOG.md
apollo-router/src/layers/async_checkpoint.rs
apollo-router/src/layers/map_first_graphql_response.rs
apollo-router/src/layers/mod.rs
apollo-router/src/layers/sync_checkpoint.rs
apollo-router/src/plugins/forbid_mutations.rs
apollo-router/src/services/execution.rs
apollo-router/src/services/layers/allow_only_http_post_mutations.rs
apollo-router/src/services/supergraph.rs

Fixes https://github.com/apollographql/router/issues/1564, see discussion there.

Add map_first_graphql_response, unify execution & supergraph response type

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml

Brings in https://github.com/apollographql/federation/pull/2132, including fixes for the following issues:
- PR: https://github.com/apollographql/federation/pull/2125
- PR: https://github.com/apollographql/federation/pull/2126
- PR: https://github.com/apollographql/federation/pull/2129
Via https://github.com/apollographql/federation-rs/pull/170
Closes https://github.com/apollographql/router/issues/1698
Closes https://github.com/apollographql/router/issues/1668

deps: update to `router-bridge@0.1.3`

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/metrics/mod.rs
apollo-router/src/plugins/telemetry/mod.rs

fix(metrics): compute time before receiving the first response from the stream each time

---

docs/source/federation-version-support.mdx

fixes #1723 by updating the federation version support table for router `1.0.0-alpha.3` to point to federation version `2.1.2-alpha.0`

docs: updates federation version support table for alpha.3

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/error.rs
apollo-router/src/graphql.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__plan_invalid_query_errors.snap
apollo-router/src/response.rs
apollo-router/src/services/supergraph_service.rs
apollo-router/tests/snapshots/integration_tests__defer_path_with_disabled_config.snap
apollo-router/tests/snapshots/integration_tests__defer_query_without_accept.snap

TLDR I'm not very proud of what I did here. It's very hard to return specific errors or just catch an error in our codebase due to our usage of `BoxError`. That's why I had to downcast and so one ...
I think in a long term we should think about a better way to handle errors. Let's discuss about it.
close #1560

return the original query planner error and add extensions code

---

NEXT_CHANGELOG.md
apollo-router/src/services/subgraph.rs
apollo-router/src/services/supergraph.rs
licenses.html

Removing:
- subgraph::new_from_response
- supergraph::new_from_response
- supergraph::new_from_graphql_response

remove some over-exposed functions from the public API

---

NEXT_CHANGELOG.md
apollo-router/src/executable.rs

You and now specify custom schema and config sources when constructing an executable.
```rust
Executable::builder()
.shutdown(ShutdownSource::None)
.schema(SchemaSource::Stream(schemas))
.config(ConfigurationSource::Stream(configs))
.start()
.await
```

Restore the ability to add custom schema and configuration sources when constructing an executable

---

Cargo.lock
Cargo.toml
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/test_harness.rs
apollo-router/src/test_harness/http_client.rs

This is a different work-around for https://github.com/apollographql/router/issues/1572.
The previous work-around required a `[patch.crates-io]` section in the root `Cargo.toml`. When the Router is used as a dependency, that root manifest is not ours so downstream users would need to apply the same patch to get the work-around.
This came up in the context of publish the Router to crates.io https://github.com/apollographql/router/issues/491 but applies the same when the `apollo-router` crate is used as a git dependency.

Remove patched async-compression, disable compression for multipart responses instead

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/include_subgraph_errors.rs
apollo-router/src/router.rs
apollo-router/src/router_factory.rs
apollo-router/tests/integration_tests.rs
docs/source/configuration/subgraph-error-inclusion.mdx

It has been experimental for a while and is now official.
fixes: #1773

promote include_subgraph_errors plugin

---

docs/source/config.json

Remove the "experimental" designation from the side-bar.
follow up to: #1776 
fixes: #1773

fix docs side-bar

---

NEXT_CHANGELOG.md
helm/chart/router/templates/deployment.yaml

- Test with `helm template router-test helm/chart/router`
- Retains probe path of `/?query={__typename}`
- Test with `helm template router-test helm/chart/router --set router.configuration.supergraph.path=/graphql`
- Utilises probe path of `/graphql?query={__typename}`
- Resolves #1787

Respect supergraph path for kubernetes deployment probes

---

NEXT_CHANGELOG.md
apollo-router-scaffold/templates/base/Cargo.toml

Now that apollo-router version "1.0.0-rc.0" is released on [crates.io](https://crates.io/crates/apollo-router), we can update scaffold to it relies on the published crate instead of the git tag.
By [@o0Ignition0o](https://github.com/o0Ignition0o) in https://github.com/apollographql/router/pull/1782

Update apollo-router-scaffold to use the published router crate

---

RELEASE_CHECKLIST.md

This is set of instructions until we automate it through our existing CI
system.

chore: Update `RELEASE_CHECKLIST.md` for publishing to Crates.io.

---

NEXT_CHANGELOG.md
apollo-router/templates/sandbox_index.html

This option will tell Sandbox to automatically check the box that requests query plans from the Router.  This will only result in a query plan being returned if the Router has been run with the `experimental.expose_query_plans` plugin set to `true` in the configuration, which is automatically enabled by using the `--dev` flag.
Fixes https://github.com/apollographql/router/issues/1803

Pass `initialRequestQueryPlan: true` to `EmbeddedSandbox`

---

apollo-router/src/executable.rs

Avoiding the newline makes for a better experience in the output since each line is uniformly prefixed with the date rather than having a cliff on one single line.
This PR doesn't have an issue or a CHANGELOG.md.

nit: adjust formatting of telemetry message to separately emitted lines

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/headers.rs
docs/source/configuration/header-propagation.mdx
docs/source/configuration/overview.mdx
examples/header-manipulation/router.yaml

Adds `request` subsection into header propagation configuration to prepare for #1284 coming post 1.0
```patch
all:
+     request:
- remove:
named: "test"
```

prepare header propagation configuration for #1284

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/mod.rs
apollo-router/src/router.rs
apollo-router/src/router_factory.rs

Fix dev mode when you don't specify a configuration file

---

apollo-router/src/configuration/mod.rs

I think a follow-up could replace this message with a link to our documentation with more details.  I've removed the `APOLLO_ROVER` conditional for now since we will release before `rover dev` is fully GA and part of our development story.

nit: Adjust messaging for dev mode and remove conditional `APOLLO_ROVER` check

---

NEXT_CHANGELOG.md
apollo-router/src/spec/field_type.rs
apollo-router/src/spec/mod.rs
apollo-router/src/spec/query/tests.rs
apollo-router/src/spec/selection.rs

fix error message when querying non existent field

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml

Creates errors for missing selection sets in named operation definitions.

apollo-parser@0.2.11

---

NEXT_CHANGELOG.md
apollo-router/src/spec/field_type.rs
apollo-router/src/spec/fragments.rs
apollo-router/src/spec/mod.rs
apollo-router/src/spec/query.rs
apollo-router/src/spec/schema.rs
apollo-router/src/spec/selection.rs

As we are progressing towards 1.0, we are progressively banning `unwrap()` and `expect()` from the critical parts of the codebase.
This codepath is exercised after Parsing has happened, so invariants expressed by `expect`s would always have been enforced or checked before. However we decided to tighten the router even further, by raising errors instead, which will provide users with even more stability guarantees.
The spec module now has gates that prevent its content from using code that explicitly panics.
```rust
#![deny(clippy::unwrap_used)]
#![deny(clippy::expect_used)]
#![deny(clippy::panic)]
```

Deny panic, unwrap and expect in the spec module

---

NEXT_CHANGELOG.md
apollo-router/src/request.rs

This removes `Request::from_bytes()` from the public API.  We were no longer using it and we don't expect anyone external to have been relying on it.
This was discovered this function during an exercise of documenting our entire public API.  We considered keeping it briefly, but it doesn't necessarily meet our requirements for shipping it in the public API.  It's internal usage was removed in [`d147f97d`](https://github.com/apollographql/router/commit/d147f97d) as part of [PR #429](https://github.com/apollographql/router/pull/429).
We can consider re-introducing this in the future (it even has a matching `Response::from_bytes()` which it composes against nicely!), but it seemed worth remove it for the time-being until the use-cases are here.  (We can already see the use-cases, but we want …

Removed `Request::from_bytes()` from public API

---

dockerfiles/tracing/datadog-subgraph/package-lock.json
dockerfiles/tracing/jaeger-subgraph/package-lock.json
dockerfiles/tracing/zipkin-subgraph/package-lock.json

Just a depenency bump on the packages we rely on internally for testing tracing

chore(deps): Bump `apollo-server-core` versions in `tracing` Dockerfiles

---

.gitignore

following #1856 to not accidentally push the submodules we downloaded before

git ignore previous git submodules

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/plugins/telemetry/mod.rs
licenses.html

The JSON bit is a bit finicky but so is the code in the `tracing_subscriber` crate which I've mainly just lifted here.
fixes: #1862
fixes: #1869

redact `apollo_private` fields

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/query_planner/mod.rs

fix #1863
in a federated query, if the subgraph returns a response with errors and a null or absent data field, the router was ignoring the subgraph error and instead returning an error complaining about the missing `_entities` field. This will now aggregate the subgraph error and the missing `_entities` error

Do not erase errors when missing  _entities

---

.circleci/config.yml

See https://rust-lang.github.io/rustup/concepts/profiles.html
Compared to the default profile, the minimal profile removes rust-docs, rustfmt, and clippy. However we still request rustfmt and clippy through rust-toolchain.toml.
Also apply https://github.com/apollographql/router/pull/1877 (not installing a redundant toolchain) for Windows CI.

Don’t install the rustc-docs component on CI

---

NEXT_CHANGELOG.md
apollo-router/src/executable.rs
apollo-router/src/plugins/traffic_shaping/deduplication.rs
apollo-router/src/plugins/traffic_shaping/mod.rs
apollo-router/src/router_factory.rs

This removes another use of Buffer in the hot path

remove Buffer from query deduplication

---

dockerfiles/diy/dockerfiles/Dockerfile.repo

This was missed in the fix for #1721. It should have been included in PR: #1722

also update the rust build crate for diy dockerfiles

---

helm/chart/router/templates/service.yaml
helm/chart/router/templates/servicemonitor.yaml

The recently added serviceMonitor functionality isn't quite correct:
- There is no .Values.serviceMonitor.port
This PR fixes this problem.

fix the recently added servicemonitor features

---

NEXT_CHANGELOG.md
apollo-router/templates/homepage_index.html

The 'homepage' option displays the studio landing page (https://github.com/apollographql/studio-landing-page/blob/main/src/App.tsx). If you don't pass `footer: false`, it adds a footer that says "This page can be customized or hidden. Learn more in the Apollo Server Docs" which is inappropriate for Router (because it is not Apollo Server, and because the page can't be customized other than by replacing it with a different page.)

Remove note about Apollo Server docs from homepage

---

.github/workflows/main.yml

The message was actually not giving as much of a helpful instruction as it
could have for contributors.  Also, it wasn't running on the right branch anymore!

Update `NEXT_CHANGELOG.md` reminder to target `dev` and add clarity

---

.circleci/config.yml
NEXT_CHANGELOG.md
helm/chart/router/templates/hpa.yaml

- Found incorrect check for selecting the appropriate hpa api version
- Updated to v2beta2 (available in all currently supported kubernetes versions) as the default
- Set v2 based on kubernetes version - available since 1.23

Fix hpa yaml for appropriate kubernetes versions

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/rhai.rs
apollo-router/src/tracer.rs
docs/source/customizations/rhai-api.mdx
examples/rhai-surrogate-cache-key/src/rhai_surrogate_cache_key.rhai

issue: #1935 suggested exposing a span's trace id via the Context. I think it's better to avoid further use of the context and provide direct acccess to the traceid from `rhai`. (Note: In case it isn't obvious the `TraceId` is the opentelemetry Span Id.)
If you ran code like the docs example, you'd see something like:
```
2022-10-10T11:37:58.404084Z  INFO apollo_router::plugins::rhai: id: 338600282987103915558890515230971876324
```
fixes: #1935
also: drive by fix of the `log_error` in the surrogate example.

expose the TraceId functionality to rhai

---

NEXT_CHANGELOG.md
apollo-router/src/json_ext.rs
apollo-router/src/spec/query/tests.rs

Queries that passed 64 bit integers for Float values would (incorrectly) fail to validate.

fix: float coercion rules should validate i64s

---

.circleci/config.yml

circleci now makes resource consumption data available for all platforms.
A quick examination of our usage on a recent dev build shows peak memory consumption of approx:
Windows
build: 12% 1/8
test: 51% 1/2
Amd
build: 15% 1/7
test: 85% 7/8
Arm
build: 8% 1/12
test: 61% 3/5
Macos
build: 46% 1/2
test: 56% 1/2
Clearly, there are significant variations between build and test (except on Macos). We should try to rightsize all of them, but step 1 is splitting the machine types for platform further into by platform and by build or test. We can already make the build machines smaller (apart from on Macos) and see how that affects performance and billing.
With less memory, you get less CPU, but because we run everything in parallel, the now slower build jobs don't affect the overall time because …

split circleci machine types into build/test

---

CHANGELOG.md

The breaking change is not for Router 1.2.0 itself, but for the [Router helm chart](https://github.com/apollographql/router/pkgs/container/helm-charts%2Frouter) which is still [1.0.0-rc.5](https://github.com/orgs/apollographql/packages/container/helm-charts%2Frouter/45240873?tag=1.0.0-rc.5)

amend changelog to reflect no breaking change in Router itself

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/files.rs
apollo-router/src/router.rs
helm/chart/router/templates/deployment.yaml
licenses.html

fixes: #1476  
fixes: #1695
The change replaces `hotwatch` with `notify` and makes use of the "recommended" watcher feature which attempts to pick a file watcher which is best suited to the execution environment. I've also improved the robustness of the test and the way in which events are conveyed from the file watcher to the consumer (retries on full to prevent lost event notifications).
I've tested this manually on my local system (Macos M1) and confirmed:
- test suite works
- docker with --hot-reload works
- kubernetes in k3d works*    
* Note: [Limitations in kubernetes configmap handling](https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically) mean that router pods in kubernetes won't react to changes to configmaps mounted to …

replace hotwatch with notify

---

fuzz/Cargo.toml
fuzz/fuzz_targets/router_errors.rs

To not keep it only on my laptop, here is another fuzz target I use when I want to check if when giving an invalid query it will throw an error on both the gateway and the router.

add a fuzz target to generate invalid queries

---

.circleci/config.yml

As far as I can tell, any error that `cargo check` could find would also be found by `cargo test` in other jobs.

Remove `cargo check` jobs from CI

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/traffic_shaping/mod.rs

The modified tests have a high random fail rate in ci, so try to reduce that to improve the reliability of the ci pipeline.

try to reduce the flakiness of rate limiting test in ci

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/plugins/telemetry/otlp.rs
licenses.html

Fixes #1976 
TLS domain must be set. This is now defaulted for the user based on endpoint
Root certificates must be loaded. This is a feature of tonic.

Fix grpc otlp tls

---

docs/source/containerization/docker.mdx

This includes an attempt at fixing an outstanding concern around our containerization documentation, in addition to adding clarity on how to pass arbitrary [supported CLI flags] to the Router.
Fixes: https://github.com/apollographql/router/issues/1127
[supported CLI flags]: https://apollographql.com/docs/router/configuration/overview#command-arguments

docs: Docker overrides for CLI arguments, config

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml

This updates to a version of the Router Bridge that packages Federaiton
2.1.4 as found in the referenced/related PRs.
Ref: https://github.com/apollographql/federation/pull/2215
Ref: https://github.com/apollographql/federation-rs/pull/204
Fixes https://github.com/apollographql/router/issues/1962

chore(deps): Update to router-bridge@0.1.11 (Federation v2.1.4)

---

docs/source/customizations/rhai.mdx

I was running into issues when copying the example from the initial docs due to function pointers in Rhai can't be referred to imported modules, so reworked the example per the [rhai docs](https://rhai.rs/book/language/fn-ptr.html?highlight=fn%20pointer#warning--global-namespace-only).

docs: fix rhai example for import modules

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/rhai.rs

convert to string to get the contents of the apollo_sdl variable

---

.circleci/config.yml
Cargo.lock
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/src/lib.rs
apollo-router-scaffold/templates/base/Cargo.toml

Since this test is typically run together with other tests, the apollo-router and its dependencies will be already built. This sharing avoids recompiling some of the dependencies, but unfortunately not all because of some differences in feature selection.
For local development however, repeated runs of the test will be much faster since the target directory is preserved across runs.
RUSTFLAGS is replaced with a crate attribute so that it doesn’t affected dependencies (which then don’t all need to be recompiled)

Faster scaffold test: share `target` and `Cargo.lock` with main workspace

---

NEXT_CHANGELOG.md
apollo-router/src/cache/mod.rs

Close examination revealed that some judicious tweaking of the locking and spawning would improve the behaviour.
In performance testing this performs the same as current (dev) or using the deduplicate crate. I can't reproduce the hanging problem with dev with this set of changes.
The rationale for the changes are as follows:
- We need to spawn the sentinel **before** we insert the waiter entry or failure after inserting, but before spawning a sentinel, will cause issues.
- Notification of waiters from the "first" entry **must be synchronised** under the "wait_map" lock, or else that becomes racy and subscribers may be missed. That notification must be immediately preceded by the removal of the wait_map entry.
fixes: #1984

improve the deduplication logic

---

dockerfiles/diy/build_docker_image.sh

The last change introduced a bug which meant you can't use the script to build a docker image from released code. This fixes it.

fix logic in argument processing for diy docker build script

---

.circleci/config.yml

The long pole on our build is the arm build/test step. Also, running everything in parallel is expensive.
Let's address both of those problems:
- require lint to succeed before starting build/test jobs
- give more resources to arm jobs to allow them to complete faster
- tweak the build setting for both arm and amd to use resources more effectively
Result:
- total build time is reduced by ~15% in my test runs (even with waiting for lint first)
- billing should be reduced by less renovate waste-fullness when lint fails

reduce CI bill and improve build speed

---

NEXT_CHANGELOG.md
apollo-router/src/lib.rs
apollo-router/src/router_factory.rs

Allows router plugins to utilize `web_endpoints`
🕷 At the moment, the `web_endpoints` function on the `Plugin` trait is not usable because the `Endpoint` struct is not exported, see a simple example plugin attempting to use `web_endpoints`:
```
#[derive(Debug)]
struct HelloWorld {
#[allow(dead_code)]
configuration: Conf,
}
#[derive(Debug, Default, Deserialize, JsonSchema)]
struct Conf {
message: String,
}
#[async_trait::async_trait]
impl Plugin for HelloWorld {
type Config = Conf;
async fn new(init: PluginInit<Self::Config>) -> Result<Self, BoxError> {
tracing::info!("{}", init.config.message);
Ok(HelloWorld {
configuration: init.config,
})
}
fn supergraph_service(&self, service: supergraph::BoxService) -> supergraph::BoxService {
service
}
fn execution_service(&self, service: …
```

Exports `Endpoint` struct

---

NEXT_CHANGELOG.md
apollo-router/src/router.rs

Fix #35 
This adds support for reloading configuration when receiving the SIGHUP signal. This only works on unix-like platforms, and only with the configuration file

reload the configuration when receiving the SIGHUP signal

---

NEXT_CHANGELOG.md
apollo-router/src/services/execution_service.rs
apollo-router/src/services/subgraph_service.rs
apollo-router/src/services/supergraph_service.rs

When I was investigating connection resets I noted that we weren't following tower documentation with respect to [cloning inner services](https://docs.rs/tower/latest/tower/trait.Service.html#be-careful-when-cloning-inner-services). 
This PR addresses that. The change to the supergraph seems to be most invasive. I have run the tests manually many times and the change seems good, but probably worth closer examination.

apply tower best practices to services when cloning inner services

---

DEVELOPMENT.md
NEXT_CHANGELOG.md

also: fix bracketing in NEXT_CHANGELOG.md
fixes: #2012

remove references to git submodules from DEVELOPMENT.md

---

NEXT_CHANGELOG.md
apollo-router/src/plugin/mod.rs
apollo-router/src/plugins/traffic_shaping/mod.rs
apollo-router/src/plugins/traffic_shaping/rate/mod.rs
apollo-router/src/plugins/traffic_shaping/rate/service.rs
apollo-router/src/plugins/traffic_shaping/timeout/layer.rs
apollo-router/src/plugins/traffic_shaping/timeout/mod.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/supergraph_service.rs

The plugin infrastructure works on `BoxService` instances, and makes no guarantee on plugin ordering.
The traffic shaping plugin needs a clonable inner service, and should run right before calling
the underlying service. So this changes the traffic plugin application so it can work directly
on the underlying service. It is still a plugin though, so it keeps the same configuration.

apply traffic shaping on subgraph directly

---

NEXT_CHANGELOG.md
helm/chart/router/README.md
helm/chart/router/README.md.gotmpl

This is a tiny PR but I think it's a valid fix. 
When I tried to run `helm show values apollographql/router` as suggested in the README I got the error `Error: repo apollographql not found`. 
I believe the command should actually be `helm show values oci://ghcr.io/apollographql/helm-charts/router` which works as expected for me.

Fix helm values command

---

NEXT_CHANGELOG.md
apollo-router/src/spec/query.rs
apollo-router/src/spec/query/tests.rs

Fix #2072
`@skip` and `@include` were not implemented for inline fragments and fragment spreads on top level operations

missing `@skip` and `@include` implementation for root operations

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
examples/supergraph-sdl/rust/Cargo.toml
fuzz/Cargo.toml

This updates our dependency on our `apollo-parser` package which brings a few improvements, including more defensive parsing of some operations.  See its CHANGELOG in [the `apollo-rs` repository](https://github.com/apollographql/apollo-rs/blob/main/crates/apollo-parser/CHANGELOG.md#032---2022-11-15) for more details on what's included in the v0.3.2 release.

deps: Update `apollo-parser` to `v0.3.2`

---

docs/source/configuration/apollo-telemetry.mdx

The newer spaceport advanced configuration is actually very much recommended!

docs: remove note about external spaceport in advanced configuration

---

NEXT_CHANGELOG.md
apollo-router/src/services/subgraph_service.rs

This PR tries to address Issue #2117
Here's an example of how the Router would now respond when a subgraph service returns a non-2xx status code and content-type not set to `application/json`.
```
{
"data": null,
"errors": [
{
"message": "HTTP fetch failed from 'my-service': 401 Unauthorized",
"path": [],
"type": "SubrequestHttpError",
"service": "my-service",
"reason": "HTTP fetch failed from 'my-service': 401 Unauthorized"
}
}
]
}
```

Improve errors when subgraph service returns a non-2xx status code

---

NEXT_CHANGELOG.md
docs/source/configuration/cors.mdx

fixes #2151
The docs match regex example was wrong, it was missing ^ at the beginning and $ at the end. `$` marks the end of a string, which could be a safety issue.

Docs: Update cors match regex example:

---

NEXT_CHANGELOG.md
dockerfiles/Dockerfile.router
dockerfiles/diy/build_docker_image.sh
dockerfiles/diy/dockerfiles/Dockerfile.repo
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
docs/source/containerization/overview.mdx

fixes: #2135
fixes: #2145 
This PR repurposes the -debug image to make it the basis for a memory tracking image which we can use for investigating router memory issues via heaptrack. (https://github.com/KDE/heaptrack)
The PR is a *breaking* change because it now automatically starts the router under the control of heaptrack. Technically, it's not really a breaking change and it's certainly not an API change, but I really want to draw people's attention to the fact that the debug image will now execute a lot slower than the non-debug image and use a lot more memory (to track memory with...).
I've updated the docker documentation to show how to mount a local directory to store the heaptrack data. I haven't updated the kubernetes docs, because we don't go into that level of detail and we …

improve router docker debug image

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__upgrade__test__move_non_existent_field.snap
apollo-router/src/configuration/upgrade.rs

Issue was introduced with #2116 but no release had this in.
Move operations would insert data in the config due to the delete magic value always getting added. Now we check before adding such values.
We may need to move to fluvio-jolt longer term.

Fixes #2123

---

NEXT_CHANGELOG.md
dockerfiles/diy/build_docker_image.sh

The addition of the `-r` flag broke the existing logic for processing the `-b` flag with non `-r` repos.
This fixes the logic and prints additional information about which repo is being used to build the image.

recent changes to add support for local repos broke the script

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/traffic_shaping/mod.rs
apollo-router/src/plugins/traffic_shaping/retry.rs
docs/source/configuration/traffic-shaping.mdx

request retries are deactivated by default on mutations

---

NEXT_CHANGELOG.md
apollo-router/src/axum_factory/axum_http_server_factory.rs
apollo-router/src/cache/mod.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/introspection.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/router.rs
apollo-router/src/services/supergraph_service.rs
docs/source/configuration/caching.mdx
docs/source/configuration/overview.mdx

Fix #2075
This implements @BrynCooke's suggestion from #2075. I did not add the option for introspection because it did not feel very useful, and would be a breaking change for the configuration format. If we really need to cache introspection responses, that could be done as part of the whole response caching feature.
Example configuration:
```yaml
supergraph:
apq:
experimental_cache:
in_memory:
limit: 512
redis:
urls: ["redis://..."]
query_planning:
experimental_cache:
in_memory:
limit: 512
redis:
urls: ["redis://..."]
```

in memory and Redis cache configuration

---

NEXT_CHANGELOG.md
apollo-router/src/services/snapshots/apollo_router__services__supergraph_service__tests__deferred_fragment_bounds_nullability-2.snap
apollo-router/src/services/snapshots/apollo_router__services__supergraph_service__tests__deferred_fragment_bounds_nullability.snap
apollo-router/src/services/supergraph_service.rs

fixes: #2169
Add a new test to confirm this is the case.

verify that deferred fragment acts as a boundary for nullability rules

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/mod.rs

fix: panic when dev mode enabled with empty config file

---

NEXT_CHANGELOG.md
docs/source/configuration/health-checks.mdx
docs/source/configuration/metrics.mdx

Docs: Add a disclaimer for users who set up health-checks and prometheus endpoints in a containers environment.
fixes #2079
The health check and the prometheus endpoint listen to 127.0.0.1 by default. While this is a safe default, it prevents other pods from performing healthchecks and scrapping prometheus data. This behavior and customization is now documented.

Docs: Add a disclaimer for users who set up health-checks and prometheus endpoints in a containers environment.

---

NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/plugins/telemetry/apollo_exporter.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/telemetry/tracing/apollo.rs
apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
apollo-router/src/plugins/telemetry/tracing/snapshots/apollo_router__plugins__telemetry__tracing__apollo_telemetry__test__condition_else.snap
apollo-router/src/plugins/telemetry/tracing/snapshots/apollo_router__plugins__telemetry__tracing__apollo_telemetry__test__condition_if.snap
apollo-router/src/plugins/telemetry/tracing/snapshots/apollo_router__plugins__telemetry__tracing__apollo_telemetry__test__trace_id.snap
apollo-router/src/plugins/telemetry/tracing/testdata/condition_else_spandata.yaml
apollo-router/src/plugins/telemetry/tracing/testdata/condition_if_spandata.yaml
apollo-router/src/query_planner/execution.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/query_planner/plan.rs
apollo-router/src/spaceport/proto/reports.proto
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap
xtask/src/commands/compliance.rs

You can now view traces in Apollo Studio as normal.
Fixes #1600
The main file to review is: apollo-router/src/plugins/telemetry/mod.rs
I've added a bunch of testing, but have not enhanced the jaeger test as I think we want to use tracing test for this.

Added Apollo Tracing support for `@defer`.

---

NEXT_CHANGELOG.md
apollo-router/src/axum_factory/axum_http_server_factory.rs
apollo-router/src/cache/mod.rs
apollo-router/src/cache/redis.rs
apollo-router/src/cache/storage.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/introspection.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/router.rs
apollo-router/src/services/layers/apq.rs
apollo-router/src/test_harness.rs

* check for Redis connection issues
* use a null byte as separator for Redis key to prevent potential injections in the future
* mark all of Redis caching as license key functionality under Elastic License v2

stabilize Redis caching for APQ and query plan

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/rhai.rs
docs/source/customizations/rhai-api.mdx

This adds support for setting a header map key with an array. This causes the HeaderMap key/values to be appended() to the map, rather than inserted().
Useful when setting cookies with multiple "set-cookie" for example.
fixes: #2211

add support for appending to header map from rhai

---

apollo-router/src/services/subgraph_service.rs

Fix expected content-type error message that had hard-coded content type 'application/graphql+json', instead of 'application/graphql-response+json' that is actually expected.

Fix expected content-type error

---

DEVELOPMENT.md
NEXT_CHANGELOG.md
apollo-router-scaffold/src/lib.rs
apollo-router/Cargo.toml
apollo-router/src/axum_factory/tests.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/plugins/expose_query_plan.rs
apollo-router/src/plugins/include_subgraph_errors.rs
apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
apollo-router/src/plugins/traffic_shaping/mod.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/query_planner/fetch.rs
apollo-router/src/router_factory.rs
dockerfiles/diy/dockerfiles/Dockerfile.repo
licenses.html
rust-toolchain.toml

Update Rust MSRV to 1.65

---

docs/source/index.mdx

Docs-only change to remove talking about Rust at the top of router docs. 
The router can now be talked about as a first-class way to operationalize supergraph runtime -- we no longer need to compare it to the legacy Gateway. We also don't need people worrying about what language the router is implemented in as part of their initial exploration.

Unfeature Rust as a first impression of the router

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/mod.rs

It is set here: https://github.com/apollographql/router/pull/2236/files#diff-37adf9e170c9b384f17336e5b5e5bf9cd94fd1d618b8969996a5ad56b635ace6R430

set_meter_provider was being called twice which had the effect of completely disabling metrics.

---

NEXT_CHANGELOG.md
dockerfiles/diy/dockerfiles/Dockerfile.repo

Add protoc to diy router build

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/include_subgraph_errors.rs
apollo-router/src/spec/query.rs

Fix #1818 
the path is used to decide whether to assign the error on the primary or deferred response

keep the error path when redacting subgraph errors

---

NEXT_CHANGELOG.md
apollo-router/src/files.rs
apollo-router/src/plugins/rhai.rs
apollo-router/src/router.rs

To get consistent behaviour across multiple platforms and file systems.
fixes: #2245
The watcher may not be as reactive, but I think it's reactive enough for things which shouldn't change frequently.
As a bonus, we no longer get events if the content is the same, so less spurious reloads, which is good. That means I had to modify the tests though to use different contents.
The rhai file watching appeared to be working fine, but to be safe I converted it to the PollWatcher as well.

replace notify recommended watcher with poll watcher

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/apollo.rs
apollo-router/src/plugins/telemetry/apollo_exporter.rs
apollo-router/tests/snapshots/apollo_reports__client_name.snap
apollo-router/tests/snapshots/apollo_reports__client_version.snap
apollo-router/tests/snapshots/apollo_reports__condition_else.snap
apollo-router/tests/snapshots/apollo_reports__condition_if.snap
apollo-router/tests/snapshots/apollo_reports__non_defer.snap
apollo-router/tests/snapshots/apollo_reports__send_header.snap
apollo-router/tests/snapshots/apollo_reports__send_variable_value.snap
apollo-router/tests/snapshots/apollo_reports__trace_id.snap

This change has not been released but the issue was introduced in #2277 Fixes #2267
Metrics will always have the definitive operation count.

As we are now using metrics for all requests we should not set operation count

---

apollo-router/src/files.rs

fix(hotreload): do not watch the entire directory, only config file

---

NEXT_CHANGELOG.md
apollo-router/src/services/subgraph_service.rs
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap

feat: Add outgoing request URLs for the subgraph calls in the OTEL spans

---

NEXT_CHANGELOG.md
apollo-router/build/studio.rs

`tonic_build` changes timestamps by a few nanos.
Router only needs to re-run `tonic_build` if `reports.proto` changes, and that's managed by the build.rs file already via `println!("cargo:rerun-if-changed={}", reports_src.to_str().unwrap());`
This just disables `tonic_build`'s rerun emits so it's fully managed by `apollo-router`

Only rebuild protos if proto source changes

---

NEXT_CHANGELOG.md
apollo-router/src/services/router_service.rs

close #2301 
here is the new error you'll receive:
```json
{
"message": "Invalid GraphQL request",
"details": "failed to deserialize the request body into JSON: invalid type: string \"null\", expected a map at line 1 column 100",
"code": "INVALID_GRAPHQL_REQUEST"
}
}
```

fix: add more details when graphql request is invalid

---

docs/source/federation-version-support.mdx

This should have been updated as part of the release process for the 1.6.0
release to indicate that Federation v2.2.2 was the active version as of that
release.  Apologies to the folks who rely on this information being accurate
to do their job correctly.
In the future, we will introduce automation to eliminate the human factor of
this, and that work is being tracked in https://github.com/apollographql/router/issues/2261.

docs: Retroactively update `federation-version-support.mdx` for v1.6.0.

---

NEXT_CHANGELOG.md
apollo-router/src/axum_factory/tests.rs
apollo-router/src/services/router_service.rs

fix: specify content type to application/json when it throws an invalid graphql request error

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/schema.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__it_does_not_leak_env_variable_values.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_bad_type.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_errors_after_first_field.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_errors_after_first_field_env_expansion.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_inline_sequence.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_inline_sequence_env_expansion.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_sequence.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_sequence_env_expansion.snap
apollo-router/src/configuration/tests.rs

Fix #2180
When starting the router with this configuration file, that contains errors due to invalid data and fields that are not recognized:
```yaml
supergraph:
listen: 127.0.0.1:4000
introspection: "a"
query_planning:
experimental_cache:
redis:
urls: ["rediss://:router@127.0.0.1:4101"]
sandbox:
enabled: true
tls:
subgraphs:
certificate_authorities: "${file./home/geal/dev/test/tls-proxy/server.crt}"
include_subgraph_errors:
all: true
```
The router will print this:
```
2023-01-05T10:57:42.878484Z ERROR configuration had errors: 
1. /supergraph/introspection
supergraph:
listen: 127.0.0.1:4000
introspection: "a"
^----- "a" is not of type "boolean"
2. /supergraph/query_planning/experimental_cache
supergraph:
listen: 127.0.0.1:4000
introspection: "a"
query_planning:
experimental_cache:
┌ …
```

show multiple validation errors

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/migrations/0004-defer_support_ga.yaml
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__upgrade_old_configuration@defer_support_ga.router.yaml.snap
apollo-router/src/configuration/testdata/migrations/defer_support_ga.router.yaml
apollo-router/src/introspection.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/tests/integration_tests.rs
docs/source/executing-operations/defer-support.mdx

Fixes #2368
Removes last mentions of `preview` now that `@defer` has reached GA.
**Checklist**
~~- [ ] Changes are compatible[^1]~~
~~- [ ] Performance impact assessed and acceptable~~
~~- [ ] Integration Tests~~
**Exceptions**
**Notes**
[^3]. Tick whichever testing boxes …

Remove last mentions of `preview` for `@defer` support.

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/telemetry/apollo.rs
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap
docs/source/configuration/apollo-telemetry.mdx

This PR reverses the choice made in https://github.com/apollographql/router/pull/2356 which came up originally in https://github.com/apollographql/router/issues/2339.  By default, we would like the user experience to be that Apollo Studio tracing works at a low sampling rate when you've provided an Apollo Studio API key.  To disable field level tracing (FTV1) entirely, the rate can be set to `0.0`.

change the default value for `apollo.field_level_instrumentation_sampler`

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/schema.rs
apollo-router/src/orbiter/mod.rs
apollo-router/src/orbiter/snapshots/apollo_router__orbiter__test__visit_config_that_needed_upgrade.snap

Fixes #2397
When we reach orbiter integration we should have a valid configuration. This change stashes the validated and expanded config rather than the raw config so that we don't have to worry about doing this stuff again within the orbiter code.
**Checklist**
- ~~[ ] Documentation[^2] completed~~
- ~~[ ] Performance impact assessed and acceptable~~
- ~~[ ] Integration Tests~~
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when …

Orbiter integration runs on expanded validated config rather than raw

---

apollo-router/src/spec/query.rs
apollo-router/src/spec/query/tests.rs
apollo-router/src/spec/schema.rs

`IntValue::source_string()` can include whitespace, which causes `i64::from_str` to fail.
**Checklist**
**Exceptions**
- Compat: I’m not sure what the macro-consequences are of the router incorrectly thinking there is no default value, so I don’t know if anyone could (accidentally) rely on this bug
- Docs: Is such a bugfix changelog-worthy?
- Perf: I expect (but have not measured) impact, if any, to be indistinguishable from noise
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to …

Fix default value parsing of integer fields of input types

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/schema.rs
apollo-router/src/executable.rs
apollo-router/src/orbiter/mod.rs
apollo-router/src/orbiter/snapshots/apollo_router__orbiter__test__create_report_incorrect_type_validated_yaml.snap
apollo-router/src/orbiter/snapshots/apollo_router__orbiter__test__create_report_invalid_validated_yaml.snap

- Fix #2412
Make the orbiter code gracefully degrade if there are issues rather than panic.
Cleaned up configuration creation code.
Put validated schema in an option rather than an Arc.
Note that there are still expects in the code, but these should remain as they would point to actual bugs.
**Checklist**
**Exceptions**
This doesn't affect perf or need new docs.
An integration test could have been written, but I feel this is better covered by the unit tests.
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so …

Make Orbiter code gracefully handle invalid validated_yaml

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/tests/snapshots/apollo_reports__client_name.snap
apollo-router/tests/snapshots/apollo_reports__client_version.snap
apollo-router/tests/snapshots/apollo_reports__condition_else.snap
apollo-router/tests/snapshots/apollo_reports__condition_if.snap
apollo-router/tests/snapshots/apollo_reports__non_defer.snap
apollo-router/tests/snapshots/apollo_reports__send_header.snap
apollo-router/tests/snapshots/apollo_reports__send_variable_value.snap
apollo-router/tests/snapshots/apollo_reports__trace_id.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap

- Fix #2403
Before this PR is `send_headers`  was set to `none` we sent header names with empty header values. Now we don't send anything
**Checklist**
**Exceptions**
**Notes**
- please …

fix(telemetry): don't send header names on Studio if send_headers is None

---

apollo-router/src/axum_factory/axum_http_server_factory.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/executable.rs
docs/source/configuration/health-checks.mdx
helm/chart/router/README.md
helm/chart/router/values.yaml

This doesn't attempt to bring full consistency (which should have a more principled pass done at some point), but this starts by:
- In human-readable references to the Router's health check, they are now referred to as "Health check" to match the treatment in our documentation.
- Reverts a cosmetic change that was included in #2173 (e137df2b4) which changed the captialization of some console message output.
- Capitalizes another lower-case log message about the "healthcheck" which was immediately followed by a capitalized line about "GraphQL".
Before:
```
Apollo Router v1.8.0 // (c) Apollo Graph, Inc. // Licensed as ELv2 (https://go.apollo.dev/elv2)
anonymous usage data is gathered to inform Apollo product development.  See https://go.apollo.dev/o/privacy for more info
healthcheck …
```

nit: Cosmetic capitalization/grammatical tweaks

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/expansion.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/schema.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__expansion__test__env_defaults.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__expansion__test__prefixed.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__expansion__test__unprefixed.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__default_config_has_defaults.snap
apollo-router/src/configuration/tests.rs
apollo-router/src/orbiter/snapshots/apollo_router__orbiter__test__create_report.snap
apollo-router/src/orbiter/snapshots/apollo_router__orbiter__test__visit_config.snap
apollo-router/src/orbiter/snapshots/apollo_router__orbiter__test__visit_config_that_needed_upgrade.snap

- Fix #2429
There are lots of steps in producing final validated configuration, this is handled when configuration is hydrated from a string. Previously Configuration::default() was using the builder rather than the parse logic.
In addition the defaulting mechanism now works directly against config with the env variables, so prefixing no longer interferes.
**Checklist**
**Exceptions**
No docs needed as this is not a change or new  in functionality.
**Notes**
In future we should consider removing the `Configuration::builder()`. We can leave the fake one. Goal would be that we have a single way of creating Configuration rather than the multiple that …

Make Configuration::default() go through centralised parse validation and expansion logic.

---

NEXT_CHANGELOG.md
docs/source/customizations/native.mdx

Two commits intentionally.  I recommend only reviewing the second as the first one does re-ordering which - if reivewed with the second - will be difficult:
- [NEXT_CHANGELOG.md re-ordering edits prior to v1.9.0.](https://github.com/apollographql/router/pull/2439/commits/83178ebb3959ad5cfbec2516a67b2151de9c8f19) https://github.com/apollographql/router/pull/2439/commits/83178ebb3959ad5cfbec2516a67b2151de9c8f19
- [NEXT_CHANGELOG.md copy/stylistic edits prior to v1.9.0.](https://github.com/apollographql/router/pull/2439/commits/2a73266770ab3aae9c08e435f27a211e3f7639ab) https://github.com/apollographql/router/pull/2439/commits/2a73266770ab3aae9c08e435f27a211e3f7639ab

NEXT_CHANGELOG.md editorial and stylistic edits prior to v1.9.0.

---

apollo-router/src/router_factory.rs
apollo-router/src/services/subgraph_service.rs

Subgraph APQ was still enabed by default, but not in the configuration

fix missing condition on default value for APQ

---

NEXT_CHANGELOG.md
apollo-router/src/error.rs
apollo-router/src/spec/schema.rs

Fixes https://github.com/apollographql/router/issues/2269
**Checklist**
**Exceptions**
**Notes**
- please raise a …

Parse introspection types separately from the provided schema

---

Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-benchmarks/benches/memory_use.rs
apollo-router-benchmarks/build.rs

This will help evaluate the impact of keeping long-lived apollo-compiler contexts.
**Checklist**
**Exceptions**
- No run-time code change
- Internal tool, the doc-comment shows how to use it
- No run-time code change
- `cargo test` compiles benches (but doesn’t run them)
**Notes**
[^3]. Tick …

Add process-level memory consumption benchmark

---

NEXT_CHANGELOG.md
apollo-router/src/spec/query.rs
apollo-router/src/spec/query/tests.rs

With such a schema, some parsing code in the Router would incorrectly return an error because it was assuming the default name. Similarly with a root mutation operation not named `Mutation`.
**Checklist**
**Exceptions**
**Notes**
[^3]. Tick whichever testing boxes are …

Fix handling of root query operation not named `Query`

---

apollo-router/src/lib.rs
apollo-router/src/spec/fragments.rs
apollo-router/src/spec/query.rs
apollo-router/src/spec/schema.rs
apollo-router/src/spec/selection.rs
apollo-router/tests/compiler_integration.rs

Continuation of https://github.com/apollographql/router/pull/2401
Similar to there, the new `Query::parse_with_hir` constructor is not used yet during normal Router operation.
The two implementations return identical results
for all of a corpus of ~1.2 million production queries.
**Checklist**
**Exceptions**
- Compat: expect identical behavior (which is supported by testing)
- Docs: no user-visible change
- Perf: expect increase of memory use during query parsing, but unknown how significant. And parsing is short, and its results cached.
- Manual testing with https://github.com/apollographql/harness-vs-apollo-rs/pull/1
**Notes**
[^1]. It may be appropriate to bring upcoming …

Add (unused) query parsing based on apollo-compiler

---

NEXT_CHANGELOG.md
apollo-router/src/axum_factory/axum_http_server_factory.rs
apollo-router/src/axum_factory/tests.rs

- Fix #2471
If you provide this configuration:
```yaml
supergraph:
path: /*
```
Since release `1.8` and due to [axum upgrade](https://github.com/tokio-rs/axum/releases/tag/axum-v0.6.0) it won't listen on `localhost` without a path. This PR intend to fix the axum routing behavior.
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part of many changes. Where applicable …

fix(axum_router): if you provide /* as path it also listens to root route without path

---

NEXT_CHANGELOG.md
apollo-router/src/spec/query.rs
apollo-router/src/spec/schema.rs

This enables the new parsing code added in https://github.com/apollographql/router/pull/2401 and https://github.com/apollographql/router/pull/2411.
**Checklist**
**Exceptions**
Perf: data structures are unchanged so no increase in long-lived memory consumption is expected: Salsa databases and caches are dropped when `parse()` returns.
**Notes**
[^2]. Configuration is an important part of many changes. Where applicable …

Parse schemas and queries with `apollo-compiler`

---

apollo-router/src/services/execution.rs
apollo-router/src/services/supergraph_service.rs
apollo-router/src/spec/query.rs
apollo-router/src/spec/schema.rs

Compilers are kept with hot Salsa memoization database in the in-memory query plan cache, and lazily-initialized for queries from the Redis cache.
We would expect some increase in memory use, but the impact is smaller than noise level (variation between runs) in `cargo bench -p apollo-router-benchmarks --bench memory_use`, which measures physical (resident) memory of a Router process after processing each of 100 queries.
<details>
Tab-separated results, in MiB:
```
Queries	dev, run #1	dev, run #2	dev, run #3	dev, run #4	PR, run #1	PR, run
#2	PR, run #3	PR, run #4
0	65.39	61.34	60.92	65.47	60.98	65.28	60.84	61.89
1	67.75	63.5	63.17	67.64	63.3	67.5	63.08	64.11
2	69.47	63.83	63.78	67.98	63.73	67.92	64.02	64.66
3	70.97	65.06	65.25	69.36	65.05	69.08	65.44	66.25
4	71	65.11	65.31	69.42	65.11 …
```

Make apollo-compiler available in execution::Request (router crate-private)

---

NEXT_CHANGELOG.md
apollo-router/src/orbiter/mod.rs

Fix #2487
The test would output would change if the env variable `APOLLO_TELEMETRY_DISABLED` was set.
Remove `args.anonymous_telemetry_disabled.true` from the test.
**Checklist**
**Exceptions**
**Notes**
[^3]. Tick whichever testing boxes are applicable. If you are adding …

Disregard APOLLO_TELEMETRY_DISABLED env variable in unit test.

---

apollo-router/src/uplink/mod.rs

The first commit extracts a sub-expression into a variable in order to make the second commit have a diff easier to read.
This change matches the example in docs for `with_current_subscriber`, so I assume this was intended. `JoinHandle` is also a future which is why the previous code compiled, but it is never polled.
**Checklist**
**Exceptions**
I don’t really understand this, it just looked suspicious.
**Notes**
[^2]. …

Use `with_current_subscriber` on a spawned task, not a `JoinHandle`

---

Cargo.lock
licenses.html

This follows up https://github.com/apollographql/router/pull/2457 which updated `git2`.  In particular, this also updates the impacted transitive dependency of `libgit2-sys ` which wasn't previously updated and had been triggering our vulnerability alert.  It's also causing our nightly builds to fail right now.
This also updates the license file accordingly.

chore(deps): update git2 and corresponding license file

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/src/cache/mod.rs
apollo-router/src/services/layers/apq.rs
apollo-router/src/services/router_service.rs

Fixes #2502 
The router now sends `cache-control: private, no-cache, must-revalidate` when a persisted query hash was not found.

APQ: Add cache-control header on PERSISTED_QUERY_NOT_FOUND

---

apollo-router/Cargo.toml

Note that the merge from `dev` on the PR this merges into (#2464) already brought this in its `Cargo.lock`, so this just
corrects the `apollo-router`'s `Cargo.toml`.

Update `router-bridge` to `0.1.14+v2.3.0`

---

apollo-router/src/json_ext.rs
apollo-router/src/query_planner/fetch.rs
apollo-router/src/query_planner/plan.rs
apollo-router/src/query_planner/selection.rs
apollo-router/src/services/execution_service.rs
apollo-router/src/spec/selection.rs

Some of the paths returned by the query planner may contain some "fragment", which are really meant to act as type conditions. That is, for some data like:
```json
{
"x": [
{ "__typename": "A", "a": 0 },
{ "__typename": "B", "a": 1 },
{ "__typename": "A", "a": 2 }
],
"y": 42
}
```
and a path `["x", "... on A", "a"]`, then the intend is that this selects the following data:
```json
{
"x": [
{ "__typename": "A", "a": 0 },
{ "__typename": "A", "a": 2 }
]
}
```
but skips the `B` entity in particular.
That logic is currently not implemented, and while fragments in path are parsed, they are otherwise ignored (and so the code currently ends up selecting the `B` entity).
The only place where such fragments may appear in paths currently is in deferred nodes, where the paths are used to select what …

Fix handling of fragments in handling of `Path`

---

Cargo.lock

This follows up https://github.com/apollographql/router/pull/2457 and https://github.com/apollographql/router/pull/2497 which both attempted to update `libgit2-sys`.
The changeset of https://github.com/apollographql/router/pull/2503 inadvertently resulted in a reversion of that version bump, which brought back the offending version and upset our compliance check.
Thankfully, we have tooling that catches this stuff (even if it wasn't on the PR itself).

chore(deps): update `libgit2-sys`, again.

---

apollo-router/src/services/layers/apq.rs
apollo-router/src/services/router_service.rs

When Automatic Persisted Queries are disabled, there's a specific error code that we should use to signal it. That error response can be cached because when APQ is not supported, we can reasonably assume it will still not be supported on the next call.
- Fix #2436
*description here*
**Checklist**
**Exceptions**
**Notes** …

return PERSISTED_QUERY_NOT_SUPPORTED when APQ is disabled

---

.gitattributes
Cargo.lock

Also update the `ahash` crate to demonstrate.
This will hopefully help catch unintentional changes such as the downgrade in https://github.com/apollographql/router/commit/9b8acdcd26e80d11d4d81a2b0b6735cc8b5b616c#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87eL2708-R2710
**Checklist**
**Exceptions**
**Notes** …

Make GitHub show Cargo.lock diffs

---

helm/chart/router/templates/deployment.yaml
helm/chart/router/values.yaml

- Fix #2543
*This leverages https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/ to enable the setting of a `priorityClassName` value which can then be set of the `Deployment` such that pod priority and preemption can be controlled.*
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part of many changes. Where applicable please try to …

Allow for priorityClassName to be set on the Deployment to control pod preemption by the scheduler

---

.changesets/maint_pixel_the_cat.md
apollo-router/tests/integration_tests.rs

- Fix #2548
As FTV1 is only requested a certain percentage of times this was causing sporadic failures in CI.
Disable FTV1 in this test.
**Checklist**
**Exceptions**
**Notes**
- please …

Turn off FTV1 for default integration test

---

.changesets/README.md
.changesets/maint_abernix_changeset_part_2.md
.github/pull_request_template.md
.github/workflows/main.yml
xtask/Cargo.lock
xtask/Cargo.toml
xtask/src/commands/all.rs
xtask/src/commands/changeset/matching_pull_request.graphql
xtask/src/commands/changeset/matching_pull_request.rs
xtask/src/commands/changeset/mod.rs
xtask/src/commands/changeset/scalars.rs
xtask/src/commands/mod.rs
xtask/src/main.rs

This follows up on Phase 1 of the project I started in #2534 by bringing along a tool that lets one stub out the nessary changeset file.
This stubbing takes place through the use of a new command:
cargo xtask changeset create
There are no required arguments to pass, though it's possible to specify some arguments that will shortcut interactive prompts.  For example, the use of the `--class <class>` (where `<class>` is one of `feat`, `maint`, etc.) will skip the interactive prompt asking for precisely that.
In most cases, the prompt has sensible defaults.  Additionally, the tool will attempt to pre-populate the changeset entry with information by matching the branch name the developer is currently working on against any PRs from that branch on GitHub which have a pull request open already. …

chore: Phase 2 of changelog project, now w/ optionally prepopulated CHANGELOG

---

.changesets/maint_on_a_dark_desert_highway.md
Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/router.rs
apollo-router/src/uplink/entitlement.rs
apollo-router/src/uplink/entitlement_query.graphql
apollo-router/src/uplink/mod.rs
apollo-router/src/uplink/schema.rs
apollo-router/src/uplink/schema_query.graphql
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_error_http_fallback.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_error_http_round_robin.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_error_no_retry.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_error_retry.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_failed_from_all.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_fallback.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_invalid.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_round_robin.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_unchanged.snap

Added entitlements uplink logic.
Common uplink code has been pulled out into the module. And some reasonably comprehensive tests have been added.
Code that handles round robin and fallback has been cleaned up, however there is a slight difference in behaviour now.
Previously in round robin mode if a failure occurred the next URL would not be checked until the next loop. Now all urls are tried consecutively.
~~In addition there may have been a potential hang on shutdown if uplink only ever reported `UNCHANGED` as the sender was never checked to see if it had been closed.~~ This is not an issue as it will stop if the main thread is exited.
This work may warrant entering the changelog, so will create an issue etc for this next week.
- Fix #2547
*description here*
**Checklist**
Complete the …

Add entitlements uplink integration

---

.circleci/config.yml

This merges a change from `main` to the `dev` branch that temporarily disables the use of `NEXT_CHANGELOG.md` for the `gh release create` command that was inadvertently left in `.circleci/config.yml` during the work that occurred in #2534.
The work to track follow-up is captured in https://github.com/apollographql/router/issues/2566.

Just use a `--notes-file` of `/dev/null` to get the release out

---

.changesets/fix_tidy_cherries_fly.md
apollo-router/src/services/supergraph_service.rs
apollo-router/src/spec/query.rs
apollo-router/src/spec/query/tests.rs

…oducted by `@interfaceObject`
The introduction of `@interfaceObject` in federation 2.3 has for consequence that a subgraph (that uses an `@interfaceObject`) may return in its response a `__typename` that corresponds to an interface type in the supergraph (but which, locally to that subgraph, is an object type).
The idea is that if that `__typename` is requested, then the query planner will ensure that another follow-up fetch will override that value so it maps to a proper object type.
However, in some cases, that `__typename` is not queried, nor is there another reason to resolve the actual underlying implementation type of the underlying object (meaning that only fields of the interface are queried), and in that case the `__typename` may still point to the interface type when …

fix: `__typename` when formatting response in some `@interfaceObject` cases

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/router.rs
apollo-router/src/state_machine.rs
apollo-router/src/uplink/entitlement.rs
apollo-router/src/uplink/entitlement_stream.rs
apollo-router/src/uplink/mod.rs
apollo-router/src/uplink/schema_stream.rs

Add WarnEntitlement and HaltEntitlement events and EntitlementExpander stream combinator.
When an entitlement event is detected in the stream it registers the warn_at and halt_at times to also generate WarnEntitlement and HaltEntitlement events.
If a subsequent entitlement is detected then existing checks cleared and new checks created if needed.
For reviewers.
* Some code has been moved around, but is unchanged. The body of what needs reviewing is: https://github.com/apollographql/router/pull/2568/files#diff-5f0172e9051bdb6e7cf11dc4b51bdbf1dc516ba0d188f6bdaed117012af8db82R109-R386
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate …

Warn and halt entitlements events

---

docs/source/configuration/metrics.mdx

Include new sections on the docs page so that we can easily find, jump to, and link to the available metric names

[docs] Update Router metrics headers

---

.changesets/maint_simon_xtask_fmt.md
xtask/src/commands/changeset/matching_pull_request.rs
xtask/src/commands/changeset/mod.rs
xtask/src/commands/lint.rs
xtask/src/commands/release.rs

`xtask` which runs `cargo fmt --all` which reformats of Rust code in all crates of the workspace. However the code of xtask itself is a separate workspace. In order for it to be formatted with the same configuration, running a second `cargo` command is required. This adds that second command, and applies the corresponding formatting.
Fixes https://github.com/apollographql/router/issues/2557
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your …

Run rustfmt on xtask too

---

renovate.json5

This follows up on the original https://github.com/apollographql/router/pull/1336 by trying to fix the case of the two Renovate PRs:
* #2588
* #2589
We'll ignore `rust` images for [the `dockerfile` manager](https://docs.renovatebot.com/modules/manager/) since they'll be covered by the annotations that group these together in our Dockerfiles and Docs, etc.

chore(renovate): Improve Rust version bumping grouping logic

---

apollo-router/Cargo.toml

Fixes the warning:
> version requirement `0.1.15+v2.3.1` for dependency `router-bridge` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
A version requirement in `[dependencies]` is not a version number. `0.1.15+v2.3.1` is interpreted as `>=0.1.15, <0.2.0`, same as `0.1.15` would since semver metadata (starting at `+`) is ignored for the purpose of version ordering.
See also https://doc.rust-lang.org/cargo/reference/resolver.html#version-metadata
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please …

Remove semver metadata from version requirement

---

.changesets/fix_lot_skid_monster_communicate.md
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/telemetry/snapshots/apollo_router__plugins__telemetry__tests__it_test_prometheus_metrics.snap

When it created a status code 500 we didn't provide the `status` attribute in metrics. Instead of having an empty `status` attribute on your metrics you'll have `status="500"`.

fix(telemetry): add missing status attribute

---

docs/source/federation-version-support.mdx

This applies the same commit from https://github.com/apollographql/router/pull/2618 but directly to `main` so it gets out prior to the next release.

docs: Update federation version support table (for `main`)

---

.changesets/feat_make_terminationgraceperiodseconds_configurable_in_helm.md
helm/chart/router/README.md
helm/chart/router/templates/deployment.yaml

Makes the `terminationGracePeriodSeconds` configurable.
This is related to https://github.com/apollographql/router/issues/2539, and is needed to properly shutdown the router without dropping any of the requests.
For example, if router supergraph timeout is 45, then the `terminationGracePeriodSeconds` should be modified accordingly.
**Checklist**
**Exceptions**
**Notes** …

feat(helm): make terminationGracePeriodSeconds configurable

---

.changesets/feat_uuid_unix_timestamp_rhai_functions.md
apollo-router/src/plugins/rhai.rs
docs/source/customizations/rhai-api.mdx

*Description*
When building Rhai scripts, it's often that you'll need to add headers that either uniquely identify a request, or append timestamp information for processing information later, such as crafting a trace header or otherwise. 
While the default `timestamp()` and associated functions (e.g. `apollo_start`) can be used for a somewhat similar function, it also isn't able to be translated into an epoch. As a result, it doesn't acutely address the asks we've heard from customers. 
**Checklist**
- Tests added and passing
**Notes**
* Unsure on how to measure performance impact; would be happy with information and I can add it
* Unsure how new functions in Rhai are tested, as the existing tests don't …

Support for UUID and Unix timestamp functions in Rhai

---

.changesets/maint_scuba_dictionary_gem_rooftop.md
apollo-router/src/configuration/cors.rs
apollo-router/src/configuration/tests.rs

Allowing any origins in the router configuration is done this way:
```yaml
cors:
allow_any_origin: true
```
It is however intuitive for users to try to set it up like so:
```yaml
cors:
origins:
- "*"
```
Unfortunately, this won't work and the error message was neither comprehensive nor actionnable:
```
ERROR panicked at 'Wildcard origin (`*`) cannot be passed to `AllowOrigin::list`. Use `AllowOrigin::any()` instead'
```
This change adds a meaningful error message which will help you successfully set up the router:
```
Invalid CORS configuration: use `allow_any_origin: true` to set `Access-Control-Allow-Origin: *`
```

CORS: Give a more meaningful message for users who misconfigured allow_any_origin

---

xtask/src/commands/changeset/mod.rs
xtask/src/commands/release.rs

Probably not the final phase of this project, but another step in the right direction of automating the changelog juggling.
This follows up on #2545 [1] and #2534 [2], which introduced an `xtask` command for automatically creating a changeset file in the `.changesets` directory.
With this addition, the existing release step (also `cargo xtask`) will now roll-up those changesets and plop them into the `CHANGELOG.md`, obeying a pre-prescribed order for how they should be presented and utilizing the file prefixes to bucket them accordingly.
The details of the changesets behaviour is outlined in the README of the `.changesets` directory, referenced below [3].
[1]: https://github.com/apollographql/router/pull/2545
[2]: https://github.com/apollographql/router/pull/2534
[3]: …

chore: Phase 3 of changelog project

---

apollo-router/src/executable.rs

The entitlement option is unused for now.

Hide (currently) unused cli option

---

.changesets/fix_bryn_service_name_default.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/telemetry/config.rs

Fixes #2641
The default tracing service name should be `router`. At some point expansion by defaults was changed, which has lead to the default being `${env.OTEL_SERVICE_NAME:-router}`.
This new default was expanded, and the resulting service name in tracing tools is unpleasant.
`telemetry.tracing.trace_config.service_name` is now defaulted to `router` again.
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when to do …

Fix default tracing service name.

---

.changesets/fix_simon_sampling.md
apollo-router/src/plugins/telemetry/mod.rs

Because tracing can be costly, it is only enabled for a configurable fraction of requests. Each request is selected for tracing or not with a corresponding probability. This used to be done as part of the subgraph service, meaning that when a single supergraph request handled by the Router involves making multiple subgraph requests, it would be possible (and likely) that tracing would only be enabled for some of those sub-requests. If this same supergraph request is repeated enough times the aggregated metrics should be fine, but for smaller sample size this risks giving an unexpectedly partial view of what’s happening.
Now each supergraph request recieved by the Router is sampled or not for FTV1, and all corresponding subgraph requests reuse the same result.
Fixes …

Sample FTV1 by supergraph request instead of by subgraph request

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/improvement.md

Removes the default `triage` label applied to the issues that are opened on this repo.
No changelog for this one, but this doesn't seem like necessary labeling anymore, to me.
Thoughts?

chore: Remove `triage` labels from issue templates

---

.changesets/fix_lasso_howl_conductor_crop.md
apollo-router/src/executable.rs

if the Executable builder is used, it should not try to parse command line arguments itself, because the wrapping application may come with its own set of arguments.
With this change, it is possible to parse command line arguments before building the Executable, passing the required parameters to the builder. And the default behaviour is still to parse them directly so this is not a breaking change.
The main API change here is exposing the `Opt` struct, and adding a method to the builder

make argument parsing optional in Executable

---

apollo-router/src/plugins/telemetry/metrics/prometheus.rs
apollo-router/tests/common.rs
apollo-router/tests/metrics_tests.rs

Add required content-type header for publishing Datadog metrics from Prometheus.
"content-type": text/plain; version=0.0.4
Fixes #2697
After this change the `content-type` header is added:
```
shaunp@IT-USA-VY1069 router % http http://localhost:9090/metrics
HTTP/1.1 200 OK
content-length: 256
content-type: text/plain; version=0.0.4
date: Mon, 27 Feb 2023 23:32:25 GMT
apollo_router_session_count_total{listener="http://0.0.0.0:9090",service_namespace="api-platforms",service_name="one-graph-router"} 1
```
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please …

fix: Add content-type header for publishing Datadog metrics

---

apollo-router/tests/jaeger_test.rs

https://github.com/apollographql/router/pull/2673 disabled the only test of `apollo-router/tests/jaeger_test.rs` on platforms other than Linux x64, but left helper functions and other that items that support that test. This resulted in "unused" warnings, making `cargo xtask lint` fail in clippy.
This change the `#[cfg]` attribute to apply to the entire module instead of the test function, making `jaeger_test.rs` an empty file after macro expansion.
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The …

Disable all of jaeger_test.rs on non-linux x64

---

.changesets/breaking_geal_authorization_check.md
.changesets/fix_telegram_fossil_doodle_sandbox.md
Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/plugins/authentication/mod.rs
apollo-router/src/plugins/authentication/tests.rs
apollo-router/src/plugins/rhai/mod.rs
apollo-router/tests/fixtures/require_authentication.rhai
docs/source/configuration/authn-jwt.mdx

*Breaking change*: this changes the JWT plugin's behaviour, it now lets all requests go through
now the authentication plugin only rejects invalid tokens (bad signature, expired, etc) but lets requests without tokens go through. The authorization decision is then handled later.
As an example, a rhai script can be used to refuse all unauthenticated requests
This also adds support for the `extensions` field in GraphQL errors generated from rhai
TODO:
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do …

move authorization out of the authentication plugin

---

.changesets/maint_geal_redis_fred.md
.circleci/config.yml
Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/cache/mod.rs
apollo-router/src/cache/redis.rs
apollo-router/src/cache/storage.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/tests/redis_test.rs

Fix #2623
Fix #2606
This replaces our usage of the `redis` and `redis-cluster-async` crates with `fred`, which comes with support for Redis cluster and rustls out of the box. Rustls support is only available in fred 6.0.0-beta.2 though, not in a stable release.
**Checklist**

Use the fred Redis client

---

apollo-router/src/services/external.rs

Fast followup to #2546, skip serializing None sent to the external extensibility coprocessor

fixup: skip serializing external payload if none

---

apollo-router/src/configuration/migrations/0006-apq.yaml
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__upgrade_old_configuration@supergraph_apq_to_apq.router.yaml.snap
apollo-router/src/configuration/testdata/migrations/supergraph_apq_to_apq.router.yaml
apollo-router/src/router_factory.rs
apollo-router/src/services/layers/apq.rs
apollo-router/src/services/router_service.rs
apollo-router/tests/redis_test.rs
docs/source/configuration/caching.mdx
docs/source/configuration/overview.mdx
router-old.yaml

For improved usability we will be moving items out of `supergraph` in router.yaml. This is because various plugins use stages as part of their yaml config.
```diff
< apq:
<   enabled: true
---
> supergraph:
>   apq:
>     enabled: true
```
Fixes #2744 
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part of many changes. Where applicable please try to document …

Move APQ to top level

---

.changesets/maint_bryn_fix_telemetry_plugin_visibility.md
apollo-router/src/lib.rs
apollo-router/src/plugins/telemetry/config.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/services/supergraph_service.rs

The telemetry plugin is currently pub. However, since the refactor of the Telemetry plugin and associated tests this doesn't need to be.
It is not a breaking change to fix this as the plugin was exported under the _private module which was clearly marked as internal. However, this can be removed altogether.
Previously we also had the Telemetry struct exported as TelemetryPlugin. This is no-longer necessary so I renamed the struct for consistency.

Fix visibility of telemetry plugin

---

docs/source/configuration/header-propagation.mdx

This was previously written for an old version of the router that used `router_service` instead of `subgraph_service`.

fix(docs): correct cookie forwarding rhai example

---

.changesets/fix_storeroom_dumbbell_searchlight_nudge.md
apollo-router/src/state_machine.rs

Previously if the router failed to reload either for config or for schema changes it would discard the new information.
Now It will always retain the new information.
Changing this behaviour means that the router must enter a good configuration state before it will reload rather than reloading with potentially inconsistent state.
For example:
1. Router starts with valid schema and config.
2. Router config is set to something invalid and restart doesn't happen. Router receives a new schema, but the router fails to restart because of config. 
3. Router receives a new config that is valid. It restarts, but with the original schema.
After this change the latest information is used to restart the router always.
Fixes #2752
This is related to #2747, but the auth plugin still needs fixing. …

State machine will always retain most recent config

---

.changesets/fix_bnjjj_fix_log_formatter_level.md
apollo-router/src/plugins/telemetry/formatters/text.rs
apollo-router/src/plugins/telemetry/tracing/datadog.rs
apollo-router/src/plugins/telemetry/tracing/jaeger.rs
apollo-router/src/plugins/telemetry/tracing/otlp.rs

An useless whitespace in front of the log level was added in logs when using the pretty text formatter.

delete useless whitespace in log text formatter

---

.changesets/maint_riding_pellet_burrito_glacier.md
apollo-router/src/plugins/telemetry/mod.rs

Otel shutdown may sometime hang due to `Telemetry::Drop` using a `tokio::spawn_blocking` to flush the `trace_provider`.
Tokio doesn't finish executing tasks before termination https://github.com/tokio-rs/tokio/issues/1156.
This means that if the runtime is shutdown there is potentially a race where `trace_provider` may not be flushed.
By using a thread it doesn't matter if the tokio runtime is shut down.
This is likely to happen in tests due to the tokio runtime being destroyed when the test method exits.
Fixes #2668
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) …

Use a thread to clean up trace_providers rather than tokio::spawn_blocking

---

.changesets/fix_geal_jwt_do_not_block_startup.md
apollo-router/src/plugins/authentication/jwks.rs

Fix #2747
JWKS download can fail sometimes, but it can be temporary, so it should not fail plugin initialization. We still try to download them during init, to make a reasonable effort of starting a router with all the JWKs, but if one download fails we still go on

Do not fail JWT plugin init on JWKS download

---

docs/source/configuration/header-propagation.mdx

This is a minor PR patching broken links caused by inclusion of quotes **"** in markdown links

docs: repair broken links to Rhai scripts

---

apollo-router/src/plugins/authentication/tests.rs

We noticed some complicated Windows-specific test setup code. It looks like `Url::from_file_path` can help here!

chore: simplify test fixture code using Url::from_file_path

---

.changesets/fix_retain_entitlement.md
CHANGELOG.md
Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
apollo-router/src/state_machine.rs
apollo-router/src/uplink/entitlement_stream.rs
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
helm/chart/router/Chart.yaml
helm/chart/router/README.md
scripts/install.sh

Our end-to-end integration testing revealed a newly-introduced bug in v1.12.0 which could affect requests to Apollo Uplink endpoints which are located in different data centers, when those results yield differing responses.  This only impacted a very small number of cases, but retaining previous fetched values is undeniably more durable and will fix this so we're expediting a fix.

release: v1.12.1 — fast-follow fix for v1.12.0

---

renovate.json5

This puts the Renovation of `router-bridge` into a PR by itself and disables automerge for it so it doesn't end up riding along with other dependencies, as it did with https://github.com/apollographql/router/pull/2732.

chore: Separate out `router-bridge` updates from grouped Renovation

---

.circleci/config.yml

We have a couple of minor improvements that can be made to our CI config:
Use environment at the executor level to control build and test concurrency.
build_release calls setup extra tools even though it has already been done.
Fixes #2762
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part of many changes. Where applicable please try to document configuration …

Circle improvements

---

.changesets/feat_bladder_dresser_glad_pill.md
apollo-router/src/plugins/telemetry/metrics/prometheus.rs
apollo-router/src/plugins/telemetry/reload.rs
apollo-router/src/router.rs
apollo-router/src/uplink/entitlement_query.graphql
apollo-router/src/uplink/entitlement_stream.rs
apollo-router/src/uplink/mod.rs
apollo-router/src/uplink/schema_stream.rs
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_empty_http_fallback.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_empty_http_round_robin.snap
apollo-router/tests/common.rs
apollo-router/tests/metrics_tests.rs

Adds metrics for uplink of the format:
```
uplink_bucket{kind="duration",query="SupergraphSdl",service_name="apollo-router",type="unchanged",url="https://uplink.api.apollographql.com/graphql",le="0.001"} 0
uplink_bucket{kind="duration",query="SupergraphSdl",service_name="apollo-router",type="unchanged",url="https://uplink.api.apollographql.com/graphql",le="0.005"} 0
uplink_bucket{kind="duration",query="SupergraphSdl",service_name="apollo-router",type="unchanged",url="https://uplink.api.apollographql.com/graphql",le="0.015"} 0
uplink_bucket{kind="duration",query="SupergraphSdl",service_name="apollo-router",type="unchanged",url="https://uplink.api.apollographql.com/graphql",le="0.05"} 0
uplink_bucket{kind="duration",query="SupergraphSdl",service_name="apollo-router",type="unchanged",url="htt …
```

Uplink metrics

---

.changesets/fix_alias_typename.md
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/spec/query.rs
apollo-router/src/spec/query/tests.rs
apollo-router/src/spec/selection.rs

Fixes #2792
PR #1762 implemented support for the query `{ __typename }` but ignored the possibility that the field might be aliased or repeated. For spec compatibility (and because this is a convenient schema-agnostic query for testing purposes), support these cases as well.
Note that the `solve_*` tests of the formatter passed before this change, as the formatter already processed this correctly.

Support aliased top-level `__typename`

---

.changesets/config_datadog_exporter_mapping.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/telemetry/tracing/datadog.rs
apollo-router/src/services/subgraph_service.rs
docs/source/configuration/tracing.mdx

This PR fixes the issue with DD exporter not providing meaningful data in the DD traces.
[There is a known issue](https://docs.rs/opentelemetry-datadog/latest/opentelemetry_datadog/#quirks) where open telemetry is not fully compatible with datadog
causing this
to fix, this, open-telemetry-datadog [added custom mapping functions](https://docs.rs/opentelemetry-datadog/0.6.0/opentelemetry_datadog/struct.DatadogPipelineBuilder.html#method.with_resource_mapping) 
after applying mapping for `span_name` and `resource_name` DD spans look like this (tested the change in our router implementation)
1. **supergraph** span resource name will be the name of the operation sent to the router, example: `myAwesomeQuery`
2. **subgraph** span resource name will be the name of the subgraph …

feat: add configurable custom mapping to dd exporter

---

.changesets/feat_log_message_support.md
apollo-router/src/plugins/rhai/mod.rs
apollo-router/src/plugins/rhai/tests.rs
docs/source/customizations/rhai-api.mdx
examples/logging/rhai/README.md
examples/logging/rhai/src/rhai_logging.rhai

Fixes #2777. 
The current logs only state the output for "rhai_*", which while mostly descriptive, doesn't cover the use-case of needing custom logs for observability. For example: 
```rhai
fn subgraph_service(service, subgraph) {
service.map_response(|response| {
if response.body.errors != {} {
log_error(response.body.errors, `Subgraph: ${subgraph}`);
}
});
}
```
Will enable customers to have per-subgraph error logging coming from the router, annotated with the subgraph name without parsing the `out` value. 
Previously, this would only be bucketed under the `rhai_error` message type. 
**Checklist**
**Exceptions**
**Notes**
[^1]. …

adding support for specified log "message" / type

---

.changesets/fix_where_were_going_we_dont_need_roads.md
apollo-router/src/uplink/entitlement_stream.rs
apollo-router/src/uplink/mod.rs
apollo-router/src/uplink/schema_query.graphql
apollo-router/src/uplink/schema_stream.rs
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_empty_http_round_robin.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_error_http_fallback.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_error_http_round_robin.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_error_retry.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_fallback.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_invalid.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_round_robin.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_unchanged.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_with_ordering_skip_epoch.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_with_ordering_skip_old.snap
apollo-router/src/uplink/testdata/test_query.graphql
apollo-router/src/uplink/testdata/test_uplink.graphql

Messages that are received from uplink are filtered if they are deemed to be older than the last message recieved.
This should prevent flapping of routers especially when `APOLLO_UPLINK_ENDPOINTS` is in use.
The tests had to be refactored as we needed to be able to test ordering ID and this wasn't possible with entitlements.
Part of #2794
**Checklist**
**Exceptions**
**Notes**
[^2]. …

Make uplink logic ignore messages that are deemed older than the last message to be received

---

.changesets/feat_bladder_dresser_glad_pill.md
apollo-router/src/uplink/mod.rs
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_unchanged_error.snap
apollo-router/tests/metrics_tests.rs

Change uplink logic to allow reporting of out-of-date events via prometheus metric.
Out of date and unchanged responses will no longer halt trying uplink endpoints.
Fixes #2815
**Checklist**
**Exceptions**
**Notes**
[^3]. Tick whichever testing boxes are applicable. If you …

Uplink: out of date handling and metrics

---

.changesets/feat_bladder_dresser_glad_pill.md
docs/source/configuration/metrics.mdx

Add `apollo_router_uplink_duration_seconds_bucket` to metrics docs.
Reworked structure for clarity.
Fixes #2816
**Checklist**
**Exceptions**
**Notes**
- please document the manual testing …

Add `apollo_router_uplink_duration_seconds_bucket` to metrics docs.

---

.circleci/config.yml

This is a small addition to https://github.com/apollographql/router/issues/242 which, when coupled with the already-landed https://github.com/apollographql/router/pull/2409, I think polishes it off nicely by letting us be notified in advance if a nightly build — which is nearly the entire release process — has succeeded or, more importantly, failed.
Resolves #2409

chore: Nightly Release CI Slack notifications

---

.changesets/maint_snap_clap_clap_snap.md
apollo-router/src/executable.rs
xtask/Cargo.lock
xtask/Cargo.toml
xtask/src/commands/all.rs
xtask/src/commands/changeset/mod.rs
xtask/src/commands/compliance.rs
xtask/src/commands/dev.rs
xtask/src/commands/dist.rs
xtask/src/commands/licenses.rs
xtask/src/commands/lint.rs
xtask/src/commands/package/macos.rs
xtask/src/commands/package/mod.rs
xtask/src/commands/release.rs
xtask/src/commands/test.rs
xtask/src/main.rs

Migrated xtask from `StructOpt` to `Clap` as `StructOpt` is in maintenance mode.
Fixes #2807
**Checklist**
**Exceptions**
**Notes** …

Migrate xtask from StructOpt to Clap

---

.changesets/fix_toss_a_coin_to_your_witcher.md
apollo-router/src/uplink/mod.rs
apollo-router/src/uplink/schema_stream.rs

The Uplink URLs that come with the router were incorrect. The primary URL worked, but the backup URL did not.
This fixes and adds an integration test to ensure that all Uplink URLs can be contacted and data retrieved.
Users of older versions of the router should upgrade as soon as possible.
However, if this is not possible then a workaround is to set `APOLLO_UPLINK_ENDPOINTS=https://uplink.api.apollographql.com/,https://aws.uplink.api.apollographql.com/`.
Fixes #2827 
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR …

Fix default Uplink endpoint URLs

---

apollo-router/src/plugins/telemetry/metrics/apollo/duration_histogram.rs
apollo-router/tests/apollo_reports.rs
apollo-router/tests/snapshots/apollo_reports__stats_mocked.snap

In order to test latency historgram computation and add synthetic field errors, this new test does not make network requests to subgraphs but instead mocks their responses.
Fixes https://github.com/apollographql/router/issues/2592
**Checklist**
**Exceptions**
**Notes** …

Add tests for per-type metrics

---

CHANGELOG.md
apollo-router/src/uplink/entitlement_query.graphql
apollo-router/src/uplink/entitlement_stream.rs
apollo-router/src/uplink/mod.rs
apollo-router/src/uplink/schema_stream.rs
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_with_ordering_skip_epoch.snap
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_with_ordering_skip_old.snap
docs/source/configuration/metrics.mdx

Update entitlement query to use ifAfterId rather than unlessId. This enables us to push all freshness checks to uplink.
Fixes #2794
**Checklist**
**Exceptions**
**Notes**
- please document …

Remove router side checks for uplink response freshness.

---

apollo-router/src/plugins/traffic_shaping/retry.rs
docs/source/configuration/metrics.mdx

This follows-up on https://github.com/apollographql/router/pull/2829 with a couple changes:
- Update metrics.mdx
- Change `apollo_router_subgraph_request_retry_total` to `apollo_router_http_request_retry_total` (but tagged with `subgraph`, accordingly)

Retry metrics

---

xtask/Cargo.toml

This PR enables the `vendored-openssl` feature on the `git2` crate in the `xtask` workspace crate.
Fixes #2904 
**Checklist**
~- [ ] Documentation completed~
~- [ ] Performance impact assessed and acceptable~
~- Tests added and passing~
~- [ ] Unit Tests~
~- [ ] Integration Tests~
~- [ ] Manual Tests~
**Exceptions**
This is a no-op that requires _less_ configuration. Docs don't currently explain that you need to install `openssl` to build this crate so there's nothing to remove.

chore: vendors openssl in xtask

---

.changesets/config_helm_extra_labels.md
helm/chart/router/templates/deployment.yaml
helm/chart/router/values.yaml

Add the capability for Helm users to set extra labels attached to the router deployment and its pods.

Helm extra labels

---

.changesets/maint_geal_fix_router_bridge.md
apollo-router/Cargo.toml

when using the router as a library, router-bridge versions can be automatically updated. We want to ensure that the router and router-bridge always work with vetted versions, so we fix it in Cargo.toml and update it manually

fix the router-bridge version

---

.changesets/maint_subgraph_http_error_status_code.md
apollo-router/src/axum_factory/tests.rs
apollo-router/src/error.rs
apollo-router/src/plugins/include_subgraph_errors.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/query_planner/fetch.rs
apollo-router/src/services/subgraph_service.rs

Includes the underlying HTTP status code in the `SubrequestHttpError` when available.
Currently, string parsing is required to pull out the HTTP status code from the `reason` of a `SubrequestHttpError` within a plugin.
This provides plugins a way to act on individual status codes in the event of `SubrequestHttpError`

Status Code provided with SubrequestHttpError

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/telemetry/apollo.rs
apollo-router/src/plugins/telemetry/apollo_exporter.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/telemetry/reload.rs
apollo-router/src/plugins/telemetry/tracing/apollo.rs
apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs

To simplify the implementation and increase reliability, the Apollo exporter, that was acting as an opentelemetry exporter, now moves up to a tracing-subscriber layer
**Checklist**
**Exceptions**
**Notes**
[^3]. Tick whichever testing boxes are …

Move apollo telemetry from an opentelemetry exporter to a tracing layer

---

docs/source/customizations/coprocessor.mdx

These duplicate table tags are breaking the docs build (MDX is clearly a fickle creature)

Fix broken docs build due to duplicate tags

---

docs/source/configuration/tracing.mdx

The URL in the comment was showing as `http://http://` previously, which is certainly incorrect!

docs: Fix duplicated scheme in comment within Tracing config

---

docs/source/configuration/tracing.mdx
docs/source/customizations/coprocessor.mdx

This merges `main` into `dev` and includes #2922, which is meant to fix another documentation build problem.

Merge `main` into `dev`

---

docs/source/configuration/authn-jwt.mdx

The AuthN Rhai example didn't use the `to_string()` method on the claims, and if the claim was parsed as a non-string type, it would cause the script to error. 
Coercing the values to be all strings resolves the issue. 
**Checklist**
**Exceptions**
This is just a minor docs update, no net new functionality. 
**Notes**
[^3]. Tick whichever testing boxes are …

docs: updating Rhai authn example to properly use to_string

---

deny.toml

Our `cargo deny` compliance tests have non-deterministically started to fail
in CI.  This seems to be a case of maybe having just put in a previously
supported configuration, rather than using the currently documented standard
of using `bans`, as seen in the [Ref Config].
Per my comment within the code, doing this defensively required some additional hurdles to be jumped.
[Ref Config]: https://embarkstudios.github.io/cargo-deny/cli/init.html

chore: Update our `cargo deny` configuration to migrate from `deny` to `bans`

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/telemetry/apollo.rs
apollo-router/src/plugins/telemetry/apollo_exporter.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/telemetry/reload.rs
apollo-router/src/plugins/telemetry/tracing/apollo.rs
apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs

Revert "Move Apollo telemetry from an opentelemetry exporter to a tracing layer (#2908)"
This reverts commit 047b2931e2f5c597739bcd061773ce476fa43a6b.

Revert "Move Apollo telemetry from an opentelemetry exporter to a tracing layer (#2908)"

---

CHANGELOG.md

The rename of a newly introduced metric in Apollo Router 1.13.0 was logged in the CHANGELOG using the _wrong_ metric name.  The metric was renamed from `apollo_router_uplink_duration_seconds_bucket` to `apollo_router_uplink_fetch_duration_seconds_bucket` in https://github.com/apollographql/router/pull/2826, but we failed to catch this discrepancy in the changelog for the v1.13.0 [release].
Ref: https://github.com/apollographql/router/pull/2826
[release]: https://github.com/apollographql/router/pull/2841

chore: Update CHANGELOG.md to reference correct metric name

---

.gitleaks.toml

This PR adds `.gitleaks.toml` to the root of this repo. This file is consumed by the secret-scanning tool that Apollo's SecOps team uses to check for secrets in our source.
This file is being added with the required configuration to tell the scanning tool to ignore values that SecOps has confirmed as false positives.
I will follow up on this PR, but if a maintainer on this repo wants to get ahead of me, this PR is safe to merge at your convenience. Let us know in #security if you have any issues or questions!
Thank you!

chore(infra): Add Gitleaks allowlist file

---

.changesets/fix_avery_fix_invalid_graphql_response.md
apollo-router/src/axum_factory/tests.rs
apollo-router/src/services/layers/content_negociation.rs
apollo-router/src/services/router_service.rs
apollo-router/tests/integration_tests.rs

This PR fixes a few cases where the router returns GraphQL errors directly rather than nesting them under a top level `errors` array.
Fixes #2934
Fixes #2946
**Checklist**
~- [ ] Documentation[^2] completed~
~- [ ] Performance impact assessed and acceptable~
**Exceptions**
No documentation needs to be updated because these are bugs. Performance should not be impacted because we are just constructing a slightly different response.

fix: return valid GraphQL responses for invalid requests

---

Cargo.lock
apollo-router-scaffold/Cargo.toml

Specifically, to bring in https://github.com/iomentum/cargo-scaffold/pull/38, released in `cargo-scaffold@0.8.9`.

fix(deps): update `cargo-scaffold` to v0.8.9

---

.changesets/maint_toddler_discuss_both_volume.md
Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/services/supergraph_service.rs

fixes #2937
Update to federation 2.4.1, which includes a fix around [`@interfaceObject`](https://github.com/apollographql/federation/blob/main/gateway-js/CHANGELOG.md#241)

update to federation 2.4.1

---

.changesets/config_extra_labels_tpl.md
helm/chart/router/templates/_helpers.tpl
helm/chart/router/templates/deployment.yaml

When a helm chart users add extra labels to the Kubernetes Deployment and pods (via the helm chart), they may want to use a piece of data from the `Values` or the `Chart` eg using the Chart version as a label value.
At the moment doing something like:
```
extraLabels:
env: {{ .Chart.AppVersion }}
```
is interpreted as:
```
labels:
env: {{ .Chart.AppVersion }}
```
This is "normal" because by default strings are not interpolated. The fix basically iterates over the `extraLabels` and uses the `tpl` function on the values (only). The result being then
```
labels:
env: "v1.2.3"
```

Treats the value of the deployment extra labels as possible templates

---

.changesets/fix_muscle_peach_thunderstorm_musical.md
dockerfiles/Dockerfile.router

This broke the release of v1.15.0.  Turns out this[ may only be compatible with](https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/) `docker buildx`.
Furthermore, the change wasn't made to the `diy` dockerfile, and we'd like to prevent the two Dockerfiles from deviating more than necessary.
Reverts apollographql/router#2925
Fixes https://github.com/apollographql/router/issues/2966

Revert "Update Dockerfile.router to use heredoc"

---

.changesets/config_extra_containers_fix.md
helm/chart/router/templates/deployment.yaml

The [previous PR](https://github.com/apollographql/router/pull/2881) does not indent correctly and makes it impossible to create extra containers.
**Checklist**
**Exceptions**
**Notes**
I nurture a distaste for YAML, text/template, and Helm, merely copied from context, and do not understand the before nor the after.
This was tested using `helm package`, copying the resulting tarball in internal Helm charts, then running `helm install … --dry-run --debug`. While I'm not 100% sure it is correct, the generated YAML seemed correct after converting to JSON and back.

fix: Helm YAML for extraContainers (#2881)

---

.changesets/maint_climber_northeast_inspector_cried.md
apollo-router/src/plugins/telemetry/apollo.rs
apollo-router/src/plugins/telemetry/apollo_exporter.rs
apollo-router/src/plugins/telemetry/metrics/apollo/snapshots/apollo_router__plugins__telemetry__metrics__apollo__studio__test__aggregation.snap
apollo-router/src/plugins/telemetry/metrics/apollo/studio.rs
apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_exclude.snap
apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_multiple_operations.snap
apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_parse_failure.snap
apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_single_operation.snap
apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_unknown_operation.snap
apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_validation_failure.snap
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
apollo-router/src/query_planner/fetch.rs
apollo-router/src/spec/query.rs
apollo-router/tests/snapshots/apollo_reports__client_name.snap
apollo-router/tests/snapshots/apollo_reports__client_version.snap
apollo-router/tests/snapshots/apollo_reports__condition_else.snap
apollo-router/tests/snapshots/apollo_reports__condition_if.snap
apollo-router/tests/snapshots/apollo_reports__non_defer.snap
apollo-router/tests/snapshots/apollo_reports__send_header.snap
apollo-router/tests/snapshots/apollo_reports__send_variable_value.snap
apollo-router/tests/snapshots/apollo_reports__stats.snap
apollo-router/tests/snapshots/apollo_reports__stats_mocked.snap
apollo-router/tests/snapshots/apollo_reports__trace_id.snap
apollo-router/tests/snapshots/tracing_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/tracing_tests__traced_basic_request.snap

add support of operationCountByType for apollo studio
**Checklist**
**Exceptions**
**Notes** …

feat: add support of operationCountByType for apollo studio

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/plugins/telemetry/formatters/text.rs
xtask/Cargo.lock
xtask/Cargo.toml
xtask/src/main.rs

Partially fixes https://rustsec.org/advisories/RUSTSEC-2021-0139
`clap` is still depending on [ansi_term](https://github.com/ogham/rust-ansi-term).
cargo audit before the change:
```
Crate:     ansi_term
Version:   0.12.1
Warning:   unmaintained
Title:     ansi_term is Unmaintained
Date:      2021-08-18
ID:        RUSTSEC-2021-0139
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0139
Dependency tree:
ansi_term 0.12.1
├── clap 2.34.0
│   ├── structopt 0.3.26
│   │   └── cargo-scaffold 0.8.7
│   │       └── apollo-router-scaffold 1.12.1
│   └── cargo-scaffold 0.8.7
└── apollo-router 1.12.1
├── throw-error 0.1.0
├── supergraph_sdl 0.1.0
├── rhai-surrogate-cache-key 0.1.0
├── rhai-subgraph-request-log 0.1.0
├── rhai-logging 0.1.0
├── rhai-error-response-mutate 0.1.0
├── …
```

deps: Use nu-ansi-term to replace unmaintained ansi_term

---

.changesets/feat_chaos_reload.md
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/router.rs
apollo-router/src/state_machine.rs
apollo-router/src/uplink/entitlement_stream.rs
apollo-router/tests/lifecycle_tests.rs

The Router can now artificially be made to hot-reload (as if the configuration or schema had changed) at a configured time interval. This can help reproduce issues like reload-related memory leaks.
The new configuration section for chaos testing is marked as experimental.
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part of many changes. Where applicable please …

Time-based forced hot-reload for chaos testing

---

.changesets/maint_garypen_2777_tracing.md
apollo-router/src/plugins/rhai/mod.rs
apollo-router/src/plugins/rhai/tests.rs

The Rhai logging output was "standardized" about a year ago. Since that time, significant efforts have been made within the rest of the router to standardize on a slightly different format. This PR brings rhai log output into line with the rest of the router.
It also addresses the requirement to make the "message" output specifiable by the script author.
Note: The changes are source code compatible, but the format of the output log line is changing. I don't think we make compatibility commitments on this, but it's worth noting.
Fixes #2777 
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention …

Re-structure the rhai logging output

---

.changesets/feat_preview_features.md
apollo-router/feature_discussions.json
apollo-router/src/configuration/experimental.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/schema.rs
apollo-router/src/executable.rs
apollo-router/src/services/supergraph_service.rs
apollo-router/tests/common.rs
apollo-router/tests/lifecycle_tests.rs
apollo-router/tests/snapshots/lifecycle_tests__cli_config_experimental.snap
apollo-router/tests/snapshots/lifecycle_tests__cli_config_preview.snap
apollo-router/tests/snapshots/lifecycle_tests__experimental_notice.snap

This expands on the existing mechanism that was originally introduced in https://github.com/apollographql/router/pull/2242, which supports the notion of an "experimental" feature, and make it compatible with the notion of "preview" features.
Most of this code was written by @o0Ignition0o, I just extracted it and put it here! 😄 
**Checklist**
- [-] Documentation[^2] completed
- [-] Performance impact assessed and acceptable
- [-] Unit Tests
- [-] Integration Tests

Also support "preview" features, in addition to "experimental" features

---

docs/source/config.json

This (hopefully) helps clarify that this docset is specific to self-hosting the router as opposed to managing cloud routing via GraphOS.

docs: Rename router docset

---

.changesets/fix_geal_fix_compression_finish.md
apollo-router/src/axum_factory/compression/mod.rs

Fix #3035
In some cases, the "finish" call to flush the compression state at the end does not flush th entire state, so it has to be called multiple times.
**Checklist**
**Exceptions**
**Notes**
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual …

make sure the compression state is flushed

---

.changesets/feat_operation_limits.md
apollo-router/feature_discussions.json
apollo-router/src/configuration/migrations/0007-parser-recursion.yaml
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__upgrade_old_configuration@parser_recursion.router.yaml.snap
apollo-router/src/configuration/testdata/migrations/parser_recursion.router.yaml
apollo-router/src/error.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/spec/mod.rs
apollo-router/src/spec/operation_limits.rs
apollo-router/src/spec/query.rs
apollo-router/src/uplink/entitlement.rs
apollo-router/src/uplink/snapshots/apollo_router__uplink__entitlement__test__restricted_features_via_config.snap
apollo-router/src/uplink/testdata/oss.router.yaml
apollo-router/src/uplink/testdata/restricted.router.yaml
apollo-router/tests/integration_tests.rs
apollo-router/tests/operation_limits.rs
apollo-router/tests/snapshots/lifecycle_tests__cli_config_preview.snap
docs/source/config.json
docs/source/configuration/operation-limits.mdx
docs/source/configuration/overview.mdx
docs/source/enterprise-features.mdx

You can define operation limits in your router's configuration to reject potentially malicious requests. An operation that exceeds _any_ specified limit is rejected.
You define operation limits in your router's [YAML config file](https://www.apollographql.com/docs/router/configuration/overview#yaml-config-file), like so:
```yaml
preview_operation_limits:
max_depth: 100
max_height: 200
max_aliases: 30
max_root_fields: 20
```
See details in operation limits documentation in `docs/source/configuration/operation-limits.mdx` and soon at https://www.apollographql.com/docs/router/configuration/operation-limits.
**Checklist**
**Exceptions**
Compatibility: the new parser limit is …

GraphOS Enterprise: operation limits

---

.changesets/docs_abernix_pr_2607_follow_up.md
docs/source/configuration/metrics.mdx

Follows up https://github.com/apollographql/router/pull/2607 with the documentation that explains the `apollo_router_cache_size` metric (a count of cache entries, not "bytes as in memory").

docs(metrics): `apollo_router_cache_size` is a count of cache entries

---

apollo-router/src/plugins/rhai/engine.rs
apollo-router/src/plugins/rhai/tests.rs

I believe it's acceptable (from a rhai point of view) to have each module define its own type HeaderMap. When they are combined into a single module, as long as the type definition is the same (not even sure if this is checked) then everything works fine.
The change passes all of the tests and the example tests.
Also: polish up some of the functions which should be "pure". It will perhaps give us a performance benefit.
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. …

Do some hackery so we don't need RhaiHeaderMap

---

.changesets/fix_fix_gzip_encoding.md
apollo-router/src/axum_factory/compression/mod.rs
apollo-router/src/axum_factory/compression/util.rs

1.17.0 sometimes panics when doing gzip response encoding. The write head for the buffer was being extended by the total amount written so far (instead of the amount written by the current iteration).
Rather than just remove the `+` in `written += ...` I thought it would be more ergonomic to add the required method to the `PartialBuffer`.
**Checklist**
Relates to https://github.com/apollographql/router/issues/1572
Root-cause: https://github.com/apollographql/router/pull/2986

fix: regression to gzip encoding causing panicks

---

.changesets/docs_abernix_pr_2607_follow_up.md
.changesets/feat_geal_query_planning_metric.md
.changesets/fix_fix_gzip_encoding.md
.changesets/fix_subgraph_status_code_not_in_gql_error.md
CHANGELOG.md
Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
helm/chart/router/Chart.yaml
helm/chart/router/README.md
scripts/install.sh

> **Note**
>
> When approved, this PR will merge into **the `1.18.0` branch** which will — upon being approved itself — merge into `main`.
>
>  - That it targets the right release branch (`1.18.0` in this case!).
>
---
We've introduced a `apollo_router_query_planning_time` histogram which captures time spent in the query planning phase.  This is documented along with our other metrics [in the documentation](https://www.apollographql.com/docs/router/configuration/metrics/#available-metrics).
By [@Geal](https://github.com/Geal) in https://github.com/apollographql/router/pull/2974
A …

prep release: v1.18.0

---

.changesets/maint_bnjjj_follow_up_3011.md
apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs

related to https://github.com/apollographql/router/pull/3011#discussion_r1183551431

refactor(telemetry): more readable code to redact errors going to apollo studio

---

.changesets/fix_garypen_context_coprocessor.md
apollo-router/src/context.rs
apollo-router/src/plugins/coprocessor.rs
apollo-router/src/plugins/telemetry/mod.rs

also:
- Modify upsert to use FnOnce rather than Fn to minimize cloning
@lennyburdette This is an attempt at a more performant fix than your PR #3049. I think the end result is the same, it should just be slightly more performant by avoiding cloning and also makes the base `Context` slightly more efficient.
Could you try a build from this branch against your test case and confirm it's still doing what you expect?
also: I've thought a little more about this and even though this is "better" than what we have on `dev` right now, I still think there is problem. This change means that we aren't racing across an entire context, but we are still racing across subgraph responses for each context update and that means there is no way to sequence the updating, which is a possible problem. It really …

Add a context try_into_iter() and use it in the co-processor

---

.changesets/fix_garypen_3065_reload_logging.md
.changesets/fix_geal_resize_flushed_buffer.md
.changesets/maint_bnjjj_follow_up_3011.md
CHANGELOG.md
Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh

> **Note**
>
> When approved, this PR will merge into **the `1.18.1` branch** which will — upon being approved itself — merge into `main`.
>
>  - That it targets the right release branch (`1.18.1` in this case!).
>
---
When writing a deferred response, if the output buffer was too small to write the entire compressed response, the compressor would write a small chunk that did not decompress to the entire primary response, and would then wait for the next response to send the rest.
Unfortunately, we cannot really know the output size we need in advance, and if we asked the decoder, it will …

prep release: v1.18.1

---

Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh

This cuts an `1.19.0-alpha.0` of the https://github.com/apollographql/router/pull/2995 PR.  This was previously released as `1.16.0-alpha.0`, but the `1.16.0-alpha.0` never became `1.16.0`.  Instead, we've since released new actual releases that superceded it.  This alpha is the new candidate to become an official  `1.19.0`, but that is still not certain until further validations are complete.

prep release: v1.19.0-alpha.0

---

.changesets/fix_garypen_rhai_throw_error.md
apollo-router/src/plugins/rhai/mod.rs
docs/source/customizations/rhai-api.mdx

In #2677 we added support for throwing graphql errors from rhai. Support was added for requests. This extends the mechanism to include responses.
fixes: #3069
**Checklist**
**Exceptions**
**Notes**
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual …

add support for handling complex throw errors in responses

---

docs/source/customizations/coprocessor.mdx

Adds a small footnote about the `RouterResponse` stage returning redacted errors vs. all errors. 
**Checklist**
**Exceptions**
**Notes**
- please document the manual …

docs: add footnote about `RouterResponse` and `errors` key

---

docs/source/customizations/coprocessor.mdx

Replace `error` with `errors` in this documentation example; `error` is merely a mistype of `errors` in this case.

docs: Update coprocessor.mdx

---

.circleci/config.yml

This puts the release machine at the same size as the machine we use for tests.
Ref: https://circleci.com/docs/configuration-reference/#windows-execution-environment
Hopefully Fixes: 50 minute Windows Releases

chore: Use `xlarge` Windows instances on our CircleCI "Release" workflow

---

.changesets/maint_avery_test_yamls.md
apollo-router/tests/integration_tests.rs
apollo-router/tests/lifecycle_tests.rs

Adds an integration test that iterates over `./examples` looking for `.yaml` files that don't have a `Cargo.toml` or `.skipconfigvalidation` sibling, and then running `setup_router_and_registry` on them.
Fixes #2932

chore: adds integration test for example YAML configuration

---

.changesets/fix_geal_filter_spans.md
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/telemetry/reload.rs
apollo-router/tests/snapshots/tracing_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/tracing_tests__traced_basic_request.snap
apollo-router/tests/snapshots/tracing_tests__variables.snap

This reverts commit ecd5d57fd5afe8fec0a7182f584b71ea58474432.
The reason for this is that parent based sampling definitely regressed and there are some ongoing questions around correctness. We will look again after the release as this did appear to give a good speedup.
Related:
#2894 
#3103 
**Checklist**
**Exceptions**
**Notes** …

Revert "Filter spans before sending them to the opentelemetry layer (#2894)"

---

apollo-router/src/uplink/entitlement_stream.rs
apollo-router/src/uplink/schema_stream.rs
apollo-router/src/uplink/uplink.graphql

This resolves the `uplink::test::test_uplink_schema_is_up_to_date` test failures in CI.

chore: Update Uplink schema in source

---

RELEASE_CHECKLIST.md

Overall, this commit adds a very verbose list of individually automated steps which can be automated into approximateily 3 fully-automated chunks.
For now, we're starting with testing the process with manual commands, and
this outlines those commands.  I've been using these for the release for a
while and literally just copy and paste the commands about after the 4th
step. (And stopping in the middle to fix the CHANGELOG.md and solicit PR
approval from the team).
Fixes https://github.com/apollographql/router/issues/170

Add a very expressive list of commands to `RELEASE_CHECKLIST.md`

---

apollo-router/src/plugins/coprocessor.rs

Now that we expect bytes back from the coprocessor, just take the bytes and don't try to convert back to JSON.
There was an error in the RouterRequest processing logic. I was still trying to convert coprocessor response bytes back to JSON and that worked but resulted in double escaped text which failed when the query planner tried to make sense of it.

don't try to convert bytes back to JSON on RouterRequest

---

.changesets/fix_geal_update_router_bridge_deno.md
Cargo.lock
apollo-router/Cargo.toml

Fix #3133
This fixes some errors in query planning on fragment with overlapping subselections, with a message of the form "Cannot add selection of field X to selection set of parent type Y".
The new router-bridge version also allows updating some dependencies that were fixed to older versions: bytes, regex, once_cell, tokio, uuid

Update the query planner to 2.4.6

---

xtask/Cargo.lock
xtask/Cargo.toml
xtask/src/commands/changeset/mod.rs
xtask/src/commands/changeset/snapshots/xtask__commands__changeset__tests__it_templatizes_with_multiple_issues_in_title.snap
xtask/src/commands/changeset/snapshots/xtask__commands__changeset__tests__it_templatizes_with_multiple_issues_in_title_and_multiple_prs_in_footer.snap
xtask/src/commands/changeset/snapshots/xtask__commands__changeset__tests__it_templatizes_with_multiple_prs_in_footer.snap
xtask/src/commands/changeset/snapshots/xtask__commands__changeset__tests__it_templatizes_with_neither_issues_or_prs.snap
xtask/src/commands/changeset/snapshots/xtask__commands__changeset__tests__it_templatizes_with_prs_in_title_when_empty_issues.snap
xtask/src/commands/changeset/snapshots/xtask__commands__changeset__tests__it_templatizes_with_prs_when_empty_issues.snap
xtask/src/commands/changeset/snapshots/xtask__commands__changeset__tests__it_templatizes_without_prs_in_title_when_issues_present.snap

Previously, it was just leaving it off, but it left things a bit
unharmonic/off-balance in terms of the resulting changeset template.  I'd
also just been manually adding those during the release process thus far, so
figured I'd just automate it now.
Also added a lot of tests and fixed a couple bugs with trailing spaces.
Relates to #https://github.com/apollographql/router/issues/2261

chore(tools): Use PR number in changeset titles when Issue is absent

---

.changesets/fix_abernix_remove_curl.md
dockerfiles/Dockerfile.router
dockerfiles/diy/dockerfiles/Dockerfile.repo

The `curl` command is only used in the image we produce today for the sake
of downloading dependencies.  It is never used after that, but we can move
it to a separate layer to further remove it from the image.
Ref: https://github.com/apollographql/router/issues/3144

Move `curl` dependency to separate layer in Docker image

---

xtask/Cargo.lock

This is the result of running `cargo update` in the `xtask/` directory (our
directory of tooling; not runtime components) to bring things more up to
date.
Follows-up: https://github.com/apollographql/router/pull/3149
Some of the changes in https://github.com/apollographql/router/pull/3152
seem to have undone some of the dependency updates, so this re-applies them.

chore(deps): `xtask/` dependency updates, again

---

.changesets/maint_garypen_3176_filter_licenses.md
about.toml

Add support for new cargo about option to filter NOASSERTION licenses.
fixes: #3176
**Checklist**
**Exceptions**
**Notes** …

filter NOASSERTION licenses

---

.changesets/feat_swan_cub_foot_audience.md
.changesets/fix_bernard_helmtest.md
.changesets/fix_fed_247.md
.changesets/fix_garypen_3173_ca_certs.md
.changesets/fix_lib_global_alloc.md
.changesets/maint_garypen_3176_filter_licenses.md
docs/source/federation-version-support.mdx

This should simplify the actual release in the next little bit and also updates the `federation-version-support.mdx` file.

chore: Some changelog prep prior to 1.20.0 release

---

dockerfiles/diy/build_docker_image.sh

- Add a `cd` to the top so that you don't have to be in the script's directory for the relative paths in the "Copy in our dockerfiles" section to work.
- Specify the directory name when cloning a repository, to support forks with names other than `router`.

diy dockerfile: two small improvements

---

apollo-router-scaffold/templates/base/Dockerfile
apollo-router/Cargo.toml
apollo-router/README.md
apollo-router/src/plugin/test/service.rs
apollo-router/src/plugins/telemetry/apollo_exporter.rs
apollo-router/src/plugins/telemetry/otlp.rs
apollo-router/src/query_planner/fetch.rs
apollo-router/src/router.rs
apollo-router/src/services/external.rs
apollo-router/src/spec/query/tests.rs
apollo-router/src/uplink/entitlement.rs
apollo-router/tests/integration_tests.rs
dockerfiles/diy/dockerfiles/Dockerfile.repo
docs/source/customizations/custom-binary.mdx
rust-toolchain.toml

This enables by default the sparse index protocol for crates.io: 
* https://blog.rust-lang.org/inside-rust/2023/01/30/cargo-sparse-protocol.html
* https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html#sparse-by-default-for-cratesio
**Checklist**
**Exceptions**
Compat: custom binary users need to upgrade their toolchain
Tests: no behavior change
**Notes** …

Upgrade to Rust 1.70

---

apollo-router/feature_discussions.json
apollo-router/tests/snapshots/lifecycle_tests__cli_config_experimental.snap

Follow-up to https://github.com/apollographql/router/pull/3130
**Checklist**
**Exceptions**
**Notes**
- please raise a …

Link to Discussion for experimental_http_max_request_bytes

---

Cargo.lock
apollo-router/Cargo.toml

See https://github.com/rust-lang/libc/issues/3264
Requiring a yanked version causes `cargo update` to fail on CI: https://app.circleci.com/pipelines/github/apollographql/router/12758/workflows/52d4c586-1da7-453b-b90f-1366c72ae46b/jobs/83879?invite=true#step-115-7
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part of many changes. Where applicable please try to …

Upgrade libc crate from yanked version

---

.circleci/config.yml

Cargo deny is taking more than 10 minutes which CircleCI is timing out from.
Fixes #3216
**Checklist**
**Exceptions**
**Notes** …

Increase the timeout for the release process 

---

docs/source/customizations/coprocessor.mdx

Add docs clarifying the `body` field and the fact it is not sent when the request is a GET

[docs] Update coprocessor docs for GET requests

---

.circleci/config.yml
xtask/src/commands/compliance.rs

Cargo deny is triggering `git credential-manager-core get`
On windows CI this will hangs as it requires user input.
The root cause seems to be the krates step in cargo-deny but did not manage to figure it out.
Disabling as a temporary measure, but we must fix this soon.
Will raise a new ticket to ensure we don't forget to actually fix this.
Fixes #3216
**Checklist**
**Exceptions**
**Notes** …

Disable cargo-deny for windows CI

---

apollo-router/src/plugins/telemetry/metrics/mod.rs

The description was copied from the total number of requests metric and has always been wrong. This fixes it.

fix description of request duration metric

---

.changesets/fix_garypen_3249_docker_heaptrack.md
.circleci/config.yml

If we don't set this flag, then heaptrack isn't installed.
fixes: #3249

set DEBUG_IMAGE=true when building debug docker image

---

docs/source/configuration/traffic-shaping.mdx

Hopefully removes the ambiguity noted in the referenced issue.  Merges to `main` intentionally as this docs change doesn't pertain to a specific version.
Closes https://github.com/apollographql/router/issues/3257

docs(traffic-shaping): Indicate that query de-duplication is disabled by default

---

.changesets/feat_geal_query_planner_plugins.md
Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/spec/query.rs
apollo-router/src/spec/query/transform.rs
apollo-router/src/spec/query/traverse.rs

We expect to use them inside query planner plugins: https://github.com/apollographql/router/pull/3177
**Checklist**
**Exceptions**
**Notes**
- please document the manual testing …

Add visitor traits for transforming or traversing queries

---

.changesets/docs_debugging_rhai.md
.changesets/feat_add_script_path_to_rhai_errors.md
apollo-router/src/plugins/rhai/mod.rs
apollo-router/src/plugins/rhai/tests.rs
apollo-router/tests/fixtures/syntax_errors.rhai
docs/source/customizations/rhai.mdx

Completely open to re-landing it with some variation of this and considering that it's happening only on Windows, it's almost undoubtedly a timing issue, but for now, this reverts apollographql/router#3254 as it's causing somewhat consistent failures in CI right now on Windows, [seen here](https://app.circleci.com/pipelines/github/apollographql/router/12962/workflows/aca214be-f9ed-453b-9775-9ada639c5f54/jobs/85133?invite=true#step-117-1196) with the following error:
```
---- plugins::rhai::tests::it_mentions_source_when_syntax_error_occurs stdout ----
thread 'plugins::rhai::tests::it_mentions_source_when_syntax_error_occurs' panicked at 'assertion failed: err.to_string().contains(\"tests/fixtures/syntax_errors.rhai\")', apollo-router\src\plugins\rhai\tests.rs:736:5
stack backtrace:
0: …
```

Revert "Improve Rhai errors"

---

.changesets/feat_garypen_diy_improvements.md
dockerfiles/Dockerfile.router
dockerfiles/diy/build_docker_image.sh

The diy build script is useful for ad-hoc image creation during testing or for building your own images based on a router repo. This set of enhancements makes it possible to
- build docker images from arbitrary (nightly) builds (-a)
- build an amd64 docker image on an arm64 machine (or vice versa) (-m)
- change the name of the image from the default 'router' (-n)
Note: the build machine image architecture is used if the -m flag is not supplied.
fixes: #3303
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. …

add additional build functionality to the diy build script

---

.changesets/fix_coupon_shotgun_ridge_bodyguard.md
apollo-router/src/plugins/telemetry/config.rs
apollo-router/src/plugins/telemetry/tracing/datadog.rs

OTEL_SERVICE_NAME env and service.name resource are now correctly used when creating tracing exporters.
This required two fixes:
- Datadog exporter should pick up the `service.name` resource rather than grabbing the service name directly from the config.
- Resource creation picks up service name in order of precedence:
1. OTEL_SERVICE_NAME
2. `service.name`
3. config yaml
Fixes #3215
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement …

Otel Ensure that service name is correctly picked up from env

---

apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/router_factory.rs
apollo-router/src/services/layers/apq.rs
apollo-router/tests/fixtures/test_plugin_ordering.rhai
apollo-router/tests/lifecycle_tests.rs
docs/source/customizations/native.mdx

Fixes https://github.com/apollographql/router/issues/3230
Fixes https://github.com/apollographql/router/issues/3207
**Checklist**
**Exceptions**
**Notes**
- please document the manual …

Test and document the ordering of plugins

---

.changesets/fix_garypen_2951_float.md
apollo-router-benchmarks/Cargo.toml
apollo-router/Cargo.toml

This feature is explicitly designed to:
"""
Use sufficient precision when parsing fixed precision floats from JSON to ensure that they maintain accuracy when round-tripped through JSON. This comes at an approximately 2x performance cost for parsing floats compared to the default best-effort precision.
"""
Despite the performance impact for floats, we need the fix in order to prevent float values losing precision when processed by the router.
fixes: #2951
**Checklist**
**Exceptions**
The manual testing was performed as described in the issue: #2951 
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to …

Enable serde_json float_roundtrip feature

---

.changesets/maint_avery_update_macos_notarizer.md
.circleci/config.yml
apollo-router/src/uplink/mod.rs
xtask/src/commands/package/macos.rs

Updates `altool` to `notarytool` for MacOS codesigning
Fixes #3275
prior art: 
https://github.com/apollographql/federation-rs/pull/370
https://github.com/apollographql/rover/pull/1658
**Checklist**
**Exceptions**
- No docs need updating, implementation detail.
- Performance impact measurement not necessary, code changes are to `xtask`.
**Notes**
[^2]. Configuration is an important part of many changes. Where applicable …

chore: updates 'altool' to 'notarytool' for macos codesigning
