Cargo.lock
crates/apollo-router-core/Cargo.toml
crates/apollo-router-core/src/query_planner/caching_query_planner.rs
crates/apollo-router/Cargo.toml
crates/apollo-router/src/state_machine.rs
crates/apollo-router/tests/integration_tests.rs

use a futures aware mutex instead to avoid blocking executors

remove last uses of parking-lot

---

docs/source/configuration.mdx

Add remark about JSON logging and TTY

---

docs/source/configuration.mdx

Signed-off-by: Phil Prasek <prasek@gmail.com>

add `--log` option to docs

---

apollo-router-core/Cargo.toml
apollo-router/src/apollo_router.rs
apollo-router/src/lib.rs
apollo-router/src/main.rs
apollo-router/src/trace.rs
apollo-router/src/warp_http_server_factory.rs

subset of the work from #224, everything but the sampling part. This can be merged independently

Tracing fixes

---

docs/gatsby-config.js

This branch configures the router docset to be indexed and searchable 🎉

Add Algolia indexing config

---

Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-benchmarks/benches/basic_composition.rs
apollo-router-core/src/error.rs
apollo-router-core/src/query_planner/mod.rs
apollo-router-core/src/response.rs
apollo-router-core/src/traits.rs
apollo-router/src/apollo_router.rs
apollo-router/src/http_subgraph.rs
apollo-router/src/lib.rs
apollo-router/src/state_machine.rs
apollo-router/src/warp_http_server_factory.rs
apollo-router/tests/integration_tests.rs

simplify response stream

---

src/bin/bin.rs
src/demos/context_propagation.rs
src/demos/custom_logging.rs
src/demos/custom_subgraph_service.rs
src/demos/demo_template.rs
src/demos/header_manipulation.rs
src/demos/load_shedding.rs
src/demos/mutate_query_body.rs
src/demos/override_service_url.rs
src/demos/rate_limiting.rs
src/demos/timeouts.rs
src/services/federation.rs

feat: fix load shed failing test + remove unused uses

---

Cargo.lock
Cargo.toml
src/demos/context_propagation.rs
src/demos/custom_instrumentation.rs
src/demos/custom_subgraph_service.rs
src/demos/demo_template.rs
src/demos/header_manipulation.rs
src/demos/load_shedding.rs
src/demos/mutate_query_body.rs
src/demos/override_service_url.rs
src/demos/rate_limiting.rs
src/demos/timeouts.rs
src/layers/header_manipulation.rs
src/lib.rs
src/services/federation.rs
src/services/graphql_subgraph_service.rs
src/services/rest_subgraph_service.rs
tests/header_manipulation.rs

This is wip to try to see how adding layers feels DX wise

wip: test harness implementation

---

CHANGELOG.md
Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
deny.toml
xtask/Cargo.toml

* Author CHANGELOG
* Bump versions!
Per instructions:
https://github.com/apollographql/router/blob/948dbc6a/RELEASE_CHECKLIST.md

release: v0.1.0-alpha.4

---

Cargo.lock
apollo-router-core/Cargo.toml
apollo-router-core/src/layers/cache.rs
apollo-router-core/src/layers/mod.rs
apollo-router-core/src/services/mod.rs

This is a demonstration caching layer that could be improved to allow the removal of CachingQueryPlanner. This layer allows caching to any service pipeline.

Demonstrate a generic cache layer.

---

apollo-router-core/src/plugin.rs
apollo-router-core/src/services/http_compat.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/router_factory.rs
apollo-router/src/state_machine.rs

Clippy fixes and slight improvement to layer error handling.
Layer error handling may go away once we implement some sort of registration mechanism similar to the plugins.

Clippy fixes

---

apollo-router/src/apollo_telemetry.rs
apollo-spaceport/src/lib.rs
licenses.html

A variety of mainly cosmetic improvements to the recently merged studio
usage and spaceport functionality.
closes: #420

small improvements to studio usage reporting

---

apollo-router-core/src/spec/fragments.rs
apollo-router-core/src/spec/query.rs
apollo-router-core/src/spec/selection.rs

Fix #469
no fix for now, only tests showing the issue

Check the type condition on fragments

---

apollo-router-core/src/layer.rs
apollo-router-core/src/plugin.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/main.rs
apollo-router/src/plugins/hello.rs
apollo-router/src/router_factory.rs

Similar to #453 This bring the plugin logic into line.
It also adds schema generation for plugins and finally a command line flag to output the schema.
We need to revisit the structure of the our command line in light of the fact we may have several commands eventually.

Plugin config rework

---

apollo-router/src/apollo_telemetry.rs
apollo-spaceport/src/server.rs

Ensure that default collection address is correct and improve the error
handling when transferring data to apollo ingress.
fixes: #483

router has incorrect default collector address

---

licenses.html

I must have missed something when merging query deduplication :(

fix licenses

---

CHANGELOG.md

Follows-up: https://github.com/apollographql/router/pull/526

Adjust CHANGELOG.md for #526

---

Cargo.lock
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
licenses.html

Largely as a consideration point.  I've marked this as _draft_, but... _discuss_!

chore: enable `full` feature set on `tower` dependency

---

apollo-router/src/main.rs

fix(router): prioritize the --supergraph arg when APOLLO_KEY is set

---

Cargo.lock
fuzz/Cargo.toml
fuzz/fuzz_targets/router.rs

we can deserialize to a json Value instead

the fuzzer does not need apollo_router_core

---

Cargo.lock
fuzz/fuzz_targets/router.rs

just an upgrade to add support of arguments and mutation

upgrade apollo-smith to support mutation and arguments

---

Cargo.lock
examples/async-allow-client-id/src/main.rs
examples/compose-your-graphql-router/Cargo.toml
examples/compose-your-graphql-router/src/main.rs
examples/context-data/src/main.rs
examples/forbid-anonymous-operations/src/main.rs

The examples weren't using the new RouterSubscriber, so they didn't
work. This PR fixes that.

Update examples to work with new RouterSubscriber

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/warp_http_server_factory.rs

Fix #27
previously we were unwrapping the result inside the connection's spawned
task, while we can be a bit smarter about errors.
For most of them, we can just ignore the error and continue to the next
connection.
Errors returned when we reach the max file descriptor limit need special
handling, because they're frequently caused by misconfiguration, and
logging a message each time the error is returned will quickly be
overwhelming. So we show an error message once, and then we wait for a
minute before printing another error

handle errors on accept() calls

---

.github/workflows/main.yml

Remind when CHANGELOG entry was not made

---

docs/source/configuration.mdx

Docs: Fix broken link on the configuration page

---

Cargo.lock
apollo-router/Cargo.toml
licenses.html

It's been a month or so since last time I did this, so doing it again.
closes: #454 
(again)

chore: merge apollo-rs main back to branch garypen/66-usage-agent

---

docs/source/configuration.mdx
examples/async-allow-client-id/config.yml
examples/async-allow-client-id/src/allow_client_id_from_file.rs

The headers layer is now a headers plugin. Layers are gone in the configuration.
Update the docs to match.

Update the documentation around headers.

---

CHANGELOG.md

Add changelog entry for fix to OTEL

---

.github/workflows/docs-preview.yml
.github/workflows/docs-publish.yml

This branch adds actions to deploy docs changes to prod and preview changes in PRs.

Set up docs preview and publish workflows

---

docs/source/configuration/overview.mdx
docs/source/customizations/overview.mdx

docs: request life-cycle and trait details

---

apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/mod.rs

The rhai plugin isn't quite in the shape we would like it to be.
We therefore remove it for this release, and we will iterate on it before we reenable it.

Remove rhai for now.

---

apollo-router/src/plugins/rhai.rs

We shouldn't be creating new engines for each invocation. Create one
engine when the plugin is created and share this under an Arc.
Note: The rhai plugin needs more extensive changes, but I'm making this
change before I forget about it.

small rhai scripting improvement to engine management

---

CHANGELOG.md
apollo-router-core/src/plugins/headers.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
examples/header-manpiulation/header_manupulation.router.yaml

And fix remove config.
Previously:
```yaml
- remove:
name: "Remove"
```
Now:
```yaml
- remove:
named: "Remove"
```
This is consistent with propagate.

Add yaml example for header manipulation.

---

docs/source/config.json
docs/source/configuration/header-propagation.mdx
docs/source/configuration/open-telemetry.mdx
docs/source/configuration/overview.mdx
docs/source/configuration/spaceport.mdx
docs/source/configuration/subgraph-routing-urls.mdx
docs/source/customizations/native.mdx
docs/source/customizations/overview.mdx
docs/source/customizations/rhai.mdx

* Minor fixes to examples 
* Generally fix up headings
* Update the rhai docs to make the emphasis on experimentalness stronger

Minor doc fixes

---

CHANGELOG.md
apollo-router/src/executable.rs
docs/source/configuration/logging.mdx
docs/source/configuration/subgraph-routing-urls.mdx

Improve logging page
Improve subgraph URL override title.

Improve logging functionality

---

docs/source/migrating-from-gateway.mdx

fast-follow on #687, which i failed to push some changes to

docs: follow-up to gateway migration in #687

---

CHANGELOG.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/telemetry.rs
apollo-router/src/plugins/telemetry/otlp/grpc.rs
apollo-router/src/plugins/telemetry/otlp/mod.rs
apollo-router/src/router_factory.rs

This PR makes the OTLP code roughly the same as the Jaeger code.
This fixes the hang on reload.

Fix OTLP hang

---

CHANGELOG.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/telemetry.rs
docs/source/configuration/opentelemetry.mdx

Adds custom serialization for `trace_config`->`attributes`
Previously we relied on the default serialization of Otel datastructures. However this produced rather complicated yaml where the user had to specify the type of each attribute.
We now have our own mirror types that include serde directives to make things nicer.
Example config is:
```yaml
telemetry:
opentelemetry:
otlp:
tracing:
exporter:
grpc:
protocol: Grpc
trace_config:
attributes:
str: "a"
int: 1
float: 1.0
bool: true
str_arr:
- "a"
- "b"
int_arr:
- 1
- 2
float_arr:
- 1.0
- 2.0
bool_arr:
- true
- false
``` 
Also applies to Jaeger

Make otel attribute config nice

---

docs/source/customizations/overview.mdx
examples/README.md
examples/context/README.md
examples/status-code-propagation/README.md

Update the hello world example git hash.
Add a readme for the examples
Improve sequence diagrams

Slight doc improvements.

---

CHANGELOG.md
apollo-router-core/src/error.rs
apollo-router-core/src/plugin_utils/structures/execution_response.rs
apollo-router-core/src/plugin_utils/structures/router_response.rs
apollo-router-core/src/plugin_utils/structures/subgraph_response.rs
apollo-router-core/src/response.rs
apollo-router/src/warp_http_server_factory.rs

Remove hasNext.
It can be added again when we come to support defer.

Remove hasNext

---

CHANGELOG.md
Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/executable.rs
apollo-router/src/lib.rs
docs/source/configuration/overview.mdx
licenses.html
uplink/Cargo.toml
uplink/src/lib.rs

Unified handling for our env variables. It's Clap or nothing.
There are a couple of other env variables that exist, but these will be eliminated rather than persisted.
Moved apollo_key, apollo_graph_ref to StructOpt,
Created apollo_schema_config_delivery_endpoint, apollo_schema_poll_interval
Added code that copies all values from Clap to the environment, that way Clap is still the source of truth, but if we have any env variable stuff still around it will continue to work. 
I tested everything manually.

Apollo uplink configurability

---

.circleci/config.yml
CHANGELOG.md
dockerfiles/Dockerfile.router
dockerfiles/router.yaml
docs/source/config.json
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
docs/source/containerization/overview.mdx

There are some notes in the CHANGELOG.md file about how to use the image.
It can probably be improved quite a bit, but it's enough to get things moving.
fixes: #728 #79 #748

dockerfile example and publish on release to github

---

apollo-spaceport/src/server.rs

add a user-agent header to the studio usage ingress submission

---

CHANGELOG.md
licenses.html
xtask/src/commands/all.rs
xtask/src/commands/compliance.rs
xtask/src/commands/lint.rs

`cargo xtask all` will now actually format your code and apply the license update for you!

chore: Quality of Life: xtask all improvements.

---

apollo-router-core/src/plugin.rs

docs: document the Plugin and DynPlugin trait

---

CHANGELOG.md
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-2.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-3.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-4.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_grpc-2.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_grpc.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_http-2.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_http.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_tls_config.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__supergraph_config_serde.snap
apollo-router/src/warp_http_server_factory.rs
docs/source/configuration/overview.mdx

add option to disable the landing page

---

Cargo.lock
apollo-router/Cargo.toml

remove openssl from zipkin's dependencies

---

Cargo.lock
apollo-router/Cargo.toml
apollo-spaceport/Cargo.toml
licenses.html
uplink/Cargo.toml

a normal cargo build will go from 630 compiled dependencies to 597

reduce dependencies and features

---

NEXT_CHANGELOG.md
apollo-router-core/src/services/mod.rs
apollo-router/src/axum_http_server_factory.rs

improve the way we handle Request with axum

---

apollo-router-benchmarks/Cargo.toml
apollo-router-benchmarks/benches/basic_composition.rs
apollo-router-benchmarks/src/lib.rs
apollo-router-benchmarks/src/shared.rs

this extracts the main functionality of the benchmarks in a shared
module that is run in a unit test

fix benchmarks and add unit tests to guard them

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs

Take the operation name either from the query or from the body

---

NEXT_CHANGELOG.md
apollo-router-core/src/layers/instrument.rs

Remove boxing in instrument

---

NEXT_CHANGELOG.md
examples/embedded/README.md

Add more details about pros and cons so that users know what they're letting themselves in for.

Improve readme for embedded router.

---

docs/source/configuration/apollo-telemetry.mdx

And `export` the variables for use in another process. 
The router doesn't support `.env` files so this hopefully will alleviate any confusion for users coming from the node.js world.

docs: remove '.env' from usage reporting env docs

---

apollo-router/src/plugins/rhai.rs

PR into a temporary non-`main` branch.
CC https://github.com/apollographql/router/issues/889

Minor cleanups for ongoing the Rhai plugin rewrite

---

apollo-router/src/plugins/telemetry/mod.rs
apollo-router/tests/integration_tests.rs

hanging tests are a source of heartburn

---

NEXT_CHANGELOG.md
apollo-router/src/executable.rs
apollo-router/src/lib.rs

Add license notice to first line of Router output

---

apollo-router-core/src/layers/cache.rs
apollo-router-core/src/response.rs
apollo-router-core/src/services/mod.rs
apollo-router-core/src/services/router_service.rs
apollo-router/src/configuration/mod.rs

Still not complete, but more "coverage"...

Add more documentation (cargo doc style)

---

dockerfiles/Dockerfile.router

APOLLO_ROUTER_CONFIGURATION_PATH -> APOLLO_ROUTER_CONFIG_PATH

fix dockerfile definition to match environment rename

---

CHANGELOG.md

Just some polish on the CHANGELOG.md for the release.  This is nitty to a
large degree, but I'm happy to entertain nits to my own nits, too.

docs: editorial on release notes for RC

---

README.md

Came to make a small grammatical tweak, stayed to put "supergraph" in a semantically appropriate place.

Grammatical tweak and minor supergraphification

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/metrics/apollo.rs
apollo-router/src/plugins/telemetry/metrics/apollo/duration_histogram.rs
apollo-router/src/plugins/telemetry/metrics/apollo/snapshots/apollo_router__plugins__telemetry__metrics__apollo__studio__test__aggregation.snap
apollo-router/src/plugins/telemetry/metrics/apollo/studio.rs
apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_multiple_operations.snap
apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_parse_failure.snap
apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_single_operation.snap
apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_unknown_operation.snap
apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_validation_failure.snap
apollo-router/src/plugins/telemetry/mod.rs

This starts to make the internal rust datastructures deviate from the protobuf. The reason we need to do this is that some of the protobuf fields are derived from the histogram count.

Fix error count cache counts.

---

apollo-router/src/plugins/rhai.rs
docs/source/customizations/rhai.mdx

also: add support for manipulating headers from ExecutionResponse and
SubgraphResponse

Improve rhai documentation

---

scripts/install.sh

I ran into this when I first tried to install - making it a little more clear for newcomers who don't necessarily understand what's going on.

friendlier language for command not found

---

NEXT_CHANGELOG.md
scripts/install.sh

chore: delete the requirement of jq in our install script and be POSIX compliant

---

NEXT_CHANGELOG.md
apollo-router-core/src/spec/schema.rs
apollo-router-core/src/testdata/starstuff@current.graphql
apollo-router/src/router_factory.rs
apollo-router/src/testdata/starstuff@current.graphql

Fix and add test for API schema hashing

Fix api_schema id hashing

---

CHANGELOG.md
NEXT_CHANGELOG.md

follow up for https://github.com/apollographql/router/pull/1042#pullrequestreview-972464770

update changelog message

---

apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/rhai.rs
docs/source/customizations/rhai.mdx
examples/add-timestamp-header/src/add_timestamp_header.rhai
examples/cookies-to-headers/src/cookies_to_headers.rhai
examples/op-name-to-header/src/op_name_to_header.rhai
examples/rhai-data-response-mutate/src/rhai_data_response_mutate.rhai
examples/rhai-error-response-mutate/src/rhai_error_response_mutate.rhai
examples/rhai-logging/src/rhai_logging.rhai

In the course of adding the extra documentation also:
- improved the rhai plugin slightly
- pure for getters
- to_string for context
- pub(crate) for many things
- improved a couple of the examples to illustrate concepts
- added a description for Rhai plugin which updated snapshot
fixes: #1056

Add details to the rhai documentation

---

NEXT_CHANGELOG.md
apollo-router-core/Cargo.toml
apollo-router/Cargo.toml
examples/async-auth/Cargo.toml
examples/hello-world/Cargo.toml
examples/jwt-auth/Cargo.toml
examples/status-code-propagation/Cargo.toml

Pin version to 0.8.8
See #1074

Pin schemars to 0.8.8

---

docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
docs/source/containerization/overview.mdx
docs/source/customizations/native.mdx
docs/source/quickstart.mdx
examples/embedded/README.md

chore: add license notices

---

apollo-router/tests/snapshots/infrastructure_tests__starstuff_supergraph_is_valid.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap
examples/graphql/supergraph.graphql

the subgraphs deployed on fly.io for demo purpose were updated, and the
supergraph schema changed

update the deployed supergraph schema

---

NEXT_CHANGELOG.md
scripts/install.sh
xtask/src/commands/package/mod.rs

fix: fix the installation script for windows with the extension

---

scripts/ci-build.sh

CI steps are now defined in .circleci/config.yml

Remove obsolete scripts/ci-build.sh

---

NEXT_CHANGELOG.md
apollo-router-core/src/spec/query.rs

fix the introspection query detection

---

xtask/src/commands/lint.rs

Fixes https://github.com/apollographql/router/issues/25

Run Clippy on all Cargo targets in xtask and CI

---

NEXT_CHANGELOG.md
apollo-router-core/src/plugin/utils/test/mod.rs
apollo-router-core/src/plugin/utils/test/snapshots/apollo_router_core__plugin__utils__test__testing__test_harness.snap

Add `call_canned` on `PluginTestHarness`. It performs a well known query that will generate a valid response.

Add `call_canned` to `PluginTestHarness`

---

Cargo.lock
apollo-router/Cargo.toml

Re-release with bumped version number

release: v0.9.2

---

NEXT_CHANGELOG.md
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap

- Use consistent (`###`) headings for each item, per example
- Use code-fences around code
- Added contributor usernames per a previous agreement that we do that. (Also updated the example template to include this!)
- Apply consistent use of `Issue` — rather than PR — in the title, when available (usually!)
- Apply consistent formatting to issues (parentheticals!)
- Add link to relevant context where applicable (e.g., Package names that might not be clear to the reader that they are crates, or to examples which might be otherwise challenging for the reader to find)
- Did some wordsmithing.

chore: editorial on `NEXT_CHANGELOG.md` prior to releasing.

---

docs/source/configuration/cors.mdx

docs: Change "Server" to "Router"

---

NEXT_CHANGELOG.md

All my fault I made a mistake by playing with GH suggestion on the original PR #1164

fix changelog

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/plugin/utils/test/mod.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/services/execution_service.rs
apollo-router/src/services/http_compat.rs
apollo-router/src/services/mod.rs
apollo-router/src/services/router_service.rs
licenses.html

The router is using an old version of buildstructor that had many issues with generics. Updating so that we can see if these are fixed.

Update buildstructor to 0.3.

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/http_server_factory.rs
apollo-router/src/router.rs
apollo-router/src/state_machine.rs
apollo-router/src/subscriber.rs

Rename `FederatedServerError` to `ApolloRouterError` for consistency with other naming

Rename FederatedServerError to ApolloRouterError

---

CHANGELOG.md
NEXT_CHANGELOG.md

Twice the emoji isn't merely twice the impact/fun/fix, even if we'd perhaps love that
No attached GitHub issue because this is small, so I've put the PR on the board in exchange for that.

chore: Update `NEXT_CHANGELOG.md` to not have twice the emoji

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/rhai.rs
apollo-router/src/request.rs
apollo-router/src/services/router_service.rs
docs/source/customizations/rhai.mdx

add support for modifying request variables from a plugin

---

NEXT_CHANGELOG.md

Ensure the contributor is correctly acknowledged.

fix NEXT_CHANGELOG.md for user contribution

---

helm/chart/router/templates/_helpers.tpl
helm/chart/router/templates/deployment.yaml

I'll not rev the helm chart, since these fixes are swiftly following on.

fix errors in helm chart

---

apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap

I meant this to be part of https://github.com/apollographql/router/pull/1271 and
messed up my commit amend

Fix config schema test after doc change

---

NEXT_CHANGELOG.md
helm/chart/router/Chart.yaml
helm/chart/router/templates/deployment.yaml

Yeah, so... in my [last PR](https://github.com/apollographql/router/pull/1245) I accidentally broke some if logic for environmental variables and volume mounts with the pre-existing code. This code will fix it. Lmk what you need and I'll get it done.

fixed if statement flow for env and volume mounts

---

.tool-versions
apollo-router-scaffold/templates/base/.tool-versions
dockerfiles/diy/dockerfiles/Dockerfile.repo
docs/source/customizations/custom-binary.mdx
renovate.json5
rust-toolchain.toml

I observed https://github.com/apollographql/router/pull/1333 was a PR that
Renovate opened to update to a more recent version of `rustc`.  While
updating our Rust version in general makes sense, it doesn't make any sense
to do in isolation.  Rather, it need to be set in various places in our
repository that rely on that being set in lock-step.
Those different places we use the version are not done in way that can
easily be DRY, but Renovate can help us open PRs that touch the right
places all at once.
This uses a special syntax and ... a regex ... to do that.
Renovate is actually built on Regex for the most part, so mostly just
perpetuating it here, I swear.
I chose to use Docker as the version source since I figure once it gets
published to Docker, the version is also available through …

renovate rustc globally, rather than individually

---

dockerfiles/diy/dockerfiles/Dockerfile.release
dockerfiles/diy/dockerfiles/Dockerfile.repo

In PR: 1279 I patched up the Dockerfile build for the
router docker image, but didn't patch up the diy
dockerfile builds.
This now fixes the diy dockerfiles...

extend fix for compression support to DIY dockerfiles

---

CHANGELOG.md

I'm unfortunately just a couple minutes too slow!
Follows up #1351

v0.10.0 CHANGELOG edits

---

NEXT_CHANGELOG.md
apollo-router/src/spec/query.rs
apollo-router/src/spec/selection.rs

fix(query): fix fragment on interface without typename

---

docs/shared/elastic-notice.mdx
docs/source/config.json
docs/source/configuration/apollo-telemetry.mdx
docs/source/configuration/cors.mdx
docs/source/configuration/header-propagation.mdx
docs/source/configuration/metrics.mdx
docs/source/configuration/overview.mdx
docs/source/configuration/subgraph-error-inclusion.mdx
docs/source/configuration/tracing.mdx
docs/source/configuration/traffic-shaping.mdx
docs/source/containerization/overview.mdx
docs/source/customizations/custom-binary.mdx
docs/source/index.mdx
docs/source/migrating-from-gateway.mdx
docs/source/quickstart.mdx

Working my way through changes that have occurred since my last pass

Various docs edits

---

dockerfiles/tracing/datadog-subgraph/package-lock.json
dockerfiles/tracing/jaeger-subgraph/package-lock.json
dockerfiles/tracing/zipkin-subgraph/package-lock.json

this will remove the vulnerability warning for dicer

update dependencies in tracing examples

---

examples/add-timestamp-header/src/main.rs
examples/cookies-to-headers/src/main.rs
examples/op-name-to-header/src/main.rs
examples/rhai-data-response-mutate/src/main.rs
examples/rhai-error-response-mutate/src/main.rs
examples/rhai-logging/src/main.rs
examples/rhai-subgraph-request-log/router.yaml
examples/rhai-subgraph-request-log/src/main.rs
examples/rhai-surrogate-cache-key/src/main.rs

The examples weren't updated correctly during the rhai promotion from
experimentation. Fixing them now.

fix rhai examples following rhai stabilisation PR (#1365)

---

docs/source/customizations/rhai.mdx
examples/README.md

Remove experimental for references to rhai

---

Cargo.lock
licenses.html

Fixes https://github.com/apollographql/router/issues/1318

Upgrade moka and crossbeam-* dependencies

---

NEXT_CHANGELOG.md
apollo-router/src/spec/query.rs

Fix: Selection merge on non object field alias

---

CHANGELOG.md
NEXT_CHANGELOG.md

Just some missing parenthesis and a couple formatting changes for the`NEXT_CHANGELOG.md`

chore: Update `NEXT_CHANGELOG.md` formatting.

---

NEXT_CHANGELOG.md
README.md

This PR updates some wording in the router docs. Some of these changes y'all may not want to make, but I think most of them are helpful changes.

docs: updates some readme wording

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/plugins/telemetry/otlp.rs
apollo-router/src/plugins/telemetry/snapshots/apollo_router__plugins__telemetry__otlp__metadata_map_serde__tests__serialize_metadata_map.snap

- fixes #1166
- changes data structure to a `IndexMap<String, Vec < String>>`
- updated test case
Signed-off-by: Rohit Dandamudi <rohitdandamudi.1100@gmail.com>

fix: update serialization format

---

apollo-router/src/introspection.rs
apollo-router/src/spec/introspection_types.graphql

Fixes https://github.com/apollographql/router/issues/1450

Introspection support for includeDeprecated, isDeprecated, and deprecationReason

---

NEXT_CHANGELOG.md
apollo-router-benchmarks/src/shared.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/introspection.rs
apollo-router/src/plugin/test/mod.rs
apollo-router/src/plugins/include_subgraph_errors.rs
apollo-router/src/plugins/traffic_shaping/mod.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/query_planner/selection.rs
apollo-router/src/router.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/router_service.rs
apollo-router/src/spec/query.rs
apollo-router/src/spec/schema.rs
apollo-router/src/state_machine.rs
apollo-router/tests/infrastructure_tests.rs
apollo-router/tests/integration_tests.rs
apollo-router/tests/rhai_tests.rs
examples/embedded/src/main.rs

If an operation exceeds the limit, the router returns an error without processing it.

Add `server.experimental_parser_recursion_limit` configuration

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/mod.rs

This PR adds:
* additionalProperties: false to the root of the schema, which improves user experience.
* Stops failure on an empty config.
The version can be used by schemastore later.

Router config enhancement

---

.circleci/config.yml

which doesn't expire.
fixes: #1453

replace personal token with apollo-bot2 token

---

Cargo.lock

fix router-bridge build

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/tests/jaeger_test.rs
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap

fix(tracing): add opentelemetry semantic attributes

---

NEXT_CHANGELOG.md
apollo-router/src/layers/mod.rs

Fixes https://github.com/apollographql/router/issues/1152

Remove ServiceBuilderExt::cache

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/mod.rs
apollo-router/src/error.rs
apollo-router/src/graphql.rs
apollo-router/src/layers/cache.rs
apollo-router/src/layers/instrument.rs
apollo-router/src/layers/map_future_with_request_data.rs
apollo-router/src/layers/sync_checkpoint.rs
apollo-router/src/lib.rs
apollo-router/src/plugin/mod.rs
apollo-router/src/plugin/serde.rs
apollo-router/src/plugin/test/mock/subgraph.rs
apollo-router/src/plugin/test/service.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/request.rs
apollo-router/src/response.rs
apollo-router/src/router.rs
apollo-router/src/services/http_ext.rs
apollo-router/src/services/mod.rs
apollo-router/src/stages.rs
apollo-router/src/test_harness.rs

Part of https://github.com/apollographql/router/issues/799

Warn on missing docs, with allow exceptions to be removed progressively

---

docs/source/customizations/rhai.mdx

doc: correct subgraph_service rhai signature

---

apollo-router/src/plugins/telemetry/mod.rs
apollo-router/tests/jaeger_test.rs
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap

Follow up to https://github.com/apollographql/router/pull/1534

Change a telemetry span name from "router" to "supergraph"

---

apollo-router/src/axum_http_server_factory.rs
apollo-router/src/graphql.rs
apollo-router/src/plugins/telemetry/metrics/prometheus.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/request.rs
apollo-router/src/services/layers/apq.rs
apollo-router/src/services/supergraph.rs
apollo-router/src/services/transport.rs
apollo-router/tests/integration_tests.rs

Part of https://github.com/apollographql/router/issues/1553

Reduce uses of http_ext

---

apollo-router/src/axum_http_server_factory.rs
apollo-router/src/router.rs

Part of https://github.com/apollographql/router/issues/1496

Add internal HTTP-level Tower service

---

NEXT_CHANGELOG.md
apollo-router/src/axum_http_server_factory.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/error.rs
apollo-router/src/graphql.rs
apollo-router/src/lib.rs
apollo-router/src/response.rs
apollo-router/src/router.rs
apollo-router/src/spec/mod.rs
apollo-router/tests/integration_tests.rs

See commit descriptions of individual commits
Part of https://github.com/apollographql/router/issues/81

Make some error enums private, remove unused variants

---

docs/source/customizations/native.mdx

Fixes https://github.com/apollographql/router/issues/1590

Update website plugin documentation for renamed APIs.

---

helm/chart/router/Chart.yaml
helm/chart/router/templates/service.yaml
helm/chart/router/values.yaml

fixes apollographql/router/issues/1626

docs: add support for helm service resource annotations

---

DEVELOPMENT.md

A few updates from my first encounter with the router project. Many thanks @o0Ignition0o for the help 🙌

docs: Update DEVELOPMENT.md

---

apollo-router/src/plugins/expose_query_plan.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/query_planner/mod.rs

Make the formatted_query_plan optional.

---

Cargo.lock
apollo-router/Cargo.toml

To bring in https://github.com/apollographql/federation-rs/pull/166
Via: https://github.com/apollographql/federation-rs/pull/167

deps: update router-bridge to 0.1.2.

---

RELEASE_CHECKLIST.md

Clarify that the thing needing updating in scaffolds is `dependencies` tags,
not `versions`.

docs: Update `RELEASE_CHECKLIST.md` again to be more precise.

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/lib.rs
apollo-router/src/plugin/mod.rs
apollo-router/src/router_factory.rs
licenses.html

I've implemented the change so that we declare a function in private scope to register each plugin.
fixes: #1703

replace startup with ctor for plugin registration

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/plugin/mod.rs
apollo-router/src/plugins/rhai.rs
apollo-router/tests/fixtures/test.rhai
docs/source/customizations/rhai-api.mdx

also:
- fix a long standing problem with scope which means global variables now work properly in our rhai scripts.
- add support for downcasting DynPlugin in test which makes testing a little simpler (I know, we don't like downcasting, but it's helpful in some kinds of testing)
fixes: #1735

add support for accessing the SDL from rhai plugins

---

apollo-router/Cargo.toml
apollo-router/build/spaceport.rs
apollo-router/src/test_harness.rs
apollo-router/testing_schema.graphql

https://github.com/apollographql/router/issues/491

Prepare for publication to crates.io

---

Cargo.lock
NEXT_CHANGELOG.md
apollo-router/Cargo.toml
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__expansion_failure_missing_variable.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__expansion_failure_unknown_mode.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__it_does_not_leak_env_variable_values.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_errors_after_first_field_env_expansion.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_inline_sequence_env_expansion.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_sequence_env_expansion.snap
apollo-router/src/configuration/testdata/tracing_apollo_env.router.yaml
apollo-router/src/configuration/testdata/tracing_datadog_env.router.yaml
apollo-router/src/configuration/testdata/tracing_jaeger_collector_env.router.yaml
apollo-router/src/configuration/testdata/tracing_otlp_grpc_basic_env.router.yaml
apollo-router/src/configuration/testdata/zipkin-url_env.router.yaml
docs/source/configuration/overview.mdx
docs/source/configuration/tracing.mdx
licenses.html

* Environment expansions must be prefixed with `env.`. This will allow us to add other expansion types in future.
* Change defaulting token from `:` to `:-`. For example:
`${env.USER_NAME:Nandor}` => `${env.USER_NAME:-Nandor}`
* Failed expansions result in an error.
Previously expansions that failed due to missing environment variables were silently skipped. Now they result in a configuration error. Add a default if optional expansion is needed.
The environment variable: `APOLLO_ROUTER_CONFIG_ENV_PREFIX` can be used to prefix environment variable lookups during configuration expansion. This may be useful for security. This feature is undocumented and unsupported and may change at any time.
For example: 
`APOLLO_ROUTER_CONFIG_ENV_PREFIX=MY_PREFIX`
Would cause:
`${env.FOO}` to be mapped to …

Environment expansion enhancements

---

DEVELOPMENT.md

Add "getting started" step re: git submodules
This PR adds clarity to the Getting Started section of the Apollo Router development guide with respect to the use of git submodules when running the `federation-demo` for testing purposes. As it stands, there is no mention of our use of git submodules in the guide, and running through the process as described fails at the container build stage due to missing files/context. While a little investigative work makes the reason for the above occurrence  clear, including this information up front makes for a better development experience.

Update development guide to include info re: use of git submodules

---

apollo-router/src/graphql.rs
apollo-router/src/http_ext.rs
apollo-router/src/test_harness.rs

Part of https://github.com/apollographql/router/issues/799 and https://github.com/apollographql/router/issues/1528

Add doc-comments in graphql.rs, test_harness.rs

---

apollo-router/src/executable.rs

Part of https://github.com/apollographql/router/issues/1528

Document builder methods for `Executable`

---

NEXT_CHANGELOG.md
apollo-router/src/plugins/telemetry/mod.rs

These warnings were introduced in #1632

add more gates to not have warnings when using --all-features

---

NEXT_CHANGELOG.md
apollo-router/src/query_planner/mod.rs
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__tests__defer_if_condition-2.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__tests__defer_if_condition-3.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__tests__defer_if_condition.snap
apollo-router/src/query_planner/testdata/defer_clause.graphql
apollo-router/src/query_planner/testdata/defer_clause_plan.json
apollo-router/src/services/subgraph_service.rs

fixes #1820
According to the defer specification, defer conditions are mandatory and default to true.
We fixed a bug where the default value wasn't initialized properly.

Defer: default the if clause to true

---

NEXT_CHANGELOG.md
helm/chart/router/Chart.yaml
helm/chart/router/templates/deployment.yaml

fix extraVolume Mounts regression

---

NEXT_CHANGELOG.md
apollo-router-scaffold/src/plugin.rs

fix(router-scaffold): add 'v' prefix for cargo version

---

.gitmodules
dockerfiles/federation-demo/.dockerignore
dockerfiles/federation-demo/Dockerfile

This attempts to remove git submodules we don't believe we need anymore.

nit: Remove git submodules

---

apollo-router/src/request.rs

Partially contributes to https://github.com/apollographql/router/issues/799
which aims to document the public API for the published Crate's
documentation which appears on [`docs.rs`].
[`docs.rs`]: https://docs.rs/crate/apollo-router

docs: `apollo-router/src/request.rs`

---

apollo-router/README.md

I couldn't locate any changes in our documentation that were relevant to the issue that this PR aims to close, so these changes are all about the `README.md`.
Closes: https://github.com/apollographql/router/issues/1849

chore(docs): Update README for v1.0.0

---

NEXT_CHANGELOG.md
apollo-router/Cargo.toml

This field states what we want our minimum supported Rust version to be:
https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
> If the currently selected version of the Rust compiler is older than the stated version, cargo will exit with an error, telling the user what version is required.
This profiles a better error message than random compilation errors.
1.63.0 is our de-facto MSRV at the moment as it is what we use on CI. I’ll file a separate issue to discuss how we want to evolve it.

Add a rust-version field in apollo-router/Cargo.toml

---

NEXT_CHANGELOG.md
dockerfiles/diy/build_docker_image.sh

Particularly useful when building a dockerfile for testing against a local repo.

add -r flag to diy dockerfile build script

---

apollo-router/README.md

Fixes https://github.com/apollographql/router/issues/1312, together with https://github.com/apollographql/router/pull/1886

Document the MSRV in README.md

---

docs/source/configuration/apollo-telemetry.mdx

This is covered here instead: https://www.apollographql.com/docs/router/configuration/metrics/ ... just trying to avoid some confusion!

Remove prometheus config from Studio reporting docs

---

Cargo.lock
apollo-router/Cargo.toml

This version includes https://github.com/apollographql/federation-rs/pull/198

Update router-bridge to 0.1.10

---

apollo-router/src/tracer.rs

They are less annoying and have more comments, but I can't figure out how to remove the random `dbg!(SpanData)` that we get during some executions.

make the tracer tests less annoying

---

NEXT_CHANGELOG.md
apollo-router/src/axum_factory/utils.rs

the `Accept` header means `*/*` when it is absent

assume Accept: application/json when no accept header is present

---

docs/source/configuration/health-checks.mdx

adding missing escape chars to the code block

fixing router healthcheck formatting

---

Cargo.lock
fuzz/Cargo.toml

Avoid staying on a yanked version: https://github.com/apollographql/apollo-rs/issues/351

Update to apollo-smith 0.2

---

apollo-router/src/spaceport/proto/reports.proto

chore: update protobuf

---

Cargo.lock
apollo-router-scaffold/Cargo.toml
docs/source/customizations/custom-binary.mdx

close #2207 
Also related to https://github.com/apollographql/router/issues/2165

docs: specify the main branch for cargo scaffold to not target default dev branch

---

NEXT_CHANGELOG.md
README.md
apollo-router/src/executable.rs
apollo-router/src/plugins/telemetry/apollo_exporter.rs
apollo-router/src/router.rs
apollo-router/src/uplink/mod.rs
docs/source/configuration/overview.mdx
licenses.html

This PR adds a timeout to apollo uplink schema polling (30s by default, configurable) and reports (90s, not configurable).

Feature: Apollo uplink: connection timeouts

---

Cargo.lock
apollo-router/Cargo.toml

it was incompatible with redis_cluster_async

rollback redis update

---

CHANGELOG.md

Some edits I'd like to apply to the changelog for #2312.

1.7.0 CHANGELOG editorial

---

docs/source/containerization/docker.mdx

docs: fix custom binary link

---

.github/workflows/github_projects_tagger.yml

This will facilitate some behind-the-scenes automation that executes in our planning repository and can help applying metadata to pull requests and issues automatically.

infra: Trigger webhooks when pull requests are created

---

NEXT_CHANGELOG.md
apollo-router-scaffold/templates/base/xtask/Cargo.toml

chore: upgrade clap version in scaffold template

---

NEXT_CHANGELOG.md
apollo-router/src/services/subgraph_service.rs
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap

fix:  span is set as the parent of traces coming from subgraphs

---

NEXT_CHANGELOG.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/telemetry/apollo.rs
apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap

fix: Change the default value of apollo.field_level_instrumentation_sampler

---

NEXT_CHANGELOG.md
apollo-router/src/spec/query.rs
apollo-router/src/spec/query/tests.rs

fix: handle aliased __typename

---

CONTRIBUTING.md
docs/source/configuration/authn-jwt.mdx
docs/source/containerization/docker.mdx
docs/source/customizations/native.mdx
docs/source/privacy.mdx

Hi. I fixed some spelling mistakes I found in the docs while reading through them. I also fixed one spelling mistake in CONTRIBUTING.md which was found while making this PR.  
**Checklist**
~~- [ ] Changes are compatible[^1]~~
~~- [ ] Documentation[^2] completed~~
~~- [ ] Performance impact assessed and acceptable~~
~~- Tests added and passing[^3]~~
~~- [ ] Unit Tests~~
~~- [ ] Integration Tests~~
~~- [ ] Manual Tests~~
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to …

Fix spelling mistakes in documentation

---

docs/source/customizations/overview.mdx

The participant name was incorrect

Fix mermaid graph

---

NEXT_CHANGELOG.md
docs/source/privacy.mdx

Fix the documentation to disable the Apollo telemetry

---

NEXT_CHANGELOG.md

Just some editorial polish to get out ahead of the release.

Changelog editorial prior to 1.10.0 release

---

NEXT_CHANGELOG.md
apollo-router-scaffold/templates/base/Dockerfile
apollo-router/Cargo.toml
apollo-router/README.md
apollo-router/src/configuration/expansion.rs
apollo-router/src/query_planner/execution.rs
apollo-router/src/query_planner/selection.rs
apollo-router/src/router.rs
apollo-router/src/uplink/entitlement.rs
apollo-router/src/uplink/schema.rs
apollo-router/tests/apollo_reports.rs
dockerfiles/diy/dockerfiles/Dockerfile.repo
docs/source/customizations/custom-binary.mdx
examples/jwt-auth/rust/src/jwt.rs
rust-toolchain.toml
xtask/src/commands/package/macos.rs
xtask/src/commands/package/mod.rs
xtask/src/commands/release.rs
xtask/src/federation_demo.rs
xtask/src/jaeger.rs

Fixes https://github.com/apollographql/router/pull/1873
**Checklist**
**Exceptions**
No behavior change
**Notes**
- please raise a separate issue …

Upgrade to Rust 1.67.0

---

Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router/Cargo.toml
examples/add-timestamp-header/rhai/Cargo.toml
examples/async-auth/rust/Cargo.toml
examples/context/rust/Cargo.toml
examples/cookies-to-headers/rhai/Cargo.toml
examples/data-response-mutate/rhai/Cargo.toml
examples/embedded/rust/Cargo.toml
examples/error-response-mutate/rhai/Cargo.toml
examples/forbid-anonymous-operations/rhai/Cargo.toml
examples/forbid-anonymous-operations/rust/Cargo.toml
examples/hello-world/rust/Cargo.toml
examples/jwt-auth/rust/Cargo.toml
examples/jwt-claims/rhai/Cargo.toml
examples/logging/rhai/Cargo.toml
examples/op-name-to-header/rhai/Cargo.toml
examples/status-code-propagation/rust/Cargo.toml
examples/subgraph-request-log/rhai/Cargo.toml
examples/supergraph-sdl/rust/Cargo.toml
examples/surrogate-cache-key/rhai/Cargo.toml

Found with https://github.com/bnjbvr/cargo-machete
**Checklist**
**Exceptions**
**Notes** …

Remove some unused dependencies

---

.changesets/feat_geal_cache_size_metric.md
apollo-router/src/cache/storage.rs
apollo-router/src/plugins/telemetry/metrics/layer.rs
apollo-router/tests/snapshots/tracing_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/tracing_tests__traced_basic_request.snap
apollo-router/tests/snapshots/tracing_tests__variables.snap

add a metric to track the cache size

---

.changesets/exp_garypen_jwt_cleanup_logging.md
apollo-router/src/plugins/authentication.rs

Because it was very messy with strings everywhere.

Clean up the JWT authentication error handling and messaging

---

.changesets/feat_garypen_rhai_re_org.md
apollo-router/src/plugins/rhai/execution.rs
apollo-router/src/plugins/rhai/mod.rs
apollo-router/src/plugins/rhai/subgraph.rs
apollo-router/src/plugins/rhai/supergraph.rs
apollo-router/src/plugins/rhai/tests.rs
apollo-router/tests/fixtures/global_variables_test.rhai
docs/source/configuration/authn-jwt.mdx
docs/source/customizations/rhai-api.mdx
examples/add-timestamp-header/rhai/src/add_timestamp_header.rhai
examples/jwt-claims/rhai/src/jwt_claims.rhai

also:
- do some basic re-organising of the rhai code
- update documentation and examples to use new "constants"
Fixes #2627
**Checklist**
~- [ ] Integration Tests~
~- [ ] Manual Tests~
**Exceptions**
**Notes** …

Add a global variable resolver for rhai

---

.changesets/docs_bnjjj_doc_2580.md
apollo-router/src/context.rs

docs: better documentation for Context::get

---

.changesets/fix_bnjjj_fix_2559.md
apollo-router/src/router_factory.rs
apollo-router/tests/fixtures/prometheus.router.yaml
apollo-router/tests/metrics_tests.rs

Force ordering of headers plugin to have better interaction with other plugins
Fixes #2559
**Checklist**
**Exceptions**
**Notes** …

fix: force ordering of headers plugin

---

apollo-router/src/uplink/mod.rs

Adds a debug message for uplink responses

Add some debug for uplink.

---

.circleci/config.yml
xtask/src/commands/lint.rs
xtask/src/commands/test.rs

This commit reworks the CI config to simplify and speed up the total runtime.
The use of caching has been reexamined, and now uses the following:
* Daily cache for toolchain and related utilities. Can change independently of other caches.
* Closest common ancestor to dev for target directory. This means that when a branch is merged into dev it will take longer to run as it will be creating caches, but branches off of dev will be quick to run. This should mean PRs are quick, which is the vast majority of builds.
Removed much platform specific behavior by using bash as the shell for windows, and doing a little pre-setup to remove differences between environments.
**Checklist** …

Simplify ci config

---

router-old.yaml

In a previous commit I accidentally added router.old.yaml

Remove accidentally added file

---

.changesets/config_creek_cornbread_dam_greenhouse.md

Add missing changeset for #2744

Add missing changeset for #2744

---

helm/chart/router/templates/deployment.yaml

Fixes #2787
**Checklist**
**Exceptions**
**Notes**
- please raise a separate issue to automate the …

Fix apollographql/router#2787

---

apollo-router/src/plugins/telemetry/proto/reports.proto

update reporting .proto
**Checklist**
**Exceptions**
**Notes**
- please raise a separate issue to automate the test and …

update reporting .proto

---

.changesets/maint_the_universe_just_loves_proving_me_wrong.md
apollo-router/tests/common.rs
apollo-router/tests/datadog_test.rs
apollo-router/tests/jaeger_test.rs
apollo-router/tests/lifecycle_tests.rs
apollo-router/tests/metrics_tests.rs
apollo-router/tests/otlp_test.rs
apollo-router/tests/zipkin_test.rs
licenses.html

It now uses buildstructor, and is simpler to use.
Graceful shutdown test has been simplified.
Stack dump on failed shutdown fixed.
Fixes #2809
**Checklist**
**Exceptions**
**Notes**
- please …

Improve integration test harness

---

.changesets/fix_geal_remove_client_setname_from_fred.md
Cargo.lock
apollo-router/Cargo.toml

do not use CLIENT SETNAME in Redis

---

.changesets/feat_bladder_dresser_glad_pill.md
.changesets/fix_where_were_going_we_dont_need_roads.md
apollo-router/src/router.rs
apollo-router/src/uplink/mod.rs
apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_unchanged_error.snap
apollo-router/tests/metrics_tests.rs
docs/source/configuration/metrics.mdx

Revert continuing to check endpoints if we get an unchanged response.
Remove the use of round-robin strategy, this is more suited to querying datasources where consistency is not guaranteed.
Add a metric for total success or failure of uplink fetches and ensure consistency of naming.
Fixes #2794
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part of many changes. …

Uplink enhancements

---

apollo-router/src/uplink/uplink.graphql

Although there are no functional changes (only comments), this fixes the test checking that it’s up to date.
Fixes https://app.circleci.com/pipelines/github/apollographql/router/11279/workflows/ef1a96c5-9ffd-4298-b49c-0d5dec4eca5d/jobs/74684?invite=true#step-116-1055
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part of many changes. Where applicable please try to …

Update the Uplink schema

---

.changesets/docs_cache_control_rhai_example.md
Cargo.lock
Cargo.toml
apollo-router/src/services/subgraph.rs
apollo-router/src/services/supergraph.rs
apollo-router/tests/fixtures/request_response_test.rhai
examples/cache-control/rhai/Cargo.toml
examples/cache-control/rhai/README.md
examples/cache-control/rhai/router.yaml
examples/cache-control/rhai/src/cache_control.rhai
examples/cache-control/rhai/src/main.rs

uses cache-control headers from subgraphs to determine an overally cache-control policy
partially addresses #326
**Checklist**
- [] Performance impact assessed and acceptable
- [] Unit Tests
**Exceptions**
**Notes**
[^3]. Tick whichever testing boxes are applicable. If you …

cache-control example

---

.changesets/maint_garypen_cleanup_output.md
apollo-router/src/plugins/telemetry/apollo_exporter.rs

It breaks json format for logs and is redundant.
**Checklist**
~- Tests added and passing[^3]~
~- [ ] Unit Tests~
~- [ ] Integration Tests~
~- [ ] Manual Tests~
**Exceptions**
**Notes**
- please …

remove redundant println()

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/spec/query.rs
apollo-router/tests/integration_tests.rs
examples/supergraph-sdl/rust/Cargo.toml

The parser now does less recursion so our recursion limit test needs a change. Fixes CI failure with updated dependencies like https://app.circleci.com/pipelines/github/apollographql/router/11672/workflows/a57c04c5-6849-40d3-b40a-437a543e586d/jobs/76934?invite=true#step-117-1189
Cherry-picked from a larger branch.
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part …

Update to apollo-parser@0.5.1 and apollo-compiler@0.8.0

---

.changesets/fix_geal_cache_storage_mutex.md
apollo-router/src/cache/mod.rs
apollo-router/src/cache/storage.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/router_service.rs
apollo-router/src/services/supergraph_service.rs

This reverts commit c0218a3b9050898c944437271cc663a1859b672b.

Revert "use a parking-lot mutex in cache storage (#2887)"

---

Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh

This cuts an `1.16.0-alpha.0` of the #2995 PR

pre-release prep: v1.16.0-alpha.0

---

apollo-router/Cargo.toml

The change is specifically targetting linux, not unix like OSs.
**Checklist**
**Exceptions**
**Notes** …

Cargo configuration should match main.rs

---

apollo-router/src/executable.rs
docs/source/quickstart.mdx

Ooh spooky I'm technically modifying the router source this time 👻

chore: Switch to "GraphOS" in Router help text

---

apollo-router/src/spec/field_type.rs
apollo-router/src/spec/fragments.rs
apollo-router/src/spec/query.rs
apollo-router/src/spec/query/tests.rs
apollo-router/src/spec/schema.rs
apollo-router/src/spec/selection.rs

This aims not to change any observable behavior.
**Checklist**
**Exceptions**
I’m counting on existing tests to make sure that existing behavior is preserved.
**Notes**
- please document the manual testing …

Replace some data structures with apollo-compiler equivalents

---

apollo-router/src/services/layers/apq.rs

Refactors `PersistedQuery` to have an associated function `maybe_from_request` that takes in a `&SupergraphRequest` and returns an `Option<PersistedQuery>`. Additionally adds a `decode_hash` that takes `&self` and returns an `Option<(String, Vec<u8>)>`. These methods are then used to construct the information needed in `apq_request` and can be re-used in other parts of the codebase as needed. This is not a user facing change.

chore: refactor `PersistedQuery` in the `apq` plugin

---

.github/workflows/update_uplink_schema.yml
apollo-router/src/uplink/mod.rs

This uses a combination of Rover and https://github.com/peter-evans/create-pull-request to create a pull request when a schema's introspection has changed.

Update Uplink schema via GitHub Actions and remove Rust assert test

---

.changesets/feat_geal_jwt_test_multiple_matching_keys.md
.changesets/fix_geal_jwt_test_multiple_matching_keys.md

This updates the changelog for https://github.com/apollographql/router/pull/3031 to be a `fix` and updates the changelog text.

changelog edits: https://github.com/apollographql/router/pull/3031

---

CHANGELOG.md
docs/source/federation-version-support.mdx

chore: @abernix's changelog edits prior to 1.19.1 release

---

Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh

This is an alpha release for 1.22.0

prep release: v1.22.0-alpha.0

---

.changesets/fix_simon_subselections_are_selections.md
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/plan.rs
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-10.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-11.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-12.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-13.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-14.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-15.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-16.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-17.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-18.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-2.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-3.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-4.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-5.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-6.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-7.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-8.snap
apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__impl-9.snap
apollo-router/src/services/snapshots/apollo_router__services__supergraph_service__tests__filter_nullified_deferred_responses-2.snap
apollo-router/src/services/supergraph_service.rs
apollo-router/src/spec/fragments.rs
apollo-router/src/spec/mod.rs
apollo-router/src/spec/query.rs
apollo-router/src/spec/query/subselections.rs
apollo-router/src/spec/query/tests.rs
apollo-router/src/spec/selection.rs

Clean-up following https://github.com/apollographql/router/pull/3298/
Fixes https://github.com/apollographql/router/issues/3263
**Checklist**
**Exceptions**
- We expect no change in behavior, so counting on existing tests for that behavior
**Notes**
[^3]. Tick whichever …

Prepare deferred subselections without reparsing

---

apollo-router/src/spec/query/snapshots/apollo_router__spec__query__tests__impl-2.snap
apollo-router/src/spec/query/snapshots/apollo_router__spec__query__tests__impl.snap

missing snapshots

---

.changesets/maint_geal_refactor_router_service.md
apollo-router/src/services/router_service.rs

No semantic changes here, this moves code around for easier readability and maintainability
**Checklist**
**Exceptions**
**Notes** …

Refactor router service

---

.changesets/maint_geal_refactor_execution_service.md
apollo-router/src/services/execution_service.rs

**Checklist**
**Exceptions**
**Notes** …

refactor ExecutionService

---

Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh

prep release: v1.23.0-alpha.0

---

docs/source/configuration/authn-jwt.mdx
docs/source/configuration/operation-limits.mdx
docs/source/containerization/docker.mdx
docs/source/customizations/native.mdx
docs/source/executing-operations/defer-support.mdx
docs/source/quickstart.mdx

No content updates here, just link repair

Fix miscellaneous broken links in router docs

---

Cargo.lock
apollo-router/Cargo.toml
xtask/Cargo.lock
xtask/Cargo.toml

**Checklist**
**Exceptions**
**Notes**
- please raise a separate issue to automate the test and label it (or ask for it …

remove unused dependencies

---

docs/source/configuration/traffic-shaping.mdx

docs(traffic_shaping): mention default timeout for subgraph request too

---

.changesets/fix_bnjjj_fix_2705.md
apollo-router/src/executable.rs

don't hide --dev when using --help

---

apollo-router/src/state_machine.rs
apollo-router/tests/common.rs
apollo-router/tests/lifecycle_tests.rs

just to see if it looks better.

tweak the logging on the state machine improvements

---

docs/source/configuration/overview.mdx

It makes more clear how to enable experimental.expose_query_plan without seeing the source code.
https://github.com/apollographql/router/blob/0b498117486dc9e17d914b80509dea37c1094d6a/apollo-router/src/plugins/expose_query_plan.rs#L79
**Checklist**
**Exceptions**
**Notes** …

docs: update experimental.expose_query_plan description

---

.changesets/fix_garypen_fix_pdb.md
helm/chart/router/templates/pdb.yaml

Add the required matchLabels: attribute

fix the pdb template

---

docs/source/config.json
docs/source/configuration/persisted-queries.mdx
docs/source/enterprise-features.mdx

This PR duplicates relevant portions of the ["main" Persisted Queries docs](https://github.com/apollographql/docs/pull/496).
**Checklist**
**Exceptions**
**Notes**
- …

Persisted queries docs edits

---

.changesets/docs_geal_plugin_doc_fix.md
docs/source/customizations/native.mdx

Fix #3539
**Checklist**
**Exceptions**
**Notes**
- please raise a separate issue to automate the test and label it (or …

self is immutable in the Plugin trait's methods

---

.changesets/docs_geal_document_request_lifecycle.md
docs/source/customizations/overview.mdx

This PR makes some edits to https://github.com/apollographql/router/pull/3391.
**Checklist**
**Exceptions**
**Notes**
- please document the manual testing (extensively) …

Request lifecycle doc edits

---

.changesets/maint_simon_rust71.md
apollo-router-scaffold/templates/base/Dockerfile
apollo-router/Cargo.toml
apollo-router/README.md
apollo-router/src/configuration/schema.rs
apollo-router/src/plugin/serde.rs
apollo-router/src/router/mod.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/layers/persisted_queries/mod.rs
dockerfiles/diy/dockerfiles/Dockerfile.repo
docs/source/customizations/custom-binary.mdx
rust-toolchain.toml

This includes the fix for https://blog.rust-lang.org/2023/08/03/cve-2023-38497.html
**Checklist**
**Exceptions**
**Notes** …

Upgrade to Rust 1.71.1

---

helm/chart/router/templates/deployment.yaml
helm/chart/router/templates/service.yaml

revert helm change pushed direct to dev

---

apollo-router/src/configuration/metrics.rs

I got some changes merged upstream so now no cloning!
**Checklist**
**Exceptions**
**Notes** …

Remove inaccurate comment about jsonpath_rust needing to clone

---

apollo-router/src/plugins/telemetry/mod.rs

**Checklist**
**Exceptions**
**Notes** …

new algorithm for cache hits

---

.changesets/feat_geal_authorization_directives.md
.changesets/maint_geal_authorization_analytics.md
docs/source/config.json
docs/source/configuration/authorization.mdx
docs/source/enterprise-features.mdx

This reverts commit c4f1a4d323e12901c74db0c1d836d31e5e77a8ca.
**Checklist**
**Exceptions**
**Notes**
- please raise a …

Reintroduce authorization documentation

---

.changesets/fix_bryn_fix_metrics_typing.md
apollo-router/src/configuration/metrics.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@apq.router.yaml.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@authorization.router.yaml.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@authorization_directives.router.yaml.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@coprocessor.router.yaml.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@entities.router.yaml.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@limits.router.yaml.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@persisted_queries.router.yaml.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@subscriptions.router.yaml.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@telemetry.router.yaml.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@traffic_shaping.router.yaml.snap
apollo-router/src/plugins/telemetry/metrics/layer.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/query_planner/bridge_query_planner.rs

Reverts apollographql/router#3701

Revert "Fix metrics attribute types"

---

docs/source/config.json

**Checklist**
**Exceptions**
**Notes** …

docs: graduate Authorization to preview from experimental

---

CHANGELOG.md

Same as https://github.com/apollographql/router/commit/b17018be5c0552b9de57f767189f9a02dd2a7799 but for the other place, before I copied and pasted the changelog that I didn't fix.

Fix changelog formatting error on `main`

---

.changesets/maint_geal_metadata_cleanup.md
Cargo.toml
deny.toml

* remove unused patch entries in Cargo.toml (referring to a 1 year old commit in opentelemetry)
* remove exemptions for the chrono security advisories (they are fixed now)
**Checklist**
**Exceptions**
**Notes** …

metadata cleanup

---

.changesets/fix_geal_fix_authenticated_reporting.md
apollo-router/src/plugins/authorization/mod.rs

This is not a security issue, it only affects usage reporting for the `@authenticated` directive
**Checklist**
**Exceptions**
**Notes**
- please document the manual testing (extensively) in …

fix authenticated directive reporting

---

docs/source/configuration/authorization.mdx

Raising the minimal version to include the fix from https://github.com/apollographql/router/commit/a55d8a491227cdf518a3e1e6a781d75cff100cf4
**Checklist**
**Exceptions**
**Notes**
- please …

Set the minimal version for Authorization to 1.29.1

---

.changesets/maint_nicolas_otlp_filter.md
apollo-router/src/plugins/telemetry/metrics/filter.rs

Fixes #3760
**Checklist**
**Exceptions**
**Notes**
- please raise a separate issue to automate the …

feat(apollo-router): add support for GraphOS Cloud metrics

---

apollo-router/feature_discussions.json
apollo-router/tests/snapshots/lifecycle_tests__cli_config_preview.snap

**Checklist**
**Exceptions**
**Notes** …

reference a github discussion about GraphOS Authorization

---

docs/source/configuration/authorization.mdx

This corrects authorization directives default configuration.
**Checklist**
**Exceptions**
**Notes** …

docs: auth directives off by default

---

.changesets/feat_garypen_2278_rhai_router_service.md
apollo-router/src/plugins/rhai/engine.rs

we need to make the API more consistent
**Checklist**
**Exceptions**
**Notes** …

remove the rhai JSON functions

---

.changesets/breaking_dev.md
xtask/src/commands/changeset/mod.rs

Fix a regression introduced in #3814

chore(xtask): fix changeset create with the new pr template

---

.changesets/feat_geal_plan_cache_warmup_doc.md
docs/source/configuration/in-memory-caching.mdx

Fix #3704
**Checklist**
**Exceptions**
**Notes**
- please raise a separate issue to automate the test and label it (or …

document the query plan cache warm up

---

apollo-router/src/layers/async_checkpoint.rs

Followup to #3819, this removes a panic which would trigger if a user misuses OneShotAsyncCheckpoint.

Don't panic in OneShotAsyncCheckpoint.

---

docs/source/configuration/metrics.mdx

Copyedit `co-processor`
---
**Checklist**
**Exceptions**
**Notes**

Copyedit coprocessor typo

---

docs/source/configuration/persisted-queries.mdx

This PR:
- Calls out the version for GA
- Cleans up terminology ("preregistered" -> "registered", etc.)
---
**Checklist**
**Exceptions**
**Notes** …

docs: add GA version callout to PQ docs

---

apollo-router/src/axum_factory/listeners.rs

Implement the same logic as for TLS and TCP.
I manually confirmed (with: `socat - UNIX-CONNECT:/tmp/router.sock`) that the same problem existed without this fix for unix domain sockets. The problem goes away with the fix.

add support for unix domain sockets idle shutdown

---

.changesets/docs_eh_docs_k8s_deployment.md
docs/shared/coproc-typical-config.mdx
docs/shared/helm-show-router-output.mdx
docs/shared/k8s-manual-config.mdx
docs/shared/router-common-config.mdx
docs/source/config.json
docs/source/configuration/authn-jwt.mdx
docs/source/configuration/distributed-caching.mdx
docs/source/containerization/docker.mdx
docs/source/containerization/kubernetes.mdx
docs/source/containerization/overview.mdx
docs/source/customizations/coprocessor.mdx
docs/source/migrating-from-gateway.mdx

Merge back from main to bring docs changes back to dev.

merge back from main to bring docs changes back onto dev.

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/tests/integration_tests.rs

Bring in some bug fixes, and fix the "without lockfile" CI job:
https://app.circleci.com/pipelines/gh/apollographql/router/16331/workflows/dae8c869-ee82-4d91-ae5e-7fcf10d1edc1/jobs/106348
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing …

Update apollo-parser to 0.6.3

---

.changesets/feat_bryn_coprocessor_has_next.md
docs/source/customizations/coprocessor.mdx

There was a missing changelog for #4016 
Also the docs in general needed updating for Supergraph support.
---
**Checklist**
**Exceptions**
**Notes** …

Changelog and supergraph coprocessor docs

---

Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
scripts/install.sh

Prepare release v1.34.0-alpha.0

prep release: v1.34.0-alpha.0

---

apollo-router/src/plugins/telemetry/proto/reports.proto
apollo-router/tests/snapshots/apollo_reports__batch_send_header.snap
apollo-router/tests/snapshots/apollo_reports__batch_trace_id.snap
apollo-router/tests/snapshots/apollo_reports__client_name.snap
apollo-router/tests/snapshots/apollo_reports__client_version.snap
apollo-router/tests/snapshots/apollo_reports__condition_else.snap
apollo-router/tests/snapshots/apollo_reports__condition_if.snap
apollo-router/tests/snapshots/apollo_reports__non_defer.snap
apollo-router/tests/snapshots/apollo_reports__send_header.snap
apollo-router/tests/snapshots/apollo_reports__send_variable_value.snap
apollo-router/tests/snapshots/apollo_reports__stats.snap
apollo-router/tests/snapshots/apollo_reports__trace_id.snap

Using:
curl -f https://usage-reporting.api.apollographql.com/proto/reports.proto >
apollo-router/src/plugins/telemetry/proto/reports.proto

Update `reports.proto` to latest version

---

docs/source/configuration/tracing.mdx

Fix a typo found on the documentation
---
**Checklist**
**Exceptions**
**Notes**

Fix typo on documentation

---

apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/authorization/mod.rs
apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__tests__authenticated_directive_reject_unauthorized.snap
apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__tests__scopes_directive_reject_unauthorized.snap
apollo-router/src/plugins/authorization/tests.rs
apollo-router/src/query_planner/bridge_query_planner.rs
docs/source/configuration/authorization.mdx

Fix #4078
This will refuse any query that would have some parts filtered by authorization directives
---
**Checklist**
**Exceptions**
**Notes** …

Authorization: option to reject unauthorized queries

---

dev-docs/decision-records/unstable-plugins.md

Adds a decision record for adding an unstable plugin API.
Aim to ratify by 2023-10-30

Add DR for unstable plugin API

---

dev-docs/decision-records/extend-plugin-init.md

Adds a DR for extending plugin init:
Target ratification date: 2023-30-10

Add DR to extend plugin init

---

.changesets/fix_garypen_more_channels.md
apollo-router/src/notification.rs

fixes: #4117
---
**Checklist**
**Exceptions**
**Notes**

Convert notification from futures channels to tokio channels

---

Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh

prep release: v1.34.0-alpha.1

---

.changesets/fix_simon_compiler_1_0.md

---
**Checklist**
**Exceptions**
**Notes**

Changelog for PR #4038: Port to apollo-compiler 1.0 beta

---

apollo-router/src/services/router_service.rs
apollo-router/src/services/snapshots/apollo_router__services__router_service__tests__escaped_quotes_in_string_literal.snap

Fixes https://github.com/apollographql/router/issues/3541
---
**Checklist**
**Exceptions**
**Notes**

Add non-regression test for escaped quotes in string literals

---

apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/telemetry/span_factory.rs

---
**Checklist**
**Exceptions**
**Notes**

Add span factory to allow us to switch between legacy and new mode.

---

apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/telemetry/config.rs
apollo-router/src/plugins/telemetry/config_new/logging.rs
apollo-router/src/plugins/telemetry/fmt_layer.rs
apollo-router/src/plugins/telemetry/formatters/json.rs
apollo-router/src/plugins/telemetry/formatters/text.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/telemetry/reload.rs
docs/source/configuration/logging.mdx

---
**Checklist**
**Exceptions**
**Notes**

Add config for new logging

---

.changesets/feat_geal_redis_ttl.md
apollo-router/src/cache/mod.rs
apollo-router/src/cache/redis.rs
apollo-router/src/cache/storage.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/introspection.rs
apollo-router/src/plugins/traffic_shaping/mod.rs
docs/source/configuration/distributed-caching.mdx

Fix #4163
---
**Checklist**
**Exceptions**
**Notes**

support TTL in redis storage

---

CHANGELOG.md

---
**Checklist**
**Exceptions**
**Notes**

copyedit 1.34.0 changelog

---

apollo-router/src/services/execution.rs
apollo-router/src/services/execution/service.rs
apollo-router/src/services/mod.rs
apollo-router/tests/snapshots/tracing_tests__traced_basic_composition.snap
apollo-router/tests/snapshots/tracing_tests__traced_basic_request.snap

no functional change
---
**Checklist**
**Exceptions**
**Notes**

move the execution service to a subfolder

---

apollo-router/src/plugins/cache/entity.rs
apollo-router/src/plugins/rhai/engine.rs

Fix #4190
---
**Checklist**
**Exceptions**
**Notes**

Entity cache: influence the cache key through a context entry

---

Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
helm/chart/router/templates/configmap.yaml
helm/chart/router/templates/hpa.yaml
helm/chart/router/templates/ingress.yaml
helm/chart/router/templates/pdb.yaml
helm/chart/router/templates/secret.yaml
helm/chart/router/templates/service.yaml
helm/chart/router/templates/serviceaccount.yaml
helm/chart/router/templates/serviceentry.yaml
helm/chart/router/templates/servicemonitor.yaml
helm/chart/router/templates/supergraph-cm.yaml
helm/chart/router/templates/tests/test-connection.yaml
helm/chart/router/templates/virtualservice.yaml
licenses.html
scripts/install.sh

prep release: v1.34.0-alpha.1
Will close once the release is out

prep release: v1.34.0-alpha.1 (#4132)

---

apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/telemetry/config_new/logging.rs
apollo-router/src/plugins/telemetry/fmt_layer.rs
apollo-router/src/plugins/telemetry/formatters/json.rs
apollo-router/src/plugins/telemetry/formatters/text.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/plugins/telemetry/reload.rs
apollo-router/src/plugins/telemetry/snapshots/apollo_router__plugins__telemetry__fmt_layer__tests__json_logging_attributes.snap
apollo-router/src/plugins/telemetry/snapshots/apollo_router__plugins__telemetry__fmt_layer__tests__json_logging_attributes_nested_spans.snap
apollo-router/src/plugins/telemetry/snapshots/apollo_router__plugins__telemetry__fmt_layer__tests__json_logging_without_span_list.snap
apollo-router/src/plugins/telemetry/snapshots/apollo_router__plugins__telemetry__fmt_layer__tests__text_logging_attributes.snap
apollo-router/src/plugins/telemetry/snapshots/apollo_router__plugins__telemetry__fmt_layer__tests__text_logging_attributes_nested_spans.snap
apollo-router/src/plugins/telemetry/snapshots/apollo_router__plugins__telemetry__fmt_layer__tests__text_logging_without_span_list.snap
apollo-router/tests/common.rs
apollo-router/tests/fixtures/jaeger-0.5-sample.router.yaml
apollo-router/tests/fixtures/jaeger-no-sample.router.yaml
apollo-router/tests/fixtures/jaeger.router.yaml
apollo-router/tests/jaeger_test.rs

add tests for the formatting layer

telemetry: add tests for the formatting layer

---

examples/context/rust/README.md
examples/status-code-propagation/rust/README.md
examples/supergraph-sdl/rust/README.md

Introduces fixes for broken mermaid sequenceDiagrams present in some `.md` files in the repo
---
**Checklist**
**Notes**

docs: fix mermaid rendering

---

apollo-router/src/plugins/telemetry/formatters/json.rs
apollo-router/src/plugins/telemetry/formatters/mod.rs
apollo-router/src/plugins/telemetry/formatters/text.rs

followup https://github.com/apollographql/router/pull/4254#pullrequestreview-1745988631

fix wrong function name

---

docs/source/configuration/authorization.mdx

---
**Checklist**
**Exceptions**
**Notes**

policy docs update

---

apollo-router/src/plugins/telemetry/mod.rs

follow up to #4148 to fix otel sdk changes.

fix changes in otel

---

Cargo.lock

For some reasons it was not covered by renovate
---
**Checklist**
**Exceptions**
**Notes**

chore(deps) update (transitive) rust crate ahash to v0.8.6

---

docs/source/customizations/rhai.mdx

As of 1.30.0, Rhai can now access RouterService

[docs-dev] Update rhai docs to include RouterService

---

docs/source/configuration/overview.mdx

---
**Checklist**
**Exceptions**
**Notes**

docs: add tip to configure text editor with router config schema

---

.changesets/feat_bryn_offline_license.md
apollo-router/src/executable.rs

Make the existing unsupported env and CLI args official.
Fixes #4219
---
**Checklist**
**Exceptions**
**Notes** …

Offline license support

---

apollo-router/src/query_planner/fetch.rs

---
**Checklist**
**Exceptions**
**Notes**

fix panic in subquery hash

---

apollo-router/src/uplink/license_enforcement.rs

Offline was missing.
---
**Checklist**
**Exceptions**
**Notes**

Add `offline` to the valid list of JWKS aud for validation

---

apollo-router/src/spec/query.rs

Further applies to #4348
---
**Checklist**
**Exceptions**
**Notes**

ignore known_type and use __typename or the inferred type

---

.changesets/exp_geal_router_bridge_options_limit.md
Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/introspection.rs
apollo-router/src/query_planner/bridge_query_planner.rs

---
**Checklist**
**Exceptions**
**Notes**

Expose query plan and paths limits

---

.gitleaks.toml
apollo-router/src/uplink/license_enforcement.rs

This PR creates updates the secret allowlisting configuration already in this repo to allowlist more detected "issues" the detected values are not actually secrets - they are benign positive detections. Additionally, this PR introduces some config to help prevent this type of benign-positive detection in the future by allowlisting `testdata` directories for a number of detection signatures and adding line comments to some tests so that future commits that interact with those lines of code do not create new detections
---
**Checklist**
**Exceptions**
None that I'm aware of? 
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other …

Allowlist benign positive secret detections

---

apollo-router/src/plugins/record_replay/record.rs
apollo-router/src/plugins/record_replay/replay.rs

1. avoid panic with invalid operations
2. emit diff for subgraph variables
---
**Checklist**
**Exceptions**
**Notes** …

fix: record/replay improvements

---

.changesets/fix_bryn_jwks_logs.md
apollo-router/src/plugins/authentication/jwks.rs

Adds a span so that we can correlate log messages, adds debug output for the content of the file. 
Fixes #4448
---
**Checklist**
**Exceptions**
**Notes** …

Improve logging for JWKS download failures.

---

docs/source/executing-operations/subscription-support.mdx

docs(subscription): update implementations of subscription callback protocol

---

docs/source/customizations/coprocessor.mdx

Fix coprocessor sample payload typos, found by @devfreddy-apollo

docs: fix coprocessor sample payload typos

---

.changesets/fix_geal_update_router_bridge2.md
Cargo.lock
apollo-router/Cargo.toml

It contains the following fixes:
* https://github.com/apollographql/federation/pull/2898
* https://github.com/apollographql/federation/pull/2905
---
**Checklist**
**Exceptions**
**Notes** …

update router-bridge to v0.5.14+v2.6.3

---

apollo-router/src/spec/selection.rs

Fix #4214
these debug assertions were testing assumptions that turned out wrong, so we are removing them
---
**Checklist**
**Exceptions**
**Notes** …

remove invalid type assertions in debug

---

apollo-router/src/logging/mod.rs
apollo-router/src/router/event/schema.rs

---
**Checklist**
**Exceptions**
**Notes**

test: change test log subscriber to capture trace/debug

---

docs/source/configuration/telemetry/exporters/tracing/otlp.mdx

Fixes #4507 
---
**Checklist**
**Exceptions**
**Notes**

Fix NewRelic tracing link

---

apollo-router/src/notification.rs

**Checklist**
**Exceptions**
**Notes**

small improvement about memory allocation for subscriptions

---

apollo-router/src/axum_factory/axum_http_server_factory.rs
apollo-router/src/axum_factory/mod.rs
apollo-router/src/lib.rs

Although part of the public API, this is not intended for use by end users, and may change at any time.
---
**Checklist**
**Exceptions**
**Notes** …

Add endpoint callback

---

docs/source/executing-operations/requests.mdx

Add link to the APQ docs and protocol as they use a different HTTP body format

[docs] Update request format docs

---

docs/source/containerization/kubernetes.mdx
docs/source/customizations/rhai-api.mdx
docs/source/enterprise-features.mdx

---
**Checklist**
**Exceptions**
**Notes**

docs: fix links

---

.circleci/config.yml
CHANGELOG.md
Cargo.lock
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.toml
apollo-router-scaffold/templates/base/xtask/Cargo.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh
xtask/src/commands/dist.rs
xtask/src/commands/package/mod.rs

> **Note**
> **This particular PR must be true-merged to `main`.**
* This PR is only ready to review when it is marked as "Ready for Review".  It represents the merge to the `main` branch of an upcoming release (version number in the title).
* We may cut any number of alpha and release candidate (RC) versions off this branch prior to formalizing it.
- Does this PR target the right branch? (usually, `main`)
- Are the appropriate **version bumps** and **release note …

release: v1.39.1

---

docs/source/configuration/telemetry/instrumentation/spans.mdx

Granular customization of spans is an enterprise feature. However the docs specifically call out by selector. This should have been all granular customization of spans.
---
**Checklist**
**Exceptions**
**Notes** …

Clarify that any customization of attributes for spans is an enterprise feature

---

.changesets/feat_lrlna_remove_header_in_rhai.md
apollo-router/src/plugins/rhai/engine.rs
apollo-router/src/plugins/rhai/tests.rs
apollo-router/tests/fixtures/remove_header.rhai

This allows users to remove headers in a Rhai script with a `.remove`.
---
**Checklist**
**Exceptions**
**Notes** …

feat(rhai): add a .remove for header maps in rhai

---

.changesets/fix_geal_subgraph_streaming_compression.md
apollo-router/src/axum_factory/compression/mod.rs
apollo-router/src/axum_factory/mod.rs
apollo-router/src/error.rs
apollo-router/src/services/http/service.rs
apollo-router/src/services/http/tests.rs

Fix #4648
---
**Checklist**
**Exceptions**
**Notes**

Implement streaming compression for subgraph requests

---

apollo-router/src/plugins/telemetry/apollo_exporter.rs
apollo-router/src/plugins/telemetry/proto/reports.proto

Update the proto to the latest version. The change was only to internal fields.
---
**Checklist**
**Notes**

Update reports proto

---

docs/source/configuration/authorization.mdx

---
**Checklist**
**Exceptions**
**Notes**

document the interaction of subscriptions with policy authorization

---

docs/source/configuration/authn-jwt.mdx

Fixes a table issue introduced in https://github.com/apollographql/router/pull/4711

docs: fix authn-jwt table

---

docs/source/errors.mdx

docs: errors link

---

apollo-router/tests/common.rs
apollo-router/tests/fixtures/batching/all_enabled.router.yaml
apollo-router/tests/fixtures/batching/block_request.rhai
apollo-router/tests/fixtures/batching/coprocessor.router.yaml
apollo-router/tests/fixtures/batching/rhai_script.router.yaml
apollo-router/tests/fixtures/batching/schema.graphql
apollo-router/tests/fixtures/batching/short_timeouts.router.yaml
apollo-router/tests/integration/batching.rs
apollo-router/tests/integration/mod.rs

This commit adds integration tests for testing subgraph batching from the router.
---
**Checklist**
**Exceptions**
**Notes** …

Add integration tests for batching

---

apollo-router/tests/zipkin_test.rs

Clippy is complaining
---
**Checklist**
**Exceptions**
**Notes**

Fix failing CI due to clippy check

---

apollo-router/src/plugins/authentication/jwks.rs

---
**Checklist**
**Exceptions**
**Notes**

remove unneeded Content-Type from the JWKS download request

---

.changesets/feat_geal_expose_operation_signature.md
apollo-router/src/query_planner/caching_query_planner.rs

Fix #4558
---
**Checklist**
**Exceptions**
**Notes**

expose the operation signature in the context

---

apollo-router/src/plugins/cache/entity.rs
apollo-router/src/plugins/record_replay/record.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/bridge_query_planner_pool.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/services/layers/allow_only_http_post_mutations.rs
apollo-router/src/services/layers/content_negotiation.rs
apollo-router/src/services/supergraph/service.rs

---
**Checklist**
**Exceptions**
**Notes**

clean up some error handling

---

docs/source/config.json

Now that  custom instruments have been added we need to show the docs.
---
**Checklist**
**Exceptions**
**Notes** …

Enable instruments documentation

---

apollo-router/Cargo.toml

otherwise the test_updated CI build will fail
---
**Checklist**
**Exceptions**
**Notes**

fix the rhai version to 1.17 until we fix the test failures in 1.18

---

RELEASE_CHECKLIST.md

Adding missing branch push to existing command.

Update RELEASE_CHECKLIST.md pre-release step.

---

.changesets/exp_carton_ginger_magnet_beacon.md
apollo-router/examples/router.yaml
apollo-router/src/configuration/metrics.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@query_planner_parallelism_auto.router.yaml.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@query_planner_parallelism_static.router.yaml.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/configuration/testdata/metrics/query_planner_parallelism_auto.router.yaml
apollo-router/src/configuration/testdata/metrics/query_planner_parallelism_static.router.yaml
apollo-router/src/query_planner/bridge_query_planner_pool.rs
apollo-router/src/router_factory.rs
docs/source/configuration/in-memory-caching.mdx
docs/source/configuration/overview.mdx
docs/source/configuration/telemetry/instrumentation/standard-instruments.mdx

Names have been improved and brought into new style. number of items queued is now a real gauge.
---
**Checklist**
**Exceptions**
**Notes** …

Fixup metrics for query planner

---

.changesets/feat_bnjjj_event_changelog.md
.changesets/feat_quart_thermos_chord_tack.md

Add changelog entry for https://github.com/apollographql/router/pull/4956 and https://github.com/apollographql/router/pull/4987

add 2 changeset for telemetry

---

apollo-federation/src/source_aware/federated_query_graph/builder.rs
apollo-federation/src/source_aware/federated_query_graph/mod.rs
apollo-federation/src/source_aware/federated_query_graph/path_tree.rs
apollo-federation/src/source_aware/fetch_dependency_graph/mod.rs
apollo-federation/src/source_aware/query_plan/mod.rs
apollo-federation/src/sources/connect/mod.rs
apollo-federation/src/sources/connect/models/mod.rs
apollo-federation/src/sources/connect/query_graph.rs
apollo-federation/src/sources/connect/spec/directives.rs
apollo-federation/src/sources/connect/spec/mod.rs
apollo-federation/src/sources/connect/spec/schema.rs
apollo-federation/src/sources/connect/spec/type_and_directive_specifications.rs
apollo-federation/src/sources/graphql/mod.rs
apollo-federation/src/sources/mod.rs

---
**Checklist**
**Exceptions**
**Notes**

cargo xtask lint --fmt

---

apollo-federation/src/sources/connect/mod.rs
apollo-federation/src/sources/connect/models/mod.rs

We can use this for FetchNode labels in query plan diagrams and for traces
---
**Checklist**
**Exceptions**
**Notes** …

add label to ConnectId

---

apollo-federation/src/subgraph/spec.rs

---
**Checklist**
**Exceptions**
**Notes**

test: make sure doctest doesn't try to parse gql as rust

---

apollo-router/src/error.rs
apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
apollo-router/src/plugins/demand_control/mod.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/fetch.rs
apollo-router/src/query_planner/plan.rs
apollo-router/src/query_planner/tests.rs

This situation indicates a query planner bug that shouldn’t happen, but if it does we prefer propagating an error to the client than bringing down the process.
---
**Checklist**
**Exceptions**
**Notes** …

Don’t panic on invalid subgraph operation

---

apollo-federation/src/sources/connect/query_graph.rs
apollo-federation/src/sources/connect/url_path_template.rs

This commit removes all potential panics from the connector graph creation logic.
---
**Checklist**
**Notes**

remove panics from connect graph

---

apollo-federation/src/sources/connect/query_graph.rs

**Checklist**
**Exceptions**
**Notes**

federation: use ConnectID label for test output

---

apollo-federation/src/sources/connect/query_graph.rs

This commit marks top-level connect nodes as being entrypoints into the connect subgraph.
It also fixes an issue in manual construction of mock graphs in tests.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If …

connector: add enter edge

---

apollo-router/src/plugins/demand_control/mod.rs
apollo-router/src/plugins/demand_control/strategy/test.rs

Increments a counter when a request passes through the demand control execution middleware.
---
**Checklist**
**Exceptions**
**Notes** …

Demand control operation metrics

---

docs/source/configuration/telemetry/exporters/metrics/overview.mdx

Clarify resource attribute usage

docs: resource attribute

---

docs/source/federation-version-support.mdx

Ref: https://github.com/apollographql/router/pull/5028

add a warning in router version for 1.45.0

---

apollo-router/src/configuration/tests.rs

Modify test to verify that the generated schema is less than 500k 
Fixes #5133
---
**Checklist**
**Exceptions**
**Notes** …

enforce json schema < 500k

---

RELEASE_CHECKLIST.md
xtask/src/commands/release.rs

Follow up to https://github.com/apollographql/router/pull/5179

Automate bumping the version number of apollo-federation

---

apollo-federation/src/query_plan/query_planner.rs
apollo-federation/src/schema/position.rs
apollo-federation/src/source_aware/federated_query_graph/builder.rs
apollo-federation/src/source_aware/federated_query_graph/mod.rs
apollo-federation/src/source_aware/query_plan/query_planner.rs
apollo-federation/src/sources/connect/federated_query_graph/builder.rs
apollo-federation/src/sources/connect/federated_query_graph/mod.rs
apollo-federation/src/sources/connect/fetch_dependency_graph/mod.rs
apollo-federation/src/sources/connect/mod.rs
apollo-federation/src/sources/graphql/federated_query_graph/builder.rs
apollo-federation/src/sources/graphql/federated_query_graph/mod.rs
apollo-federation/src/sources/graphql/mod.rs
apollo-federation/src/sources/source/federated_query_graph/builder.rs
apollo-federation/src/sources/source/federated_query_graph/mod.rs
apollo-federation/src/sources/source/mod.rs

This PR adds source-agnostic query graph creation logic. For clarity, this is a simplified version of the code, meant to help validate overall architecture changes.

Add source-agnostic query graph creation logic

---

apollo-federation/src/source_aware/federated_query_graph/builder.rs

This PR sets root-operation type nodes in the federated query graph (if present), during source-agnostic query graph creation logic.

Set root operation type nodes in federated query graph

---

apollo-federation/src/source_aware/federated_query_graph/builder.rs

---
**Checklist**
**Exceptions**
**Notes**

typo in builder.rs

---

Cargo.lock
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/src/lib.rs

version 0.14 of cargo-scaffold no longer clones the entire git repository, [it only gets the latest state of the tree](https://github.com/iomentum/cargo-scaffold/pull/54) at the targeted reference.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick …

faster scaffolding tests

---

apollo-router/tests/integration/lifecycle.rs

that test is not flaky, but still takes 15s to do the same operation 3 times in a row
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) …

remove iterations from test_reload_config_with_broken_plugin_recovery

---

apollo-router/src/query_planner/bridge_query_planner.rs

---
**Checklist**
**Exceptions**
**Notes**

faster subselection keys test

---

apollo-router/src/axum_factory/axum_http_server_factory.rs

The tests are marked as flaky in CI, so let's try to improve them.
- Reduce the timeout (nano-seconds rather than micro-seconds)
- Remove the (seemingly) redundant sleep
- Make the test multi-threaded (which I think it should be)
- Add comments to explain what the tests are doing

improve experimental broken pipe logging testing

---

docs/source/customizations/rhai-api.mdx

Fix #5239 
---
**Checklist**
**Exceptions**
**Notes**

fix the rhai base64 alphabet parameter documentation

---

apollo-router/src/plugins/connectors/fetch.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/fetch.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/query_planner/subscription.rs
apollo-router/src/services/fetch.rs
apollo-router/src/services/fetch_service.rs
apollo-router/src/services/mod.rs

Add a passthrough fetch service.

FetchService

---

apollo-router/src/plugins/telemetry/metrics/apollo/studio.rs
apollo-router/src/plugins/telemetry/proto/reports.proto
apollo-router/tests/snapshots/apollo_reports__batch_send_header-2.snap
apollo-router/tests/snapshots/apollo_reports__batch_send_header.snap
apollo-router/tests/snapshots/apollo_reports__batch_trace_id-2.snap
apollo-router/tests/snapshots/apollo_reports__batch_trace_id.snap
apollo-router/tests/snapshots/apollo_reports__client_name-2.snap
apollo-router/tests/snapshots/apollo_reports__client_name.snap
apollo-router/tests/snapshots/apollo_reports__client_version-2.snap
apollo-router/tests/snapshots/apollo_reports__client_version.snap
apollo-router/tests/snapshots/apollo_reports__condition_else-2.snap
apollo-router/tests/snapshots/apollo_reports__condition_else.snap
apollo-router/tests/snapshots/apollo_reports__condition_if-2.snap
apollo-router/tests/snapshots/apollo_reports__condition_if.snap
apollo-router/tests/snapshots/apollo_reports__non_defer-2.snap
apollo-router/tests/snapshots/apollo_reports__non_defer.snap
apollo-router/tests/snapshots/apollo_reports__send_header-2.snap
apollo-router/tests/snapshots/apollo_reports__send_header.snap
apollo-router/tests/snapshots/apollo_reports__send_variable_value-2.snap
apollo-router/tests/snapshots/apollo_reports__send_variable_value.snap
apollo-router/tests/snapshots/apollo_reports__stats.snap
apollo-router/tests/snapshots/apollo_reports__stats_mocked.snap
apollo-router/tests/snapshots/apollo_reports__trace_id-2.snap
apollo-router/tests/snapshots/apollo_reports__trace_id.snap

This is the same as https://github.com/apollographql/router/pull/5264 but in a local branch to make sure some enterprise related tests pass
Updates proto, snapshots, and code to conform to the new protobuf spec.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: …

chore: Update Apollo Protobuf

---

apollo-federation/src/source_aware/query_plan/display.rs
apollo-federation/src/source_aware/query_plan/mod.rs
apollo-federation/src/sources/graphql/mod.rs
apollo-router/src/configuration/mod.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/query_planner/convert_source_aware.rs
apollo-router/src/query_planner/mod.rs

this is nowhere near a final state, but it should set us up to start using the SAQP as soon as it's ready
---
**Checklist**
**Exceptions**
**Notes** …

newnew query planner mode

---

apollo-federation/src/sources/source/federated_query_graph/builder.rs

This PR addresses FED-199. Specifically, it provides an implementation of `FederatedQueryGraphBuilders::process_subgraph_schemas`.

Implemented FederatedQueryGraphBuilders::process_subgraph_schemas

---

.github/CODEOWNERS

Add codeowners for router directories
Add CODEOWNERS file  protection
---
**Checklist**
**Exceptions**
**Notes** …

Add codeowners for router directories

---

.changesets/docs_maria_frontmatter_update.md

Adds changeset for https://github.com/apollographql/router/pull/5164

docs: add frontmatter changeset

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/plugins/rhai/tests.rs
apollo-router/tests/integration/rhai.rs

Fix updated circle ci test suite

fix(test): upgrade the tracing-test crate

---

apollo-router/tests/samples/README.md
apollo-router/tests/samples/enterprise/query-planning-redis/README.md
apollo-router/tests/samples/enterprise/query-planning-redis/configuration.yaml
apollo-router/tests/samples/enterprise/query-planning-redis/plan.json
apollo-router/tests/samples/enterprise/query-planning-redis/supergraph.graphql
apollo-router/tests/samples_tests.rs

This makes sure that if we do not set up the key and graph ref locally, then tests will not fail. They will still be checked in CI though
---
**Checklist**
**Exceptions**
**Notes** …

Support enterprise features in samples testing

---

apollo-federation/src/schema/type_and_directive_specification.rs

am i reading this right?
---
**Checklist**
**Exceptions**
**Notes**

typo in ensure_expected_type_kind

---

.changesets/fix_fix_content_type_error.md
apollo-router/src/services/subgraph_service.rs

Fixes #5359
---
**Checklist**
**Exceptions**
**Notes**

improvement: error message for invalid 'content-type' in subgraph response

---

.github/CODEOWNERS

Adding other members to codeowners of `apollo-federation`.

add @lrlna @TylerBloom @duckki to codeowners of `apollo-federation`

---

apollo-router/src/plugins/cache/metrics.rs

---
**Checklist**
**Exceptions**
**Notes**

Entity cache: remove debug prints in metrics

---

apollo-router/src/uplink/license_enforcement.rs
apollo-router/src/uplink/testdata/schema_enforcement_connectors.graphql

Add license check for connectors

---

apollo-router/src/plugins/connectors/http_json_transport.rs
apollo-router/src/services/connector_service.rs

---
**Checklist**
**Exceptions**
**Notes**

fix variables/value in http transport make_request

---

apollo-router/src/plugins/connectors/handle_responses.rs
apollo-router/src/plugins/connectors/make_requests.rs
apollo-router/src/plugins/connectors/mod.rs
apollo-router/src/plugins/connectors/steelthread.graphql
apollo-router/src/plugins/connectors/tests.rs
apollo-router/src/services/connect.rs
apollo-router/src/services/connector_service.rs
apollo-router/src/services/fetch_service.rs

instead of subgraph request and response
---
**Checklist**
**Exceptions**
**Notes**

use connect::Request/Response

---

docs/source/customizations/rhai-api.mdx

Fixes an incorrect code snippet

docs: update rhai timing execution example

---

apollo-router/src/protocols/websocket.rs
apollo-router/src/services/subgraph_service.rs

Send both sub protocol and websocket termination message. Close it faster when the subscription is closed from the client side.
Also websocket error coming from the subgraph will now be propagated properly.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick …

close the ws connection faster and propagate error from subgraph when using ws

---

apollo-router/tests/integration/telemetry/logging.rs

---
**Checklist**
**Exceptions**
**Notes**

check the license before running the events integration tests

---

.changesets/docs_feature_dynatraceotel.md
docs/source/config.json
docs/source/configuration/telemetry/exporters/metrics/dynatrace.mdx
docs/source/configuration/telemetry/exporters/tracing/dynatrace.mdx

Add telemetry docs pages for Dynatrace
---
**Checklist**
**Exceptions**
**Notes**

Add telemetry docs pages for Dynatrace

---

apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/query_planner/execution.rs
apollo-router/src/query_planner/tests.rs
apollo-router/src/services/execution.rs
apollo-router/src/services/execution/service.rs
apollo-router/src/services/query_planner.rs
apollo-router/src/services/supergraph/service.rs

Prune more obsolete connectors code
---
**Checklist**
**Exceptions**
**Notes**

More code pruning

---

apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
apollo-router/src/plugins/file_uploads/rearrange_query_plan.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/dual_query_planner.rs
apollo-router/src/query_planner/execution.rs
apollo-router/src/query_planner/fetch.rs
apollo-router/src/query_planner/plan.rs
apollo-router/src/query_planner/tests.rs
apollo-router/src/services/execution.rs
apollo-router/tests/type_conditions.rs

Remove unnecessary changes between the dev and connectors branches. This includes insignificant formatting or comment changes.
---
**Checklist**
**Exceptions**
**Notes** …

Remove unnecessary diffs

---

apollo-router/src/plugins/connectors/handle_responses.rs
apollo-router/src/plugins/connectors/make_requests.rs
apollo-router/src/services/connect.rs
apollo-router/src/services/fetch_service.rs

---
**Checklist**
**Exceptions**
**Notes**

use already-parsed operation in make_requests

---

apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
apollo-router/src/query_planner/bridge_query_planner.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/query_planner/fetch.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/query_planner/subgraph_context.rs
apollo-router/src/services/supergraph/tests.rs
apollo-router/tests/type_conditions.rs

---
**Checklist**
**Exceptions**
**Notes**
[CNN-193]: …

revert files with unnecessary changes

---

apollo-federation/src/sources/connect/expand/mod.rs
apollo-federation/src/sources/connect/expand/tests/mod.rs
apollo-router/src/plugins/connectors/mod.rs
apollo-router/src/plugins/connectors/query_plans.rs
apollo-router/src/plugins/expose_query_plan.rs
apollo-router/src/services/connector_service.rs
apollo-router/src/services/supergraph/service.rs
apollo-router/src/spec/schema.rs

---
**Checklist**
**Exceptions**
**Notes**

expose query plan

---

apollo-federation/src/sources/connect/spec/directives.rs
apollo-federation/src/sources/connect/spec/mod.rs
apollo-federation/src/sources/connect/spec/type_and_directive_specifications.rs

to avoid issues with invalid schemas during authoring — the expansion code for satisfiability happens in composition/on edit
---
**Checklist**
**Exceptions**
**Notes** …

remove panics in connect/spec

---

apollo-router/src/uplink/license_enforcement.rs
apollo-router/src/uplink/testdata/schema_enforcement_connectors.graphql

---
**Checklist**
**Exceptions**
**Notes**

connectors license enforcement with join__directive serialization

---

apollo-federation/src/link/federation_spec_definition.rs
apollo-federation/src/link/join_spec_definition.rs
apollo-federation/src/merge.rs
apollo-federation/src/query_graph/extract_subgraphs_from_supergraph.rs
apollo-federation/src/snapshots/apollo_federation__merge__tests__steel_thread.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_supergraph.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_types_from_different_subgraphs.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_with_descriptions.snap
apollo-federation/tests/snapshots/main__composition_tests__compose_removes_federation_directives.snap
apollo-federation/tests/snapshots/main__extract_subgraphs__can_extract_subgraph.snap

---
**Checklist**
**Exceptions**
**Notes**

add basic support for overrideLabel in extract_subgraphs_from_supergraph

---

apollo-federation/src/merge.rs
apollo-federation/src/snapshots/apollo_federation__merge__tests__basic.snap
apollo-federation/src/sources/connect/expand/merge/basic_1.graphql
apollo-federation/src/sources/connect/expand/merge/basic_2.graphql
apollo-federation/tests/snapshots/main__composition_tests__can_compose_supergraph-2.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_supergraph.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_types_from_different_subgraphs-2.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_types_from_different_subgraphs.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_with_descriptions-2.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_with_descriptions.snap
apollo-federation/tests/snapshots/main__composition_tests__compose_removes_federation_directives-2.snap
apollo-federation/tests/snapshots/main__composition_tests__compose_removes_federation_directives.snap

---
**Checklist**
**Exceptions**
**Notes**

include custom scalars in merge_subgraphs

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/plugins/connectors/handle_responses.rs
apollo-router/src/plugins/connectors/http_json_transport.rs
apollo-router/src/plugins/connectors/plugin.rs
apollo-router/src/query_planner/execution.rs
apollo-router/src/services/connector_service.rs

also fixes a url double-encoding issue
---
**Checklist**
**Exceptions**
**Notes**

allow debugging invalid responses

---

apollo-federation/src/sources/connect/mod.rs
apollo-federation/src/sources/connect/models/mod.rs

Needed in `apollo-composition`

Expose validation severity for consumers

---

apollo-federation/src/sources/connect/expand/carryover.rs
apollo-federation/src/sources/connect/expand/snapshots/apollo_federation__sources__connect__expand__carryover__tests__carryover.snap
apollo-federation/src/sources/connect/expand/tests/mod.rs
apollo-federation/src/sources/connect/expand/tests/schemas/types_used_twice.graphql
apollo-federation/src/sources/connect/expand/tests/schemas/types_used_twice.yaml
apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__types_used_twice__it_expands_supergraph-2.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__types_used_twice__it_expands_supergraph-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__types_used_twice__it_expands_supergraph.snap
apollo-federation/src/sources/connect/expand/visitor.rs
apollo-federation/src/sources/connect/json_selection/visitor.rs
apollo-federation/src/sources/connect/validation/selection.rs
apollo-router/src/plugins/connectors/handle_responses.rs

---
**Checklist**
**Exceptions**
**Notes**

fixes post vacay

---

apollo-federation/src/sources/connect/validation/extended_type.rs
apollo-federation/src/sources/connect/validation/mod.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@missing_connect_on_mutation_field.graphql.snap
apollo-federation/src/sources/connect/validation/test_data/validation/missing_connect_on_mutation_field.graphql

---
**Checklist**
**Exceptions**
**Notes**
[CNN-293]: …

adding validation for mutation fields

---

apollo-federation/src/merge.rs
apollo-federation/src/snapshots/apollo_federation__merge__tests__inaccessible.snap
apollo-federation/src/sources/connect/expand/merge/inaccessible.graphql

---
**Checklist**
**Exceptions**
**Notes**

add inaccessible support to merge_subgraphs

---

Cargo.lock
apollo-federation/src/lib.rs
apollo-federation/src/query_plan/fetch_dependency_graph.rs
apollo-federation/src/query_plan/fetch_dependency_graph_processor.rs
apollo-federation/src/query_plan/query_planner.rs
apollo-federation/src/schema/definitions.rs
apollo-federation/src/schema/mod.rs
apollo-federation/src/schema/position.rs
apollo-federation/src/sources/connect/expand/carryover.rs
apollo-federation/src/sources/connect/expand/mod.rs
apollo-federation/src/sources/connect/mod.rs
apollo-federation/src/sources/connect/validation/mod.rs
apollo-federation/src/subgraph/database.rs
apollo-federation/src/subgraph/mod.rs

---
**Checklist**
**Exceptions**
**Notes**

revert a whole bunch of files

---

apollo-federation/src/merge.rs
apollo-federation/src/snapshots/apollo_federation__merge__tests__inaccessible.snap
apollo-federation/src/sources/connect/expand/merge/inaccessible_2.graphql

---
**Checklist**
**Exceptions**
**Notes**

fix: don't add inaccessible twice

---

apollo-federation/src/sources/connect/json_selection/apply_to.rs
apollo-federation/src/sources/connect/json_selection/selection_set.rs
apollo-router/src/plugins/connectors/testdata/steelthread.graphql
apollo-router/src/plugins/connectors/testdata/steelthread.yaml
apollo-router/src/plugins/connectors/tests.rs

---
**Checklist**
**Exceptions**
**Notes**

fix: include __typename in response selection

---

apollo-federation/src/link/federation_spec_definition.rs
apollo-federation/src/schema/position.rs
apollo-federation/src/sources/connect/mod.rs
apollo-federation/src/sources/connect/models.rs
apollo-router/src/services/connector_service.rs

---
**Checklist**
**Exceptions**
**Notes**

reduce diff with dev

---

apollo-federation/src/merge.rs
apollo-federation/src/snapshots/apollo_federation__merge__tests__steel_thread.snap
apollo-federation/src/sources/connect/expand/merge/connector_Query_users_0.graphql

prior to this change, when a type shows up a second time, we weren't merging arguments into the newly added fields
---
**Checklist**
**Exceptions**
**Notes** …

fix: add field arguments to existing types

---

docs/source/configuration/telemetry/apollo-telemetry.mdx

docs: fix telemetry link

---

apollo-federation/src/sources/connect/expand/mod.rs
apollo-federation/src/sources/connect/expand/visitors/input.rs
apollo-federation/src/sources/connect/expand/visitors/selection.rs

This PR removes all panics in subgraph expansion.
Once #5713 is merged, this history will be simpler.
---
**Checklist**
**Exceptions**
**Notes** …

connectors: fix panics in expansion

---

apollo-federation/src/sources/connect/url_template.rs

The diff looks complicated, but this is just grouping tests by what they're testing to make it easier to find things.

Reorganize URL template tests

---

apollo-federation/src/sources/connect/expand/mod.rs
apollo-federation/src/sources/connect/expand/tests/mod.rs
apollo-federation/src/sources/connect/expand/tests/schemas/circular.graphql
apollo-federation/src/sources/connect/expand/tests/schemas/circular.yaml
apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__circular__it_expands_supergraph-2.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__circular__it_expands_supergraph-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__circular__it_expands_supergraph.snap

---
**Checklist**
**Exceptions**
**Notes**

fix: ensure that fields are added when a type refers to itself

---

apollo-router/src/plugins/connectors/testdata/quickstart.graphql
apollo-router/src/plugins/connectors/testdata/quickstart.yaml
apollo-router/src/plugins/connectors/tests.rs

---
**Checklist**
**Exceptions**
**Notes**

test the quickstart example

---

docs/source/configuration/telemetry/instrumentation/spans.mdx
docs/source/federation-version-support.mdx

- Fix `<PremiumFeature>`
- Fix table formatting

docs: fix component name

---

apollo-router/src/router_factory.rs

having that in a macro was making the function unnecessarily large
---
**Checklist**
**Exceptions**
**Notes**

move plugin creation to a function

---

apollo-router/src/query_planner/dual_query_planner.rs

- With diff description, it's slightly easier to identify where the difference is.
- This is a facility for testing.
---
**Checklist**
[ROUTER-470]: https://apollographql.atlassian.net/browse/ROUTER-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(dual-query-planner): added description to semantic diff failures

---

apollo-router/src/plugins/csrf.rs
apollo-router/src/plugins/headers.rs

small optimizations and fixes noticed while profiling other parts of the router
---
**Checklist**
**Exceptions**
**Notes** …

small optimizations

---

apollo-federation/src/sources/connect/expand/tests/schemas/carryover.graphql
apollo-federation/src/sources/connect/expand/tests/schemas/carryover.yaml
apollo-federation/src/sources/connect/expand/tests/schemas/realistic.graphql
apollo-federation/src/sources/connect/expand/tests/schemas/realistic.yaml
apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__carryover__it_expands_supergraph-2.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__carryover__it_expands_supergraph-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__carryover__it_expands_supergraph.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__realistic__it_expands_supergraph-2.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__realistic__it_expands_supergraph-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__realistic__it_expands_supergraph.snap
apollo-federation/src/sources/connect/expand/visitors/input.rs

---
**Checklist**
**Exceptions**
**Notes**

expand fixes

---

.github/CODEOWNERS

---
**Checklist**
**Exceptions**
**Notes**

add connectors to CODEOWNERS

---

Cargo.lock
apollo-router/Cargo.toml

---
**Checklist**
**Exceptions**
**Notes**

Fix versions for aws-sdk-ssooidc and aws-sdk-sts

---

apollo-federation/src/sources/connect/validation/mod.rs
apollo-federation/src/sources/connect/validation/selection.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@fields_with_arguments.graphql.snap
apollo-federation/src/sources/connect/validation/test_data/validation/fields_with_arguments.graphql

---
**Checklist**
**Exceptions**
**Notes**

disallow fields with arguments if they're not connectors

---

apollo-router/src/plugins/cache/invalidation.rs

---
**Checklist**
**Exceptions**
**Notes**
[ROUTER-682]: …

Fix invalidated entries counter metric

---

apollo-federation/src/sources/connect/validation/extended_type.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@all_fields_selected.graphql.snap
apollo-federation/src/sources/connect/validation/test_data/all_fields_selected.graphql

---
**Checklist**
**Exceptions**
**Notes**

fix: validate each @connect on a field

---

apollo-router/templates/sandbox_index.html

---
**Checklist**
**Exceptions**
**Notes**

enabling connectors debugging via embed

---

.changesets/fix_bryn_datadog_sample_propagation.md

Forgot to git add the changelog for #6005
---
**Checklist**
**Exceptions**
**Notes**

Changelog for 6005

---

Cargo.lock
apollo-router/Cargo.toml

---
**Checklist**
**Exceptions**
**Notes**

remove test-span

---

apollo-router/src/plugins/connectors/plugin.rs

Before
After
---
**Checklist**
**Exceptions**
**Notes**

fix: group mapping errors

---

apollo-router/src/spec/query/snapshots/apollo_router__spec__query__transform__tests__remove_directive-10.snap
apollo-router/src/spec/query/snapshots/apollo_router__spec__query__transform__tests__remove_directive-11.snap
apollo-router/src/spec/query/snapshots/apollo_router__spec__query__transform__tests__remove_directive-12.snap
apollo-router/src/spec/query/snapshots/apollo_router__spec__query__transform__tests__remove_directive-13.snap
apollo-router/src/spec/query/snapshots/apollo_router__spec__query__transform__tests__remove_directive-14.snap
apollo-router/src/spec/query/snapshots/apollo_router__spec__query__transform__tests__remove_directive-7.snap
apollo-router/src/spec/query/snapshots/apollo_router__spec__query__transform__tests__remove_directive-8.snap
apollo-router/src/spec/query/snapshots/apollo_router__spec__query__transform__tests__remove_directive-9.snap
apollo-router/src/spec/query/transform.rs

Follow up for missing cases in #5952
---
**Checklist**
**Exceptions**
**Notes**
[ROUTER-736]: …

Follow up fixes for authorization filtering

---

apollo-federation/src/operation/mod.rs

This PR fixes a bug where unnecessary fragment removal was occurring after rebasing instead of before it (like in JS QP), resulting in cases where the field's parent type wouldn't match the selection set it was being added to.

fix(federation): Unnecessary fragment removal should occur before rebasing

---

apollo-federation/src/query_plan/fetch_dependency_graph.rs

This PR fixes a bug where in `handle_requires()`, when checking whether a grand child can be merged into its grand parent, we mistakenly compare its `merge_at`/`inputs` against the grand parent instead of the parent (like in JS QP). This can result in cases where a grand child is mistakenly hoisted (or not hoisted) onto its grand parent.

fix(federation): Check `merge_at`/`inputs` against parent instead of grand parent during grand child merge check

---

.changesets/config_garypen_promote_otel.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/telemetry/apollo.rs
apollo-router/src/plugins/telemetry/tracing/apollo.rs
apollo-router/tests/apollo_otel_traces.rs
apollo-router/tests/fixtures/apollo_reports.router.yaml
apollo-router/tests/fixtures/apollo_reports_batch.router.yaml
docs/source/configuration/telemetry/instrumentation/standard-instruments.mdx

Update:
- Configuration option
- Documentation
Create:
- Migration
- Migration test
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) …

promote experimental_otlp_tracing_sampler from experimental

---

Cargo.lock
apollo-router/Cargo.toml
apollo-router/src/services/layers/static_page.rs
apollo-router/templates/homepage_index.html
apollo-router/templates/sandbox_index.html
xtask/src/commands/release/process.rs

We aren't exactly doing rocket science here
askama takes about 3-4 seconds to compile on my machine.
Closes #5878
---
**Checklist**
**Exceptions**
We do not appear to have tests for the static pages. I could add some but I think the best option is snapshotting, which is only to prevent accidental changes here 🤷🏻‍♀️  …

Replace askama by manual string replace

---

.changesets/maint_feature_rhaitelemetry.md
apollo-router/src/configuration/metrics.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@rhai.router.yaml.snap
apollo-router/src/configuration/testdata/metrics/rhai.router.yaml

This just merges @andrewmcgivery's https://github.com/apollographql/router/pull/6027 into dev.  It's already been reviewed.  It just needs tests to run.

Added telemetry for Rhai usage (#6027)

---

apollo-federation/src/sources/connect/json_selection/mod.rs
apollo-federation/src/sources/connect/validation/coordinates.rs
apollo-federation/src/sources/connect/validation/extended_type.rs
apollo-federation/src/sources/connect/validation/selection.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@circular_reference.graphql.snap
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@circular_reference_2.graphql.snap
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@denest_scalars.graphql.snap
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@denest_scalars2.graphql.snap
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@fields_with_arguments.graphql.snap
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@group_selection_on_scalar.graphql.snap
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@non_root_circular_reference.graphql.snap
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@rest.graphql.snap
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@select_nonexistant_group.graphql.snap

Also reorganizes selection code a bit with some new helper structs.

Use more specific locations for JSONSelection when available

---

apollo-router/src/query_planner/dual_query_planner.rs

Updated `defer_primary_node_matches` and `deferred_node_matches` to use semantic diff based on the existing `operation_matches`, instead of string comparison of subselections.
I've tested manually. It's tricky to unit-test these nodes. It's mainly reusing the existing `operation_matches` function with some refactoring. So, there shouldn't be major concerns.
---
**Checklist**
[ROUTER-788]: https://apollographql.atlassian.net/browse/ROUTER-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dual-query-planner): use semantic diff when comparing Defer nodes

---

apollo-router/src/query_planner/dual_query_planner.rs

- In rare cases, the `requires` field can have multiple items with the same SelectionKey.
- The previous comparison method could fail to match them if they are in different order.
---
**Checklist**
[ROUTER-803]: https://apollographql.atlassian.net/browse/ROUTER-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dual_query_planner): updated semantic diff to set-comparison on `requires`

---

apollo-router/src/query_planner/dual_query_planner.rs

Semantic diff generated messages are not very helpful when the difference is under a parallel node.
Example diff message (old):
```
mismatched set: missing item[0]
under Parallel node
under item[1]
under Sequence node
```
The semantic diff now digs deeper into the parallel nodes if only one child item is mismatching on each side.
For example, JS QP's parallel node has [A, B, C] and Rust QP has [B, C, A']. Then, we can say A and A' are supposed to be matching. Then, the error message includes the difference between A and A'.
Thus, the example diff above improves as following:
```
mismatch: no matching fragment definition for XXX
under Fetch node (operation name: YYY)
under Flatten node (path: ZZZ)
under item[0]
under Sequence node
under a sole unmatched pair (0 -> 2) in a set comparison …
```

test(dual-query-planner): improved semantic diff message for parallel nodes

---

apollo-federation/src/sources/connect/header.rs
apollo-router/src/plugins/connectors/testdata/steelthread.graphql
apollo-router/src/plugins/connectors/testdata/steelthread.yaml
apollo-router/src/plugins/connectors/tests.rs

---
**Checklist**
**Exceptions**
**Notes**
[CNN-490]: https://apollographql.atlassian.net/browse/CNN-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …

Add the ability to use $args and $this in headers

---

apollo-router/src/services/layers/query_analysis.rs

This is usually small, but still
---
**Checklist**
**Exceptions**
The testing process is that it compiles
**Notes**

Remove redundant clone

---

.changesets/fix_geal_progressive_override_test.md
CHANGELOG.md
Cargo.lock
apollo-federation/Cargo.toml
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.template.toml
apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
scripts/install.sh

> **Note**
>
> When approved, this PR will merge into **the \`1.57.1\` branch** which will — upon being approved itself — merge into \`main\`.
>
>  - That it targets the right release branch (\`$1.57.1\` in this case!).
>
---

prep release: v1.57.1

---

.changesets/fix_geal_progressive_override_test.md
.circleci/config.yml
CHANGELOG.md
Cargo.lock
apollo-federation/Cargo.toml
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.template.toml
apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
apollo-router/Cargo.toml
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/tests/samples/enterprise/progressive-override/basic/README.md
apollo-router/tests/samples/enterprise/progressive-override/basic/configuration.yaml
apollo-router/tests/samples/enterprise/progressive-override/basic/configuration2.yaml
apollo-router/tests/samples/enterprise/progressive-override/basic/plan.json
apollo-router/tests/samples/enterprise/progressive-override/basic/rhai/main.rhai
apollo-router/tests/samples/enterprise/progressive-override/basic/supergraph.graphql
apollo-router/tests/samples/enterprise/progressive-override/warmup/README.md
apollo-router/tests/samples/enterprise/progressive-override/warmup/configuration.yaml
apollo-router/tests/samples/enterprise/progressive-override/warmup/configuration2.yaml
apollo-router/tests/samples/enterprise/progressive-override/warmup/plan.json
apollo-router/tests/samples/enterprise/progressive-override/warmup/rhai/main.rhai
apollo-router/tests/samples/enterprise/progressive-override/warmup/supergraph.graphql
apollo-router/tests/samples_tests.rs
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
scripts/install.sh

> **Note**
> **This particular PR must be true-merged to \`main\`.**
* This PR is only ready to review when it is marked as "Ready for Review".  It represents the merge to the \`main\` branch of an upcoming release (version number in the title).
* We may cut any number of alpha and release candidate (RC) versions off this branch prior to formalizing it.
- Does this PR target the right branch? (usually, \`main\`)
- Are the appropriate **version bumps** and **release …

release: v1.57.1

---

apollo-router/src/plugins/connectors/http_json_transport.rs
apollo-router/src/plugins/connectors/make_requests.rs

---
**Checklist**
**Exceptions**
**Notes**

add content-length header to requests as appropriate

---

apollo-router/src/plugins/connectors/http_json_transport.rs

---
**Checklist**
**Exceptions**
**Notes**

fix JSONSelection::parse signature

---

apollo-router/src/plugins/connectors/handle_responses.rs

---
**Checklist**
**Exceptions**
**Notes**

fix: correctly record invalid request for debugging

---

Cargo.lock
apollo-federation/Cargo.toml
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.template.toml
apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh

---
**Checklist**
**Exceptions**
**Notes**

prep release: v2.0.0-preview.1

---

docs/source/reference/router/telemetry/trace-exporters/overview.mdx

We commonly get questions and confusion on `always_on` vs `always_off`

[docs] Update Router telemetry docs

---

apollo-router/src/query_planner/dual_query_planner.rs

This PR improved the `subscription_primary_matches` function with semantic comparison.
Other nodes like fetch/defer have already been improved. The subscription node was the only one left to fix.
---
**Checklist**
**Exceptions**
I've confirmed the false mismatches found from corpus have been eliminated. Unfortunately, it's too cumbersome to add unit tests, but the code change is small and similar to the existing fetch node comparison.

fix(dual-query-planner): semantic diff treatment to subscription comparison

---

docs/source/reference/migration/from-router-v1.mdx

rename and copyedit router v2 migration page

docs: v2 migration

---

apollo-router/src/plugins/connectors/handle_responses.rs
apollo-router/src/plugins/connectors/http.rs
apollo-router/src/plugins/connectors/http_json_transport.rs
apollo-router/src/plugins/connectors/make_requests.rs
apollo-router/src/plugins/connectors/plugin.rs
apollo-router/src/plugins/connectors/plugin/debug.rs
apollo-router/src/services/connector_service.rs

---
**Checklist**
**Exceptions**
**Notes**

fix: emit debug extension for each response chunk

---

.changesets/fix_renee_quieres_queries.md
apollo-router/src/services/layers/persisted_queries/mod.rs

As titled
---
**Checklist**
**Exceptions**
**Notes**

Fix typo in persisted query metric attribute

---

apollo-federation/src/link/database.rs
apollo-federation/src/link/federation_spec_definition.rs
apollo-federation/src/link/mod.rs
apollo-federation/src/subgraph/spec.rs

There isn't any fuzzy matching around the name (i.e. it won't suggest things that are a letter or two off like in federation).
---
**Checklist**
**Exceptions**
**Notes** …

Enable test to look for invalid federation imports.

---

docs/source/reference/migration/from-router-v1.mdx

Add a note about the most recent v2 version and the expected state of the upgrade guide during the Developer Preview.

docs: note for upgrade guide

---

apollo-router/src/configuration/mod.rs

Looks like something did not merge right.
---
**Checklist**
**Exceptions**
**Notes**

fix build after merges

---

apollo-router/src/services/external.rs

It said `FIXME`
This is my best guess at what the module contains. Please confirm!
---
**Checklist**
**Exceptions**
No tests or compatibility or performance impact for doc comment change.
**Notes** …

Add doc comment to `services::external`

---

.circleci/config.yml
about.toml
licenses.html

Signed-off-by: Benjamin <5719034+bnjjj@users.noreply.github.com>
Co-authored-by: Gary Pennington <gary@apollographql.com>
(cherry picked from commit 5f72471d05deb6379610d1f661b2d84b4c65e10a)

fix cargo about (#6423)

---

apollo-router/src/plugins/connectors/tests/mod.rs

just whitespace changes in queries and ordering changes in parallel fetch nodes. nothing that actually changes functionality.
---
**Checklist**
**Exceptions**
**Notes** …

update tests for native QP

---

apollo-federation/src/query_plan/display.rs
apollo-federation/src/query_plan/fetch_dependency_graph.rs
apollo-federation/src/query_plan/mod.rs
apollo-router/src/query_planner/convert.rs

This PR makes bugfixes to the Rust QP port of type-conditioned fetching. There's a few of these, so I'm going to leave comments on the code with relevant information.

Miscellaneous type-conditioned fetching fixes

---

apollo-router/src/plugins/connectors/handle_responses.rs
apollo-router/src/plugins/connectors/make_requests.rs
apollo-router/src/plugins/connectors/tests/mod.rs

---
**Checklist**
**Exceptions**
**Notes**

include paths in errors

---

apollo-federation/src/schema/mod.rs
apollo-federation/src/schema/schema_upgrader.rs
apollo-federation/src/supergraph/subgraph.rs

SchemaUpgrader is placeholder for now.

Add upgrade_subgraphs_if_necessary port from JS code

---

apollo-federation/src/sources/connect/models.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@invalid_connect_http_headers.graphql.snap
apollo-federation/src/sources/connect/validation/test_data/invalid_connect_http_headers.graphql

---
**Checklist**
**Exceptions**
**Notes**

fix: allow setting `accept` header

---

Cargo.lock
apollo-federation/Cargo.toml
apollo-router-benchmarks/Cargo.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh

New preview release
---
**Checklist**
**Exceptions**
**Notes**

prep release: v2.0.0-preview.4

---

Cargo.lock
Cargo.toml
apollo-federation/src/operation/tests/mod.rs
apollo-federation/src/query_graph/path_tree.rs
apollo-federation/src/subgraph/mod.rs
apollo-router/src/error.rs
apollo-router/src/graphql/mod.rs
apollo-router/src/graphql/response.rs
apollo-router/src/introspection.rs
apollo-router/src/services/supergraph/snapshots/apollo_router__services__supergraph__tests__invalid_input_enum.snap
apollo-router/src/spec/query/transform.rs
examples/supergraph-sdl/rust/Cargo.toml

---
**Checklist**
**Exceptions**
**Notes**

Update to apollo-compiler 1.25.0 stable release

---

.changesets/fix_junior_granddad_salami_dye.md
.changesets/fix_tninesling_demand_control_perf.md
Cargo.lock
Cargo.toml
apollo-federation/src/operation/tests/mod.rs
apollo-federation/src/query_graph/path_tree.rs
apollo-federation/src/subgraph/mod.rs
apollo-router/src/error.rs
apollo-router/src/graphql/mod.rs
apollo-router/src/graphql/response.rs
apollo-router/src/introspection.rs
apollo-router/src/plugins/connectors/tests/mod.rs
apollo-router/src/plugins/demand_control/cost_calculator/schema.rs
apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
apollo-router/src/plugins/fleet_detector.rs
apollo-router/src/services/supergraph/snapshots/apollo_router__services__supergraph__tests__invalid_input_enum.snap
apollo-router/src/spec/query/transform.rs
dockerfiles/tracing/datadog-subgraph/package-lock.json
dockerfiles/tracing/jaeger-subgraph/package-lock.json
dockerfiles/tracing/zipkin-subgraph/package-lock.json
docs/source/routing/self-hosted/containerization/docker.mdx
examples/coprocessor-override-launchdarkly/package-lock.json
examples/supergraph-sdl/rust/Cargo.toml

Merges dev into next and reverts https://github.com/apollographql/router/commit/f52bab84301cee3a32254b48562d8cb13998447b, which should stay on dev and in the 1.x line, but not on next and the 2.x line.
The fleet detector changes were a bit tricky to merge. I think we should be okay merging this on Monday.

merge dev into next

---

apollo-router/src/axum_factory/tests.rs
apollo-router/src/plugin/mod.rs
apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
apollo-router/src/plugins/include_subgraph_errors.rs
apollo-router/src/plugins/test.rs
apollo-router/src/plugins/traffic_shaping/mod.rs
apollo-router/src/query_planner/caching_query_planner.rs
apollo-router/src/query_planner/execution.rs
apollo-router/src/query_planner/fetch.rs
apollo-router/src/query_planner/query_planner_service.rs
apollo-router/src/query_planner/subscription.rs
apollo-router/src/query_planner/tests.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/execution/service.rs
apollo-router/src/services/supergraph/service.rs
apollo-router/src/spec/query.rs
apollo-router/src/spec/query/change.rs

Cherry-pick of https://github.com/apollographql/router/pull/6569 onto dev

Avoid re-computing implementers_map in QueryHashVisitor (dev)

---

apollo-router/tests/samples/enterprise/connectors-debugging/README.md
apollo-router/tests/samples/enterprise/connectors-debugging/plan.json

---
**Checklist**
**Exceptions**
**Notes**

use hardcode port outside ephemeral port range

---

docs/source/reference/router/telemetry/trace-exporters/jaeger.mdx
docs/source/routing/performance/query-planner-pools.mdx

(Re)add page for deprecated query planner pool

docs: deprecated query planner pool

---

apollo-router/src/plugins/connectors/incompatible.rs
apollo-router/src/plugins/connectors/incompatible/apq.rs
apollo-router/src/plugins/connectors/incompatible/authentication.rs
apollo-router/src/plugins/connectors/incompatible/batching.rs
apollo-router/src/plugins/connectors/incompatible/headers.rs
apollo-router/src/plugins/connectors/incompatible/traffic_shaping.rs
apollo-router/src/plugins/connectors/incompatible/url_override.rs
apollo-router/tests/integration/connectors.rs

Add some more warnings for incompatible router features.
---
**Checklist**
**Exceptions**
**Notes** …

connectors: add batching warning

---

docs/source/routing/performance/caching/entity.mdx

docs: fix link entity caching link

---

docs/source/reference/graphos-features.mdx

Clarify use of schema delivery to maintain schema when using offline license

doc: clarify offline license

---

docs/source/reference/graphos-features.mdx

Clarify use of schema delivery to maintain schema when using offline license<hr>This is an automatic backport of pull request #6679 done by [Mergify](https://mergify.com).

doc: clarify offline license (backport #6679)

---

apollo-federation/src/sources/connect/expand/carryover.rs
apollo-federation/src/sources/connect/expand/snapshots/apollo_federation__sources__connect__expand__carryover__tests__carryover.snap
apollo-federation/src/sources/connect/expand/tests/schemas/ignore/directives.graphql
apollo-federation/src/sources/connect/expand/tests/schemas/ignore/directives.yaml
apollo-router/tests/samples/enterprise/connectors-demand-control/README.md
apollo-router/tests/samples/enterprise/connectors-demand-control/configuration.yaml
apollo-router/tests/samples/enterprise/connectors-demand-control/http_snapshots.json
apollo-router/tests/samples/enterprise/connectors-demand-control/plan.json
apollo-router/tests/samples/enterprise/connectors-demand-control/supergraph.graphql
apollo-router/tests/samples/enterprise/connectors-demand-control/supergraph.yaml

---
**Checklist**
**Exceptions**
**Notes**

carryover cost/listSize directives

---

apollo-router/src/plugins/connectors/handle_responses.rs
apollo-router/src/plugins/connectors/tests/mod.rs

customer bug report.
eventually we'll probably want content negotiation but this is good enough for now
---
**Checklist**
**Exceptions**
**Notes** …

fix: don't try json parsing empty bodies

---

docs/source/reference/router/configuration.mdx

Fixes malformed table on configuration page

doc: fix malformed table

---

docs/source/routing/about-router.mdx

docs: fix image

---

apollo-router/src/test_harness/http_snapshot.rs

These changes only affect the test snapshot server, not the router itself.
* Filter headers sent to upstream API
* Pass query parameters through to upstream API
* Ensure that the content-length in snapshot response is correct
---
**Checklist**
**Exceptions**
**Notes** …

Snapshot server fixes

---

apollo-router-benchmarks/src/shared.rs
apollo-router/src/plugin/test/mock/canned.rs
apollo-router/src/services/supergraph/tests.rs
apollo-router/tests/samples/core/defer/plan.json
apollo-router/tests/samples/enterprise/entity-cache/defer/plan.json
apollo-router/tests/samples/enterprise/entity-cache/invalidation-entity-key/plan.json
apollo-router/tests/tracing_common/mod.rs

---
**Checklist**
**Exceptions**
**Notes**

Fix subgraph mocks for tests that use fragments

---

apollo-router/src/uplink/mod.rs

Add router version to uplink request. Note that this may produce weird versions for users that have custom builds.
---
**Checklist**
**Exceptions**
**Notes** …

add router version to uplink request (backport #6698)

---

Cargo.lock
apollo-federation/cli/Cargo.toml
apollo-federation/cli/src/main.rs

- Added tracing-subscriber.
- Filtering based on the RUST_LOG variable.
---
**Checklist**
Exception: Internal debugging feature

test(federation-cli): enable log printing from apollo-federation-cli

---

Cargo.lock
apollo-federation/Cargo.toml
apollo-federation/src/sources/connect/validation/mod.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@valid_large_body.graphql.snap
apollo-federation/src/sources/connect/validation/test_data/valid_large_body.graphql

Adds a test for validation speeds in snapshots (just a max time) and upgrades shape-rs to fix an issue.

Test validation speeds

---

apollo-federation/src/sources/connect/spec/mod.rs
apollo-federation/src/sources/connect/validation/mod.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@connect_spec_version_error.graphql.snap
apollo-federation/src/sources/connect/validation/test_data/connect_spec_version_error.graphql

Add clear error message when connect link version is wrong

---

docs/source/routing/performance/query-batching.mdx

Add details about how batching impacts the billable count on paid plans

[docs] Update query-batching with billable details

---

docs/source/routing/about-v1.mdx

[deploy preview ](https://deploy-preview-474--apollo-docs-rewrite.netlify.app/docs/graphos/routing/v1/about-v1)from https://github.com/apollographql/docs-rewrite/pull/474

docs: router 1.x info

---

docs/source/reference/router/self-hosted-install.mdx

<hr>This is an automatic backport of pull request #6796 done by [Mergify](https://mergify.com).

docs: clarify router download steps (backport #6796)

---

.changesets/helm_targetport_configuration.md
helm/chart/router/templates/service.yaml
helm/chart/router/values.yaml

Allow setting of service port in helm chart
---
**Checklist**
**Exceptions**
**Notes**
<hr>This is an …

Allow setting of service port in helm chart (backport #6804)

---

.changesets/feat_remote_proxy_downloads.md
scripts/install.sh

Brings over the work done in #6244, originally done by @LongLiveCHIEF so that we can merge it before LTS without lots of rebasing
---
**Checklist**
**Notes** …

ROVER-263 Enable remote proxy downloads (same as #6244)

---

.changesets/feat_remote_proxy_downloads.md
scripts/install.sh

Brings over the work done in #6244, originally done by @LongLiveCHIEF so that we can merge it before LTS without lots of rebasing
---
**Checklist**
**Notes** …

ROVER-263 Enable remote proxy downloads (same as #6244) (backport #6667)

---

apollo-router/src/services/subgraph_service.rs

Follow up of #6771 to make CI works properly.
---
**Checklist**
**Exceptions**
**Notes**
[ROUTER-1083]: …

Add more observability around WS handshake failures (backport #6798)

---

docs/source/routing/about-v1.mdx

Removes LTS information until 1.61.

docs: update about 1.x

---

docs/source/reference/graphos-features.mdx
docs/source/routing/about-router.mdx
docs/source/routing/cloud/index.mdx
docs/source/routing/customization/coprocessor.mdx
docs/source/routing/observability/index.mdx
docs/source/routing/observability/otel-traces-to-prometheus.mdx
docs/source/routing/observability/telemetry/instrumentation/events.mdx
docs/source/routing/observability/telemetry/instrumentation/instruments.mdx
docs/source/routing/observability/telemetry/instrumentation/spans.mdx
docs/source/routing/operations/subscriptions/index.mdx
docs/source/routing/security/authorization.mdx
docs/source/routing/security/jwt.mdx
docs/source/routing/security/router-authentication.mdx
docs/source/routing/self-hosted/index.mdx
docs/source/routing/self-hosted/resource-management.mdx

- Call out router rate limit for free plan
- Update areas that mention an Enterprise plan is needed for particular features<hr>This is an automatic backport of pull request #6748 done by [Mergify](https://mergify.com).

docs: free plan changes (backport #6748)

---

docs/source/routing/about-v1.mdx

Only merge once 1.61 is released

docs: add back LTS info

---

docs/source/reference/upgrade/from-router-v1.mdx

docs: fix link

---

docs/source/reference/upgrade/from-router-v1.mdx
docs/source/routing/graphos-reporting.mdx

Since 1.61, we have removed the experimental prefix on this option.  This PR aims to clarify the appropriate option name depending on version.
---
**Checklist**
**Exceptions**
**Notes** …

Docs update for otlp_tracing_sampler >= 1.61

---

docs/source/routing/graphos-reporting.mdx

Manual backport of https://github.com/apollographql/router/pull/6842/files

docs: update otlp reporting

---

docs/source/routing/customization/rhai.mdx

Add link on Rhai customization guide to Rhai API reference page

docs: rhai api ref

---

docs/source/routing/customization/rhai.mdx

Add link on Rhai customization guide to Rhai API reference page <hr>This is an automatic backport of pull request #6876 done by [Mergify](https://mergify.com).

docs: rhai api ref (backport #6876)

---

apollo-router/src/plugins/telemetry/otlp.rs

In #6816 accidentally forgot to remove `dbg!` before merging it 🤦
---
**Checklist**
**Exceptions**
**Notes**

Remove accidental dbg!

---

.github/CODEOWNERS

Allow all fed core members to approve PRs in `apollo-federation`
---
**Checklist**
**Exceptions**
**Notes**

Add all fed core members as apollo-federation owners

---

Cargo.lock
apollo-federation/Cargo.toml
apollo-router/Cargo.toml

deps: update rstest to 0.25.0

---

CHANGELOG.md

---
**Checklist**
**Exceptions**
**Notes**

Remove duplicates in the changelog

---

apollo-router/tests/integration/traffic_shaping.rs

This test is frequently failing on CI, especially on macOS.
Looking into it, the test is making an incorrect assertion. The purpose of the test is to make sure that when a request times out, it has the GraphQL operation name in the `otel.name` attribute.
This assertion was changed in the backpressure work, likely because backpressure made the test fail:
https://github.com/apollographql/router/commit/8f1459b59eb77dade3fa559649735b0ca7aced12#diff-922f40380fab15ec672ef4074c95504d1e925de392bb8f11b38f83a080d83a58L116-R117
Note this *does not* indicate broken behaviour in the router: the test just failed because it specifies an extremely short timeout of 1 nanosecond. When backpressure functions correctly, the request times out before the GraphQL operation is even parsed. So we don't know what …

Fix flaky test for timed-out operation name in tracing

---

apollo-federation/src/query_plan/display.rs
apollo-router/src/query_planner/convert.rs

I forgot to apply some minor refactoring suggestions for PR #6861 before merging it.
---
**Checklist**
**Exceptions**
This is just a refactoring.

refactor: simplified some parts of PR #6861

---

apollo-router/src/plugins/connectors/incompatible/tls.rs
apollo-router/src/plugins/connectors/incompatible/traffic_shaping.rs
apollo-router/tests/integration/connectors.rs

Update warnings on connector configuration incompatibility for TLS and Traffic Shaping.
---
**Checklist**
**Exceptions**
**Notes** …

Update warnings on connector configuration incompatibility for TLS and Traffic Shaping

---

.changesets/feat_bryn_connection_metrics_2_0.md

#7023 was missing a changeset
---
**Checklist**
**Exceptions**
**Notes**

Add changeset for #7023

---

apollo-federation/src/sources/connect/validation/mod.rs
apollo-federation/src/sources/connect/validation/schema.rs

We disallow certain federation directives from being imported at all when connectors are in use. This moves that check into the new "schema-wide" group for organization purposes. The check itself is identical _except_ that it now only happens when the other schema-wide checks happen. So the user-facing impact is if you have errors in your connect directives and _then_ you import `@context`, you won't see the error on the import until you fix the errors you already had.
The function itself is a copy/paste.

Move link import conflict check into schema-wide checks

---

apollo-federation/src/sources/connect/models.rs
apollo-federation/src/sources/connect/spec/directives.rs
apollo-federation/src/sources/connect/spec/mod.rs
apollo-federation/src/sources/connect/spec/versions.rs
apollo-federation/src/sources/connect/validation/graphql.rs
apollo-federation/src/sources/connect/validation/http/headers.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@headers__disallowed_header_names.graphql.snap
apollo-federation/src/sources/connect/validation/test_data/headers/disallowed_header_names.graphql

---
**Checklist**
**Exceptions**
**Notes**

use spec version to determine allowed headers

---

.changesets/config_meryl_pulsr_1463.md
apollo-router/src/configuration/migrations/0037-preview_otlp_error_metrics.yaml
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__upgrade_old_configuration@apollo_extended_errors.yaml.snap
apollo-router/src/configuration/testdata/migrations/apollo_extended_errors.yaml
apollo-router/src/plugins/connectors/incompatible/telemetry.rs
apollo-router/src/plugins/telemetry/apollo.rs
apollo-router/src/services/layers/persisted_queries/snapshots/apollo_router__services__layers__persisted_queries__tests__pq_layer_freeform_graphql_with_safelist_log_unknown_true@logs.snap
apollo-router/src/services/router/service.rs
apollo-router/src/services/router/tests.rs
apollo-router/tests/integration/connectors.rs

Reverts apollographql/router#7040

Revert "Revert "Error categorization: make feature flag non-experimental""

---

apollo-federation/src/sources/connect/expand/mod.rs
apollo-federation/src/sources/connect/id.rs
apollo-federation/src/sources/connect/models.rs
apollo-federation/src/sources/connect/snapshots/apollo_federation__sources__connect__models__tests__from_schema_v0_2.snap
apollo-federation/src/sources/connect/spec/directives.rs
apollo-federation/src/sources/connect/tests/schemas/simple_v0_2.graphql
apollo-federation/src/sources/connect/tests/schemas/simple_v0_2.yaml
apollo-federation/src/sources/connect/validation/connect.rs
apollo-federation/src/sources/connect/validation/connect/selection.rs
apollo-federation/src/sources/connect/validation/coordinates.rs
apollo-federation/src/sources/connect/validation/expression.rs
apollo-federation/src/sources/connect/validation/variable/mod.rs
apollo-federation/src/sources/connect/validation/variable/resolver/this.rs
apollo-federation/src/sources/connect/variable.rs

this is safe to merge because there's no active version of federation that allows connect on types
---
**Checklist**
**Exceptions**
**Notes** …

connect runtime: find @connect on types

---

apollo-federation/src/sources/connect/validation/connect.rs

`validate_source_name` now returns the `SourceName` so it's more clear what's happening, and that this check has to pass before we can run checks which require it. Also moves the header check up, since that _doesn't_ require the source name.

Make `@connect(source:)` validation more self contained

---

apollo-federation/src/sources/connect/models.rs
apollo-federation/src/sources/connect/models/keys.rs
apollo-federation/src/sources/connect/snapshots/apollo_federation__sources__connect__models__tests__from_schema_v0_2.snap
apollo-federation/src/sources/connect/tests/schemas/simple_v0_2.graphql
apollo-federation/src/sources/connect/tests/schemas/simple_v0_2.yaml
apollo-federation/src/sources/connect/variable.rs
apollo-router/src/plugins/connectors/make_requests.rs

---
**Checklist**
**Exceptions**
**Notes**

add $batch variable and update entity resolver logic

---

apollo-federation/src/sources/connect/models.rs
apollo-router/src/plugins/connectors/handle_responses.rs
apollo-router/src/plugins/connectors/http_json_transport.rs
apollo-router/src/plugins/connectors/make_requests.rs
apollo-router/src/services/connect.rs
apollo-router/src/services/fetch_service.rs

also cleans up some snapshot tests with a more readable debug impl
---
**Checklist**
**Exceptions**
**Notes**

make a request for a batch of connectors

---

docs/source/routing/uplink.mdx

Update schema size limit in Uplink

docs: update schema size limit

---

apollo-federation/src/sources/connect/json_selection/mod.rs
apollo-federation/src/sources/connect/json_selection/selection_set.rs
apollo-federation/src/sources/connect/mod.rs
apollo-router/src/plugins/connectors/handle_responses.rs
apollo-router/src/plugins/connectors/make_requests.rs
apollo-router/src/plugins/connectors/testdata/batch.graphql
apollo-router/src/plugins/connectors/testdata/batch.yaml
apollo-router/src/plugins/connectors/tests/batch.rs
apollo-router/src/plugins/connectors/tests/mod.rs

to ensure integrity between joins, we have to sort the response objects to match the requested entity references. this is essentially the dataloader pattern
---
**Checklist**
**Exceptions**
**Notes** …

handle batch responses with sorting logic

---

docs/source/routing/self-hosted/resource-estimator.mdx

Update copy on  https://www.apollographql.com/docs/graphos/routing/self-hosted/resource-estimator

docs: update resource estimator copy

---

docs/source/routing/self-hosted/resource-estimator.mdx

Update copy on  https://www.apollographql.com/docs/graphos/routing/self-hosted/resource-estimator<hr>This is an automatic backport of pull request #7081 done by [Mergify](https://mergify.com).

docs: update resource estimator copy (backport #7081)

---

apollo-router/src/plugins/authentication/mod.rs

exactly what it says on the tin. This fixes an issue raised by a customer.
---
**Checklist**
**Exceptions**
**Notes** …

stop logging JWKS (backport #7079)

---

apollo-federation/src/sources/connect/validation/connect.rs
apollo-federation/src/sources/connect/validation/connect/selection.rs
apollo-federation/src/sources/connect/validation/coordinates.rs
apollo-federation/src/sources/connect/validation/expression.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch.graphql.snap
apollo-federation/src/sources/connect/validation/test_data/batch.graphql

---
**Checklist**
**Exceptions**
**Notes**

minimal validations to support connect on type

---

apollo-federation/src/sources/connect/validation/connect.rs

A few things in here:
1. Unifies the way we validate a single `@connect` whether on type or field
2. Carries the parse/validate structure up another level
3. Creates a new `ResolvedField` struct to add some semantics to seen fields. We'll want to use that in more places as refactors continue

Create parse & type check phases for `@connect`

---

apollo-federation/src/merge.rs
apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__basic.snap
apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__inaccessible.snap
apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__input_types.snap
apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__interface_implementing_interface.snap
apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__interface_object.snap
apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__steel_thread.snap
apollo-federation/src/schema/position.rs
apollo-federation/src/sources/connect/expand/carryover.rs
apollo-federation/src/sources/connect/expand/snapshots/apollo_federation__sources__connect__expand__carryover__tests__carryover.snap
apollo-federation/src/sources/connect/expand/tests/schemas/expand/carryover.graphql
apollo-federation/src/sources/connect/expand/tests/schemas/expand/carryover.yaml
apollo-federation/src/sources/connect/expand/tests/schemas/ignore/directives.graphql
apollo-federation/src/sources/connect/expand/tests/schemas/ignore/directives.yaml
apollo-federation/src/sources/connect/expand/tests/snapshots/api@carryover.graphql.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/supergraph@batch.graphql.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/supergraph@carryover.graphql.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/supergraph@interface-object.graphql.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/supergraph@keys.graphql.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/supergraph@nested_inputs.graphql.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/supergraph@normalize_names.graphql.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/supergraph@realistic.graphql.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/supergraph@sibling_fields.graphql.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/supergraph@simple.graphql.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/supergraph@steelthread.graphql.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/supergraph@types_used_twice.graphql.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_supergraph.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_types_from_different_subgraphs.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_with_descriptions.snap
apollo-federation/tests/snapshots/main__composition_tests__compose_removes_federation_directives.snap

---
**Checklist**
**Exceptions**
**Notes**

don't discard context/fromContext when using connectors

---

apollo-federation/src/sources/connect/id.rs
apollo-federation/src/sources/connect/validation/connect.rs
apollo-federation/src/sources/connect/validation/connect/entity.rs
apollo-federation/src/sources/connect/validation/connect/http.rs
apollo-federation/src/sources/connect/validation/connect/selection.rs
apollo-federation/src/sources/connect/validation/mod.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch.graphql.snap
apollo-federation/src/sources/connect/validation/test_data/batch.graphql

- using $batch on fields
- using connect on root types
- incorrect fields on batch
- using $batch and $this together
- using $batch in selection
---
**Checklist**
**Exceptions**
**Notes** …

additional validations for connect on type/$batch

---

apollo-router/src/plugins/connectors/tests/mod.rs

Add test for yaml config overriding connectors schema defined headers
---
**Checklist**
**Exceptions**
**Notes** …

Add test for yaml config overriding connectors schema defined headers

---

.changesets/fix_shawl_goalie_nickel_antelope.md
CHANGELOG.md
Cargo.lock
apollo-federation/Cargo.toml
apollo-federation/src/query_graph/build_query_graph.rs
apollo-federation/src/query_graph/graph_path.rs
apollo-federation/src/query_graph/mod.rs
apollo-federation/src/query_plan/query_planner.rs
apollo-federation/src/query_plan/query_planning_traversal.rs
apollo-federation/src/query_plan/query_planning_traversal/non_local_selections_estimation.rs
apollo-federation/tests/query_plan/build_query_plan_tests/overrides.rs
apollo-federation/tests/query_plan/build_query_plan_tests/overrides/shareable.rs
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.template.toml
apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
apollo-router/Cargo.toml
apollo-router/src/configuration/metrics.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__env_metrics.snap
apollo-router/src/query_planner/query_planner_service.rs
apollo-router/src/services/layers/query_analysis.rs
apollo-router/src/spec/operation_limits.rs
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh

> **Note**
> **This particular PR must be true-merged to `1.x`.**
* This PR represents the merge to the `1.x` branch of an upcoming release (version number in the title).
- Does this PR target the right branch? (usually, `1.x`)
- Are the appropriate **version bumps** and **release note edits** in the end of the commit list (or within the last few commits).  In other words, "Did the 'release prep' PR actually land on this branch?"
- If those things look good, this PR …

release: v1.61.2

---

.changesets/fix_volleyball_embrace_cottage_prosecutor.md
CHANGELOG.md
Cargo.lock
apollo-federation/Cargo.toml
apollo-federation/src/query_graph/build_query_graph.rs
apollo-federation/src/query_graph/graph_path.rs
apollo-federation/src/query_graph/mod.rs
apollo-federation/src/query_plan/query_planner.rs
apollo-federation/src/query_plan/query_planning_traversal.rs
apollo-federation/src/query_plan/query_planning_traversal/non_local_selections_estimation.rs
apollo-federation/tests/dhat_profiling/query_plan.rs
apollo-federation/tests/query_plan/build_query_plan_tests/overrides.rs
apollo-federation/tests/query_plan/build_query_plan_tests/overrides/shareable.rs
apollo-router-benchmarks/Cargo.toml
apollo-router/Cargo.toml
apollo-router/src/configuration/metrics.rs
apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__env_metrics.snap
apollo-router/src/query_planner/query_planner_service.rs
apollo-router/src/services/layers/query_analysis.rs
apollo-router/src/spec/operation_limits.rs
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh

> **Note**
> **This particular PR must be true-merged to `dev`.**
* This PR represents the merge to the `dev` branch of an upcoming release (version number in the title).
- Does this PR target the right branch? (usually, `dev`)
- Are the appropriate **version bumps** and **release note edits** in the end of the commit list (or within the last few commits).  In other words, "Did the 'release prep' PR actually land on this branch?"
- If those things look good, this PR …

release: v2.1.1

---

apollo-federation/src/merge.rs
apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__basic.snap
apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__inaccessible.snap
apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__input_types.snap
apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__interface_implementing_interface.snap
apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__interface_object.snap
apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__steel_thread.snap
apollo-federation/src/schema/position.rs
apollo-federation/src/sources/connect/expand/carryover.rs
apollo-federation/src/sources/connect/expand/snapshots/apollo_federation__sources__connect__expand__carryover__tests__carryover.snap
apollo-federation/src/sources/connect/expand/tests/schemas/expand/carryover.graphql
apollo-federation/src/sources/connect/expand/tests/schemas/expand/carryover.yaml
apollo-federation/src/sources/connect/expand/tests/schemas/ignore/directives.graphql
apollo-federation/src/sources/connect/expand/tests/schemas/ignore/directives.yaml
apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@carryover.graphql-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@carryover.graphql.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@circular.graphql-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@interface-object.graphql-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@keys.graphql-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@nested_inputs.graphql-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@normalize_names.graphql-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@realistic.graphql-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@sibling_fields.graphql-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@simple.graphql-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@steelthread.graphql-3.snap
apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@types_used_twice.graphql-3.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_supergraph.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_types_from_different_subgraphs.snap
apollo-federation/tests/snapshots/main__composition_tests__can_compose_with_descriptions.snap
apollo-federation/tests/snapshots/main__composition_tests__compose_removes_federation_directives.snap

---
**Checklist**
**Exceptions**
**Notes**
<hr>This is an automatic backport of pull request #7113 done by …

don't discard context/fromContext when using connectors (backport #7113)

---

RELEASE_CHECKLIST.md

These edits are not comprehensive, but start to incorporate some of the changes necessary to evolve the release process for the multiple release lines.
Something > everything, and I'd rather we improve this on each release rather than not make any changes. 😄

Some edits to RELEASE_CHECKLIST.md

---

apollo-router/src/error.rs
apollo-router/src/plugins/cache/entity.rs
apollo-router/src/query_planner/caching_query_planner.rs

---
**Checklist**
**Exceptions**
**Notes**

don't cache QP errors for authz or pool processing failures

---

Cargo.lock
apollo-router/Cargo.toml

Remove unused dependency: async-channel
---
**Checklist**
**Exceptions**
**Notes**

Remove unused dependency: async-channel

---

docs/source/routing/configuration.mdx
docs/source/routing/graphos-reporting.mdx

Recommend v2.1.2 as the minimum version for extended error reporting.
---
**Checklist**
**Exceptions**
**Notes** …

Update extended errors min version to 2.1.2

---

.changesets/docs_vulture_companion_residence_yarn.md
docs/source/routing/router-api-gateway-comparison.mdx

Update the tech note with more details now that we have connectors

[docs] Update API Gateway tech note

---

.changesets/fix_caroline_compute_pool_metrics.md
apollo-router/src/compute_job/metrics.rs
apollo-router/src/compute_job/mod.rs
apollo-router/src/compute_job/snapshots/apollo_router__compute_job__tests__observability@logs.snap
apollo-router/tests/integration/telemetry/metrics.rs

Makes use of the strum `snake_case` serialization option.
I updated the existing changeset rather than adding a new one, hopefully that will make things easier when it comes time to mint the changelog.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick …

Use snake case for metric values

---

.changesets/fix_caroline_compute_pool_metrics.md
apollo-router/src/compute_job/metrics.rs
apollo-router/src/compute_job/mod.rs
apollo-router/src/compute_job/snapshots/apollo_router__compute_job__tests__observability@logs.snap
apollo-router/tests/integration/telemetry/metrics.rs

Makes use of the strum `snake_case` serialization option.
I updated the existing changeset rather than adding a new one, hopefully that will make things easier when it comes time to mint the changelog.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick …

Use snake case for metric values (backport #7308)

---

apollo-federation/src/link/federation_spec_definition.rs
apollo-federation/src/schema/mod.rs
apollo-federation/src/schema/type_and_directive_specification.rs
apollo-federation/src/subgraph/typestate.rs
apollo-federation/src/supergraph/mod.rs

- ported `addFederationOperation` from JS
- ported `expands_everything_if_only_the_federation_spec_is_linked` test

feat(federation/composition): port addFederationOperations

---

.changesets/feat_enhanced_client_awareness.md
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/enhanced_client_awareness/mod.rs
apollo-router/src/plugins/enhanced_client_awareness/tests.rs
apollo-router/src/plugins/mod.rs
apollo-router/src/plugins/telemetry/metrics/apollo/snapshots/apollo_router__plugins__telemetry__metrics__apollo__studio__test__aggregation.snap
apollo-router/src/plugins/telemetry/metrics/apollo/studio.rs
apollo-router/src/plugins/telemetry/mod.rs
apollo-router/src/router_factory.rs
apollo-router/src/services/layers/persisted_queries/snapshots/apollo_router__services__layers__persisted_queries__tests__pq_layer_freeform_graphql_with_safelist_log_unknown_true@logs.snap

This is the plugin to enable capturing of client library metadata, aka. Enhanced Client Awareness.
**Checklist**
- I've been working closely with the Insights team and they're aware of this work and helping with the implementation.
- ~Documentation[^2] completed~
- I don't believe any documentation is necessary because this is not a configurable plugin; it should _always_ execute. It is the clients that are configurable re. whether to send the request metadata or not.
**Manual Testing**
* Tested locally using the [Deepspace Dogfood supergraph with local Router code](https://github.com/mdg-private/deepspace-dogfood-supergraph?tab=readme-ov-file#running-local-route …

feature: Plugin for Enhanced Client Awareness

---

docs/source/routing/observability/telemetry/trace-exporters/datadog.mdx
docs/source/routing/observability/telemetry/trace-exporters/dynatrace.mdx
docs/source/routing/observability/telemetry/trace-exporters/jaeger.mdx
docs/source/routing/observability/telemetry/trace-exporters/new-relic.mdx
docs/source/routing/observability/telemetry/trace-exporters/overview.mdx

Clarify the trace exporters that are configurations of OTLP trace exporter

docs: trace exporters

---

docs/source/routing/security/persisted-queries.mdx

This seems like a typo.
---
**Checklist**
**Exceptions**
**Notes**

docs: typo on PQ docs

---

apollo-federation/src/sources/connect/spec/directives.rs

Replace from_values with TryFrom
---
**Checklist**
**Exceptions**
**Notes**

Replace from_values with TryFrom

---

apollo-federation/src/sources/connect/models/http_json_transport.rs

[CNN-771]: https://apollographql.atlassian.net/browse/CNN-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Skip null values in `queryParams`

---

apollo-federation/src/sources/connect/spec/type_and_directive_specifications.rs

Refactor type_and_directive_specifications to avoid extra allocations when creating field lists
---
**Checklist**
**Exceptions**
**Notes** …

Refactor type_and_directive_specifications to avoid extra allocations when creating field lists

---

apollo-federation/src/sources/connect/validation/mod.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch.graphql.snap
apollo-federation/src/sources/connect/validation/test_data/batch.graphql

---
**Checklist**
**Exceptions**
**Notes**

add a test for batch/this in request/response mappings

---

apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch.graphql.snap

---
**Checklist**
**Exceptions**
**Notes**

fix snapshot text

---

docs/source/routing/graphos-features.mdx

add space after comma
---
**Checklist**
**Exceptions**
**Notes**

add space after comma

---

.changesets/fix_am_bug_variablenestedinputargument.md
apollo-router/src/plugins/connectors/make_requests.rs
apollo-router/src/plugins/connectors/make_requests/graphql_utils.rs
apollo-router/src/plugins/connectors/testdata/variables-subgraph.graphql
apollo-router/src/plugins/connectors/testdata/variables.graphql
apollo-router/src/plugins/connectors/tests/mod.rs

Fix bug where connectors errored when using a variable in a nested input argument
---
**Checklist**
**Exceptions**
**Notes** …

Fix bug where connectors errored when using a variable in a nested input argument

---

apollo-router/tests/snapshots/apollo_otel_traces__connector-2.snap
apollo-router/tests/snapshots/apollo_otel_traces__connector.snap
apollo-router/tests/snapshots/apollo_otel_traces__connector_error-2.snap
apollo-router/tests/snapshots/apollo_otel_traces__connector_error.snap

Synchronizes new recently merged snapshots with other upstream changes.
---
**Checklist**
**Exceptions**
**Notes** …

Update Apollo OTel trace snapshots

---

apollo-router/src/plugins/telemetry/proto/reports.proto
apollo-router/tests/snapshots/apollo_reports__batch_send_header-2.snap
apollo-router/tests/snapshots/apollo_reports__batch_send_header.snap
apollo-router/tests/snapshots/apollo_reports__batch_trace_id-2.snap
apollo-router/tests/snapshots/apollo_reports__batch_trace_id.snap
apollo-router/tests/snapshots/apollo_reports__client_name-2.snap
apollo-router/tests/snapshots/apollo_reports__client_name.snap
apollo-router/tests/snapshots/apollo_reports__client_version-2.snap
apollo-router/tests/snapshots/apollo_reports__client_version.snap
apollo-router/tests/snapshots/apollo_reports__condition_else-2.snap
apollo-router/tests/snapshots/apollo_reports__condition_else.snap
apollo-router/tests/snapshots/apollo_reports__condition_if-2.snap
apollo-router/tests/snapshots/apollo_reports__condition_if.snap
apollo-router/tests/snapshots/apollo_reports__demand_control_stats.snap
apollo-router/tests/snapshots/apollo_reports__demand_control_trace-2.snap
apollo-router/tests/snapshots/apollo_reports__demand_control_trace.snap
apollo-router/tests/snapshots/apollo_reports__demand_control_trace_batched-2.snap
apollo-router/tests/snapshots/apollo_reports__demand_control_trace_batched.snap
apollo-router/tests/snapshots/apollo_reports__new_field_stats.snap
apollo-router/tests/snapshots/apollo_reports__non_defer-2.snap
apollo-router/tests/snapshots/apollo_reports__non_defer.snap
apollo-router/tests/snapshots/apollo_reports__send_header-2.snap
apollo-router/tests/snapshots/apollo_reports__send_header.snap
apollo-router/tests/snapshots/apollo_reports__send_variable_value-2.snap
apollo-router/tests/snapshots/apollo_reports__send_variable_value.snap
apollo-router/tests/snapshots/apollo_reports__stats.snap
apollo-router/tests/snapshots/apollo_reports__trace_id-2.snap
apollo-router/tests/snapshots/apollo_reports__trace_id.snap

Updates the reports.proto file to the latest and fixes the snapshot tests.
---
**Checklist**
**Exceptions**
**Notes** …

Update reports proto and snapshots

---

Cargo.lock
apollo-federation/Cargo.toml
apollo-router-benchmarks/Cargo.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
scripts/install.sh

---
**Checklist**
**Exceptions**
**Notes**

prep release: v2.3.0-preview.0

---

apollo-federation/src/schema/type_and_directive_specification.rs

The commented issue has been fixed by PR #7421.
---
**Checklist**
**Exceptions**
This PR only updates comment lines.

chore(federation/composition): removed a comment link mentioning FED-172

---

docs/source/routing/observability/client-id-enforcement.mdx

Add info about how to customize the client info in studio dynamically via context values

[docs] Update client-id-enforcement.mdx

---

apollo-federation/src/query_graph/graph_path.rs

This is a small PR meant to introduce types/changes to help work progress independently for the satisfiability validation.

feat(federation/composition): Add `TransitionGraphPath` and switch to `UnadvanceableClosures`

---

apollo-federation/src/link/join_spec_definition.rs
apollo-federation/src/schema/type_and_directive_specification.rs

Ports the join spec from JS per [joinSpec.ts](https://github.com/apollographql/federation/blob/main/internals-js/src/specs/joinSpec.ts#L75).
---
**Checklist**
**Exceptions**
**Notes** …

Port join spec

---

apollo-federation/src/sources/connect/spec/mod.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@connect_spec_version_error.graphql.snap
apollo-federation/src/sources/connect/validation/test_data/connect_spec_version_error.graphql
apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
apollo-router/src/plugins/connectors/configuration.rs
apollo-router/src/uplink/feature_gate_enforcement.rs
apollo-router/src/uplink/testdata/connectv0_3.router.yaml
apollo-router/src/uplink/testdata/feature_enforcement_connect_v0_2.graphql
apollo-router/src/uplink/testdata/feature_enforcement_connect_v0_3.graphql

connect/v0.3 doesn't exist yet, but i'm optimistically adding support for it so that this code is still exercised
---
**Checklist**
**Exceptions**
**Notes** …

switch connectors feature gate from 0.2 to 0.3.

---

apollo-federation/src/sources/connect/validation/mod.rs
apollo-federation/src/sources/connect/validation/schema.rs
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch__batch_incorrect_context_key.graphql.snap
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch__batch_missing_key.graphql.snap
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch__batch_missing_nested_key.graphql.snap
apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch__batch_nested_keys.graphql.snap

Adds new error codes for a number of `$batch` validations.
Also removes a number of unused error codes.
---
**Checklist**
**Exceptions**
**Notes** …

[Batch] Add batch error codes and remove unused codes

---

apollo-federation/src/sources/connect/json_selection/methods/public/join_not_null.rs

---
**Checklist**
**Exceptions**
**Notes**

evaluate the argument to joinNotNull

---

.changesets/feat_bnjjj_changeset_7070.md

Add missing changelog for #7070

add changeset for PR 7070

---

.changesets/feat_log_whether_enforcement_was_skipped.md
CHANGELOG.md
Cargo.lock
apollo-federation/Cargo.toml
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.template.toml
apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
scripts/install.sh

> **Note**
>
> When approved, this PR will merge into **the `1.61.7` branch** which will — upon being approved itself — merge into `main`.
>
>  - That it targets the right release branch (`1.61.7` in this case!).
>
---
When logging unknown operations encountered during safe-listing, include information about whether enforcement was skipped. This will help distinguish between truly problematic external operations (where `enforcement_skipped` is false) and internal operations that are intentionally allowed to bypass safelisting (where `enforcement_skipped` is true).
By …

prep release: v1.61.7

---

.changesets/feat_log_whether_enforcement_was_skipped.md
.circleci/config.yml
CHANGELOG.md
Cargo.lock
RELEASE_CHECKLIST.md
apollo-federation/Cargo.toml
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.template.toml
apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.datadog.yml
dockerfiles/tracing/docker-compose.jaeger.yml
dockerfiles/tracing/docker-compose.zipkin.yml
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh

> **Note**
> **This particular PR must be true-merged to `1.x`.**
* This PR is only ready to review when it is marked as "Ready for Review".  It represents the merge to the `1.x` branch of an upcoming release (version number in the title).
* We may cut any number of alpha and release candidate (RC) versions off this branch prior to formalizing it.
- Does this PR target the right branch? (usually, `1.x`)
- Are the appropriate **version bumps** and **release note …

release: v1.61.7

---

apollo-federation/src/merger/merger.rs

Fixed bad merge of #7613 
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level logs. Please read [this guidance](https://github.com/apollographql/router/blob/dev/dev-docs/metrics. …

Add missing bail import removed by bad merge

---

apollo-federation/src/connectors/json_selection/methods/future/eq.rs
apollo-federation/src/connectors/json_selection/methods/future/match_if.rs
apollo-federation/src/connectors/json_selection/methods/public/match.rs
apollo-federation/src/connectors/json_selection/selection_trie.rs
apollo-federation/src/connectors/mod.rs
apollo-federation/src/connectors/spec/mod.rs
apollo-federation/src/connectors/validation/mod.rs

There were very few potential panics left in `apollo_federation::connectors` anyway, so let's enforce preventing future ones with lints!

Apply "don't panic!" lints to all of `connectors`

---

apollo-federation/src/connectors/json_selection/methods.rs
apollo-federation/src/connectors/json_selection/methods/future/mod.rs
apollo-federation/src/connectors/json_selection/methods/public/eq.rs
apollo-federation/src/connectors/json_selection/methods/public/mod.rs

Promoting connectors eq method to public
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level logs. Please read [this guidance](https://github.com/apollographql/router/blob/dev/de …

Promoting connectors eq method to public

---

.changesets/fix_bnjjj_add_operation_name_subscription_metric.md
.changesets/fix_bnjjj_fix_coprocessor_subscription.md
.changesets/fix_caroline_telemetry_http_route.md
CHANGELOG.md
Cargo.lock
apollo-federation/Cargo.toml
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.template.toml
apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.jaeger.yml
docs/shared/k8s-manual-config.mdx
helm/chart/router/Chart.yaml
helm/chart/router/README.md
scripts/install.sh
xtask/src/commands/release.rs

> **Note**
>
> When approved, this PR will merge into **the `1.61.8` branch** which will — upon being approved itself — merge into `main`.
>
>  - That it targets the right release branch (`1.61.8` in this case!).
>
---

prep release: v1.61.8

---

apollo-federation/src/connectors/mod.rs
apollo-federation/src/connectors/runtime.rs
apollo-federation/src/connectors/runtime/inputs.rs
apollo-router/src/plugins/connectors/handle_responses.rs
apollo-router/src/plugins/connectors/make_requests.rs
apollo-router/src/plugins/connectors/mod.rs

passing context to a-f code is handled by a trait
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level logs. Please read [this …

move request input and variable merging into apollo-federation

---

.changesets/docs_jr_add_all_in_one_container_docs.md
docs/source/routing/self-hosted/index.mdx

Updates the documentation to add reference to the new all-in-one container

BGS-351 Add reference to All-In-One Container

---

Cargo.lock
apollo-router/src/configuration/tests.rs

Add mock env var for new sigv4 test

---

docs/source/routing/security/jwt.mdx

---
**Checklist**
**Exceptions**
**Notes** …

fix table layout in jwt docs

---

docs/source/routing/self-hosted/containerization/kubernetes/other-considerations.mdx

From internal conversations this came up with another customer recently. 
Internal Apollo Only can read more here: https://apollograph.slack.com/archives/C02UX05LF4K/p1730322335560069

[docs] Add note about termination period for shutdown

---

apollo-router/src/plugins/response_cache/tests.rs

Fixes currently broken test in dev.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level logs. Please read [this guidance](https://github.com/apollographql/router/blob/dev/dev-doc …

Include cleanup_interval in tests

---

apollo-federation/src/connectors/json_selection/methods.rs
apollo-federation/src/connectors/json_selection/methods/public/mod.rs
apollo-federation/src/connectors/json_selection/methods/public/parse_int.rs

---
**Checklist**
**Exceptions**
**Notes** …

Add connectors `->parseInt` method

---

apollo-router/src/plugin/test/mock/connector.rs
apollo-router/src/plugin/test/mock/mod.rs
apollo-router/src/plugin/test/mod.rs
apollo-router/src/plugins/connectors/handle_responses.rs
apollo-router/src/plugins/connectors/make_requests.rs
apollo-router/src/plugins/headers/mod.rs
apollo-router/src/plugins/telemetry/config_new/connector/events.rs
apollo-router/src/plugins/telemetry/config_new/connector/selectors.rs
apollo-router/src/plugins/telemetry/config_new/fixtures/connector/custom_counter_with_conditions/test.yaml
apollo-router/src/plugins/telemetry/config_new/fixtures/connector/custom_histogram/test.yaml
apollo-router/src/plugins/telemetry/config_new/fixtures/connector/http_client_request_duration/test.yaml
apollo-router/src/plugins/telemetry/config_new/fixtures/connector/mapping_problems/test.yaml
apollo-router/src/plugins/telemetry/config_new/fixtures/connector/subgraph_and_connector/test.yaml
apollo-router/src/plugins/telemetry/config_new/fixtures/schema.json
apollo-router/src/plugins/telemetry/config_new/instruments.rs
apollo-router/src/plugins/telemetry/fmt_layer.rs
apollo-router/src/plugins/traffic_shaping/mod.rs
apollo-router/src/services/connector/request_service.rs
apollo-router/src/services/connector_service.rs

Trying to simplify response mapping so it'll be easier to share with another project.
[CNN-926]: https://apollographql.atlassian.net/browse/CNN-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Clean up dead/unused Connectors code.

---

.changesets/fix_bnjjj_rh_924.md
CHANGELOG.md
Cargo.lock
apollo-federation/Cargo.toml
apollo-router-benchmarks/Cargo.toml
apollo-router-scaffold/Cargo.toml
apollo-router-scaffold/templates/base/Cargo.template.toml
apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
apollo-router/Cargo.toml
dockerfiles/tracing/docker-compose.jaeger.yml
docs/shared/k8s-manual-config.mdx
helm/chart/router/Chart.yaml
helm/chart/router/README.md
licenses.html
scripts/install.sh

> **Note**
> **This particular PR must be true-merged to `1.x`.**
* This PR is only ready to review when it is marked as "Ready for Review".  It represents the merge to the `1.x` branch of an upcoming release (version number in the title).
* We may cut any number of alpha and release candidate (RC) versions off this branch prior to formalizing it.
- Does this PR target the right branch? (usually, `1.x`)
- Are the appropriate **version bumps** and **release note …

release: v1.61.10

---

apollo-router/src/uplink/license_enforcement.rs
apollo-router/src/uplink/snapshots/apollo_router__uplink__license_enforcement__test__restricted_features_via_config.snap
apollo-router/src/uplink/testdata/restricted.router.yaml

---
**Checklist**
**Exceptions**
**Notes** …

response_cache: entitlements

---

apollo-router/src/uplink/license_enforcement.rs
apollo-router/src/uplink/snapshots/apollo_router__uplink__license_enforcement__test__restricted_features_via_config.snap
apollo-router/src/uplink/testdata/restricted.router.yaml

---
**Checklist**
**Exceptions**
**Notes** …

response_cache: entitlements (backport #7988)

---

.changesets/fix_tylerb_fed_644.md

This PR adds a missing changelog entry for PR #7929.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level logs. Please read [this …

Added a changelog entry for #7929 (backport #7983)

---

apollo-federation/src/connectors/id.rs
apollo-federation/src/connectors/mod.rs
apollo-router/src/plugins/connectors/handle_responses.rs
apollo-router/src/plugins/connectors/tests/content_type.rs
apollo-router/src/plugins/connectors/tests/error_handling.rs
apollo-router/src/plugins/connectors/tests/mod.rs
apollo-router/tests/samples/enterprise/connectors-debugging/plan.json

---
**Checklist**
**Exceptions**
**Notes** …

Removes @connect from connector coordinate

---

apollo-federation/src/connectors/json_selection/apply_to.rs
apollo-federation/src/connectors/json_selection/parser.rs

Before we had the `...` spread syntax (merged recently in #7957 but not yet released), it was possible to spread multiple object properties into a larger object by using an anonymous path with a trailing `SubSelection` (formerly called a `PathWithSubSelection` in the grammar) as a `NamedSelection`, alongside other `NamedSelection` elements in a `SubSelection`, like so:
```graphql
id
created
model
choices->first.message { role content }
```
Now that we have the `...` syntax, this selection can (and probably should) be written
```graphql
id
created
model
... choices->first.message { role content }
```
For backwards compatibility, we need to preserve the old `PathWithSubSelection` syntax for now, though we probably want to encourage using an explicit `...`, because it makes the selection …

Fix (and more thoroughly test) JSONSelection single-path parsing regression in connect/v0.3

---

apollo-federation/src/connectors/json_selection/apply_to.rs

Follow-up to #8082.
Since the final operand in `$(missing ?? null)` does not have a `??` operator _after_ it, I believe a final `null` value should be returned as-is, rather than getting mapped to `None`. The current behavior ends up returning `None` for the whole expression when the last operand evaluates to `null`, due to the loop logic for handling chains of `??` operator(s).
At a more intuitive level, if `$(possibly_missing ?? any_default)` becomes our standard idiom for default values, we shouldn't have to explain/maintain the exception that `any_default` can be anything _except_ `null` specifically when you're using a chain of `??` operators (but can be `null` when you're using `?!`). With this commit, any `any_default` result counts as successful as long as it's not `None`.

Allow `null` as successful default in `$(missing ?? null)`

---

apollo-federation/src/schema/schema_upgrader.rs

Reverts apollographql/router#8101

Revert "fix(composition): fix check for root type extensions"

---

apollo-federation/src/connectors/expand/tests/snapshots/connectors@batch.graphql.snap
apollo-federation/src/connectors/expand/tests/snapshots/connectors@carryover.graphql.snap
apollo-federation/src/connectors/expand/tests/snapshots/connectors@interface-object.graphql.snap
apollo-federation/src/connectors/expand/tests/snapshots/connectors@keys.graphql.snap
apollo-federation/src/connectors/expand/tests/snapshots/connectors@nested_inputs.graphql.snap
apollo-federation/src/connectors/expand/tests/snapshots/connectors@normalize_names.graphql.snap
apollo-federation/src/connectors/expand/tests/snapshots/connectors@realistic.graphql.snap
apollo-federation/src/connectors/expand/tests/snapshots/connectors@sibling_fields.graphql.snap
apollo-federation/src/connectors/expand/tests/snapshots/connectors@simple.graphql.snap
apollo-federation/src/connectors/expand/tests/snapshots/connectors@steelthread.graphql.snap
apollo-federation/src/connectors/expand/tests/snapshots/connectors@types_used_twice.graphql.snap
apollo-federation/src/connectors/mod.rs
apollo-federation/src/connectors/models.rs
apollo-federation/src/connectors/runtime/cache.rs
apollo-federation/src/connectors/snapshots/apollo_federation__connectors__models__tests__from_schema_v0_2.snap
apollo-router/src/plugins/connectors/handle_responses.rs
apollo-router/src/plugins/connectors/make_requests.rs
apollo-router/src/plugins/connectors/tracing.rs
apollo-router/src/plugins/headers/mod.rs
apollo-router/src/plugins/telemetry/config_new/connector/events.rs
apollo-router/src/plugins/telemetry/config_new/connector/selectors.rs
apollo-router/src/plugins/telemetry/config_new/instruments.rs
apollo-router/src/plugins/telemetry/fmt_layer.rs
apollo-router/src/plugins/traffic_shaping/mod.rs
apollo-router/src/services/connect.rs
apollo-router/src/services/connector/request_service.rs

---
**Checklist**
**Exceptions**
**Notes** …

add fetch operation type and output/entity type to cache key components

---

apollo-router/src/plugins/fleet_detector.rs

[FLEET-305]
---
The router will only track certain deployment_types inside of the fleet awareness metrics. This PR sets the correct valid values for this metric type.
**Checklist**
**Exceptions**
This is a change to the metrics collected for fleet awareness, which do not impact users.
**Notes** …

ensure deployment type metric is bound to certain values

---

Cargo.lock
apollo-router/Cargo.toml

Also update the dev dependency. See #8177 
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level logs. Please read [this …

deps: RUSTSEC-2025-0055 Update tracing-subscriber

---

docs/source/routing/configuration/yaml.mdx
docs/source/routing/customization/overview.mdx
docs/source/routing/graphos-features.mdx
docs/source/routing/operations/file-upload.mdx
docs/source/routing/security/request-limits.mdx

---
Updates documentation to reflect feature tiering changes made in the [recent router release](https://github.com/apollographql/router/releases/tag/v2.6.0).
References:
- [Product's feature tiering matrix](https://docs.google.com/document/d/13wh3NBmBnSPKBCH1f19eir-caWbz6Y9wKEHItXq6l1c/edit?tab=t.7kwmpu4gs3p#heading=h.37ncslwgnmfs)
- [Additional feedback from product](https://docs.google.com/document/d/1ea30pyaIAaBg4xTUXuUDDa3w16fhhR7KvEm3QQNE-D8/edit?tab=t.pyvj315sx3ne#heading=h.gx3p2h7ez2ov)
Ran the docs site locally using `librarian.local.config.mts` file  with override for the `router`  repository.
Specifically, the following pages were checked:
- http://localhost:3000/docs/graphos/connectors/reference/directives
- http://localhost:3000/docs/graphos/routing/customization/overview
- …

Update license requirements in docs

---

docs/source/routing/customization/coprocessor/reference.mdx

update docs on coprocessor execution service

[docs] Update ExecutionRequest header and add details

---

Cargo.lock
about.toml
apollo-router/Cargo.toml
apollo-router/src/configuration/schema.rs
apollo-router/src/configuration/tests.rs
apollo-router/src/configuration/yaml.rs
deny.toml

Builds on and closes #6500
@Stranger6667 contributed an update of the jsonschema crate, which we're using a very old version of. This PR rebases that change on top of dev.
---
**Checklist**
- <strike>Changeset is included for user-facing changes</strike>
- <strike>Documentation[^2] completed</strike>
- <strike>Metrics and logs are added[^3] and documented</strike>
- <strike>Integration tests</strike>
- <strike>Manual tests, as necessary</strike> …

deps: update jsonschema

---

apollo-federation/src/connectors/json_selection/apply_to.rs

In PR #8221 I pushed down the blanket check for `input_shape.is_none()` at the beginning of `PathList::compute_output_shape`, so it now occurs only for variants that require access to the input shape, like `PathList::Key` and `PathList::Method`, while also allowing `$variable` evaluation and the `$(...)` syntax even when given a `None` input shape, since those `PathList` variants do not necessarily have to use the input shape. I still stand by the general idea of this change.
Unfortunately, I missed a case where the `None`-termination is still important: we do not want to execute the `SubSelection` of any `Path SubSelection` if the final shape of the `Path` part evaluates to `None`. That was the previous behavior under the blanket check (until #8221, which was merged to `dev` last week …

[JSONSelection] Fix regression: skip processing `SubSelection` when `input_shape` is `None`
