apollographql/router

- .changesets/maint_geal_always_create_traffic_shaping.md
- apollo-router/src/plugins/expose_query_plan.rs
- apollo-router/src/router_factory.rs
- apollo-router/src/services/supergraph_service.rs
Fix #3327
that plugin is always part of the plugins list and should always be active, with default configuration
**Checklist**
**Exceptions**
**Notes**
- please document the manual testing …
> always instantiate the traffic shaping plugin

- .changesets/feat_garypen_2467_rhai_method.md
- apollo-router/src/plugins/rhai/engine.rs
- apollo-router/src/plugins/rhai/tests.rs
- apollo-router/tests/fixtures/request_response_test.rhai
- docs/source/customizations/rhai-api.mdx
It may be useful to know the method of a request in your Rhai script.
This adds support for getting the method and performing comparisons against String representations.
```
fn process_request(request) {
if request.method == "OPTIONS"  {
request.headers["x-custom-header"] = "value"
}
}
```
Note: You may not modify the method.
fixes: #2467
**Checklist**
**Exceptions**
**Notes**
[^2]. …
> Add support for getting request method in Rhai

- .changesets/fix_geal_defer_label.md
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/services/execution_service.rs
- apollo-router/src/spec/query.rs
- apollo-router/src/spec/query/subselections.rs
- apollo-router/src/spec/query/tests.rs
Fix #3337
With a query contains a deferred fragment, and that deferred fragment containing a non nullable field, like this one:
```graphql
{
a {
b
... @defer {
c
}
}
}
```
If the filter removes that non nullable `c` field, then the filtered query has this shape:
```graphql
{
a {
b
}
}
```
Which will not be deferred, so only one response will be sent, without multipart. This is fine, because the server can decide if something must be deferred or not.
But this was triggering issues in response formatting, because response formatting for the original query was working from the original query, with the fragment, but ignoring the `@defer` directive.
Which means that if the response ends up being like this after the filtered query's formatting:
```json
{
"a": {
"b": 1,
}
}
```
It was then …
> fix response formatting with defer and query filtering

- .changesets/feat_simon_operation_limits_ga.md
- apollo-router/feature_discussions.json
- apollo-router/src/configuration/migrations/0007-parser-recursion.yaml
- apollo-router/src/configuration/migrations/0008-operation-limits-ga.yaml
- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__upgrade_old_configuration@operation-limits-preview.yaml.snap
- apollo-router/src/configuration/testdata/migrations/operation-limits-preview.yaml
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/services/router_service.rs
- apollo-router/src/spec/operation_limits.rs
- apollo-router/src/spec/query.rs
- apollo-router/src/uplink/license_enforcement.rs
- apollo-router/src/uplink/snapshots/apollo_router__uplink__license_enforcement__test__restricted_features_via_config.snap
- apollo-router/src/uplink/testdata/oss.router.yaml
- apollo-router/src/uplink/testdata/restricted.router.yaml
- apollo-router/tests/integration_tests.rs
- apollo-router/tests/operation_limits.rs
- apollo-router/tests/snapshots/lifecycle_tests__cli_config_preview.snap
- docs/source/config.json
- docs/source/configuration/operation-limits.mdx
- docs/source/configuration/overview.mdx
[Operation Limits](https://www.apollographql.com/docs/router/configuration/operation-limits) (a GraphOS Enterprise feature) and [parser limits](https://www.apollographql.com/docs/router/configuration/overview/#parser-based-limits) are now moving to General Availability, from Preview where they have been since Apollo Router 1.17.
For more information about launch stages, please see the documentation here: https://www.apollographql.com/docs/resources/product-launch-stages/
In addition to removing the `preview_` prefix, the configuration section has been rename to just `limits` to reflect that it concerns not only operations but also the parser and the requests. ([The request size limit](https://www.apollographql.com/docs/router/configuration/overview/#request-limits) is still …
> Move operation limits and parser limits to General Availability

- .changesets/maint_geal_busy_timer_guard.md
- apollo-router/src/context/mod.rs
- apollo-router/src/plugins/coprocessor.rs
- apollo-router/src/services/subgraph_service.rs
manually tracking active requests is error prone because we might return early without decrementing the active requests. To make sure this is done properly, `enter_active_request` now returns a guard struct, that will decrement the count on drop
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part of many changes. Where applicable please try to document …
> use a Drop guard to track active requests

- .changesets/fix_capsule_add_skull_sail.md
- apollo-router/src/axum_factory/utils.rs
- apollo-router/src/context/mod.rs
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
- apollo-router/src/query_planner/subscription.rs
- apollo-router/src/services/layers/query_analysis.rs
- apollo-router/tests/common.rs
- apollo-router/tests/jaeger_test.rs
- apollo-router/tests/lifecycle_tests.rs
- apollo-router/tests/metrics_tests.rs
- apollo-router/tests/snapshots/tracing_tests__traced_basic_composition.snap
- apollo-router/tests/snapshots/tracing_tests__traced_basic_request.snap
- apollo-router/tests/snapshots/tracing_tests__variables.snap
- apollo-router/tests/subscription_load_test.rs
- apollo-router/tests/telemetry_test.rs
https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/instrumentation/graphql/
Root span name has changed from request to `<graphql.operation.kind> <graphql.operation.name>`
Fixes #3229
**Checklist**
**Exceptions**
**Notes**
[^3]. Tick whichever testing boxes …
> Bring root span name in line with otel semantic conventions.

- .changesets/maint_geal_remove_compiler_from_query.md
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/query_planner/caching_query_planner.rs
- apollo-router/src/services/execution.rs
- apollo-router/src/services/layers/query_analysis.rs
- apollo-router/src/services/query_planner.rs
- apollo-router/src/services/router_service.rs
- apollo-router/src/services/supergraph.rs
- apollo-router/src/services/supergraph_service.rs
- apollo-router/src/spec/query.rs
- apollo-router/src/spec/query/tests.rs
Fix #3373 
we don't really need to carry the compiler inside that object, since it is now cached at the query analysis layer. We also should not carry it in the supergraph request and execution request, because that makes the builders hard to manipulate for plugin authors. Since we are not exposing the compiler in the public API yet, we move it inside the context's private entries, where it will be easily accessible from internal code.
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for …
> remove the compiler from Query

- Cargo.lock
- apollo-router/Cargo.toml
Update to 0.3.0, as 0.2.9 was yanked. The release for 0.2.9 had a breaking change which caused issues when compiling stable router versions
> Update router-bridge version

- .changesets/maint_avery_update_and_pin_bridge.md
- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/services/supergraph_service.rs
Updates `router-bridge` from ` = "0.3.0+v2.4.8"` to ` = "=0.3.1+v2.4.9"`, note that with this PR, this dependency is now pinned to an exact version. This version update started failing tests because of a minor ordering change and it was not immediately clear why the test was failing. Pinning this dependency (that we own) allows us to only bring in the update at the proper time and will make test failures caused by the update to be more easily identified.
This was done once before in #2916 but it is fairly easy to forget to pin something when updating. To mitigate this, I've added a comment to the `Cargo.toml` and also a unit test that parses `Cargo.toml` and makes sure `router-bridge` contains an `=` to pin it.
**Checklist**
Complete the checklist (and note appropriate exceptions) before …
> chore: router-bridge 0.3.0+v2.4.8 -> =0.3.1+2.4.9

- .changesets/maint_geal_move_post_mutation_layer.md
- apollo-router/src/services/execution_service.rs
- apollo-router/src/services/layers/allow_only_http_post_mutations.rs
- apollo-router/src/services/supergraph_service.rs
Now that we have access to a compiler in supergraph requests, we don't need to look into the query plan to know if a request contains mutations
**Checklist**
**Exceptions**
**Notes**
- …
> move AllowOnlyHttpPostMutationsLayer at the supergraph service level

- apollo-router/src/axum_factory/snapshots/apollo_router__axum_factory__tests__defer_is_not_buffered.snap
- apollo-router/src/plugins/traffic_shaping/cache.rs
- apollo-router/src/query_planner/fetch.rs
- apollo-router/src/services/snapshots/apollo_router__services__supergraph_service__tests__missing_entities.snap
- apollo-router/src/services/supergraph_service.rs
Removed error added if subgraph response did not include entities. Instead a warning is raised in the logs.
Fixes #3402
**Checklist**
**Exceptions**
**Notes**
- please document the manual …
> Don't add an error if subgraph response is missing `_entities`.

- .changesets/feat_garypen_metrics_as_delta.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/telemetry/metrics/otlp.rs
- apollo-router/src/plugins/telemetry/otlp.rs
Add a new configuration option (Temporality) to the otlp metrics configuration.
This may be useful to fix problems with metrics when being processed by datadog which tends to expect Delta, rather than Cumulative, aggregations.
See:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6129
- https://github.com/DataDog/documentation/pull/15840
for more details.
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as …
> add support for delta aggregation to otlp metrics

- .changesets/docs_geal_document_claim_augmentation.md
- docs/source/configuration/authn-jwt.mdx
Fix #3102
We documented plugin ordering guarantees in #3321, but it is worth calling out how ordering works between authentication and coprocessors, as claims augmentation is a common use case
**Checklist**
**Exceptions**
**Notes**
[^3]. Tick whichever testing boxes are …
> document claim augmentation via coprocessors

- .changesets/maint_simon_uncolliding_relabel.md
- apollo-router/src/query_planner/labeler.rs
- apollo-router/tests/integration_tests.rs
- apollo-router/tests/snapshots/integration_tests__include_if_works.snap
The `@defer` directive accepts a `label` argument, but it is optional. To more accurately handle deferred responses, the Router internally rewrites queries to add labels on the `@defer` directive where they are missing. Responses eventually receive the reverse treatment to look as expected by client.
This was done be generating random strings, handling collision with existing labels, and maintaining a `HashSet` of which labels had been synthesized. Instead, we now add a prefix to pre-existing labels and generate new labels without it. When processing a response, the absence of that prefix indicates a synthetic label.
> Fix: only add label arguments on defer directives

- .changesets/maint_igni_coprocessor_idle_timeout_duration.md
- apollo-router/src/plugins/coprocessor.rs
Having a too high idle pool timeout durations can sometimes trigger situations in which an HTTP request cannot complete (see [this comment](https://github.com/hyperium/hyper/issues/2136#issuecomment-589488526) for more information).
This changeset sets a default timeout duration of 5 seconds, which we may make configurable eventually.
> Coprocessor: Set a default pool idle timeout duration.

- .changesets/fix_federation_fragments.md
- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/services/supergraph_service.rs
PR #3453 Incorrectly defaulted reuse query fragments to off. This is now controlled by federation.
**Checklist**
**Exceptions**
**Notes**
- please document the manual testing (extensively) …
> Modify ``reuse_query_fragments` to allow federation to decide to default on or off

- .changesets/feat_garypen_3345_pdb.md
- helm/chart/router/templates/pdb.yaml
- helm/chart/router/values.yaml
Example Configuration:
```yaml
podDisruptionBudget:
minAvailable: 1
```
fixes: #3345
**Checklist**
**Exceptions**
**Notes** …
> Add support for PodDisruptionBudget to helm chart

- docs/source/configuration/apollo-telemetry.mdx
An edge case was reported by a customer and this was uncovered in Slack
> [docs] Update apollo-telemetry to mention that FTV1 is required for errors

- docs/source/configuration/traffic-shaping.mdx
This PR adds some clarification around timeout configuration in https://github.com/apollographql/router/pull/3456.
Fixes https://github.com/apollographql/router/issues/3441
**Checklist**
**Exceptions**
**Notes** …
> Clarify timeout options

- .changesets/maint_garypen_3435_reuse_hyper_pool.md
- apollo-router/src/services/subgraph_service.rs
Having a high idle pool timeout duration can sometimes trigger situations in which an HTTP request cannot complete (see [this comment](https://github.com/hyperium/hyper/issues/2136#issuecomment-589488526) for more information).
This changeset sets a default timeout duration of 5 seconds, which we may make configurable eventually.
fixes: #3435
**Checklist**
**Exceptions**
**Notes**
[^2]. …
> Add a pool idle timeout for subgraph HTTP connectors

- CHANGELOG.md
Removes (inactive) docs link and clarifies that persisted queries is a forthcoming feature.
**Checklist**
**Exceptions**
**Notes** …
> Remove persisted docs from changelog

- .changesets/feat_garypen_177_coprocessor_metrics.md
- apollo-router/src/plugins/coprocessor.rs
- docs/source/configuration/metrics.mdx
Introduces a new metric for the router:
```
apollo.router.operations.coprocessor
```
It has two attributes:
```
coprocessor.stage: string (RouterRequest, RouterResponse, SubgraphRequest, SubgraphResponse)
coprocessor.succeeded: bool
```
**Checklist**
**Exceptions**
Ran a router with all coprocessor stages enabled and prometheus enabled. Sent in a request to generate a success metric. Then stopped the coprocessor and sent in another request to generate a fail metric. Examined the prometheus metrics to ensure they were as expected. e.g.:
```
apollo_router_operations_coprocessor_total{coprocessor_stage="RouterRequest",coprocessor_succeeded="false",service_name="apollo-router",ot …
```
> Add coprocessor metrics

- .changesets/fix_bnjjj_fix_subscription_metrics.md
- apollo-router/src/plugin/test/mock/canned.rs
- apollo-router/src/plugins/telemetry/metrics/apollo.rs
- apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_for_subscription_error.snap
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/src/services/router.rs
- apollo-router/src/services/supergraph_service.rs
- apollo-router/src/uplink/license_enforcement.rs
- apollo-router/src/uplink/snapshots/apollo_router__uplink__license_enforcement__test__restricted_features_via_config.snap
- apollo-router/testing_schema.graphql
Fix the error count for subscription requests for apollo telemetry
> Fix the error count for subscription requests for apollo telemetry

- .changesets/feat_add_helm_init_containers.md
- helm/chart/router/templates/deployment.yaml
- helm/chart/router/values.yaml
*The init container option created in the router's helm chart*
Feature  #3248
> Feat: Add init containers options to helm chart

- .changesets/maint_contract_fiancee_ark_grey.md
- apollo-router/src/services/layers/persisted_queries/manifest_poller.rs
- apollo-router/src/services/layers/persisted_queries/mod.rs
Ideally we don't use panic ever in non-test code. In addition, if we can get away with expect then we should do so rather than if let panic.
For locks there's no benefit from passing the supplied message to the expect as the message is hard coded to something like `lock poisoned`.
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part of many changes. Where applicable …
> (chore) Remove some panic! calls from the pq code

- .changesets/maint_bnjjj_caching_metrics.md
- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/telemetry/config.rs
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
- apollo-router/src/plugins/traffic_shaping/cache.rs
- apollo-router/src/plugins/traffic_shaping/mod.rs
I added a metric only if we enable that feature setting `telemetry.metrics.common.experimental_enable_cache_metrics` to `true`. It will generate metrics to better where and which data would benefit from caching.
example
```
apollo_router_operations_entity_cachable_bucket{entity_type="Product",service_name="apollo-router",subgraph="products",vary="",otel_scope_name="apollo/router",otel_scope_version="",le="0.05"} 0
apollo_router_operations_entity_cachable_bucket{entity_type="Product",service_name="apollo-router",subgraph="products",vary="",otel_scope_name="apollo/router",otel_scope_version="",le="0.1"} 0
apollo_router_operations_entity_cachable_bucket{entity_type="Product",service_name="apollo-router",subgraph="products",vary="",otel_scope_name="apollo/router",otel_scope_version="",le="0.25 …
```
> add experimental caching metrics

- .changesets/maint_rhubarb_waterfront_notebook.md
- apollo-router/src/executable.rs
- apollo-router/src/plugin/mod.rs
If users plugins are detected and logging either hasn't been configured then emit a log message stating that user logs be be being silenced and point them towards what they need to do to configure their logging.
Fixes #3526
**Checklist**
**Exceptions**
**Notes**
[^3]. Tick …
> Add a message to the logs indicating when custom plugins are detected and there is a possibility that log entries may be silenced

- .changesets/maint_garypen_3533_istio_warn.md
- apollo-router/src/uplink/mod.rs
- docs/source/containerization/kubernetes.mdx
We have encountered situations where the injection of istio-proxy in a router pod (executing in kubernetes) causes strange networking errors during uplink retrieval.
The root cause of the issue is that the router is executing and attempting retrieve uplink schemas whilst the istio-proxy is modifying network configuration at the same time.
This warning message will direct users to information which should help them to configure their cluster or pod to avoid this problem.
fixes: #3533
**Checklist**
~~- [ ] Unit Tests~~
~~- [ ] Integration Tests~~
**Exceptions**
This is difficult to test, since the root cause (istio networking re-configuration as the pod executes) is very …
> add a warning if we think istio-proxy injection is causing problems

- .changesets/feat_geal_coprocessor_latency_metric.md
- apollo-router/src/plugins/coprocessor.rs
- docs/source/configuration/metrics.mdx
Fix #2924 
Introduces a new metric for the router:
```
apollo.router.operations.coprocessor.duration
```
It has one attributes:
```
coprocessor.stage: string (RouterRequest, RouterResponse, SubgraphRequest, SubgraphResponse)
```
It is an histogram metric tracking the time spent calling into the coprocessor
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part of many …
> add a metric tracking coprocessor latency

- .changesets/fix_geal_redis_fixes.md
- apollo-router/src/cache/redis.rs
- apollo-router/src/cache/storage.rs
- apollo-router/src/spec/query/subselections.rs
Fix #3045 
The reconnection policy was using an exponential backoff delay with a maximum number of attempts. Once that maximum is reached, reconnection was never tried again (there's no baseline retry). We change that behaviour by adding infinite retries with a maximum delay of 2 seconds, and a timeout of 1 millisecond on redis commands, so that the router can continue serving requests in the meantime.
This PR contains additional fixes:
- release the lock on the in memory cache while waiting for redis, to let the in memory cache serve other requests
- add a custom serializer for `SubSelectionKey`: this type is used as key in a HashMap, which is converted to a JSON object, and object keys must be strings, so a specific serializer is needed instead of the derived one
**Checklist**
Complete …
> Fix redis reconnections

- .changesets/fix_garypen_3521_keep_listening.md
- apollo-router/src/axum_factory/axum_http_server_factory.rs
- apollo-router/src/http_server_factory.rs
- apollo-router/src/state_machine.rs
We'd like to have more control over the sequencing of server shutdown so that the main (GraphQL) server is required to complete before other servers are shutdown.
This is particularly desirable when the router is executing in Kubernetes, since continuing to report live/ready checks during shutdown is a requirement.
fixes: #3521
**Checklist**
**Exceptions**
Difficult to assess the impact with automated testing. All existing tests pass and I performed manual testing as follows:
1. Run a router
```
cargo run -- -s examples/graphql/local.graphql -c router.yaml --hot-reload
```
Note: Config doesn't matter, I'm just passing one to have a `touch` target. `--hot-reload` is to enable …
> Require the main (GraphQL) server to shutdown before other servers

- .gitleaks.toml
This updates the .gitleaks.toml file in the root of the repo. This file is used to adjust gitleaks configuration when running against this repo. Primarily, this configuration is used to create a repo-local allowlist of detected "secret" values that should be allowed to remain in git history. Usually, this happens if the detected value is not actually a secret or if the detected value was a secret that has since been revoked/rotated.
> Update Gitleaks ignore file

- .changesets/docs_geal_redis_connection_schemes.md
- docs/source/configuration/distributed-caching.mdx
Fix #3534
**Checklist**
**Exceptions**
**Notes**
- please raise a separate issue to automate the test and label it (or …
> document the Redis URL format

- .changesets/maint_igni_dockerfiles_datadog_dependencies.md
- dockerfiles/tracing/datadog-subgraph/Dockerfile
- dockerfiles/tracing/datadog-subgraph/package-lock.json
This changeset updates the dd-trace dependency and the nodeJS version of the example Dockerfile.
> Maint: Update datadog-subgraph npm dependencies

- .changesets/fix_igni_subscriptions_subgraph_ping_pong.md
- apollo-router/src/protocols/websocket.rs
Websocket servers will sometimes send Ping() messages before they Ack the connection initialization. This changeset allows the router to send Pong() messages, while still waiting until either `CONNECTION_ACK_TIMEOUT` elapsed, or the server successfully Acked the websocket connection start.
> Fix: handle ping/pong websocket messages before the Ack message is received.

- .circleci/config.yml
By setting up the remote Docker process _earlier_ in the CircleCI release process, this makes it easier to _use_ that remote Docker instance when doing the "Re-run with SSH" step in CircleCI since  it's _not_ possible to setup the Remote Docker _from_ SSH.  If a step before the Remote Docker step fails to run (thus necessitating the Retry with SSH), then it's impossible to manually finish the release (or even debug) using the SSH console.
(This is a follow-up lesson/todo from a couple past occurrences right now.  Overall, it should be a no-op on the regular happy-path process.)
> chore: Setup Remote Docker in Release process earlier

- .changesets/fix_igni_safely_deal_with_invalid_redis_keys.md
- apollo-router/src/cache/redis.rs
Fix #3594
This changeset returns an error if a value couldn't be serialized before being sent to the redis storage backend.
It also logs the error in console and prompts you to open an issue (This message showing up would be a router bug!).
> Redis storage: return an error if a non serializable value is sent.

- .changesets/docs_abernix_hot_reload_clarify.md
- README.md
- apollo-router/src/executable.rs
- docs/source/configuration/overview.mdx
The supergraph and configuration that is deliverd by Uplink is always delivered to a running Router and will result in a hot-reload.  Files that are provided locally - e.g., `--config ./file.yaml` and `--supergraph ./supergraph.graphql` are ONLY reloaded via file-watching mechanisms if the `--hot-reload` is passed, or if another flag infers `--hot-reload` (as is the case with `--dev`).
> docs: Clarify that hot-reload does not affect Uplink-delivered config/schema

- .changesets/feat_bryn_router_analytics_initial.md
- apollo-router/src/context/mod.rs
- apollo-router/src/plugins/authentication/mod.rs
- apollo-router/src/plugins/subscription.rs
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/src/protocols/websocket.rs
- apollo-router/src/query_planner/execution.rs
- apollo-router/src/query_planner/fetch.rs
- apollo-router/src/services/layers/persisted_queries/mod.rs
- apollo-router/src/services/subgraph_service.rs
- apollo-router/src/services/supergraph_service.rs
- apollo-router/tests/snapshots/tracing_tests__traced_basic_composition.snap
- apollo-router/tests/snapshots/tracing_tests__traced_basic_request.snap
- apollo-router/tests/snapshots/tracing_tests__variables.snap
- licenses.html
Many of our existing metrics are poorly and inconsistently named. In addition they follow prometheus style rather than otel style.
This PR adds some new metrics that will hopefully give us a good foundation to build upon.
New metrics are namespaced `apollo.router.operations.*`.
Until officially documented the metrics should be treated as unstable, as we may need change the names to ensure consistency.
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so …
> Adds some new (unstable) metrics

- renovate.json5
Our own `apollo-` packages deserve to get front-and-center treatment.  This changes them  to be in their own PR — just like router-bridge — to facilitate workflows that surface their changes earlier, and get us dog-fooding them quicker.  (At the very least, become aware of their updates!).
They also have a small proclivity to require more hands-on changes since they're pre-0.x and we use them so extensively, so this will avoid them blocking the other dep bumps landing.
> chore(deps): separate out apollo-rs packages from renovations

- apollo-router/src/query_planner/bridge_query_planner.rs
Instead of having 4 different counters for the different kinds of mismatches, and nothing for correct results, this PR uses a single counter `apollo.router.validation`. It tags the count with a `kind` for schema/operation validation, and a `result`: `match` if the Rust and JS results are the same, otherwise `false_positive` or `false_negative`. With the old count it only reported mismatches, which shouuuuuld never happen, but if this never sends any metrics we don't really know if there is some other issue causing the whole thing to be skipped.
> Tweak metrics for Rust/JS GraphQL validation mismatch

- Cargo.lock
- apollo-router-benchmarks/Cargo.toml
- apollo-router/Cargo.toml
- examples/coprocessor-subgraph/rust/Cargo.toml
- xtask/Cargo.lock
- xtask/Cargo.toml
This tries to aim a majority of the (now very old)
https://github.com/apollographql/router/pull/2665.
However, this intentionally holds back the following from a larger, more
ambitious set of updates which has more work to be done.  The packages held
back are:
- base64
- ecdsa
- tokio-tungstenite
- tonic
- toml
- serde_yaml
- jsonschema
Additional PRs can adjust those deps since they require some more nuanced
changes.  In fact, I even have one of them handy already, but would rather
land this straight update, first.
> chore(deps): Almost a full update of pre-0.x "minor-y" deps

- docs/source/configuration/authn-subgraph.mdx
It appears that the YAML was indented a bit too much causing the YAML itself to be a code-fence (based on markdown indentation rules 🤣 )
Fixes #3619
> docs: Fix incorrect formatting in authn-subgraph.mdx

- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/plugins/authentication/tests.rs
- apollo-router/src/plugins/rhai/engine.rs
- apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
- apollo-router/tests/apollo_reports.rs
This follows up my https://github.com/apollographql/router/pull/3624, which is related to bumping dependencies as is the case with https://github.com/apollographql/router/pull/3628 and https://github.com/apollographql/router/pull/2665 before that.
My previous PR didn't bump some of the dependency changes that required additional changes, but this starts chipping away at that, first with `base64`!
(Also improving my own Rust abilities. ;))
> chore(deps): Update `base64` package

- .changesets/maint_garypen_3587_enable_1_28_0.md
- .circleci/config.yml
Support has now been added for kubernetes `1.28.0` and we can re-enable checking.
This is reverting the change from #3584.
fixes: #3587
**Checklist**
**Exceptions**
**Notes**
- please …
> chore: Enable checking for kubernetes 1.28.0 in kubeconform

- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_bad_type.snap
This follows up my https://github.com/apollographql/router/pull/3624, which
is related to bumping dependencies as is the case with
https://github.com/apollographql/router/pull/3628 and
https://github.com/apollographql/router/pull/2665 before that.
My previous PR didn't bump some of the dependency changes that required
additional changes, but this starts chipping away at that.
This PR updates `jsonschema`
> chore(deps): update jsonschema to 0.17.1

- deny.toml
Part of a fix for #3645
This changeset allows us to keep working on the router while #3643 deals with the issue. Note the initial issue is not critical for the router since operators have agency on which subgraphs they make https requests to.
> Temporarily allow webpki in deny.toml

- .changesets/maint_frog_deejay_motorcar_planetarium.md
- apollo-router/src/plugins/telemetry/metrics/apollo.rs
We're creating an OTLP metrics pipeline to compliment the existing Protobuf based metrics.
This flips the switch to enable this by default.
It uses the existing endpoint, so should require no extra config for users, and will allow us to add useful metrics faster in future.
**Checklist**
**Exceptions**
**Notes**
[^2]. Configuration is an important part of many changes. Where applicable please …
> Enable Apollo OTLP metrics export

- .changesets/maint_geal_authorization_analytics.md
- apollo-router/src/plugins/authorization/authenticated.rs
- apollo-router/src/plugins/authorization/mod.rs
**Checklist**
**Exceptions**
**Notes**
- please raise a separate issue to automate the test and label it (or ask for it …
> add a metric tracking authorization usage

- .changesets/feat_geal_authorization_directives.md
- apollo-router/src/plugins/authorization/authenticated.rs
- apollo-router/src/plugins/authorization/policy.rs
- apollo-router/src/plugins/authorization/scopes.rs
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__authenticated__tests__mutation.snap
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__policy__tests__mutation-3.snap
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__policy__tests__mutation.snap
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__scopes__tests__mutation.snap
Implement authorization directives on operation types
**Checklist**
**Exceptions**
**Notes** …
> Authorization on operations

- .changesets/feat_nicolas_subgraph_fetches.md
- apollo-router/src/query_planner/execution.rs
- apollo-router/src/query_planner/plan.rs
Fixes #3658
**Checklist**
**Exceptions**
**Notes**
Right now, I've set it to take the max possible value for `PlanNode::Condition`. An alternative would be to return the min-max possible values for the number of subgraph fetches instead. Let me know what you folks prefer.
[^2]. Configuration is an important part of many changes. Where applicable please try to document …
> feat(apollo-router): add `QueryPlan.subgraph_fetches`

- .changesets/fix_bryn_redis_cache_miss_log.md
- apollo-router/src/cache/redis.rs
The fred client doesn't seem to deal with nil values correctly, and as opposed to returning an error for `is_not_found` it returns a parse error
Fixes #2876
**Checklist**
**Exceptions**
**Notes**
[^3]. Tick whichever testing boxes are applicable. If you are adding Manual …
> Fred doesn't seem to return an is_not_found error if the record does not exist

- CHANGELOG.md
- docs/source/containerization/docker.mdx
- docs/source/containerization/kubernetes.mdx
- helm/chart/router/README.md
- scripts/install.sh
We have discovered an issue with comment parsing in graphql schema in this release (#3680).
To prevent issues for our users we have decided to yank this release. Users should use 1.27.0 until we fixed the issue and released 1.28.1.
This commit reverts our documentation and also points `install.sh` back to 1.27.0.
> Revert docs for for now-"yanked" v1.28.0

- .changesets/fix_arc_config_mem_leak.md
- apollo-router/src/notification.rs
- apollo-router/src/router_factory.rs
- apollo-router/src/services/supergraph_service.rs
The issue is described in detail here: https://github.com/apollographql/router/issues/3686
This PR uses `Weak` references to `Configuration` inside `Notify`'s broadcast channel. This was causing a memory leak on router reload.
If the `upgrade` in the `subscription_task` is not successful, we cannot update, so it is simply skipped this time, waiting for the next valid configuration broadcast.
I'm not sure what the best way to test this is within the router test suite. Happy to hear suggestions. I've validated it remediates the memory leak issue on our end.
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes …
> Fix memory leak caused by Arc circular reference in `Notify`

- docs/source/customizations/coprocessor.mdx
Fixes `Syntax error in graph` for flowchart in https://www.apollographql.com/docs/router/customizations/coprocessor/#how-it-works
Preview: https://deploy-preview-3694--apollo-router-docs.netlify.app/customizations/coprocessor#how-it-works
> [docs] Fix syntax error in mermaid flowchart for router coprocessor

- CHANGELOG.md
We yanked v1.28.0 due to https://github.com/apollographql/router/issues/3680, but re-published it with https://github.com/apollographql/router/pull/3696 (v1.28.1).
This moves the changelog from 1.28.0 to 1.28.1 where the full contents of the release can be recognized!
> chore: Merge v1.28.0 changelog into v1.28.1

- docs/source/customizations/coprocessor.mdx
Apply fix in https://github.com/apollographql/router/pull/3694 to `main`
> docs: Fix syntax error in mermaid flowchart for router coprocessor in `main`

- CHANGELOG.md
- docs/source/customizations/coprocessor.mdx
This brings two `main` changes to `dev:
- chore: Merge v1.28.0 changelog into v1.28.1 (#3699)
- docs: Fix syntax error in mermaid flowchart for router coprocessor in `main` (#3698)
> Reconcile `dev` after release notes adjustment

- .changesets/fix_bryn_fix_config_metrics.md
- apollo-router/src/configuration/metrics.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@subscriptions.router.yaml.snap
Fix Apollo metrics for detection of subscription callbacks.
Fixes #3687
**Checklist**
**Exceptions**
**Notes**
- please …
> Fix config metrics path and test for subscription callbacks

- .changesets/maint_geal_unneeded_schema_parsing.md
- apollo-router/src/orbiter/mod.rs
- apollo-router/src/state_machine.rs
- apollo-router/src/uplink/license_enforcement.rs
We do not need to parse the schema before license enforcement because it does not use it.
We do not need it either in orbiter because the factory contains the parsed schema
**Checklist**
**Exceptions**
**Notes** …
> remove unneeded schema parsing steps

- .circleci/config.yml
Currently we save caches when running on all branches. In theory this should not happen on any PR as long as dev has been run first. However this is racy and particularly during releases we end up waiting ages for caches to be saved that are never used.
Restrict the saving of caches to dev.
**Checklist**
**Exceptions**
**Notes** …
> Only save CircleCI caches when running against dev

- .changesets/fix_bryn_fix_metrics_typing.md
- apollo-router/src/configuration/metrics.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@apq.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@authorization.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@authorization_directives.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@coprocessor.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@entities.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@limits.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@persisted_queries.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@subscriptions.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@telemetry.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@traffic_shaping.router.yaml.snap
- apollo-router/src/plugins/telemetry/metrics/layer.rs
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/src/query_planner/bridge_query_planner.rs
Metrics attributes were being coerced to strings. This is now fixed.
In addition the logic around the what accepted as metrics attributes has been simplified. It will log and ignore values of the wrong type.
Fixes #3691
**Checklist**
**Exceptions**
**Notes**
[^3]. Tick …
> Fix metrics attribute types

- .changesets/maint_bryn_uplink_client.md
- apollo-router/src/uplink/mod.rs
Previously uplink requests created a new reqwest client each time, this may cause CPU spikes especially on OSX.
Fixes #3333
**Checklist**
**Exceptions**
**Notes**
- please document the …
> Uplink connections now reuse reqwest client

- docs/source/configuration/overview.mdx
- docs/source/configuration/persisted-queries.mdx
This PR adds information about persisted queries router configuration options. The "security levels" or "modes" were already documented, but this adds reference information about the individual options. I've purposefully put them after the modes, since those are likely to be more useful to readers.
I'm targeting `main` since this is only a docs change. LMK if that's not right.
> docs: add persisted query configuration options info

- apollo-router/src/plugins/authentication/mod.rs
- apollo-router/src/query_planner/execution.rs
- apollo-router/src/query_planner/fetch.rs
This fixes a bug where you would encounter error logs: monotonic counter must be u64 or f64. This metric will be ignored.
> Fix monotonic counter type

- .changesets/fix_geal_fix_execution_span_attribution.md
- apollo-router/src/services/execution_service.rs
- apollo-router/tests/snapshots/tracing_tests__traced_basic_composition.snap
- apollo-router/tests/snapshots/tracing_tests__traced_basic_request.snap
Previously, any event in processing would be reported under the supergraph span, or any plugin span (like rhai) happening in between
**Checklist**
**Exceptions**
**Notes** …
> GraphQL response processing must happen under the execution span

- .changesets/fix_geal_remove_clones_from_headers_plugin.md
- apollo-router/src/plugins/headers.rs
Fix #3068 
the operations were cloned for every subgraph query, this is a bit wasteful so we create them only once, and store them under an Arc
**Checklist**
**Exceptions**
**Notes**
- …
> remove clones from the header plugin

- .changesets/docs_fix_broken_links.md
- docs/source/configuration/cors.mdx
- docs/source/customizations/coprocessor.mdx
This PR removes a broken anchor link [reported by Zillow](https://apollograph.slack.com/archives/C0721M2F6/p1693434962231179) and removes some links about authorization directives. (The changes were originally intended to launch with the authorization directive docs. I will revert the changes in [that PR](https://github.com/apollographql/router/pull/3673).)
> docs: fix broken links

- Cargo.lock
- apollo-router/Cargo.toml
This PR removes the `introspector-gadget` dependency from the `Cargo.toml` as I don't believe it's used by this crate anymore. If this passes I think I'd like to deprecate that crate and move it fully back into the Rover repository so it's easier to make changes to its implementation.
> chore: removes unused introspector-gadget crate

- .changesets/fix_dragonfly_ship_win_folder.md
- apollo-router/src/context/mod.rs
- apollo-router/src/services/subgraph_service.rs
This change allows the contexts OPERATION_NAME to be set to None.
> Subscriptions: Correct v1.28.x regression allowing panic via un-named subscription operation

- apollo-router/src/query_planner/fetch.rs
there was always one additional clone before, even when the entity was used in only one place. In local benchmarks, I could see this remove 200μs from a query
**Checklist**
**Exceptions**
**Notes**
[^3]. Tick whichever testing boxes …
> remove a cloned entity from response_at_path

- apollo-router/src/plugins/telemetry/metrics/apollo.rs
Currently apollo metrics may have the same metadata between multiple routers. This means that we can't disambiguate when multiple routers are sending data.
Add a random UUID to the metadata.
This has no user facing impact.
Note: there is no unit test or integration test for this. We need to take a broader look at how we do telemetry testing, and the solution should probably involve otel collector. However that is beyond the scope of this ticket.
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The …
> Add apollo.router.id to otlp metrics metadata

- docs/source/federation-version-support.mdx
Update the [Federation version matrix](https://www.apollographql.com/docs/router/federation-version-support/) in our docs to have ⚠️ indicators as per our convention.
> docs: Update federation-version-support.mdx

- apollo-router/src/configuration/metrics.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@entities.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@traffic_shaping.router.yaml.snap
- apollo-router/src/plugins/authorization/mod.rs
Fix typos:
* timout->timeout
* filtered->authorization.filtered
* needs_authenticated->authorization.authenticated
* needs_requires_scopes->authorization.requires_scopes
**Checklist**
**Exceptions**
**Notes** …
> Fix metrics typos

- apollo-router/src/services/supergraph_service.rs
- apollo-router/src/spec/schema.rs
- apollo-router/src/spec/selection.rs
Followup to #3718, this changeset makes sure we're able to generate the most concrete selection set for a given operation.
This means finding the most concrete type we can when we're dealing with interfaces:
- If InterfaceA implements InterfaceB, use InterfaceA as current_type to generate an inline fragment's selection set
Given the following invariants:
```graphql
interface OperationItemStuff implements OperationItem
```
For
```graphql
fragment OperationItemFragment on OperationItem {
... on OperationItemStuff {
stuff
}
}
```
The most concrete interface to generate fields for `OperationItemStuff` is not `OperationItem`, so we narrow down the selection to `OperationItemStuff`.
The fixes for #3718 still apply, IE:
Given the following invariants:
```graphql
type Dog implements Animal
``` …
> Fix: deal with interface inheritance when retrieving selectionset

- docs/source/configuration/authn-jwt.mdx
- In Rhai, it is `request[.subgraph].body.extensions`, the example was missing the `.body`
- Fix link to rhai example for forwarding headers
**Checklist**
**Notes** …
> docs: fix auth rhai example and link

- CHANGELOG.md
This corrects the CHANGELOG entry for #3586 which inadvertently suggested using `<your_graph_variant>` twice instead of `<your_graph_id>` and (separately) `<your_graph_variant>`:
```
https://studio.apollographql.com/graph/<your_graph_id>/variant/<your_graph_variant>/operations?query=<apollo_operation_id>
```
This doesn't replace the need to document this in https://github.com/apollographql/router/issues/3803. 😄
> Update Changelog for #3586

- .changesets/maint_bnjjj_fix_3740.md
- apollo-router/tests/common.rs
- apollo-router/tests/fixtures/subscription.router.yaml
- apollo-router/tests/subscription_load_test.rs
Add a regression test that ensures an unnamed subscription makes it through the request pipeline.
Fixes #3740
> test(subscription): add integration test for subscription

- .changesets/fix_igni_coprocessors_discard_content_length.md
- apollo-router/src/plugins/coprocessor.rs
- apollo-router/src/plugins/coprocessor_test.rs
- docs/source/customizations/coprocessor.mdx
ControlFlow::Break in coprocessors would lead to all response headers being directly forwarded back to the router, which would lead to content-length missmatch. This changeset discards content-length sent by the coprocessor.
> Coprocessors: Discard content-length sent by coprocessors.

- .github/pull_request_template.md
This has looked pretty funny to me for a while now and the fix was as simple as using `:` instead of `.`!  Inspired by @nathanmarcos doing it as a one-off in https://github.com/apollographql/router/pull/3805. 😸 
I also took the opportunity to add a nice horizontal rule that improves the ascetics of the rendered result and made some other small tweaks to text/formatting.  Most notably though, I removed the suggestion to open a issue labeled `manual test`.  It takes up a lot of real-estate in the text, and not a single issue has been opened or labeled as such. (Nor does the label even exist. 😅 )
> chore: Fix formatting in `pull_request_template.md`

- .gitleaks.toml
This implements additional allowlisting for benign positive "secret" detection. The values allowlisted in this PR are test/sample JWTs and private keys. 
Apologies for repeated PRs on this. These detections appeared after my last PR for allowlisting secrets. I believe that gitleaks (the project we're using to scan for secrets) updated their signatures to better detect JWTs, causing more detections. I've run gitleaks on this repo by hand and after this change, there are currently no additional detections generated. 
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) …
> Additional benign positive allowlisting

- docs/source/configuration/authorization.mdx
- docs/source/enterprise-features.mdx
While I previously used the term "access controls" when describing the authorization directives because it describes both authN (`@authenticated`) and authz, it's better to just use one term ("authorization") across the board if we continue to refer to these as the "authorization directives".
It also fixes a broken link in the authz docs.
> docs: unify authz terminology

- .changesets/fix_renee_fix_large_ints.md
- apollo-router/src/query_planner/labeler.rs
- apollo-router/src/query_planner/snapshots/apollo_router__query_planner__labeler__tests__large_float_written_as_int.snap
- apollo-router/src/spec/query/transform.rs
In GraphQL source text, you can write an integer outside the int32 range if a float is expected. apollo-rs parses these numbers as f64 inside `hir::Value::Int` because at that time, the expected type of the value is not known, especially because it's possible to parse queries without knowledge of the schema.
In the defer label transformation, any apollo-rs `hir::Value::Int` was treated as an i32. This would cause an error if it's one such large integer. The fully proper way to convert `hir::Value` to another type (ie. encoder or serde_json, as is done elsewhere) would be to match on the actual GraphQL type declared by the schema. But the simpler thing to do is to just use a Float if the value is too big for an Int. This will round-trip correctly.
See test for an example that used to fail: …
> Fix error response on large numbers in query transformations

- .changesets/maint_garypen_3663_no_overwrites.md
- .circleci/config.yml
This improves the resilience of our pipeline.
fixes: #3663
---
**Checklist**
**Exceptions**
**Notes**
> Check if docker images and helm charts exist before creating them

- .changesets/feat_bnjjj_fix_3621.md
- apollo-router/src/cache/mod.rs
- apollo-router/src/cache/redis.rs
- apollo-router/src/cache/storage.rs
- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/introspection.rs
- apollo-router/src/plugins/traffic_shaping/mod.rs
- docs/source/configuration/distributed-caching.mdx
It adds a configuration to set another timeout than the default one (2ms) for redis requests. It also change the default timeout to 2ms (previously set to 1ms)
Example for APQ:
```yaml
apq:
router:
cache:
redis:
urls: ["redis://..."] 
timeout: 5ms
```
Fixes #3621
---
**Checklist**
**Exceptions**
**Notes** …
> feat(redis): add configuration to set the timeout

- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/query_planner/caching_query_planner.rs
- apollo-router/src/router_factory.rs
- apollo-router/src/services/router_service.rs
- apollo-router/src/services/supergraph_service.rs
Fix #3766
Cache warm up has been in testing for long enough, and has proven highly ezffective in smoothing out latencies when updating a schema. So this will activate it by default. It can still be deactivated by configuring it to 0:
```yaml
supergraph:
query_planning:
warmed_up_queries: 0
```
By default, it will now warm up the cache with the 30% most used queries
**Checklist**
**Exceptions**
**Notes**
[^1]. It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so …
> Activate query planner cache warm up by default

- .circleci/config.yml
re-enables the CI build pipeline. We'll restore these version checks in the future by reverting this.
> Disable helm check for missing kubernetes versions until supported by kubeconform

- .changesets/feat_garypen_one_shot_async_check.md
- apollo-router-scaffold/templates/plugin/src/plugins/{{snake_name}}.rs
- apollo-router/src/layers/async_checkpoint.rs
- apollo-router/src/layers/mod.rs
- apollo-router/src/plugins/coprocessor.rs
- apollo-router/src/plugins/coprocessor/supergraph.rs
- apollo-router/src/services/layers/allow_only_http_post_mutations.rs
- docs/source/customizations/native.mdx
- examples/async-auth/rust/src/allow_client_id_from_file.rs
The existing AsynCheckpoint requires `Clone` and thus introduces a need for Service Buffering that reduces the performance and resiliance of the router.
This new service set of Services, Layers and utility functions removes the requirement for `Clone` and thus the requirement for service buffering.
Existing uses of AsyncCheckpoint within the router are replaced with OneShotAsyncCheckpoint along with the requirement to `buffer()` such services.
---
**Checklist**
**Exceptions**
**Notes** …
> Introduce OneShotAsyncCheckpoint

- .changesets/fix_geal_fix_studio_reporting2.md
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/src/router_factory.rs
Fix https://github.com/apollographql/router/issues/3871
The sampling filter introduced in
https://github.com/apollographql/router/commit/b58a67c92d65b00c6c11c246e220dce9e2755de1 was making sure that the Apollo exporter was configured when the key is present, but not in the right place: that configuration is used in various places to set up information in the spans and the context, and that is used to create the Studio report and injecting the traces there.
In previous versions, the code was relying on the inject_schema_id function in router_factory.rs to always insert a configuration for the Apollo exporter.
This commit adds back the code that creates that configuration, but only if the Apollo key and graph reference are present
---
**Checklist**
Complete the checklist (and note …
> fix: Studio Reporting when it is not configured

- apollo-router/src/metrics/mod.rs
- apollo-router/src/plugins/telemetry/mod.rs
> improve metrics macros

- .circleci/config.yml
- xtask/src/commands/release.rs
Adds a new `xtask release pre-verify`
Adds a check that the cargo toml matches the local tagged tree.
Fixes #3664
---
**Checklist**
**Exceptions**
**Notes** …
> preverify release version

- apollo-router/src/http_ext.rs
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
- apollo-router/src/services/layers/apq.rs
- apollo-router/src/services/layers/content_negotiation.rs
- apollo-router/src/services/router.rs
- apollo-router/src/services/router_service.rs
- apollo-router/src/services/subgraph_service.rs
`HeaderName::from_static` and `HeaderValue::from_static` can avoid allocations, but we do not get the full benefit from this function by calling them directly in the code: They are const functions, so their result should be stored in a const or static value, then reused elsewhere.
This also removes some unneeded header allocations when handling client name and client version
---
**Checklist**
**Exceptions**
**Notes** …
> fewer header manipulations and allocations

- .changesets/fix_persisted_queries_failover_and_error_handling.md
- apollo-router/src/services/layers/persisted_queries/manifest_poller.rs
- apollo-router/src/test_harness/mocks/persisted_queries.rs
- apollo-router/src/uplink/mod.rs
- apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_transforming_new_response_first_response_transform_fails.snap
If an Uplink request fails, the `stream_from_uplink` function automatically tries the next configured Uplink endpoint. However, in the case of the persisted queries feature, the Uplink response contains an URL located in the same cloud provider as the Uplink endpoint (which is used to fetch the full PQ list chunk). Before this PR, the PQ code fetched this second URL "outside" of `stream_from_uplink`, so an error downloading this file would *not* result in re-trying the Uplink request itself on the next endpoint.
This PR factors out the body of `stream_from_uplink` into `stream_from_uplink_transforming_new_response`, which takes an async function that is called on any `UplinkResponse::New` to transform the response. (`stream_from_uplink` passes the identity function here, so its API is not …
> persisted queries: improve Uplink failover and error handling

- .changesets/maint_bnjjj_fix_3865.md
- apollo-router/src/plugins/telemetry/metrics/layer.rs
Add more supported types for metric counters in `MetricsLayer`.
Now it's not mandatory and won't panic in debug mode if you don't specify `1u64` in this example:
```rust
tracing::info!(
monotonic_counter
.apollo
.router
.operations
.authentication
.jwt = 1,
authentication.jwt.failed = true
)
```
Fixes #3865 
**Checklist**
**Exceptions**
**Notes** …
> fix(telemetry): support more types for metric counters

- .circleci/config.yml
Currently we use medium machines for linux builds. These are underpowered to build the router.
Currently release builds take near 50 minutes without caching.
https://circleci.com/product/features/resource-classes/
Switch to xlarge for release builds.
---
**Checklist**
**Exceptions**
**Notes** …
> Use xlarge machines for linux builds

- .changesets/fix_bryn_move_telemetry.md
- apollo-router/src/axum_factory/axum_http_server_factory.rs
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/tests/common.rs
- apollo-router/tests/metrics_tests.rs
Our metrics are currently mutated at the supergraph service. 
This is a throwback from when the router service did not exist.
Move operation count metrics to the first thing that happens in the pipeline. Note that this won't catch disconnects because they are reliant on the status code of the response, which will stop processing before the metric is incremented.
This also move the creation of the root span to the just after so that cors and extensions are traced.
Fixes #3915
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to …
> Move `apollo.router.operations` to the outer layer of the router pipeline.

- docs/source/executing-operations/subscription-callback-protocol.mdx
In preparation for a GA version of the protocol, both router and subgraphs should specify callback protocol version header in their messages. Also clarifying that subgraph should respond with empty GraphQL data response to the initial callback request.
Related: https://github.com/apollographql/router/issues/3884
> docs: update callback protocol to include headers

- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/telemetry/endpoint.rs
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/src/plugins/telemetry/otlp.rs
- apollo-router/src/plugins/telemetry/tracing/datadog.rs
- apollo-router/src/plugins/telemetry/tracing/jaeger.rs
- apollo-router/src/plugins/telemetry/tracing/mod.rs
- apollo-router/src/plugins/telemetry/tracing/zipkin.rs
We have multiple places in the code that deal with endpoint parsing for otel exporters. 
This PR removes duplicated logic across exporters and adds some tests.
The new types implement default and will allow us to use serde default in a follow up PR.
Part of #3226
---
**Checklist**
**Exceptions**
**Notes** …
> Move processing of endpoints to UriEndpoint and SocketEndpoint

- .changesets/fix_geal_compression_minimal_output_size.md
- apollo-router/src/axum_factory/compression/mod.rs
it should be at least large enough to hold the 10 byte gzip header. Otherwise the compressor goes into an infinite loop
---
**Checklist**
**Exceptions**
**Notes** …
> set a minimal size in the compression output buffer

- docs/source/configuration/distributed-caching.mdx
Docs update to note the Redis cache prefixes per the internal Slack discussion about this as it's come up a few times.
> docs: add note about redis prefixes

- apollo-router/src/services/subgraph_service.rs
until we figure out a fix for: https://github.com/apollographql/router/issues/3998
> disable self-signed certificate tls test

- .changesets/docs_garypen_3838_document_buffering.md
- docs/source/customizations/overview.mdx
Provides specific guidance on request and response buffering within the router.
fixes: #3838
---
**Checklist**
**Exceptions**
**Notes**
> document guidance for request and response buffering

- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/persisted_queries.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__subgraph_override.snap
- apollo-router/src/configuration/tests.rs
- apollo-router/src/context/mod.rs
- apollo-router/src/plugins/authentication/mod.rs
- apollo-router/src/plugins/coprocessor/mod.rs
- apollo-router/src/plugins/subscription.rs
- apollo-router/src/plugins/telemetry/apollo.rs
- apollo-router/src/plugins/telemetry/config.rs
- apollo-router/src/plugins/telemetry/metrics/prometheus.rs
- apollo-router/src/plugins/telemetry/tracing/mod.rs
There are two types of serde defaulting:
* container
* field
Container level defaulting will use an instance of the default implementation and take missing fields from it. Field level defaulting uses either the default implementation or optionally user supplied function to initialize missing fields.
When using field level defaulting it is essential that the Default implementation of a struct exactly match the serde annotations.
A test checks to ensure that field level defaulting is not used in conjunction with a Default implementation and gives guidance on resolution.
Fixes #4000
---
**Checklist**
**Exceptions** …
> Fix defaulting in router config

- .changesets/fix_bryn_fix_coprocessor_stream.md
- apollo-router/src/plugins/coprocessor/supergraph.rs
- apollo-router/src/services/external.rs
- apollo-router/src/services/supergraph.rs
The logic for supporting deferred responses can't work.
The issues is here: [router/apollo-router/src/plugins/coprocessor/supergraph.rs](https://github.com/apollographql/router/blob/cf4a79a126132eb30e368bdf2277a89278ae2a9b/apollo-router/src/plugins/coprocessor/supergraph.rs#L431-L432)
This will always panic as the wrong builder is used for the stage.
Fixes #4013
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to …
> Fix and add test for co-processors handling of streaming responses

- apollo-router/src/plugins/coprocessor/supergraph.rs
- apollo-router/src/services/external.rs
- docs/source/customizations/coprocessor.mdx
Add a new field in SupergraphResponse that can be used to determine when a request has finished.
Fixes #4016
---
**Checklist**
**Exceptions**
**Notes** …
> Add support for has_next in coprocessors `SupergraphResponse`

- .changesets/maint_garypen_4025_helm_docs.md
- .circleci/config.yml
Recent updates to helm-docs mean that the golang on the OS is too old.
Download a version from the golang website and use that.
fixes: #4025 
---
**Checklist**
**Exceptions**
**Notes** …
> use a more modern golang with helm-docs

- .changesets/fix_bryn_prom_differing_descriptions.md
- apollo-router/src/axum_factory/axum_http_server_factory.rs
- apollo-router/src/axum_factory/utils.rs
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/src/services/layers/query_analysis.rs
- apollo-router/tests/common.rs
- apollo-router/tests/metrics_tests.rs
Metrics definitions must match, including descriptions.
Currently we have the same metric scattered across the codebase. This is not ideal, but we are refactoring metrics callsites. 
In the meantime, let's just make things match so that users don't see an error in the logs.
I tries to pull stuff out to consts, but I don't think this is possible without changing the macros, and we don't actually want people to have multiple callsites for metrics. The golden rule is one metric one callsite.
Fixes #4047
> Make all `apollo_router_http_requests_total` metrics match

- docs/source/customizations/rhai.mdx
Until https://github.com/apollographql/router/issues/3642 is resolved and from [prior discussion](https://apollograph.slack.com/archives/C02UX05LF4K/p1695326294453519), document the limitation that a request or response body cannot be accessed from `router_service` callbacks.
Deploy previews:
- Added [new Services limitation](https://deploy-preview-4071--apollo-router-docs.netlify.app/customizations/rhai#services)
> docs: limitation of no request/response body access from router_service

- docs/source/customizations/coprocessor.mdx
This PR fixes a typo in coprocessor.mdx by replacing "excecution" with "execution".
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) …
> Update coprocessor.mdx to fix typo

- .changesets/fix_bryn_fix_metrics_2.md
- apollo-router/src/services/router_service.rs
- apollo-router/tests/common.rs
- apollo-router/tests/fixtures/prometheus.router.yaml
- apollo-router/tests/metrics_tests.rs
There was another instance of a metric that was missed that used the old metrics layer. Update this and add a test
Fixes #4047
---
**Checklist**
**Exceptions**
**Notes** …
> Fix another instance of conflicting metrics definitions.

- .changesets/fix_bryn_fix_metrics_2.md
- CHANGELOG.md
- Cargo.lock
- apollo-router-benchmarks/Cargo.toml
- apollo-router-scaffold/Cargo.toml
- apollo-router-scaffold/templates/base/Cargo.toml
- apollo-router-scaffold/templates/base/xtask/Cargo.toml
- apollo-router/Cargo.toml
- dockerfiles/tracing/docker-compose.datadog.yml
- dockerfiles/tracing/docker-compose.jaeger.yml
- dockerfiles/tracing/docker-compose.zipkin.yml
- helm/chart/router/Chart.yaml
- helm/chart/router/README.md
- licenses.html
- scripts/install.sh
> **Note**
>
> When approved, this PR will merge into **the `1.33.2` branch** which will — upon being approved itself — merge into `main`.
>
>  - That it targets the right release branch (`1.33.2` in this case!).
>
---
Identically _named_ metrics were being emitted for `apollo_router_http_requests_total` (as intended) but with different _descriptions_ (not intended) resulting in occasional, but noisy, log warnings:
```
OpenTelemetry metric error occurred: Metrics error: Instrument description conflict, using existing.
```
The metrics' descriptions have been brought into alignment to …
> prep release: v1.33.2

- apollo-router/src/plugins/telemetry/config_new/attributes.rs
Fix telemetry attribute schema generation
Add a couple of missing attributes.
The new config is skipped right now, but be tested by existing config tests once the config is enabled.
Existing tests will check that the router yaml examples are valid with respect to schema. As the new documentation covers the news schema, it will be tested.
---
**Checklist**
**Exceptions**
**Notes** …
> New telemetry config tweaks

- apollo-router/src/plugins/telemetry/config_new/attributes.rs
- apollo-router/src/plugins/telemetry/config_new/events.rs
- apollo-router/src/plugins/telemetry/config_new/instruments.rs
- apollo-router/src/plugins/telemetry/config_new/snapshots/apollo_router__plugins__telemetry__config_new__attributes__test__extendable_serde.snap
Serde `flatten` doesn't do what we want it to do.
Custom `Deserializer` that will to the right thing, first trying a custom attribute and then a standard attribute.
Part of #3226 
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes …
> Fix serde deserialization for Extendable.

- helm/chart/router/templates/configmap.yaml
- helm/chart/router/templates/hpa.yaml
- helm/chart/router/templates/ingress.yaml
- helm/chart/router/templates/pdb.yaml
- helm/chart/router/templates/secret.yaml
- helm/chart/router/templates/service.yaml
- helm/chart/router/templates/serviceaccount.yaml
- helm/chart/router/templates/serviceentry.yaml
- helm/chart/router/templates/servicemonitor.yaml
- helm/chart/router/templates/supergraph-cm.yaml
- helm/chart/router/templates/tests/test-connection.yaml
- helm/chart/router/templates/virtualservice.yaml
Followup to #4005 , this updates the name where we forgot to, so we can cut an other alpha and deploy the chart.
> Fixup: update helm chart common label to apollographql.

- docs/source/configuration/overview.mdx
Add links to features with config properties that were missing from the [router configuration overview](https://deploy-preview-4141--apollo-router-docs.netlify.app/configuration/overview)
> docs: add links to router configuration overview

- dockerfiles/diy/dockerfiles/Dockerfile.repo
To make debugging easier. Also update from bullseye to bookworm to align with update to rust 1.72.0.
> Add more packages to our diy debug images

- .changesets/fix_nicolas_multi_value_headers.md
- apollo-router/src/plugins/headers.rs
Uses `HeaderMap.append` instead of `insert` to prevent removing values from multi-value headers.
__Note__: This might break implementations that require on a single header value being passed.
Fixes #4153
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick …
> fix: support multi-value headers

- .changesets/fix_geal_authz_filtered_fragments.md
- apollo-router/src/plugins/authorization/authenticated.rs
- apollo-router/src/plugins/authorization/policy.rs
- apollo-router/src/plugins/authorization/scopes.rs
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__authenticated__tests__fragment_fields.snap
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__authenticated__tests__interface_fragment.snap
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__policy__tests__fragment_fields.snap
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__policy__tests__interface_fragment-2.snap
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__policy__tests__interface_fragment.snap
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__scopes__tests__fragment_fields.snap
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__scopes__tests__interface_fragment-2.snap
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__scopes__tests__interface_fragment-3.snap
- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__scopes__tests__interface_fragment.snap
- apollo-router/src/spec/query/transform.rs
Fix #4060
If a fragment was removed, whether because its condition cannot be fulfilled or its selections were removed, then the corresponding fragment spreads must be removed from the filtered query.
This also fixes the error paths related to fragments: before, the path started at the fragment definition, while now the fragment's errors are added at the point of application
---
**Checklist**
**Exceptions**
**Notes** …
> Authorization: Fix fragment filtering

- .changesets/fix_garypen_batch_ordering_fix.md
- apollo-router/src/services/query_batching/testdata/expected_good_response.json
- apollo-router/src/services/router_service.rs
This addresses the bug found in-house testing of experimental batching support.
Fixes #4143
---
**Checklist**
**Exceptions**
**Notes** …
> Remove the first element from the Vec, not the last

- docs/source/configuration/metrics.mdx
- docs/source/configuration/tracing.mdx
The previous location (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md) appears to have changed to https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/README.md.
> docs: update otel conventions link

- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/http_server_factory.rs
- apollo-router/src/lib.rs
- apollo-router/tests/redis_test.rs
Remove some unused crates and convert our redis tests to use the `fred` crate. That means we can remove our dev dependency on the `redis` crate.
This yielded a 1.5% reduction in test build time on my laptop.
Note: This is an exploratory PR, since it's fairly tricky to get unused crates information across multiple platforms with various conditional compilations in play.
---
**Checklist**
**Exceptions**
**Notes** …
> Remove unused crates from the project

- .changesets/config_aaron_allow_custom_healthcheck_endpoint.md
- DEVELOPMENT.md
- apollo-router/src/axum_factory/axum_http_server_factory.rs
- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/configuration/tests.rs
- docs/source/configuration/health-checks.mdx
Adds a configuration option for custom health check endpoints, using `/health` as default
Fixes #2938
---
**Checklist**
**Exceptions**
**Notes** …
> Configuration: allow custom health check endpoint

- RELEASE_CHECKLIST.md
`cargo xtask release prepare` uses some cargo commands and the helm-docs utility, this adds the required dependencies to the release docs.
Most of them you will be warned about when you run the xtask, but `cargo-edit` is not obvious (the error only mentions `set-version` not where to get it).
> List required programs in release checklist

- .changesets/docs_lb_coprocessor_break_router_stages.md
- docs/source/customizations/coprocessor.mdx
The coprocessor RouterRequest and RouterResponse stages fully supports `control: { break: 500 }` but the response body must be a string. This change provides examples in the "Terminating a client request" section.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is an important part of many changes. Where applicable please …
> docs: clarify coprocessor router stage responses

- apollo-router/src/services/subgraph_service.rs
refactoring of subgraph tests to remove redundant parts and use the subgraph request builder where possible. This will remove the need for repetitive change like in https://github.com/apollographql/router/pull/4175
---
**Checklist**
**Exceptions**
**Notes** …
> simplify subgraph tests

- .circleci/config.yml
Sometimes a new release of kubernetes becomes available well in advance of kubeconform support. Because we always use the latest patch release of a kubernetes to validate our Helm files, we can end up with a broken CI pipeline.
This changes the logic so that we always try all of the patch releases for a minor release using the first one we find before moving on to the next minor release. This is fine, since it's more important to keep our CI pipeline working than to be verifying our Helm templates against the very latest patch release of kubernetes.
---
**Checklist**
**Exceptions**
**Notes** …
> Improve the robustness of our kubeconform processing

- .changesets/fix_simon_recursion_limit_default.md
- apollo-router/Cargo.toml
- apollo-router/benches/deeply_nested.rs
- apollo-router/benches/deeply_nested/router.yaml
- apollo-router/benches/deeply_nested/supergraph.graphql
- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/configuration/testdata/metrics/limits.router.yaml
- apollo-router/src/configuration/tests.rs
- docs/source/configuration/overview.mdx
The previous default of 4096 was too high. I can reliable make the Router process (compiled in release mode) abort with a stack overflow with ~2400 nested selection sets.
`deeply_nested.rs` demonstrates it. It as "benchmark" because that’s an easy way to get access to a Router compiled in release mode. It is not run on CI because CI currently does not compile in release mode.
Note that the Router cannot handle response JSON data more nested than 128 levels anyway:`serde_json::Deserializer` has its own recursion limit, hard-coded to 128. It can be disabled (with both run-time *and* compile-time opt-in) but not changed.
Our corpus of 5.3 million operations from customers has 8 entries that use more recursion than the new default.
See also:
* …
> Lower default GraphQL parser recursion limit to 500

- apollo-router/src/plugins/telemetry/config_new/attributes.rs
- apollo-router/src/plugins/telemetry/config_new/extendable.rs
- apollo-router/src/plugins/telemetry/config_new/mod.rs
- apollo-router/src/plugins/telemetry/config_new/spans.rs
- apollo-router/src/plugins/telemetry/dynamic_attribute.rs
- apollo-router/src/plugins/telemetry/fmt_layer.rs
- apollo-router/src/plugins/telemetry/formatters/json.rs
- apollo-router/src/plugins/telemetry/formatters/mod.rs
- apollo-router/src/plugins/telemetry/formatters/text.rs
- apollo-router/src/plugins/telemetry/mod.rs
Only use `LinkedList` and get rid of `HashMap` for the custom attributes.
Fixes #4251 
**Checklist**
**Exceptions**
**Notes** …
> refactor(telemetry): use LinkedList instead of HashMap for custom attributes

- .changesets/fix_garypen_4173_redis_config.md
- apollo-router/src/cache/redis.rs
We have supported additional schemas in our redis configuration for a while, but we never updated our redis connection logic to process the new schemas. This is now fixed.
fixes: #4173
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing …
> Add missing schemas for redis connections

- .changesets/fix_geal_relax_jwks_requirements.md
- apollo-router/src/plugins/authentication/mod.rs
- apollo-router/src/plugins/authentication/tests.rs
- apollo-router/tests/fixtures/jwks-ec-no-alg.json
- apollo-router/tests/fixtures/jwks-no-use.json
- apollo-router/tests/fixtures/jwks-rsa-no-alg.json
Fix https://github.com/apollographql/router/issues/3986
We had a bug where if `use` and `key_ops` are absent, we do not consider a key for verification. As shown in the tests, there is no issue if `alg` is not present, we still detect the key correctly
---
**Checklist**
**Exceptions**
**Notes** …
> Relax JWKS requirements

- apollo-router/tests/fixtures/jaeger-advanced.router.yaml
- apollo-router/tests/fixtures/jaeger-no-sample.router.yaml
- apollo-router/tests/fixtures/jaeger.router.yaml
- apollo-router/tests/jaeger_test.rs
#4102 Introduced some changes to tests that would result in failures if the developer did not have an enterprise account. This is now gated on the appropriate env variables being present.
Changes:
Revert configuration of existing jaeger tests for not use custom span attributes.
Add a new test specifically for this.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is …
> Make Jaeger tests run without APOLLO_KEY and APOLLO_GRAPH_REF

- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/plugins/telemetry/resource.rs
These tests manipulated the environment and thus cannot execute in parallel with each other. The fix forces these tests to execute serially with respect to each other.
fixes: #4067
Note: No changeset as this doesn't have any meaningful user-facing impact.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is an important part of many changes. Where applicable please …
> Remove races in plugins::telemetry::resource::test

- apollo-router/src/plugins/telemetry/mod.rs
Previously it stated a path of: telemetry.span.mode which is incorrect.
---
**Checklist**
**Exceptions**
**Notes** …
> Fix the warning on startup for telemetry.instrumentation.span.mode.

- .changesets/maint_uplink_message_tweaks.md
- apollo-router/src/executable.rs
- apollo-router/src/uplink/mod.rs
- apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_failed_from_single.snap
- apollo-router/src/uplink/snapshots/apollo_router__uplink__test__stream_from_uplink_invalid.snap
Fixes #3877
* Adds a warning on startup if a single URL is provided in `APOLLO_UPLINK_ENDPOINTS`: "Only a single uplink endpoint is configured. We recommend specifying at least two endpoints so that a fallback exists." 
* note that the existing behaviour is preserved if no valid URLs are set - the router fails to start up
* Updates the error messages that is shown if fetches fail to all uplink endpoints from "fetch failed from all endpoints" to either "fetch failed from all N uplink endpoints" or "fetch failed from uplink endpoint, and there are no fallback endpoints configured" depending on how many endpoints are configured
---
**Checklist**
**Exceptions** …
> Improve uplink error/warning messages

- apollo-router/src/plugins/authorization/scopes.rs
- apollo-router/src/plugins/cache/entity.rs
- apollo-router/tests/fixtures/supergraph-auth.graphql
- apollo-router/tests/redis_test.rs
- apollo-router/tests/snapshots/redis_test__test__entity_cache_authorization-2.snap
- apollo-router/tests/snapshots/redis_test__test__entity_cache_authorization-3.snap
- apollo-router/tests/snapshots/redis_test__test__entity_cache_authorization.snap
This builds upon #4208 to use subgraph level authorization status in  the cache key, to split cache entries per authorization contexts
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, …
> Entity cache: link cache and authorization

- deny.toml
We believe this only impacts the router-bridge and we don't do RSA private key related operations in the router-bridge.
> Disable RSA advisory check

- .changesets/fix_garypen_4300_rename.md
- apollo-router/src/plugins/telemetry/apollo_exporter.rs
- deny.toml
- docs/source/configuration/metrics.mdx
Rename from `type` to `report.type` to better comply with OTEL naming conventions.
fixes: #4300
---
**Checklist**
**Exceptions**
**Notes** …
> Rename apollo.router.telemetry.studio.reports type attribute

- Cargo.lock
Contains a fix for a critical regression in 0.7.3. That version was yanked from crates.io but it already made it to our `Cargo.lock` for 1.34.1 and the 1.35.0 release candidate.
This should be part of 1.35.0
> chore(deps): update apollo-parser

- docs/source/containerization/docker.mdx
- docs/source/containerization/kubernetes.mdx
Some of the links on the [kubernetes](https://www.apollographql.com/docs/router/containerization/kubernetes/) and [docker](https://www.apollographql.com/docs/router/containerization/docker/) pages refer to [a configuration page](https://www.apollographql.com/docs/configuration/overview) two levels up resulting in a 404
Quickest way to find one is go to the Kubernetes page and click on `command-line options and YAML configuration`
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do …
> docs(kubernetes/docker): Update relative path for configuration links

- apollo-router/Cargo.toml
They are usually low value: demonstrating basic usage of API that is already execised in parts of other tests. However they are costly since each doctest is compiled as a separate executable that depends on the apollo_router crate. For reasons we don’t fully understand, linking takes a pathologically long time and, especially on Linux, large amount of memory. Many linker running in parallel can run out of memory. For example:
https://app.circleci.com/pipelines/github/apollographql/router/17749/workflows/5e2cd87a-c10b-41b8-900e-e5d517b8abe8/jobs/116288?invite=true#step-116-326592_69
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It …
> Disable running doctests

- .changesets/fix_bryn_span_mode.md
- apollo-router/src/axum_factory/axum_http_server_factory.rs
- apollo-router/src/axum_factory/testdata/span_mode_default.router.yaml
- apollo-router/src/axum_factory/testdata/span_mode_deprecated.router.yaml
- apollo-router/src/axum_factory/testdata/span_mode_spec_compliant.router.yaml
`telemetry.instrumentation.spans.span_mode` was not being correctly applied, resulting in extra request spans that should not have been present in spec compliant mode.
Fixes #4335
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes …
> Fix `telemetry.instrumentation.spans.span_mode`

- apollo-router/src/metrics/aggregation.rs
- apollo-router/src/metrics/mod.rs
When observable metrics are created any callbacks are registered with the metrics pipeline. They are never cleaned up. This means that we may slowly leak memory if this feature is ever used.
Currently the metrics layer does NOT use this and instead calls `observe` directly on gauges. This means that we don't currently leak, but this shouldn't actually work as according to the rust docs for `observe`:
```
Records the state of the instrument.
It is only valid to call this within a callback. If called outside of the registered callback it should have no effect on the instrument, and an error will be reported via the error handler.
```
Fixing this means that we get rid of the thread that is constantly refreshing gauges between exports.
Fixes #4352
---
**Checklist**
Complete the checklist (and …
> Make observable metrics clean up once they are dropped

- docs/source/configuration/authorization.mdx
Updated example `@policy` use case, and added tips choosing `@requiresScopes` vs. `@policy`
Deploy preview: https://deploy-preview-4361--apollo-router-docs.netlify.app/configuration/authorization
> docs: update policy use case example

- .changesets/docs_subgraph_error_inclusion.md
- docs/source/configuration/subgraph-error-inclusion.mdx
- docs/source/configuration/telemetry/apollo-telemetry.mdx
- docs/source/executing-operations/subscription-support.mdx
Update docs sets to link to other info on on why you might not be seeing error message in logs or GraphOS and where you can go to configure those
> [docs] Update subgraph-error-inclusion to link to other docs

- docs/source/customizations/rhai.mdx
As of 1.30.0, Rhai can now access RouterService
> [docs] Update rhai docs to include Router service

- .changesets/docs_bnjjj_fix_4342.md
- docs/source/configuration/telemetry/exporters/logging/overview.mdx
Put back the documentation about `experimental_when_header` configuration for logging.
Fixes #4342
> docs(telemetry): display docs for experimental_when_header

- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/tests/snapshots/tracing_test__traced_basic_composition.snap
- apollo-router/tests/snapshots/tracing_test__traced_basic_request.snap
- apollo-router/tests/snapshots/tracing_test__variables.snap
Here, it'll actually be handled by our analytics infrastructure.
Follow-up for #4159
> Move comparative validation metric into `apollo.router.operations` namespace

- apollo-router/src/configuration/metrics.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__env_metrics.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@apq.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@authorization.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@authorization_directives.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@batching.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@coprocessor.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@defer.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@entities.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@jwt.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@limits.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@persisted_queries.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@sigv4.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@subscriptions.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@telemetry.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@tls.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@traffic_shaping.router.yaml.snap
- apollo-router/src/metrics/aggregation.rs
- apollo-router/src/metrics/filter.rs
- apollo-router/src/metrics/mod.rs
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/src/state_machine.rs
Adds some metrics for some specific apollo env variables to show if they are set or not.
Uses the new metrics macros rather than the hash map to exercise more of the stack.
As a bonus, the thread that was used to continuously update the gauges is gone. 
I had to make some changes to the asserting to allow asserting of all metrics rather than just specific ones hence all the snapshot changes. On the plus side they look better now.
Fixes #4290
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. …
> Adds new metrics for some apollo specific env variables

- .changesets/fix_geal_update_rustls.md
- Cargo.lock
Fix #4305 
replace https://github.com/apollographql/router/pull/4344
In some cases, the router could retry TLS connection indefinitely with an invalid session ticket, making it impossible to contact a subgraph. rustls 0.21.10 contains a fix for that
---
**Checklist**
**Exceptions**
**Notes** …
> Fix TLS session ticket retries

- .changesets/feat_bnjjj_chore_4269.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/subscription.rs
- apollo-router/src/services/subgraph_service.rs
- apollo-router/src/services/supergraph/service.rs
- docs/source/executing-operations/subscription-callback-protocol.mdx
Previously we had an accept header value that could not be compliant with media type RFC so I updated the value to be more like the one we use from client to router with multipart protocol.
I also added the way to display the body even if `content-type` is not accepted.
> fix(callback): change accept header value for callback mode with subscriptions

- .changesets/feat_bryn_supergraph_urls.md
- apollo-router/src/executable.rs
- apollo-router/src/logging/mod.rs
- apollo-router/src/query_planner/snapshots/apollo_router__query_planner__tests__typename_propagation2.snap
- apollo-router/src/router/event/schema.rs
- apollo-router/src/router/event/snapshots/apollo_router__router__event__schema__tests__schema_by_url.snap
- apollo-router/src/router/event/snapshots/apollo_router__router__event__schema__tests__schema_by_url_all_fail.snap
- apollo-router/src/router/event/snapshots/apollo_router__router__event__schema__tests__schema_by_url_fallback.snap
- apollo-router/src/router/event/snapshots/apollo_router__router__event__schema__tests__schema_no_watch.snap
- apollo-router/src/router/event/snapshots/apollo_router__router__event__schema__tests__schema_success_fail_success.snap
- apollo-router/src/uplink/license_stream.rs
- apollo-router/src/uplink/snapshots/apollo_router__uplink__license_stream__test__validate_audience_multiple_filtered.snap
- apollo-router/src/uplink/snapshots/apollo_router__uplink__license_stream__test__validate_audience_single_filtered.snap
APOLLO_ROUTER_SUPERGRAPH_URLS takes a comma separated list of URLs which will be polled in order to try and retrieve the supergraph schema.
The regular `apollo_uplink_poll_interval` is used for duration between polls.
Fixes #4219
---
**Checklist**
**Exceptions**
**Notes** …
> Add support for downloading supergraph schema from a list of URLs.

- .changesets/maint_lb_helm_chart_deprecated_config.md
- helm/chart/router/templates/_helpers.tpl
- helm/chart/router/templates/configmap.yaml
- helm/chart/router/templates/deployment.yaml
- helm/chart/router/templates/service.yaml
- helm/chart/router/values.yaml
This patch updates the generated router config to avoid a "router configuration contains deprecated options" warning on router startup.
I tested this change against the in house router's chart in three ways:
* As it currently is, using the deprecated shape. The results are the same and the router can start up with it.
* Without any telemetry at all. The resulting config no longer contains `telemetry`.
* After updating telemetry configuration to the new structure. The resulting config is correct and the router no longer spits out deprecation warnings.
---
**Checklist**
**Exceptions**
**Notes** …
> fix: update telemetry config in helm chart

- apollo-router/src/spec/query/change.rs
the hasher was assuming only inline fragments under _entities queries, but as an optimisation, named fragments can be reused
---
**Checklist**
**Exceptions**
**Notes** …
> Fix subgraph query hashing with fragment reuse

- apollo-router/src/configuration/metrics.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__env_metrics.snap
Adding dev mode so that we can filter out particularly router developers from our usage metrics.
---
**Checklist**
**Exceptions**
**Notes** …
> Add dev mode to the env metrics reported to apollo.

- apollo-router/src/services/supergraph/snapshots/apollo_router__services__supergraph__tests__fragment_reuse.snap
- apollo-router/src/services/supergraph/tests.rs
As an optimization, query fragments can be reused in subgraph _entities queries, and this case was not handled in some parts of the router
This adds a test for https://github.com/apollographql/router/pull/4387 and https://github.com/apollographql/router/pull/4388 where subgraph query hashing only supported inline fragments
---
**Checklist**
**Exceptions**
**Notes**
[^2]: …
> test fragment reuse

- .changesets/feat_garypen_4370_rhai_request_id.md
- apollo-router/src/plugins/rhai/engine.rs
- apollo-router/src/plugins/rhai/tests.rs
- apollo-router/tests/fixtures/request_response_test.rhai
- docs/source/customizations/rhai-api.mdx
We recently added an ID to Context which uniquely identifies the context for the duration of a request/response lifecycle. This is now accessible on Request or Response objects from Rhai scripts.
For example:
```rhai
// Map Request for the Supergraph Service
fn supergraph_service(service) {
const request_callback = Fn("process_request");
service.map_request(request_callback);
}
// Generate a log for each Supergraph request with the request ID
fn process_request(request) {
print(`request id : ${request.id}`);
}
```
Note: We have chosen to expose this Context data directly from Request/Response objects rather than on the Context object to avoid the possibility of name collisions (with "id") in the context data.
fixes: #4370
---
**Checklist**
Complete the checklist (and note appropriate …
> Expose Context Id to Rhai scripts

- apollo-router/src/query_planner/selection.rs
- apollo-router/src/query_planner/snapshots/apollo_router__query_planner__tests__missing_typename_and_fragments_in_requires2.snap
- apollo-router/src/query_planner/tests.rs
Investigation as a follow up to https://github.com/apollographql/router/commit/4a592f4933b7b9e46f14c7a98404b9e067687f09
If the field we are selecting from is a union, when going into  `execute_selection_set`, `current_type` will be the name of the union. If we already have a `__typename` field, it will be more precise than `current_type` and should be used instead
---
**Checklist**
**Exceptions**
**Notes** …
> use __typename as current type if present in requires selection

- .changesets/maint_igni_update_zerocopy.md
- Cargo.lock
This changeset updates zerocopy to 0.7.31, which has a fix for https://rustsec.org/advisories/RUSTSEC-2023-0074.
> chore: Update zerocopy dependency

- .circleci/config.yml
This changeset makes sure only branches from the apollographql/router repository are elligible for nightlies and releases.
This change is not user facing, I don't think it warrants a changeset.
> chore: Prevent accidental publish CI pipelines to be run

- .circleci/config.yml
Followup to https://github.com/apollographql/router/pull/4419, this makes the circleci file valid on any repository
> create a nightly noop release publish step

- docs/source/configuration/telemetry/exporters/tracing/otlp.mdx
Small documentation change after a customer question around the otel endpoint.
> Add note about otel endpoint param being only the base url

- docs/source/executing-operations/subscription-support.mdx
Fix unformatted bullets in note for HTTP callback setup
> docs: fix formatting of HTTP callback setup note

- .changesets/feat_simon_http_max_request_bytes_ga.md
- apollo-router/feature_discussions.json
- apollo-router/src/configuration/metrics.rs
- apollo-router/src/configuration/migrations/0021-http-max-request-bytes-ga.yaml
- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__upgrade_old_configuration@http_max_request_bytes.router.yaml.snap
- apollo-router/src/configuration/testdata/metrics/limits.router.yaml
- apollo-router/src/configuration/testdata/migrations/http_max_request_bytes.router.yaml
- apollo-router/src/services/router/service.rs
- apollo-router/src/services/router/tests.rs
- apollo-router/tests/fixtures/prometheus.router.yaml
- apollo-router/tests/snapshots/lifecycle_tests__cli_config_experimental.snap
- apollo-router/tests/telemetry/metrics.rs
- docs/shared/router-common-config.mdx
- docs/source/configuration/overview.mdx
- docs/source/containerization/kubernetes.mdx
By default Apollo Router limits the size of the HTTP request body it will read from the network to 2 MB. In this version, the YAML configuration to change the limit is promoted from experimental to general availability.
For more information about launch stages, please see the documentation here: https://www.apollographql.com/docs/resources/product-launch-stages/
Before increasing this limit significantly consider testing performance in an environment similar to your production,
especially if some clients are untrusted. Many concurrent large requests could cause the Router to run out of memory.
Previous configuration will warn but still work:
```yaml
limits:
experimental_http_max_request_bytes: 2000000 # Default value: 2 MB
```
The warning can be fixed by removing the `experimental_` …
> Promote HTTP request size limit from experimental to general availability

- .changesets/fix_bnjjj_fix_metric_name.md
- apollo-router/src/request.rs
- docs/source/configuration/telemetry/instrumentation/standard-instruments.mdx
Rename `apollo_router.operations.batching` to  `apollo.router.operations.batching` because it doesn't follow our conventions with `apollo.router.` prefix.
**Checklist**
**Exceptions**
**Notes** …
> fix(telemetry): use the right conventions for batching metrics

- dev-docs/multipart-subscriptions-protocol.md
Remove the multipart boundary from the client `Accept` header. Typically, the boundary is decided by the server in order to avoid nameclashes with the parts contents. It just happens that `--graphql` works all the time for us because the part contents are JSON.
Keep `--graphql` as a "may" for convenience but mandate that clients support any boundary sent by the server. I _think_ this is already the case for web/ios/kotlin? Ping @alessbell @calvincestari 
ping @bnjjj @abernix
> [multipart-subscriptions-protocol.md] Let the server decide the boundary

- docs/source/configuration/subgraph-error-inclusion.mdx
Fixes links in following sections: 
- https://deploy-preview-4455--apollo-router-docs.netlify.app/configuration/subgraph-error-inclusion#sending-errors-to-graphos
- https://deploy-preview-4455--apollo-router-docs.netlify.app/configuration/subgraph-error-inclusion#logging-graphql-request-errors
> docs: fix broken links 

- .changesets/fix_bryn_fix_datadog_default_url.md
- apollo-router/src/plugins/telemetry/tracing/datadog.rs
- docs/source/configuration/telemetry/exporters/tracing/datadog.mdx
The default URL for the datadog exporter was incorrectly set to `http://localhost:8126/v0.4/traces`
This now matches the default exporter URL of http://127.0.0.1:8126.
https://github.com/open-telemetry/opentelemetry-rust-contrib/blob/main/opentelemetry-datadog/src/exporter/mod.rs#L31
Fixes #4416 
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is an important part …
> Fix the datadog default tracing exporter URL.

- .changesets/feat_bnjjj_feat_4346.md
- apollo-router/src/cache/redis.rs
- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- docs/source/configuration/distributed-caching.mdx
```yaml title="router.yaml"
supergraph:
query_planning:
experimental_cache:
redis: #highlight-line
urls: ["redis://..."] #highlight-line
username: admin/123 # Optional, can be part of the urls directly, mainly useful if you have special character like '/' in your password that doesn't work in url
password: admin # Optional, can be part of the urls directly, mainly useful if you have special character like '/' in your password that doesn't work in url
timeout: 5ms # Optional, by default: 2ms
ttl: 24h # Optional, by default no expiration
```
Fixes #4346
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be …
> feat(redis): add options to set username and password separately

- apollo-router/src/metrics/aggregation.rs
- apollo-router/src/metrics/filter.rs
The `AggregateMeterProvider` is used by the Router to allow us to have several metrics subsystems that forward metrics to different places. In addition it has enhanced testability.
However, some users may be trying to set up otel by themselves outside of the regular router lifecycle, and they will receive no metrics.
This PR also makes the `AggregateMeterProvider` forward to the `GlobalMeterProvider`. The setup for this happens at creation time of `AggregateMeterProvider` and setting the regular otel meter provider after this happens will have no effect.
This functionality is not reccommeneded for general users, and may change in breaking ways in the future.
Fixes #4313
---
**Checklist**
- …
> Aggregate meter provider also delegates to global meter provider

- xtask/src/commands/changeset/mod.rs
the generated changesets still contained this:
```
---
```
---
**Checklist**
**Exceptions**
**Notes**
> fix PR body extraction in changesets

- .changesets/fix_lb_requires_selection_set_abstract_types.md
- apollo-router/src/query_planner/selection.rs
- apollo-router/src/services/supergraph/snapshots/apollo_router__services__supergraph__tests__abstract_types_in_requires.snap
- apollo-router/src/services/supergraph/tests.rs
This uses a more flexible abstract type / concrete type check when applying a selection set to an entity reference before it's used in a fetch node. Previous to this change, we would drop data from the reference when it selected using an inline fragment (e.g. `@requires(fields: "... on Foo { a } ... on Bar { b }")`).
This addresses a customer issue.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when …
> fix: build entity representations with inline fragments correctly

- apollo-router/src/axum_factory/tests.rs
- apollo-router/src/plugins/telemetry/metrics/apollo.rs
- apollo-router/src/services/layers/content_negotiation.rs
- apollo-router/src/services/mod.rs
- apollo-router/src/services/router.rs
- apollo-router/src/services/router/service.rs
- apollo-router/src/services/supergraph/service.rs
- apollo-router/src/services/supergraph/snapshots/apollo_router__services__supergraph__tests__subscription_without_header.snap
- apollo-router/src/test_harness/http_client.rs
- apollo-router/tests/common.rs
- apollo-router/tests/integration/subscription.rs
- docs/source/executing-operations/defer-support.mdx
Related to #4395
Remove the multipart boundary from the client `Accept` header. Typically, the boundary is decided by the server in order to avoid nameclashes with the parts contents. It just happens that `--graphql` works all the time for us because the part contents are JSON.
Keep `--graphql` as a "may" for convenience but mandate that clients support any boundary sent by the server. I _think_ this is already the case for web/ios/kotlin? Ping @alessbell @calvincestari 
ping @martinbonnin  @abernix 
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. …
> refactor(multipart): do not enforce boundary in accept header

- apollo-router/src/plugins/authorization/authenticated.rs
- apollo-router/src/plugins/telemetry/metrics/apollo.rs
- apollo-router/src/services/supergraph/service.rs
- apollo-router/src/services/supergraph/snapshots/apollo_router__services__supergraph__tests__subscription_without_header.snap
- apollo-router/src/test_harness/http_client.rs
- apollo-router/tests/apollo_reports.rs
- apollo-router/tests/integration_tests.rs
- apollo-router/tests/snapshots/integration_tests__defer_query_without_accept.snap
- dev-docs/multipart-subscriptions-protocol.md
- docs/source/executing-operations/subscription-multipart-protocol.mdx
- docs/source/executing-operations/subscription-support.mdx
Nitpick follow up from https://github.com/apollographql/router/pull/4447 to use the MDN convention of adding a space after `,` and none after `;`. I didn't really find a reference for that but I think it makes sense? 
Closest I could get is [RFC7231](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.1) that says:
```
For example, the following examples are all equivalent, but the first is preferred for consistency:
text/html;charset=utf-8
text/html;charset=UTF-8
Text/HTML;Charset="utf-8"
text/html; charset="utf-8"
```
Also remove a leftover `boundary=graphql` from the executing_operations docs
> HTTP headers: remove space after ';'

- .changesets/fix_bnjjj_fix_log_level.md
- apollo-router/src/executable.rs
- apollo-router/src/plugins/telemetry/reload.rs
- examples/supergraph-sdl/rust/src/supergraph_sdl.rs
By default the log level of the application if `RUST_LOG` is not set is `info` and if you provide `--log` or `APOLLO_RUST_LOG` value then it overrides the default `info` log level with `apollo_router=...` because it only impacts the `apollo_router` crate, not external custom plugin and so one.
By doing this fix, by default if you have a custom plugin with info logs or metrics you won't have to enforce `RUST_LOG=info` everytime, it will work as expected.
> Note: it doesn't impact the behavior of `RUST_LOG` if you set it.
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of …
> fix(log): set info log level by default for the entire application

- docs/source/configuration/authorization.mdx
Fix example Rhai script in docs for `@requiresScopes`.
Thanks @andrewmcgivery for fixing!
> docs: fix example Rhai script for requiresScopes

- .changesets/fix_geal_expose_operationkind.md
- apollo-router/src/query_planner/mod.rs
- apollo-router/src/services/mod.rs
Fix #4410
`OperationKind` was already used in a public field but the type itself was still private.
---
**Checklist**
**Exceptions**
**Notes** …
> make OperationKind public

- scripts/install.sh
Modifying the install script is going to give us the correct behaviour.
> Let's standardise on aarch64 rather than arm64

- .changesets/fix_geal_event_sampling.md
- apollo-router/src/plugins/telemetry/reload.rs
Fix #4321 
Fix #3872 (the regression appears in 1.30, when #2999 was merged)
related: #2402
This fixes a regression introduced in #2999, where events were not sent anymore with traces
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing …
> send log events with traces

- apollo-router/src/plugins/headers.rs
We keep finding cases i the router where we have a list of strings, like headers or span names, and call .contains() on that list, which results in going through the list one by one for a comparison, resulting in a significant perf hit
---
**Checklist**
**Exceptions**
**Notes** …
> replace the vec of reserved headers with a HashSet

- .changesets/feat_telemetry_header_format.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/telemetry/config.rs
- apollo-router/src/plugins/telemetry/mod.rs
resolves #4422
Previously, when the `experimental_response_trace_id` was enabled, the router would append the trace id, if present, to the headers of the response in hexadecimal format, left-padded with 0s. This commit allows specifying through the new config option `format` whether to have that value be hexadecimal (the previous behaviour and the new default) or decimal.
Below is an example of the new configuration option in action:
```yaml
telemetry:
apollo:
client_name_header: name_header
client_version_header: version_header
exporters:
tracing:
experimental_response_trace_id:
enabled: true
header_name: trace_id
format: decimal # Optional, defaults to hexadecimal
```
Note: Writing tests for this would be useful, but it seems very difficult to prime a trace ID that isn't randomly …
> add formatting options for trace_id

- .changesets/fix_geal_headers_propagation_filter.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/headers.rs
- apollo-router/src/services/subgraph_service.rs
Fix #4312
Fix #4398
Potential regression caused by this PR: the only way to activate subgraph request compression right now is to have the `Content-Encoding` header set. This header was not part of the reserved headers before, and it is now, so if a router was configured to propagate that header (either explicitely or by overly large matching), then now the subgraph request will not be compressed.
I do not think it is a good idea to have subgraph compression driven by the headers. That header should instead be set by the subgraph service directly, from an option set in configuration
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It …
> do not propagate Accept, Accept-Encoding and Content-Encoding headers

- .changesets/fix_telemetry_env_var_inconsistency.md
- apollo-router/src/executable.rs
- apollo-router/src/orbiter/mod.rs
Fixes #3023 
This commit allows for a more valid range of values for the env var APOLLO_TELEMETRY_DISABLED, which should fix inconsistencies with rover's behaviour when disabling telemetry.
There should probably be a way to pass the top-level command args to other portions of the codebase so that telemetry can be respected across the codebase using the same deserialization logic.
---
**Checklist**
**Notes** …
> Fix valid APOLLO_TELEMETRY_DISABLED flag options

- .changesets/fix_crystal_yell_juggle_craft.md
- helm/chart/router/templates/hpa.yaml
When adding a HPA, with memory and cpu limits, then argoCD application appears OutOfSync.
This is because of not consequent sorting the live manifest and the desired manifest.
Fixes #4435
---
**Checklist**
- Tests added and passing[^3] (not sure if this is required)
**Exceptions**
**Notes** …
> fix: ordering of hpa targets

- .changesets/feat_bnjjj_fix_4425.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/telemetry/config_new/attributes.rs
- apollo-router/src/plugins/telemetry/config_new/selectors.rs
If you have several baggage items and would like to add all of them directly as span attributes, for example `baggage: my_item=test, my_second_item=bar` will add 2 span attributes `my_item=test` and `my_second_item=bar`.
```yaml
telemetry:
spans:
router:
attributes:
baggage: true
```
Fixes #4425
**Checklist**
**Exceptions**
**Notes** …
> feat(telemetry): add a new selector to get all baggage key values

- apollo-router/src/services/subgraph_service.rs
Some proxys do not handle repeated headers very well, so this will remove one of the instances where it can happen in the router. Merging the multiple `Accept` headers will have the same result for the subgraph as writing two different headers
---
**Checklist**
**Exceptions**
**Notes** …
> merge the repeated Accept headers

- apollo-router/src/spec/mod.rs
- apollo-router/src/uplink/license_enforcement.rs
- apollo-router/src/uplink/snapshots/apollo_router__uplink__license_enforcement__test__progressive_override_with_renamed_join_spec.snap
- apollo-router/src/uplink/snapshots/apollo_router__uplink__license_enforcement__test__schema_enforcement_directive_arg_version_in_range.snap
- apollo-router/src/uplink/snapshots/apollo_router__uplink__license_enforcement__test__schema_enforcement_spec_version_in_range.snap
- apollo-router/src/uplink/testdata/progressive_override_renamed_join.graphql
- apollo-router/src/uplink/testdata/schema_enforcement_directive_arg_version_in_range.graphql
- apollo-router/src/uplink/testdata/schema_enforcement_directive_arg_version_out_of_range.graphql
- apollo-router/src/uplink/testdata/schema_enforcement_spec_version_in_range.graphql
- apollo-router/src/uplink/testdata/schema_enforcement_spec_version_out_of_range.graphql
The initial implementation of directive argument schema enforcement is lacking:
* It doesn't handle renames of the `join` spec via `as`, meaning the restriction could be circumvented via a `join` rename.
* It only looked for the directive argument on the definition rather than actual usages. If the arg is defined but unused, we shouldn't enforce anything. It might exist in the definition simply as a result of using the latest versions of subgraph libs/composition.
Additionally, this PR introduces the requirement of specifying a `semver::VersionReq` for enforcement.
> Improve schema enforcement

- .changesets/feat_bnjjj_fix_4561.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/telemetry/config_new/selectors.rs
- docs/source/configuration/telemetry/instrumentation/spans.mdx
```yaml
telemetry:
spans:
router:
attributes:
"my_attribute": "constant_value"
supergraph:
attributes:
"my_attribute": "constant_value"
subgraph:
attributes:
"my_attribute": "constant_value"
```
Fixes #4561 
----
**Checklist**
**Exceptions**
**Notes** …
> feat(telemetry): static attribute on specific span

- apollo-router/src/error.rs
This could be confusing for our users to talk about introspection.
> change error when query plan is empty

- .changesets/feat_bnjjj_feat_4369.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/telemetry/config_new/logging.rs
- apollo-router/src/plugins/telemetry/fmt_layer.rs
- docs/source/configuration/telemetry/exporters/logging/stdout.mdx
You can configure the logging output format when you're running on an interactive shell. If bother `format` and `tty_format` are configured then the format depends on how the router is run:
* In an interactive shell, `tty_format` will take precedence.
* In a non-interactive shell, `format` will take precedence.
You can explicitly set the format in `router.yaml` with `telemetry.exporters.logging.stdout.tty_format`:
```yaml title="router.yaml"
telemetry:
exporters:
logging:
stdout:
enabled: true
format: json
tty_format: text
```
Fixes #4369
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes …
> Ability to automatically switch the logging format depending on the terminal

- .changesets/feat_bnjjj_fix_4443.md
- apollo-router/src/configuration/migrations/0022-spans_subgraph_response_body.yaml
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/json_ext.rs
- apollo-router/src/plugin/serde.rs
- apollo-router/src/plugins/telemetry/config_new/selectors.rs
- docs/source/configuration/telemetry/instrumentation/selectors.mdx
Deprecated `subgraph_response_body` in favor of `subgraph_response_data` and `subgraph_response_errors` which is a [selector](https://www.apollographql.com/docs/router/configuration/telemetry/instrumentation/selectors/) and use a JSON Path to fetch data/errors from the subgraph response. 
Example:
```yaml
telemetry:
spans:
subgraph:
attributes:
"my_attribute":
subgraph_response_data: "$.productName"
subgraph_response_errors: "$.[0].message"
```
Fixes #4443
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do …
> Add selectors to extract body elements using JSONPath

- apollo-router/src/plugins/progressive_override/mod.rs
- apollo-router/src/plugins/progressive_override/tests.rs
These were accidentally named under the impression that they were tracking schema-related config rather than operation-based behavior.
> fix: Progressive override - use `.operations` instead of `.schema` for operations-related metrics

- docs/source/customizations/coprocessor.mdx
From [user request](https://apollograph.slack.com/archives/C0721M2F6/p1705952702706759), add (empty) `body.variables` to SupergraphRequest example
> docs: SupergraphRequest example

- .circleci/config.yml
- xtask/src/commands/dist.rs
- xtask/src/commands/package/mod.rs
This reintroduces x86_64 OSX packages that were removed due to CircleCI's deprecation of their x84_64 OSX workers. This generates two different build artifacts of the router
---
**Checklist**
**Exceptions**
**Notes** …
> build x86_64 and aarch64 packages for OSX

- scripts/install.sh
Related:
* https://github.com/apollographql/router/pull/4484
* https://github.com/apollographql/router/pull/4515 
* https://github.com/apollographql/router/pull/4518
* https://github.com/apollographql/router/pull/4605
---
**Checklist**
**Exceptions**
**Notes** …
> Allow OSX x86_64 binaries in the install script

- .changesets/fix_guitar_brighten_tailor_gel.md
- CHANGELOG.md
- Cargo.lock
- apollo-router-benchmarks/Cargo.toml
- apollo-router-scaffold/Cargo.toml
- apollo-router-scaffold/templates/base/Cargo.toml
- apollo-router-scaffold/templates/base/xtask/Cargo.toml
- apollo-router/Cargo.toml
- dockerfiles/tracing/docker-compose.datadog.yml
- dockerfiles/tracing/docker-compose.jaeger.yml
- dockerfiles/tracing/docker-compose.zipkin.yml
- helm/chart/router/Chart.yaml
- helm/chart/router/README.md
- scripts/install.sh
> **Note**
>
> When approved, this PR will merge into **the `1.39.1` branch** which will — upon being approved itself — merge into `main`.
>
>  - That it targets the right release branch (`1.39.1` in this case!).
>
---
We've re-instated the macOS Intel-based binary production and distribution that we had stopped in v1.38.0 on account of our CI provider shutting down their own Intel machines in upcoming months.  Rather than using an Intel-based machine, we will rely on the Xcode-supported cross-compilation to produce _two_ separate binaries, both created and tested only with an ARM-based …
> prep release: v1.39.1

- apollo-router/build/main.rs
when running `cargo publish`, the `Cargo.toml` file is rewritten, and the shorthand `crate_name = "version"` is converted to an object
Follows up 127fa59b3560a0b6fe97f07c20f30d6d0f59d480 in  https://github.com/apollographql/router/pull/4583
> fix federation version extraction

- .changesets/fix_geal_propagate_headers_when_not_sampling.md
- apollo-router/src/plugins/telemetry/reload.rs
- apollo-router/src/services/external.rs
- apollo-router/src/services/http/service.rs
Fix https://github.com/apollographql/router/issues/4544
When a trace is not sampled (due to the filtering layer we use in the telemetry plugin), the `OpenTelemetryLayer` is not called, and so a `TraceId`(the opentelemetry-api one, not the router side one) is never generated, which means that when reaching the header propagation code, the current span context is invalid (trace id = 0 and span id = 0) and so the propagation headers are not sent.
We want the propagation headers to still be sent when the trace is not sampled, to let the subgraphs know that they should not sample the trace either.
One option was to explicitely set the propagation headers, but that depends a lot on which propagation protocol is used. The trick I use here is generating on the fly a span context with non zero …
> define a trace id for propagated headers when not sampling

- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/router_factory.rs
- apollo-router/src/services/http.rs
- apollo-router/src/services/http/service.rs
- apollo-router/src/services/http/tests.rs
Fix #4491 
when TLS was not configured for subgraphs, the OS provided list of certificates was parsed once per subgraph, which resulted in long loading times on OSX.
This generates the native root store once, and reuses it across subgraphs
---
**Checklist**
**Exceptions**
**Notes** …
> only load the TLS native store once

- docs/source/configuration/authn-jwt.mdx
- docs/source/configuration/authorization.mdx
- docs/source/configuration/distributed-caching.mdx
- docs/source/configuration/operation-limits.mdx
- docs/source/configuration/persisted-queries.mdx
- docs/source/configuration/telemetry/exporters/metrics/overview.mdx
- docs/source/configuration/telemetry/instrumentation/conditions.mdx
- docs/source/configuration/telemetry/instrumentation/events.mdx
- docs/source/configuration/telemetry/instrumentation/instruments.mdx
- docs/source/configuration/telemetry/instrumentation/spans.mdx
- docs/source/configuration/telemetry/overview.mdx
- docs/source/customizations/coprocessor.mdx
- docs/source/enterprise-features.mdx
- docs/source/executing-operations/subscription-support.mdx
Many features that were previously denoted "Enterprise only" are also now included in the Dedicated plan.
This PR calls those out and adds an explanation of "GraphOS Router" found on the often linked pricing page.
This PR is dependent on component changes in https://github.com/apollographql/docs/pull/777 and should be merged shortly after it.
---
**Checklist**
**Exceptions**
**Notes** …
> docs: document premium vs enterprise router features

- .changesets/fix_geal_propagate_headers_when_not_sampling.md
- CHANGELOG.md
- Cargo.lock
- apollo-router-benchmarks/Cargo.toml
- apollo-router-scaffold/Cargo.toml
- apollo-router-scaffold/templates/base/Cargo.toml
- apollo-router-scaffold/templates/base/xtask/Cargo.toml
- apollo-router/Cargo.toml
- dockerfiles/tracing/docker-compose.datadog.yml
- dockerfiles/tracing/docker-compose.jaeger.yml
- dockerfiles/tracing/docker-compose.zipkin.yml
- helm/chart/router/Chart.yaml
- helm/chart/router/README.md
- scripts/install.sh
> **Note**
>
> When approved, this PR will merge into **the `1.40.1` branch** which will — upon being approved itself — merge into `main`.
>
>  - That it targets the right release branch (`1.40.1` in this case!).
>
---
When the router was configured to sample only a portion of the trace, either through a ratio or using parent based sampling, and when trace propagation was configured, if a trace was not sampled, the router did not send the propagation headers to the subgraph. The subgraph was then unable to decide whether to record the trace or not. Now we make sure that trace headers will …
> prep release: v1.40.1

- .changesets/fix_bnjjj_fix_4699.md
- apollo-router/src/plugins/telemetry/mod.rs
When configuring the `experimental_response_trace_id` without an explicit header it now correctly takes the default one `apollo-trace-id`.
```yaml
telemetry:
exporters:
tracing:
experimental_response_trace_id:
enabled: true
```
Fixes #4699 
---
**Checklist**
**Exceptions**
**Notes** …
> fix(telemetry): use the right default header name when experimental_response_trace_id is enabled

- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/spec/schema.rs
- apollo-router/src/testdata/minimal_fed2_supergraph.graphql
To get a better understanding of how many users are still on fed v1, this PR adds a metric.
I put it under the `lifecycle` key, is that appropriate?
The version is inferred based on the version of the join spec that is used, as this is closely tied to the federation version. The federation minor version is not available in a supergraph as far as I know (it could only be inferred based on features that are in use, but that's not reliable if someone doesn't use every feature).
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to …
> Add a metric for federation version

- apollo-router/src/configuration/metrics.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@apq.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@authorization.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@authorization_directives.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@batching.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@coprocessor.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@entities.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@file_uploads.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@limits.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@persisted_queries.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@subscriptions.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@telemetry.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@tls.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@traffic_shaping.router.yaml.snap
Internal config metric attributes had an extra trailing dot that was introduced in #4364.
This PR strips off the extra dot that was introduced.
Fixes #4689
---
**Checklist**
**Exceptions**
**Notes** …
> Fix trailing dot on internal router usage metric attributes

- docs/source/executing-operations/subscription-support.mdx
This PR updates the subscription support article.
The current frontmatter and intro suggestion that this feature is for self-hosted routers only. The feature is also available for cloud routers. It also uses shared components introduced in https://github.com/apollographql/docs/pull/783.
> docs: update subscription frontmatter

- .changesets/feat_geal_entity_cache_span.md
- apollo-router/src/plugins/cache/entity.rs
This adds the `cache_lookup` and `cache_store` spans to show the Redis calls in entity cache. This also changes the behavior slightly so that storing in Redis does not stop the execution of the rest of the query
---
**Checklist**
**Exceptions**
**Notes**
[^3]: …
> Entity cache: Add spans around redis interaction

- .changesets/fix_geal_osx_x86.md
- .circleci/config.yml
Cross compiling the router from ARM to x86 encounters issues with deno snapshots, so for now we will reactivate x86 builds for macos on CircleCI
---
**Checklist**
**Exceptions**
**Notes** …
> reactivate the macos x86_64 builder

- .circleci/config.yml
Update our linux images
from: `2004:2022.04.1`
to: `2004:2024.01.1`
Still `ubuntu 20.04` based, but with more recent patches and not subject to brown outs.
> update our base linux image to avoid CI brown outs

- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/testdata/minimal_fed2_supergraph.graphql
- apollo-router/tests/telemetry/metrics.rs
Follow-up to #4713.
Per discussion with @BrynCooke this changes the new metric to a gauge, named `apollo.router.supergraph.federation`.
Also adds a basic test for it.
> Change the new federation version metric to a gauge

- .changesets/fix_geal_osx_x86.md
- .circleci/config.yml
- CHANGELOG.md
- Cargo.lock
- apollo-router-benchmarks/Cargo.toml
- apollo-router-scaffold/Cargo.toml
- apollo-router-scaffold/templates/base/Cargo.toml
- apollo-router-scaffold/templates/base/xtask/Cargo.toml
- apollo-router/Cargo.toml
- apollo-router/src/axum_factory/axum_http_server_factory.rs
- apollo-router/src/axum_factory/utils.rs
- apollo-router/src/plugins/telemetry/proto/reports.proto
- apollo-router/src/services/http/service.rs
- apollo-router/src/services/layers/content_negotiation.rs
- apollo-router/tests/common.rs
- apollo-router/tests/telemetry/metrics.rs
- dockerfiles/tracing/docker-compose.datadog.yml
- dockerfiles/tracing/docker-compose.jaeger.yml
- dockerfiles/tracing/docker-compose.zipkin.yml
- helm/chart/router/Chart.yaml
- helm/chart/router/README.md
- licenses.html
- scripts/install.sh
This fixes a Denial-of-Service (DoS) type vulnerability which exists in affected versions of the Router (back to v0.9.5).  This fix changes the evaluation of the `limits.http_max_request_bytes` configuration to take place on a stream of bytes, allowing it to be applied to compressed HTTP payloads, prior to decompression.  Previously, the limit was only being applied after the entirety of the compressed payload was decompressed, which could result in significant memory consumption which exceeded configured expectations while compressed payloads were expanded.
By [@Geal](https://github.com/Geal) in 9e9527c73c8f34fc8438b09066163cd42520f413
We have re-activated macOS Intel (x86) builds in CircleCI, despite their upcoming deprecation, while we take a different approach to solving this and …
> release: v1.40.2: security: Apply `limits.http_max_request_bytes` on streaming request body decompression

- .changesets/fix_geal_non_blocking_stdout.md
- apollo-router/src/executable.rs
- apollo-router/src/plugins/telemetry/fmt_layer.rs
- docs/source/customizations/native.mdx
This reverts commit 11fad3c8563b012b4a09d81644eb218df07ee4ba from #4625 on account of discomfort with the solution and not being able to concretely tie it back an actual fix for the root cause.  We have re-opened #4612 to track the need to get back to this.
> Revert "use a non blocking stdout (#4625)"

- .changesets/feat_geal_jwt_source.md
- .gitleaks.toml
- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/authentication/mod.rs
- apollo-router/src/plugins/authentication/tests.rs
- docs/source/configuration/authn-jwt.mdx
Fix https://github.com/apollographql/router/issues/4665 (docs)
The token can be stored in different headers, but it can also be carried by a cookie. This adds cookies as an alternative source of tokens, and allows multiple alternative sources
---
**Checklist**
**Exceptions**
**Notes** …
> Support loading JWT from other sources

- .changesets/feat_geal_jwks_headers.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/authentication/jwks.rs
- apollo-router/src/plugins/authentication/mod.rs
- apollo-router/src/plugins/authentication/tests.rs
- docs/source/configuration/authn-jwt.mdx
Fix #4651
This adds the ability to set static headers on HTTP requests to download a JWKS from an identity provider
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document …
> add headers to the JWKS download request

- apollo-router/tests/fixtures/file_upload/schema.graphql
- apollo-router/tests/integration/file_upload.rs
Existing integration tests for the file uploads plugin did not test for non-nullable uploads. As this is realistically the more common case, this commit adds a test to ensure that non-nullable files work as expected.
This is necessary since the router does some substitution of the variables for the file upload case which might cause validation issues if not carefully tested.
As is the case in #4754, this commit is rebased off of #4726 as certain tests fail when the output blocks.
Fixes #4708 
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. …
> Add integration test for non-nullable files

- .changesets/fix_bryn_datadog_trace_id.md
- apollo-router/src/plugins/telemetry/formatters/json.rs
- docs/source/configuration/authn-jwt.mdx
- docs/source/configuration/telemetry/exporters/tracing/datadog.mdx
To enable correlation between DataDog tracing and logs dd.trace_id must appear as a span attribute and also on the root of each json formatted log message.
Currently, users can output dd.trace_id on logs but it is located within the span attributes, and therefore will not show as correlated in the datadog UI.
Old:
```
{"timestamp":"2024-03-07T14:42:44.408899252Z","level":"ERROR","message":"test","target":"apollo_router::plugins::telemetry","spans":[{"http.route":"/","http.request.method":"POST","url.path":"/","dd.trace_id":"3377607226581119358","client.name":"","client.version":"","name":"router"},{"name":"supergraph"},{"graphql.operation.type":"query","name":"execution"},{"apollo.subgraph.name":"products","name":"fetch"}],"resource":{"service.version":"1.40.1","process.executable.name":"r …
```
> Attach `dd.trace_id` to json formatted log messages

- apollo-router/tests/common.rs
This commit ups the timeout used when verifying that the router instance started by the integration test works as expected.
This is a temporary solution to fix some flakiness in the tests as a better solution would not depend so heavily on non-deterministic timings of the router.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is an important part of many changes. …
> Up timeout in integration tests

- CHANGELOG.md
- Cargo.lock
- apollo-router-benchmarks/Cargo.toml
- apollo-router-scaffold/Cargo.toml
- apollo-router-scaffold/templates/base/Cargo.toml
- apollo-router-scaffold/templates/base/xtask/Cargo.toml
- apollo-router/Cargo.toml
- dockerfiles/tracing/docker-compose.datadog.yml
- dockerfiles/tracing/docker-compose.jaeger.yml
- dockerfiles/tracing/docker-compose.zipkin.yml
- helm/chart/router/Chart.yaml
- helm/chart/router/README.md
- scripts/install.sh
> [!NOTE]
>
> v1.41.1 replaces a failed publish of v1.41.0.  The version number had to be moved from v1.41.0 to v1.41.1, but the release is otherwise the same.  Apologies for the confusion!
Only the version numbers have changed.
> release: v1.41.1

- apollo-router/feature_discussions.json
- apollo-router/src/configuration/metrics.rs
- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/configuration/testdata/metrics/batching.router.yaml
- apollo-router/src/services/router/service.rs
- apollo-router/src/services/router/tests.rs
- apollo-router/src/uplink/license_enforcement.rs
- apollo-router/tests/fixtures/apollo_reports_batch.router.yaml
- apollo-router/tests/snapshots/lifecycle_tests__cli_config_experimental.snap
- docs/source/configuration/traffic-shaping.mdx
- docs/source/executing-operations/query-batching.mdx
This commit adds configuration options for later use in the router to subgraph epic. More changes will be necessary to actually use these new configuration changes.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. …
> Add config for router-subgraph batching

- .changesets/fix_bnjjj_multipart_test.md
- apollo-router/src/axum_factory/tests.rs
- apollo-router/src/protocols/multipart.rs
This PR changes the way we're sending chunks in the stream. Instead of finishing the chunk with `\r\n` we don't send this at the end of our current chunk but instead at the beginning of the next one. For the end users nothing changes but it let us to close the stream with the right final boundary by appending `--\r\n` directly to the last chunk.
Fixes #4634
---
**Checklist**
**Exceptions**
**Notes** …
> Fix chunk formatting in multipart protocol

- apollo-router/src/axum_factory/utils.rs
- apollo-router/src/plugins/telemetry/mod.rs
Otel internally does a case-insensitive compare, so it's just a minor code improvement that doesn't affect existing tests for spans in any way.
---
**Checklist**
**Exceptions**
**Notes** …
> Introduce constants for span status

- .changesets/feat_add_container_scaling_config.md
- helm/chart/router/templates/hpa.yaml
- helm/chart/router/values.yaml
Update the helm chart to allow specifying container resource HPA targets (https://kubernetes.io/blog/2023/05/02/hpa-container-resource-metric/). This functionality is only available in Kubernetes 1.27+ by default. Multiple containers and criteria types can be configured.
This supports the use case when the router is running with extra containers that have independent scaling constraints from the overall pod usage.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing …
> Support configuring container resource HPA targets

- docs/source/config.json
- docs/source/errors.mdx
Document router response status codes in [new errors page](https://deploy-preview-4733--apollo-router-docs.netlify.app/errors)
Resolves https://github.com/apollographql/router/issues/4740 and https://apollographql.atlassian.net/browse/DOC-34
> docs: router HTTP response status codes

- apollo-router/src/batching.rs
- apollo-router/src/services/subgraph_service.rs
This commit adds a few more unit tests for verifying the functionality of all helper methods and, where applicable, beefy methods pertinent to the subgraph batching initiative.
Note: This commit builds off of #4780 so @garypen please refer to [this commit](https://github.com/apollographql/router/pull/4787/commits/e7038b3832a95246bc23da33959f74d1a46ddf5e).
---
**Checklist**
**Exceptions**
**Notes** …
> Add missing unit tests for subgraph batching

- docs/source/configuration/telemetry/instrumentation/standard-instruments.mdx
Fixes https://github.com/apollographql/router/issues/4804
> docs: Add note that `apollo_router_span` is replaced `apollo_router_processing_time`

- apollo-router/src/executable.rs
- apollo-router/src/orbiter/mod.rs
- apollo-router/src/router/mod.rs
- apollo-router/src/router_factory.rs
- apollo-router/src/state_machine.rs
This unbreaks e.g. `cargo test -- -q`
---
**Checklist**
**Exceptions**
**Notes**
> Orbiter: don’t parse CLI arguments in tests

- apollo-router/src/query_planner/caching_query_planner.rs
Now that UsageReporting is stored in an Arc, we can just clone it and drop the lock, then insert what we want in the context outside of the lock
This fixes a bug often triggerd in CI: 
```
thread 'test_plugin_ordering' panicked at apollo-router/src/context/extensions/sync.rs:66:21:
ExtensionsGuard held for 11ms. This is probably a bug that will stall the Router and cause performance problems. Run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
https://app.circleci.com/pipelines/github/apollographql/router/19639/workflows/34bc93f3-6a17-4514-9a5c-66a725f47f72/jobs/131057?invite=true#step-117-304313_184
---
**Checklist**
**Exceptions**
*Note …
> drop the ExtensionsGuard earlier

- .changesets/fix_bryn_zipkin_service_name.md
- .circleci/config.yml
- apollo-router/src/plugins/telemetry/tracing/zipkin.rs
- apollo-router/tests/fixtures/zipkin.router.yaml
- apollo-router/tests/zipkin_test.rs
Zipkin exporter ignores service-name from the trace config. We have to explicitly set it.
Added integration test for zipkin
Fixes #4807
---
**Checklist**
**Exceptions**
**Notes** …
> Zipkin service name not populated

- docs/source/configuration/traffic-shaping.mdx
Add table to clarify the resulting HTTP protocol of a subgraph connection when configuring `experimental_http2`.
Resolves [DOC-11](https://apollographql.atlassian.net/browse/DOC-11)
[DOC-11]: https://apollographql.atlassian.net/browse/DOC-11?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> doc: clarify the resulting protocol of a subgraph connection when configuring experimental_http2

- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/demand_control/mod.rs
- apollo-router/src/plugins/mod.rs
- apollo-router/src/router_factory.rs
- apollo-router/src/uplink/license_enforcement.rs
- apollo-router/src/uplink/snapshots/apollo_router__uplink__license_enforcement__test__restricted_features_via_config.snap
- apollo-router/src/uplink/testdata/restricted.router.yaml
Created scaffolding for new demand control plugin with a simple config. The max cost setting is planned to come from the limits block of the configuration, so it is not included in this change. The plugin is currently not registered so it does not appear in the config schema during development
Fixes [ROUTER-181](https://apollographql.atlassian.net/browse/ROUTER-181)
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement …
> Create scaffolding for new demand control plugin

- .changesets/fix_geal_entity_cache_slots.md
- apollo-router/src/cache/redis.rs
- apollo-router/src/plugins/cache/entity.rs
in a Redis cluster, entities can be stored in different nodes, which makes MGET fails. This splits the MGET query in multiple MGETs calls grouped by key hash, to make sure each one will get to the corresponding node, then merges responses in the correct order.
---
**Checklist**
**Exceptions**
**Notes** …
> hash all entities to the same slot to support MGET in clusters

- .changesets/feat_subscription_websocket_heartbeat.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/subscription.rs
- apollo-router/src/protocols/websocket.rs
- apollo-router/src/services/subgraph_service.rs
- docs/source/executing-operations/subscription-support.mdx
Add the ability to enable heartbeat for cases where the subgraph drops idle connections.
For example, https://netflix.github.io/dgs/
```yaml
subscription:
mode:
passthrough:
all:
path: /graphql
heartbeat_interval: enable #Optional
```
Fixes #4621
---
**Checklist**
**Exceptions**
**Notes** …
> feat(subscription): add configurable heartbeat for websocket protocol

- RELEASE_CHECKLIST.md
Wrote up these changes on Friday night and just wanted to push them up.  The overall mechanisms haven't changed (e.g., a tag creates a release), but these are steps which have changed, process-wise in terms of how we do releases.  Today, we've adopted the pattern of:
1. Open a Release Branch from a point in time with specific intention to land certain features for a specific milestone we're working toward (e.g., Subscription WebSocket fixes in the last release).  This PR targets `main`, but stays as draft until it's ready to go final (step 4)
2. Stage changes and final polish on that Release branch and associated PR while the rest of `dev` moves forward.
3. Cut any number of release candidates for testing and validation.  These release candidates don't get the full-changelog treatment.
4. …
> docs: Update RELEASE_CHECKLIST.md to reflect state of operations

- .circleci/config.yml
CI is failing on `choco install cmake` because it can't find the `cmake.install` dependency. Weirdly it does find that package if you install it directly. As I understand it, these packages follow an established chocolatey pattern and so it's not an implementation detail, so we should be able to rely on `cmake.install` directly.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: …
> ci: fix CMake install by explicitly using `cmake.install` on windows

- .changesets/fix_geal_request_completion.md
- .circleci/config.yml
- RELEASE_CHECKLIST.md
- apollo-router/src/axum_factory/axum_http_server_factory.rs
- apollo-router/src/axum_factory/mod.rs
- apollo-router/src/axum_factory/snapshots/apollo_router__axum_factory__axum_http_server_factory__tests__request_cancel@logs.snap
- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/coprocessor/execution.rs
- apollo-router/src/plugins/coprocessor/mod.rs
- apollo-router/src/plugins/coprocessor/supergraph.rs
- apollo-router/src/query_planner/execution.rs
- apollo-router/src/services/router/service.rs
- apollo-router/tests/integration/batching.rs
- apollo-router/tests/integration/mod.rs
- docs/source/errors.mdx
This commit allows cancelled requests by a coprocessor to also cancel portions of a batch query correctly.
This logic should eventually be moved higher up the call stack of the router so that future plugins, custom plugins, and anything else that might cancel portions of a batch query not timeout without needing to copy this commit's logic.
---
**Checklist**
**Exceptions**
**Notes** …
> Add batching cancellations to coprocessor

- apollo-router/src/services/subgraph_service.rs
Without this fix a null body would cause the router to panic.
With this fix, if a body is null, then the router returns an error to the user.
> [batching] fix subgraph unwrapping

- .changesets/fix_i1g_subscription_websocket_fix_ping.md
- apollo-router/src/protocols/websocket.rs
Removes invalid payload on graphql-ws Ping message
Fixes #4852
---
**Checklist**
**Exceptions**
**Notes**
> subscription: remove payload on websocket's Ping

- .changesets/fix_graphql_request_extensions.md
- apollo-router/src/request.rs
- apollo-router/src/snapshots/apollo_router__request__tests__extensions.snap
- apollo-router/src/snapshots/apollo_router__request__tests__missing_extensions.snap
- apollo-router/src/snapshots/apollo_router__request__tests__null_extensions.snap
According to the graphql over http spec we should be allowing `null` to be passed for extensions in the request. https://graphql.github.io/graphql-over-http/draft/#sel-EALFPCCBCEtC37P
Currently,w e reject the payload, which is an issue for some clients.
This is now fixed and tests added.
FIxes #4856
---
**Checklist**
**Exceptions**
**Notes** …
> `null` extensions incorrectly disallowed on request

- apollo-router/src/batching.rs
- apollo-router/src/services/subgraph_service.rs
Tracing is now tracked against the batching_request span (with tracing links!) for those items which can be batched.
> [batching] Add tracing support for subgraph batching

- .changesets/fix_bnjjj_4798.md
- apollo-router/src/plugins/telemetry/metrics/otlp.rs
- apollo-router/src/plugins/telemetry/otlp.rs
- apollo-router/src/plugins/telemetry/tracing/otlp.rs
In our [documentation](https://www.apollographql.com/docs/router/configuration/telemetry/exporters/tracing/otlp/#endpoint) when configuration http endpoint for tracing otlp exporter we say that users should only include the base address of the otlp endpoint. It was only working for grpc protocol and not http due to [this bug](https://github.com/open-telemetry/opentelemetry-rust/issues/1618). This inconsistency is now fixed with a workaround in the router waiting for the fix in openetelemetry crate.
So for example you'll have to specify the right path for http:
```yaml
telemetry:
exporters:
tracing:
otlp:
enabled: true
endpoint: "http://localhost:4318"
protocol: http
```
Fixes #4798
---
**Checklist** …
> fix(telemetry): keep consistency between tracing otlp endpoint

- apollo-router/src/batching.rs
- apollo-router/src/services/router/service.rs
These tweaks are enough (I think) for us to make progress.
Let's review together and then decide how to proceed.
> [batching] tweak single cancellation point changes

- apollo-router/src/batching.rs
- apollo-router/src/plugins/coprocessor/execution.rs
- apollo-router/src/plugins/coprocessor/mod.rs
- apollo-router/src/plugins/coprocessor/supergraph.rs
- apollo-router/src/plugins/rhai/mod.rs
- apollo-router/src/services/router/service.rs
- apollo-router/tests/fixtures/batching/coprocessor.router.yaml
- apollo-router/tests/integration/batching.rs
This commit moves handling of cancelled batch queries into the router service so that any custom rust plugin, rhai script, coprocessor, etc. will have cancelled requests handled without needing to handle batches specially.
---
**Checklist**
**Exceptions**
**Notes** …
>  Move batch query cancellation up

- .changesets/fix_geal_reparent_spans.md
- apollo-router/src/layers/instrument.rs
- apollo-router/src/plugins/telemetry/logging/snapshots/apollo_router__plugins__telemetry__logging__test__when_header@logs.snap
Fix https://github.com/apollographql/router/issues/4827
---
**Checklist**
**Exceptions**
**Notes**
> Give spans their proper parent in the plugin stack

- .changesets/fix_glasser_selector_labels.md
- helm/chart/router/templates/deployment.yaml
Every other use of `router.selectorLabels` is in an actual selector; every other `metadata.labels` uses `router.labels`.
The effect of this PR is to add `helm.sh/chart`, `app.kubernetes.io/version`, and `app.kubernetes.io/managed-by` labels to pods.
---
**Checklist**
**Exceptions**
**Notes** …
> Helm chart: include all standard labels in pod spec

- .changesets/fix_apq_cache_key_to_match_redis_convention.md
- apollo-router/src/services/layers/apq.rs
- apollo-router/tests/integration/redis.rs
This PR conforms the apq cache key to follow redis convention. This helps when using redis clients to properly display keys in nested form.
query plan cache key was fixed in a similar pr: https://github.com/apollographql/router/pull/4583
---
**Checklist**
**Exceptions**
**Notes** …
> replace null separator in apq cache key with : to match convention

- .changesets/feat_garypen_2002_subgraph_batching.md
- docs/source/executing-operations/query-batching.mdx
Add a new paragraph to explain batching and make the changeset examples valid.
> try to improve the docs based on Edward's comments

- .changesets/fix_garypen_revive_docker_heaptrack.md
- dockerfiles/Dockerfile.router
- dockerfiles/diy/dockerfiles/Dockerfile.repo
Since we made our images more secure, we run our router process as user 'router'. If we are running under 'heaptrack', e.g.: in a debug image, then we cannot write to /dist/data because it is owned by 'root'.
This changes the ownership of /dist/data from 'root' to 'router' to allow writes to succeed.
> Make router user the owner of the docker image's /dist/data directory

- docs/source/configuration/telemetry/instrumentation/selectors.mdx
This attribute is not yet implemented, we are tracking the work to do that in https://github.com/apollographql/router/issues/4830
However until we actually implement it we should remove from the docs
> [docs] Remove supergraph selector response body

- .changesets/fix_glasser_pq_error_status_codes.md
- apollo-router/src/services/layers/persisted_queries/mod.rs
Previously, sending a request that failed for a PQ-related reason would return a 200 status code. Now, various PQ-related errors lead to non-200 status codes:
- Sending a PQ ID that is unknown yields 404 Not Found
- Sending freeform GraphQL when no freeform GraphQL is allowed yields 400 Bad Request
- Sending both a PQ ID and freeform GraphQL in the same request (if the APQ feature is not also enabled) yields 400 Bad Request
- Sending freeform GraphQL that is not in the safelist when the safelist is enabled yields 403 Forbidden
- A particular internal error that shouldn't happen yields 500 Internal Server Error
**Checklist**
**Exceptions**
This could be …
> feat(pq): use 4xx status code on PQ errors

- .changesets/maint_garypen_fix_telemetry_integration_test_macos.md
- apollo-router/tests/integration/mod.rs
- apollo-router/tests/integration/telemetry/jaeger.rs
- apollo-router/tests/integration/telemetry/otlp.rs
- apollo-router/tests/integration/telemetry/zipkin.rs
For a little while we have had a warning with integration tests on macOS. This fixes the warning.
> fix annoying integration test warning on macOS

- apollo-router/src/configuration/metrics.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__custom_plugin.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__ignore_cloud_router_plugins.snap
Adds a metric for configuration of custom plugins. This will help inform us of how may users are writing custom rust based plugins.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, …
> Add metric for use of custom plugins

- apollo-router/src/configuration/metrics.rs
#4923 added a println that should not have been there.
---
**Checklist**
**Exceptions**
**Notes**
> Remove println accidentally added in 4923

- apollo-router/src/configuration/metrics.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@query_planner_parallelism_auto.router.yaml.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@query_planner_parallelism_static.router.yaml.snap
Fix typo `query_panner` -> `query_planner`
> query_panner -> query_planner

- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- examples/supergraph-sdl/rust/Cargo.toml
Fixes #4649
Requires an apollo-federation update to feign support for join spec v0.4. The new join spec doesn't affect how the API schema is generated so the only thing the update does is *not error*. The new release also includes a query plan Display implementation for #4815! 
I ran it through our whole harness testing again, which is quite reliable for API schema as the schema data is complete. The only observable differences are in the sorting of keys in input objects in default values which is both very limited, and doesn't make sense in the JS version, so that's good. The *meaning* of schemas did not change in any case.
> Enable Rust-based API schema generation by default

- apollo-router/src/logging/mod.rs
- apollo-router/src/plugins/mod.rs
- apollo-router/src/plugins/telemetry/logging/mod.rs
- apollo-router/src/plugins/test.rs
This is suited for unit testing where you wish to inspect the request and response both at the start of the pipeline and at the destination service.
The existing TestHarness is about firing up the entire router stack.
Alternatives that we have tried are mocking, which never ends well.
This test harness is super simple, and allows you to create a plugin, fire a fake request through, perform assertion on the request during the pipeline execution, return a fake response, perform validation on the returned response.
It's only used in telemetry at the moment, but it'll be useful for demand control.
---
**Checklist**
**Exceptions**
**Notes** …
> Move PluginTestHarness out of telemetry for use in other plugins

- apollo-router/src/batching.rs
- apollo-router/src/services/router/service.rs
- apollo-router/src/services/subgraph_service.rs
- apollo-router/src/services/supergraph/service.rs
It turns out that it's tricky. We need to use tokio async mutex to stop the compiler complaining that parking lot mutex guard isn't send.
We still need the parking lot mutex, because we can't make query_for_index() async or that causes a different Send/Sync issue.
Other problems are avoided by using:
- AtomicUsize to track remaining
- Arc/Mutex on Sender to allow for cloning and interior mutability
I'm not 100% convinced this is an improvement, since the code is slower and more complex and I don't actually think there is a race in the existing code *unless* someone is doing something very funky with the batching extensions(). So, I'll put it on a branch and seek specific feedback on this change.
> [batching] make batching look less racy

- .circleci/config.yml
- Cargo.lock
- apollo-router/Cargo.toml
CircleCI OSX x86_64 workers are deprecated and will be removed in June. To get ahead of that, we are now building those versions from the M1 workers.
This required a change in router-bridge, to start the deno instance of the query planner without snapshots: https://github.com/apollographql/federation-rs/commit/6c23a0785d874b4787dd5025c0da8c4916cdd50d
In our tests, this did not really affect the startup time, this change is safe to use.
---
**Checklist**
**Exceptions**
**Notes** …
> cross compile OSX x86_64 router builds from M1

- .changesets/feat_geal_remove_legacy_validation.md
- Cargo.lock
- Cargo.toml
- apollo-router/Cargo.toml
- apollo-router/src/error.rs
- apollo-router/src/plugins/authorization/mod.rs
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/query_planner/caching_query_planner.rs
- apollo-router/src/router/mod.rs
- apollo-router/src/spec/mod.rs
- apollo-router/src/spec/query.rs
- apollo-router/src/spec/query/subselections.rs
- apollo-router/tests/integration/validation.rs
- apollo-router/tests/integration_tests.rs
- apollo-router/tests/snapshots/integration_tests__defer_path_with_disabled_config.snap
- apollo-router/tests/snapshots/integration_tests__validation_errors_from_rust.snap
- examples/supergraph-sdl/rust/Cargo.toml
Error messages are now mostly the same as the graphql-js messages from before (where possible). GraphQL syntax errors are reported as `PARSING_ERROR` again instead of as `GRAPHQL_VALIDATION_ERROR`.
`SpecError::ParsingError` is replaced by `SpecError::ParseError` which contains structured error information similar to `SpecError::ValidationError`. The other uses of `ParsingError` are replaced by `TransformError`, as most of them are in query transforms/filtering. The error messages for `TransformError` remain the same.
There will still be differences in error messages, especially when querying undefined fields etc, because previously those would hit an error case deep inside the router whereas now they will be rejected early on. This is an easily explainable difference with obvious benefits …
> Rust validation backwards compatibility fixes

- apollo-router/src/plugins/file_uploads/rearrange_query_plan.rs
1. Replace unordered HashSet/HashMap with IndexSet/IndexMap. It makes predictable order of variable names inside error messages
2. Add unit tests
3. For Parallel node simplify result query plan by doing special handling of cases: a. if only one subnode is using files don't change anything b. if all subnodes are using files replace `Parallel` with `Sequence`
---
**Checklist**
**Exceptions**
**Notes** …
> file-uploads: Add tests and improve errors for rearrange_query_plan

- docs/source/errors.mdx
Define the HTTP status code 504 per the [implementation].
[implementation]: https://github.com/apollographql/router/blob/ab069ef2df14d41c37b8087f4aa9a3b60fc38242/apollo-router/src/plugins/traffic_shaping/timeout/error.rs#L28
> docs: Update "errors" to include traffic-shaping timeouts' 504 status

- docs/source/config.json
- docs/source/configuration/telemetry/exporters/metrics/overview.mdx
- docs/source/configuration/telemetry/instrumentation/instruments.mdx
- docs/source/configuration/telemetry/instrumentation/standard-instruments.mdx
- docs/source/configuration/telemetry/overview.mdx
Add instruments page to left-nav, and update related pages.
> docs: add instruments to left-nav

- apollo-router/src/services/router/service.rs
During testing we found an existing issue with batching support which causes the router to panic if an empty batch is submitted to the router.
This is only a problem if batching support is enabled.
We now explicitly check for empty batches and return a helpful error message if they are detected.
> Don't try to process empty batches of requests

- CHANGELOG.md
Two of my recent changes had sloppy headers.
---
**Checklist**
**Exceptions**
None, CHANGELOG.md change only.
**Notes**
> changelog: fix a few typos in headers

- apollo-router/Cargo.toml
- apollo-router/build/main.rs
- apollo-router/src/query_planner/bridge_query_planner.rs
When running `cargo publish`, the build script looks for a workspace Cargo.toml that does not exist because that does not execute from inside the repository
---
**Checklist**
**Exceptions**
**Notes** …
> move back the router-bridge version in the router's Cargo.toml

- apollo-router/src/axum_factory/tests.rs
- apollo-router/src/configuration/mod.rs
* Use an available port number
* Add an artificial delay to make sure the short timeout is triggered
The latter is an attempt to fix the test sometimes returning HTTP 200 instead of the expect 504 Gateway Timeout. I suspect either that the future wrapped in timeout would return `Ready` immediately (our `plugins::traffic_shaping::timeout` only polls the `sleep` future when the main future returns `Pending`), or the normal flow would complete within a kernel tick (which is likely much less frequent than 1ns), so `sleep` would measure zero elapsed time.
Fixes https://github.com/apollographql/router/issues/4910
---
**Checklist**
**Exceptions**
*Note any exceptions …
> Make test_supergraph_timeout more robust

- .circleci/config.yml
We test our Helm chart against known stable Kubernetes versions.  [Kubernetes v1.30.0] came out last night, however, the [manifest] on which we rely in order to uses a particularly odd format when this happens, leaving both `previousPatches` empty, but also not a nice representation of "current version" that we can rely on without doing some funny inference.  (YAML comes into play here)
This fix wouldn't be necessary after the first patch (v1.30.1), but the work to fix this in a better way is disproportional to just not testing the very first patch version of a new Kubernetes minor, which is probably a totally fine trade-off for the first month of a brand new Kubernetes release.  (v1.30.1 already shows in the manifest as coming on 2024-05-15).
For now, this unblocks CI.  We could consider …
> ci: Only validate Helm against Kubernetes versions with "previous patches"

- Cargo.lock
- apollo-router/Cargo.toml
> [!IMPORTANT]
>
> Read below for important details.  While the Router is unaffected, this patch will be applied in Router v1.45.0 which will release on Monday, April 22, 2024.
While the Router **does** use `rustls`, [RUSTSEC-2024-0336] (also known as [CVE-2024-32650] and [GHSA-6g7w-8wpp-frhj]) **DOES NOT affect the Router** since it uses `tokio-rustls` which is specifically called out in the advisory as unaffected.
Despite the lack of impact, we update `rustls` version v0.21.10 to [rustls v0.21.11] which includes a patch.
[RUSTSEC-2024-0336]: https://rustsec.org/advisories/RUSTSEC-2024-0336.html
[CVE-2024-32650]: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-32650
[GHSA-6g7w-8wpp-frhj]: https://github.com/advisories/GHSA-6g7w-8wpp-frhj
[rustls v0.21.11]: …
> chore(deps,security): update rustls to v0.21.11

- .circleci/config.yml
This fixes the version number for `cargo-about` , `cargo-deny` and `cargo-edit` to make sure that building an old branch in the future will still work
---
**Checklist**
**Exceptions**
**Notes** …
> fix versions for cargo-about, cargo-deny, cargo-edit

- .circleci/config.yml
When building an old version of the Router, we have a `rust-toolchain.toml` file that fixes the version used to build, but `rustup.sh` does not actually take that file into account: it installs the last stable, that is then cached, and then when building the router, we install on the fly the required version. This is not a big issue when working on the `dev` branch which always uses the last stable. But for older versions, we should cache the version actually used
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this …
> fix rust version in CI

- docs/source/executing-operations/subscription-support.mdx
This header wasn't rendering correctly in our documentation.  This attempts to fix that.
It was showing as this:
> docs(subscription-support): Try to fix formatting of L3 header.

- docs/shared/telemetry-performance.mdx
- docs/source/config.json
- docs/source/configuration/telemetry/instrumentation/conditions.mdx
- docs/source/configuration/telemetry/instrumentation/events.mdx
- docs/source/configuration/telemetry/instrumentation/instruments.mdx
- docs/source/configuration/telemetry/instrumentation/selectors.mdx
- docs/source/configuration/telemetry/instrumentation/standard-attributes.mdx
- docs/source/configuration/telemetry/overview.mdx
Docs for https://github.com/apollographql/router/issues/4320 (PR https://github.com/apollographql/router/pull/4956):
- Unhide Events page and add to left-nav
- Add telemetry performance trade-off note
> docs: custom events telemetry

- .changesets/feat_geal_coprocessor_urls.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/coprocessor/execution.rs
- apollo-router/src/plugins/coprocessor/mod.rs
- apollo-router/src/plugins/coprocessor/supergraph.rs
- apollo-router/src/plugins/coprocessor/test.rs
- apollo-router/src/services/external.rs
- docs/shared/coproc-typical-config.mdx
- docs/source/customizations/coprocessor.mdx
This makes it possible to have different coprocessor URLs per stage. The initial URL configuration still serves as a global default, but it can be overriden per stage
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. …
> make the coprocessor URL configurable per stage

- .changesets/fix_garypen_router_236_dd_mapping.md
- apollo-router/src/plugins/telemetry/tracing/datadog.rs
The DD exporter does some explicit mapping of attributes and was using a value "apollo.subgraph.name" that the latest versions of the router don't use. The correct choice is "subgraph.name".
Update the mapping to reflect this change.
> Use subgraph.name attribute not apollo.subgraph.name

- apollo-router/src/plugins/demand_control/cost_calculator/fixtures/federated_ships_fragment_query.graphql
- apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
This resolves an issue where fragments were always being scored as costless. The fragment test is now updated to ensure nontrivial fragments (ie. fragments containing objects) receive a nontrivial score.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick …
> Fix fragment scoring

- .changesets/fix_geal_schema_aware_hash_introspection.md
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/query_planner/fetch.rs
- apollo-router/src/query_planner/plan.rs
- apollo-router/src/spec/query.rs
- apollo-router/src/spec/query/change.rs
- docs/source/configuration/telemetry/instrumentation/standard-instruments.mdx
- docs/source/customizations/native.mdx
- docs/source/executing-operations/subscription-support.mdx
Fix #5006
in https://github.com/apollographql/router/pull/4883 we introduced a query hashing scheme that stays stable across schema updates if the update does not affect the query. Unfortunately, it was not taking introspection queries into account.
This fixes the hashing mechanism to add the schema string to hashed data if we encounter an introspection field. This is a temporary fix until we move introspection execution out of query planning. At that point, this hashing mechanism won't ever see introspection fields.
This PR starts from the 1.44.0 tag, since the bug was introduced there. It will be easy to update it to either 1.45 or the latest dev, depending on when we want to ship that fix
---
**Checklist** …
> Use the entire schema when hashing an introspection query

- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
- apollo-router/src/plugins/demand_control/mod.rs
- apollo-router/src/plugins/demand_control/strategy/mod.rs
- apollo-router/src/uplink/testdata/restricted.router.yaml
Before we implement a directive to indicate paging in lists, we are using a statically defined assumed size for lists returned in each response. Since there's no real one-size-fits-all value for this, the initial setup will require users to set an assumed list size in the configuration for the static cost estimator.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration …
> Add list size configuration for static demand control

- .github/workflows/update_apollo_protobuf.yaml
In the same spirit as the existing Apollo Uplink schema automation which exists in https://github.com/apollographql/router/actions/workflows/update_uplink_schema.yml.  This will only allow one PR at a time for this branch name, and only commit changes (and update that branch) when there is a change.
> Update Apollo Protobuf via GitHub Actions PR

- apollo-router/src/plugins/telemetry/apollo_exporter.rs
We'll have a GitHub Action do the maintenance on this file, rather than
having a test remind us that it's stale.  The test results in all PRs (and
all downstream users of this repository) suddenly getting failing tests
every time our infra-team deploys a new version of the proto, whereas the
GitHub Action can be a much more controlled burn.
The GitHub action that replaces this is in [#5030], and we will merge this test just as soon as that is validated.
[#5030]: https://github.com/apollographql/router/pull/5030
> tests: Remove "is proto fresh" test in lieu of GitHub Action

- .circleci/config.yml
In practice, this file actually serves as a cache key for our configuration due to the incorporation of the file's hash in the [key/ID], which I need to bump in order to rotate the cache in CircleCI.  While I'm here, I might as well fix the editor warnings being emitted about this not being a valid version of Xcode, along with some trailing newlines!  While we had '14.2' as the value to bring in patch releases of Xcode, I'd rather we not have that level of indeterminism anyhow, so I'll just make it '14.2.0' which is the latest '14.2' release anyhow.
[key/ID]: https://github.com/apollographql/router/blob/0137e0cf848b9b22ef94fe14b32ed1a082d3f0b5/.circleci/config.yml#L73-L83
> chore/nit: Fix warnings and trailing newlines in CircleCI Config

- apollo-router/tests/common.rs
- apollo-router/tests/integration/lifecycle.rs
This prevents any possibility of port clash, and also doesn't risk the situation where the OS doesn't release the socket in time before it is reused by the router.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If …
> Make integration tests extract the socket address from logs

- .changesets/fix_garypen_router_243_batch_fetch_filter.md
- apollo-router/src/query_planner/plan.rs
- apollo-router/src/services/supergraph/service.rs
Without filtering the query hashes during batch creation we could end up in a situation where we have additional query hashes in the batch.
This manifests itself by batch queries failing with query hashes appearing as committed without ever having been registered in a batch.
Filtering during batch creation is now matching the filtering at subgraph coordination.
> Filter the fetches we add to a batch when we create the batch

- apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__tests__cache_key_metadata.snap
- apollo-router/src/plugins/authorization/tests.rs
---
**Checklist**
**Exceptions**
**Notes**
> add a test to guarantee correct CacheKeyMetadata generation

- docs/source/_redirects
Adds a redirect for the previous metrics URL
> docs: add metrics redirect

- apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
- apollo-router/src/plugins/test.rs
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/query_planner/bridge_query_planner_pool.rs
- apollo-router/src/query_planner/tests.rs
Both of those functions were used to initialize a planner with a new schema, but their implementation diverged with the introduction of the API schema generation and the new planner. THis merges both functions so we use the same code path in all cases
---
**Checklist**
**Exceptions**
**Notes** …
> merge BridgeQueryPlanner new() and new_from_planner()

- apollo-router/src/uplink/license_stream.rs
This increases the timing windows for the `license_expander_claim_pause_claim test`. This test is failing semi regularly particularly on windows as the timer resolution is 15ms.
This test is particularly prone to failure as we are expecting a `want` state to be entered before proceeding.
Hopefully this will improve the reliability of the test.
---
**Checklist**
**Exceptions**
**Notes** …
> Flaky test: license_expander_claim_pause_claim test

- Cargo.toml
Add apollo-federation crate to workspace default members, which are selected by commands like `cargo test` when `-p <package>` or `--workspace` is not used.
> Run federation tests by default

- .changesets/maint_garypen_router_258_update_router_bridge.md
- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/tests/integration/redis.rs
- docs/source/federation-version-support.mdx
- fuzz/Cargo.toml
This lands https://github.com/apollographql/router/pull/5064 onto the release branch
> Update the version of the router-bridge (v1.46.0 version of #5064)

- apollo-federation/src/query_graph/build_query_graph.rs
- apollo-federation/src/query_graph/extract_subgraphs_from_supergraph.rs
- apollo-federation/src/query_graph/graph_path.rs
- apollo-federation/src/query_graph/mod.rs
- apollo-federation/src/query_graph/path_tree.rs
- apollo-federation/src/query_plan/conditions.rs
- apollo-federation/src/query_plan/display.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/query_plan/fetch_dependency_graph_processor.rs
- apollo-federation/src/query_plan/mod.rs
- apollo-federation/src/query_plan/operation.rs
- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/src/query_plan/query_planning_traversal.rs
- apollo-federation/src/schema/field_set.rs
- apollo-federation/src/schema/subgraph_metadata.rs
- apollo-federation/src/subgraph/spec.rs
As discussed in standup a few days ago. I know not everyone was there so feel free to raise objections here too. I thought this might be a nice opportunity to do it since we have very little open work due to the repo move.
We have several things that are called normalization, but the structures actually do not guarantee any of them have been done. They are just the Operation / Selection structures that apollo-federation uses internally, so we should simply call them Operation, SelectionSet, FieldSelection, etc, and convert between apollo-compiler and apollo-federation types at public API boundaries.
> chore(federation): Remove Normalized prefix from operation types

- apollo-router/src/configuration/metrics.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@demand_control.router.yaml.snap
- apollo-router/src/configuration/testdata/metrics/demand_control.router.yaml
Adds config metric for demand control with important settings as attributes.
---
**Checklist**
**Exceptions**
**Notes** …
> Add demand control config metrics

- .github/CODEOWNERS
- apollo-federation/CODEOWNERS
`CODEOWNERS` files in subdirectories don't do anything. this moves the fed-next codeowners into the router's codeowners file, which will request review of apollo-federation folks on new apollo-federation PRs. Do we still want this? I personally would like to continue to get review requests by default just to be able to track things easily in github notifications.
> chore(federation): migrate CODEOWNERS

- apollo-federation/src/query_plan/operation.rs
- apollo-router/src/query_planner/bridge_query_planner.rs
- examples/graphql/supergraph-fed2.graphql
Reproduction which now returns an empty query plan instead of panicking:
```yaml
experimental_query_planner_mode: both
```
```sh
cargo run -- --dev -c router.yaml -s examples/graphql/supergraph-fed2.graphql --log=debug
```
```sh
curl --request POST \
--header 'content-type: application/json' \
--url 'http://127.0.0.1:4000/' \
--data '{"query":"{topProducts {name}}"}'
```
The federation 2 starstuff schema is copied from https://github.com/apollographql/starstuff/blob/cdcdd5a3650d0ddf3dbb5e80f8b0212b5c4fe3ac/supergraph.graphql
> Rust QP: only todo!() in with_normalized_defer if defer is used

- apollo-federation/src/query_graph/condition_resolver.rs
Since `QueryPlanningTraversal` directly implements `ConditionResolver` trait, let's remove the todo stub. Should composition need it in the future (I think it will do the same as `QueryPlanningTraversal` though), we can include it again.
Changelog is not necessary, as this does not affect the router.
> apollo-federation: remove unused impl ConditionResolver for CachingConditionResolver

- apollo-federation/src/source_aware/fetch_dependency_graph/mod.rs
- apollo-federation/src/sources/connect/mod.rs
- apollo-federation/src/sources/graphql/mod.rs
- apollo-federation/src/sources/mod.rs
This PR adjusts for source-aware fetch dependency graphs and query plans to avoid clones (it adds some `Arcs`s around `Vec`s we expect to clone a lot, and uses `Node` around `Value`)
> Adjust data structures in fetch dependency graphs to avoid clones

- apollo-federation/src/sources/connect/mod.rs
- apollo-federation/src/sources/graphql/mod.rs
In #5111 , I forgot to update source-specific fetch dependency graph node data to avoid clones.
> Adjust source-specific fetch dependency graph node to avoid clones (part 2)

- apollo-federation/src/source_aware/federated_query_graph/mod.rs
- apollo-federation/src/sources/connect/mod.rs
This PR copy/pastes the accessor code from non-source-aware query graphs to `FederatedQueryGraph`, as they'll be used in connector fetch dependency graph code.
> Add accessors for common federated query graph data

- .circleci/config.yml
- .config/nextest.toml
- apollo-router-scaffold/src/lib.rs
Nextest by default will try to run a test on each CPU core available. However this isn't suitable for integration tests as the router will be using multiple threads. This is leading to many test failures in CI.  
In addition the scaffold test really shouldn't be run at the same time as any other test as it invokes rustc. This manifests as tests taking 3 minutes or more if they are unlucky enough to get scheduled at the same time.
---
**Checklist**
**Exceptions**
**Notes** …
> chore(tests): provide more threads to each integration test in nextest config

- apollo-federation/src/source_aware/fetch_dependency_graph/mod.rs
- apollo-federation/src/sources/connect/mod.rs
- apollo-federation/src/sources/graphql/mod.rs
- apollo-federation/src/sources/mod.rs
This PR addresses post-merge feedback given in https://github.com/apollographql/router/pull/5111#discussion_r1593506479 . Specifically, it uses slices instead of `Vec`s in `Arc`s for `merge_at`/response paths.
> Use slices instead of vecs in Arcs for `merge_at`

- apollo-federation/src/query_plan/query_planner.rs
An accessor for Rust query planner's API schema.
> apollo-federation: QueryPlanner::api_schema() getter

- apollo-federation/src/query_plan/query_planner.rs
Related to #5093.
We need to have unique keys for query plan cache entries to prevent cache poisoning by routers running different options, either concurrently or event just during a config change.
This is currently possible with the js query planner, but not with the rust query planner because Hash is not implemented.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: …
> Make query planner config implement Hash

- apollo-federation/src/query_plan/operation.rs
- Also, changed its return type to Result<Selection, ...>, instead of
Result<Optional<Selection, ...>>
Related: https://github.com/apollographql/router/pull/5082
---
**Checklist**
> fixed `SelectionSet::make_selection` method to preserve insertion ordering

- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/query_plan/operation.rs
- apollo-federation/src/query_plan/query_planner.rs
Ooookay. It produces a query plan that does key resolution across multiple subgraphs.
Conditions from `@key(fields:)` and other directives are parsed in the context of their subgraph schema. That means we need to rebase them onto the supergraph schema to add them to input selections for fetch dependency nodes. Additionally there was a bug in rebasing that caused the selection set to reference the old schema.
Producing the final FetchNodes relied on `impl From<SelectionSet> for executable::SelectionSet`, which was marked as `todo!()`. We already have a `TryFrom<&SelectionSet>`, so use that instead.
**There are more bugs**: this does **not** appear to actually fetch the `name` field that I asked for. If I find the cause quickly I'll push a fix here otherwise let's do that in a separate PR
> fix(federation): Fix rebasing, fix creating fetch nodes

- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/query_plan/operation.rs
Over time we added some shorthand constructors for operation types, but we also still constructed many things manually. This PR uses some of the existing constructors instead of writing out the whole struct, and adds several more.
In particular I think the spots that had a lot of `)))})` nesting are now easier to read.
The constructors on `Selection` types are also aimed towards usage in tests.
This is a bit of a weird PR since it doesn't have a clear end goal but I already made these changes on another branch to write a test that turned out to be unnecessary. It will also help with tests in https://github.com/apollographql/router/pull/5119.
> chore(federation): add and use some more ergonomic operation types constructors

- apollo-federation/src/query_plan/display.rs
- apollo-federation/src/query_plan/query_planner.rs
`.new_line()` and `.initial_indent_level()` both add indentation to the first line of each selection. This patch special-cases selection set printing so it only uses `.initial_indent_level()` to print indentation.
> fix(federation): fix initial indentation in printed query plans

- apollo-federation/src/source_aware/federated_query_graph/graph_path.rs
- apollo-federation/src/source_aware/federated_query_graph/path_tree.rs
Condition resolution really occurs on the edge's head, and not the edge. `FederatedGraphPath`s don't really make this distinction, and accordingly data for an edge and data for an edge's head are at the same "index". However, `FederatedPathTree`s do make this distinction, separating edge-specific data into `Child`. This PR moves data at the edge's head currently in `Child` upward to the `FederatedPathTree`.
> Move path tree child fields that are on the node to the path tree itself

- apollo-federation/src/sources/connect/json_selection/README.md
- apollo-federation/src/sources/connect/json_selection/parser.rs
Thanks to @lennyburdette's [playground](https://silver-palm-tree-app.vercel.app/), I quickly found a bug with the parsing of `NamedPathSelection`. This PR adds a number of regression tests and fixes the bug.
I updated the [`README.md`](https://github.com/apollographql/router/blob/1db31250ef73137f6ce84d24d33bf42442e12f7c/apollo-federation/src/sources/connect/json_selection/README.md#namedpathselection-) to emphasize the importance of parsing `NamedPathSelection` before `NamedFieldSelection` and `NamedQuotedSelection`, so just read those changes if you're curious why this solution makes sense for a parser like this one.
> [JSONSelection] Fix precedence of parsing `NamedPathSelection` within `NamedSelection` rule

- apollo-federation/src/sources/connect/federated_query_graph/builder.rs
- apollo-federation/src/sources/connect/federated_query_graph/mod.rs
- apollo-federation/src/sources/connect/federated_query_graph/snapshots/apollo_federation__sources__connect__federated_query_graph__builder__tests__it_handles_a_cyclical_schema.snap
- apollo-federation/src/sources/connect/federated_query_graph/snapshots/apollo_federation__sources__connect__federated_query_graph__builder__tests__it_handles_a_nested_schema.snap
- apollo-federation/src/sources/connect/federated_query_graph/snapshots/apollo_federation__sources__connect__federated_query_graph__builder__tests__it_handles_a_simple_schema.snap
- apollo-federation/src/sources/connect/federated_query_graph/snapshots/apollo_federation__sources__connect__federated_query_graph__builder__tests__it_handles_an_aliased_schema.snap
- apollo-federation/src/sources/connect/models/mod.rs
- apollo-federation/src/sources/connect/spec/schema.rs
This commit adds parsed `@connect` directives (modeled as `Connector`) to the query graph for connect-specific graphs. This should make it so that later execution can use the already parsed directive information when constructing requests.
---
**Checklist**
**Exceptions**
**Notes** …
> connect: add `Connector` to query graph

- .changesets/fix_bryn_internal_server_error.md
- apollo-router/src/axum_factory/axum_http_server_factory.rs
- apollo-router/tests/integration/coprocessor.rs
- apollo-router/tests/integration/fixtures/broken_coprocessor.router.yaml
- apollo-router/tests/integration/mod.rs
- apollo-router/tests/integration/snapshots/integration_tests__integration__coprocessor__error_not_propagated_to_client.snap
When an http 500 is returned we should not return the details of the error to the client. 
Instead, they are now logged at ERROR level.
In addition, the error is now returned as a graphql error rather than a plaintext error. This gives a better experience in sandbox.
---
**Checklist**
**Exceptions**
**Notes** …
> fix: return internal errors as structured error responses

- .changesets/fix_bnjjj_fix_custom_events_off.md
- apollo-router/src/plugins/telemetry/config_new/events.rs
- apollo-router/src/plugins/telemetry/testdata/custom_events.router.yaml
- docs/source/configuration/telemetry/instrumentation/events.mdx
Don't create custom events and attributes if you set the level to `off` 
example of configuration:
```yaml
telemetry:
events:
router:
request: info
response: info
error: info
my.disabled_request_event:
message: "my event message"
level: off # Disabled because we set the level to off
on: request
attributes:
http.request.body.size: true
```
---
**Checklist**
**Exceptions**
**Notes** …
> fix(telemetry): do not create custom events if level is off

- docs/source/executing-operations/file-uploads.mdx
Reverts apollographql/router#5167, which reverted the original https://github.com/apollographql/router/pull/4626 by @Meschreiber — I do actually think the failing tests are a result of something _in_ the PR, in the form of docs.  This should be re-analyzed!
> docs: add file uploads

- apollo-federation/src/sources/connect/fetch_dependency_graph/mod.rs
This commit implements the `SourcePathApi` trait for `ConnectPath`, opening the door to adding connect-specific path information to the query planning stack.
---
**Checklist**
**Exceptions**
**Notes** …
> connect: Implement PathApi for connect::federated_query_graph::Path

- apollo-federation/src/sources/connect/fetch_dependency_graph/mod.rs
This PR adds an `apollo_compiler` `Node<>` wrapper around `Value` in `connect::fetch_dependency_graph::Node` (I forgot to do it in a previous PR which added it to other data structure storing arguments). This PR also changes the selection be optional in `connect::fetch_dependency_graph::Node`.
> Adjust connect nodes in fetch dependency graphs

- apollo-federation/src/source_aware/federated_query_graph/builder.rs
- apollo-federation/src/sources/connect/federated_query_graph/builder.rs
This PR enacts changes in the intra-source builder API discussed earlier last week to create a sub-builder, which imposes the restriction that only one source can be added at a time (previously this restriction had to be checked at runtime).
> Update intra-source builder API to restrict source adding

- apollo-federation/src/sources/connect/models/snapshots/apollo_federation__sources__connect__models__validation__test_validate_source__duplicate_source_name.snap
- apollo-federation/src/sources/connect/models/snapshots/apollo_federation__sources__connect__models__validation__test_validate_source__empty_source_name.snap
- apollo-federation/src/sources/connect/models/snapshots/apollo_federation__sources__connect__models__validation__test_validate_source__invalid_chars_in_source_name.snap
- apollo-federation/src/sources/connect/models/snapshots/apollo_federation__sources__connect__models__validation__test_validate_source__source_directive_rename.snap
- apollo-federation/src/sources/connect/models/test_data/source_directive_rename.graphql
- apollo-federation/src/sources/connect/models/validation.rs
This also adopts the new name in error messages, with snapshot tests to confirm!
Also tweaked the error handling for invalid/no name so that other errors are still collected. This shouldn't matter in practice _yet_ because TypeScript should be validating the presence and type of the `name` argument... but this feels more future-proof.
TS side is at https://github.com/apollographql/federation/pull/3007
> Support renaming of `@source` in validation.

- apollo-federation/src/query_graph/mod.rs
- apollo-federation/src/query_graph/path_tree.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/query_plan/operation.rs
- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/src/query_plan/query_planning_traversal.rs
This PR addresses FED-127.
The key function that was ported was [`computeRootSerialDependencyGraph`](https://github.com/apollographql/federation/blob/main/query-planner-js/src/buildPlan.ts#L3600). There are two places where I would like feedback on. I've left comments with my notes. Outside those few lines, everything else is ready for review.
> Port computeRootSerialDependencyGraph

- apollo-federation/src/query_graph/mod.rs
- apollo-federation/src/schema/position.rs
In `position.rs`, we've been adding `From`/`TryFrom`s for `*TypeDefinitionPosition`s as they end up being used. However, since we're working on two separate branches now (`dev` and `connectors`), this leads to merge conflicts if both `dev` and `connectors` add them separately.
This PR adds the missing `From`/`TryFrom`s, and additionally:
- Sorts the `From`/`TryFrom`s
- Updates old code to align on newer patterns  (e.g. `FederationError::internal()` and `r#""#`).
- We also do this for some methods in `impl *TypeDefinitionPosition`s.
- Moves the `TryFrom<QueryGraphNodeType>`s to  `query_graph/mod.rs` (since `QueryGraphNodeType` is more of a query-graph specific type, and the type itself is going away in the source-aware refactor).
> Add missing `From`/`TryFrom`s for schema positions

- apollo-federation/src/sources/connect/fetch_dependency_graph/mod.rs
- apollo-federation/src/sources/connect/json_selection/parser.rs
This commit adds support for adding a path to a connect allowing for JSON selections to be built as the query traverses the connect-specific graph.
---
**Checklist**
**Exceptions**
**Notes** …
> connect: add path to node

- apollo-router/src/query_planner/subgraph_context.rs
PR #5088 changed the signature of a method. It had a green CI run and git succedded at squashing/rebasing it, but the target `dev` branch gained a new call to that method in the mean time so the resulting merge has a compile error.
This would have been prevented if we ran CI on exactly what was about to be pushed to `dev`, instead of only on PR branch. The Rust project calls this [the "not rocket science" rule of software engineering](https://graydon.livejournal.com/186550.html).
> Fix semantic merge conflict with https://github.com/apollographql/router/pull/5088

- apollo-federation/src/source_aware/federated_query_graph/path_tree.rs
- apollo-federation/src/sources/connect/fetch_dependency_graph/mod.rs
- apollo-federation/src/sources/graphql/fetch_dependency_graph/mod.rs
- apollo-federation/src/sources/source/fetch_dependency_graph/mod.rs
This commit implements the method `can_reuse_node` of the `FetchDependencyGraphApi` trait for the connect-specific `FetchDependencyGraph`.
---
**Checklist**
**Exceptions**
**Notes** …
> connect: impl `can_reuse_node` for FetchDependencyGraph

- apollo-federation/src/query_plan/fetch_dependency_graph_processor.rs
- apollo-federation/src/sources/connect/fetch_dependency_graph/mod.rs
This commit implements the `to_cost` method of the `FetchDependencyGraphApi` for the connector-specific fetch graph. For now, that cost is set to a static value mirroring the cost of a fetch in GraphQL so that the query planner can still consistently choose shorter paths when comparing between the two.
Later work might entail looking at the `JSONSelection` itself and calculating a scaling cost based on the selection.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing …
> connect: add static cost to connect fetch

- apollo-federation/src/query_plan/optimize.rs
I just noticed this bug in the code that I merged in https://github.com/apollographql/router/pull/5195. (This is why we need tests. But, tests are coming soon!)
> fixed a logic bug in `check_can_reuse_fragment_and_track_it` (one-liner)

- apollo-federation/tests/query_plan/build_query_plan_support.rs
- apollo-federation/tests/query_plan/build_query_plan_tests.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/named_fragments_preservation.rs
- apollo-federation/tests/query_plan/supergraphs/avoids_unnecessary_fetches.graphql
- apollo-federation/tests/query_plan/supergraphs/handles_non_intersecting_fragment_conditions.graphql
- apollo-federation/tests/query_plan/supergraphs/it_avoid_fragments_usable_only_once.graphql
- apollo-federation/tests/query_plan/supergraphs/it_does_not_try_to_apply_fragments_that_are_not_valid_for_the_subgaph.graphql
- apollo-federation/tests/query_plan/supergraphs/it_handles_fragment_rebasing_in_a_subgraph_where_some_subtyping_relation_differs.graphql
- apollo-federation/tests/query_plan/supergraphs/it_handles_fragment_rebasing_in_a_subgraph_where_some_union_membership_relation_differs.graphql
- apollo-federation/tests/query_plan/supergraphs/it_preserves_directives_when_fragment_is_reused.graphql
- apollo-federation/tests/query_plan/supergraphs/it_preserves_directives_when_fragment_not_used.graphql
- apollo-federation/tests/query_plan/supergraphs/it_works_with_nested_fragments_1.graphql
- apollo-federation/tests/query_plan/supergraphs/it_works_with_nested_fragments_when_only_the_nested_fragment_gets_preserved.graphql
- apollo-federation/tests/query_plan/supergraphs/respects_query_planner_option_reuse_query_fragments.graphql
Part of FED-221, porting some more tests from `query-planner-js/src/__tests__/buildPlan.test.ts`
---
**Checklist**
**Exceptions**
**Notes** …
> Port some more QP tests

- .changesets/exp_experimental_graphql_instruments.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/telemetry/config_new/graphql/attributes.rs
- apollo-router/src/plugins/telemetry/config_new/graphql/selectors.rs
Adds `operation_name` selector and `graphql.operation.name` attribute to graphql metrics.
This is not enabled by default as cardinality could be high, but it does allow graphql operation to be used in selector and therefore conditions.
```
telemetry:
instruments:
graphql:
list.length:
attributes:
graphql.operation.name: true
```
```
telemetry:
instruments:
graphql:
my.field.usage:
unit: "unit"
value: field_unit
condition:
eq:
- operation_name: string
- "ExampleQuery"
type: counter
description: "description"
attributes:
graphql.list.length: true
graphql.field.name: true
graphql.operation.name: true
```
---
**Checklist** …
> Add support for operation name on graphql metrics.

- .changesets/config_bryn_transmit_query_planning_metrics.md
- apollo-router/src/metrics/filter.rs
- apollo-router/src/query_planner/bridge_query_planner_pool.rs
This does not leak any sensitive data, but does allow us to gather metrics on query planner time so that we can see where the rust query planner is making a difference.
REVIEWERS:
* Please check my assertion that no sensitive data is leaked on these metrics.
* Also has `apollo_router.query_planning.warmup.duration` been removed?
---
**Checklist**
**Exceptions**
**Notes**
[^2]: …
> Sending query planner metrics to Apollo

- .changesets/fix_renee_lifecycle_metric.md
- apollo-router/src/metrics/filter.rs
Rust API schema generation was enabled by default in #4931, but the metrics were not making it to us.
This change affects two metrics:
- `apollo.router.lifecycle.api_schema`
- `apollo.router.lifecycle.license`
Reviewers please check that it's okay for `.license` to be submitted as well.
Fixes ROUTER-332
> Submit `lifecycle` metrics to Apollo

- apollo-federation/tests/query_plan/build_query_plan_tests/named_fragments_preservation.rs
- apollo-federation/tests/query_plan/supergraphs/respects_query_planner_option_reuse_query_fragments_false.graphql
- apollo-federation/tests/query_plan/supergraphs/respects_query_planner_option_reuse_query_fragments_true.graphql
Reproduction: `cargo test -p apollo-federation -- -q`
https://github.com/apollographql/router/pull/5157 introduced a new kind of snapshot test for the Rust query planner. Test schemas are specified as sets of subgraph schemas, so composing them is needed. Since we don’t have composition in Rust yet, the tests rely on JS composition through Rover. To avoid a dependency on Rover on CI and for most contributors, the composed supergraph are cached in the repository. Rover use is opt-in and only required when a cached file is missing or out of date. (Composition inputs are hashed.)
The file name is derived (through a macro) from the test function name. To detect name conflicts, a static `OnceLock<Mutex<HashSet<&'static str>>>` is used to ensure no name is used more than once.
The static hash …
> Fix running `cargo test` without nextest

- apollo-federation/src/sources/connect/fetch_dependency_graph/mod.rs
- apollo-federation/src/sources/connect/json_selection/mod.rs
- apollo-federation/src/sources/connect/json_selection/parser.rs
- apollo-federation/src/sources/connect/json_selection/pretty.rs
Fixes an issue where a path with a variable would duplicate the $.
---
**Checklist**
**Exceptions**
**Notes**
> json_selection: fix pretty print duplicate $

- .changesets/fix_bnjjj_fix_5173.md
- apollo-router/src/plugins/telemetry/mod.rs
If a metric has too high a cardinality the following warning will be displayed as a warning instead of an errorl:
`OpenTelemetry metric error occurred: Metrics error: Warning: Maximum data points for metric stream exceeded/ Entry added to overflow`
Fixes #5173 
---
**Checklist**
**Exceptions**
**Notes** …
> fix(telemetry): metrics overflow is logged as a warning rather than error

- apollo-federation/src/sources/connect/fetch_dependency_graph/mod.rs
- apollo-federation/src/sources/connect/json_selection/pretty.rs
This PR implements the simplification of `PrettyPrintable::pretty_print[_with_indentation]` that I described in https://github.com/apollographql/router/pull/5248#discussion_r1617870171.
Thanks to @nicholascioli for adding a bunch of tests in PR #5248, which allowed me to make these changes confidently.
> Simplify `PrettyPrintable::pretty_print[_with_indentation]` method signatures

- apollo-federation/src/query_plan/operation.rs
- apollo-federation/src/query_plan/optimize.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/named_fragments_preservation.rs
Added `normalize` call in `normalize_operation`.
Fixed a bug in NamedFragments::reduce
- normalize selection sets after retain_fragments call
Fixed InlineFragmentSelection::normalize
- Normalize sub-selections with the correct type
Sorry for mixing a few different changes in this PR. Unfortunately, those issues are intertwined in tests. Gathering them in one PR to minimize spurious test changes.
This depends on https://github.com/apollographql/router/pull/5284 in order to pass all tests.
This PR will improve a few tests failing in https://github.com/apollographql/router/pull/5214.
---
**Checklist**
> Fixed a few normalize issues

- .changesets/fix_bnjjj_fix_selector_context.md
- apollo-router/src/plugins/telemetry/config_new/attributes.rs
- apollo-router/src/plugins/telemetry/config_new/conditional.rs
- apollo-router/src/plugins/telemetry/config_new/conditions.rs
- apollo-router/src/plugins/telemetry/config_new/cost/mod.rs
- apollo-router/src/plugins/telemetry/config_new/events.rs
- apollo-router/src/plugins/telemetry/config_new/extendable.rs
- apollo-router/src/plugins/telemetry/config_new/fixtures/router/custom_counter_on_error/metrics.snap
- apollo-router/src/plugins/telemetry/config_new/fixtures/router/custom_counter_on_error/router.yaml
- apollo-router/src/plugins/telemetry/config_new/fixtures/router/custom_counter_on_error/test.yaml
- apollo-router/src/plugins/telemetry/config_new/graphql/attributes.rs
- apollo-router/src/plugins/telemetry/config_new/graphql/selectors.rs
- apollo-router/src/plugins/telemetry/config_new/instruments.rs
- apollo-router/src/plugins/telemetry/config_new/mod.rs
- apollo-router/src/plugins/telemetry/config_new/selectors.rs
- apollo-router/src/plugins/telemetry/mod.rs
It gives the ability to configure custom instruments like this:
```yaml
http.server.request.timeout:
type: counter
value: unit
description: "request in timeout"
unit: request
attributes:
graphql.operation.name:
response_context: operation_name
condition:
eq:
- "request timed out"
- error: reason
```
---
**Checklist**
**Exceptions**
**Notes** …
> fix(telemetry): add support of response_context selector when it's in error

- Cargo.lock
- apollo-federation/Cargo.toml
- apollo-federation/src/query_graph/extract_subgraphs_from_supergraph.rs
- apollo-federation/src/schema/position.rs
- apollo-federation/src/source_aware/federated_query_graph/builder.rs
- apollo-federation/src/sources/graphql/federated_query_graph/builder.rs
- apollo-federation/src/sources/graphql/federated_query_graph/mod.rs
- apollo-federation/src/sources/graphql/federated_query_graph/schemas/simple.graphql
- apollo-federation/src/sources/graphql/mod.rs
- apollo-federation/src/sources/source/mod.rs
This PR addresses FED-200, which outlines the implementation of `FederatedQueryGraphBuilderApi::process_subgraph_schema` for `FederatedQueryGraphBuilder`.
I want to point out that I added a dependency to the `either` crate. This was already a transitive dependency (used by `itertools`). It was helpful for this implementation. I also noticed that it would be useful in other places as well. For example, it would be nice to have a method like `FederationSchema::possible_runtime_types` but which returned a non-consuming iterator rather than a freshly allocated `IndexSet`. Since `either::Either` implements iterator so long as both sides are iterators, we could copy the existing `possible_runtime_types` method and use `Either`s for each branch. I'm sure there are other places where we could …
> Implemented FederatedQueryGraphBuilderApi::process_subgraph_schema for FederatedQueryGraphBuilder

- apollo-federation/src/query_plan/operation.rs
- apollo-federation/tests/query_plan/build_query_plan_tests.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/named_fragments_preservation.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/provides.rs
The issue was that add_selection could set its sub-selection items' parent type as their originating parent type, instead of the rebased parent type (`self.type_position`).
This is the real fix for FED-230.
Fixed crashes in tests
- `it_handles_fragment_rebasing_in_a_subgraph_where_some_subtyping_relation_differs` (in named_fragments_preservation.rs)
- `it_works_on_interfaces` (in provides.rs)
---
**Checklist**
**Exceptions**
**Notes** …
> fixed SelectionSet::add_selection to set its member's parent type consistently

- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/query_plan/operation.rs
- apollo-federation/src/query_plan/optimize.rs
- removed Selection::from_inline_fragment method, since `new` is more direct.
- moved the assertion check in `from_inline_fragment` into the `new`.
- refactored calls to the removed method
- refactored all direct InlineFragmentSelection construction to use `new`.
- fixed a few `InlineFragmentSelection` generation code with potentially wrong sub-selection type. (But, no tests are affected at this time.)
---
**Checklist**
**Exceptions**
**Notes** …
> added InlineFragmentSelection::new constructor

- apollo-federation/src/query_plan/query_planning_traversal.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/requires/include_skip.rs
This PR fixes a bug where recursive query planning would ignore conditionals (`@skip`/`@include`).
> Fix bug where recursive query planning ignored conditionals

- apollo-federation/src/query_graph/graph_path.rs
`OperationConditional` is already cheap to clone.
The `Arc<Vec<>>` inside `OpGraphPathContext` is also a little smelly but removing it would cause a lot of copying at the moment.
> chore(federation): remove unnecessary Arc around OperationConditional

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/src/query_plan/query_planning_traversal.rs
- apollo-federation/src/schema/definitions.rs
- apollo-federation/tests/query_plan/build_query_plan_tests.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/interface_type_explosion.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/merged_abstract_types_handling.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/named_fragments_preservation.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/provides.rs
- Several tests have improved.
- One snapshot failure became an assert_eq failure, but that's a known issue.
- Some expected plans were missing `__typename` lines. I added them since the JS version of their tests have it.
Fixes FED-239
---
**Checklist**
**Exceptions**
**Notes** …
> FED-239: fixed and simplified `subselection_type_if_abstract`

- apollo-federation/src/query_graph/extract_subgraphs_from_supergraph.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/handles_fragments_with_directive_conditions.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/handles_operations_with_directives.rs
- apollo-federation/tests/query_plan/supergraphs/fragment_with_intersecting_parent_type_and_directive_condition.graphql
- apollo-federation/tests/query_plan/supergraphs/nested_fragment_with_interseting_parent_type_and_directive_condition.graphql
This PR:
- Fixes a bug in subgraph extraction where directives weren't being pre-inserted, leading to errors when subgraphs declared user-defined executable directives.
- Fixes a bug in tests where directives are being declared on `FRAGMENT_SPREAD` when they should really be declared on `INLINE_FRAGMENT` (the JS wasn't catching this for some reason, but the Rust validations did).
This PR updates tests that were encountering this pre-insertion error.
- The tests in `handles_fragments_with_directive_conditions.rs` now encounter a different error, more similar to FED-263 (which has been updated to include this file).
- The tests in `handles_operations_with_directives.rs` also now encounter a different error, which is specific to the functionality under test. FED-285 has been created to track …
> Fix bug in subgraph extraction where directives weren't pre-inserted

- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/error.rs
- apollo-router/src/plugins/file_uploads/rearrange_query_plan.rs
- apollo-router/src/plugins/record_replay/recording.rs
- apollo-router/src/plugins/record_replay/replay.rs
- apollo-router/src/plugins/rhai/engine.rs
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/query_planner/caching_query_planner.rs
- apollo-router/src/query_planner/convert.rs
- apollo-router/src/query_planner/plan.rs
- apollo-router/src/query_planner/tests.rs
- apollo-router/src/services/supergraph/service.rs
Before this PR on query plan cache miss we would, sequentially:
* Run the Rust QP
* Run the JS QP
* Compare results
* Return the result from JS
After this PR, in the main code path:
* Run the JS QP
* Spawn a background job with that result (shared in `Arc`) and the input document
* Return the result from JS
Meanwhile, the Rust QP and the result comparison runs in the background on a dedicated thread pool. Jobs are dropped if the bounded queue is full. To limit resource consumption at the moment the "pool" is a single thread, and the queue size is 10. Both of these parameters are `const` items in the code (not exposed in Router YAML config at this time).
To try it out, create a `router.yaml` file:
```yaml
experimental_query_planner_mode: both
```
Then run:
```
cargo run -- --dev -c …
```
> Move QP "both" mode comparison to a background thread with bounded queue

- CHANGELOG.md
In theory https://github.com/apollographql/router/releases/tag/v1.40.0 was the first version in which this was fixed, but we don't recommend running that version for the reasons that are already noted in the CHANGELOG.md.
Therefore, the first version that we recommend using to utilize custom historgrams is https://github.com/apollographql/router/releases/tag/v1.46.0.  This updates the CHANGELOG.md to signal that with a note and a duplication of the original CHANGELOG entry.
Original Issue: https://github.com/apollographql/router/issues/4543
Initial PR: https://github.com/apollographql/router/pull/4572
Stabilizing PR: https://github.com/apollographql/router/pull/4771
> chore(docs): Replicate custom histograms CHANGELOG to v1.46.0.

- .changesets/maint_bryn_disable_tests_apollo_key_missing.md
- apollo-router/tests/common.rs
- apollo-router/tests/integration/coprocessor.rs
- apollo-router/tests/integration/redis.rs
- apollo-router/tests/integration/telemetry/metrics.rs
A number of tests require APOLLO_KEY and APOLLO_GRAPH_REF to be present to execute successfully.
These are now skipped if these are not present.
---
**Checklist**
**Exceptions**
**Notes** …
> Disable GraphOS tests when apollo key not present

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/query_graph/graph_path.rs
- apollo-federation/tests/query_plan/build_query_plan_tests.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/interface_object.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/interface_type_explosion.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/named_fragments.rs
In add_at_path, we rebase sub-selections, but didn't rebase the current element itself.
The JS version's workflow is a bit different. It constructs a new field without rebasing and then call normalize, which rebases as well.
Fixes https://apollographql.atlassian.net/browse/FED-251 (partially)
There are some failures with the same error message remain, but the issue seems to be in the fetch dependency graph, instead (visiting wrong subgraph).
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. …
> fix: fixed `add_at_path` to rebase incoming `element`

- apollo-federation/src/operation/contains.rs
- apollo-federation/src/operation/mod.rs
This PR fixes equality/hash logic for operation elements. Specifically:
1. Equality shouldn't care about order in map-likes (i.e. argument order in fields and directives, and field order in object values).
1.  The previous code for key equality used sorted arguments in directives, but it wasn't recursively sorting values in directive arguments.
2. The previous code for field/inline fragment/fragment spread equality wasn't comparing using sorted map-likes.
3.  As part of fixing the above, the new code has added a `sorted_arguments` field to `Field`.
2. Equality shouldn't care about directive order (this is specifically a choice of federation, and not GraphQL).
1. The previous code for key equality wasn't sorting directives.
2. The previous code for field/inline fragment/fragment spread …
> Fix equality-checking logic for operation elements

- apollo-federation/tests/query_plan/build_query_plan_tests/field_merging_with_skip_and_include.rs
It turns out https://github.com/apollographql/router/pull/5343 fixed FED-242, but the final order of the `@skip`/`@include` directives has changed. Given that the order shouldn't have mattered to begin with, this difference with the JS codebase is probably fine.
To be clear, we maintain the user's directive order when there's not multiple equal fields with different directive order; when there are such fields, we have to pick some user order for the subgraph query for the sake of merging, and it appears that's changed in the Rust code. However, it's unlikely for users to have cared about which one got picked, given that they would have viewed merging the fields itself as a bug if they cared about directive order. Long-term, there is a strategy to assist users who care about directive …
> Update skip/include merging test to change order

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/operation/optimize.rs
- apollo-federation/src/operation/rebase.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/merged_abstract_types_handling.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/requires.rs
Adds debug assertions to ensure that we point to the same schemas/type positions when constructing/modifying `SelectionSet`s.
Bug fixes
* when rebasing inline fragments we were not checking whether we point to the same schema
* when rebasing inline fragments we were not updating target schema
* when adding selections through `add_at_path` we were not checking for `None`/empty selection sets for composite types (i.e. invalid selection sets that don't have anything to merge)
* add back removal of "unnecessary" inline fragments to `add_at_path` flow (as we should only apply it if we have a single path element)
Fixes 
* [FED-241](https://apollographql.atlassian.net/browse/FED-241)
* [FED-248](https://apollographql.atlassian.net/browse/FED-248)
* …
> fix(federation): selection set modification fixes

- apollo-federation/tests/query_plan/build_query_plan_tests.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/merged_abstract_types_handling.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/named_fragments.rs
- apollo-federation/tests/query_plan/supergraphs/another_mix_of_fragments_indirection_and_unions.graphql
- apollo-federation/tests/query_plan/supergraphs/can_reuse_fragments_in_subgraph_where_they_only_partially_apply_in_entity_fetch.graphql
- apollo-federation/tests/query_plan/supergraphs/can_reuse_fragments_in_subgraph_where_they_only_partially_apply_in_root_fetch.graphql
- apollo-federation/tests/query_plan/supergraphs/does_not_error_out_handling_fragments_when_interface_subtyping_is_involved.graphql
- apollo-federation/tests/query_plan/supergraphs/handles_case_of_key_chains_in_parallel_requires.graphql
- apollo-federation/tests/query_plan/supergraphs/handles_fragments_with_interface_field_subtyping.graphql
- apollo-federation/tests/query_plan/supergraphs/handles_mix_of_fragments_indirection_and_unions.graphql
- apollo-federation/tests/query_plan/supergraphs/handles_spread_unions_correctly.graphql
- apollo-federation/tests/query_plan/supergraphs/handles_types_with_no_common_supertype_at_the_same_merge_at.graphql
- apollo-federation/tests/query_plan/supergraphs/interface_interface_interaction.graphql
- apollo-federation/tests/query_plan/supergraphs/interface_interface_interaction_but_no_need_to_type_explode.graphql
- apollo-federation/tests/query_plan/supergraphs/interface_union_interaction.graphql
- apollo-federation/tests/query_plan/supergraphs/interface_union_interaction_but_no_need_to_type_explode.graphql
- apollo-federation/tests/query_plan/supergraphs/it_executes_mutation_operations_in_sequence.graphql
- apollo-federation/tests/query_plan/supergraphs/key_where_at_external_is_not_at_top_level_of_selection_of_requires.graphql
- apollo-federation/tests/query_plan/supergraphs/union_interface_interaction.graphql
- apollo-federation/tests/query_plan/supergraphs/union_interface_interaction_but_no_need_to_type_explode.graphql
- apollo-federation/tests/query_plan/supergraphs/union_union_interaction.graphql
- apollo-federation/tests/query_plan/supergraphs/union_union_interaction_but_no_need_to_type_explode.graphql
Addresses FED-249
Updated the snapshots of a few tests where the parallel query nodes were out of order. The solution to these tests was to update the snapshot.
There is one test ([here](https://github.com/apollographql/router/blob/fe84831a643548e6d1bd3762cc121885063272e0/apollo-federation/tests/query_plan/build_query_plan_tests/merged_abstract_types_handling.rs#L785)) called out in the ticket that is caused by a different issue. This issue is addressed by the changes in @duckki 's [PR for FED-55](https://github.com/apollographql/router/pull/5345).
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming …
> Update a few snapshots with out of order `Parallel` nodes

- apollo-router/src/router_factory.rs
- apollo-router/src/services/layers/query_analysis.rs
- apollo-router/src/testdata/supergraph_with_context.graphql
- apollo-router/src/testdata/supergraph_with_override_label.graphql
A follow up to #5335
Just to ensure we are not rejecting acceptable supergraphs, along with the correct directive name used for in progressive overrides search.
> add some tests for experimental_query_planner_mode unsupported feature rejections, 

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/operation/rebase.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/src/query_plan/query_planning_traversal.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/interface_type_explosion.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/introspection_typename_handling.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/merged_abstract_types_handling.rs
This PR:
- Makes bugfixes to `selection_set_is_fully_local_from_all_nodes()`.
- It was only checking for inconsistent abstract types at top-level, when it should be checking every element.
- I've added a method called `any_element()` to help facilitate this (this was called `some()` in the JS codebase).
- The call to `can_rebase_on()` wasn't checking whether the selection set could be rebased on the node's schema.
- As a matter of efficiency, we should early return when the node's `has_reachable_cross_subgraph_edges` is `true`, as it's much faster to check than rebasing. I've accordingly rearranged the checks so it's first (mirroring the JS codebase).
- Similarly for efficiency, the JS codebase had ordered the check for inconsistent abstract runtime types until after rebasing. I've …
> Fix bugs in selection set locality checking and inconsistent abstract type checking

- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/query_planner/fetch.rs
The default apollo-compiler serialization includes is indented like this:
```graphql
{
topProducts {
name
}
}
```
This change the Rust query planner to use the "no indent" style for subgraph operations in fetch nodes, which looks like this:
```graphql
{ topProducts { name } }
```
There is no line break or indentation, but some whitespace is still used for readability so it still differs from the JS query planner which minimizes whitespace: `{topProducts{name}}`.
This PR merely reduces the amount of bytes on the network (or amount of work given to compression). Before removing Deno entirely we’ll likely want serialization to match that of JS exactly, because tests using `MockSubgraph` rely on a mapping of exact subgraph query string to response to supply.
---
**Checklist**
Complete the …
> Rust QP: serialize subgraph operations without line breaks or indentation

- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/src/query_plan/query_planning_traversal.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/debug_max_evaluated_plans_configuration.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/interface_type_explosion.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/introspection_typename_handling.rs
Fixes most of FED-272
To avoid the risk of incrementing a cloned counter and then dropping it, this PR removes `derive(Clone)` on `QueryPlanningStatistics` and pass it around by reference instead.
I tried make this a `&mut QueryPlanningStatistics` exclusive reference, but that would require changing every use of `&QueryPlanningParameters` to be a `&mut` exclusive reference too.
This proved difficult as parameters are shared in multiple places.
Instead, the counter is now a `Cell<usize>` so that it can be incremented through a shared reference.
This causes `QueryPlanningStatistics` and `QueryPlanningParameters` to be `!Sync` but that’s ok: they only exist within one single-threaded call to `build_query_plan()`.
The `QueryPlanner` itself is still `Sync` and multiple threads can run separate …
> Implement evaluated_plan_count statistic

- apollo-federation/src/operation/optimize.rs
- apollo-federation/src/operation/rebase.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/named_fragments_preservation.rs
JS code applies [normalization](https://github.com/apollographql/federation/blob/main/internals-js/src/operations.ts#L1462) on the rebased fragment definitions that eliminates the unnecessary inline spreads.
Fixes #[FED-261](https://apollographql.atlassian.net/browse/FED-261)
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is an important part of many changes. …
> fix(federation): normalize rebased fragment definitions

- apollo-federation/src/operation/rebase.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/query_plan/query_planning_traversal.rs
- apollo-federation/tests/query_plan/build_query_plan_tests.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/merged_abstract_types_handling.rs
This PR fixes a few separate issues in `can_rebase_on()` and `can_add_to()`:
- In `FieldSelection.can_add_to()`, when recursing into the selection set, the wrong type position was passed in (it should be the base type of the field's return type, not the field's parent type).
- In `Field.type_if_added_to()`, the result was mistakenly being converted to a `CompositeTypeDefinitionPosition` when it should be an `OutputTypeDefinitionPosition`.
- In `Field.can_rebase_on()`, the wrong schema was being passed into the call to `is_interface_object()` (it should be the field's, based on the JS code).
- In `InlineFragmentData.can_rebase_on()`, the wrong schema was being passed in when getting the casted type and executing `runtime_types_intersect()` (it should be the schema of the given parent type, …
> Fix various bugs in `can_rebase_on()` and `can_add_to()`

- .changesets/fix_bryn_demand_control_formatting_hot_path.md
- apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
The following pattern was being used in the hot path for demand control:
```
field.inner_type_def(schema).ok_or(
DemandControlError::QueryParseFailure(format!(
"Field {} was found in query, but its type is missing from the schema.",
field.name
))
)?;
```
This was causing formatting and heap allocations for every visit of a field.
Changed to:
```
field.inner_type_def(schema).ok_or_else(|| {
DemandControlError::QueryParseFailure(format!(
"Field {} was found in query, but its type is missing from the schema.",
field.name
))
})?;
```
Surprised clippy didn't notice this
Flamegraph before:
demand-control-instrumented | basic | 4608 | 4000 | 7000 | True | 6 | 501 | 78.637681
-- | -- | -- | -- | -- | -- | -- | -- | --
After:
simulation | scenario | rps | minRps | maxRps | success | min_latency_ms …
> Prevent formatting in hot path

- apollo-federation/src/query_plan/query_planning_traversal.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/debug_max_evaluated_plans_configuration.rs
- apollo-federation/tests/query_plan/supergraphs/multiplication_overflow_in_reduce_options_if_needed.graphql
The first commit shows the test failing.
This method is all about bringing this number down, so we use `usize::MAX` to represent values that overflowed and recompute as needed.
---
**Checklist**
**Exceptions**
**Notes** …
> Fix integer overflow in QP reduce_options_if_needed

- RELEASE_CHECKLIST.md
Some additional improvements/bug-fixes to the docs:
- During the final publish, the `apollo-federation` package also has to be published
- Chain multi-line commands together conditionally, per convention and previous pain-point, in order to avoid the off chance of "one failed, but the second one worked".
- Add the missing `--auto` and `--merge` flags to the Reconcile dev step.
> chore: Update RELEASE_CHECKLIST.md

- apollo-federation/src/api_schema.rs
- apollo-federation/src/schema/mod.rs
`FederationSchema` requires that the schema isn't modified behind its back. Otherwise the referencers may get out of sync. With `schema_mut()`, you could modify types directly and cause bugs.
Only API schema was using this function. It doesn't use it in a way that would affect referencers, but the method should still not exist. Here I replaced it by unwrapping the schema and then re-wrapping it after API schema has done its thing. It means referencers will be re-computed, but all in all that's not the biggest issue in the world.
> chore(federation): remove `FederationSchema::schema_mut`

- apollo-federation/src/query_graph/graph_path.rs
Before https://github.com/apollographql/router/pull/5402, some combinations of schema and query would cause `flat_cartesian_product` to compute `num_options == 1 << 44` and try to allocate 211 terabytes in `Vec::with_capacity`. The heap allocation failed, which made `Vec` abort the process.
Even if we avoided the abort somehow, `flat_cartesian_product` would then go on to try to build trillions of items and take excessive time and/or memory.
This PR makes `flat_cartesian_product` if the number of items exceeds an arbitrary limit of one million items. This is **untested**, since https://github.com/apollographql/router/pull/5402 already fixed our know reproduction case. If another case is found please add a test.
> Return an error in case of excessive cartesian product size

- apollo-federation/src/query_graph/graph_path.rs
This PR fixes a bug in `OpGraphPath.advance_with_operation_element()` where, when dealing with a field on an interface type, type explosion was mistakenly performed when it shouldn't have been.
> Fix bug in `advance_with_operation_element()` where type explosion should be avoided

- .changesets/feat_bnjjj_add_missing_units_desc_instruments.md
- apollo-router/src/plugins/telemetry/config_new/fixtures/router/attribute.error.type/metrics.snap
- apollo-router/src/plugins/telemetry/config_new/fixtures/router/attribute.on_graphql_error/metrics.snap
- apollo-router/src/plugins/telemetry/config_new/fixtures/router/http.server.active_requests/metrics.snap
- apollo-router/src/plugins/telemetry/config_new/fixtures/router/http.server.request.body.size/metrics.snap
- apollo-router/src/plugins/telemetry/config_new/fixtures/router/http.server.request.body.size_with_custom_attributes/metrics.snap
- apollo-router/src/plugins/telemetry/config_new/fixtures/router/http.server.request.duration/metrics.snap
- apollo-router/src/plugins/telemetry/config_new/fixtures/router/http.server.request.duration_with_custom_attributes/metrics.snap
- apollo-router/src/plugins/telemetry/config_new/fixtures/router/http.server.response.body.size/metrics.snap
- apollo-router/src/plugins/telemetry/config_new/instruments.rs
This PR adds description and units to standard instruments available in the router. These descriptions and units have been copy pasted directly from the [OpenTelemetry semantic conventions](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/) and are needed for better integrations with APMs.
---
**Checklist**
**Exceptions**
**Notes** …
> feat(telemetry): add description and units to standard instruments

- apollo-federation/src/operation/rebase.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/schema/mod.rs
- apollo-federation/src/schema/position.rs
While reviewing #5401, I noticed we had some bugs when checking for interface objects. This PR:
- Fixes a bug in `compute_input_rewrites_on_key_fetch()` where it was passing the wrong schema in when checking whether a type was an interface object.
- Note that this required adding an argument to `add_post_require_inputs()`, which then caused Clippy to complain about there being too many arguments. I've accordingly split some of the arguments out into a separate struct.
- Fixes a bug in `is_interface_object_type()` where it silently ignores if the type doesn't exist, or if the `@interfaceObject` directive definition is missing. 
- This requires changing it and some upstream callers to return `Result`s.
- Fixes a bug in `is_useless_node()` where it silently ignores if a node or its subgraph …
> Fix bugs in interface object checking

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/query_plan/mod.rs
- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/tests/query_plan/build_query_plan_tests.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/subscriptions.rs
- apollo-federation/tests/query_plan/supergraphs/defer_gets_stripped_out.graphql
Currently, the Rust QP does not handle `@defer`. Because of this, the private preview needs to strip out the use of this directive. This is requires implementing `Operation::without_defer` and ensuring that, while building the query plan, this method is called regardless of config.
Fixes FED-293
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is an important part …
> Implemented `Operation::without_defer`

- apollo-federation/src/sources/connect/mod.rs
- apollo-federation/src/sources/connect/models/mod.rs
- apollo-federation/src/sources/connect/models/test_data/absolute_connect_url_with_source.graphql
- apollo-federation/src/sources/connect/models/test_data/invalid_connect_url.graphql
- apollo-federation/src/sources/connect/models/test_data/invalid_connect_url_scheme.graphql
- apollo-federation/src/sources/connect/models/test_data/missing_connect_on_query_field.graphql
- apollo-federation/src/sources/connect/models/test_data/missing_source_import.graphql
- apollo-federation/src/sources/connect/models/test_data/relative_connect_url_without_source.graphql
- apollo-federation/src/sources/connect/models/test_data/renamed_connect_directive.graphql
- apollo-federation/src/sources/connect/models/test_data/valid_connect_absolute_url.graphql
- apollo-federation/src/sources/connect/models/validation.rs
Includes:
* Require that all fields on `Query` have a `@connect`
* Check for relative vs absolute URLs in `@connect` are applied correctly, depending on whether a `source` is set
* Provide a warning if it looks like users are trying to use a source, but didn't import the directive (since this is usually a mistake)
Because there is now a warning, there's also refactoring to make this a little closer to fbp-style build messages with severity (instead of only errors).
(recreation of #5355)
> More `@connect` validations

- apollo-federation/src/error/mod.rs
- apollo-federation/src/lib.rs
- apollo-federation/src/merge.rs
- apollo-federation/src/operation/mod.rs
- apollo-federation/src/query_graph/extract_subgraphs_from_supergraph.rs
- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/src/schema/mod.rs
Instead of panicking with `todo!()`, return an error.
A lot of these were only coming from composition call sites as far as I could tell, but I'd rather not have the todos and have redundant errors in places than a panic. 
I added an explicit `UnsupportedFederationVersion` error kind to `SingleFederationError`. It's `ErrorCode` placement is the very last, so shouldn't mess up the numbering there. I prefer to be extra explicit here rather than returning `Internal`. 
The `MergeFailure` had to be turned to `Vec<String>`, I didn't really feel like dealing with `Vec<&str>` (which we shouldn't have had in the first place) when trying to do a `From`. That entire module's error handling will have to be reworked anyways, this just makes it more straightforward to convert for that todo.
> fix(federation): turn todos into SingleFederationError

- .changesets/docs_bnjjj_docs_standard_instr.md
- docs/source/configuration/telemetry/instrumentation/instruments.mdx
Added documentations about standard instruments available at the subgraph service:
* `http.client.request.body.size` - A histogram of request body sizes for requests handled by subgraphs.
* `http.client.request.duration` - A histogram of request durations for requests handled by subgraphs.
* `http.client.response.body.size` - A histogram of response body sizes for requests handled by subgraphs.
These instruments are configurable in `router.yaml`:
```yaml title="router.yaml"
telemetry:
instruments:
subgraph:
http.client.request.body.size: true # (default false)
http.client.request.duration: true # (default false)
http.client.response.body.size: true # (default false)
```
---
**Checklist** …
> docs(telemetry): add docs about standard instruments for subgraph

- apollo-federation/src/sources/connect/mod.rs
- apollo-federation/src/sources/connect/models/mod.rs
- apollo-router/src/plugins/connectors/handle_responses.rs
- apollo-router/src/plugins/connectors/make_requests.rs
- apollo-router/src/plugins/connectors/mod.rs
- apollo-router/src/services/connector_service.rs
After we switch the router services to use Connectors generated in expand_connectors(), we can start using these functions and delete:
* src/plugins/connectors/response_formatting/ — will be replaced with apply_with_selection
* src/plugins/connectors/finder_field.rs — not necessary in single-phase query planning!
* src/plugins/connectors/http_json_transport.rs — saving the part that use the new Transport
* src/plugins/connectors/request_inputs.rs — didn't need to be its own module
* src/plugins/connectors/request_response.rs
This version leaves out some functionality:
* instrumentation, logging, and json selection diagnostics
* alias and __typename handling (beyond the root output type)
we should address both of these when we add JSONSelection::apply_with_selection or whatever we're going …
> new versions of make_requests and handle_responses that use apollo-federation's Connector

- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/interface_object.rs
FED-251 is actually a symptom of several different root causes.
This PR is relatively clear-cut case, but others need a more closer look.
Partially fixes https://apollographql.atlassian.net/browse/FED-251
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick …
> FED-251: fixed a (type-position, schema) inconsistency in `compute_nodes_for_key_resolution`

- apollo-federation/src/operation/mod.rs
Paired on this with @dariuszkuc 
This PR fixes a bug in selection set equality checking where it compares the schema and selection set's type when it shouldn't.
Note that we encountered this bug when discovering that condition exclusion wasn't working as expected. With this bugfix, computing how to jump to each subgraph should be much faster when there are many subgraphs.
> Fix bug in selection set equality checking

- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/interface_object.rs
This PR fixes a bug where, during query planner construction, the interface types that are interface objects (in at least one subgraph schema) are computed incorrectly. This ends up fixing one particular snapshot test.
> Fix bug in interface object type collection during query planner construction

- apollo-federation/src/query_graph/graph_path.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/requires.rs
This PR fixes a small logic bug in filter_on_schema.
4 of the requires.rs test failures are gone.
---
**Checklist**
**Exceptions**
**Notes** …
> fix: fixed filter_on_schema

- apollo-federation/src/query_plan/query_planner.rs
- The test doesn't need to be ignored anymore, since It's no longer crashing.
- However, the expected snapshot was not correct.
- I generated a query plan from JS federation and it matched the Rust output!
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick …
> test: updated `plan_simple_root_field_query_for_multiple_subgraphs` test

- apollo-federation/src/operation/tests/mod.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/fragment_autogeneration.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/handles_operations_with_directives.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/interface_object.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/introspection_typename_handling.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/merged_abstract_types_handling.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/named_fragments.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/provides.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/requires.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/requires/include_skip.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/subscriptions.rs
- Dropped outdated comments
- Added more description to the existing failure comments.
---
**Checklist**
**Exceptions**
Only comments were updated.
**Notes** …
> refactor: Updated/added the comments on tests

- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/interface_object.rs
The `inputs_for_require` looked different from JS counterpart ([permalink](https://github.com/duckki/federation/blob/bbf83946800d0e6f83307e1941cd7052f8a3c38d/query-planner-js/src/buildPlan.ts#L4762)). I fixed that.
That eliminates the remaining FED-251 test failures. They turned into snapshot assertion failures, but they looked like a condition fetch issue (the final entity fetch wasn't added to the plan).
Fixes https://apollographql.atlassian.net/browse/FED-251
---
**Checklist**
**Exceptions**
**Notes** …
> FED-251: fixed `inputs_for_require` to use the entity_type/schema

- apollo-router/src/query_planner/dual_query_planner.rs
When using `experimental_query_planner_mode:both`, emit mismatch metrics as `debug` rather than `warn` as there are still a fair few mismatches.
> fix(bridge_query_planner): change log level for mismatches

- apollo-federation/src/sources/connect/expand/mod.rs
- apollo-federation/src/sources/connect/expand/tests/mod.rs
- apollo-federation/src/sources/connect/expand/tests/schemas/simple.graphql
- apollo-federation/src/sources/connect/expand/tests/schemas/simple.yaml
- apollo-federation/src/sources/connect/mod.rs
- apollo-federation/src/sources/connect/models/mod.rs
- apollo-federation/src/sources/connect/spec/directives.rs
- apollo-federation/src/sources/connect/spec/mod.rs
- apollo-federation/src/sources/connect/url_path_template.rs
- apollo-federation/src/subgraph/mod.rs
This PR adds the ability to expand connect-aware subgraphs into their own atomic subgraphs each containing a single connector. Each subgraph only contains the needed types and fields as described by the connector's selection set, inputs, and body.
This PR is only the initial implementation. More PRs are needed to have it fully working.
---
**Checklist**
**Exceptions**
**Notes** …
> connector: initial expand subgraphs

- apollo-router/src/error.rs
- apollo-router/src/plugins/connectors/supergraph.rs
- apollo-router/src/spec/schema.rs
---
**Checklist**
**Exceptions**
**Notes**
> use expand_connectors to get new supergraph and connectors map

- .changesets/fix_geal_update_router_bridge4-2.md
- .changesets/fix_geal_update_router_bridge4.md
- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/tests/integration/redis.rs
- docs/source/federation-version-support.mdx
- fuzz/Cargo.toml
This update covers:
- federation update to 2.8.1 to fix a performance issue when looking up contexts: https://github.com/apollographql/federation/pull/3031
- remove deno_crypto due to the vulnerability reported in curve25519-dalek (router-bridge was only using it to expose crypto.getRandomValues for UUID generation): https://rustsec.org/advisories/RUSTSEC-2024-0344
Fixes https://github.com/apollographql/router/issues/5484
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. …
> chore(deps,security): Update `router-bridge` to 0.5.27+v2.8.1

- apollo-federation/src/query_graph/graph_path.rs
- apollo-federation/src/query_graph/mod.rs
- apollo-federation/src/query_graph/path_tree.rs
Fixes
* `SimultaneousPaths` should not wrap single element in redundant brackets `{ }`
* `OpGraphPath` added missing conditions to the edges
* `OpGraphPath` added missing root nodes
Before
```
{ --[key()]--> I(S1) --[__typename]--> String(S1) }
```
After
```
I(S2) --[{ id } ⊢ key()]--> I(S1) --[__typename]--> String(S1)
```
---
**Checklist**
**Exceptions**
**Notes**
[^2]: …
> fix: misc graph_path display fixes

- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/shareable_root_fields.rs
Fix state update logic for handling processed nodes. We were incorrectly retaining already processed nodes.
JS code `mergeRemaingsAndRemoveIfFound`
```javascript
return inEdges.filter(e => otherEdges.includes(e))
```
RS code `merge_remains_and_remove_if_found`
```rust
- in_edges.retain(|e| !other_node.unhandled_parents.contains(e));
+ in_edges.retain(|e| other_node.unhandled_parents.contains(e));
```
JS code `updateForProcessedGroups`
```javascript
const newEdges = edges.filter((edge) => !processed.includes(edge.group));
```
RS code `update_for_processed_nodes`
```rust
- edges.retain(|edge| processed.contains(&edge.parent_node_id));
+ edges.retain(|edge| !processed.contains(&edge.parent_node_id));
```
Also fixed incorrect parent<->child relationship in handle requires -> when creating new …
> fix(federation): handle shareable root operations

- apollo-federation/tests/query_plan/build_query_plan_tests/requires.rs
Updates the parallel fetch order for the `handles_multiple_requires_involving_different_nestedness` and `it_handes_diamond_shape_depedencies` tests.
---
**Checklist**
**Exceptions**
**Notes** …
> fix(federation): update the parallel fetch order for requires test

- docs/shared/batch-processor-ref.mdx
Default for max_queue_size is 2048, not 5.
---
**Checklist**
**Exceptions**
**Notes**
> Fix typo in batch processor default config docs

- apollo-federation/src/sources/connect/models/snapshots/validation_tests@invalid_entity_arg_on_field.graphql.snap
- apollo-federation/src/sources/connect/models/snapshots/validation_tests@invalid_entity_arg_on_list_type.graphql.snap
- apollo-federation/src/sources/connect/models/snapshots/validation_tests@invalid_entity_arg_on_non_entity_field.graphql.snap
- apollo-federation/src/sources/connect/models/test_data/validation/invalid_entity_arg_on_list_type.graphql
- apollo-federation/src/sources/connect/models/test_data/validation/invalid_entity_arg_on_non_entity_field.graphql
- apollo-federation/src/sources/connect/models/validation.rs
Adding validation check to ensure `entity: true` is only set on fields that return valid entity types (non list & non scalar)
---
**Checklist**
**Exceptions**
**Notes** …
> adding validation for entity types with entity:true

- apollo-router/src/plugins/connectors/handle_responses.rs
- apollo-router/src/plugins/connectors/make_requests.rs
we'll need the relevant selection set for the specific HTTP response to map the response with aliases, type names, and field selection
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, …
> track selection set for requests

- apollo-router/tests/snapshots/apollo_reports__batch_send_header-2.snap
- apollo-router/tests/snapshots/apollo_reports__batch_send_header.snap
- apollo-router/tests/snapshots/apollo_reports__batch_trace_id-2.snap
- apollo-router/tests/snapshots/apollo_reports__batch_trace_id.snap
- apollo-router/tests/snapshots/apollo_reports__client_name-2.snap
- apollo-router/tests/snapshots/apollo_reports__client_name.snap
- apollo-router/tests/snapshots/apollo_reports__client_version-2.snap
- apollo-router/tests/snapshots/apollo_reports__client_version.snap
- apollo-router/tests/snapshots/apollo_reports__condition_else-2.snap
- apollo-router/tests/snapshots/apollo_reports__condition_else.snap
- apollo-router/tests/snapshots/apollo_reports__condition_if-2.snap
- apollo-router/tests/snapshots/apollo_reports__condition_if.snap
- apollo-router/tests/snapshots/apollo_reports__non_defer-2.snap
- apollo-router/tests/snapshots/apollo_reports__non_defer.snap
- apollo-router/tests/snapshots/apollo_reports__send_header-2.snap
- apollo-router/tests/snapshots/apollo_reports__send_header.snap
- apollo-router/tests/snapshots/apollo_reports__send_variable_value-2.snap
- apollo-router/tests/snapshots/apollo_reports__send_variable_value.snap
- apollo-router/tests/snapshots/apollo_reports__stats.snap
- apollo-router/tests/snapshots/apollo_reports__trace_id-2.snap
- apollo-router/tests/snapshots/apollo_reports__trace_id.snap
- docs/source/enterprise-features.mdx
Clarify that the `--license <license_path>` option is only available when running the router binary, not for use with `rover dev`
> docs: clarify offline license options

- docs/source/containerization/kubernetes.mdx
Fixes a doc reference to an archived Build a Supergraph (BAS) repository in favor of the replacement reference architecture.
> remove BAS reference

- docs/source/configuration/overview.mdx
Clarify enhanced signature generation _may_ cause different operation ids
> docs: clarify enhanced signature generation might cause different operation ids

- apollo-federation/tests/query_plan/build_query_plan_tests/provides.rs
For the `it_works_on_unions()` test in `provides.rs`, it turns out that the [Rust query plan snapshots](https://github.com/apollographql/router/blob/544f8f619f5541d37ed79176d463c8e0fc713b3b/apollo-federation/tests/query_plan/build_query_plan_tests/provides.rs#L251) have diverged from the [JS code's snapshots](https://github.com/apollographql/federation/blob/b2e5ab66f84688ec304cfcf2c6f749c86aded549/query-planner-js/src/__tests__/buildPlan.test.ts#L646). I'm not sure how it happened, but I copy/pasted the query plan snapshots from the JS tests back into the Rust tests, and they pass now.
> Fix test snapshot misalignment between Rust and JS code

- .changesets/feat_bnjjj_implement_drop_aggregation_view.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/telemetry/config.rs
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/src/plugins/telemetry/testdata/prometheus_custom_view_drop.router.yaml
- docs/source/configuration/telemetry/exporters/metrics/overview.mdx
You can drop specific metrics if you don't want these metrics to be sent to your APM using [otel views](https://opentelemetry.io/docs/specs/otel/metrics/sdk/#view).
```yaml title="router.yaml"
telemetry:
exporters:
metrics:
common:
service_name: apollo-router
views:
- name: apollo_router_http_request_duration_seconds # Instrument name you want to edit. You can use wildcard in names. If you want to target all instruments just use '*'
aggregation: drop
```
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking …
> feat(telemetry): add the ability to drop metrics using otel views

- apollo-federation/src/operation/mod.rs
When normalizing the selection sets they might contain references to named fragments. We need to pass valid named fragments in order to normalize.
Note that in the JS codebase, fragments kept reference to named fragments hence when rebasing it would work without explicitly passing the fragments. In RS we don't store those references so when we rebase/normalize we have to explicitly pass them in.
---
**Checklist**
**Exceptions**
**Notes** …
> fix(federation): pass fragments when normalizing selections

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/query_graph/graph_path.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/introspection_typename_handling.rs
In JS version, Field's `siblingTypename` field can be either undefined, empty string or an alias name.
In Rust, the `Name` type can't hold empty string and the empty string case wasn't implemented before. This PR fixed that by adding a new enum type to distinguish the unaliased/aliased cases.
One previously failing snapshot test is now fixed.
Many mismatches from corpus data are fixed.
---
**Checklist**
> fix(federation): fixed unnecessary sibling typename aliasing

- apollo-router/src/lib.rs
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/query_planner/dual_query_planner.rs
- apollo-router/src/query_planner/mod.rs
Summary
* Expose `plan_matches` function via `_private` module, so performance-harness can use it without duplicating comparison code.
* `operation_matches` compares operations via their ASTs.
* Some parts of AST are ordering-tolerant like query variable declaration, parallel fetches.
Known issues:
* There are still false positive patterns that are not handled, yet. (Need more investigation)
* Comparison of parallel fetches could be more optimized.
---
**Checklist**
[FED-318]: https://apollographql.atlassian.net/browse/FED-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FED-318: Semantic comparison of query plans

- .changesets/fix_bnjjj_fix_coprocessor_with_subs.md
- apollo-router/src/plugins/coprocessor/execution.rs
- apollo-router/src/plugins/coprocessor/mod.rs
- apollo-router/src/plugins/coprocessor/supergraph.rs
- apollo-router/src/plugins/coprocessor/test.rs
- apollo-router/src/protocols/multipart.rs
Do not override skipped data from serde when you returns a body from a coprocessor response stage.
---
**Checklist**
**Exceptions**
**Notes** …
> fix(subscription): make coprocessors work better with subscriptions

- docs/source/executing-operations/demand-control.mdx
There was a typo in the docs around events, and one of the configuration examples had an error when using the operation name attribute.
For now rename to titles to router.yaml, we will revert when we change the logic for detection of router yamls.
---
**Checklist**
**Exceptions**
**Notes** …
> Fix some typos in the demand control docs

- docs/source/configuration/traffic-shaping.mdx
Uses shared `<HttpConnection />` component introduced in https://github.com/apollographql/docs/pull/889
See in deploy preview: https://deploy-preview-5536--apollo-router-docs.netlify.app/configuration/traffic-shaping#http2
> docs: use shared `HTTPConnection` component

- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_a_realistic_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_a_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_steelthread_supergraph-2.snap
- apollo-federation/src/sources/connect/mod.rs
- apollo-federation/src/sources/connect/models/mod.rs
- apollo-router/src/plugins/connectors/configuration.rs
- apollo-router/src/plugins/connectors/handle_responses.rs
- apollo-router/src/plugins/connectors/make_requests.rs
- apollo-router/src/plugins/connectors/tests.rs
- apollo-router/src/spec/schema.rs
Add the ability override the base URL of a `@source` directive in the supergraph configuration YAML. Any connector referencing that source will use the overridden base URL.
This required adding the source name to the `ConnectId` of the connector, to allow looking up the associated source configuration. This field is optional, since a connector can directly specify the full URL of the REST API, rather than referring to a source directive. In that case, the base URL cannot be overridden.
---
**Checklist**
**Exceptions**
**Notes** …
> Add ability to override base URL on a connector source

- docs/source/configuration/overview.mdx
Adds docs for extended reference reporting configuration
> docs: add extended reference reporting

- apollo-router/src/plugins/connectors/handle_responses.rs
- apollo-router/src/plugins/connectors/tests.rs
- apollo-router/src/query_planner/fetch.rs
- apollo-router/src/services/connect.rs
- apollo-router/src/services/fetch_service.rs
* Change return type of the connector service to `graphql::Response` to match subgraph service. This allows the fetch service to treat responses the same as subgraph service responses
* Add `response_at_path` call after connector service responses
* Add deferred fetch handling after connector service responses
* The unit test is updated to include an entity, which now passes
The goal here is to achieve parity between connector service and subgraph service response processing, while minimizing changes from the `dev` branch.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. …
> Fetch parity between connector service and subgraph service

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/query_plan/query_planner.rs
Summary
- ported `withoutIntrospection` JS function
---
**Checklist**
**Exceptions**
**Notes**
[FED-332]: …
> FED-332: added the `remove_introspection` step in `normalize_operation`

- .changesets/fix_bnjjj_fix_event_instr_response_context_sel.md
- apollo-router/src/plugins/telemetry/config_new/fixtures/supergraph/event.attributes.on_graphql_error/metrics.snap
- apollo-router/src/plugins/telemetry/config_new/fixtures/supergraph/event.attributes.on_graphql_error/router.yaml
- apollo-router/src/plugins/telemetry/config_new/fixtures/supergraph/event.attributes.on_graphql_error/test.yaml
- apollo-router/src/plugins/telemetry/config_new/selectors.rs
This will fix cases when you want to create a custom instruments having a value set to `event_*` with a condition executed on event and using the `response_context` selector in attributes.
Example:
```yaml
telemetry:
instruments:
supergraph:
sf.graphql_router.errors:
value: event_unit
type: counter
unit: count
description: "graphql errors handled by the apollo router"
condition:
eq:
- true
- on_graphql_error: true
attributes:
"operation":
response_context: "operation_name" # This was not working before
```
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention …
> fix(telemetry): add response_context handling in event selector when using an event_* instrument

- apollo-federation/src/error/mod.rs
- apollo-federation/src/schema/field_set.rs
- apollo-federation/tests/api_schema.rs
- apollo-router/src/spec/schema.rs
The double newline is kind of awkward in CLI output IMO.
For example, I had a query that caused these errors:
```
The following errors occurred:
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- variable `$a` is not defined
- …
```
> chore(federation): reduce whitespace in `MultipleFederationErrors`

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/schema/mod.rs
This is an alternative to #5534 that does not add a new cache. I think this approach is preferable
as it has the same effect (optimizing the one very hot path) but with a much more limited "blast radius"
(less code affected overall).
It does the intersection check with just the information that's readily available on the schema.
`possible_runtime_types` is still slow, but it's no longer called in this very hot path. If it turns up in profiling later we can still consider optimizing `possible_runtime_types` with a cache or with wrapper types.
Closes #5534.
> fix(federation): optimize `runtime_types_intersect`

- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_a_realistic_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_a_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_steelthread_supergraph-2.snap
- apollo-federation/src/sources/connect/mod.rs
- apollo-federation/src/sources/connect/models/mod.rs
- apollo-router/src/plugins/connectors/http_json_transport.rs
- apollo-router/src/plugins/connectors/make_requests.rs
- apollo-router/src/plugins/connectors/testdata/steelthread.graphql
- apollo-router/src/plugins/connectors/testdata/steelthread.yaml
- apollo-router/src/plugins/connectors/tests.rs
- apollo-router/src/services/connect.rs
Propagate headers from the supergraph GraphQL query to Connectors REST HTTP requests, as specified by the `headers` attributes on the `@connect` and `@source` directives.
---
**Checklist**
**Exceptions**
**Notes** …
> Propagate HTTP headers to connectors requests

- apollo-federation/src/sources/connect/json_selection/pretty.rs
- apollo-router/src/configuration/expansion.rs
- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__expansion__test__dev_mode.snap
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/connectors/configuration.rs
- apollo-router/src/plugins/connectors/handle_responses.rs
- apollo-router/src/plugins/connectors/http_json_transport.rs
- apollo-router/src/plugins/connectors/make_requests.rs
- apollo-router/src/plugins/connectors/mod.rs
- apollo-router/src/plugins/connectors/plugin.rs
- apollo-router/src/router_factory.rs
- apollo-router/src/services/connector_service.rs
in `--dev` mode or with preview_connectors.debug_extensions set to true, and the client includes a `Apollo-Connectors-Debugging: true` request header, responses will include connector request/response data like this:
```json
{
"apolloConnectorsDebugging": {
"version": "1",
"data": [
{
"request": {
"url": "https://jsonplaceholder.typicode.com/users",
"method": "GET",
"headers": [["content-type","application/json"]],
"body": "TODO"
},
"response": {
"status": 200,
"headers": [["content-type","application/json"]],
"body": {"kind":"json","content":{...}}
},
"selection": {
"source":".results { id name }",
"result": {...},
"errors":[{"message":"...","path":"...","count":10}]
}
}
]
}
}
}
```
---
**Checklist**
Complete the checklist (and note appropriate exceptions) before the PR …
> connector debugging on response extensions

- apollo-federation/src/sources/connect/expand/mod.rs
- apollo-federation/src/sources/connect/expand/tests/schemas/realistic.graphql
- apollo-federation/src/sources/connect/expand/tests/schemas/realistic.yaml
- apollo-federation/src/sources/connect/expand/tests/schemas/simple.graphql
- apollo-federation/src/sources/connect/expand/tests/schemas/simple.yaml
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_a_realistic_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_a_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_a_supergraph-3.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_steelthread_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_steelthread_supergraph-3.snap
- apollo-federation/src/sources/connect/expand/visitor.rs
- apollo-federation/src/sources/connect/mod.rs
- apollo-federation/src/sources/connect/models/mod.rs
- apollo-federation/src/sources/connect/url_path_template.rs
- apollo-router/src/plugins/connectors/handle_responses.rs
- apollo-router/src/plugins/connectors/make_requests.rs
- apollo-router/src/plugins/connectors/testdata/steelthread.graphql
- apollo-router/src/plugins/connectors/testdata/steelthread.yaml
- apollo-router/src/plugins/connectors/tests.rs
This PR adds support for synthesizing keys for expanded subgraphs from the inputs to the transport for a connector. More work will need to be done to support input types and expanding inputs from an HTTP transport's JSON body.
---
**Checklist**
**Exceptions**
**Notes** …
> connectors: derive key from inputs

- apollo-federation/src/sources/connect/expand/mod.rs
- apollo-federation/src/sources/connect/expand/tests/schemas/realistic.graphql
- apollo-federation/src/sources/connect/expand/tests/schemas/realistic.yaml
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_a_realistic_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_a_realistic_supergraph-3.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_a_realistic_supergraph.snap
This commit separates out processing of input types and output directives into two separate stages. This addresses issues when populating output fields since input types need to exist before creating the field with arguments and output keys need to reference the output field before appending key directives.
---
**Checklist**
**Exceptions**
**Notes** …
> connectors: separate input type and output key processing

- Cargo.lock
- Cargo.toml
- apollo-federation/Cargo.toml
- apollo-router/Cargo.toml
This bumps the versions of some minor and patch versions of packages which
are currently queued up in the (now) monolithic https://github.com/apollographql/router/pull/4786.
Chipping away at these is still important week to week.
This PR contains the following updates (largely copied from the other PR):
| Package | Change | Age | Adoption | Passing | Confidence | Type | Update |
|---|---|---|---|---|---|---|---|
| [anyhow](https://togithub.com/dtolnay/anyhow) | `1.0.80` -> `1.0.86` | [![age](https://developer.mend.io/api/mc/badges/age/crate/anyhow/1.0.81?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/crate/anyhow/1.0.86?slim=true)](https://docs.renovatebot.com/merge-confidence/) | …
> chore(deps): anyhow, clap, tempfile, thiserror, rust-embed, jsonwebtoken

- Cargo.lock
- apollo-router/Cargo.toml
Changelogs are accessible within, but interdispersed between:
- https://github.com/apollographql/router/pull/3628
- https://github.com/apollographql/router/pull/4786
basic-toml = "0.1.9"
brotli = "3.5.0"
flate2 = "1.0.30"
libc = "0.2.155"
libtest-mimic = "0.7.3"
linkme = "0.3.27"
lru = "0.12.3"
memchr = "2.7.4"
num-traits = "0.2.19"
parking_lot = "0.12.3"
paste = "1.0.15"
pin-project-lite = "0.2.14"
prost = "0.12.6"
prost-types = "0.12.6"
regex = "1.10.5"
reqwest = "0.11.27"
rustls = "0.21.12"
semver = "1.0.23"
serial_test = "3.1.1"
similar = "2.5.0"
test-log = "0.2.16"
test-span = "0.7.0"
tikv-jemallocator = "0.5.4"
time = "0.3.36"
tokio-stream = "0.1.15"
tokio-util = "0.7.11"
tracing = "0.1.40"
tracing-core = "0.1.32"
tracing-subscriber = "0.3.18"
url = "2.5.2"
uuid = "1.9.1"
walkdir = …
> chore(deps): collection of minor and patch version bumps

- apollo-federation/src/sources/connect/models/mod.rs
- apollo-router/src/plugins/connectors/handle_responses.rs
- apollo-router/src/plugins/connectors/http_json_transport.rs
- apollo-router/src/plugins/connectors/make_requests.rs
- apollo-router/src/plugins/connectors/plugin.rs
- apollo-router/src/plugins/connectors/testdata/mutation.graphql
- apollo-router/src/plugins/connectors/testdata/mutation.yaml
- apollo-router/src/plugins/connectors/tests.rs
* Add request bodies to Connectors HTTP requests
* Add request body to debug extension data
* Refactor Connectors debug extension data so selection is part of associated request or response data
* Add test for mutation using a Connector
* Fix a bug in boolean logic to determine if a Connector is on a root type, which caused it to fail for mutation operations
---
**Checklist**
**Exceptions**
**Notes**
With these changes, it's now possible to execute mutations against REST APIs using Connectors, and to see the request body and selection in the debug output:
```json
"body": {
"kind": "json",
"content": {
"title": "test issue 12"
},
"selection": {
"source": "{\n …
```
> Add request bodies to Connectors HTTP requests

- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/plugins/connectors/mod.rs
- apollo-router/src/plugins/connectors/tests.rs
- apollo-router/src/plugins/connectors/tracing.rs
- apollo-router/src/query_planner/execution.rs
- apollo-router/src/services/connector_service.rs
- apollo-router/src/services/fetch_service.rs
* Add a `connect` tracing span
* Refactor the `fetch` tracing span into the `FetchService`
* Set the name of the fetch span to the original subgraph name for a connectors subgraph
---
**Checklist**
**Exceptions**
**Notes**
In Jaeger, you can now see a fetch span on the original subgraph name, a connect span for the connector, and a request span for the REST HTTP request:
There is remaining work to add additional field attributes.
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to …
> Add connect tracing span

- .changesets/fix_bnjjj_fix_rhai_traceid.md
- apollo-router/src/plugins/rhai/engine.rs
Before, when calling `traceid()` in a rhai script, if the trace wasn't sampled you won't get the traceid. It's now fixed and you'll get trace id even if the trace is not sampled.
---
**Checklist**
**Exceptions**
**Notes** …
> fix(rhai): provide a valid trace id even if the trace isn't sampled

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/operation/rebase.rs
- apollo-federation/src/query_graph/mod.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/schema/position.rs
Much like `try_get()` in #5605, we regularly use `try_from()` on positions just to check if we *can* convert, or to conditionally do something with a converted type. In some hot paths like rebasing or optimize(), we do not actually use the error. So creating a full error with an allocated string is excessive in those cases.
This adds a cheap internal error type for `Position::try_from()` conversion failures. I also added macros to declare the conversions because they're all the same.
> fix(federation): remove temporary string allocations from position `try_from()` errors

- .changesets/feat_bnjjj_feat_284.md
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/telemetry/config_new/selectors.rs
- docs/source/configuration/telemetry/instrumentation/selectors.mdx
`on_graphql_error` exists for router and supergraph, but not for subgraph. This adds support for `subgraph_on_graphql_error` selector for symmetry and to also allow easy detection of which subgraphs requests contain graphql errors in response body. 
```yaml
telemetry:
instruments:
subgraph:
http.client.request.duration:
attributes:
subgraph.graphql.errors: # attribute containing a boolean set to true if response.errors is not empty
subgraph_on_graphql_error: true
```
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please …
> Add 'subgraph_on_graphql_error' selector for subgraph

- apollo-router/src/plugins/record_replay/record.rs
Currently the `Schema` struct created in Record/Replay plugin is missing api_schema (it's `None`!) information that's necessary when parsing an executable document. This means that any incoming operation with Record/Replay plugin enabled, will panic with `missing API schema`.
This change adds an additional `schema.with_api_schema()` call before instantiating this plugin. The fix does reparse the schema, but this is also a debugging plugin. The expectation is that this change will be superseded by #5623 in the 1.52.0 release.
> fix(record plugin): record plugin should use a Schema with api_schema

- apollo-federation/src/link/mod.rs
- apollo-federation/src/sources/connect/expand/mod.rs
- apollo-federation/src/sources/connect/models/snapshots/validation_tests@disallowed_federation_imports.graphql.snap
- apollo-federation/src/sources/connect/models/test_data/validation/disallowed_federation_imports.graphql
- apollo-federation/src/sources/connect/models/validation.rs
- apollo-federation/src/sources/connect/spec/mod.rs
- apollo-federation/src/subgraph/database.rs
- apollo-federation/src/subgraph/mod.rs
- apollo-federation/src/subgraph/spec.rs
Prevents `@context`, `@fromContext`, and `@interfaceObject` from being used with connectors.
We _might_ want `Link` and `Import` to retain location info (`Node`s) directly, but doing so will require carrying around lifetimes, so I didn't go mess with that yet.
[CNN-168]: https://apollographql.atlassian.net/browse/CNN-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Validation error when importing conflicting directives

- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_a_realistic_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_a_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__it_expands_steelthread_supergraph-2.snap
- apollo-federation/src/sources/connect/models/mod.rs
- apollo-router/src/plugins/connectors/tests.rs
Quick fix for HTTP method case on connectors label. This label shows up in the query plan, for example.
---
**Checklist**
**Exceptions**
**Notes** …
> Fix casing on HTTP method in connectors label

- .changesets/fix_error_locations.md
- apollo-router/src/graphql/mod.rs
- apollo-router/tests/integration/mod.rs
- apollo-router/tests/integration/subgraph_response.rs
GraphQL spec require that both "line" and "column" are positive numbers. 
However GraphQL Java and GraphQL Kotlin return `{ "line": -1, "column": -1 }` if they can't determine error location inside query. 
So instead of failing we now just remove such locations.
---
**Checklist**
**Exceptions**
**Notes** …
> Handle subgraph response with -1 values inside error locations

- .changesets/fix_spawn_blocking_parser.md
- apollo-router/src/query_planner/caching_query_planner.rs
- apollo-router/src/services/layers/query_analysis.rs
- apollo-router/tests/snapshots/apollo_otel_traces__batch_send_header-2.snap
- apollo-router/tests/snapshots/apollo_otel_traces__batch_send_header.snap
- apollo-router/tests/snapshots/apollo_otel_traces__batch_trace_id-2.snap
- apollo-router/tests/snapshots/apollo_otel_traces__batch_trace_id.snap
Reverts apollographql/router#5582 which was originally @xuorig's in https://github.com/apollographql/router/pull/5235 which @Geal  took over and @garypen ultimately landed. 
Unfortunately, it seems this is causing tests to flake at a somewhat pronounced rate — always on Linux. We believe it's just actually the tests, or the way we tested, but we'll revert this for now so `dev` isn't flaking for everyone trying to develop against it.
I'll open a revert for this revert as a draft after this lands. 😄
> Revert "use spawn_blocking for parsing"

- apollo-federation/src/query_graph/path_tree.rs
- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/tests/query_plan/build_query_plan_tests.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/mutations.rs
- apollo-federation/tests/query_plan/supergraphs/adjacent_mutations_get_merged.graphql
- apollo-federation/tests/query_plan/supergraphs/non_adjacent_mutations_do_not_get_merged.graphql
This PR addresses an issue in the `compute_root_serial_dependency_graph` function. While iterating through the top-level fields, sucessive `OpTree`s from the same subgraph were being merged instead of concatenated. This can cause mutations to be merged together and effective forgotten.
Fixes FED-336.
---
**Checklist**
**Exceptions**
**Notes** …
> Use OpTree concatenation in serial query planning 

- apollo-router/src/plugins/connectors/testdata/nullability.graphql
- apollo-router/src/plugins/connectors/testdata/nullability.yaml
- apollo-router/src/plugins/connectors/tests.rs
Add a test that nullable fields are correctly set to `null` when not included in the REST response.
---
**Checklist**
**Exceptions**
**Notes** …
> Add test for nullability with connectors

- Cargo.lock
- apollo-federation/Cargo.toml
- apollo-federation/src/sources/connect/json_selection/mod.rs
- apollo-federation/src/sources/connect/json_selection/selection_set.rs
- apollo-federation/src/sources/connect/mod.rs
- apollo-router/src/plugins/connectors/handle_responses.rs
- apollo-router/src/plugins/connectors/http_json_transport.rs
- apollo-router/src/plugins/connectors/make_requests.rs
- apollo-router/src/plugins/connectors/plugin.rs
- apollo-router/src/plugins/connectors/testdata/mutation.yaml
- apollo-router/src/plugins/connectors/testdata/selection.graphql
- apollo-router/src/plugins/connectors/testdata/selection.yaml
- apollo-router/src/plugins/connectors/testdata/steelthread.graphql
- apollo-router/src/plugins/connectors/testdata/steelthread.yaml
- apollo-router/src/plugins/connectors/tests.rs
Implement a mechanism to apply a selection set to a `JSONSelection` to create a new `JSONSelection`. This selects only things that are in the selection set, and maps fields to aliases in the selection set. The transformed `JSONSelection` is then applied to the result of the connectors REST API call to create the response. The transformed `JSONSelection` is also included in the debug extension data.
This also adds support for variables when applying the `JSONSelection`.
---
**Checklist**
**Exceptions**
**Notes** …
> Apply selection set to JSONSelection

- xtask/Cargo.lock
- xtask/Cargo.toml
Since 0d2e347ffdb28cb7b4a7664e911a538d7616a61e I get a compile error when running anything `xtask`. I think maybe the `reqwest` update changed the set of tokio features that's enabled by `reqwest`?
```
error[E0599]: no function or associated item named `new_multi_thread` found for struct `tokio::runtime::Builder` in the current scope
--> src/commands/changeset/mod.rs:240:34
|
240 |         tokio::runtime::Builder::new_multi_thread()
|                                  ^^^^^^^^^^^^^^^^
|                                  |
|                                  function or associated item not found in `Builder`
|                                  help: there is an associated function with a similar name: `new_current_thread`
```
This patch enables "full" tokio features. That's excessive for what …
> fix(xtask): fix compilation

- docs/source/enterprise-features.mdx
Just a clarification to existing documentation behavior on our Offline License feature page that builds on the functionality introduced by @lleadbet in https://github.com/apollographql/router/pull/5310 as an implementation of https://github.com/apollographql/router/issues/4587.
> chore(docs): Point to local PQ manifests when using Offline Licenses

- apollo-federation/src/sources/connect/mod.rs
- apollo-federation/src/sources/connect/models.rs
This was vestigial from before the reorganization. Now exposing the module instead of items from within it to make changes easier in the future.
> Move validation imports out of models

- docs/source/containerization/docker.mdx
- docs/source/containerization/kubernetes.mdx
- docs/source/managed-federation/client-awareness.mdx
Remove unused imported Link component
> docs: remove unused imported component

- apollo-federation/src/link/database.rs
A code comment seems like a useful enough and low-key enough place to write this, but it's not something we are actually planning on doing.
> chore(federation): un-TODO comment transfered from JS

- apollo-router/src/query_planner/dual_query_planner.rs
This PR improves semantic comparison of query plans as following:
- Selection sets are no longer order-sensitive. Selections are sorted by the selection key before comparison.
- Fragment definitions are no longer order-sensitive. Fragment definitions are sorted by the name before comparison.
---
**Checklist**
[FED-318]: https://apollographql.atlassian.net/browse/FED-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Improves semantic comparison of query plans

- apollo-federation/cli/src/main.rs
- apollo-federation/src/error/mod.rs
- apollo-federation/src/operation/mod.rs
- apollo-federation/src/operation/optimize.rs
- apollo-federation/src/query_graph/extract_subgraphs_from_supergraph.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/src/subgraph/spec.rs
- apollo-federation/tests/api_schema.rs
We had a bug where an input like this:
```graphql
fragment x on T {
__typename @include(if: $var)
field
}
query ($var: Boolean!) {
returnsT {
...x
}
someEntity {
.. on T { field }
}
}
```
Could produce a subgraph entity query like this. Note this isn't a precise reproduction, since the exact reproduction involving entities is more difficult, but it is an accurate presentation of the problem:
```graphql
query Example($representations: [_Any!]!) {
_entities(representations: $representations) {
... on T {
__typename @include(if: $var)
field
}
}
}
```
The entity query references a `$var` that does not exist.
This is because when the final subgraph operation is produced, we first determine what variables the operation needs, and *then* try to reuse fragments from the input. Inline fragments …
> fix(federation): fix "$var is not defined" in subgraph entity query

- apollo-federation/src/query_plan/fetch_dependency_graph_processor.rs
- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/src/query_plan/query_planning_traversal.rs
Remove the `Clone` impl and pass a `&mut` reference around instead.
Fixes FED-282, together with https://github.com/apollographql/router/pull/5391 which removed the `Clone` impl of `QueryPlanningParameters`
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick …
> Avoid cloning FetchDependencyGraphToQueryPlanProcessor

- .changesets/fix_bryn_service_version.md
- apollo-router/src/plugins/telemetry/resource.rs
- apollo-router/tests/integration/telemetry/datadog.rs
- apollo-router/tests/integration/telemetry/fixtures/datadog.router.yaml
This PR allows yaml configured service.version to override the built in version that is baked into the router.
For example:
```yaml
telemetry:
exporters:
tracing:
common:
resource:
service.version: 1.0
```
Overrides the version to `1.0`.
Here is an example where I have overridden the version in datadog:
Existing docs are OK, this is a bugfix.
---
**Checklist**
**Exceptions**
**Notes** …
> (Fix) telemetry: allow overriding of service.version

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/operation/optimize.rs
- apollo-federation/src/operation/tests/mod.rs
- apollo-federation/src/query_graph/build_query_graph.rs
- apollo-federation/src/query_graph/mod.rs
- apollo-federation/src/query_plan/conditions.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/query_plan/query_planning_traversal.rs
- apollo-federation/src/schema/subgraph_metadata.rs
A small cleanup. This function is infallible, so we should not return a `Result`.
Also allows removing Result wrapping from a few other functions, notably everything in `ExternalMetadata`.
> chore(federation): remove unnecessary Result from Selection::selection_set()

- .changesets/fix_bryn_datadog_timeout.md
- apollo-router/src/plugins/telemetry/tracing/datadog.rs
This is caused by connection pooling.
Setting the pool value to something very low causes the errors to disappear.
Improves #2058
This is impossible to automatically test as the Datadog agent test image does not behave in the same way as the real agent.
Related issue:
https://github.com/open-telemetry/opentelemetry-rust-contrib/issues/7
I did some manual testing.
---
#ROUTER-456
**Checklist**
**Exceptions**
**Notes** …
> (fix) Prevent Datadog timeout errors in logs

- helm/chart/router/templates/service.yaml
A first stab at trying to expose EC invalidation port.
Some questions:
- Do we want to expose more than one port?
- We don't.
- Do we want a default port or do we want to just expose the chosen port as the service port?
- We don't, you must specify a port number in your `listen` configuration.
- Do we want to call the port "invalidation". I just chose that arbitrarily.
- Good enough choice for now, to be finalised at some point. 
Some thoughts. The check to see if `invalidation` is enabled is a relatively complex `and` of various configuration properties. Could this be simplified?
Anyway, it's basically working within the constraints established by these questions.
Here are some sample configurations that highlight why we need to resolve these question:
1. Defined two listen points, one …
> Add basic helm support for EC invalidation port exposure

- .changesets/fix_bryn_datadog_exporter_span_metrics.md
- apollo-router/src/plugins/telemetry/tracing/datadog_exporter/exporter/model/v05.rs
- apollo-router/src/plugins/telemetry/tracing/datadog_exporter/mod.rs
- apollo-router/tests/integration/telemetry/datadog.rs
In #5609 The backported code from the datadog exporter used code from the feature `agent-sampling`.
This was an incorrect decision as this requires that the sampler is updated to support such functionality. The result is that traces are not being shown in the Datadog UI even though they were exported.
This PR switches the code with `not(agent-samping)` code which will delegate sampling to the sampler in the router yaml config.
Relates to #5609
---
**Checklist**
**Exceptions**
**Notes** …
> Datadog sampling priority not set

- apollo-federation/src/sources/connect/expand/carryover.rs
- apollo-federation/src/sources/connect/expand/mod.rs
- apollo-federation/src/sources/connect/expand/snapshots/apollo_federation__sources__connect__expand__carryover__tests__carryover.snap
- apollo-federation/src/sources/connect/expand/tests/mod.rs
- apollo-federation/src/sources/connect/expand/tests/schemas/carryover.graphql
- apollo-federation/src/sources/connect/expand/tests/schemas/carryover.yaml
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__carryover__it_expands_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__carryover__it_expands_supergraph-3.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__carryover__it_expands_supergraph.snap
merge code now handles inaccessible, but we still need the carryover code because expansion doesn't copy over inaccessibles yet. this change avoids adding the link twice and adds a test to capture this behavior.
the test does not cover other carried-over directives (authenticated, etc) because composition doesn't support them yet
---
**Checklist**
**Exceptions**
**Notes**
[^2]: …
> fix: don't double up inaccessible link

- .changesets/maint_bnjjj_entity_cache_versioning.md
- apollo-router/src/plugins/cache/entity.rs
- apollo-router/tests/integration/redis.rs
---
**Checklist**
**Exceptions**
**Notes**
[ROUTER-424]: …
> add version in the entity cache hash

- apollo-federation/src/sources/connect/expand/mod.rs
- apollo-federation/src/sources/connect/expand/tests/mod.rs
- apollo-federation/src/sources/connect/expand/tests/schemas/nested_inputs.graphql
- apollo-federation/src/sources/connect/expand/tests/schemas/nested_inputs.yaml
- apollo-federation/src/sources/connect/expand/tests/schemas/realistic.graphql
- apollo-federation/src/sources/connect/expand/tests/schemas/realistic.yaml
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__nested_inputs__it_expands_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__nested_inputs__it_expands_supergraph-3.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__nested_inputs__it_expands_supergraph.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__realistic__it_expands_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__realistic__it_expands_supergraph-3.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__realistic__it_expands_supergraph.snap
- apollo-federation/src/sources/connect/expand/visitors/input.rs
- apollo-federation/src/sources/connect/expand/visitors/mod.rs
- apollo-federation/src/sources/connect/expand/visitors/selection.rs
This PR adds input type support to the subgraph expansion code needed for processing connect directives.
---
**Checklist**
**Exceptions**
**Notes** …
> connectors: expand input types

- apollo-federation/src/operation/rebase.rs
The PR ensures that the parent type of a fragment is changed when it is rebased.
Fixes FED-352
---
**Checklist**
**Exceptions**
**Notes** …
> Changed parent type when a fragement is rebased

- Cargo.lock
- apollo-federation/Cargo.toml
- apollo-federation/src/operation/mod.rs
- apollo-federation/src/query_graph/graph_path.rs
- apollo-federation/src/utils/logging.rs
The `snapshot!` macro was serializing values to JSON. This caused issues for graphs and maps with nodes and keys (respectively) that could not be readily serialized into strings. The `derive` impl of `Serialize` was also feature gated for a few types that we do not yet to generally be serializable.
---
**Checklist**
**Exceptions**
**Notes** …
> Fixed serialization panic in snapshot macro

- apollo-router/src/query_planner/dual_query_planner.rs
- apollo-router/src/query_planner/selection.rs
This PR changes dual_query_planner to compare `requires` and `*_rewrites` fields semantically (ignoring their ordering).
---
**Checklist**
> semantic comparison of `requires` and `*_rewrites` fields of `FetchNode`

- apollo-router/src/lib.rs
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/query_planner/dual_query_planner.rs
This specifically compares JS' `QueryPlanResult` and Rust's `QueryPlan` structs, i.e. the ones we use to semantic diff when looking for mismatches. The rendered diff uses `diff::lines` under the hood.
> chore(qp): add a diff_plan function to display differences between js & rust qps

- apollo-router/src/lib.rs
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/query_planner/dual_query_planner.rs
Exporting `render_diff` so it can be used by https://github.com/mdg-private/federation-performance-harness/pull/69.
Also, I corrected a few comments.
---
**Checklist**
> export render_diff via the `_private` module

- .changesets/fix_bnjjj_fix_subgraph_selector_for_event.md
- apollo-router/src/plugins/telemetry/config_new/events.rs
- apollo-router/src/plugins/telemetry/config_new/selectors.rs
- apollo-router/src/plugins/telemetry/testdata/custom_events.router.yaml
As `events` are triggered at a specific stage (`request`|`response`|`error`) we can only have condition for the related stage and so sometimes you can also have selectors that can be applied at several stages (like `subgraph_name` to get the subgraph name). This change adds more possibilities when creating conditions on events.
Example of an event to log the raw subgraph response only on a subgraph named `products`, this was not working before.
```yaml
telemetry:
events:
subgraph:
response:
level: info
condition:
eq:
- subgraph_name: true
- "products"
```
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be …
> Evaluate selectors in response stage when possible

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/operation/optimize.rs
- apollo-federation/src/operation/simplify.rs
- apollo-federation/src/operation/tests/mod.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
There is a special case where `reuse_fragments()` can introduce a new variable reference, that is not part of the operation definition it is called on.
If you have a fragment `B` that is used inside a different fragment `A`, where `B`'s runtime types do not intersect with the parent type where fragment `A` is used, `B` is essentially a dead branch. It will never be executed. Because most of the federation code works on expanded selection sets, the dead branch is not present at all. However, when we try to reuse fragments, the dead branch may be re-added. Fragment reuse checks also work on expanded selection sets, so it's as if the fragment `B`'s selections do not exist while we consider if fragment `A` should be used. That means fragment `A` may be used, introducing the dead branch `B`. …
> fix(federation): prevent reuse_fragments() from introducing new variable references

- apollo-federation/src/operation/merging.rs
- apollo-federation/src/operation/mod.rs
This patch moves the `merge_into` and `add_selection_set` function families into a new `operation::merging` module.
This ensures the privacy of most of the internal `merge_into` methods (except `SelectionSet::merge_selections_into`, which is in use in some selection set constructors).
I documented preconditions and error returns for each function.
The function bodies are unchanged, except they now use `FederationError::internal` instead of creating `SingleFederation::Internal` instances manually.
> chore(federation): move selection merging to a module

- apollo-router/src/axum_factory/tests.rs
- apollo-router/src/orbiter/mod.rs
- apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
- apollo-router/src/plugins/include_subgraph_errors.rs
- apollo-router/src/plugins/record_replay/record.rs
- apollo-router/src/plugins/test.rs
- apollo-router/src/plugins/traffic_shaping/mod.rs
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/query_planner/bridge_query_planner_pool.rs
- apollo-router/src/router_factory.rs
- apollo-router/src/spec/schema.rs
- apollo-router/src/state_machine.rs
- apollo-router/src/test_harness.rs
- apollo-router/src/uplink/license_enforcement.rs
- apollo-router/src/uplink/testdata/schema_enforcement_directive_arg_version_in_range.graphql
- apollo-router/src/uplink/testdata/schema_enforcement_directive_arg_version_out_of_range.graphql
- apollo-router/src/uplink/testdata/schema_enforcement_spec_version_in_range.graphql
- apollo-router/src/uplink/testdata/schema_enforcement_spec_version_out_of_range.graphql
- apollo-router/src/uplink/testdata/unix_socket.graphql
As discussed in https://github.com/apollographql/router/pull/5623#issuecomment-2217896741
This may may startup and reload slightly faster for large schemas, but more importantly it makes `spec::Schema` available in more places which will help upcoming changes for Rust replatforming.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is an important part of many …
> Parse supergraph schema early to avoid re-parsing

- apollo-router/src/plugin/mod.rs
> Simplify `register_plugin!`

- .changesets/breaking_lb_next_apollo_otel_default.md
- apollo-router/src/plugins/telemetry/apollo.rs
BREAKING CHANGE: This change will cause traces in Apollo Studio to appear differently
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document the manual testing (extensively) …
> feat: default to Apollo reporting over OTel

- Cargo.lock
- apollo-router/Cargo.toml
- apollo-router/src/plugins/connectors/snapshots/apollo_router__plugins__connectors__tests__tracing_connect_span.snap
- apollo-router/src/plugins/connectors/tests.rs
There was feedback in #5108 about adding a dependency on [tracing-fluent-assertions](https://crates.io/crates/tracing-fluent-assertions) when there are already other dependencies in use to test tracing. Instead, use the existing `test-snap` dependency to create a snapshot of the connectors span.
---
**Checklist**
**Exceptions**
**Notes** …
> Remove tracing-fluent-assertions dependency

- .github/CODEOWNERS
This will facilitate early notification and edition of changelog entries
> mark the docs team as owner of .changesets

- apollo-router/src/apollo_studio_interop/mod.rs
- apollo-router/src/apollo_studio_interop/tests.rs
- apollo-router/src/plugins/telemetry/mod.rs
- apollo-router/src/services/execution/service.rs
Fixes reporting of the enum values from responses in extended references for deferred requests. Deferred requests include two passes through the format response function, so we need to add to an existing map of enums rather than overwriting it on each pass. We also clear the map when submitting a report so that subscription reports only include the enum values referenced in responses from the particular query in the subscription request/event.
---
**Checklist**
**Exceptions**
**Notes** …
> Fix usage reporting of enum values in deferred requests

- apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
- apollo-router/src/plugins/test.rs
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/query_planner/bridge_query_planner_pool.rs
Config `supergraph.query_planning.experimental_parallelism` defaults to 1, but when set to something else `BridgeQueryPlannerPool` creates that many instances of `BridgeQueryPlanner` which in turn create a JS worker each.
If config `experimental_query_planner_mode` is also set to `new` or `both` (current default is `legacy`), the each `BridgeQueryPlanner` would also unnecessarily create its own instance of the Rust `QueryPlanner` struct.
Instead, a single `QueryPlanner` is now shared with `Arc`. Unlike JS workers, `QueryPlanner` only contains read-only data and can safely be shared between threads. This should reduce memory use when both `supergraph.query_planning.experimental_parallelism` and `experimental_query_planner_mode` are configured to non-default values.
---
**Checklist** …
> Share a single Rust QP instance when using a pool of JS workers

- apollo-federation/src/query_plan/fetch_dependency_graph.rs
This PR is a simple fix of the `is_descendant_of` function. This change reduces panics in many cases.
Additionally, this PR strengthens the cycle detection assertion in the `add_parent` function. That prevents some infinite loop cases. Those cases still panics, which need further investigation.
It was difficult to formulate a test for this. I need help for that.
---
**Checklist**
[ROUTER-546]: https://apollographql.atlassian.net/browse/ROUTER-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(federation): fixed the `is_descendant_of` function

- apollo-router/src/query_planner/fetch.rs
- apollo-router/src/services/fetch_service.rs
Reverts changes to the `FetchNode::response_at_path` function that were made for Connectors. The function is now identical to what it was before - only the visibility has changed so it can be called from `FetchService`. Most notably, this adds back the `&self` parameter. This simplifies the calling code, which already had access to the `FetchNode` and can just pass a reference to it in directly, rather than destructuring out fields to be passed to the function.
This is a minor code refactor - no functional changes were made.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) …
> Remove changes to FetchNode::response_at_path

- apollo-router/src/query_planner/subscription.rs
- apollo-router/src/spec/schema.rs
Fixes a couple of minor issues identified during the connectors code review, #5108:
* `join__graph` should not be case insensitive
* Change `unwrap` back to `expect` in subscription code
---
**Checklist**
**Exceptions**
**Notes** …
> Minor connectors fixes from code review

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/schema/field_set.rs
Today's 15-minute cleanup :)
This set of functions is used in one place, and it has some odd behaviours. In JS, an "element" is free, because its data structures are built on element/selection set pairings. But we don't have the "element" type exactly in our data structures, our closest equivalent is the `Selection` type. Therefore the `for_each_element` function had to convert types including some inexpensive, but non-zero clones.
`for_each_element` also translates named fragment spreads to inline fragments. AFAICT, this is a historical artifact ported from JS, as the only place where `for_each_element` was used does not support named fragment spreads to begin with.
I replaced it, for now, with a manual visitor. I think it might make sense to have something like a `for_each_selection` …
> chore(federation): remove `for_each_element`

- apollo-federation/cli/src/bench.rs
- apollo-federation/cli/src/main.rs
A better way to tinker with options than editing the source.
> feat(federation): add query planner config flags to the CLI

- apollo-federation/src/operation/mod.rs
- apollo-federation/src/operation/optimize.rs
Today's 25 minute cleanup:
- Moves the `collect_used_fragment_names` family of functions to one place in the source file.
- Remove an unnecessary temporary selection set clone (‼️)
- Use `u32` to store the counts as they can never be negative.
- Instead of clearing the internal map with `NamedFragments.retain(false)`, replace the whole structure with an empty one.
> chore(federation): refactor fragment usage counting

- .changesets/fix_bryn_revert_5703.md
- apollo-router/src/plugins/telemetry/tracing/datadog_exporter/exporter/model/v05.rs
- apollo-router/src/plugins/telemetry/tracing/datadog_exporter/mod.rs
- apollo-router/tests/integration/telemetry/datadog.rs
This reverts commit 901eb563a1c669542e99e066a70cbfa6612ee5d2.
Multiple users have reported that the above commit causes the metrics on the APM view in Datadog to disappear.
Efforts to reproduce the issue internally have failed.
I have checked the payload being sent to the datadog agent with and without this change - and they look identical.
That being said, until we can figure out a concrete cause and reproduction we should revert this.
Two commits that follow the revert move the test that was lost over and adds a changelog.
Manual testing:
* Send many requests to the router and verified the number of traces in the APM view matched.
* Verified that traces were visible via trace explorer.
---
**Checklist** …
> Revert "Datadog sampling priority not set (#5703)"

- apollo-router/src/plugins/connectors/handle_responses.rs
- apollo-router/src/plugins/connectors/http_json_transport.rs
- apollo-router/src/plugins/connectors/make_requests.rs
- apollo-router/src/plugins/connectors/plugin.rs
- apollo-router/src/services/connector_service.rs
There was a race condition due to the way debug data was being added to the `ConnectorsContext`. The connectors context was removed from the request context extensions for each query, updated, then put back. If the query planner executed multiple queries in parallel, they would all try to do this at once. Once one of them successfully removed the connectors context, any others running concurrently would get back `None`.
The connectors context is now left in place rather than removed, and is accessed through `Option<Arc<Mutex<ConnectorsContext>>>`. This preserves a single lookup in the `Extensions` for each fetch. If the debug feature is not enabled, the option will be `None`. If it is enabled, the mutex is locked and the context is updated with the debug information.
---
**Checklist** …
> Fix race condition when adding debug data to connector context

- apollo-router/src/configuration/mod.rs
- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/query_planner/bridge_query_planner.rs
- apollo-router/src/query_planner/caching_query_planner.rs
- apollo-router/src/router_factory.rs
- apollo-router/tests/integration/lifecycle.rs
Some supergraph schemas supported by current Router versions (notably those using Apollo Federation 1) are not supported by the new Rust query planner. When a user explicitly configures `experimental_query_planner_mode: new` or `experimental_query_planner_mode: both`, we want unsupported schemas to cause an error at Router startup in order to make the issue very visible.
This adds `experimental_query_planner_mode: both_best_effort` which is like `both` whenever possible, and silently falls back to `legacy` otherwise. This behavior makes it suitable to potentially become the new default config.
Fixes ROUTER-601
---
**Checklist**
**Exceptions**
*Note any …
> Add `experimental_query_planner_mode: both_best_effort` config

- .changesets/fix_bnjjj_improve_gt_lt_conditions.md
- apollo-router/src/plugins/telemetry/config.rs
- apollo-router/src/plugins/telemetry/config_new/conditions.rs
This will enable the ability to have gt/lt conditions on header selectors for example, if you want to put a specific attribute on a span if the `content-length` header is greater than 100:
```yaml
telemetry:
spans:
mode: spec_compliant
router:
attributes:
trace_id: true
payload_is_to_big: # Set this attribute to true if the value of content-length header is > than 100
static: true
condition:
gt:
- request_header: "content-length"
- 100
``` 
---
**Checklist**
**Exceptions**
**Notes** …
> add the ability for gt/lt conditions to parse the string selector to number

- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/tests/query_plan/build_query_plan_tests.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/requires.rs
- apollo-federation/tests/query_plan/supergraphs/test_merging_fetches_do_not_create_cycle_in_fetch_dependency_graph.graphql
The `merge_fetches_to_same_subgraph_and_same_inputs` function must merge decendant nodes into ancestor nodes and not the other way around (to avoid cycles).
This PR fixes it by topologically sorting the fetch dependency graph nodes before collecting nodes to merge. So, their merger is always topologically ordered.
---
**Checklist**
[ROUTER-546]: https://apollographql.atlassian.net/browse/ROUTER-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(federation): fixed a QP panic saying "would create a cycle"

- apollo-federation/tests/query_plan/build_query_plan_tests/merged_abstract_types_handling.rs
Due to the differences between JS and RS graph structures (JS is always topologically sorted) we occassionally end up with different parallel fetch node  order....
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If …
> chore(federation): fix merged abstract types test

- .changesets/feat_geal_return_response_with_errors.md
- apollo-router/src/plugins/cache/entity.rs
- apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__missing_entities-2.snap
- apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__missing_entities.snap
- apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_data-2.snap
- apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_data.snap
- apollo-router/src/plugins/cache/tests.rs
- docs/source/configuration/entity-caching.mdx
If we are requesting entities from a subgraph, where some of them are present in cache, and the subgraph is unavailable (ex: network issue), we want to return a response with the entities we got from the cache, other entities nullified, and an error pointing at the paths of unavailable entities
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is an important part of …
> Entity cache: return cached entities with errors

- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- related to PR #5797
---
**Checklist**
[ROUTER-546]: https://apollographql.atlassian.net/browse/ROUTER-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(federation): added more comments in fetch dependency graph code

- apollo-federation/src/sources/connect/expand/mod.rs
- apollo-federation/src/sources/connect/expand/tests/schemas/realistic.graphql
- apollo-federation/src/sources/connect/expand/tests/schemas/realistic.yaml
- apollo-federation/src/sources/connect/expand/tests/schemas/simple.graphql
- apollo-federation/src/sources/connect/expand/tests/schemas/simple.yaml
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__realistic__it_expands_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__realistic__it_expands_supergraph-3.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__realistic__it_expands_supergraph.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__simple__it_expands_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__simple__it_expands_supergraph-3.snap
- apollo-federation/src/sources/connect/json_selection/mod.rs
- apollo-federation/src/sources/connect/json_selection/parameter_extraction.rs
- apollo-federation/src/sources/connect/json_selection/parser.rs
- apollo-federation/src/sources/connect/mod.rs
This commit adds support for expanding dependent types and key generation for parameters in a JSONSelection included in the transport body.
---
**Checklist**
**Exceptions**
**Notes** …
> connectors: expand JSONSelection in transport body

- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- Generates a string representing the graph in GraphViz dot format.
- Useful for debugging.
It generates diagram like this:
---
**Checklist**
> test(federation): added `FetchDependencyGraph::to_dot` method

- .changesets/fix_bnjjj_fix_supergraph_query_selector.md
- apollo-router/src/plugins/telemetry/config_new/selectors.rs
The `query: root_fields` selector works on `response` stage for events right now but it should also work on `event_response`. This configuration is now working:
```yaml
telemetry:
events:
supergraph:
OPERATION_LIMIT_INFO:
message: operation limit info
on: event_response
level: info
attributes:
graphql.operation.name: true
query.root_fields:
query: root_fields
``` 
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use …
> execute supergraph query selector also on events

- apollo-federation/src/link/cost_spec_definition.rs
- apollo-federation/src/query_graph/extract_subgraphs_from_supergraph.rs
- apollo-federation/tests/extract_subgraphs.rs
- apollo-federation/tests/snapshots/main__extract_subgraphs__does_not_extract_demand_control_directive_name_conflicts.snap
- apollo-federation/tests/snapshots/main__extract_subgraphs__does_not_extract_renamed_demand_control_directive_name_conflicts.snap
When users set up a custom directive which conflicts with demand control directive names, we would incorrectly try to extract that to subgraphs as the federation directive. This updates the extraction code to ignore non-apollo directives when propagating demand control directives to subgraphs.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is an important part of …
> Ignore non-apollo directives when extracting demand control directives to subgraphs

- apollo-federation/src/merge.rs
- apollo-federation/src/sources/connect/expand/tests/mod.rs
- apollo-federation/src/sources/connect/expand/tests/schemas/normalize_names.graphql
- apollo-federation/src/sources/connect/expand/tests/schemas/normalize_names.yaml
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__normalize_names__it_expands_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__normalize_names__it_expands_supergraph-3.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__normalize_names__it_expands_supergraph.snap
This _almost_ completely implements [the JS equivalent](https://github.com/apollographql/federation/blob/c4744da360235d8bb8270ea048f0e0fa5d03be1e/internals-js/src/specs/joinSpec.ts#L18), but I intentionally left out adding the `_` suffix, since it'll update _all_ our snapshots and be messy. It's not obvious to me _why_ that rule was in place initially, and clearly this pattern has been working for us so far, so 🤷.
Implemented with a new type, just so I could easily see all the things this impacts. I reduced/moved a couple clones while updating type signatures, since I was looking.
[CNN-399]: https://apollographql.atlassian.net/browse/CNN-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Normalize subgraph names when generating expanded enum values

- Cargo.lock
- apollo-federation/Cargo.toml
- apollo-federation/src/sources/connect/header.rs
- apollo-federation/src/sources/connect/mod.rs
- apollo-federation/src/sources/connect/models.rs
- apollo-federation/src/sources/connect/spec/directives.rs
- apollo-router/src/plugins/connectors/http_json_transport.rs
- apollo-router/src/plugins/connectors/testdata/steelthread.graphql
- apollo-router/src/plugins/connectors/testdata/steelthread.yaml
- apollo-router/src/plugins/connectors/tests.rs
Add the ability to reference `$config` variables in headers sent to connectors. This allows, for example, specifying a static token in an authorization header.
Config YAML:
```yaml
preview_connectors:
subgraphs:
subgraph_name:
$config:
api_token: ${env.API_TOKEN}
```
GraphQL Schema:
```graphql
@source(
name: "jsonPlaceholder"
http: {
baseURL: "https://jsonPlaceholder.typicode.com/"
headers: [
{ name: "Authorization", value: "Bearer {$config.api_token}" }
]
}
)
```
Note that curly brace characters `{` and `}` are technically allowed within header values. Currently, since the variable reference grammar implemented here only accepts names starting with the `$confg` namespace, this should not cause a problem unless the customer actually wants to send a literal value containing the string …
> Add ability to reference $config in header values

- apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
- apollo-router/src/plugins/telemetry/config.rs
Use the default if it's not explicitly specified. Prevents a breaking change to existing configurations.
Follow-up to #5803 and #5802.
Note we also have a `tracing.experimental_response_trace_id.format` configuration that is required. Should that also be optional, with otel format as the default?
> fix: make new `tracing.propagation.format` config optional

- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__normalize_names__it_expands_supergraph-2.snap
- apollo-federation/src/sources/connect/expand/tests/snapshots/apollo_federation__sources__connect__expand__tests__realistic__it_expands_supergraph-2.snap
- apollo-federation/src/sources/connect/header.rs
- apollo-router/src/plugins/connectors/error.rs
- apollo-router/src/plugins/connectors/handle_responses.rs
- apollo-router/src/plugins/connectors/tests.rs
- apollo-router/src/query_planner/execution.rs
- apollo-router/src/services/fetch_service.rs
With connectors, the subgraph service and connector service are called from a fetch service. This created some differences in how errors from the subgraph service were being reported through the fetch service compared to when the subgraph service was called directly. These differences have been removed, so errors from the subgraph service, or errors when invoking the subgraph service, will be reported exactly as before - always as `FetchError::SubrequestHttpError`.
Additionally, HTTP errors from a connector REST API call are now also reported as `FetchError::SubrequestHttpError`, with the connector information in the `service` extension.
```json
{
"message": "HTTP fetch failed from 'posts.jsonPlaceholder http: GET /users/{$this.id!}/postsd': 404: Not Found",
"code": …
```
> Report connectors errors as fetch errors

- apollo-federation/src/link/cost_spec_definition.rs
- apollo-federation/src/link/database.rs
- apollo-federation/src/link/mod.rs
- apollo-federation/src/merge.rs
- apollo-federation/src/operation/contains.rs
- apollo-federation/src/operation/mod.rs
- apollo-federation/src/operation/optimize.rs
- apollo-federation/src/query_graph/extract_subgraphs_from_supergraph.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/query_plan/fetch_dependency_graph_processor.rs
- apollo-federation/src/query_plan/query_planner.rs
- apollo-federation/src/sources/connect/url_path_template.rs
- apollo-federation/tests/query_plan/build_query_plan_support.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/requires.rs
One of the tests was failing with a non-deterministic QP snapshot failure. I suspected this was due to usage of `HashMap`/`HashSet`, and after converting all usages of them to `apollo_compiler`'s `IndexMap`/`IndexSet`, the test's QP snapshot is now consistent across 100 runs. (We probably don't need to convert all usages for this test to pass, but this may help reduce non-determinism/help reproducibility in the future.)
> fix(federation): change `HashMap`/`HashSet` usage to `IndexMap`/`IndexSet` to avoid non-determinism

- apollo-federation/src/query_graph/graph_path.rs
Previously, the number wasn't included in the error and the placeholder `{num_options}` was printed as is. The actual number is now displayed in the message.
This is a simple error message fix. No behavior changes are expected.
---
**Checklist**
> chore(federation): fixed the error formating of "excessive number of combinations"

- apollo-federation/src/query_graph/build_query_graph.rs
- apollo-federation/src/query_graph/extract_subgraphs_from_supergraph.rs
- apollo-federation/tests/query_plan/build_query_plan_tests/requires.rs
- apollo-federation/tests/query_plan/supergraphs/handles_requires_from_supergraph.graphql
When parsing `@requires` field set selection we need to use supergraph schema instead of a target subgraph schema.
---
**Checklist**
**Exceptions**
**Notes** …
> fix(federation): use supergraph when parsing requires fieldset

- apollo-router/src/services/connect.rs
- apollo-router/src/services/connector_service.rs
- apollo-router/src/services/fetch.rs
- apollo-router/src/services/fetch_service.rs
The connectors PR had a comment about the `![allow(missing_docs)]` attribute. These actually had no effect, since the types are not `pub`. These are removed, and I added a few module and type docs.
---
**Checklist**
**Exceptions**
**Notes** …
> Add missing docs for connectors modules

- .changesets/fix_garypen_fix_sessions_and_handle_reporting.md
- apollo-router/src/axum_factory/axum_http_server_factory.rs
- apollo-router/src/axum_factory/listeners.rs
Session counting incorrectly included connections to the health check or other non-graphql connections. This is now corrected so that only connections to the main graphql port are counted.
Warnings about file handle shortages are now handled correctly as a global resource.
Note: This was manually tested since integration/unit testing isn't really viable.
> Fix session counting and the reporting of file handle shortage

- docs/source/configuration/authn-jwt.mdx
- docs/source/configuration/authn-subgraph.mdx
- docs/source/configuration/csrf.mdx
- docs/source/configuration/distributed-caching.mdx
- docs/source/configuration/entity-caching.mdx
- docs/source/configuration/in-memory-caching.mdx
- docs/source/configuration/operation-limits.mdx
- docs/source/configuration/persisted-queries.mdx
- docs/source/configuration/telemetry/overview.mdx
- docs/source/executing-operations/demand-control.mdx
- docs/source/executing-operations/subscription-support.mdx
Adds a callout/links to relevant GraphQL summit workshops
> docs: add summit callouts

- .changesets/fix_renee_consistent_uplink_type.md
- apollo-router/src/uplink/mod.rs
I'm not sure if this is a legitimate issue but it looks weird.
The `apollo_router_uplink_fetch_duration_seconds` metric has a `query` attribute which normally contains a simplified name, such as `license` for `apollo_router::uplink::LicenseQuery` or `persistentquerymanifest` for `apollo_router::uplink::PersistentQueryManifestQuery`.
But if the uplink fetch *fails*, the query attribute instead contains the whole type name, `apollo_router::uplink::licensequery` instead of `license`.
I suspect these were meant to be the same?
> Use consistent `query` name in uplink metrics

- Cargo.lock
- apollo-router/Cargo.toml
- rust-toolchain.toml
Rowan increased its MSRV to 1.77 in a patch version. Pinning it to the previous patch release should fix the `updated` CI job.
> fix: pin rowan version to pass CI

- apollo-router/src/plugins/connectors/http_json_transport.rs
- apollo-router/src/services/connector_service.rs
Fix a panic I ran into when running performance tests. Also fix a hot spot around string concatenation and allocation that I noticed in the flame graph.
---
**Checklist**
**Exceptions**
**Notes** …
> Fix panic when running from performance test

- apollo-federation/cli/src/main.rs
As titled, operations should not be validated against the supergraph schema
> fix(federation): validate query against API schema in CLI

- Cargo.lock
- fuzz/subgraph/Cargo.toml
- fuzz/subgraph/src/main.rs
Hopefully this will speed up CI since there will be fewer crates to download. Not sure if it works as intended, since I'm not sure what the _expected_ result of running the fuzz test is.
> Remove actix dependencies by switching fuzz subgraph to axum

- apollo-federation/src/link/cost_spec_definition.rs
- apollo-federation/src/query_graph/extract_subgraphs_from_supergraph.rs
Reverts apollographql/router#5847
We won't need this anymore with a bigger refactor cleaning up compilation instead
> Revert "Revert some IndexMap/Set changes that break `--release` builds for x86"

- apollo-federation/src/lib.rs
- apollo-federation/src/query_graph/build_query_graph.rs
- apollo-federation/src/query_graph/mod.rs
- apollo-federation/src/query_plan/fetch_dependency_graph.rs
- apollo-federation/src/supergraph/mod.rs
- apollo-federation/src/supergraph/schema.rs
- apollo-federation/src/supergraph/subgraph.rs
Convert `query_graph::extract_subgraphs_from_supergraph` into `supergraph` with split-up submodules
Refactored _just_ enough to fix compilation times on `next`. We probably want to take a bigger pass in the future to refactor further, work out naming, etc (for example, if there's a `supergraph` mod now, maybe the `Supegraph` struct should be in it?).
> Split up `extract_subgraphs_from_supergraph` module

- apollo-federation/src/sources/connect/validation/extended_type.rs
- apollo-federation/src/sources/connect/validation/snapshots/validation_tests@circular_reference_3.graphql.snap
- apollo-federation/src/sources/connect/validation/snapshots/validation_tests@invalid_entity_arg_on_field.graphql.snap
- apollo-federation/src/sources/connect/validation/test_data/validation/circular_reference_3.graphql
- apollo-federation/src/sources/connect/validation/test_data/validation/invalid_entity_arg_on_field.graphql
Using a second connector to create a relationship on the same type almost works.
```graphql
type Query {
user(id: ID!): User @connect(entity: true, ..., selection: "id name")
}
type User {
id: ID
name: String
friends: [User] @connect(..., selection: "id")
}
```
(This supports `{user{friends{name}}}`.)
But the query planner assumes it can repeatedly recurse and resolve the friends field multiple times with a single fetch.
`{user{friends{friends{...}}}`
```
QueryPlan {
Sequence {
Fetch(service: "users. http: GET http://localhost:4999/users/{$args.id!}") {
{
user(id: $userId) {
__typename
id
name
}
}
},
Flatten(path: "user") {
Fetch(service: "users. http: GET http://localhost:4999/users/{$this.id!}") {
{
... on User {
__typename
id
}
} =>
{
... on User {
friends {
id
friends {
id
}
}
}
}
}, …
```
> disallow direct circular references
