apollographql/router

.changesets/fix_bnjjj_fix_fatal_error_subgraph_response.md, apollo-router/src/services/subgraph_service.rs
When the subgraph connection is closed or in error, return a proper subgraph response containing an error. This was preventing subgraph response service to be triggered in coprocessor and rhai.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever …
=> fix(subgraph_service): when the subgraph connection is closed or in error, return a proper subgraph response

apollo-router/src/plugins/connectors/handle_responses.rs, apollo-router/src/plugins/connectors/make_requests.rs
this is a minor optimization, but for entity requests the selection is always the same so we shouldn't transform the selection mapping for each request
---
**Checklist**
**Exceptions**
**Notes** …
=> refactor: apply_selection once per connector

.changesets/feat_enabling_both_best_effort_query_planners.md, apollo-router/src/configuration/mod.rs, apollo-router/tests/integration/redis.rs
Formally switches `#[default]` to `both_best_effort` for `experimental_query_planner_mode` and adds a changelog entry.
=> feat: enable both_best_effort query planners

.changesets/feat_tninesling_make_demand_control_ga.md, apollo-router/src/configuration/metrics.rs, apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap, apollo-router/src/configuration/testdata/metrics/demand_control.router.yaml, apollo-router/src/plugins/demand_control/fixtures/enforce_on_execution_request.router.yaml, apollo-router/src/plugins/demand_control/fixtures/enforce_on_execution_response.router.yaml, apollo-router/src/plugins/demand_control/fixtures/enforce_on_subgraph_request.router.yaml, apollo-router/src/plugins/demand_control/fixtures/enforce_on_subgraph_response.router.yaml, apollo-router/src/plugins/demand_control/fixtures/measure_on_execution_request.router.yaml, apollo-router/src/plugins/demand_control/fixtures/measure_on_execution_response.router.yaml, apollo-router/src/plugins/demand_control/fixtures/measure_on_subgraph_request.router.yaml, apollo-router/src/plugins/demand_control/fixtures/measure_on_subgraph_response.router.yaml, apollo-router/src/plugins/demand_control/mod.rs, apollo-router/src/plugins/telemetry/testdata/demand_control_delta_filter.router.yaml, apollo-router/src/plugins/telemetry/testdata/demand_control_result_attribute.router.yaml, apollo-router/src/plugins/telemetry/testdata/demand_control_result_filter.router.yaml, apollo-router/src/router_factory.rs, apollo-router/src/uplink/license_enforcement.rs, apollo-router/src/uplink/snapshots/apollo_router__uplink__license_enforcement__test__restricted_features_via_config.snap, apollo-router/src/uplink/testdata/restricted.router.yaml, apollo-router/tests/apollo_reports.rs, apollo-router/tests/fixtures/apollo_reports.router.yaml, apollo-router/tests/fixtures/apollo_reports_batch.router.yaml, docs/source/executing-operations/demand-control.mdx
Renames the `preview_demand_control` feature to `demand_control`, and makes demand control docs more beginner-friendly.
---
**Checklist**
**Exceptions**
**Notes** …
=> Make demand control GA

apollo-federation/src/operation/mod.rs, apollo-federation/tests/query_plan/build_query_plan_tests.rs, apollo-federation/tests/query_plan/supergraphs/redundant_typename_for_inline_fragments_without_type_condition.graphql
When adding `__typename` field for abstract types, we need to check for inline fragment type condition and not the parent selection set. If we have an inline fragment without type condition and it is pointing to and abstract type, then the required `__typename` field should have already been added to its parent field.
We continue adding `__typename` for fragments with a type condition as their type condition _may_ be different than the parent type.
```graphql
foo {  
a
... @skip(if: false) {  
b
}
}
```
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) …
=> fix(federation): remove redundant typename for inline fragments

apollo-federation/src/query_plan/fetch_dependency_graph.rs, apollo-federation/tests/query_plan/build_query_plan_tests.rs, apollo-federation/tests/query_plan/supergraphs/test_merging_fetches_reset_cached_costs.graphql
Fetch dependency graph nodes cache their cost values. And whenever their selection sets get modified, their cached cost must reset. However, we had a few places where that invariant was violated.
The `selection_set_mut` method is supposed to be used, since the method resets the cache. However, other methods could get around it and modify `selection_set` without calling the method. This PR fixes those places to use the `selection_set_mut` method.
---
**Checklist**
[ROUTER-553]: https://apollographql.atlassian.net/browse/ROUTER-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(federation): fixed a bug where cached node costs were not reset after modification

docs/source/configuration/in-memory-caching.mdx
The section immediately below this explains the up-to-date warm-up behaviour
=> docs: remove duplicate old cache warm-up documentation

apollo-federation/src/error/mod.rs, apollo-federation/src/query_plan/query_planner.rs
Two small TODO comments.
- Return a `FederationError::UnknownOperation` when passed an operation name that does not exist.
- Remove the panic comment about empty selection sets: panicking doesn't add anything there, though it is technically unreachable.
=> chore(federation): address two TODOs in `build_query_plan`

.changesets/docs_feature_operationlimitsotel.md, docs/source/configuration/operation-limits.mdx
Add OTEL information for operation limits
---
**Checklist**
**Exceptions**
**Notes**
=> Add OTEL information for operation limits

Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs, apollo-router/src/plugins/progressive_override/snapshots/apollo_router__plugins__progressive_override__tests__non_overridden_field_yields_expected_query_plan.snap, apollo-router/src/plugins/progressive_override/snapshots/apollo_router__plugins__progressive_override__tests__overridden_field_yields_expected_query_plan.snap, apollo-router/src/plugins/snapshots/apollo_router__plugins__expose_query_plan__tests__it_expose_query_plan-2.snap, apollo-router/src/plugins/snapshots/apollo_router__plugins__expose_query_plan__tests__it_expose_query_plan.snap, apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__plan_root.snap, apollo-router/tests/integration/redis.rs, apollo-router/tests/integration/snapshots/integration_tests__integration__redis__query_planner_cache.snap, apollo-router/tests/snapshots/set_context__set_context.snap, apollo-router/tests/snapshots/set_context__set_context_dependent_fetch_failure.snap, apollo-router/tests/snapshots/set_context__set_context_list.snap, apollo-router/tests/snapshots/set_context__set_context_list_of_lists.snap, apollo-router/tests/snapshots/set_context__set_context_no_typenames.snap, apollo-router/tests/snapshots/set_context__set_context_type_mismatch.snap, apollo-router/tests/snapshots/set_context__set_context_union.snap, apollo-router/tests/snapshots/set_context__set_context_unrelated_fetch_failure.snap, apollo-router/tests/snapshots/set_context__set_context_with_null.snap, apollo-router/tests/snapshots/type_conditions__type_conditions_disabled.snap, apollo-router/tests/snapshots/type_conditions__type_conditions_enabled.snap, apollo-router/tests/snapshots/type_conditions__type_conditions_enabled_generate_query_fragments.snap, apollo-router/tests/snapshots/type_conditions__type_conditions_enabled_list_of_list.snap, apollo-router/tests/snapshots/type_conditions__type_conditions_enabled_list_of_list_of_list.snap, apollo-router/tests/snapshots/type_conditions__type_conditions_enabled_shouldnt_make_article_fetch.snap
This pulls in the latest beta release of router-bridge which includes directives when serializing subgraph schemas.
The demand control tests have been updated to test both the JS and Rust query planners to ensure the new router-bridge resolves the issue.
This includes directives which previously were missing, which changed query hashes in several tests. Most of the files touched in this PR are updating query hashes in snapshots.
---
**Checklist**
**Exceptions**
**Notes** …
=> Use router-bridge beta.1

apollo-federation/src/sources/connect/expand/mod.rs
This commit makes it so that all inputs to a field decorated by a connect directive get expanded into the generated subgraph.
Before this change, certain graph configurations would not carry over input types which caused composition to fail.
---
**Checklist**
**Exceptions**
**Notes** …
=> connectors: always expand inputs

docs/source/configuration/experimental_query_planning_mode.mdx
Moved over from #5883 due to me messing up a change of base branch.
This PR introduces hidden docs for the experimental query planning mode.
=> docs: add noIndex:true docs for experimental query planning mode

docs/source/configuration/experimental_query_planner_mode.mdx
The file previously used "experimental query **planning** mode" instead of "experimental query **planner** mode", which did not match the feature flag name. This fixes the name to match the feature flag.
=> docs: rename experimental query planner mode title

CHANGELOG.md
Follows-up: https://github.com/apollographql/router/pull/5904
=> docs(changelog): Fix broken link for experimental queryplanner docs.

apollo-federation/src/sources/connect/json_selection/pretty.rs, apollo-router/src/plugins/connectors/plugin.rs
This commit fixes top-level selections from being erroneously wrapped in `{}`, better matching what the user specified in the original schema.
It also adds a bit of documentation to structs encountered during the fix.
---
**Checklist**
**Exceptions**
**Notes** …
=> connectors: fix JSONSelection pretty printing

Cargo.lock, apollo-router/Cargo.toml
1.40.0 has its MSRV set to 1.78., while we only support 1.76 for now
---
**Checklist**
**Exceptions**
**Notes** …
=> Fix aws-sdk-sso to 1.39.0

docs/source/configuration/telemetry/exporters/metrics/new-relic.mdx
New Relic configuration requires the use of the trailing `/v1/metrics` values, not just the initial part of the URL.
[ROUTER-687]: https://apollographql.atlassian.net/browse/ROUTER-687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Use specific URL examples in New Relic

.changesets/config_musket_minute_linen_kitchen.md, dockerfiles/Dockerfile.router, helm/chart/router/README.md, helm/chart/router/templates/deployment.yaml, helm/chart/router/values.yaml
When we want to use debug mode, we can only get 1 file per node in Kubernetes, this change allows us to do 2 things:
- set `restartPolicy` of pod as desired.
- add hostname in path for collecting healtrack data.
Fixes #5789
---
**Checklist**
**Exceptions**
**Notes** …
=> feat: ease of use debugging

apollo-federation/src/query_plan/fetch_dependency_graph.rs
Currently, if we produce an invalid subgraph operation, it looks exactly the same as a validation error from the input query. This makes issues harder to debug.
This PR turns validation errors at the end of planning into internal errors, so we know where they come from, and so end users do not get confused about what a validation error means. The new error explicitly mentions that it's a bug in the query planner that should be reported to Apollo.
It's not possible to add a test for this, as it only triggers for bugs. I manually tested it with the bug that's fixed in #5785:
```
Details: Query planning produced an invalid subgraph operation.
Error: fragSpreadOnly directive is not supported for INLINE_FRAGMENT location
```
=> fix(federation): treat invalid subgraph operations as internal errors

docs/source/customizations/rhai-api.mdx
Clarify in text and code samples that throwing exception to terminate client requests from Rhai must happen from supergraph service.
=> docs: Clarify terminating client requests with Rhai exception must be thrown from supergraph

apollo-federation/src/sources/connect/header.rs, apollo-router/src/plugins/connectors/handle_responses.rs, apollo-router/src/plugins/connectors/make_requests.rs, apollo-router/src/plugins/connectors/testdata/steelthread.graphql, apollo-router/src/plugins/connectors/testdata/steelthread.yaml, apollo-router/src/plugins/connectors/tests.rs
Add the ability to define headers for connectors that reference request context values. For example, this allows REST API calls made by connectors to include a header with the JWT claims added by a Coprocessor.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: …
=> Add ability to reference request context values in headers

docs/source/config.json
This PR removes the "Preview" icon next to demand control in the docs nav. It also removes the page from showing up from two places in the nav.
=> docs: remove preview from demand control in nav

apollo-router/src/services/connector_service.rs
Replace the internal connectors subgraph name with the connector in error responses. Previously, errors at the HTTP transport level were returning the internal subgraph name.
The error response now looks like:
```json
{
"data": null,
"errors": [
{
"message": "HTTP fetch failed from 'characters.simpsons http: GET /characters': error trying to connect: tcp connect error: Connection refused (os error 61)",
"path": [],
"code": "SUBREQUEST_HTTP_ERROR",
"service": "characters.simpsons http: GET /characters",
"reason": "error trying to connect: tcp connect error: Connection refused (os error 61)"
}
}
],
"valueCompletion": [
{
"message": "Cannot return null for non-nullable field Query.characters",
"path": []
}
]
}
}
```
---
**Checklist**
Complete the checklist …
=> Replace internal connectors subgraph name in errors

apollo-federation/src/operation/merging.rs, apollo-federation/src/operation/mod.rs, apollo-federation/src/operation/optimize.rs, apollo-federation/src/operation/simplify.rs, apollo-federation/src/operation/tests/mod.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_plan/conditions.rs, apollo-federation/src/query_plan/fetch_dependency_graph.rs, apollo-federation/tests/query_plan/build_query_plan_tests/requires/include_skip.rs, apollo-federation/tests/query_plan/supergraphs/it_handles_a_simple_at_requires_triggered_within_a_conditional.graphql, apollo-federation/tests/query_plan/supergraphs/it_handles_an_at_requires_triggered_conditionally.graphql, apollo-federation/tests/query_plan/supergraphs/it_handles_an_at_requires_where_multiple_conditional_are_involved.graphql
This PR introduces two optimizations to `SelectionSet::merge_selections_into`.
The simpler of the two removes the intermediate buffers used in the method. Now, selections whose keys already exist in the selection map are immediately merged together. This means there is more recursion but no allocating buffers. It remains unclear if this will have any performance impact (positive or negative), but it simplifies the code by a fair amount. Because of this, all of the `*SelectionValue::merge_into` methods have also be refactored to take a single selection rather than an iterator. This removes more intermediate buffering.
The second change, which actually relates to the ticket, adds logic to `Selection::from_element` to remove optionally unnecessary directives from the element. The intention …
=> Refactor SelectionSet::merge_selections_into and remove unnecessary directives in Selection::from_element

apollo-federation/src/utils/fallible_iterator.rs, apollo-federation/src/utils/mod.rs
When I created the `FallibleIterator` extension trait, all of the tests were doc tests. Due to a visibility issue, these tests were failing. Moreover, doc tests (at least for `apollo-federation`) are not checked in CI. These makes running `cargo test` locally annoying because you see a bunch of failures and unhelpful in CI because they aren't ran.
To fix this, I added `ignore` too all examples in the docs and copied the examples into unit tests.
---
**Checklist**
**Exceptions**
**Notes** …
=> Moves tests for `FallibleIterator`

apollo-router/src/plugins/connectors/handle_responses.rs, apollo-router/src/plugins/connectors/tests.rs, apollo-router/src/plugins/include_subgraph_errors.rs, apollo-router/src/services/fetch.rs, apollo-router/src/services/fetch_service.rs
If `include_subgraph_errors` if false for a subgraph containing connectors, any errors returned by connectors HTTP requests will be redacted from the response. Note that if the connectors debugging feature is enabled, information about the failed request will still be returned in the debug data.
Note that because the `include_subgraph_errors` plugin doesn't know about connectors, and connectors don't have access to the `include_subgraph_errors` plugin, there is no direct way to do the redaction. Instead, the connectors feature stores the subgraph name on the error as an extension, and the plugin checks for this extension to see if the error should be redacted.
With `include_subgraph_errors` set to `true`:
```json
{
"data": null,
"errors": [
{
"message": "HTTP fetch failed from …
```
=> Add support for include_subgraph_errors to connectors

apollo-federation/src/query_plan/fetch_dependency_graph.rs, apollo-federation/tests/query_plan/build_query_plan_tests.rs, apollo-federation/tests/query_plan/supergraphs/handles_multiple_conditions_on_abstract_types.graphql
In JS implementation, conditions were recalculated at the very end when we were creating final selection set. We were missing condition update in one of the update paths.
---
**Checklist**
**Exceptions**
**Notes** …
=> fix(federation): always update conditions on FetchSelectionSet updates

apollo-federation/cli/src/main.rs
This PR adds a new CLI option to apollo-federation to allow for just expanding supergraphs to either stdout or a specified folder.
```bash
cargo run -p apollo-federation-cli -- expand <SUPERGRAPH>
```
The command also supports specifying a prefix to limit which expanded subgraphs to show using the flag `--filter-prefix <PREFIX>`.
__Note: This is mainly for debugging expansion while we wait for a source-aware future. Do NOT rely on the output of this command for anything other than debugging or reference.__
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other …
=> connectors: add debug cli for expansion

apollo-router/src/plugins/connectors/handle_responses.rs, apollo-router/src/plugins/connectors/http.rs, apollo-router/src/plugins/connectors/http_json_transport.rs, apollo-router/src/plugins/connectors/make_requests.rs, apollo-router/src/plugins/connectors/plugin.rs, apollo-router/src/services/connector_service.rs
instead of inserting into the debug extension twice, we can pass around the debug request object and insert the request and response at the same time, ensuring that we never match a response to the wrong request
also stops passing the schema into handle_requests—the selection set we pass in is schema-aware
---
**Checklist**
**Exceptions**
**Notes** …
=> fix debug concurrency

.changesets/fix_bryn_fix_gauges.md, apollo-router/src/cache/mod.rs, apollo-router/src/cache/storage.rs, apollo-router/src/metrics/aggregation.rs, apollo-router/src/query_planner/caching_query_planner.rs, apollo-router/src/services/supergraph/service.rs, apollo-router/tests/integration/telemetry/metrics.rs
When a hot reload happens the opentelemetry meter provider is refreshed.
Gauges in particular MUST be created after this refresh has happened.
The query planner pipeline is currently created outside of the plugin lifecycle, and therefore does not have the opportunity to do this.
We can consider reintroducing the `query_planner` and `activate` hooks in plugins in future it would probably help, or have some equivalent. But for now this PR just adds an `activate` call that is threaded right down to the `CacheStorage`. This can be called on the query planner pipeline after telemetry has been activated.
This is tested in integration test by starting the router without prometheus and then adding it after a reload.
---
**Checklist**
Complete the checklist (and note appropriate exceptions) before …
=> Fix query plan cache gauges that stopped working after hot reload

apollo-federation/src/sources/connect/expand/mod.rs, apollo-federation/src/sources/connect/expand/tests/schemas/expand/keys.graphql, apollo-federation/src/sources/connect/expand/tests/schemas/expand/keys.yaml, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@keys.graphql-2.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@keys.graphql-3.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@keys.graphql.snap
This PR adds support for tracking sibling relationships in the actual selection of a connector. Previous behaviour was to only track this sibling relationships from the transport body and HTTP path template.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: …
=> connectors: track $this usage in selection

.changesets/fix_bryn_fix_gauges.md, apollo-router/src/query_planner/bridge_query_planner_pool.rs, apollo-router/src/query_planner/caching_query_planner.rs, apollo-router/tests/integration/telemetry/metrics.rs
The v8 heap usage and queue gauges were not working after hot reload.
This is because gauges MUST be created after the global meter provider is updated.
This builds on the work from #5996 by introducing an `activate` function to populate the gauges when we are ready.
The integration test from 5996 is extended to test for the extra metrics.
---
**Checklist**
**Exceptions**
Bug fix, no docs needed
Unit tests don't capture reload of router, so this is done in integration tests.
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing …
=> Fix v8 gauges on hot reload

.changesets/fix_tninesling_demand_control_variable_check.md, apollo-router/src/graphql/visitor.rs, apollo-router/src/json_ext.rs, apollo-router/src/plugins/demand_control/cost_calculator/directives.rs, apollo-router/src/plugins/demand_control/cost_calculator/fixtures/custom_cost_query_with_variable_slicing_argument.graphql, apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs, apollo-router/src/plugins/demand_control/mod.rs, apollo-router/src/plugins/demand_control/strategy/static_estimated.rs, apollo-router/src/plugins/telemetry/config_new/graphql/mod.rs, apollo-router/src/plugins/telemetry/metrics/local_type_stats.rs, apollo-router/src/plugins/telemetry/mod.rs
We're missing variable support in demand control scoring, so they're currently not counted. Additionally, they don't get passed through to the list size directive, which prevents users from using variables as slicing arguments. This change includes the request variables in context extensions so they can be accessed from the demand control plugin pipeline.
This includes a small refactor to wrap some of the common scoring arguments (schema, request document, etc) into a scoring context to reduce the number of arguments to each function.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to …
=> Include request variables in demand control scoring

apollo-router/src/plugins/telemetry/reload.rs, apollo-router/tests/common.rs, apollo-router/tests/integration/telemetry/datadog.rs, apollo-router/tests/integration/telemetry/fixtures/datadog_no_sample.router.yaml
#5788 introduced a regression where samping was being set on propagated headers regardless of the sampling decision in the router or upstream.
This PR reverts the code in question and adds a test to check that a non-sampled request will not result in sampling in the downstream subgraph service.
---
**Checklist**
**Exceptions**
* Bug fix so no docs change.
* Integration test rather than unit test because this is telemetry.
**Notes** …
=> Fix datadog sample propagation

apollo-router/src/query_planner/bridge_query_planner.rs
Planning code is synchronous (it never `await`s) and can take non-trivial time, so it is effectively "blocking" from Tokio’s point of view. If too many Tokio threads are busy planning queries, few threads remain available to run async code.
This runs the planner inside `tokio::task::spawn_blocking`, following the precedent of graphql parsing in `query_analysis.rs`. This uses a thread pool of maximum size 512 threads, which may not be what we want. From its documentation, `spawn_blocking` appears to be made for code that often blocks in synchronous syscalls.
Instead we may prefer to have a thread pool for "compute tasks" that defaults to $NUM_CPUS threads, and wrap it with something that uses `tokio::sync::oneshot` to send results back to async code.
=> Run new query planner off of Tokio threads

apollo-federation/src/sources/connect/validation/entity.rs, apollo-federation/src/sources/connect/validation/extended_type.rs, apollo-federation/src/sources/connect/validation/mod.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@valid_no_connect_on_resolvable_key_field.graphql.snap, apollo-federation/src/sources/connect/validation/test_data/valid_no_connect_on_resolvable_key_field.graphql
The validation to check that entity fields are resolvable through `@connect` directives was incorrectly marking resolvable key fields as errors. The key fields are now added to the list of visited fields to prevent this. This requires iterating down a tree of key fields if there are input types in use. That is implemented using a `Vec`-based stack instead of recursion, and it has checks to avoid cycles. Also added a unit test, and refactored some code to handle `@key` directives to avoid code duplication.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour …
=> Allow resolvable key fields to have no connect directive

.changesets/fix_bryn_fix_gauges.md, apollo-router/src/introspection.rs, apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs, apollo-router/src/plugins/test.rs, apollo-router/src/query_planner/bridge_query_planner.rs, apollo-router/src/query_planner/bridge_query_planner_pool.rs, apollo-router/src/services/layers/apq.rs, apollo-router/src/services/router/service.rs, apollo-router/tests/common.rs, apollo-router/tests/integration/telemetry/fixtures/prometheus.router.yaml, apollo-router/tests/integration/telemetry/metrics.rs
Similar to the query planner gauges, these must be initialized after telemetry has been activated.
Fixes:
* `apollo_router_cache_size` for `APQ` and `introspection`
As a result of this change every query planner in the query planner pool will share the same cache storage for introspection queries. Otherwise many identical gauges are created, and they are not summed. It doesn't really make sense that each query planner should have a separate cache anyway.
Another issue was noticed, and commented on. APQLayer uses deduplicating cache which is fallible. This is initialized after telemetry has been activated, so if it fails it is likely that telemetry will stop working. This is not fixable without a larger refactor to bring APQ init forward, which is out of scope for this PR. We'll tackle …
=> Fix APQ and introspection gauges

apollo-federation/src/sources/connect/json_selection/apply_to.rs, apollo-federation/src/sources/connect/json_selection/helpers.rs, apollo-federation/src/sources/connect/json_selection/methods.rs, apollo-federation/src/sources/connect/json_selection/methods/future.rs, apollo-federation/src/sources/connect/json_selection/methods/public.rs
Following up on this suggestion from @nicholascioli: https://github.com/apollographql/router/pull/5762#discussion_r1727811782
The `apply_to_path` method used to have more than one mutable parameter (`input_path` as well as `errors`), but now that `input_path` is immutable, I agree it's cleaner to go all the way and avoid any mutable parameters, so `apply_to_path` can be a pure function.
One big benefit of this refactoring is that each `apply_to_path` method now returns just the errors resulting from the subtree that it handled, whereas the previous `&mut errors: IndexSet<ApplyToError>` strategy made it difficult to know which errors came from which `apply_to_path` method call. This will help if we ever decide to memoize the results of `apply_to_path` methods, or if we want to expose …
=> [JSONSelection] Remove `&mut errors: IndexSet<ApplyToError>` from `apply_to_path` method signatures

.changesets/config_introspection_both.md, Cargo.lock, Cargo.toml, apollo-router/src/configuration/mod.rs, apollo-router/src/query_planner/bridge_query_planner.rs, apollo-router/src/query_planner/dual_introspection.rs, apollo-router/src/query_planner/mod.rs, apollo-router/tests/integration/introspection.rs, examples/supergraph-sdl/rust/Cargo.toml
* Update apollo-compiler to fix ROUTER-703 introspection incorrectly listing unused built-in scalars: https://github.com/apollographql/apollo-rs/pull/911
* Run Rust introspection off of Tokio threads, with the same reasoning as for the query planner in https://github.com/apollographql/router/pull/5998
* Enable introspection "both" mode by default. The legacy implementation is still used in the response but both are run and their results compared. The result of comparing both responses is logged at `DEBUG` level. At `TRACE` level, mismatches print the full query and the response diff. Example usage: `router --log error,apollo_router=info,apollo_router::query_planner::dual_introspection=trace`
---
**Checklist** …
=> Fix introspection bug, run off Tokio threads, enable "both" mode

apollo-router/src/query_planner/dual_introspection.rs, apollo-router/src/query_planner/dual_query_planner.rs, apollo-router/tests/integration/introspection.rs
At this point majority of the comparison cases in query planner semantic diffing match, we can move the trace for matched case to `trace`.
And in order to get a better insight on introspection mismatches, the log level for introspection comparison diff is moved up to `debug`.
=> adjust log levels for introspection and query planner mismatches

apollo-federation/src/query_graph/build_query_graph.rs, apollo-federation/src/query_graph/mod.rs, apollo-federation/tests/query_plan/build_query_plan_tests/interface_object.rs
`SimultaneousPathsWithLazyIndirectPaths::indirect_options` function acts as a tie-breaker when two options lead to the same plan costs, since the first one beats the others. Thus, the ordering of its return value gets to determine the shape of query plan in certain cases.
`indirect_options` calls `advance_with_non_collecting_and_type_preserving_transitions`, which in turn calls `GraphPath::next_edges`. In most cases, the `next_edges` method returns the `non_trivial_followup_edges` struct's value. The `non_trivial_followup_edges` stores its value in `IndexSet<EdgeIndex>` and its `iter()` method preserves its insertion order. Therefore, the ordering eventually depends on the order in which the set was constructed.
The `non_trivial_followup_edges` struct is constructed in the …
=> updated `non_trivial_followup_edges` to use `Vec`, instead of IndexSet

.circleci/config.yml
We use Rust nightly on CI in order to check that fuzz targets can still compile. With current latest nightly we’re running into a compiler panic: https://github.com/rust-lang/rust/issues/130769
To unblock merging PRs, this pins the nightly version used on CI to a slightly older one that does not have this panic. This should be reverted after the panic is fixed in a new Rust nightly.
=> Temporarily pin CI to Rust nightly-2024-09-22

Cargo.lock, Cargo.toml, apollo-federation/src/compat.rs, apollo-federation/src/link/argument.rs, apollo-federation/src/link/database.rs, apollo-federation/src/link/mod.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_graph/mod.rs, apollo-federation/src/query_plan/conditions.rs, apollo-federation/src/supergraph/mod.rs, apollo-router/src/plugins/authorization/policy.rs, apollo-router/src/plugins/authorization/scopes.rs, apollo-router/src/plugins/demand_control/cost_calculator/directives.rs, apollo-router/src/plugins/progressive_override/mod.rs, apollo-router/src/query_planner/dual_introspection.rs, apollo-router/src/spec/query/change.rs, apollo-router/src/spec/schema.rs, apollo-router/src/spec/selection.rs, apollo-router/src/uplink/license_enforcement.rs, apollo-router/tests/fixtures/introspect_full_schema.graphql, apollo-router/tests/fixtures/schema_to_introspect.graphql, apollo-router/tests/integration/introspection.rs, apollo-router/tests/integration/snapshots/integration_tests__integration__introspection__both_mode_integration.snap, apollo-router/tests/integration/snapshots/integration_tests__integration__introspection__integration.snap, examples/supergraph-sdl/rust/Cargo.toml
… to correctly return the default string instead of `null` for argument-less `@deprecated`.
https://github.com/apollographql/apollo-rs/pull/914 also renames `argument_for_name` to `specified_argument_for_name`, leaving the previous name for a new method that accounts for default value and nullability.
Additionally, introspection response comparison in "both" mode now tolerates differences in the ordering of input object fields in `defaultValue` strings.
Together, these two changes fix the remaining known sources of mismatch.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the …
=> Fix introspection `deprecationReason` field

apollo-router/src/services/subgraph_service.rs
This is failing due to a XCode version issue, and blocking releases right now. DEactivating the test only on OSX ensures we at least check it for linux
---
**Checklist**
**Exceptions**
**Notes** …
=> deactivate test_subgraph__service_panic on OSX

apollo-federation/src/query_plan/query_planning_traversal.rs
This PR removes option pruning in `compute_best_plan_from_closed_branches()`, as it has been removed from JS QP. (The reasoning was that it was observed pruning could save time in some cases, but could be substantially worse in a few others.) Note that we should also be able to get rid of overriding IDs, although that requires changing more code (and the JS QP hasn't done it yet either), so I'm leaving it to the future/later PRs.
=> Remove pruning when computing best plan

apollo-router/src/query_planner/dual_query_planner.rs
Summary:
- case 1: JS QP may convert an enum value into string. Compare JS string value and Rust enum value by the content.
- case 2: Rust QP expands an empty object value by filling in its default field values. Consider any JS empty object values are equal to any Rust object values (assuming Rust field values are all default values).
Includes a few unit tests for positive matching.
Corpus run in progress...
---
**Checklist**
[ROUTER-753]: https://apollographql.atlassian.net/browse/ROUTER-753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(dual-query-planner): improved semantic diff to handle default value differences

.changesets/config_renee_router_768_mode_metrics.md, apollo-router/src/configuration/metrics.rs, apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__experimental_mode_metrics.snap, apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__experimental_mode_metrics_2.snap, apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__experimental_mode_metrics_3.snap
We have metrics comparing Rust and JS QP / introspection, which implies we know how many customers are running `both` versions. But we don’t really know who is opting out, and we also have no way to know if someone is using `new`, which we hope to try out with specific customers soon.
This reports configuration values to Apollo:
- `apollo.router.config.experimental_query_planner_mode` with `mode={legacy,both_best_effort,both,new}`
- `apollo.router.config.experimental_introspection_mode` with `mode={legacy,both,new}`
**Todo**:
---
**Checklist**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to …
=> telemetry: add metrics for Rust vs. Deno configuration values

.changesets/fix_bnjjj_fix_fatal_error_subgraph_response.md, apollo-router/src/services/subgraph_service.rs, apollo-router/tests/integration/file_upload.rs, apollo-router/tests/integration/telemetry/datadog.rs
This backports the fix from #5859 to a minor on 1.52.x, landing on top of https://github.com/apollographql/router/releases/tag/v1.52.1.
=> fix(subgraph_service): when the subgraph connection is closed or in error, return a proper subgraph response (#5859)

apollo-federation/src/sources/connect/validation/graphql/strings.rs
It looks like #6058 updated `apollo-compiler` to a version where `Directive::argument_by_name` takes a `name` and a `schema`, rather than just a `name`, and then #6031 (which was passing tests on its own) was merged on top of #6058 without a final rebase/retest, so [the build is currently failing on `next`](https://app.circleci.com/pipelines/github/apollographql/router/26494/workflows/94f5ba5d-a8e9-49ad-ba75-b9d754b05bf9/jobs/191856).
=> Fix small merge conflict between #6031 and #6058

apollo-router/src/plugins/connectors/plugin.rs
with rover dev or hot reloading, plugins are initialized each supergraph update, leading to redundant logs
---
**Checklist**
**Exceptions**
**Notes** …
=> fix: emit connectors debugging log only once

.changesets/chore_update_router_bridge_292.md, Cargo.lock, apollo-router/Cargo.toml, apollo-router/tests/integration/redis.rs, fuzz/Cargo.toml
Update to latest router-bridge and federation version. This federation version fixes sibling `__typename` optimization (that will reduce JS vs RS QP mismatch) and `@context/@fromContext` fix for handling argument name collisions.
=> chore: update router-bridge@0.6.3+v2.9.2

apollo-router/src/query_planner/dual_introspection.rs, apollo-router/tests/fixtures/schema_to_introspect.graphql, apollo-router/tests/integration/snapshots/integration_tests__integration__introspection__both_mode_integration.snap, apollo-router/tests/integration/snapshots/integration_tests__integration__introspection__integration.snap
In GraphQL introspection response, the `defaultValue` of an anrgument or input object field is represented as a JSON string that contains GraphQL syntax. If that value contains a GraphQL object value, graphql-js seems to sort its contents by input object field name whereas apollo-compiler preserves the source ordering.
This causes introspection JSON responses to be different in a way that we consider not to be meaningful: object values are semantically unordered maps. Introspection "both" mode already had code to sort object values in order to ignore these differences, but was missing the case where `defaultValue` is not directly an object value but a list value of object values.
---
**Checklist** …
=> Fix introspection false mismatch: defaultValue list of objects

.circleci/config.yml
This reverts PR https://github.com/apollographql/router/pull/6048 now that https://github.com/rust-lang/rust/issues/130769 is fixed.
Fixes ROUTER-764
---
**Checklist**
**Exceptions**
**Notes** …
=> Revert "Temporarily pin CI to Rust nightly-2024-09-22 (#6048)"

apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@keys.graphql-2.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@realistic.graphql-2.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@simple.graphql-2.snap, apollo-federation/src/sources/connect/expand/visitors/mod.rs, apollo-federation/src/sources/connect/expand/visitors/selection.rs, apollo-federation/src/sources/connect/json_selection/README.md, apollo-federation/src/sources/connect/json_selection/apply_to.rs, apollo-federation/src/sources/connect/json_selection/grammar/Path.svg, apollo-federation/src/sources/connect/json_selection/grammar/PathSelection.svg, apollo-federation/src/sources/connect/json_selection/grammar/PathWithSubSelection.svg, apollo-federation/src/sources/connect/json_selection/location.rs, apollo-federation/src/sources/connect/json_selection/methods/tests.rs, apollo-federation/src/sources/connect/json_selection/parser.rs, apollo-federation/src/sources/connect/json_selection/pretty.rs, apollo-federation/src/sources/connect/json_selection/selection_set.rs, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__location__tests__arrow_path_ranges.snap, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__location__tests__parse_with_range_snapshots.snap, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__parser__tests__expr_path_selections.snap, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__parser__tests__path_with_subselection-2.snap, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__parser__tests__path_with_subselection-3.snap, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__parser__tests__path_with_subselection-4.snap, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__parser__tests__path_with_subselection-5.snap, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__parser__tests__path_with_subselection-6.snap, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__parser__tests__path_with_subselection-7.snap, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__parser__tests__path_with_subselection.snap, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__parser__tests__selection.snap, apollo-federation/src/sources/connect/validation/selection.rs, apollo-router/src/plugins/connectors/make_requests.rs
It was pointed out to me recently (by @dylan-apollo and @lennyburdette) that JSONSelection strings sometimes become unnecessarily verbose when you want to include one or more fields from a higher level of an input object, along with multiple fields extracted from some deeply nested path within that object.
For example, the response shape returned by the [OpenAI `/chat/completions` endpoint](https://platform.openai.com/docs/api-reference/chat) buries the actual response text from the LLM within an array of `choices`, containing objects with a `message` property that provides the `role` and `content` of the response, where the `content` is the desired response from the LLM (irrelevant properties omitted for clarity):
```json
{
"id": "chatcmpl-123",
"created": 1677652288,
"model": …
```
=> [JSONSelection] Allow `NamedSelection ::= Path SubSelection | ...` without an `Alias` for flattening multiple deeply nested properties

apollo-federation/src/sources/connect/json_selection/apply_to.rs, apollo-federation/src/sources/connect/json_selection/lit_expr.rs, apollo-federation/src/sources/connect/json_selection/parser.rs, apollo-federation/src/sources/connect/json_selection/pretty.rs, apollo-federation/src/sources/connect/json_selection/selection_set.rs, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__parser__tests__path_with_subselection-6.snap, apollo-federation/src/sources/connect/json_selection/snapshots/apollo_federation__sources__connect__json_selection__parser__tests__selection.snap, apollo-federation/src/sources/connect/validation/test_data/all_fields_selected.graphql, apollo-federation/src/sources/connect/validation/test_data/disallowed_abstract_types.graphql, apollo-router/src/plugins/connectors/handle_responses.rs, apollo-router/src/plugins/connectors/make_requests.rs, apollo-router/src/plugins/connectors/testdata/selection.graphql, apollo-router/src/plugins/connectors/testdata/selection.yaml
Now that PR #6076 allows `PathWithSubSelection` syntax to appear within a `SubSelection` alongside other named selections, the shorthand of using `.field` to refer to a path consisting of a single `field` key has become potentially ambiguous:
```graphql
__typename: $("Product")
.field { nested child }
```
Because parsing is insensitive to spaces/newlines/comments between tokens, this code parses the same as
```graphql
__typename: $("Product").field { nested child }
```
which produces a runtime `ApplyToError` because the `"Product"` string does not have a `field` property.
Fortunately, using the `$` variable (i.e. `$.field`, introduced in #5142) has identical behavior to the shorthand, and does not suffer from any parsing ambiguity:
```graphql
__typename: $("Product")
$.field { nested …
```
=> [JSONSelection] Forbid single-`.key` paths, requiring `$.key` instead

apollo-federation/src/operation/simplify.rs
Some of our customers have a query shape like this:
```graphql
{
nodes {
__typename
... on MySpecialNode {
value
}
... on HasNodes {
... on Node {
__typename
... on MySpecialNode {
value
}
}
}
}
}
```
Here, we know that the second `MySpecialNode` fragment is redundant, as the first instance of the fragment will always already select the `nodes.value` field. We currently do not remove the redundant fragment.
This PR fixes `flatten_unnecessary_fragments` so it matches JS QP and removes the second instance of the fragment. The actual fix is https://github.com/apollographql/router/pull/6082/commits/7e9adbdc6c1203223a3881b43d685499a3c815b9, the other changes in simplify.rs are to add a test and to remove some unnecessary clones.
[ROUTER-782]: …
=> fix(federation): fix lifting selections when flattening inline fragments

apollo-federation/src/operation/optimize.rs
Sometimes, fragment reuse would leave behind a selection in a selection
set that is also part of a fragment that was applied to that selection
set. That's suboptimal.
An example from the Apollo codebase is an output like this:
```graphql
{
descendants {
...TraceNodeFragment
errors {
locations {
__typename
line
column
}
}
}
}
fragment TraceNodeFragment on Trace {
errors {
locations {
__typename
line
column
}
}
}
```
Here `errors.locations.*` is selected twice.
The cause is this difference in our `intersection` implementation:
https://github.com/apollographql/federation/blob/df5eb3cb0e2b4802fcd425ab9c23714de2707db3/internals-js/src/operations.ts#L2676-L2680
If a field selection's subselection completely disappears in
`intersection()`, we previously kept the field selection, instead of …
=> fix(federation): fix left-behind selections in fragment reuse

apollo-federation/src/schema/mod.rs
We discussed what to do with this in the triage call,
recording the outcome of the discussion so we don't have to talk about it again later :)
=> chore(federation): clarify TODO comment that we will keep for query planning GA

apollo-router/src/query_planner/dual_query_planner.rs
Summary:
- updated the coercion check to recurse into List and Object values.
- loosened Object value check to be a inclusion check, instead of empty check
---
**Checklist**
[ROUTER-753]: https://apollographql.atlassian.net/browse/ROUTER-753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(dual-query-planner): fixed the remaining of coercion mismatches between Rust QP and JS QP

apollo-federation/src/operation/optimize.rs, apollo-federation/tests/query_plan/build_query_plan_tests/fragment_autogeneration.rs, apollo-federation/tests/query_plan/supergraphs/same_as_js_router798.graphql
This is to match the JavaScript implementation. We can get rid of it
later.
[ROUTER-798]: https://apollographql.atlassian.net/browse/ROUTER-798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(federation): do not generate fragments without type condition

apollo-federation/src/error/mod.rs, apollo-federation/src/operation/merging.rs, apollo-federation/src/operation/rebase.rs, apollo-federation/src/operation/simplify.rs
We use a mix of internal errors and debug asserts for invariant violations. Returning an internal error is quite verbose:
```rust
return Err(FederationError::internal(format!("message: {}", some_value)));
// with a longer message, this becomes 3 or more lines
```
This PR proposes two new macros: `internal_error!()` and `ensure!()`.
`internal_error!()` takes `format!()` syntax and returns an internal error from the surrounding function. The above snippet becomes:
```rust
internal_error!("message: {}", some_value);
```
`ensure!()` is a panicky assertion in debug mode, and returns an internal error in release mode. It replaces the `if invariant { internal_error!() }` pattern.
```rust
ensure!(self.schema() == other.schema(), "cannot merge selections from different schemas");
```
`ensure!()` …
=> chore(federation): Add macros for internal errors

apollo-federation/src/query_plan/conditions.rs, apollo-federation/tests/query_plan/build_query_plan_tests/field_merging_with_skip_and_include.rs, apollo-federation/tests/query_plan/supergraphs/fields_are_not_overwritten_when_directives_are_removed.graphql
In SelectionSet::remove_conditions_from_selection_set, a `SelectionMap` was being constructed directly from an existing selection set. Each selection had its conditions removed and inserted into the new map; however, it is possible that removing the directives from the selection would now cause a key collision. An example of this can be seen in the tests that were added:
```graphql
query Test($b: Boolean!) {
foo @include(if: $b) {
bar {
name
}
bar @include(if: $b) {
thing
}
}
}
```
When the selection set was finalized, the selection `bar { name }` was getting overwritten because, after the next selection had its `@include` directive removed, the two selections' keys collided. In the JS code, they used `SelectionSet::lazyMap`, so now the Rust code does too.
---
**Checklist**
Complete the …
=> Corrected overwritten fields in `remove_conditions_from_selection_set`

apollo-federation/src/query_graph/path_tree.rs, apollo-federation/tests/query_plan/build_query_plan_tests/introspection_typename_handling.rs, apollo-federation/tests/query_plan/supergraphs/test_indirect_branch_merging_with_typename_sibling.graphql
- When paths have equivalent (but with minor difference) trigger values, the last path's value is used in the returned tree.
- This change is to match JS QP implementation's behavior.
---
**Checklist**
[ROUTER-772]: https://apollographql.atlassian.net/browse/ROUTER-772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(federation): updated PathTree::from_path to use the last trigger value

apollo-federation/src/operation/directive_list.rs, apollo-federation/src/query_plan/conditions.rs, apollo-federation/tests/query_plan/build_query_plan_tests.rs, apollo-federation/tests/query_plan/supergraphs/condition_order_router799.graphql
Rust was iterating in a consistent order, JS iterates in declaration
order.
Surprisingly this was the only place we use the consistent order. This
removes the `iter_sorted()` method from DirectiveList that is now no
longer used. Internally, DirectiveList still uses the consistent sort
order for hashing and equality.
I think it's somewhat nicer to use the consistent order here, so you do
not get different plans based on an innocuous input difference, but so
be it. We can consider using a consistent order everywhere we handle
directives in the future.
[ROUTER-799]: https://apollographql.atlassian.net/browse/ROUTER-799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(federation): match JS condition order with multiple skip/include on the same selection

Cargo.lock, apollo-federation/Cargo.toml, apollo-federation/src/operation/mod.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/schema/position.rs
This PR refactors `SelectionSet::split_top_level_fields` away from using `Box<dyn Iterator>`s. While not a performance issue (the function is called from exactly one place), it was a very smelly implementation, which required every item to be to be allocated in its own allocation before being yielded by the iterator.
Since the iterator is recursive, I had to just implement `Iterator` on an internal type rather than use the opaque type (which can't be recursive at all) returned by the function.
Lastly, I saw a couple of other `Box<dyn Iterator>`s that that could be turned into RPITs by using the `Either` type from the `either` crate. `either` is already a transitive dependency, so it adds no extra dependencies to the `apollo-federation` or `apollo-router`.
---
**Checklist**
Complete the …
=> Refactored `SelectionSet::split_top_level_fields`

apollo-federation/src/query_graph/build_query_graph.rs, apollo-federation/tests/query_plan/build_query_plan_tests/provides.rs, apollo-federation/tests/query_plan/supergraphs/test_provides_edge_ordering.graphql
Instead of using petgraph's `edges_directed` method.
This PR matches JS QP's ordering for `provides` edges.
The change in the `copy_for_provides_internal` method was strictly necessary. The other changes in `add_provides_edges` was made for consistency.
---
**Checklist**
[ROUTER-802]: https://apollographql.atlassian.net/browse/ROUTER-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(federation): use `out_edges_with_federation_self_edges` in query builder

CHANGELOG.md
---
**Checklist**
**Exceptions**
**Notes**
=> changelog for router 2.0.0-preview.0

Cargo.lock, Cargo.toml, apollo-router/src/apollo_studio_interop/mod.rs, apollo-router/src/apollo_studio_interop/tests.rs, apollo-router/src/plugins/demand_control/mod.rs, apollo-router/src/plugins/telemetry/mod.rs, apollo-router/src/query_planner/bridge_query_planner.rs, apollo-router/src/query_planner/caching_query_planner.rs, apollo-router/src/query_planner/execution.rs, apollo-router/src/query_planner/plan.rs, apollo-router/src/services/execution/service.rs, apollo-router/src/services/layers/allow_only_http_post_mutations.rs, apollo-router/src/services/layers/query_analysis.rs, apollo-router/src/services/supergraph/service.rs, apollo-router/src/spec/query.rs, apollo-router/src/spec/query/subselections.rs, apollo-router/src/spec/query/tests.rs, apollo-router/tests/integration/operation_name.rs
The following is now done in `QueryAnalysisLayer` instead of in the `BridgeQueryPlanner` service:
* Finding the relevant operation in a GraphQL document based on `operationName`. Now `ParsedDocument` in context contains a reference to the parsed `apollo_compiler::executable::Operation`.
* Scan that operation’s root fields to find which are present: root `__typename`, schema intropsection, and "normal" non-meta fields. This is a preliminary step to moving introspection out of `BridgeQueryPlanner`.
As a side-effect observable to clients, the exact response for some error cases like an empty document changes slightly as the error no longer comes from JavaScript code.
Also optional drive-by refactor in the second commit: change `spec::Query` to contain a single `Operation` instead of a …
=> Move some GraphQL analysis earlier in the pipeline

apollo-federation/src/query_graph/graph_path.rs, apollo-federation/tests/query_plan/build_query_plan_tests/interface_object.rs, apollo-federation/tests/query_plan/supergraphs/test_interface_object_advance_with_non_collecting_and_type_preserving_transitions_ordering.graphql
This PR is a follow-up of #6127, which fixed an ordering issue.
The custom heap behaves like the JS QP's [`popMin` method](https://github.com/apollographql/federation/blob/cc4573471696ef78d04fa00c4cf8e5c50314ba9f/query-graphs-js/src/graphPath.ts#L1375).
- JS `popMin` method returns the minimum item in the heap. Also, it returns the first inserted one if there are multiple equally minimum items.
- On the other hand, Rust's BinaryHeap returns an arbitrary item in that case, which caused mismatches.
- It appears that `@interfaceObject` is necessary to create the original issue.
---
**Checklist**
[ROUTER-802]: …
=> fix(federation): updated GraphPath to use a custom MaxHeap, instead of BinaryHeap

apollo-federation/src/operation/mod.rs, apollo-federation/src/query_plan/conditions.rs, apollo-federation/src/query_plan/fetch_dependency_graph_processor.rs, apollo-federation/tests/query_plan/build_query_plan_tests.rs
PR https://github.com/apollographql/router/pull/6120 was the wrong solution. JS doesn't actually maintain the order
of the conditions, like I thought. Instead, it always puts `@skip` first
and `@include` second, the opposite of what Rust was doing.
https://github.com/apollographql/federation/blob/cc4573471696ef78d04fa00c4cf8e5c50314ba9f/query-graphs-js/src/pathContext.ts#L13-L33
The queries I was testing with just happened to pass in https://github.com/apollographql/router/pull/6120.
This changes the implementation of `Conditions::from_directives` to
pick the directives out manually instead of iterating. Technically, this
does two iterations of the directive list...but, the code is a bit
simpler, I think.
In the second commit I do a small refactor to replace the `is_negated`
boolean by a …
=> fix(federation): correct order of @skip and @include conditions on the same selection

helm/chart/router/templates/deployment.yaml
Add an Environment variable to the container that's deployed so that we can easily scan if customers are deploying using the official Helm Chart or some other way.
Ran this through the templater and it generates correctly so there's little to test beyond that.
**Checklist**
**Notes** …
=> Add Environment Variable To Helm Chart To Check Usage

apollo-federation/src/operation/contains.rs
It came up during a huddle recently why this option exists. Clarify it
for future readers.
=> chore(federation): improve doc comment on ignore_missing_typename

apollo-federation/src/operation/mod.rs, apollo-federation/tests/query_plan/build_query_plan_tests/introspection_typename_handling.rs, apollo-federation/tests/query_plan/supergraphs/it_preserves_typename_with_directives.graphql
The sibling typename optimization treated __typename and __typename @skip(if:$X) interchangeably. Thus, one could become a sibling of the other, depending on the order they appear in query. That is problematic, since sibling typename should not have directives or aliases.
The same issue found in JS QP. The matching PR for that is https://github.com/apollographql/federation/pull/3164.
Rust QP didn't have the other problem dropping some __typename selections in fetch operations like JS QP. But, still ordering could be wrong, picking __typename with directives ahead of the plain `__typename`.
- updated to only fold a plain __typename without alias/directives.
- also, fixed __typename ordering in fetch operations to put the plain __typename ahead of others.
---
**Checklist**
Complete the …
=> fix(federation): fixed sibling typename optimization handling multiple __typename selections

apollo-router/src/plugins/demand_control/cost_calculator/fixtures/basic_fragments_query.graphql, apollo-router/src/plugins/demand_control/cost_calculator/fixtures/basic_supergraph_schema.graphql, apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
Prerequisite for https://github.com/apollographql/router/pull/6013.
Fixes errors like:
```
Attempted to look up a field on type MyInterface, but the field does not exist
```
Fragment definitions have a type condition, and all selections inside
the fragment are executed against that type condition. Previously, the
demand control cost calculator executed them against the parent type
*where the fragment is used*, which is often different.
---
**Checklist**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so …
=> fix(demand_control): use correct parent type in fragment definitions

apollo-federation/src/sources/connect/validation/selection.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@rest-good.graphql.snap, apollo-federation/src/sources/connect/validation/test_data/rest-good.graphql
this fixes an incorrect unused field validation when using `rest: *`:
```
No connector resolves field `User.rest`. It must have a `@connect` directive or appear in `@connect(selection:)`.
```
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever …
=> fix: visit rest: * selections

Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/plugins/coprocessor/mod.rs, apollo-router/src/services/hickory_dns_connector.rs, apollo-router/src/services/http/service.rs, apollo-router/src/services/mod.rs
This crate was renamed.
For details, see: https://github.com/hickory-dns/hickory-dns/issues/2051
---
**Checklist**
**Exceptions**
**Notes** …
=> Change `trust-dns-resolver` to `hickory-resolver`

apollo-federation/src/sources/connect/json_selection/selection_set.rs, apollo-router/src/plugins/connectors/make_requests.rs, apollo-router/src/plugins/connectors/make_requests/graphql_utils.rs
once https://github.com/apollographql/router/pull/6013 lands, we'll need the code in connectors that converts fetch node operations to http calls to understand named fragments.
---
**Checklist**
**Exceptions**
**Notes** …
=> fix: support fragments from fetch nodes in connectors

.changesets/fix_garypen_log_less_error_for_subgraph_batching.md, apollo-router/src/services/subgraph_service.rs
If a subgraph batch succeeds, we try to notify the original waiting requester that the operation succeeded. If this notification fails, we currently log out the entire subgraph response as part of the notification error.
This may contain either or both of a lot of data or PII data which should not be logged.
---
**Checklist**
**Exceptions**
**Notes** …
=> If subgraph batching, do not log the full response when failing to notify a waiter

apollo-federation/src/compat.rs, apollo-router/src/query_planner/dual_query_planner.rs, apollo-router/src/query_planner/selection.rs
This PR fixes a bug in semantic diff and two bugs in literal value coercion.
Also, it includes an enhancement in semantic diff to handle coercion difference between JS QP and Rust QP where numeric string literals are coerced into integer literals in JS QP (while Rust QP doesn't).
These changes are separated into their own commit.
This PR unblocks https://github.com/apollographql/router/pull/6158.
- Fix: The semantic diff now compares selection arguments and aliases.
- Improvement: Allow integer literals to match string literals (if they are numeric)
- Fix: accept an enum value for custom scalar type (to match JS QP behavior)
- Fix: coerce values in fragment definitions
---
**Checklist**
- …
=> fix(dual-query-planner): fixed a few bugs in semantic diff and literal value coercion

apollo-federation/src/sources/connect/url_template.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@invalid-path-parameter.graphql.snap
"expected $this, got this" is confusing, so hopefully "expected $this, got \`this\`" helps
---
**Checklist**
**Exceptions**
**Notes** …
=> fix: add backticks around incorrect variable name

apollo-router/src/query_planner/dual_query_planner.rs
Fragment definitions and their names could be slightly reordered/switched. This PR updates semantic diff to handle those differences.
- `same_ast_document` creates a fragment mapping from the JS fragment name to matching Rust fragment name based on their definition body, not their places or names.
- Fragment spreads in selection sets are compared after mapping JS fragment names to Rust fragment names.
---
**Checklist**
=> fix(dual-query-planner): updated semantic diff to handle fragment name differences

docs/source/configuration/telemetry/exporters/logging/overview.mdx
=> docs: use equals in log specifier

docs/source/configuration/telemetry/exporters/metrics/dynatrace.mdx
This ensures that `temporality: delta` is included in the suggestions for Dynatrace.
=> Docs: Update Dynatrace Metrics documentation

apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_plan/fetch_dependency_graph.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-federation/src/query_plan/query_planning_traversal.rs, apollo-federation/src/utils/logging.rs
- `FetchDependencyGraph` snapshots are formatted in GraphViz dot format.
- Open branch snapshots are pretty printed in plain text format.
Those changes are in separate commits. It may be easier to review commit by commit.
---
**Checklist**
=> Snapshot improvements for `FetchDependencyGraph` and open branches

.github/CODEOWNERS
Removing @nicholascioli as a special case since you're part of the connectors team now!
=> Update connectors code owners

apollo-federation/src/sources/connect/expand/mod.rs, apollo-federation/src/sources/connect/expand/tests/schemas/expand/keys.graphql, apollo-federation/src/sources/connect/expand/tests/schemas/expand/keys.yaml, apollo-federation/src/sources/connect/expand/tests/schemas/regenerate.sh, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@keys.graphql-2.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@keys.graphql-3.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@keys.graphql.snap
Technically also allows some interface stuff that won't work, but it's caught in validation! Based on #6201 which should be merged first.
[CNN-485]: https://apollographql.atlassian.net/browse/CNN-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add fields referenced only in entity arguments to split subgraphs

.changesets/fix_geal_deduplication_processing_time.md, apollo-router/src/plugins/traffic_shaping/deduplication.rs
waiting for a deduplicated request was incorrectly counted as time spent in the router overhead, so even the subgraph request time was measured
---
**Checklist**
**Exceptions**
**Notes** …
=> do not count the wait time in deduplication as processing time

apollo-federation/src/query_plan/query_planner.rs
- Discourage reuse_query_fragments
- Remove performance warning on generate_query_fragments
- Remove reference to internal file in "public" doc comment
=> chore(federation): update outdated comments in QueryPlannerConfig

.changesets/docs_clarify_authorization_directive_composition.md, docs/source/configuration/authorization.mdx, docs/source/errors.mdx
Makes authorization directive composition docs clearer
=> docs: correct authorization directive composition

apollo-federation/src/sources/connect/expand/mod.rs, apollo-federation/src/sources/connect/json_selection/known_var.rs, apollo-router/src/plugins/connectors/handle_responses.rs, apollo-router/src/plugins/connectors/make_requests.rs
---
**Checklist**
**Exceptions**
**Notes**
=> $status var in responses

.changesets/fix_renee_limit_errors.md, apollo-router/src/error.rs, apollo-router/tests/integration/validation.rs
A small proposal.
It's possible to craft relatively small queries (within a few dozen KB) that produce tens of thousands of validations errors. The router then needs to spend a bunch of time formatting several megabytes of JSON in response. That's a waste of time.
By limiting the amount of errors we limit the response size and the time spent formatting the response to those queries.
I only applied it to GraphQL parsing and validation errors here. Perhaps it should be a general limit in the router. But for parsing and validation errors I think it's reasonable to silently drop further errors--I'm not sure it's appropriate for every other kind of error.
[ROUTER-822]: https://apollographql.atlassian.net/browse/ROUTER-822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
=> Limit the amount of GraphQL validation errors returned in the response

apollo-federation/src/sources/connect/expand/mod.rs, apollo-federation/src/sources/connect/expand/tests/schemas/expand/sibling_fields.graphql, apollo-federation/src/sources/connect/expand/tests/schemas/expand/sibling_fields.yaml, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@sibling_fields.graphql-2.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@sibling_fields.graphql-3.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@sibling_fields.graphql.snap
We generate a fake selection for path-like variables (e.g., `$this.a.b`) so that we can use the same visitor code as elsewhere to collect fields to carry over to intermediate subgraphs. That selection was broken for any nested fields, since `{b}` is not valid selection on its own. This corrects that problem by omitting the surrounding braces at the first level of nesting, and only putting them back when creating the `@key`.
=> Fix fake selection for nested fields in expansion

docs/source/configuration/telemetry/instrumentation/instruments.mdx
The actual default enablement or disablement of these instruments depends on the [`default_requirement_level` setting](https://www.apollographql.com/docs/graphos/reference/router/telemetry/instrumentation/instruments#default_requirement_level)
=> docs: instruments defaults depend on default_requirement_level

apollo-federation/src/operation/simplify.rs, apollo-federation/tests/query_plan/build_query_plan_tests.rs, apollo-federation/tests/query_plan/supergraphs/rebase_non_intersecting_without_dropping_inline_fragment_due_to_directive.graphql
This is an unhandled corner case where an inline fragment's selections are flattened into an empty selection set, but the fragment itself can't go away due to some reason (such as having a directive on it).
Example:
```graphql
#!subgraph
type Query {
test: X
}
interface I {
i: Int
}
type X implements I {
i: Int
}
type Y implements I {
i: Int
}
#!operation
{
test { # subselection type: X
... on I { # upcast to I
... @skip(if: true) {
... on Y { # downcast to Y (which is non-intersecting)
i
}
}
}
}
}
```
This PR is related to https://github.com/apollographql/router/pull/5370, which has a similar fix in a different part of the same method.
---
**Checklist**
=> fix(federation): fixed a rebase error during flattening the input query

apollo-federation/src/error/mod.rs, apollo-federation/src/operation/merging.rs, apollo-federation/src/query_graph/mod.rs, apollo-federation/src/query_plan/conditions.rs
After DM discussion with @TylerBloom. They brought up that
`internal_error!()` as introduced in https://github.com/apollographql/router/pull/6080 cannot be used in
`.ok_or_else()` and some other common situations in the federation
codebase.
This splits the error creation and error return apart, following the
naming convention from `anyhow`:
- `internal_error!()` creates an internal error value from a format string.
- `bail!()` returns out of the parent function with an internal error.
- `ensure!()` returns out of the parent function with an internal error if its condition fails.
`internal_error!()` doesn't look like a massive win compared to `FederationError::internal(format!())` at first glance, but it does feel a lot more lightweight to read in my opinion.
=> chore(federation): add format-only error macro

apollo-router/src/configuration/metrics.rs, apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__metrics@connectors.router.yaml.snap, apollo-router/src/configuration/testdata/metrics/connectors.router.yaml
Add metrics for usage of `preview_connectors` configuration.
---
**Checklist**
**Exceptions**
**Notes** …
=> Add metrics for preview_connectors configuration

apollo-federation/src/sources/connect/validation/selection.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@invalid_selection_syntax.graphql.snap
Currently, we highlight the entire string when `selection` can't be parsed. This limits the highlight to just the offset identified by the parser (as of #6089).
An alternative could be to highlight the entire string after the offset, which might make the error more visible in-editor.
Before:
After:
=> Provide single-character locations for `selection` parse errors

Cargo.lock, apollo-federation/Cargo.toml, apollo-federation/src/lib.rs, apollo-federation/src/link/federation_spec_definition.rs, apollo-federation/src/query_graph/build_query_graph.rs, apollo-federation/src/query_graph/condition_resolver.rs, apollo-federation/src/query_graph/mod.rs, apollo-federation/src/schema/position.rs, apollo-federation/src/utils/fallible_iterator.rs
There are still a few TODOs. The regular expression that is used will fail to build because looking around is not supported. The logic inside the `simpleTraversal` for the context has also not been ported. Lastly, the definition position types might be off and need to be tested.
=> Added logic to parse `@context` in `FederatedQueryGraphBuilder::build`

apollo-federation/tests/query_plan/supergraphs/rebase_non_intersecting_without_dropping_inline_fragment_due_to_directive.graphql, apollo-router/src/plugins/telemetry/formatters/json.rs
Due to the merge order of #6237 and #6242, this supergraph was using the wrong federation version, causing tests to fail on CI.
=> fix(federation): recompose test supergraph

docs/source/reference/router/telemetry/instrumentation/instruments.mdx
Fix table being too wide by adding spaces and making it wrappable
=> docs: fix table wrapping

apollo-federation/src/query_plan/fetch_dependency_graph.rs
In order to support `@context` during fetch dependency graph processing, this PR refactors `handle_requires()` into two functions: `handle_conditions_tree()` and `create_post_requires_node()` (the first of which gets reused by `@context` logic).
=> Refactor `handle_requires()` to support `@context` use cases

apollo-router/src/configuration/metrics.rs
Follow-up to #6013 
We'd like to know if anyone opts out of fragment generation, as we are intending to remove the experimental fragment reuse algorithm (due to being slow, and potentially buggy).
I did not add an automated test for this, I'm not sure how to approach a test for a private metric, and I did not find tests for the other configuration metrics. Perhaps I missed them?
I did manual testing by adding a `println!()` to the new code and running it with various configurations.
---
**Checklist** …
=> Report a metric to Apollo if fragment reuse is enabled

apollo-federation/src/operation/mod.rs, apollo-federation/src/query_graph/build_query_graph.rs, apollo-federation/src/query_graph/condition_resolver.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_graph/mod.rs, apollo-federation/src/query_graph/path_tree.rs, apollo-federation/src/query_plan/display.rs, apollo-federation/src/query_plan/fetch_dependency_graph.rs, apollo-federation/src/query_plan/mod.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-federation/src/query_plan/query_planning_traversal.rs, apollo-router/src/query_planner/convert.rs
This PR:
1. Updates `compute_nodes_for_op_path_element()` to handle `@context`/`@fromContext` on fields, using the refactored `handleRequires()` functions created during #6263.
2. Updates `to_plan_node()` to add context variables and usages to the query plan fetch nodes.
3. Fixes a `todo()` in `resolve_condition_plan()` where the `context_map` should be `None`.
4. Changes various typings introduced during the `@context`/`@fromContext` work to be more specific, usually replacing `String` with `Name` or `FetchDataPathElement`.
5. Introduces `FetchDataPathElement::Parent` for specifically representing the "goto parent" element in fetch paths (`".."` is not a valid GraphQL name, and we shouldn't be using it in `FetchDataPathElement::Key`).
- I did not change this behavior in router's query …
=> Handle @fromContext/@context during fetch dependency graph processing and miscellaneous bugfixes

examples/coprocessor-surrogate-cache-key/nodejs/src/index.js
Applies to https://github.com/apollographql/router/pull/6234
=> Use a `Map` rather than object for coprocessor surrogate cache key example

apollo-router/src/plugins/authorization/tests.rs, apollo-router/src/query_planner/dual_query_planner.rs
We are getting mismatches when comparing PlanNodes between JS & Rust with ~authorisation~ authorization directives. This mismatch comes from `authorization` field in PlanNode. The executing query plan (and in comparison mode, it will be the JS QP) receives the appropriate `CacheKeyMetadata`,
```rust
CacheKeyMetadata { 
is_authenticated: true,
scopes: [],
policies: []
}
```
but the Rust QP does not, since it will not be used to execute, authenticate, etc any of the requests and gets discarded in this comparison mode. 
Because we do not attach this metadata to the Rust PlanNode **in comparison mode**, we see a ton of false mismatches for everyone using auth directives. 
This PR skips comparing `authorization` field in PlanNode, as this field gets populated _after_ the query plan is already …
=> QP comparison mode: skip comparing PlanNode.authorization

apollo-federation/src/schema/position.rs, apollo-federation/src/supergraph/mod.rs
This is my proposed "solution" for handling the shadowing of builtin types and directives in federated schemas.
That is, what happens if a subgraph (*or supergraph*) SDL contains a scalar declaration like:
```graphql
scalar Boolean
```
where the type name collides with a name provided by the GraphQL spec.
The PR contains some cleanup commits. The first two commits are cleanup, the rest is implementing the below.
graphql-js completely ignores SDL definitions of built-in scalars, instead only using the built-in ones:
https://github.com/graphql/graphql-js/blob/c079ae3cf8bf5bc0f255bde1ce2fbd424436cffb/src/utilities/extendSchema.ts#L185-L188 
For directives, graphql-js uses the built-in definitions if no custom definition was provided: …
=> fix(federation): remove special-casing of adding reserved or built-in items to a schema

apollo-federation/src/query_plan/query_planner.rs, apollo-router/src/query_planner/caching_query_planner.rs
QueryPlannerConfig is currently missing Serialize implementation that will be eventually needed for the query planner cache once we use only one planner in the Router.
=> add `Serialize` to apollo_federation::QueryPlannerConfig

apollo-federation/src/query_graph/condition_resolver.rs, apollo-federation/src/query_plan/query_planning_traversal.rs
Added `extra_conditions` argument to to `ConditionResolverCache` which was causing error in a snapshot test.
=> Context test correction: `set_context_test_efficiently_merge_fetch_groups`

apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/supergraph/mod.rs, apollo-federation/src/supergraph/schema.rs, apollo-federation/tests/query_plan/build_query_plan_tests/context.rs
Refactoring to avoid copypasta as much as possible, though there's still room to improve. Also some changes in can_satisfy_conditions to accomodate union.
=> extract context onto interface and union

apollo-federation/src/lib.rs, apollo-federation/src/link/argument.rs, apollo-federation/src/link/context_spec_definition.rs, apollo-federation/src/link/federation_spec_definition.rs, apollo-federation/src/link/join_spec_definition.rs, apollo-federation/src/merge.rs, apollo-federation/src/operation/rebase.rs, apollo-federation/src/query_graph/build_query_graph.rs, apollo-federation/src/query_graph/condition_resolver.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_graph/mod.rs, apollo-federation/src/query_graph/path_tree.rs, apollo-federation/src/query_plan/fetch_dependency_graph.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-federation/src/supergraph/mod.rs, apollo-federation/tests/query_plan/build_query_plan_tests/context.rs
This PR removes the allow directive for dead code, unused items, and clippy's lints and moves it back to be in a warning.
=> Context code clean up

apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/subgraph/spec.rs, apollo-router/tests/set_context.rs
This PR fixes a Rust-only bug in `GraphPath::add()` where it didn't properly push to `context_to_selection` and `parameter_to_context` in the case of a `None` edge, causing the `GraphPath` iterator to prematurely end due to `zip` semantics.
=> Fix bug with `@context` state tracking in `GraphPath::add()`

.circleci/config.yml
Presently, knowing about this condition as soon as possible is valuable in
ensuring that we are quickly aware and able to reconcile changes to
dependencies which may be difficult for library-consumers of the Router.
Today, we get that through a feedback loop on individual PRs and release
workflows, however those can be inconveniently timed and blocking.
By moving this to a scheduled workflow in CircleCI, we can run it at a
cadence that suits us and get notifications via Slack immediately.
This should conceivably supersede https://github.com/apollographql/router/pull/5935
[ROUTER-868]: https://apollographql.atlassian.net/browse/ROUTER-868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: Remove "test_updated" from release workflows

.github/CODEOWNERS
Individuals should now all be covered by teams
=> Remove a couple redundant codeowner rules

docs/source/routing/about-router.mdx, docs/source/routing/observability/error-reporting.mdx, docs/source/routing/observability/federated-trace-data.mdx, docs/source/routing/observability/otel.mdx, docs/source/routing/uplink.mdx
This PR moves some pages that are currently in the federation repo but appear in the Routing section of our docs.
This is a continuation (completion?) of the effort started here: https://github.com/apollographql/router/pull/6157
=> docs: move pages from federation

apollo-router/src/configuration/cors.rs, docs/source/reference/migration/from-router-v1.mdx
Various invalid CORS configuration values were ignored, with an error logged. For example, providing an invalid regex to `match_origins`, or an unknown method to `allow_methods`. These are now hard errors and you can't start the router if you have invalid configuration.
---
**Checklist**
**Exceptions**
**Notes** …
=> fix(cors): don't ignore invalid configuration

apollo-federation/src/query_plan/conditions.rs, apollo-federation/src/query_plan/fetch_dependency_graph.rs
The `Conditions` structure represents the combined skip/include conditions of a GraphQL query path (and of a FetchDependencyGraphNode).
The storage of variable conditions looks inefficient. I tried some quick refactors to make it more efficient, which didn't hugely affect overall planning performance, even on plans that spend a lot of time computing conditions. Perhaps the representation isn't the biggest issue. I think we can still simplify it, though. I might tinker with that if I find some spare cycles in December.
This PR does not change the representation. I only added tests and documentation.
I also flipped the order of the `update_with()` argument. The order of the arguments disagreed with the name of the method. We were not updating the argument at all: we were updating `self`, …
=> chore(federation): add unit tests and documentation for conditions handling

.changesets/fix_bnjjj_fix_880.md, apollo-router/src/plugins/telemetry/config_new/instruments.rs, apollo-router/src/plugins/telemetry/config_new/selectors.rs, apollo-router/tests/integration/telemetry/fixtures/graphql.router.yaml, apollo-router/tests/integration/telemetry/metrics.rs
Query selector was raising error logs like `this is a bug and should not happen`. It's now fixed.
Now this configuration will work properly:
```yaml title=router.yaml
telemetry:
exporters:
metrics:
common:
views:
- name: oplimits.*
aggregation:
histogram:
buckets:
- 0
- 5
- 10
- 25
- 50
- 100
- 500
- 1000
instruments:
supergraph:
oplimits.aliases:
value:
query: aliases
type: histogram
unit: number
description: "Aliases for an operation"
oplimits.depth:
value:
query: depth
type: histogram
unit: number
description: "Depth for an operation"
oplimits.height:
value:
query: height
type: histogram
unit: number
description: "Height for an operation"
oplimits.root_fields:
value:
query: root_fields
type: histogram
unit: number
description: "Root fields for an operation"
```
--- …
=> fix(telemetry): fix supergraph query selector

docs/source/reference/migration/from-gateway.mdx, docs/source/routing/about-router.mdx, docs/source/routing/customization/coprocessor.mdx, docs/source/routing/customization/rhai.mdx, docs/source/routing/observability/client-id-enforcement.mdx, docs/source/routing/observability/federated-trace-data.mdx, docs/source/routing/operations/subscriptions/multipart-protocol.mdx, docs/source/routing/security/authorization.mdx, docs/source/routing/security/jwt.mdx, docs/source/routing/security/router-authentication.mdx, docs/source/routing/self-hosted/containerization/index.mdx
This PR adds links to relevant repositories in the `apollosolutions` organization.
https://github.com/apollographql/docs-rewrite/pull/343 must merge first since it adds a shared component used in this PR.
=> docs: add links to solutions repositories

apollo-federation/src/query_plan/fetch_dependency_graph.rs
While I was working on #6325, I figured I might as well tackle this related issue quickly.
Certain graph and query shapes cause the `FetchSelectionSet::conditions` to be recomputed very, very frequently. Now, they are only recomputed when required.
On most plans there is no noteworthy difference, but on plans with many large fetch nodes and many possible plans, the difference can be high-single-digit % in *total planning time*, which is very worthwhile.
When `OnceLock::get_or_try_init` is stabilised, this will be easier :)
---
**Checklist**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do …
=> fix(federation): avoid constantly recomputing conditions

Cargo.lock, apollo-federation/Cargo.toml, apollo-federation/src/display_helpers.rs, apollo-federation/src/operation/directive_list.rs, apollo-federation/src/operation/mod.rs, apollo-federation/src/operation/selection_map.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_plan/mod.rs, apollo-federation/src/utils/mod.rs, apollo-federation/src/utils/serde_bridge.rs
This PR changes how several types are serialized in `apollo-federation`. Namely, there are several types from `apollo-compiler` that do not implement `serde::Serialize`. Before, these types were serialized as strings or simply skipped. This has been changes to use the provided `serialize` method on those `apollo-compiler` types. Additionally, this changes the inner type of `SelectionId` and `OverrideId` from a `usize` to a `Uuid`. This adds `uuid` as a dependency to `apollo-federation`, but `uuid` was already a (transitive) dependency of `apollo-router`.
---
**Checklist**
**Exceptions**
**Notes** …
=> chore(federation): Improved serialization impls

.circleci/config.yml
In the same spirit as the `next` branch did in 21a05d752cc140a685a971f63158 and in the spirit of eliminating the occasionally recurring but decidedly problematic `libunwind` error, which is actively blocking the v1.58.0 release, but has previously caused corrutped builds in CI.
Previously, while we had updated the "next" branch (for v2.x of the Router), we had delayed this work on the v1 line (dev branch) eliminate because we hadn't time to validate that it wouldn't potentially drop support for macOS 12 users.
However, given some more time to validate, we confirmed that release binaries produced with these newer versions of macOS and Xcode are still able to execute on older macOS versions, therefore making the change not only acceptable, but desireable since we will want to have the most …
=> ci: Upgrade build/test environments to macOS v14.3.1 and Xcode v15.4.0

.circleci/config.yml
Alternative title: "Fix the f* chocolatey cant work!!!" (lovingly)
We get weird spurious failures from chocolatey installing CMake, on some branches and not others. If we just grab cmake.exe from the CMake release on GitHub, and put it in `~/.local/bin`, what can go wrong? Let's find out!
=> ci: install cmake straight from github on windows

apollo-router/src/query_planner/dual_query_planner.rs
This PR improves the semantic diff by sorting directives applied on selections before comparison.
---
**Checklist**
=> fix(dual-query-planner): sort directives before comparison in semantic diff

apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert-5.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_data-3.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_data.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-3.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-5.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private.snap, apollo-router/tests/snapshots/set_context__set_context_dependent_fetch_failure_rust_qp.snap, apollo-router/tests/snapshots/set_context__set_context_list_of_lists_rust_qp.snap, apollo-router/tests/snapshots/set_context__set_context_list_rust_qp.snap, apollo-router/tests/snapshots/set_context__set_context_no_typenames_rust_qp.snap, apollo-router/tests/snapshots/set_context__set_context_rust_qp.snap, apollo-router/tests/snapshots/set_context__set_context_type_mismatch_rust_qp.snap, apollo-router/tests/snapshots/set_context__set_context_union_rust_qp.snap, apollo-router/tests/snapshots/set_context__set_context_unrelated_fetch_failure_rust_qp.snap, apollo-router/tests/snapshots/set_context__set_context_with_null_rust_qp.snap, apollo-router/tests/snapshots/type_conditions___test_type_conditions_disabled-2.snap, apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled-2.snap, apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled_generate_query_fragments-2.snap, apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled_list_of_list-2.snap, apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled_list_of_list_of_list-2.snap, apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled_shouldnt_make_article_fetch-2.snap
`dev` wasn't merged in #6205 before being squashed and committed. 
Because of that, `dev` had some changes in tests that didn't change the hash produced by the old query hash algorithm but resulted in a hash change once #6205 was merged.
Example: #6310 Added test changes related to @context and #6205 added a special case to handle @context directives
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and …
=> Fix snapshots after #6205 was merged

Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/plugins/fleet_detector.rs
Adds an additional metric on the `fleet_detector` plugin to track the instance and its environment (OS, distribution, compute platform, etc.) in a non-intrusive way.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. …
=> plugins/fleet_detector: add instance gauge

Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/plugins/telemetry/tracing/datadog_exporter/exporter/mod.rs
This PR adds a dependency of:
```http-0_2 = { version = "0.2.12", package = "http" }```
to allow the vendored dd exporter code to continue to use hyper 0.2 pending the otel upgrade.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes …
=> hyper upgrade - dd exporter

.changesets/fix_renee_max_evaluated_plans_rs.md, .circleci/config.yml, apollo-router/src/configuration/mod.rs, apollo-router/src/query_planner/bridge_query_planner.rs, apollo-router/tests/integration/fixtures/query_planner_max_evaluated_plans.graphql, apollo-router/tests/integration/query_planner.rs, apollo-router/tests/integration/query_planner/max_evaluated_plans.rs
The experimental `max_evaluated_plans` and `paths_limit` options were only propagated to the legacy JS planner, not the native query planner.
Now they work with both planners.
Adds integration tests for the `apollo.router.query_planning.plan.evaluated_plans` metric, with and without `max_evaluated_plans` set, with the legacy and the native query planners.
---
**Checklist**
**Exceptions**
**Notes** …
=> fix: propagate evaluated plans limit and paths limit to the native query planner

apollo-router/src/cache/redis.rs, apollo-router/src/configuration/mod.rs, apollo-router/src/plugins/coprocessor/mod.rs, apollo-router/src/router_factory.rs, apollo-router/src/services/http/service.rs, apollo-router/src/services/http/tests.rs, apollo-router/src/services/subgraph_service.rs
This contains 3 commits updating our usage of rustls to the new APIs. Please see the commit descriptions for details on all of the changes.
The trait solver started to kick in for a much larger amount of code, so this PR increases the compiler errors on the hyper upgrade branch to about 90. I've solved all the TLS-related errors I could find in the increased set of errors and left the rest alone.
[ROUTER-898]: https://apollographql.atlassian.net/browse/ROUTER-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update `rustls` usages

apollo-router/src/plugins/connectors/testdata/README.md, apollo-router/src/plugins/connectors/testdata/connector-without-source.graphql, apollo-router/src/plugins/connectors/testdata/connector-without-source.yaml, apollo-router/src/plugins/connectors/testdata/form-encoding.yaml, apollo-router/src/plugins/connectors/testdata/interface-object.yaml, apollo-router/src/plugins/connectors/testdata/mutation.graphql, apollo-router/src/plugins/connectors/testdata/mutation.yaml, apollo-router/src/plugins/connectors/testdata/nullability.yaml, apollo-router/src/plugins/connectors/testdata/quickstart.graphql, apollo-router/src/plugins/connectors/testdata/quickstart.yaml, apollo-router/src/plugins/connectors/testdata/regenerate.sh, apollo-router/src/plugins/connectors/testdata/selection.graphql, apollo-router/src/plugins/connectors/testdata/selection.yaml, apollo-router/src/plugins/connectors/testdata/steelthread.graphql, apollo-router/src/plugins/connectors/testdata/steelthread.yaml, apollo-router/src/plugins/connectors/testdata/variables.yaml
Same treatment I gave the expansion test cases. Removes references to old versions of composition and brings all the supergraph SDLs up to date. Also fixed one inconsistency between a YAML and its .graphql.
=> Regenerate the runtime test cases for connectors and provide some instructions.

apollo-federation/src/sources/connect/validation/extended_type.rs, apollo-federation/src/sources/connect/validation/mod.rs, apollo-federation/src/sources/connect/validation/selection.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@all_fields_selected.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@disallowed_abstract_types.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@disallowed_federation_imports.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@fields_with_arguments.graphql.snap
Should give us less busy work in `federation-rs` when testing/releasing. Preserves naming of previous codes.
=> Move `Code::to_string` to `apollo-federation` from `apollo-composition`.

apollo-federation/src/lib.rs, apollo-federation/src/link/argument.rs, apollo-federation/src/link/context_spec_definition.rs, apollo-federation/src/link/federation_spec_definition.rs, apollo-federation/src/link/join_spec_definition.rs, apollo-federation/src/operation/rebase.rs, apollo-federation/src/query_graph/build_query_graph.rs, apollo-federation/src/query_graph/condition_resolver.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_graph/mod.rs, apollo-federation/src/query_graph/path_tree.rs, apollo-federation/src/query_plan/fetch_dependency_graph.rs, apollo-federation/src/schema/field_set.rs, apollo-federation/src/schema/position.rs, apollo-federation/src/subgraph/mod.rs, apollo-federation/src/subgraph/spec.rs, apollo-federation/src/supergraph/mod.rs, apollo-federation/src/supergraph/schema.rs, apollo-federation/src/supergraph/subgraph.rs, apollo-federation/src/utils/mod.rs, apollo-federation/tests/query_plan/build_query_plan_tests/context.rs, apollo-federation/tests/snapshots/main__extract_subgraphs__can_extract_subgraph.snap, apollo-federation/tests/snapshots/main__extract_subgraphs__does_not_extract_demand_control_directive_name_conflicts.snap, apollo-federation/tests/snapshots/main__extract_subgraphs__does_not_extract_renamed_demand_control_directive_name_conflicts.snap, apollo-federation/tests/snapshots/main__extract_subgraphs__extracts_demand_control_directives.snap, apollo-federation/tests/snapshots/main__extract_subgraphs__extracts_renamed_demand_control_directives.snap, apollo-federation/tests/snapshots/main__extract_subgraphs__extracts_set_context_directives.snap, apollo-router/tests/snapshots/set_context__set_context_union_rust_qp.snap
In summary, this PR makes changes to the Rust QP port of `@context`/`@fromContext` for the sake of:
- Bugfixes.
- Renames/Refactors to simplify and reduce confusion.
- Adherence to existing conventions.
- This isn't necessarily an endorsement of those conventions, but primarily for consistency sake.
There's a lot of these, so I'm going to leave comments on the code with relevant information (mainly bugfix notes, but with some occasional notes about refactors).
=> Miscellaneous @context/@fromContext bugfixes

apollo-router/src/plugins/traffic_shaping/retry.rs
A change to the experimental_retry has been introduced accidentally in this [PR](https://github.com/apollographql/router/pull/6351). This PR reverts that change because it needs further discussion.
=> remove fix for experimental_retry

apollo-federation/src/sources/connect/json_selection/parser.rs, apollo-federation/src/sources/connect/validation/graphql/strings.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@invalid_connect_http_headers.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@invalid_selection_syntax.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@invalid_source_http_headers.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@valid_selection_with_escapes.graphql.snap, apollo-federation/src/sources/connect/validation/test_data/valid_selection_with_escapes.graphql
As defined in the [GraphQL spec](https://spec.graphql.org/October2021/#sec-String-Value), standard strings may contain escape sequences, and block strings have their whitespace modified to remove any common indent or leading whitespace lines.
The Apollo Connectors feature parses various GraphQL strings in the `@connect` and `@source` directives, and provides messages with location information when there are problems within the content of those strings. To prevent each parser from having to handle escape sequences, the parsers should execute on the strings returned by `apollo-compiler`, which processes the escape sequences and block string whitespace. This requires mapping the locations returned by the parsers back to the corresponding locations in the original file by reversing the rules …
=> Handle escape sequences in GraphQL strings

Cargo.lock, apollo-federation/Cargo.toml
We are getting errors with an outdated version of hashbrown that needs to updated due to a bug in borsch serialisation 🍲 . This updates us to a version of hashbrown that fixes this vulnerability.
```
error[vulnerability]: Borsh serialization of HashMap is non-canonical
┌─ /Users/ira/Code/apollographql/router/Cargo.lock:261:1
│
261 │ hashbrown 0.15.0 registry+https://github.com/rust-lang/crates.io-index
│ ---------------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2024-0402
= Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0402
= The borsh serialization of the HashMap did not follow the borsh specification.
It potentially produced non-canonical encodings dependent on insertion order.
It also did not perform canonicty checks …
```
=> update hashbrown dep for compliance

apollo-router/tests/integration/redis.rs
Since router's configuration has changed, the redis cache keys have to be updated.
=> update redis integration tests after removal of experimental_reuse_query_fragments

Cargo.lock, apollo-federation/src/sources/connect/header.rs, apollo-federation/src/sources/connect/url_template.rs, apollo-federation/src/sources/connect/variable/mod.rs
Extra text after a variable reference will now properly report an invalid variable reference in headers and URL paths.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document …
=> Fix bug where URL variable parsing was not all-consuming

.changesets/fix_bnjjj_fix_880.md, .changesets/fix_renee_max_evaluated_plans_rs.md, CHANGELOG.md, Cargo.lock, apollo-federation/Cargo.toml, apollo-router-benchmarks/Cargo.toml, apollo-router-scaffold/Cargo.toml, apollo-router-scaffold/templates/base/Cargo.template.toml, apollo-router-scaffold/templates/base/xtask/Cargo.template.toml, apollo-router/Cargo.toml, dockerfiles/tracing/docker-compose.datadog.yml, dockerfiles/tracing/docker-compose.jaeger.yml, dockerfiles/tracing/docker-compose.zipkin.yml, helm/chart/router/Chart.yaml, helm/chart/router/README.md, scripts/install.sh
> **Note**
>
> When approved, this PR will merge into **the `1.58.1` branch** which will — upon being approved itself — merge into `main`.
>
>  - That it targets the right release branch (`1.58.1` in this case!).
>
---
Telemetry customizations like those featured in the [request limits telemetry documentation](https://www.apollographql.com/docs/graphos/routing/security/request-limits#collecting-metrics) now work as intended when using the `query` selector on the `supergraph`.  In some cases, this was causing a `this is a bug and should not happen` error, but is now resolved.
By …
=> prep release: v1.58.1

.changesets/fix_address_dentist_buyer_frown.md, apollo-router/src/services/supergraph/service.rs, apollo-router/tests/integration/coprocessor.rs, apollo-router/tests/integration/fixtures/coprocessor.router.yaml
If a coprocessor responds with an empty body at the supergraph stage then the router would panic as there was a false expectation that the query had already been validated.
There is a deeper issue around coprocessors and their ability to modify the query before processing. As query analysis and plugins may use the query to populate context modifying the query won't necessarily do what the user wants. In fact the router will simply ignore the modified query as the parsed version is already in context. But that will be tackled in future pipeline rework.
---
**Checklist**
**Exceptions**
* No unit tests as it is the interaction across the entire pipeline that …
=> Fix coprocessor empty body panic

apollo-federation/cli/src/main.rs, apollo-federation/src/query_plan/mod.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-router/tests/integration/redis.rs
Cleanup query planner code by removing unused bypass QP functionality. This was a gateway only feature that was never supported on the router.
---
**Checklist**
**Exceptions**
**Notes** …
=> Cleanup unused bypass QP functionality

.changesets/config_simon_router_version_in_cache_key.md, apollo-router/build/main.rs, apollo-router/src/query_planner/bridge_query_planner.rs, apollo-router/src/query_planner/caching_query_planner.rs, apollo-router/tests/integration/redis.rs
If you have enabled [Distributed query plan caching](https://www.apollographql.com/docs/router/configuration/distributed-caching/#distributed-query-plan-caching), starting with this release and going forward you should anticipate additional cache regeneration cost when updating between any Router versions.
More often than not, an Apollo Router release may contain changes that affect what query plans are generated or how they’re represented. To avoid using outdated entries from distributed cache, the cache key includes a counter that was manually incremented with relevant data structure or algorithm changes. Instead the cache key now includes the Router version number, so that different versions will always use separate cache entries.
---
**Checklist**
Complete the checklist (and note …
=> Distributed query plan cache keys include the Router version number

apollo-router/src/plugins/fleet_detector.rs
This adds a new attribute to the `apollo.router.instance` metric to track if the Router instance was deployed using the official Apollo helm chart vended in this repository.
---
**Checklist**
**Exceptions**
**Notes** …
=> plugins/fleet_detector: detect if the Router was deployed using the official Apollo Helm chart

apollo-federation/src/error/mod.rs, apollo-federation/src/operation/merging.rs, apollo-router/src/query_planner/bridge_query_planner.rs
This PR updates the error messaging when query planner encounters unmergeable fields (indicating a known bug in query planner), and increments an internal metric when this error kind is encountered. Note that query planner does not check all such cases of this, as doing so is computationally expensive. The bug itself is not fixed in this PR, as it requires substantial effort to fix.
=> Improve error messaging when QP encounters unmergeable fields

Cargo.lock, apollo-federation/Cargo.toml, apollo-router-benchmarks/Cargo.toml, apollo-router/Cargo.toml, dockerfiles/tracing/docker-compose.datadog.yml, dockerfiles/tracing/docker-compose.jaeger.yml, dockerfiles/tracing/docker-compose.zipkin.yml, helm/chart/router/Chart.yaml, helm/chart/router/README.md, licenses.html, scripts/install.sh
Prep for Connectors release 2.0.0-preview.3.
In order to update the license file, this requires upgrading to `cargo-about` version 0.6.6 locally to pick up [this fix](https://github.com/EmbarkStudios/cargo-about/releases/tag/0.6.6). However, that version of `cargo-about` cannot be installed with Rust 1.76, which the router has pinned, so the circleci `config.yml` has not been updated to this version.
---
**Checklist**
**Exceptions**
**Notes** …
=> prep release: v2.0.0-preview.3

.circleci/config.yml, about.toml, licenses.html
cargo about and cargo deny have separate configuration files: about.toml and deny.toml.
deny.toml was updated to allow Unicode-3.0 license in #6417 , but about.toml was not updated. This is causing `cargo xtask licenses` to fail.
This PR fixes about.toml.
=> fix cargo about

apollo-federation/src/error/mod.rs
In v1.58.0, the `internal_error!` macro was updated to no longer return its error for release builds, but the `ensure!` macro (which calls `internal_error!`) wasn't updated accordingly. This means that `ensure!` callsites in the current code are silently ignoring their errors if their check fails in release builds. This PR updates `ensure!` to use the `bail!` macro, which does return its error.
=> Update `ensure!` macro to return its error

apollo-federation/cli/src/main.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-federation/src/query_plan/query_planning_traversal.rs, apollo-federation/tests/query_plan/build_query_plan_tests/interface_object.rs, apollo-federation/tests/query_plan/supergraphs/test_type_conditioned_fetching_with_interface_object_does_not_crash.graphql
Fetch dependency graph expects supergraph types.
So, Interface object types from subgraphs need to be converted to interface type positions.
Also, added `--type-conditioned-fetching` option to the CLI tool.
---
**Checklist**
=> fix(federation): convert query graph node's type for fetch dependency graph path

apollo-router/src/json_ext.rs, apollo-router/src/query_planner/plan_compare.rs
Two issues:
1. JS QP may have empty key roots in response path data, which is ignored by the router. On the other hand, Rust QP does not use such a placeholder. So, the semantic diff ignores the placeholder during comparison.
2. JS QP may have empty condition list, but it was deserialized incorrectly (for example, `k|[]` would be interpreted as a whole key name). This is now fixed in the router's deserializer.
---
**Checklist**
=> fix(semantic-diff): fixed false mismatches with type conditioned fetching enabled

apollo-federation/src/sources/connect/json_selection/selection_set.rs, apollo-router/src/plugins/connectors/handle_responses.rs, apollo-router/src/plugins/connectors/make_requests.rs, apollo-router/src/plugins/connectors/tests/mod.rs
three scenarios:
1. connector on a root field: the entire object is handled by json_selection, which does __typename injection. if the return type is abstract, json_selection logic will handle it.
2. explicit entity connector: the entire object is handled by json_selection, which does __typename injection. if the entity type is abstract, the planner decides if it needs __typename (it won't if it's an interfaceObject), and json_selection logic will handle it.
3. field on an entity: the __typename for the entity type is handled outside of json_selection. but there's only two scenarios: it's an object type so we know the __typename and can inject it, or its an interface object and we shouldn't supply the __typename.
---
**Checklist**
Complete the checklist (and note appropriate exceptions) …
=> refactor: simplify __typename handling in connectors code

apollo-router/src/plugins/connectors/handle_responses.rs, apollo-router/src/services/connector_service.rs
The Connectors service runs all the REST API requests for an operation as parallel async tasks. However, it was waiting for *all* of them to return a response before processing the results from *any* request.
These changes move the result processing into the same async block as the request, allowing each result to be processed as soon as it is available. These changes don't reduce the total amount of work to be done, but rather change when the work is done to reduce the total latency in some cases. For example, if one task is blocked due to long REST API request latency, we can spend that time processing the results of any requests that have already completed.
The only work that needs to happen after all of the requests complete is the aggregation of the results. The work is now split …
=> Move result handling to initial async block

apollo-federation/src/error/mod.rs, apollo-federation/src/query_graph/build_query_graph.rs
Internal errors should only be used for situations that never happen. Technically a context parse error should not happen if the supergraph is valid, so it could be argued to be a correct usage of an internal error.
The test suite contains checks for context parse errors though. `bail!()` should be treated as a panic, and the tests are not treating it as a panic, so I think the best way for now is to introduce a new error branch for `@fromContext` parse errors.
I would like to make `bail!()` panic in debug mode soon, just like `ensure!()` does, so we can get stack traces for those situations that should never happen.
=> fix(federation): do not use internal errors for context parse errors

apollo-federation/src/sources/connect/json_selection/apply_to.rs, apollo-federation/src/sources/connect/json_selection/methods.rs, apollo-federation/src/sources/connect/json_selection/methods/future.rs, apollo-federation/src/sources/connect/json_selection/methods/public.rs
Previously, `->` methods (#5762) were implemented as functions and registered in a `lazy_static!` map for dynamic lookup at runtime.
This PR refactors the system for registering methods, so there is now an `ArrowMethod` enum with a variant for each known method, and each method is now represented by a struct type that has an `::apply` method, whose signature resembles the previous function implementations.
In the future, we can add other methods to these structs, so `->` methods can programmatically define their interactions with the output shape of the JSONSelection, for example.
=> Make `->` method registration more flexible and type-safe

.circleci/config.yml
Updated the configuration of the `semgrep` CI scan job to exclude a rule that is working to detect usage of insecure websockets. In general this is a good test, but Router runs a series of tests (like [here](https://github.com/apollographql/router/blob/31e73671f542ff987c1351c1748c91c4817349d1/apollo-router/src/protocols/websocket.rs#L958)) using `ws://` instead of `wss://` which is causing CI checks to fail unnecessarily. 
---
**Checklist**
**Exceptions**
N/A
**Notes** …
=> disable insecure ws semgrep signature

Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/lib.rs, apollo-router/src/plugins/connectors/testdata/quickstart_api_snapshots/query_1.json, apollo-router/src/plugins/connectors/testdata/quickstart_api_snapshots/query_2.json, apollo-router/src/plugins/connectors/testdata/quickstart_api_snapshots/query_3.json, apollo-router/src/plugins/connectors/testdata/quickstart_api_snapshots/query_4.json, apollo-router/src/plugins/connectors/tests/mod.rs, apollo-router/src/test_harness.rs, apollo-router/src/test_harness/http_snapshot.rs, apollo-router/src/test_harness/http_snapshot_main.rs, apollo-router/tests/samples/enterprise/connectors/http_snapshots.json, apollo-router/tests/samples/enterprise/connectors/plan.json, apollo-router/tests/samples_tests.rs
This re-implements the HTTP snapshot server from #6032, but on top of `hyper` 1.x.
The snapshot server is behind the `snapshot` feature flag.
To run the snapshot server standalone:
```sh
cargo run --bin snapshot --features snapshot -- --snapshot-path /tmp/snapshots.json --url https://jsonPlaceholder.typicode.com/ --port 5280 --offline -v
```
To install the snapshot server:
```sh
cargo install --locked --path apollo-router --features snapshot
```
To run the samples tests using the snapshot server:
```sh
cargo test --test samples --features snapshot
```
---
**Checklist**
**Exceptions**
**Notes** …
=> Reimplement HTTP snapshot server on hyper 1.x

apollo-router/src/plugins/fleet_detector.rs, apollo-router/src/plugins/mod.rs
Fixes the `fleet_detector` plugin after hyper 1.0 update
---
**Checklist**
**Exceptions**
**Notes**
=> fix(fleet_detector): fix fleet_detector for hyper 1.0

docs/source/routing/query-planning/native-query-planner.mdx
Fix 1.59.0 reconciliation of native query planner page
=> doc: reconcile native query planner page

apollo-router/src/plugins/connectors/http_json_transport.rs
Flame graphs from performance tests show `flatten_keys` as a minor hotspot in the connectors code. These changes improve performance by about 25% (the added test drops from 8170ms to 6210ms) while preserving the depth-first output ordering.
---
**Checklist**
**Exceptions**
**Notes** …
=> Improve performance of flatten_keys

DEVELOPMENT.md
This change just adds a command to run the release-dhat profile, because sometimes I need to be lazy and just copy/paste these things.
=> (smol) clarification on running `release-dhat` profile in DEVELOPMENT.md

apollo-federation/src/sources/connect/mod.rs, apollo-router/src/plugins/connectors/error.rs, apollo-router/src/plugins/connectors/tests/mod.rs, apollo-router/src/services/connector_service.rs
now a single connection error won't halt the processing of all requests for a fetch node
---
**Checklist**
**Exceptions**
**Notes** …
=> wrap http client errors in an error type we control

apollo-federation/src/sources/connect/validation/mod.rs
This commit modifies the result of connector-related validation to add some metadata around connector-enabled subgraphs and to keep the parsed schema so that downstream consumers can leverage the schema if needed when performing additional validation.
A follow-up PR to those downstream consumers to use this new format is pending.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: …
=> connectors: keep schema in validation

docs/source/routing/security/jwt.mdx
Updates metrics to use with the JWT auth plugin
=> docs: update jwt authentication metric

Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/ageing_priority_queue.rs
This new functionality in crossbeam allows us to remove a loop that is redundant with a similar loop inside the library.
=> Priority queue: use crossbeam-channel "biased select"

apollo-router/src/axum_factory/axum_http_server_factory.rs, apollo-router/src/axum_factory/listeners.rs
Somehow missed this in #6476
No changeset because it's in #6476 : )
[ROUTER-911]: https://apollographql.atlassian.net/browse/ROUTER-911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Migrate `apollo_router_session_count_total` metric to an OTel gauge

apollo-federation/cli/src/main.rs, apollo-federation/src/merge/snapshots/apollo_federation__merge__tests__basic.snap, apollo-federation/src/sources/connect/expand/merge/basic_1.graphql, apollo-federation/src/sources/connect/expand/merge/basic_2.graphql, apollo-federation/src/sources/connect/expand/mod.rs, apollo-federation/src/sources/connect/expand/tests/mod.rs, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@realistic.graphql-3.snap, apollo-router/src/plugins/connectors/testdata/mutation.yaml, apollo-router/src/plugins/connectors/tests/mod.rs, apollo-router/src/spec/schema.rs, apollo-router/tests/samples/enterprise/connectors-defer/README.md, apollo-router/tests/samples/enterprise/connectors-defer/configuration.yaml, apollo-router/tests/samples/enterprise/connectors-defer/http_snapshots.json, apollo-router/tests/samples/enterprise/connectors-defer/plan.json, apollo-router/tests/samples/enterprise/connectors-defer/supergraph.graphql, apollo-router/tests/samples/enterprise/connectors-defer/supergraph.yaml
this fixes a query planning panic when using `@defer` within a mutation.
the root issue is that we never added `schema { mutation: Mutation }` when necessary. you'd think that would be a bigger problem, but apparently the query planner doesn't mind a missing root type definition. if `Mutation` is defined, it'll use it — this is probably a bug!
however, some part of defer bookkeeping cares about the root type definition, so when it's missing, it wasn't able to populate a map of deferred information. this lead to a panic in this very specific case.
in addition, i fixed a TODO about using the router's api schema config within the expansion code.
---
**Checklist** …
=> fix: include mutation root type definition in connectors

.changesets/fix_tninesling_subscription_operation_init.md, apollo-router/src/plugins/demand_control/cost_calculator/fixtures/subscription_query.graphql, apollo-router/src/plugins/demand_control/cost_calculator/fixtures/subscription_schema.graphql, apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs, apollo-router/src/query_planner/plan.rs, apollo-router/src/query_planner/subscription.rs
When subgraph operations are deserialized, typically from a query plan cache, they are not automatically parsed into a full document. Each node needs to initialize its operation(s) prior to execution, and the primary node inside SubscriptionNode was missed in the first pass.
This PR also includes a test for demand control scoring. The new test does not reproduce this original issue, but it does provide some basic coverage to ensure scoring handles this operation type.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this …
=> Eagerly init subgraph operation for subscription primary nodes

.circleci/config.yml, apollo-router/src/plugins/connectors/tests/mod.rs, apollo-router/src/test_harness/http_snapshot.rs, apollo-router/tests/samples/enterprise/connectors-debugging/README.md, apollo-router/tests/samples/enterprise/connectors-debugging/configuration.yaml, apollo-router/tests/samples/enterprise/connectors-debugging/http_snapshots.json, apollo-router/tests/samples/enterprise/connectors-debugging/plan.json, apollo-router/tests/samples/enterprise/connectors-debugging/supergraph.graphql, apollo-router/tests/samples/enterprise/connectors-debugging/supergraph.yaml, apollo-router/tests/samples/enterprise/connectors-defer/http_snapshots.json, apollo-router/tests/samples/enterprise/connectors-defer/plan.json, apollo-router/tests/samples/enterprise/connectors-defer/supergraph.yaml, apollo-router/tests/samples_tests.rs
because the debugger captures the host/port of the http API, i had to add the ability to specify a port. this could be a problem if another test chooses the same port, but that's pretty unlikely given the number of snapshot tests we have.
also, you have to use the subgraph name "connectors" for snapshot tests to work.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration …
=> connectors debugging snapshot test

apollo-router/src/services/layers/content_negotiation.rs
Looking at https://github.com/apollographql/router/issues/6501, I didn't find a test that checks that multiple `Accept` mime types are parsed correctly. The existing tests either use a single mime type in the `Accept` header, or use multiple types that are all unsupported by the router.
The test passes already, so this does not solve #6501, but it covers a case we had not covered before.
---
**Checklist**
**Exceptions**
Compatibility, documentation, performance not relevant for an added test
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for …
=> chore(router): add test for `Accept` with multiple MIME types & parameters

apollo-federation/src/sources/connect/validation/mod.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@all_fields_selected.graphql.snap, apollo-federation/src/sources/connect/validation/test_data/all_fields_selected.graphql
the external directive can be applied to fields, or to an object which effectively applies it to all fields
---
**Checklist**
**Exceptions**
**Notes** …
=> fix: ignore @external types when validating resolvablility

dockerfiles/tracing/datadog-subgraph/package-lock.json, dockerfiles/tracing/jaeger-subgraph/package-lock.json, dockerfiles/tracing/zipkin-subgraph/package-lock.json, examples/coprocessor-override-launchdarkly/package-lock.json
This updates several non-load-bearing "dev dependencies" that we use in our testing framework to resolve security warnings that appear when running `npm audit`.  Due to the nature of the packages' use inside of this reposoitory, none of these updates respresents a risk to users of the router: they are
not included in its compiled distribution nor used at runtime.
=> chore(deps): Update dev dependencies with `npm audit fix`

apollo-federation/src/sources/connect/json_selection/methods.rs, apollo-federation/src/sources/connect/json_selection/methods/public.rs, apollo-federation/src/sources/connect/json_selection/methods/tests.rs
with this method, users can reimplement previous accidental behavior:
```graphql
type Query {
f(foos: [Int]): T
@connect(http: { GET: "/{$args.foos}" }, selection: "$")
}
```
Prior to preview.3, this would result in `"/[1,2,3]"`. We removed that behavior so we could implement repeated path/query params in a principled way. But now you can achieve the same result with:
```graphql
type Query {
f(foos: [Int]): T
@connect(http: { GET: "/{$args.foos->jsonStringify}" }, selection: "$")
}
```
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please …
=> `->jsonStringify` method

apollo-router/src/axum_factory/tests.rs
Adds tests to record the behavior of the decompression layer's new type signature.
---
**Checklist**
**Exceptions**
**Notes** …
=> Add decompression failure tests

.changesets/maint_renee_migrate_metrics_histograms.md, .changesets/maint_renee_migrate_metrics_values.md, apollo-router/src/axum_factory/listeners.rs, apollo-router/src/axum_factory/tests.rs
In #6495 I migrated this metric to an otel ObservableGauge. However the lifetime of the count guard was too short, so the value of the metric would almost always just be 0; and the lifetime of the instrument was too short, so even the wrong value of 0 would not actually be reported. This change was not part of a release so there is no user impact as long as we land this :)
Now the lifetime of the instrument is captured by all requests, so the instrument is kept even post-reload if a request is still being completed from the old schema.
Also, a test verifies that the count increments and decrements as expected.
This does **not need to be ported to Router 2.0**.
---
**Checklist**
- Tests added …
=> fix(router, only 1.x): fix the `apollo_router_session_count_total` metric

.changesets/fix_junior_granddad_salami_dye.md, apollo-router/src/plugins/fleet_detector.rs
This uses hyper's `SizeHint` for infering the request body size when we have a priori knowledge of the request body.
Fixes #6503 
---
**Checklist**
**Exceptions**
None
**Notes** …
=> fix(fleet_detector): use SizeHint for subgraph request when possible

apollo-router/src/plugins/limits/layer.rs, apollo-router/src/services/layers/allow_only_http_post_mutations.rs, apollo-router/src/services/layers/apq.rs, apollo-router/src/services/layers/content_negotiation.rs, apollo-router/src/services/layers/persisted_queries/mod.rs, apollo-router/src/services/layers/query_analysis.rs, apollo-router/src/services/layers/static_page.rs, apollo-router/src/services/router/service.rs, apollo-router/src/services/supergraph/service.rs, dev-docs/layer-inventory.md, layer_inventory.md
Targeting https://github.com/apollographql/router/pull/6486.
This is an attempt to interpret the world, not to change it, but some stylistic nits may have slipped in :)
This PR documents the "front-end" of our service stack, namely everything before query planning. I'll work on the "back-end" (execution, subgraph requests etc) next.
=> Document tower layers in router and supergraph services

.circleci/config.yml
This commit fixes an issue with a downstream dependency (`aws-lc-sys`) caused by using an old version of GCC by updating the base CircleCI image to `current`.
This was realistically a long-time coming because the previous tag of `stable` was deprecated in favor of `current` back in 2022.
Below is a quote from the [docker hub page](https://hub.docker.com/r/cimg/base) explaining the change to the tag names:
> current - This image tag points to the latest, production ready base image. This is a replacement for the old stable tag. This image should be used by projects that want a decent level of stability but would like to get occasional software updates. It is typically updated once a month.
---
**Checklist** …
=> update CircleCI base image

docs/source/routing/self-hosted/containerization/docker.mdx
Add example `compose.yaml` to run router with `docker compose`
=> docs: add docker compose config example

docs/source/routing/performance/caching/entity.mdx
Fixes the "no glyph" representation currently appearing on https://www.apollographql.com/docs/graphos/routing/performance/caching/entity
=> docs: fix entity cache mermaid diagram

apollo-router/src/metrics/mod.rs
It's easy to forget `.with_metrics()` in an async metrics test, and you have to read dev-docs/metrics.md to know about this.
So let's add the link to dev-docs/metrics.md in the doc comments for the metrics assertion macros, and also call it out in the panic message that you get if you forget to do this.
=> Point developers to `.with_metrics()` in metrics assertions

apollo-router/src/axum_factory/tests.rs, apollo-router/src/plugin/mod.rs, apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs, apollo-router/src/plugins/include_subgraph_errors.rs, apollo-router/src/plugins/test.rs, apollo-router/src/plugins/traffic_shaping/mod.rs, apollo-router/src/query_planner/bridge_query_planner.rs, apollo-router/src/query_planner/bridge_query_planner_pool.rs, apollo-router/src/query_planner/caching_query_planner.rs, apollo-router/src/query_planner/execution.rs, apollo-router/src/query_planner/fetch.rs, apollo-router/src/query_planner/tests.rs, apollo-router/src/router_factory.rs, apollo-router/src/services/execution/service.rs, apollo-router/src/services/supergraph/service.rs, apollo-router/src/spec/query.rs, apollo-router/src/spec/query/change.rs
This PR goes on top of v1.59.1 to fix a performance regression introduced in 1.59.0
=> Avoid re-computing implementers_map in QueryHashVisitor (1.59)

apollo-router/src/axum_factory/tests.rs, apollo-router/src/metrics/mod.rs, apollo-router/src/plugin/mod.rs, apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs, apollo-router/src/plugins/include_subgraph_errors.rs, apollo-router/src/plugins/test.rs, apollo-router/src/plugins/traffic_shaping/mod.rs, apollo-router/src/query_planner/caching_query_planner.rs, apollo-router/src/query_planner/execution.rs, apollo-router/src/query_planner/fetch.rs, apollo-router/src/query_planner/query_planner_service.rs, apollo-router/src/query_planner/subscription.rs, apollo-router/src/query_planner/tests.rs, apollo-router/src/router_factory.rs, apollo-router/src/services/connector_service.rs, apollo-router/src/services/execution/service.rs, apollo-router/src/services/fetch_service.rs, apollo-router/src/services/supergraph/service.rs, apollo-router/src/spec/query.rs, apollo-router/src/spec/query/change.rs, docs/source/routing/performance/caching/entity.mdx, docs/source/routing/performance/caching/in-memory.mdx
Step 1 of https://github.com/apollographql/router/pull/6576. After this we can merge next back into dev. *This PR*'s merge commit will turn into the LTS 1.x branch.
The trickiest part here is to apply the changes from #6570 to the connectors code. Basically it's just about changing some `HashMap<Valid<Schema>>` types to the new `SubgraphSchemas` type.
=> merge dev into next

docs/source/reference/router/federation-version-support.mdx
Document router version which support Federation 1.
=> docs: update Federation 1 support

apollo-federation/src/sources/connect/validation/mod.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@all_fields_selected_repro.graphql.snap, apollo-federation/src/sources/connect/validation/test_data/all_fields_selected_repro.graphql
before this change, if you use `extend schema` to add the link directive and you don't define `Query`, the schema extension is dropped and the validations don't see the link. this means that all connector validations are skipped!
---
**Checklist**
**Exceptions**
**Notes** …
=> fix: explictly support `extend schema @link` for connectors

apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap, apollo-router/src/plugins/demand_control/mod.rs, apollo-router/src/plugins/limits/mod.rs, apollo-router/src/plugins/telemetry/config_new/events.rs, apollo-router/src/plugins/telemetry/config_new/graphql/mod.rs, apollo-router/src/plugins/telemetry/logging/mod.rs, apollo-router/src/plugins/test.rs
The PluginTestHarness previously created services on every call.
However this is no good for testing plugins in the new world where services are reused.
The harness has been modified to return service handles that allow calls to be made against the service:
```
let test_harness: PluginTestHarness<MyTestPlugin> =
PluginTestHarness::builder().build().await;
let mut service = test_harness.router_service(|_req| async {
Ok(router::Response::fake_builder()
.data(serde_json::json!({"data": {"field": "value"}}))
.header("x-custom-header", "test-value")
.build()
.unwrap())
});
for _ in 0..2 {
let response = service.call_default().await.unwrap();
assert_eq!(
response.response.headers().get("x-custom-header"),
Some(&HeaderValue::from_static("test-value"))
);
}
```
---
**Checklist**
Complete the …
=> Improve PluginTestHarness for multi call

apollo-federation/src/sources/connect/json_selection/lit_expr.rs, apollo-federation/src/sources/connect/json_selection/parser.rs
The `tuple` and `alt` methods in `nom` can result in high stack usage because they can take a number of parsers as parameters, which are all on the stack at once. Breaking up `alt` calls into smaller chunks of parsers and eliminating `tuple` in favor of incrementally calling parsers results in a large reduction in the amount of data that needs to be on the stack all at once.
This allows parsing a greater depth of nested JSON selection syntax in a given stack size (from a depth 33 to 46 on my local machine for the test case I was using, a 40% improvement).
---
**Checklist**
**Exceptions**
**Notes** …
=> Reduce stack usage when parsing JSON selection

.changesets/fix_simon_rayonless_sysinfo.md, Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/plugins/fleet_detector.rs
In version 1.59.0, Apollo Router started using the `sysinfo` crate to gather metrics about available CPUs and RAM. By default, that crate uses `rayon` internally to parallelize its handling of system processes. In turn, rayon creates a pool of long-lived threads.
In a particular benchmark on a 32-core Linux server, this caused resident memory use to increase by about 150 MB. This is likely a combination of stack space (which only gets freed when the thread terminates) and per-thread space reserved by the heap allocator to reduce cross-thread synchronization cost.
This regression is now fixed by:
* Disabling `sysinfo`’s use of `rayon`, so the thread pool is not created and system processes information is gathered in a sequential loop.
* Making `sysinfo` not gather that information in the …
=> Fix increased memory usage in `sysinfo` since Router 1.59.0 (backport #6634)

apollo-router/src/executable.rs, apollo-router/src/router/event/schema.rs, apollo-router/src/router/event/snapshots/apollo_router__router__event__schema__tests__schema_by_url_fallback@logs.snap, docs/source/reference/migration/from-router-v1.mdx, docs/source/reference/router/configuration.mdx
Follow-up to https://github.com/apollographql/router/pull/6268.
Using `--supergraph-urls` is still supported! Only hot reloading it is not.
The `--supergraph-urls` command-line argument or the `APOLLO_ROUTER_SUPERGRAPH_URLS` environment variable no longer support hot reloading. In v1.x, if hot reloading was enabled, the router would repeatedly fetch the URLs on the interval specified by `--apollo-uplink-poll-interval`.
If hot reloading from a remote URL is desired, consider running a script to download the supergraph URL on an interval, and point the router to the downloaded file on the filesystem.
---
**Checklist**
**Exceptions** …
=> Remove hot reload support for `--supergraph-urls`

apollo-federation/src/sources/connect/validation/selection.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@body_selection.graphql.snap, apollo-federation/src/sources/connect/validation/test_data/body_selection.graphql
Validate that body selections contain at least one variable reference. Otherwise, they would either be selecting from input (which there is none) or just a static literal.
---
**Checklist**
**Exceptions**
**Notes** …
=> Validate body selection contains at least one variable

apollo-router/src/configuration/schema.rs
Prints out a message with a link to the migration guide whenever a configuration is found to be invalid.
---
**Checklist**
**Exceptions**
**Notes** …
=> In case of broken config add warning message with url to migration guide

apollo-router/src/metrics/mod.rs, apollo-router/src/plugins/test.rs
The Router service is required to use UnsyncBoxBody because futures::Stream is not Sync. Changing this to use a different Streams implementation (e.g.: tokio) is a lot of work and not guaranteed to improve things.
This causes issues for `with_metrics()` since it requires the provided closure to be `Send` so that it can be boxed(). Actually, `with_metrics()` doesn't have to box the created closure, it could use `boxed_local()`.
That leads to a simple change to `with_metrics()` which means Router service can be used with it and all existing tests continue to function.
=> with_metrics() doesn't require `Send`

apollo-router/Cargo.toml
A mini syntax tweak that solves a warning on each Cargo run.
```
warning: ./apollo-router/Cargo.toml: `default_features` is deprecated in favor of `default-features` and will not work in the 2024 edition
```
---
**Checklist**
**Exceptions**
Nothing beyond visual inspection deemed necessary for such a trivial change.
**Notes**
[^2]: Configuration is an important part of many changes. Where applicable please …
=> chore: default_features -> default-features in cargo.toml

docs/source/reference/router/configuration.mdx, docs/source/routing/about-router.mdx
- Adds a link to connectors doc in the configuration reference
- Mentions Connectors in the router overview
=> docs: add connectors reference/link

apollo-router/src/plugins/telemetry/apollo_exporter.rs, apollo-router/src/plugins/telemetry/config_new/mod.rs, apollo-router/src/plugins/telemetry/dynamic_attribute.rs, apollo-router/src/plugins/telemetry/fmt_layer.rs, apollo-router/src/plugins/telemetry/otel/layer.rs, apollo-router/src/plugins/telemetry/otel/tracer.rs, apollo-router/src/plugins/telemetry/tracing/datadog/agent_sampling.rs
Primarily updates calls for span lookups to log an error when the lookup doesn't find a span. The OTel layer hooks unfortunately do not return results, but I think a no-op with an error log is preferably than a panic in the case of a missing span. Additionally, this rewrites a few small blocks to avoid calls to unwrap/expect and propagate errors where possible. 
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to …
=> Try not to panic when span lookups fail

apollo-router/src/plugins/cache/entity.rs, apollo-router/src/plugins/connectors/incompatible.rs, apollo-router/src/plugins/connectors/incompatible/coprocessor.rs, apollo-router/src/plugins/connectors/incompatible/demand_control.rs, apollo-router/src/plugins/connectors/incompatible/entity_cache.rs, apollo-router/src/plugins/connectors/incompatible/rhai.rs, apollo-router/src/plugins/connectors/incompatible/telemetry.rs, apollo-router/src/plugins/connectors/incompatible/tls.rs, apollo-router/tests/integration/connectors.rs
This commit adds more warnings for the following features when used in connector-enabled subgraphs:
- TLS
- Rhai
- Coprocessors
- Preview Entity Cache
- Demand Control
- Telemetry
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes …
=> connectors: add more feature warnings

apollo-federation/src/sources/connect/json_selection/apply_to.rs, apollo-federation/src/sources/connect/validation/expression.rs
Causes a composition error in URIs/headers/body when a literal object has a property accessed which doesn't exist.
This is taken from the name resolution code, but has no impact on non-literals right now since there's no resolution yet.
=> Catch invalid fields of literal objects

apollo-router/tests/common.rs
This commit adds back a dump of the logs when running the test harness so that failing tests dump their log for better debugging.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, …
=> add log dump to integration panic

apollo-router/src/plugins/demand_control/cost_calculator/fixtures/federated_ships_typename_query.graphql, apollo-router/src/plugins/demand_control/cost_calculator/fixtures/federated_ships_typename_response.json, apollo-router/src/plugins/demand_control/cost_calculator/snapshots/apollo_router__plugins__demand_control__cost_calculator__static_cost__tests__federated_query_with_typenames@logs.snap, apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
When scoring responses with `__typename`, the lookups were failing and producing far too many warn logs. In request scoring, we short-circuit on this field because it isn't included in the pre-processed schema. This change does the same on response scoring, and it changes the log messages from warn to debug logs.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is …
=> (Demand Control) Properly short-circuit __typename scoring on response fields

docs/shared/diagrams/router-request-lifecycle-overview.mdx, docs/shared/router-lifecycle-services.mdx, docs/source/reference/router/telemetry/instrumentation/events.mdx, docs/source/reference/router/telemetry/instrumentation/spans.mdx, docs/source/routing/customization/overview.mdx, docs/source/routing/observability/telemetry.mdx, docs/source/routing/request-lifecycle.mdx, docs/source/routing/security/authorization.mdx
Manual changes from https://github.com/apollographql/router/pull/6497 into 1.x
See [deploy preview](https://deploy-preview-401--apollo-docs-rewrite.netlify.app/docs/graphos/routing/request-lifecycle) of this branch (created from https://github.com/apollographql/docs-rewrite/pull/401/)
=> docs: router request lifecycle

apollo-federation/src/query_graph/graph_path.rs
Span names do not support `format!` syntax. Instead fields can be used. The `%` operator tells `tracing` to use the Display impl.
Spotted while trying out https://github.com/apollographql/router/pull/6717 :)
=> chore(federation): use attributes on debug spans instead of fmt syntax

docs/source/reference/router/telemetry/metrics-exporters/overview.mdx
`apollo_router_http_requests` metrics were removed in Router 2.0 by https://github.com/apollographql/router/pull/6361. This removes the remaining mentions of them in documention.
`docs/source/reference/migration/from-router-v1.mdx` documents:
> This is replaced by `http.server.request.duration` metric for requests from clients to router and `http.client.request.duration` for requests from router to subgraphs.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this …
=> docs: remove mention of apollo_router_http_requests in metrics exporter docs

apollo-router/src/plugins/router_limits/mod.rs
[HTTP 429 Too Many Requests](https://www.rfc-editor.org/rfc/rfc6585#section-4) normally means that a specific user or client is making too many requests, but the TPS limit counts total requests per Router instance regardless of how many clients are making them. [HTTP 503 Service Unavailable](https://www.rfc-editor.org/rfc/rfc9110#status.503) is more appropriate and should be returned instead since “temporary overload” is a possible reason for unavailability.
---
**Checklist**
**Exceptions**
**Notes** …
=> Use HTTP 503 Service Unavailable for free plan rate limit

Cargo.lock
Any PRs wouldn't merge due to this `xtask check-compliance` error:
```
error[vulnerability]: Hickory DNS failure to verify self-signed RRSIG for DNSKEYs
┌─ /router/Cargo.lock:266:1
│
266 │ hickory-proto 0.24.1 registry+https://github.com/rust-lang/crates.io-index
│ -------------------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2025-0006
= Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0006
= Announcement: https://github.com/hickory-dns/hickory-dns/security/advisories/GHSA-37wc-h8xc-5hc4
= Solution: Upgrade to ^0.24.3 OR >=0.25.0-alpha.5 (try `cargo update -p hickory-proto`)
```
I updated `hickory-proto` version as suggested in the `xtask check-compliance` error message.
```
cargo update -p hickory-proto
```
--- …
=> fix: fixed the compliance error (RUSTSEC-2025-0006)

.changesets/maint_tninesling_skip_disabled_dc_plugin.md, apollo-router/src/plugins/demand_control/cost_calculator/schema.rs, apollo-router/src/plugins/demand_control/mod.rs
When enabled, preallocates capacity for demand control's processed schema and shrinks to fit after processing. When disabled, skips the type processing entirely to minimize startup impact.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing …
=> Reduce demand control allocations on start/reload

apollo-router/Cargo.toml, apollo-router/src/compute_job.rs, apollo-router/src/executable.rs, apollo-router/src/services/layers/persisted_queries/snapshots/apollo_router__services__layers__persisted_queries__tests__pq_layer_freeform_graphql_with_safelist_log_unknown_true@logs.snap
Router creates a thread pool dedicated to "compute jobs" to avoid blocking Tokio threads. By default this pool has as many threads as available CPUs. This can now be changed by setting the `$APOLLO_ROUTER_COMPUTE_THREADS` environment variable to an integer value. This feature is intentionally undocumented and should be considered "experimental".
Also rename the pre-existing (also undocumented) `$APOLLO_ROUTER_NUM_CORES` to `$APOLLO_ROUTER_IO_THREADS` to better reflect what it does.
Drive-by unrelated change: make `cargo run` default to the main router executable.
----
Manual testing instructions: in a terminal, run:
```sh
APOLLO_ROUTER_COMPUTE_THREADS=4 cargo run -- \
-c router.yaml -s examples/graphql/supergraph.graphql --dev \
--log …
```
=> Add $APOLLO_ROUTER_COMPUTE_THREADS environment variable (backport #6746)

.changesets/fix_sushi_caboose_police_agency.md, apollo-federation/src/sources/connect/json_selection/lit_expr.rs
We previously decided to allow leading 0s, per [this discussion](https://github.com/apollographql/router/pull/5762#discussion_r1711807550).
However, since we use the parsing logic of `serde_json::Number` to produce the internal representation, and that logic fails given leading zeros, we need to normalize the input `&str` a bit before calling `number.parse()`. We already perform some similar normalizations, e.g. ensuring the fractional part is at least a 0 (not empty after the `.`), so there's precedent.
Thanks to @nicholascioli for finding this problem using fuzz testing!
=> Remove leading 0s before parsing into `serde_json::Number`

apollo-federation/src/error/mod.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-federation/src/query_plan/query_planning_traversal.rs, apollo-router/src/query_planner/query_planner_service.rs
Before we start generating a query plan, we need to first evaluate all possible ways (options) that given query can be resolved. This PR exposes number of options that were considered to generate a final query plan.
=> expose number of evaluated query plan options

apollo-federation/src/sources/connect/json_selection/selection_set.rs, apollo-router/src/plugins/connectors/make_requests.rs, apollo-router/tests/samples/enterprise/connectors-pqs/README.md, apollo-router/tests/samples/enterprise/connectors-pqs/configuration.yaml, apollo-router/tests/samples/enterprise/connectors-pqs/http_snapshots.json, apollo-router/tests/samples/enterprise/connectors-pqs/manifest.json, apollo-router/tests/samples/enterprise/connectors-pqs/plan.json, apollo-router/tests/samples/enterprise/connectors-pqs/supergraph.graphql, apollo-router/tests/samples/enterprise/connectors-pqs/supergraph.yaml
i'm not sure why, but __typename selections appear in certain fetch node operations only for PQs. our current __typename handling would emit `__typename: $("_Entity")` which is never correct (_Entity is a union), so i added an extra guard against this.
---
**Checklist**
**Exceptions**
**Notes** …
=> fix: connectors, pqs, and __typename

.changesets/feat_pubmodmatt_connectors_ga_config.md, CHANGELOG.md, apollo-router/src/configuration/connector.rs, apollo-router/src/configuration/expansion.rs, apollo-router/src/configuration/metrics.rs, apollo-router/src/configuration/migrations/0035-preview_connectors.yaml, apollo-router/src/configuration/migrations/0036-preview_connectors_subgraphs.yaml, apollo-router/src/configuration/snapshots/apollo_router__configuration__expansion__test__dev_mode.snap, apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap, apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__upgrade_old_configuration@connectors_preview.router.yaml.snap, apollo-router/src/configuration/testdata/metrics/connectors.router.yaml, apollo-router/src/configuration/testdata/migrations/connectors_preview.router.yaml, apollo-router/src/plugins/connectors/configuration.rs, apollo-router/src/plugins/connectors/plugin.rs, apollo-router/src/plugins/connectors/tests/mod.rs, apollo-router/src/router_factory.rs, apollo-router/src/services/connector_service.rs, apollo-router/tests/common.rs, apollo-router/tests/samples/enterprise/connectors-debugging/configuration.yaml, apollo-router/tests/samples/enterprise/connectors-defer/configuration.yaml, apollo-router/tests/samples/enterprise/connectors-demand-control/configuration.yaml, apollo-router/tests/samples/enterprise/connectors-pqs/configuration.yaml, apollo-router/tests/samples/enterprise/connectors/configuration.yaml, docs/source/routing/observability/telemetry/instrumentation/selectors.mdx
Rename `preview_connectors` router config to `connectors`. In addition, `subgraphs` is now moved to `sources`, and under that, settings for a source are under `<subgraph name>.<source name>`. This matches other connectors config, for example, under `telemetry` and `authorization`.
The `$config` item has also changed, from being global to all sources in a subgraph, to being specific to a source under the `<subgraph name>.<source name>` entry.
A migrator is added to rename `preview_connectors` to `connectors`, but we cannot migrate the other changes. A warning is emitted if the `subgraphs` config was in use (which includes `$config` under `subgraphs`). Both the old `subgraphs` and new `sources` are allowed currently. This can be changed after a deprecation period, to remove the `subgraphs` …
=> Move preview_connectors config to connectors for GA

apollo-router/src/configuration/upgrade.rs
It doesn't make sense to point users to `router config upgrade` when this is only run during `router config upgrade`. Since we are starting from a clean slate in router 2.0.0, the effective_migrations are also all unsupported, rather than deprecated, options, and should be emitted as an error than a warn.
=> change error message for unsupported options for `router config upgrade`

apollo-federation/src/sources/connect/json_selection/pretty.rs
My PR #6458 originally included support for conditional inline selections, which would have required a leading `...` for clarity, unlike the existing [`PathWithSubSelection`](https://github.com/apollographql/router/blob/dev/apollo-federation/src/sources/connect/json_selection/README.md#pathwithsubselection-) syntax.
We decided to hold back conditional selection support for the GA release, so I removed it from that PR, but I missed a spot in the pretty-printing code. I've now cleaned that up and added a regression test, with some comments about what we might do in the future, when we get back to implementing conditional selections.
Thanks to @nicholascioli for catching this oversight with fuzz testing.
=> Hide leading `...` for inline `PathWithSubSelection`

Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/test_harness/http_snapshot.rs
Add the ability to specify a `regex` for the URL path in a shapshot file. This is useful when constructing tests that may result in a number of HTTP requests where responses can be reused, or where the path is dynamically generated during the test (such as a randomly generated identifier).
```json
"request": {
"method": "GET",
"path": null,
"regex": "users/.*/posts",
"body": null
},
```
The snapshot server first looks for an exact match to the URL path in the map, then sequentially applies each `regex` if no exact match if found. Performance could degrade if there were a lot of `regex` snapshots, but this should be reasonable for a small number of snapshots.
The regular expression provided will need to escape any special characters used by the `regex` crate, such as the `?` in query …
=> Add ability to specify path as regex in snapshots

apollo-router/src/plugins/telemetry/apollo_otlp_exporter.rs, apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
The telemetry exporter had a mutex that seems unnecessary and increases the risk of deadlock.
In addition, we now call out explicitly that the apollo exporter will not use resources set by the `set_resources` function. This was never called in practice, but it's better to be safe.
---
**Checklist**
**Exceptions**
I'm not putting in a changelog because there is no material change to the code except the removal of the mutex.
There are no docs changes.
Existing export tests pass.
There are no new unit tests written. 
However we could do with some new tests in future as we are relying on integration testing.
**Notes**
[^1]: It may be …
=> Remove mutex from apollo telemetry exporter

apollo-router/src/metrics/aggregation.rs
TLDR:
The aggregate meter provider had not taken into account the possibility that we would add metrics directly to metrics exporters. This meant that if a meter has metrics in them then the circularity would cause a deadlock.
This only happens on shutdown, but I have added tests for reload just in case.
The longer description:
It is very unusual for telemetry exporters to emit telemetry themselves. None of the regular Otel exporters do this and it's the sort of circular reference that can go wrong. The Apollo exporter does this.
This PR builds upon #6790 to ensure that on the event an exporter does try and access the meter provider during shutdown the AggregateMeterProvider will not deadlock.
Our CI has code to detect deadlocks and it will dump stack traces when this happens. The flaky …
=> Prevent deadlocks on metrics shutdown

.circleci/config.yml, RELEASE_CHECKLIST.md
We have a notion of "Latest" which is represented by GitHub.  This indicates what appears on our GitHub Repo homepage, but also what our cURL installer installs when you use `latest`.  (No surprise as it's built on GitHub artifacts which also use that as [its "latest"](https://github.com/apollographql/router/releases/latest))
Because we now have two different "major" versions on the Router repository, we need to make sure they don't both compete for which is "latest".  Removing this from CI and moving this to an explicit step in `RELEASE_CHECKLIST.mdd` is a temporary solution and we can figure out how to operationalize it further next. (Which could actually involve re-introducing this commit, but only on the 2.x line, or something, but there are also other signals we could automatically …
=> chore: Delegate setting "latest" to RELEASE_CHECKLIST.md, rather than CI.

.circleci/config.yml, RELEASE_CHECKLIST.md
We have a notion of "Latest" which is represented by GitHub.  This indicates what appears on our GitHub Repo homepage, but also what our cURL installer installs when you use `latest`.  (No surprise as it's built on GitHub artifacts which also use that as [its "latest"](https://github.com/apollographql/router/releases/latest))
Because we now have two different "major" versions on the Router repository, we need to make sure they don't both compete for which is "latest".  Removing this from CI and moving this to an explicit step in `RELEASE_CHECKLIST.mdd` is a temporary solution and we can figure out how to operationalize it further next. (Which could actually involve re-introducing this commit, but only on the 2.x line, or something, but there are also other signals we could automatically …
=> chore: Delegate setting "latest" to RELEASE_CHECKLIST.md, rather than CI. (backport #6809)

apollo-router/src/state_machine.rs, apollo-router/src/uplink/license_enforcement.rs
removes claims from the event name in the state machine. 
used to look like:
```
INFO  state machine transitioned event="UpdateLicense(Licensed)"
```
currently looks like:
```
INFO  state machine transitioned event="UpdateLicense(Licensed { limits: Some(LicenseLimits { tps: Some(TpsLimit { capacity: 300, interval: 60s }) }) })"
```
and this change brings it back to:
```
INFO  state machine transitioned event="UpdateLicense(Licensed)"
```
---
**Checklist**
**Exceptions**
**Notes** …
=> fix(state-machine): remove claims from license state log

.changesets/fix_lost_typename_attachment.md, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_graph/path_tree.rs, apollo-federation/tests/query_plan/build_query_plan_tests/introspection_typename_handling.rs
Fixed `PathTree::from_paths` to prefer trigger value with a typename sibling attached.
---
**Checklist**
<hr>This is an automatic backport of pull request #6555 done by [Mergify](https://mergify.com).
=> fix(federation): fixed a bug losing `__typename` selection in query plan (backport #6555)

docs/source/routing/graphos-reporting.mdx
In our docs, we claim that "usage reporting" to GraphOS can happen through OpenTelemetry. In reality, we have various reporting mechanisms, and only traces can use OpenTelemetry: operation metrics are for now still using our own format.
This is probably not a huge deal (and it's maybe arguable if this should even be documented in such detail..?), but these tweaks should make things more accurate.
=> docs: tweak language around GraphOS + OTLP trace reporting

docs/source/routing/performance/traffic-shaping.mdx
A user noted that since `experimental_retry` was [removed from traffic shaping](https://github.com/apollographql/router/pull/6338) we should no longer mention it as a task in the [ordering section](https://www.apollographql.com/docs/graphos/routing/performance/traffic-shaping#ordering).
=> docs: remove request retry mention from traffic-shaping

apollo-router/src/metrics/aggregation.rs
TLDR:
The aggregate meter provider had not taken into account the possibility that we would add metrics directly to metrics exporters. This meant that if a meter has metrics in them then the circularity would cause a deadlock.
This only happens on shutdown, but I have added tests for reload just in case.
The longer description:
It is very unusual for telemetry exporters to emit telemetry themselves. None of the regular Otel exporters do this and it's the sort of circular reference that can go wrong. The Apollo exporter does this.
This PR builds upon #6790 to ensure that on the event an exporter does try and access the meter provider during shutdown the AggregateMeterProvider will not deadlock.
Our CI has code to detect deadlocks and it will dump stack traces when this happens. The flaky …
=> Prevent deadlocks on metrics shutdown (backport #6800)

docs/source/routing/graphos-reporting.mdx
This reverts commit 2660308f9f2a66109ccb3b3d27608734a0244e14.
That commit introduced a mdx error preventing all docs builds across apollo: https://github.com/apollographql/apollo-kotlin/pull/6387#issuecomment-2667974068
I'll re-apply it later but correctly...
cc @martinbonnin
=> docs: fix build

docs/source/routing/performance/traffic-shaping.mdx
A user noted that since `experimental_retry` was [removed from traffic shaping](https://github.com/apollographql/router/pull/6338) we should no longer mention it as a task in the [ordering section](https://www.apollographql.com/docs/graphos/routing/performance/traffic-shaping#ordering).<hr>This is an automatic backport of pull request #6826 done by [Mergify](https://mergify.com).
=> docs: remove request retry mention from traffic-shaping (backport #6826)

docs/source/routing/observability/telemetry/metrics-exporters/prometheus.mdx
Calls out difference in prometheus exporter
=> docs: add note for prometheus separator behavior

apollo-router/src/plugins/connectors/http_json_transport.rs, apollo-router/src/plugins/connectors/plugin/debug.rs, apollo-router/src/plugins/telemetry/config_new/connector/selectors.rs, apollo-router/src/plugins/telemetry/config_new/events.rs, apollo-router/src/plugins/telemetry/config_new/instruments.rs, apollo-router/src/plugins/telemetry/fmt_layer.rs, apollo-router/src/services/connector/request_service.rs, apollo-router/src/services/connector/request_service/transport/http.rs
Update connectors request to use a String instead of RouterBody and convert to RouterBody just-in-time to be consistent with how subgraphs are handled.
Why?
1. Simplify code
2. Unblock traffic shaping
3. Unblock coprocessors
4. Make it consistent with the existing subgraph code
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is an important part of many changes. …
=> Update connectors request to use a String instead of RouterBody

docs/source/routing/observability/telemetry/metrics-exporters/prometheus.mdx
Calls out difference in prometheus exporter<hr>This is an automatic backport of pull request #6837 done by [Mergify](https://mergify.com).
=> docs: add note for prometheus separator behavior (backport #6837)

Cargo.lock, Cargo.toml, apollo-router/Cargo.toml
The schemars blocker is now fixed upstream. The local changes needed were already done in https://github.com/apollographql/router/pull/6850 and https://github.com/apollographql/router/pull/6854.
=> Upgrade apollo-router crate to Rust edition 2024

.changesets/fix_stance_intercom_body_director.md, apollo-federation/src/error/mod.rs, apollo-federation/src/operation/mod.rs, apollo-federation/src/operation/tests/mod.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_graph/path_tree.rs, apollo-federation/src/query_plan/fetch_dependency_graph.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-federation/src/query_plan/query_planning_traversal.rs, apollo-federation/tests/query_plan/build_query_plan_tests/overrides.rs, apollo-federation/tests/query_plan/build_query_plan_tests/overrides/shareable.rs, apollo-router/src/compute_job.rs, apollo-router/src/introspection.rs, apollo-router/src/query_planner/query_planner_service.rs, apollo-router/src/services/layers/query_analysis.rs
When a request is cancelled, resources (compute time/memory) allocated to that request should be released. However, query planning is an exception, and currently keeps running after the request is cancelled. This PR adds cooperative cancellation to `build_query_plan()`, to ensure that when the request is cancelled, query planning errors shortly after.
=> Ensure `build_query_plan()` cancels when the request cancels

.circleci/config.yml
It no longer does implicitly: https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html
This hopefully fixes errors like: https://app.circleci.com/pipelines/github/apollographql/router/31290/workflows/ae3f29fe-a970-4ee4-8361-269eb1290577/jobs/230487?invite=true#step-108-710_67
=> Explicitly ask rustup to install the active toolchain

docs/source/routing/customization/overview.mdx
The operation kind is actually lowercase (and always has been).
=> docs: fix values for `apollo::supergraph::operation_kind` context key

docs/source/routing/performance/query-batching.mdx
Clarify that data consistency is primary benefit of query batching.
See [deploy preview](https://www.apollographql.com/docs/deploy-preview/0fb54c667c82f61b01ee6fdb/graphos/routing/performance/query-batching)
=> docs: query batching data consistency 

Cargo.lock
In the `Cargo.lock`, `uuid@1.15.1` no longer depends on `js-sys`. Happened after the `apollo-compiler` [upgrade](https://github.com/apollographql/router/pull/6913) to `v1.27.0`, which removed its dependency on `uuid`. Not sure why CI didn't catch this in that PR.
=> Update Cargo.lock for `uuid` change

.changesets/fix_fix_oltp_enpoint_config.md, apollo-router/src/plugins/telemetry/config.rs, apollo-router/src/plugins/telemetry/endpoint.rs, apollo-router/src/plugins/telemetry/otlp.rs, apollo-router/src/plugins/telemetry/tracing/datadog/mod.rs, apollo-router/src/plugins/telemetry/tracing/jaeger.rs, apollo-router/src/plugins/telemetry/tracing/zipkin.rs
In the router config, if option `telemetry.exporters.metrics.otlp.endpoint` omitted or set as `default` then endpoint URI is populated by [oltp crate](https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-otlp)
This creates subtle issues because router defaults are:
https://github.com/apollographql/router/blob/5a4ee0c9198e5a4428ebe42a64f72d2a83f5b398/apollo-router/src/plugins/telemetry/otlp.rs#L29-L32
But [oltp crate](https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-otlp) defaults are:
https://github.com/open-telemetry/opentelemetry-rust/blob/1f0e361dff504e2fd0344445533a0f653292db81/opentelemetry-otlp/src/exporter/mod.rs#L59-L60
So I think it makes sense to always use router defaults in all places.
---
**Checklist**
Complete the checklist …
=> Use explicit default on omitted telemetry endpoints (backport #6816)

.github/CODEOWNERS
Updating these to new names that we're using internally.  I will backport this to a couple places to ensure they're not used still in actively enforced places.
=> Update team names in CODEOWNERS

.github/CODEOWNERS
Per comment from @goto-bus-stop  in https://github.com/apollographql/router/pull/6936#discussion_r1983194113
=> Remove now unused CODEOWNERS line for apollo-router-scaffold

apollo-federation/src/schema/mod.rs, apollo-federation/src/schema/subgraph_metadata.rs
Implements a pattern for iterating over all applications of a particular directive. In JS, this is called as `directive.applications()` on some directive definition. In Rust, the directive definition itself doesn't have a pointer back to the `FederationSchema`, so the schema will return the iterators. There is a different iterator for each directive because the contained fields don't have useful common types, and this tries to provide a simply, strongly-typed directive representation for consumption.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) …
=> Pattern for iterating over directive applications

Cargo.lock
```
error[vulnerability]: Some AES functions may panic when overflow checking is enabled.
┌─ /home/circleci/project/Cargo.lock:499:1
│
499 │ ring 0.17.8 registry+https://github.com/rust-lang/crates.io-index
│ ----------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2025-0009
= Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0009
```
I ran `cargo update -p ring` per the solution suggested on the advisory.
=> fix(Cargo.lock): fixed a compliance error due to RUSTSEC-2025-0009

apollo-router/src/plugins/limits/mod.rs, apollo-router/src/plugins/test/mod.rs, apollo-router/src/plugins/test/router_ext.rs, apollo-router/src/plugins/test/subgraph_ext.rs, apollo-router/src/plugins/test/supergraph_ext.rs
Allows easy checking of headers/context/body etc.
This doesn't affect production code as it is only for tests.
Example:
```rust
#[tokio::test]
async fn test_subgraph_service_assertions() {
let test_harness: PluginTestHarness<MyTestPlugin> =
PluginTestHarness::builder().build().await;
let service = test_harness.subgraph_service("test_subgraph", |mut req| async move {
req.assert_context_contains("request-context-key");
req.assert_context_not_contains("non-existent-key");
req.assert_context_eq("request-context-key", "request-context-value".to_string());
req.assert_header_eq("x-request-header", "request-value");
req.assert_body_eq(serde_json::json!({"query": "topProducts"}))
.await;
let context = req.context.clone();
context
.insert("response-context-key", …
```
=> Add assertion helpers to plugin test harness

Cargo.lock, apollo-federation/Cargo.toml, apollo-router/Cargo.toml
Pulled out from https://github.com/apollographql/router/pull/6614.
This essentially adds a _new_ version to our tree because 0.13.0 is in use by prost; that will go away once we update prost.
=> deps: update itertools to 0.14.0

Cargo.lock
```
error[vulnerability]: Some AES functions may panic when overflow checking is enabled.
┌─ /home/circleci/project/Cargo.lock:499:1
│
499 │ ring 0.17.8 registry+https://github.com/rust-lang/crates.io-index
│ ----------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2025-0009
= Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0009
```
I ran `cargo update -p ring` per the solution suggested on the advisory.
<hr>This is an automatic backport of pull request #6946 done by [Mergify](https://mergify.com).
=> fix(Cargo.lock): fixed a compliance error due to RUSTSEC-2025-0009 (backport #6946)

.github/CODEOWNERS
Updating these to new names that we're using internally.  I will backport this to a couple places to ensure they're not used still in actively enforced places.<hr>This is an automatic backport of pull request #6936 done by [Mergify](https://mergify.com).
=> Update team names in CODEOWNERS (backport #6936)

Cargo.lock, Cargo.toml, apollo-router/src/plugins/cache/entity.rs, apollo-router/src/plugins/cache/invalidation.rs
Part of https://github.com/apollographql/router/issues/6673
---
**Checklist**
**Exceptions**
**Notes** …
=> Entity caching: sort entity keys before hashing the key (backport #6799)

docs/source/routing/customization/coprocessor.mdx, docs/source/routing/security/authorization.mdx, docs/source/routing/security/jwt.mdx
Fix router 2.x docs to use updated `apollo::authentication::jwt_claims` name
=> docs: jwt_claims

deny.toml
[RUSTSEC-2024-0437](https://rustsec.org/advisories/RUSTSEC-2024-0437) shows a vulnerability in the `protobuf` crate's decoder implementation.
We use protobuf 2.x through the `prometheus` and `opentelemetry-prometheus` crates. A patch is only available for protobuf 3.x.
We basically cannot update to a patched version of `protobuf`, especially since we are also using an older version of opentelemetry.
Luckily, the prometheus crates only use the protobuf *encoder* implementation, not the decoder implementation. So we are not actually affected by the advisory.
This patch adds an exemption for the vulnerability, and disallows adding any *new* dependency on the vulnerable protobuf crates, so we can not silently add a dependency that *does* use the decoder implementation.
=> Add exemption for RUSTSEC-2024-0437 and prevent adding new vulnerable dependencies

deny.toml
[RUSTSEC-2024-0437](https://rustsec.org/advisories/RUSTSEC-2024-0437) shows a vulnerability in the `protobuf` crate's decoder implementation.
We use protobuf 2.x through the `prometheus` and `opentelemetry-prometheus` crates. A patch is only available for protobuf 3.x.
We basically cannot update to a patched version of `protobuf`, especially since we are also using an older version of opentelemetry.
Luckily, the prometheus crates only use the protobuf *encoder* implementation, not the decoder implementation. So we are not actually affected by the advisory.
This patch adds an exemption for the vulnerability, and disallows adding any *new* dependency on the vulnerable protobuf crates, so we can not silently add a dependency that *does* use the decoder implementation.
<hr>This is an …
=> Add exemption for RUSTSEC-2024-0437 and prevent adding new vulnerable dependencies (backport #6962)

.changesets/fix_bnjjj_fix_entity_caching_entity_key.md, Cargo.lock, Cargo.toml, apollo-router/src/plugin/test/mock/subgraph.rs, apollo-router/src/plugins/cache/entity.rs, apollo-router/src/plugins/cache/invalidation.rs, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert-5.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-2.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-3.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-4.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-5.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-6.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_data-3.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_data.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-3.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-5.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private.snap, apollo-router/src/plugins/cache/tests.rs, apollo-router/src/query_planner/mod.rs, apollo-router/src/query_planner/selection.rs, apollo-router/tests/integration/redis.rs
Separate entity keys and representation variable value in the cache key to avoid issues with `@requires` for example.
close #6673 
<hr>This is an automatic backport of pull request #6888 done by [Mergify](https://mergify.com).
=> fix(entity_caching): do not include other fields from representation variable than the entity keys (backport #6888)

apollo-federation/src/correctness/query_plan_analysis.rs, apollo-federation/src/correctness/response_shape.rs, apollo-federation/src/correctness/response_shape_compare.rs
This is a pure refactoring in preparation of the soundness check feature implementation.
It will be easier to review commit by commit.
* 1st commit: Revised `collect_definitions_for_type_condition` to return an `Result<Option<...` value.
* Separating the None case from errors.
* 2nd commit: Clarified the `interpret_*_node` function semantics in query_plan_analysis.
* `state` parameter is only used for `requires` checking (used by the soundness check later).
* `interpret_*_node` functions return only newly fetched responses.
* So, the `state` argument value never flows into the return value.
* This was the original intention and it won't change the behavior of the checker.
* 3rd commit: Improved entity fetch node handling
*  Fetch node may have multiple entity fetches in its subgraph …
=> refactor(federation): QP correctness checker refactoring

.changesets/feat_pipeline_metrics.md, apollo-router/src/configuration/mod.rs, apollo-router/src/plugins/telemetry/config_new/instruments.rs, apollo-router/src/plugins/telemetry/mod.rs, apollo-router/src/services/router.rs, apollo-router/src/services/router/pipeline_handle.rs, apollo-router/src/services/router/service.rs, apollo-router/tests/common.rs, apollo-router/tests/integration/telemetry/fixtures/prometheus_updated.router.yaml, apollo-router/tests/integration/telemetry/metrics.rs, apollo-router/tests/integration/telemetry/otlp.rs, docs/source/routing/observability/telemetry/instrumentation/standard-instruments.mdx
To enable debugging when request pipelines are being kept around a new gauge metric has been added:
- `apollo.router.pipelines` - The number of request pipelines active in the router
- `schema.id` - The Apollo Studio schema hash associated with the pipeline.
- `launch.id` - The Apollo Studio launch id associated with the pipeline (optional).
- `config.hash` - The hash of the configuration
Backport: https://github.com/apollographql/router/pull/6953
---
**Checklist**
**Exceptions**
**Notes** …
=> Add apollo.router.pipelines metrics

apollo-federation/src/query_graph/condition_resolver.rs, apollo-federation/src/query_graph/graph_path.rs
- added `impl Display for GraphPath`
- also, fixed `types: [...]` printing type names without separation.
- added `EdgeIndexDisplay` - a display helper for `EdgeIndex`
- reduced `ConditionResolution` debug dump (changed it to `snapshot!`)
---
**Checklist**
**Exceptions**
Improvements in debug logging. No public behavior changes.
=> test(federation): a few improvements in query planner debug logs

apollo-federation/src/correctness/query_plan_analysis.rs, apollo-federation/src/correctness/response_shape.rs, apollo-federation/src/operation/tests/mod.rs, apollo-federation/tests/query_plan/build_query_plan_support.rs, apollo-federation/tests/query_plan/build_query_plan_tests/context.rs, apollo-federation/tests/query_plan/build_query_plan_tests/merged_abstract_types_handling.rs
This PR removes `@context` arguments from the response shapes computed from query plan's fetch nodes.
- Context arguments are only added in query plans and not present in input query.
- They should be removed from query plan response shape for apples-to-apples comparison.
---
**Checklist**
**Exceptions**
This is about internal testing. No impact on public features.
=> fix(federation/correctness): remove context arguments from entity fetch response shapes

apollo-federation/src/operation/contains.rs, apollo-federation/src/operation/merging.rs, apollo-federation/src/operation/mod.rs, apollo-federation/src/operation/optimize.rs, apollo-federation/src/operation/rebase.rs, apollo-federation/src/operation/selection_map.rs, apollo-federation/src/operation/simplify.rs, apollo-federation/src/operation/tests/mod.rs, apollo-federation/src/query_graph/build_query_graph.rs, apollo-federation/src/query_graph/path_tree.rs, apollo-federation/src/query_plan/conditions.rs, apollo-federation/src/query_plan/fetch_dependency_graph.rs, apollo-federation/src/query_plan/fetch_dependency_graph_processor.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-federation/src/query_plan/query_planning_traversal.rs, apollo-federation/src/schema/field_set.rs, apollo-federation/tests/query_plan/build_query_plan_tests/fragment_autogeneration.rs
In order to simplify the query planning process, we first "normalize" the `apollo-rs` Operation into a form that deduplicates all selections and expands all fragment spreads. As a result, during query planning we only have to handle field selections and inline fragments. This PR refactors federation code to remove all the fragment spread references. Since operations are normalized before query planning, that logic should never be executed anyway. As a side effect fragment generation logic now generates `apollo-rs` Operation instead.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the …
=> chore: refactor federation to avoid referencing fragment spreads

Cargo.lock, apollo-federation/tests/api_schema.rs
The snapshot update is due to the update of Ariadne crate.
=> Update dependencies + fix snapshot

docs/source/routing/security/persisted-queries.mdx
Adds `MinVersion` tags to persisted query configurations. (Spurred on by [this addition](https://github.com/apollographql/router/pull/6987)).
=> doc: Add MinVersions for PQ configs

docs/source/routing/security/persisted-queries.mdx
Adds `MinVersion` tags to persisted query configurations. (Spurred on by [this addition](https://github.com/apollographql/router/pull/6987)).<hr>This is an automatic backport of pull request #7013 done by [Mergify](https://mergify.com).
=> doc: Add MinVersions for PQ configs (backport #7013)

.changesets/fix_brotli_compression_level.md, apollo-router/src/axum_factory/compression/mod.rs
Per the discussion in #6857, the current Brotli compression level is set to `11` which is the highest quality. A setting of `4` is a much more reasonable value for dynamic workloads, and aligns with Koa' & Cloudflare's practice.
Fixes #6857
---
**Checklist**
**Exceptions**
**Notes** …
=> Reduce Brotli compression level

.changesets/feat_feature_configvalidatesubcommand.md, apollo-router/src/configuration/mod.rs, apollo-router/src/executable.rs, docs/source/reference/router/configuration.mdx
Add router config validate subcommand to allow validation of a Router config file without fully starting up the Router.
```
./router config validate <path-to-config-file.yaml>
```
Note this is a port of https://github.com/apollographql/router/pull/6131 to a new PR to be on a fresh branch against Router 2.0. The implementation is otherwise identical.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when …
=> Add router config validate command

apollo-federation/src/link/mod.rs, apollo-federation/src/sources/connect/validation/connect.rs, apollo-federation/src/sources/connect/validation/connect/entity.rs, apollo-federation/src/sources/connect/validation/expression.rs, apollo-federation/src/sources/connect/validation/graphql.rs, apollo-federation/src/sources/connect/validation/graphql/strings.rs, apollo-federation/src/sources/connect/validation/link.rs, apollo-federation/src/sources/connect/validation/mod.rs, apollo-federation/src/sources/connect/validation/schema.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@missing_source_import.graphql.snap, apollo-federation/src/sources/connect/validation/source.rs
Only user facing change is a slight tweak to an error message (see snapshot).
Moves the validations of `@link` for connectors out of `mod.rs` and into a new `ConnectLink` struct—so we "parse" the details of the link to use later, rather than validate their components. Because the spec version and imported names of `@source` and `@connect` come from that link, they are grouped into that struct as well, which causes some code changes elsewhere where they're used.
=> Move connect `@link` validations into their own type/module

.github/CODEOWNERS
The federation and router teams have distinct focuses, and the fed-core team doesn't typically need to review changes to the `apollo-router` directory.
Hopefully this will reduce notification fatigue and make it easier to understand which teams' reviews are blocking the merging of a PR. However, if we find it blocks PRs from being merged, we should revert this change.
NB: This should in no way preclude fed-core from reviewing `apollo-router` changes! All feedback is welcome :)
=> Remove `fed-core` from `apollo-router/` owner list

apollo-federation/src/sources/connect/validation/connect.rs, apollo-federation/src/sources/connect/validation/mod.rs, apollo-federation/src/sources/connect/validation/schema.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@missing_connect_on_mutation_field.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@missing_connect_on_query_field.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@renamed_connect_directive.graphql.snap
Our seen field validation is capable of detecting this already, and this makes more sense to live in the schema-wide checks.
Two user-facing changes:
1. This check will now only happen when the other seen field validations happen—so only after all `@connect` are verified to be accurate
2. The error message and code are different, see the snapshot for details
=> Remove specialization of missing `@connect` on Mutation/Query

apollo-federation/src/sources/connect/validation/connect.rs, apollo-federation/src/sources/connect/validation/schema.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@subscriptions_with_connectors.graphql.snap
Same deal as previous ones, this doesn't have to do with `@connect` specifically, so I've moved it into the schema-wide checks. Which means it won't trigger if there are errors in individual `@connect`s.
Does make me wonder if in the future we want to run _some_ schema-wide checks, just not all to reduce surprises.
=> Move no subscriptions check into schema-wide checks

.changesets/config_meryl_pulsr_1463.md, apollo-router/src/configuration/migrations/0037-preview_otlp_error_metrics.yaml, apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap, apollo-router/src/plugins/connectors/incompatible/telemetry.rs, apollo-router/src/plugins/telemetry/apollo.rs, apollo-router/src/services/layers/persisted_queries/snapshots/apollo_router__services__layers__persisted_queries__tests__pq_layer_freeform_graphql_with_safelist_log_unknown_true@logs.snap, apollo-router/src/services/router/service.rs, apollo-router/src/services/router/tests.rs, apollo-router/tests/integration/connectors.rs
Make the feature flag `experimental_otlp_error_metrics` non-experimental
Implements #PULSR-1463
---
**Checklist**
**Exceptions**
**Notes** …
=> Error categorization: make feature flag non-experimental

.changesets/config_meryl_pulsr_1463.md, apollo-router/src/configuration/migrations/0037-preview_otlp_error_metrics.yaml, apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap, apollo-router/src/plugins/connectors/incompatible/telemetry.rs, apollo-router/src/plugins/telemetry/apollo.rs, apollo-router/src/services/layers/persisted_queries/snapshots/apollo_router__services__layers__persisted_queries__tests__pq_layer_freeform_graphql_with_safelist_log_unknown_true@logs.snap, apollo-router/src/services/router/service.rs, apollo-router/src/services/router/tests.rs, apollo-router/tests/integration/connectors.rs
Reverts apollographql/router#7033
Some issues found with the snapshot and migration might not be working.
=> Revert "Error categorization: make feature flag non-experimental"

.changesets/fix_rreg_use_batch_config_for_apollo_metrics.md, apollo-router/src/plugins/telemetry/metrics/apollo/mod.rs
This fix allows users to control Apollo otlp metrics' `PeriodicReader`with the `telemetry.apollo.batch_processor.scheduled_delay` and `telemetry.apollo.batch_processor.max_export_timeout` configs. This brings parity between Apollo otlp metrics and [non-Apollo otlp Exporter metrics](https://github.com/apollographql/router/blob/0f88850e0b164d12c14b1f05b0043076f21a3b28/apollo-router/src/plugins/telemetry/metrics/otlp.rs#L37-L40)
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism …
=> Use batch_processor Config for Apollo Metrics PerodicReader

.changesets/feat_limit_client_batch_size.md, apollo-router/src/configuration/mod.rs, apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap, apollo-router/src/configuration/tests.rs, apollo-router/src/services/query_batching/testdata/batch_exceeds_maximum_size_response.json, apollo-router/src/services/router/service.rs, apollo-router/src/services/router/tests.rs, docs/source/routing/performance/query-batching.mdx
Add an optional `maximum_size` parameter to the batching configuration. 
* When specified, the router will reject requests which contain more than `maximum_size` queries in the client batch.
* When unspecified, the router performs no size checking (the current behavior).
I've also added tests for the configuration and router, and updated the documentation to reflect the new parameter.
NB: I ended up using HTTP code 422 (`Unprocessable Content`) as the error code when a batch is rejected due to the maximum size limit. My original plan was to use 413 (`Content Too Large`), but the error ended up being mangled by the `limit` plugin.
---
**Checklist**
**Exceptions** …
=> Add configuration option to limit maximum batch size (backport #7005)

apollo-federation/src/sources/connect/validation/connect.rs, apollo-federation/src/sources/connect/validation/connect/method.rs, apollo-federation/src/sources/connect/validation/http.rs
The check is only for `@connect`, so it lives in the `connect` module now. You also can't get a `URLTemplate` out of it unless the template is valid (so moving all related validations into the same place).
This is basically prep for a `ConnectHttp` struct or similar that we will build up containing the entire successfully parsed `http` arg—which we will then type check at a later stage (once that's extracted).
=> Consolidate `@connect(http.method)` checks

.changesets/fix_stance_intercom_body_director.md
Per #6949, this feature doesn't yet work fully. We also need significantly more design and testing time in order to release it without breaking customers.
The part of the feature that's already implemented doesn't hurt, so I'm keeping the existing implementation and its tests. It's not a problem to release it, it just won't do much.
But we shouldn't advertise it in the changelog for 2.1.
=> Remove the cancellation changeset

apollo-federation/src/sources/connect/json_selection/selection_set.rs, apollo-router/src/plugins/connectors/make_requests.rs
the query planner doesn't ask for key fields when it makes a batch entity request (because it already has them). but we'll need key fields in order to match the response objects with the entity references and ensure that the batch result is consistent with the request
---
**Checklist**
**Exceptions**
**Notes** …
=> support preserving key fields in connector response mapping

.changesets/fix_bnjjj_fix_log_with_subs_jwt.md, apollo-router/src/services/supergraph/service.rs
In https://github.com/apollographql/router/pull/6930 we introduced [logs](https://github.com/apollographql/router/pull/6930/files#diff-7597092ab9d509e0ffcb328691f1dded20f69d849f142628095f0455aa49880cR648) in `jwt_expires_in` function which causes a lot of logs when using subscriptions. 
Thanks to this unexpected behavior it unveils a bug in the subscription implementation with JWT. Indeed if there was not JWT claims in the context, before we set a timeout set at `Duration::MAX`. Now it's always pending and there's no timeout anymore
=> fix(subscription): check if jwt claims is part of the context before getting the jwt expiration

Cargo.lock, apollo-router/Cargo.toml
Closes https://github.com/apollographql/router/pull/6923
async-channel is used elsewhere in our dep tree but not by the router directly.
=> deps: remove unused dependency `async-channel`

apollo-federation/src/sources/connect/validation/connect/http.rs, apollo-federation/src/sources/connect/validation/coordinates.rs
Right now parse and type_check are called back-to-back, but once other components are ready, the entire connector can be checked in two phases.
Also swapped the body coordinate to the lazy "don't allocate a string unless we need to" style we use elsewhere, but I put the coordinate right in `http` since I'm hopeful we won't _need_ a top-level `coordinates` module when this is all over.
There's also an open question of whether when we do the type-checking work for the body here if it'd be worth extracting info about keys for use later (rather than re-parsing & extracting as we do today).
=> Split `@connect(http.body)` validations into two phases.

apollo-federation/src/sources/connect/models.rs, apollo-federation/src/sources/connect/spec/schema.rs, apollo-federation/src/sources/connect/validation/connect/http.rs, apollo-federation/src/sources/connect/validation/coordinates.rs, apollo-federation/src/sources/connect/validation/http/url.rs
Right now parse and type_check are called back-to-back, but once other components are ready, the entire connector can be checked in two phases.
Depends on:
=> Split `@connect(http.<METHOD>)` validation into phases.

apollo-federation/src/sources/connect/validation/connect.rs, apollo-federation/src/sources/connect/validation/connect/selection.rs, apollo-federation/src/sources/connect/validation/coordinates.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@empty_selection.graphql.snap, apollo-federation/src/sources/connect/validation/test_data/empty_selection.graphql
Basically, `get_json_selection` became `Selection::parse` and `get_seen_fields_from_selection` became `Selection::type_check`.
One thing we lose by splitting out parsing and type-checking is some ability to keep going after encountering an error. Because we need to keep the success result around (e.g., `Selection` in this case) for later type checking, it's much less ergonomic to collect errors. We'll have to decide if this is acceptable or worth the code complexity cost of working around.
=> Split `@connect(selection:)` parsing & type checking.

.changesets/feat_bryn_connection_metrics_2_0.md, apollo-router/src/plugins/telemetry/config_new/instruments.rs, docs/source/routing/observability/telemetry/instrumentation/standard-instruments.mdx
In this PR we rename the `state` attribute on `apollo.router.open_connections` to `http.connection.state`
This enables us to use the [Otel convention] (https://opentelemetry.io/docs/specs/semconv/attributes-registry/http/#http-connection-state)
Technically this attribute is on a custom instrument, so there is no requirement to call it the same as the convention, but it's probably better from the user perspective to reuse a well known attribute.
Note that we don't support `idle` as a value yet, but we should add this in future.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the …
=> Rename metric attribute `state` to `http.connection.state` (backport #7088)

apollo-federation/src/query_plan/query_planner.rs, apollo-federation/src/schema/field_set.rs, apollo-federation/src/schema/fixtures/field-set-alias.graphqls
`Subgraph::parse_and_expand` is an incomplete implementation and it may be removed in the future.
---
**Checklist**
**Exceptions**
This is a refactoring of test code.
=> refactor(federation): updated QP tests not to use `Subgraph::parse_and_expand`

.changesets/bug_bryn_connection_metrics_rename.md
In the 2.1.0 release we added a metric `apollo.router.open-connections`.
This had an attribute `state` which should have been `http.connection.state`. However the rename PRs missed the cut for the release.
The actual PRs for the rename did get merged, but they updated the original changelog items which will be zapped once the release happens.
It was deemed better to fix this now before many people start relying on this metric.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism …
=> Add changelog for `state`->`http.connection.state` rename

apollo-router/src/compute_job.rs, apollo-router/src/introspection.rs, apollo-router/src/query_planner/query_planner_service.rs, apollo-router/src/services/layers/query_analysis.rs
This PR is expected to not change any run-time behavior, but makes it easier to use the “compute” thread pool:
* The return type no longer includes a `Result` related to the callback having panicked. Instead `resume_unwind` is used to propagate any panic to the caller. This is not a behavior change because every single caller was using `.expect()` on that `Result`, and because we also install a panic hook that exits the process so unwinding never starts this whole code path is unreachable.
* The callback no longer needs to implement `UnwindSafe`. With the above change, `compute_job::execute(job)` is effectively the same as `job()` regarding unwind safety.
---
**Checklist**
- Tests added and …
=> Remove `UnwindSafe` bound and panic `Result` from `compute_job::execute`

apollo-router/src/plugins/rhai/engine.rs, apollo-router/src/plugins/rhai/mod.rs, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__rhai_plugin_execution_service_error@logs.snap, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__rhai_plugin_supergraph_service@logs.snap, apollo-router/src/plugins/rhai/tests.rs
Update the `call_fn` to indicate that the expected return type is `Dynamic` and improve the logging of errors so it's clear which service is failing.
---
**Checklist**
**Exceptions**
**Notes** …
=> Improve the invocation of rhai service methods (backport #7112)

apollo-federation/Cargo.toml, apollo-federation/src/sources/connect/spec/mod.rs, apollo-federation/src/sources/connect/validation/link.rs, apollo-router/Cargo.toml
Unless a build of composition specifically opts in to the unstable 0.2 feature now, composition will reject 0.2 versions.
=> Prevent composition of 0.2.

apollo-federation/src/link/federation_spec_definition.rs, apollo-federation/src/schema/blueprint.rs, apollo-federation/src/sources/connect/expand/carryover.rs
The `build_subgraph` utility takes in a partial schema and expands it to include definitions for `@link` as well as federation directives. Note that this utility is still private to the blueprint tests, but it will soon be ready to use widely in composition tests. After collecting links metadata for the schema, it now applies the blueprint's `on_directive_definition_and_schema_parsed` hook, which ultimately uses the federation spec's `add_elements_to_schema` functionality.
JS source for blueprint hook in [federation.ts](https://github.com/apollographql/federation/blob/3566777b82cc7a5e011a096764f8ee2884524658/internals-js/src/federation.ts#L2113-L2240)
Some notes on the blueprint:
As we go along, we'll probably find that the code in the blueprint is either misnamed or obsolete. This PR …
=> Inject federation definitions when building test schemas

.changesets/fix_improve_jwt_errors.md, apollo-router/src/plugins/authentication/error.rs, apollo-router/src/plugins/authentication/jwks.rs, apollo-router/src/plugins/authentication/tests.rs
Enhanced parsing error messages for JWT Authorization header values now provide developers with clear, actionable feedback while ensuring that no sensitive data is exposed.
Examples of the updated error messages:
```diff
-         Header Value: '<invalid value>' is not correctly formatted. prefix should be 'Bearer'
+         Value of 'authorization' JWT header should be prefixed with 'Bearer'
```
```diff
-         Header Value: 'Bearer' is not correctly formatted. Missing JWT
+         Value of 'authorization' JWT header has only 'Bearer' prefix but no JWT token
```
---
**Checklist**
**Exceptions**
**Notes** …
=> Improve error message for invalid JWT Header values

.circleci/config.yml, RELEASE_CHECKLIST.md
This reverts the change introduced in:
- https://github.com/apollographql/router/pull/6809
This will also need to be backported to 1.x to revert the similarly applied
https://github.com/apollographql/router/pull/6811.
It turns out that this change, while precautionarily a great idea, is not
necessary! This is only noted very very discreetly in this part of the
easily missed [GitHub documentation].
[GitHub documentation]: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#about-release-management:~:text=Optionally%2C%20select%20Set%20as%20latest%20release.%20If%20you%20do%20not%20select%20this%20option%2C%20the%20latest%20release%20label%20will%20automatically%20be%20assigned%20based%20on%20semantic%20versioning.
=> Revert: chore: Delegate setting "latest" to RELEASE_CHECKLIST.md, rather than CI.

docs/source/routing/self-hosted/containerization/index.mdx
Noticed `/` is missing in the config path
Closes https://github.com/apollographql/router/pull/6107
---
**Checklist**
**Exceptions**
**Notes** …
=> docs: add missing slash in the config path

apollo-router/src/plugins/connectors/tests/connect_on_type.rs, apollo-router/src/plugins/connectors/tests/mod.rs, apollo-router/src/plugins/connectors/tests/req_asserts.rs
Connectors assertions weren't properly handling parallel requests, which can technically happen in any order.
=> Fix flakey connectors test

.circleci/config.yml, RELEASE_CHECKLIST.md
This reverts the change introduced in:
- https://github.com/apollographql/router/pull/6809
This will also need to be backported to 1.x to revert the similarly applied
https://github.com/apollographql/router/pull/6811.
It turns out that this change, while precautionarily a great idea, is not
necessary! This is only noted very very discreetly in this part of the
easily missed [GitHub documentation].
[GitHub documentation]: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#about-release-management:~:text=Optionally%2C%20select%20Set%20as%20latest%20release.%20If%20you%20do%20not%20select%20this%20option%2C%20the%20latest%20release%20label%20will%20automatically%20be%20assigned%20based%20on%20semantic%20versioning.
<hr>This is an automatic …
=> Revert: chore: Delegate setting "latest" to RELEASE_CHECKLIST.md, rather than CI. (backport #7125)

apollo-router/src/plugins/telemetry/metrics/apollo/mod.rs
Reverts apollographql/router#7024
We're reverting this because:
1. It reused the configuration for exporting traces. These are very different things. We need to actually have different config for tracing and metrics as exporting should have different periods.
2. The default export period has gone from 60 seconds to 5 seconds for metrics. This vastly increases the metrics we ingest.
3. There are no lower bounds on export frequency. Tracing and metrics should have different lower bounds. This needs to implemented on both tracing and metrics.
=> Revert "Use batch_processor Config for Apollo Metrics PerodicReader"

.changesets/fix_improve_jwt_errors.md, apollo-router/src/plugins/authentication/mod.rs, apollo-router/src/plugins/authentication/tests.rs
Enhanced parsing error messages for JWT Authorization header values now provide developers with clear, actionable feedback while ensuring that no sensitive data is exposed.
Examples of the updated error messages:
```diff
-         Header Value: '<invalid value>' is not correctly formatted. prefix should be 'Bearer'
+         Value of 'authorization' JWT header should be prefixed with 'Bearer'
```
```diff
-         Header Value: 'Bearer' is not correctly formatted. Missing JWT
+         Value of 'authorization' JWT header has only 'Bearer' prefix but no JWT token
```
---
**Checklist**
**Exceptions**
**Notes** …
=> Improve error message for invalid JWT Header values (backport #7121)

docs/source/routing/self-hosted/containerization/index.mdx
Noticed `/` is missing in the config path
Closes https://github.com/apollographql/router/pull/6107
---
**Checklist**
**Exceptions**
**Notes** …
=> docs: add missing slash in the config path (backport #7072)

apollo-federation/src/sources/connect/validation/connect.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch.graphql.snap
Moves the parse/type-check structure up another level for `@connect`. Now, every `@connect` directive in the schema will be parsed before any are type checked _but_ we're still type checking every `@connect` which _does_ parse, so we shouldn't be missing validations.
The functions `fields_seen_by_connectors_on_types`, `fields_seen_by_connectors_on_fields`, and `fields_seen_by_connector` are all combined into a single `Connect::find_on_type` function, except for these changes:
1. Type checking doesn't happen in `find_on_type`, it's now triggered separately in the top-level `fields_seen_by_all_connects` (which should, itself, be broken up in the future).
2. Marking a field with `@connect` as "seen" happens in type checking phase now
3. Checking for direct recursion on field-based connectors …
=> Parse all `@connect` before any type check.

apollo-federation/cli/src/main.rs, apollo-federation/src/correctness/mod.rs, apollo-federation/src/correctness/query_plan_analysis.rs, apollo-federation/src/correctness/query_plan_analysis_test.rs, apollo-federation/src/correctness/query_plan_soundness.rs, apollo-federation/src/correctness/query_plan_soundness_test.rs, apollo-federation/src/correctness/response_shape.rs, apollo-federation/src/correctness/response_shape_compare.rs, apollo-federation/src/query_plan/display.rs, apollo-federation/tests/query_plan/build_query_plan_tests/merged_abstract_types_handling.rs
This PR contains 4 commits with the first 2 commits being just a refactoring and a minor fix:
* refactor: added `AnalysisContext` struct to pass `subgraphs_by_name` around.
* fix: improved `interpret_plan_node_at_path` to compute the merged states
* feat: implemented the soundness part of the correctness checker
* tests
It will be easier to review commit by commit, since the refactoring is widespread.
---
**Checklist**
**Exceptions**
This is an internal testing feature.
The corpus result looked reasonable.
=> feat(federation/correctness): implemented the soundness part of the correctness checker

apollo-federation/src/sources/connect/json_selection/apply_to.rs, apollo-federation/src/sources/connect/json_selection/methods.rs, apollo-federation/src/sources/connect/json_selection/methods/future/and.rs, apollo-federation/src/sources/connect/json_selection/methods/future/arithmetic.rs, apollo-federation/src/sources/connect/json_selection/methods/future/eq.rs, apollo-federation/src/sources/connect/json_selection/methods/future/get.rs, apollo-federation/src/sources/connect/json_selection/methods/future/has.rs, apollo-federation/src/sources/connect/json_selection/methods/future/keys.rs, apollo-federation/src/sources/connect/json_selection/methods/future/match_if.rs, apollo-federation/src/sources/connect/json_selection/methods/future/not.rs, apollo-federation/src/sources/connect/json_selection/methods/future/or.rs, apollo-federation/src/sources/connect/json_selection/methods/future/typeof.rs, apollo-federation/src/sources/connect/json_selection/methods/future/values.rs, apollo-federation/src/sources/connect/json_selection/methods/public/echo.rs, apollo-federation/src/sources/connect/json_selection/methods/public/entries.rs, apollo-federation/src/sources/connect/json_selection/methods/public/first.rs, apollo-federation/src/sources/connect/json_selection/methods/public/json_stringify.rs, apollo-federation/src/sources/connect/json_selection/methods/public/last.rs, apollo-federation/src/sources/connect/json_selection/methods/public/map.rs, apollo-federation/src/sources/connect/json_selection/methods/public/match.rs, apollo-federation/src/sources/connect/json_selection/methods/public/size.rs, apollo-federation/src/sources/connect/json_selection/methods/public/slice.rs
This PR removes the `tail: &WithRange<PathList>` parameter from the `ArrowMethodImpl::apply` trait method that each arrow method must implement, which is a significant simplification because arrow method implementations are now responsible for returning only their immediate value, not also invoking the rest of the path (the `tail`) to return a final value recursively.
For reference, the `tail` of an arrow method invocation is `input->method(arg).THIS.PART`, so it's a little strange that the implementation of each `->method` was previously responsible for continuing to evaluate its own tail. Instead, the runtime code that invokes methods will now call `tail.apply_to_path` automatically on behalf of any method that returns a non-`None` value, enforcing the same protocol for every method. …
=> Simplify `->` method tail handling, ensuring left associativity

apollo-federation/src/link/federation_spec_definition.rs, apollo-federation/src/schema/type_and_directive_specification.rs
I've reviewed the federated schema outputs and compared against JS output and documentation.
I found a few discrepancies and fixed them.
---
**Checklist**
=> fix(federation/composition): fixed a few directive spec definition discrepancies

.changesets/docs_timbotnik_pulsr_1484_graphos_error_docs.md, docs/source/routing/errors.mdx
Provides additional documentation for error codes from Router.  Also better differentiates between HTTP status codes and GraphQL error extensions codes that can occur during Router execution.
https://www.apollographql.com/docs/deploy-preview/bd4351dc12913e9308f58b27/graphos/routing/errors
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is an important part of many …
=> Docs: Expand GraphQL error codes

docs/source/routing/performance/caching/in-memory.mdx
Adding this info to an appropriate place so it is not hidden in just the federation docs
: https://github.com/apollographql/federation/pull/3226/files
=> [docs] Update in-memory cache warm up

.changesets/fix_caroline_deadlock.md, apollo-router/src/plugins/telemetry/formatters/json.rs, apollo-router/src/plugins/telemetry/otel/layer.rs
I've been trying to look into a deadlock on `tracing-subscriber::registry::Extensions`. The function `extract_dd_trace_id` is a relatively good candidate for the lock trigger due to the fact that it's looking at the root span extensions, rather than those of the current span.
For more information about when reentrant locking may cause a deadlock see: https://doc.rust-lang.org/std/sync/struct.RwLock.html
```
// Thread 1              |  // Thread 2
let _rg1 = lock.read();  |
|  // will block
|  let _wg = lock.write();
// may deadlock          |
let _rg2 = lock.read();  |
```
To test this we ran an instrumented version of the router that would log out if re-entrant locking of span extensions was detected.
---
**Checklist**
Complete the checklist (and note appropriate exceptions) before the …
=> Tracing deadlock investigation (backport #7142)

.changesets/feat_bnjjj_config_auto_migration.md, apollo-router/src/configuration/mod.rs, apollo-router/src/configuration/schema.rs, apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__upgrade_old_configuration@minor__health_check.yaml.snap, apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__upgrade_old_major_configuration@apollo_extended_errors.yaml.snap, apollo-router/src/configuration/testdata/migrations/defer_support_ga.router.yaml, apollo-router/src/configuration/testdata/migrations/minor/health_check.yaml, apollo-router/src/configuration/tests.rs, apollo-router/src/configuration/upgrade.rs, apollo-router/src/executable.rs
Enable configuration auto migration when running the Router, only when it's migration written for the related version.
Example: if you're running on Router 2.x, only migrations named `2xxx_*.yaml` will be automatically applied. Previous migrations will have to be applied using `router upgrade` command. 
---
**Checklist**
**Exceptions**
**Notes** …
=> feat(configuration): enable auto migration for minor version bumps

Cargo.lock
This addresses [RUSTSEC-2025-0023](https://rustsec.org/advisories/RUSTSEC-2025-0023).
I don't have a reason to assume that we're affected by this issue (you have to have an unusual `Clone` implementation), so the update is just to unblock our CI, and a changeset is unnecessary.
This is a manual backport of #7174, only increasing the patch version of tokio and not the minor.
=> fix: update tokio to address unsoundness issue (backport #7174)

apollo-router/src/plugins/cache/invalidation.rs, apollo-router/src/query_planner/query_planner_service.rs, apollo-router/src/spec/schema.rs
This PR adds units to several 'duration' metrics' descriptions.
Per #7034, we are not able to actually modify the metrics' units - doing so would change the name of the metrics in Prometheus.
The metrics in question:
* `apollo.router.cache.invalidation.duration`
* `apollo.router.query_planning.plan.duration`
* `apollo.router.query_planning.total.duration`
* `apollo.router.schema.load.duration`
---
**Checklist**
**Exceptions**
**Notes** …
=> Add units to metric descriptions

.changesets/fix_heap_tail_paper_bunk.md, apollo-federation/src/sources/connect/expand/carryover.rs, apollo-federation/src/sources/connect/expand/snapshots/apollo_federation__sources__connect__expand__carryover__tests__carryover.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/it_expand_supergraph@carryover.graphql-3.snap
I didn't notice that the actual argument is removed from the supergraph. I tested this end-to-end and it's working
---
**Checklist**
**Exceptions**
**Notes** …
=> remove argument when adding contextArguments (backport #7132)

apollo-router/src/compute_job.rs
The compute job worker pool is used for CPU-bound tasks, like GraphQL parsing, validation, and query planning. When there are too many jobs to handle in parallel, jobs enter a queue.
We previously set this queue size to 20 (per thread) somewhat arbitrarily. We got some signals that this may be too little. Actually, most jobs complete very quickly.
This patch increases the queue size to 1 000 jobs per thread. For reference, in older router versions that were based on the JavaScript query planner, the equivalent queue size was _10 000_.
The number is still a bit arbitrary, and subject to more changes in the future as we understand its effects better. Along with some other tweaks to job priorities we expect this to give better behaviour and reject fewer requests needlessly.
[ROUTER-1236]: …
=> Adjust compute job worker pool queue size

apollo-router/src/compute_job.rs
The compute job worker pool is used for CPU-bound tasks, like GraphQL parsing, validation, and query planning. When there are too many jobs to handle in parallel, jobs enter a queue.
We previously set this queue size to 20 (per thread) somewhat arbitrarily. We got some signals that this may be too little. Actually, most jobs complete very quickly.
This patch increases the queue size to 1 000 jobs per thread. For reference, in older router versions that were based on the JavaScript query planner, the equivalent queue size was _10 000_.
The number is still a bit arbitrary, and subject to more changes in the future as we understand its effects better. Along with some other tweaks to job priorities we expect this to give better behaviour and reject fewer requests needlessly.
[ROUTER-1236]: …
=> Adjust compute job worker pool queue size (backport #7205)

Cargo.lock, apollo-router/Cargo.toml
There is a potential double-free in crossbeam-channel 0.5.14.
https://github.com/crossbeam-rs/crossbeam/releases/tag/crossbeam-channel-0.5.15<hr>This is an automatic backport of pull request #7209 done by [Mergify](https://mergify.com).
=> deps: update crossbeam-channel (backport #7209)

Cargo.lock, apollo-router/Cargo.toml
There is a potential double-free in crossbeam-channel 0.5.14.
https://github.com/crossbeam-rs/crossbeam/releases/tag/crossbeam-channel-0.5.15<hr>This is an automatic backport of pull request #7209 done by [Mergify](https://mergify.com).<hr>This is an automatic backport of pull request #7215 done by [Mergify](https://mergify.com).
=> deps: update crossbeam-channel (backport #7209) (backport #7215)

.changesets/fix_caroline_compute_pool_metrics.md, apollo-router/src/compute_job/metrics.rs, apollo-router/src/compute_job/mod.rs, apollo-router/src/introspection.rs, apollo-router/src/query_planner/query_planner_service.rs, apollo-router/src/services/layers/query_analysis.rs, apollo-router/tests/integration/telemetry/metrics.rs, docs/source/routing/observability/telemetry/instrumentation/standard-instruments.mdx
This PR extracts some of the work done in #7111 to make use of those metrics in router `v2.x`. It does not include any of the spans, which I assume will be added in #7124.
There are a few changes and some refactoring, which I can revert if it's not helpful - the main change was to promote `compute_job` to a module and extract the metrics into their own file.
New metrics:
- `apollo.router.compute_jobs.queue_is_full` - A counter of requests rejected because the queue was full.
- `apollo.router.compute_jobs.duration` - A histogram of time spent in the compute pipeline by the job, including the queue and query planning.
- `job.type`: (`QueryPlanning`, `QueryParsing`, `Introspection`)
- `job.outcome`: (`ExecutedOk`, `ExecutedError`, `ChannelError`, `RejectedQueueFull`, `Abandoned`)
- …
=> Add compute pool metrics (backport #7184)

apollo-federation/src/schema/schema_upgrader.rs
Ports all tests from [schemaUpgrader.test.ts](https://github.com/apollographql/federation/blob/main/internals-js/src/__tests__/schemaUpgrader.test.ts). Tests are currently ignored and can be selectively enabled as we implement the schema upgrader.
---
**Checklist**
**Exceptions**
**Notes** …
=> Port schema upgrader tests

.changesets/fix_renee_bail_invalid_query_plans.md, apollo-federation/src/query_plan/mod.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-federation/tests/query_plan/build_query_plan_tests/subscriptions.rs, apollo-federation/tests/query_plan/supergraphs/trying_to_use_include_with_a_subscription_results_in_an_error.graphql, apollo-federation/tests/query_plan/supergraphs/trying_to_use_skip_with_a_subscription_results_in_an_error.graphql
When an invalid query plan is generated, we may panic and crash the
router. This was probably introduced before we had the short error
macros :)
Let's use the `bail!()` macro for all these cases and return internal
errors. None of these cases should happen unless there is a bug.
<hr>
This is an automatic backport of pull request #7214 done by [Mergify](https://mergify.com).
[ROUTER-1230]: https://apollographql.atlassian.net/browse/ROUTER-1230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ<hr>This is an automatic backport of pull request #7219 done by [Mergify](https://mergify.com).
=> fix(federation): return internal errors for invalid query plans (backport #7214) (backport #7219)

apollo-federation/src/query_graph/graph_path.rs
We had a bug in the indirect options computation relative to the JS code, where the JS code was not caching the computation if the subsequent operation element had `@skip`/`@include`, but the Rust code forgot to return and effectively was caching (and was doing the computation twice). After looking at the code more closely, both the JS and Rust code are wrong, and there’s nothing wrong with caching indirect options when the subsequent operation element has `@skip`/`@include` (because the computation itself doesn't depend on the subsequent operation element at all). This PR accordingly just removes the branch.
=> Fix indirect options bug where we mistakenly avoid caching for `@skip`/`@include` elements

renovate.json5
Not sure if it hurts, but it surely doesn't help to have it.
=> chore: remove empty matchPackageNames from renovate config

.changesets/feat_bryn_compute_job_spans.md, apollo-router/src/ageing_priority_queue.rs, apollo-router/src/compute_job/metrics.rs, apollo-router/src/compute_job/mod.rs, apollo-router/src/compute_job/snapshots/apollo_router__compute_job__tests__observability@logs.snap, apollo-router/src/plugins/telemetry/consts.rs, apollo-router/src/services/layers/query_analysis.rs, apollo-router/tests/snapshots/apollo_otel_traces__batch_send_header-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__batch_send_header.snap, apollo-router/tests/snapshots/apollo_otel_traces__batch_trace_id-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__batch_trace_id.snap, apollo-router/tests/snapshots/apollo_otel_traces__client_name-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__client_name.snap, apollo-router/tests/snapshots/apollo_otel_traces__client_version-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__client_version.snap, apollo-router/tests/snapshots/apollo_otel_traces__condition_else-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__condition_else.snap, apollo-router/tests/snapshots/apollo_otel_traces__condition_if-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__condition_if.snap, apollo-router/tests/snapshots/apollo_otel_traces__non_defer-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__non_defer.snap, apollo-router/tests/snapshots/apollo_otel_traces__send_header-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__send_header.snap, apollo-router/tests/snapshots/apollo_otel_traces__send_variable_value-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__send_variable_value.snap, apollo-router/tests/snapshots/apollo_otel_traces__trace_id-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__trace_id.snap
The router uses a separate thread pool called "compute jobs" to ensure that requests do not block tokio io worker threads.
This PR adds spans to jobs that are on this pool to allow users to see when latency is introduced due to 
resource contention within the compute job pool.
* `compute_job`:
- `job.type`: (`QueryParsing`|`QueryParsing`|`Introspection`)
* `compute_job.execution`
- `job.age`: `P1`-`P8`
- `job.type`: (`QueryParsing`|`QueryParsing`|`Introspection`)
Jobs are executed highest priority (`P8`) first. Jobs that are low priority (`P1`) age over time, eventually executing 
at highest priority. The age of a job is can be used to diagnose if a job was waiting in the queue due to other higher 
priority jobs also in the queue.
As the result of compute jobs are generally cached these …
=> Add spans for compute jobs

apollo-federation/src/error/mod.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-federation/src/query_plan/query_planning_traversal.rs, apollo-federation/tests/query_plan/build_query_plan_tests.rs, apollo-federation/tests/query_plan/build_query_plan_tests/disable_subgraphs.rs, apollo-federation/tests/query_plan/supergraphs/test_if_disabling_all_subgraph_jumps_causes_error.graphql, apollo-federation/tests/query_plan/supergraphs/test_if_disabling_less_expensive_subgraph_jump_causes_other_to_be_used.graphql, apollo-federation/tests/query_plan/supergraphs/test_if_less_expensive_subgraph_jump_is_used.graphql, apollo-router/src/query_planner/query_planner_service.rs
This PR updates `build_query_plan()` to optionally accept a set of subgraphs that shouldn't be used for query planning. This may result in no query plan being found; if it does, the `SingleFederationError::NoPlanFoundWithDisabledSubgraphs` error is emitted (normally, composition's satisfiability check guarantees that a plan is always found).
[FED-586]: https://apollographql.atlassian.net/browse/FED-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow disabling subgraphs during query planning

.changesets/fix_duckki_entity_cache_matching_key.md, apollo-router/src/plugins/cache/entity.rs, apollo-router/src/plugins/cache/invalidation.rs, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert-5.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_nested_field_set-2.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_nested_field_set-3.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_nested_field_set-4.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_nested_field_set-5.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_nested_field_set-6.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_nested_field_set.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-5.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_data-3.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_data.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-3.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-5.snap, apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private.snap, apollo-router/src/plugins/cache/tests.rs, apollo-router/src/testdata/supergraph_nested_fields.graphql, apollo-router/tests/integration/redis.rs
This is my suggestion for PR https://github.com/apollographql/router/pull/7207.
This PR fixes a bug in entity caching introduced by the fix in https://github.com/apollographql/router/pull/6888 for cases where several `@key` directives with different fields were declared on a type as documented [here](https://www.apollographql.com/docs/graphos/schema-design/federated-schemas/reference/directives#managing-types). 
For example if you have this kind of entity in your schema:
```graphql
type Product @key(fields: "upc") @key(fields: "sku") {
upc: ID!
sku: ID!
name: String
}
```
[ROUTER-1244]: https://apollographql.atlassian.net/browse/ROUTER-1244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(entity-cache): handle multiple key directives

.changesets/fix_renee_bail_invalid_query_plans.md, apollo-federation/src/query_plan/mod.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-federation/tests/query_plan/build_query_plan_tests/subscriptions.rs, apollo-federation/tests/query_plan/supergraphs/trying_to_use_include_with_a_subscription_results_in_an_error.graphql, apollo-federation/tests/query_plan/supergraphs/trying_to_use_skip_with_a_subscription_results_in_an_error.graphql
When an invalid query plan is generated, we may panic and crash the
router. This was probably introduced before we had the short error
macros :)
Let's use the `bail!()` macro for all these cases and return internal
errors. None of these cases should happen unless there is a bug.
This is an automatic backport of pull request #7214 done by [Mergify](https://mergify.com).
[ROUTER-1230]: https://apollographql.atlassian.net/browse/ROUTER-1230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(federation): return internal errors for invalid query plans (backport #7214)

.changesets/fix_simon_unwarn_resource_attr.md, apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
If Uplink is enabled, Router 2.1.x emits this warning at startup event though no user configuration or other choice is responsible for it:
```
WARN  setting resource attributes is not allowed for Apollo telemetry
```
This removes the warning entirely as it’s not particularly helpful.
Reproduction:
```
APOLLO_KEY=secret APOLLO_GRAPH_REF=starstuff@current cargo run
```
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement …
=> Remove "setting resource attributes is not allowed" warning

.changesets/fix_bryn_poll_pending_compute_jobs.md, apollo-router/src/compute_job/mod.rs, apollo-router/src/query_planner/query_planner_service.rs, apollo-router/src/services/router/service.rs, apollo-router/tests/common.rs, apollo-router/tests/integration/fixtures/rust_query_planner.router.yaml, apollo-router/tests/integration/query_planner.rs
Compute jobs in the router are used to execute CPU intensive work outside of the main io worker threads, in particular for QueryParsing, QueryPlanning and Introspection.
We currently check in the pipeline if the compute job is full and if it is then it will return `Poll::Pending` in the tower services.
However this will cause requests to hang until timeout.
This PR shifts the logic into `call` and will immediately return a `SERVICE_UNAVAILABLE` response to the user.
---
**Checklist**
**Exceptions**
No new docs
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour …
=> fix: poll pending compute jobs hang request

xtask/src/commands/package/macos.rs
#7281 passed on CI but breaks xtask locally. Not sure why it passed, but this fixes it.
=> fix: make xtask compile again after #7281

apollo-router/src/compute_job/mod.rs
Pulls in #6663 by @theJC. Adds a log message at `info` level to report the number of threads used by the compute pool as well as the total queue capacity.
Fixes #6662, #6663
---
**Checklist**
**Exceptions**
**Notes** …
=> Report thread pool size and queue length during startup

.changesets/fix_simon_jwt_metrics.md, apollo-router/src/plugins/authentication/mod.rs
This fixes the `apollo.router.operations.authentication.jwt` counter metric to behave [as documented](https://www.apollographql.com/docs/graphos/routing/security/jwt#observability): emitted for every request that uses JWT, with the `authentication.jwt.failed` attribute set to true or false for failed or successful authentication.
Previously, it was only used for failed authentication.
The attribute-less and accidentally-differently-named `apollo.router.operations.jwt` counter was and is only emitted for successful authentication, but is deprecated now.
---
**Checklist**
**Exceptions**
**Notes** …
=> Fix JWT metrics discrepancy

.changesets/fix_renee_increase_compute_job_queue.md
We have a lot of changesets for the compute job worker pool changes, we should consolidate them when we do the release but we should also make sure we do list all the effects.
=> docs: add changeset for #7205

dev-docs/yaml-design-guidance.md
Without a `/`, the URL went to a nonexistent file
=> fix(dev-docs): Fix URL to config migrations documentation

.github/workflows/update_apollo_protobuf.yaml, .github/workflows/update_uplink_schema.yml
I tried to apply some fixes to
https://github.com/apollographql/router/pull/6958 and ended up in an
existential struggle, force-pushing back and forth with Github Actions.
=> chore: warn about pushing changes to Github Actions automatic update PRs

docs/source/routing/security/authorization.mdx
These docs are using the 2.x context key name. In 1.x, you have to instead use the old name, `apollo_authorization::policies::required`.
=> docs: fix context key for required policies (1.x)

docs/source/routing/security/authorization.mdx, docs/source/routing/security/jwt.mdx
In 2.x, you can specify different values for the
`coprocessor.**.context` keys.
- `context: deprecated` uses the 1.x names for context keys.
- `context: all` uses the 2.x names for context keys.
- `context: true` uses the **1.x** names for context keys.
We should not recommend `context: true` anywhere in our docs, except in
the upgrade guide, and should potentially start logging a warning for it.
This updates two mentions of `context: true` are actually _buggy_.
(even better might be to use an allowlist of only the necessary extension
keys here, but I'm just solving the bugs first ;) )
=> docs: use `context: all` for coprocessor in 2.x docs

helm/chart/router/templates/virtualservice.yaml
Closes https://github.com/apollographql/router/pull/7268
Fixes https://github.com/apollographql/router/issues/7267
#7268 as a branch so CI can run.
=> Fix helm template syntax for virtualservice `Hosts` list

docs/source/routing/observability/telemetry/instrumentation/events.mdx
https://www.apollographql.com/docs/graphos/routing/observability/telemetry/instrumentation/events#standard-events
The notice was under the "Custom events" section, but also applies to
the "Standard events" section. This moves the notice to (near) the top
of the page.
https://github.com/apollographql/router/blob/def63abda4e447d36aebc67d7029fcccc59985ea/apollo-router/src/uplink/license_enforcement.rs#L355-L358
[RH-830]: https://apollographql.atlassian.net/browse/RH-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ<hr>This is an automatic backport of pull request #7199 done by [Mergify](https://mergify.com).
=> docs: all event instrumentation config requires a GraphOS plan (backport #7199)

helm/chart/router/templates/virtualservice.yaml
Closes https://github.com/apollographql/router/pull/7268
Fixes https://github.com/apollographql/router/issues/7267
#7268 as a branch so CI can run.<hr>This is an automatic backport of pull request #7284 done by [Mergify](https://mergify.com).
=> Fix helm template syntax for virtualservice `Hosts` list (backport #7284)

.changesets/fix_renee_increase_compute_job_queue.md
We have a lot of changesets for the compute job worker pool changes, we should consolidate them when we do the release but we should also make sure we do list all the effects.<hr>This is an automatic backport of pull request #7287 done by [Mergify](https://mergify.com).
=> docs: add changeset for #7205 (backport #7287)

.changesets/fix_simon_jwt_metrics.md, apollo-router/src/plugins/authentication/mod.rs
This fixes the `apollo.router.operations.authentication.jwt` counter metric to behave [as documented](https://www.apollographql.com/docs/graphos/routing/security/jwt#observability): emitted for every request that uses JWT, with the `authentication.jwt.failed` attribute set to true or false for failed or successful authentication.
Previously, it was only used for failed authentication.
The attribute-less and accidentally-differently-named `apollo.router.operations.jwt` counter was and is only emitted for successful authentication, but is deprecated now.
---
**Checklist**
**Exceptions**
**Notes** …
=> Fix JWT metrics discrepancy (backport #7258)

.changesets/config_header_read_timeout.md, apollo-router/src/axum_factory/axum_http_server_factory.rs, apollo-router/src/axum_factory/listeners.rs, apollo-router/src/configuration/mod.rs, apollo-router/src/configuration/server.rs, apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap, apollo-router/src/configuration/tests.rs, docs/source/routing/configuration.mdx
This change exposes the server's header read timeout as the `server.http.header_read_timeout` configuration option.
By default, the `server.http.header_read_timeout` is set to previously hard-coded 10 seconds. A longer timeout can be configured using the `server.http.header_read_timeout` option.
```yaml title="router.yaml"
server:
http:
header_read_timeout: 30s
```
---
**Checklist**
**Exceptions**
**Notes** …
=> Add configurable server header read timeout

apollo-federation/src/sources/connect/expand/tests/snapshots/connectors@batch.graphql.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/connectors@carryover.graphql.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/connectors@interface-object.graphql.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/connectors@nested_inputs.graphql.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/connectors@normalize_names.graphql.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/connectors@realistic.graphql.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/connectors@simple.graphql.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/connectors@steelthread.graphql.snap, apollo-federation/src/sources/connect/expand/tests/snapshots/connectors@types_used_twice.graphql.snap, apollo-federation/src/sources/connect/models.rs, apollo-federation/src/sources/connect/snapshots/apollo_federation__sources__connect__models__tests__from_schema_v0_2.snap, apollo-federation/src/sources/connect/spec/directives.rs, apollo-federation/src/sources/connect/spec/schema.rs, apollo-router/src/plugins/connectors/configuration.rs, apollo-router/src/plugins/connectors/handle_responses.rs, apollo-router/src/plugins/connectors/http_json_transport.rs, apollo-router/src/plugins/connectors/make_requests.rs, apollo-router/src/plugins/connectors/tracing.rs, apollo-router/src/plugins/headers/mod.rs, apollo-router/src/plugins/traffic_shaping/mod.rs, apollo-router/src/services/connector_service.rs
This doesn't do much right now other than simplify snapshots, but it's part of #7220 and makes that PR easier to review by doing this separately.
=> Change `source_url` to be an `http::Uri`

about.toml
https://github.com/apollographql/router/pull/6972 updated `deny.toml`, but we only run `cargo about` during a release process so the need to update `about.toml` was not visible when merging the PR, only when making a Nightly release:
https://app.circleci.com/pipelines/github/apollographql/router/33528/workflows/9a2cdf3d-e398-48c9-9b2c-aa147117a073/jobs/247848?invite=true#step-117-23403_48
CI for this PR again won’t check it, but I could reproduce the release error locally by running `cargo xtask licenses` and this PR fixes it.
=> Align accepted licenses in `about.toml` with `deny.toml`

apollo-federation/src/sources/connect/models/http_json_transport.rs, apollo-federation/src/sources/connect/string_template.rs
We can no longer short circuit because there are going to be more sources of path/query soon.
Also added a new test to make sure we don't double-encode things that were already encoded, since that's possible with the new model.
[CNN-738]: https://apollographql.atlassian.net/browse/CNN-738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Refactor `make_uri` to prep for properties.

.changesets/fix_events_conditions.md, apollo-router/src/plugins/telemetry/config_new/events.rs, apollo-router/src/plugins/telemetry/config_new/snapshots/apollo_router__plugins__telemetry__config_new__events__tests__router_events@logs.snap, apollo-router/tests/common.rs, apollo-router/tests/integration/telemetry/events.rs, apollo-router/tests/integration/telemetry/mod.rs
The core issue is that currently, some `on_request`/`on_response` functions exit earlier:
https://github.com/apollographql/router/blob/3ae5f3f2e02464f6208f078a6611ec9f2b002ba8/apollo-router/src/plugins/telemetry/config_new/events.rs#L261-L264
And because of it, bypass `response` and custom events:
https://github.com/apollographql/router/blob/3ae5f3f2e02464f6208f078a6611ec9f2b002ba8/apollo-router/src/plugins/telemetry/config_new/events.rs#L273-L281
---
**Checklist**
**Exceptions**
**Notes** …
=> telemetry: correctly apply conditions on events

Cargo.lock, Cargo.toml, apollo-router/Cargo.toml, xtask/Cargo.toml
Removes ~12 dependencies from the main tree by updating `router-fuzz` to use the same version of `reqwest` as `apollo-router`. Should save some time on clean builds in CI & cache space.
Note that xtask is still on the old version because it's not in the workspace.
=> Remove duplicate reqwest

.changesets/fix_caroline_redis_conn_leak.md, apollo-router/src/cache/redis.rs, apollo-router/src/cache/storage.rs, apollo-router/src/metrics/mod.rs, apollo-router/src/plugins/cache/entity.rs, apollo-router/tests/integration/fixtures/redis_connection_closure.router.yaml, apollo-router/tests/integration/redis.rs, dev-docs/metrics.md
The router performs a 'hot reload' whenever it detects a schema update. During this reload, it effectively instantiates a new internal router, warms it up (optional), redirects all traffic to this new router, and drops the old internal router.
This PR fixes a bug in that drop process where the Redis connections are never told to terminate, even though the Redis client pool is dropped. This leads to an ever-increasing number of inactive Redis connections, which eats up memory.
The fix is simply to spawn a task which calls `quit` on the client pool within a `Drop` implementation.
TODO:
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It …
=> fix: terminate unused Redis connections on schema update (backport #7319)

apollo-federation/src/link/federation_spec_definition.rs, apollo-federation/src/link/link_spec_definition.rs, apollo-federation/src/schema/type_and_directive_specification.rs, apollo-federation/src/subgraph/mod.rs, apollo-federation/src/subgraph/typestate.rs, apollo-federation/tests/subgraph/subgraph_validation_tests.rs
Also fixed some validation functions in `type_and_directive_specification.rs`.
Note: This fix won't change the current production behavior of query planner, since QP initialization won't see invalid cases anyways.
---
**Checklist**
=> test(federation/composition): ported the rest of "@core/@link handling" tests 

docs/source/routing/observability/telemetry/metrics-exporters/datadog.mdx, docs/source/routing/observability/telemetry/metrics-exporters/dynatrace.mdx, docs/source/routing/observability/telemetry/metrics-exporters/new-relic.mdx, docs/source/routing/observability/telemetry/metrics-exporters/otlp.mdx
Add clarification that Datadog, Dynatrace, New Relic exporters are configurations of OTLP exporter
=> docs: otlp metrics exporters

docs/source/routing/observability/telemetry/metrics-exporters/datadog.mdx, docs/source/routing/observability/telemetry/metrics-exporters/dynatrace.mdx, docs/source/routing/observability/telemetry/metrics-exporters/new-relic.mdx, docs/source/routing/observability/telemetry/metrics-exporters/otlp.mdx
Add clarification that Datadog, Dynatrace, New Relic exporters are configurations of OTLP exporter<hr>This is an automatic backport of pull request #7334 done by [Mergify](https://mergify.com).
=> docs: otlp metrics exporters (backport #7334)

.changesets/fix_bnjjj_rh_845.md, apollo-router/src/graphql/request.rs, apollo-router/src/services/router/tests.rs
Fix the metric `apollo.router.operations.batching.size`, it will now contain the right batch size.
---
**Checklist**
**Exceptions**
**Notes** …
=> Fix metric `apollo.router.operations.batching.size` (backport #7306)

.changesets/config_renee_warn_on_coprocessor_context_true.md, apollo-router/src/plugins/coprocessor/mod.rs, docs/source/routing/customization/coprocessor.mdx, docs/source/routing/upgrade/from-router-v1.mdx
`context: true` is how you enabled propagating context through coprocessors in 1.x. Now, you should use `context: deprecated` to use the 1.x context key names, or `context: all` to use the 2.x context key names.
`context: true` is an alias for `context: deprecated` but should not be used. This patch clarifies in the docs that you should not use `context: true`, and logs a runtime warning on startup if you do use it.
=> Clarify coprocessor config `context: true` behaviour

.changesets/config_header_read_timeout.md, apollo-router/src/axum_factory/axum_http_server_factory.rs, apollo-router/src/axum_factory/listeners.rs, apollo-router/src/configuration/mod.rs, apollo-router/src/configuration/server.rs, apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap, apollo-router/src/configuration/tests.rs, docs/source/routing/configuration.mdx
This change exposes the server's header read timeout as the `server.http.header_read_timeout` configuration option.
By default, the `server.http.header_read_timeout` is set to previously hard-coded 10 seconds. A longer timeout can be configured using the `server.http.header_read_timeout` option.
```yaml title="router.yaml"
server:
http:
header_read_timeout: 30s
```
---
**Checklist**
**Exceptions**
**Notes** …
=> Add configurable server header read timeout (backport #7262)

apollo-federation/src/query_graph/build_query_graph.rs, apollo-federation/src/query_graph/mod.rs, apollo-federation/src/schema/blueprint.rs, apollo-federation/src/schema/field_set.rs, apollo-federation/src/schema/mod.rs, apollo-federation/src/subgraph/typestate.rs, apollo-federation/src/utils/human_readable.rs, apollo-federation/src/utils/mod.rs
Port `validateKeyOnInterfacesAreAlsoOnAllImplementations()` and `validateInterfaceObjectsAreOnEntities()` from the JS composition code, i.e. the per-subgraph validations for interface objects. Note that as part of this, `printHumanReadableList()` and `joinStrings()`, were also ported.
=> Add subgraph validation for interface objects

.changesets/maint_renee_apollo_compiler_1_28.md, Cargo.lock, Cargo.toml, apollo-federation/tests/api_schema.rs
This introduces a new validation rule, which will reject more queries than before, but it's not breaking because we already didn't support such queries in other parts of the router.
Changelog:
---
- **Reject `@skip`/`@include` on subscription root fields - [dariuszkuc] [SimonSapin] and [goto-bus-stop], [pull/963]**
This implements a [GraphQL spec RFC](https://github.com/graphql/graphql-spec/pull/860), rejecting
subscriptions in validation that can be invalid during execution.
- **New shorthand methods for mutable directive argument access - [tninesling], [pull/967]**
Introduces new methods:
- `DirectiveList::get_all_mut`
- `DirectiveList::argument_by_name_mut`
- `DirectiveList::specified_argument_by_name_mut`
- **Update `ariadne` trait implementations - [lrlna], [pull/960]** …
=> deps: update apollo-compiler (backport #7338)

apollo-router/src/executable.rs, xtask/src/commands/lint.rs
Use a Mutex for the dhat profiler instead of a `static mut`.
Pass `--all-features` to Clippy in `cargo xtask lint`.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document …
=> Fix clippy when run with `--all-features`

docs/source/routing/security/persisted-queries.mdx
This seems like a typo.
---
**Checklist**
**Exceptions**
**Notes**
<hr>This is an …
=> docs: typo on PQ docs (backport #7373)

docs/source/routing/upgrade/from-router-v1.mdx
Clarify removal and replacement of `apollo_router_session_count_active` metric in v2
=> docs: apollo_router_session_count_active

apollo-federation/src/schema/blueprint.rs, apollo-federation/src/schema/validators/external.rs, apollo-federation/src/schema/validators/mod.rs, apollo-federation/tests/subgraph/subgraph_validation_tests.rs
Ported these JS functions:
- validateNoExternalOnInterfaceFields
- validateAllExternalFieldsUsed
---
**Checklist**
=> feat(federation/composition): ported `@external` directive validation

apollo-federation/src/schema/blueprint.rs, apollo-federation/src/schema/mod.rs, apollo-federation/src/schema/referencer.rs, apollo-federation/src/schema/subgraph_metadata.rs, apollo-federation/src/schema/validators/external.rs, apollo-federation/src/schema/validators/key.rs, apollo-federation/src/schema/validators/mod.rs, apollo-federation/src/schema/validators/provides.rs, apollo-federation/src/schema/validators/requires.rs, apollo-federation/tests/subgraph/subgraph_validation_tests.rs
(This is a follow-up PR for https://github.com/apollographql/router/pull/7381.)
Also, this PR fixed incorrect `EXTERNAL_UNUSED` errors by collecting `@requires`/`@provides` directive application on interface fields.
---
**Checklist**
=> feat(federation/composition): implemented `UNSUPPORTED_ON_INTERFACE` errors

Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/configuration/tests.rs, apollo-router/src/executable.rs, apollo-router/src/plugins/authentication/subgraph.rs, apollo-router/src/plugins/coprocessor/mod.rs, apollo-router/src/plugins/telemetry/metrics/apollo/mod.rs, apollo-router/src/services/http/service.rs, apollo-router/src/services/http/tests.rs, apollo-router/src/services/subgraph_service.rs, apollo-router/src/test_harness/http_snapshot.rs, apollo-router/tests/apollo_otel_traces.rs, apollo-router/tests/apollo_reports.rs, apollo-router/tests/set_context.rs, apollo-router/tests/type_conditions.rs, dev-docs/HYPER_1.0_REVIEW_NOTES.md
`aws-lc-sys` is our slowest dependency to build right now (at least on my machine). We also shouldn't need it, because `ring` (which we also have) is functionally equivalent.
When it was originally added (see the deleted Markdown content), there wasn't a clear way to only keep one of those dependencies—but there seems to be a path now! So this PR removes our slowest-to-build dependency as well as several others that were getting pulled in.
Special thanks to @andrewmcgivery for identifying this dependency bottleneck and @Velfi for helping me fix it!
=> Remove aws-lc from dependencies

apollo-federation/src/link/link_spec_definition.rs, apollo-federation/src/schema/blueprint.rs
When the `@link` directive definition is missing, we have some logic that automatically adds the `link` spec's type/directive definitions to the schema. We weren't accounting for the link spec's aliases/imports when doing this, while the JS codebase was, so we've ported that logic here. Note that this logic has several bugs, but we're going to port it as-is for now and address the bugs later.
=> Account for spec aliases/imports when auto-injecting `link` spec directives/types

.changesets/fix_caroline_demote_log_line.md, apollo-router/src/plugins/authentication/mod.rs
This was originally at `info` level and recently changed to `error`. IMO `info` is a more reasonable level for expected failures like these.
NB: 1.x uses `info` level for this message already.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever …
=> fix: decrease log level for JWT authentication failure

docs/source/routing/performance/caching/distributed.mdx
What's changing:
- Updates a link to the in-memory caching page, which currently goes nowhere
=> Fix broken link to in-memory caching docs page

.changesets/fix_bryn_otlp_export_dd_measured.md, apollo-router/src/plugins/telemetry/tracing/datadog/span_processor.rs, apollo-router/tests/integration/telemetry/otlp.rs
Reverts apollographql/router#7344, per observation in https://github.com/apollographql/router/pull/7344#pullrequestreview-2811299291
Instead we'll recommend this configuration and add this to our documentation in a follow-up PR:
```yaml
supergraph:
attributes:
"_dd.measured":
static: 1
```
=> Revert "Add _dd.measured to spans when agent sampling is enabled"

apollo-federation/src/link/context_spec_definition.rs, apollo-federation/src/link/cost_spec_definition.rs, apollo-federation/src/link/federation_spec_definition.rs, apollo-federation/src/link/inaccessible_spec_definition.rs, apollo-federation/src/link/join_spec_definition.rs, apollo-federation/src/link/link_spec_definition.rs, apollo-federation/src/link/spec_definition.rs, apollo-federation/src/merge.rs, apollo-federation/src/schema/type_and_directive_specification.rs
Takes advantage of the static spec definitions by using `&'static` instead of `Box`. This allows us to define directive definitions with `&|v| MY_SPEC_VERSIONS.find(v)` instead of `Box::new(|v| MY_SPEC_VERSIONS.find(v).cloned())`.
To make this work, I've ported over the constructor parameter we were missing from spec definitions, which gives the minimum federation version for each spec.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so …
=> Un-box statically-defined supergraph specifications

Cargo.lock, apollo-federation/Cargo.toml, apollo-federation/cli/src/main.rs, apollo-federation/src/error/mod.rs, apollo-federation/src/error/suggestion.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-federation/src/schema/blueprint.rs, apollo-federation/src/schema/schema_upgrader.rs, apollo-federation/src/subgraph/typestate.rs, apollo-federation/tests/subgraph/subgraph_validation_tests.rs
This PR ports the rest of FederationBlueprint callback implementations.
There are a few places that still need to be revisited (commented as `TODO`). But, the callbacks themselves are useable and ready for review.
=> FederationBlueprint callback implementations

apollo-federation/src/sources/connect/validation/connect/http.rs, apollo-federation/src/sources/connect/validation/connect/selection.rs, apollo-federation/src/sources/connect/validation/errors.rs, apollo-federation/src/sources/connect/validation/expression.rs, apollo-federation/src/sources/connect/validation/http/url_properties.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@invalid_selection_syntax.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@url_properties__invalid_mappings.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@url_properties__path.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@url_properties__query_params.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@valid_selection_with_escapes.graphql.snap
1. Use parsing error location for more accuracy
2. Store the `MappingArgument` in a few places to reuse the expression (vs recreating)
3. Don't allocate coordinate strings unless necessary (using `Display`)
=> Some tweaks to `MappingArgument`

apollo-federation/src/sources/connect/validation/http/url_properties.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@url_properties__invalid_mappings.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@url_properties__path.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@url_properties__query_params.graphql.snap
1. Lean into the "properties aren't special, we will have several of them" feel by storing a `Vec<Property>` instead of iterating on `self`
2. Use the same coordinates in type checking as parsing (sans `http.`)
3. Single definition of the list of properties we're interested in via enum `PropertyName`
=> Lean into iterator in `UrlProperties`

docs/source/routing/cloud/dedicated.mdx
I changed acronym in header to full term. AWS => Amazon Web Services (AWS)
=> Docs: Update Header from Acronym to Full Terminology

Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/plugins/connectors/tests/mod.rs, apollo-router/src/plugins/connectors/tests/req_asserts.rs, apollo-router/src/uplink/mod.rs, apollo-router/tests/common.rs
Updates wiremock to 0.6, removing several dependencies.
One test is changed. A connectors test was asserting that inserting a header with comma-separated values was received as _multiple headers_.
This is not an HTTP feature, but was a quirk of wiremock 0.5. It's removed in 0.6.
https://github.com/LukeMathWalker/wiremock-rs/pull/128/files#diff-d66a7ae966da7f4a6abe13626b8c8793b52f2d81fe85799024f57a14150ababcL146-R120
=> deps: update wiremock

apollo-federation/src/error/mod.rs, apollo-federation/src/subgraph/mod.rs
There are some places in composition code that need to create a `FederationError`, but annotated with subgraph name. Ideally we would split federation errors into internal errors, query planning errors, and composition errors, and give composition errors the ability to be annotated with subgraph name. But that's further out, so for now, this PR tries to introduce a small changeset for allowing subgraph name annotation. If there's a nicer approach with similar size/simplicity, let me know in review and I'll switch to it.
=> Add FederationError variant for subgraph errors

apollo-federation/src/sources/connect/json_selection/README.md, apollo-federation/src/sources/connect/json_selection/apply_to.rs, apollo-federation/src/sources/connect/json_selection/grammar/LitExpr.svg, apollo-federation/src/sources/connect/json_selection/grammar/LitPath.svg, apollo-federation/src/sources/connect/json_selection/lit_expr.rs, apollo-federation/src/sources/connect/json_selection/location.rs, apollo-federation/src/sources/connect/json_selection/parser.rs, apollo-federation/src/sources/connect/json_selection/pretty.rs, apollo-federation/src/sources/connect/json_selection/snapshots/naked_literal_path_for_connect_v0_2-2.snap, apollo-federation/src/sources/connect/json_selection/snapshots/naked_literal_path_for_connect_v0_2-3.snap, apollo-federation/src/sources/connect/json_selection/snapshots/naked_literal_path_for_connect_v0_2-4.snap, apollo-federation/src/sources/connect/json_selection/snapshots/naked_literal_path_for_connect_v0_2-5.snap, apollo-federation/src/sources/connect/json_selection/snapshots/naked_literal_path_for_connect_v0_2-6.snap, apollo-federation/src/sources/connect/json_selection/snapshots/naked_literal_path_for_connect_v0_2.snap
PR #5994 introduced the `$(...)` wrapper for injecting `LitExpr` JSON expression literals into selection syntax. Along with `->` method arguments, the `$(...)` wrapper is one of two ways to enter an expression parsing context, where the syntax to be parsed is closer to JSON than to GraphQL, and thus more convenient for crafting new/input data, as compared with the selection syntax, which is oriented towards selecting/transforming existing data.
Once parsing has entered the expression context, you shouldn't need to keep using `$(...)` to wrap JSON expressions. For many literal expressions, this is true: for example, you can write `$({ a: 1, b: 2 })` rather than `$({ a: $(1), b: $(2) })`. However, if you wanted to apply a `->` method or grab a `.key` from a JSON literal expression, the …
=> Allow naked `LitExpr::LitPath` in expression parsing context

Cargo.lock, apollo-router/Cargo.toml, apollo-router/tests/integration/telemetry/otlp.rs, apollo-router/tests/snapshots/apollo_otel_traces__batch_send_header-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__batch_send_header.snap, apollo-router/tests/snapshots/apollo_otel_traces__batch_trace_id-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__batch_trace_id.snap, apollo-router/tests/snapshots/apollo_otel_traces__client_name-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__client_name.snap, apollo-router/tests/snapshots/apollo_otel_traces__client_version-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__client_version.snap, apollo-router/tests/snapshots/apollo_otel_traces__condition_else-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__condition_else.snap, apollo-router/tests/snapshots/apollo_otel_traces__condition_if-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__condition_if.snap, apollo-router/tests/snapshots/apollo_otel_traces__non_defer-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__non_defer.snap, apollo-router/tests/snapshots/apollo_otel_traces__send_header-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__send_header.snap, apollo-router/tests/snapshots/apollo_otel_traces__send_variable_value-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__send_variable_value.snap, apollo-router/tests/snapshots/apollo_otel_traces__trace_id-2.snap, apollo-router/tests/snapshots/apollo_otel_traces__trace_id.snap, examples/throw-error/rhai/Cargo.toml
1. Removes an unused hyper 0.14 dependency. Now, only one hyper version exists in our tree!
2. Updates `opentelemetry-proto` to align with other otel dependencies. This removes several duplicate otel and protobuf related dependencies
A snapshot changed because of 2). I can't tell for certain if this is because of insta, prost, or opentelemetry-proto. But it's because the `int_value` proto field is an int64, which is arguably not round-trippable in YAML (...assuming a JSON/JS style number implementation where every number is float64). So sometimes int64s have to be serialized as strings.
I think this is an acceptable change, because it's only asserting how the test parses values from serialized protobuf and then serialized to YAML; if it's parsed into a string, or an int, it doesn't really …
=> deps: clean up some duplicate and unused dependencies

apollo-federation/src/sources/connect/json_selection/helpers.rs, apollo-federation/src/sources/connect/json_selection/mod.rs, apollo-federation/src/sources/connect/json_selection/parser.rs, apollo-federation/src/sources/connect/json_selection/selection_trie.rs, apollo-federation/src/sources/connect/models.rs, apollo-federation/src/sources/connect/models/keys.rs, apollo-federation/src/sources/connect/validation/connect/selection.rs, apollo-federation/src/sources/connect/validation/connect/selection/variables.rs, apollo-federation/src/sources/connect/validation/expression.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@keys_and_entities__valid__entity_field_counts_as_key_resolver.graphql.snap, apollo-federation/src/sources/connect/variable.rs
This PR changes `VariableReference::path: Vec<VariablePathPart>` to `VariableReference::selection: SelectionTrie`, introducing a new data structure called `SelectionTrie`, because a single variable reference may involve a nested structure of sub-selections, rather than a single linear path. Acknowledging this complexity allows us to capture more accurate `$batch` usage information, so all essential keys will be included in `@key(fields: "...")`.
There are a number of selection set-related data structures currently in use in this codebase, like `FieldSet` and `apollo_compiler::executable::SelectionSet` and `apollo-federation::operation::SelectionSet`, but `SelectionTrie` seemed worthwhile because it can track location information for all the field names it stores (see …
=> [JSONSelection] Improve `$batch.a { b c }` input selection analysis

apollo-router/tests/samples_tests.rs
Lately the most common test failure I see is in `/enterprise/persisted-queries/basic` from the "samples" tests. It's very flaky and I've reran workflows because of this test at least 6 times last week. It's impossible to debug though. This adds logging when a samples-based test panics.
=> chore: print logs when samples-based test panics

.circleci/config.yml
Remove usage of `mise trust`, which is not required on CI. (https://github.com/apollographql/router/pull/7393#discussion_r2078004099)
Add the `--raw` flag to `install`, to hopefully handle random hangs.
This flag disables parallel installs (is slower), but importantly disables
the terminal UI with progress bars etc. that mise uses. Without
the progress bar, CircleCI should be able to detect that there
has been no output for a while and kill the job if it gets stuck.
=> chore: tweak mise usage on CI

.circleci/config.yml
Remove usage of `mise trust`, which is not required on CI. (https://github.com/apollographql/router/pull/7393#discussion_r2078004099)
Add the `--raw` flag to `install`, to hopefully handle random hangs.
This flag disables parallel installs (is slower), but importantly disables
the terminal UI with progress bars etc. that mise uses. Without
the progress bar, CircleCI should be able to detect that there
has been no output for a while and kill the job if it gets stuck.
<hr>This is an automatic backport of pull request #7466 done by [Mergify](https://mergify.com).
=> chore: tweak mise usage on CI (backport #7466)

apollo-federation/cli/src/main.rs, apollo-federation/src/composition/mod.rs, apollo-federation/src/composition/satisfiability.rs, apollo-federation/src/lib.rs, apollo-federation/src/schema/schema_upgrader.rs, apollo-federation/src/subgraph/mod.rs, apollo-federation/src/subgraph/typestate.rs, apollo-federation/src/supergraph/mod.rs
Initial version of overall composition process with placeholders for various composition phases.
Composition process consists of following phases
1. expand subgraphs - add missing federation definitions to the schema
2. upgrade subgraphs - upgrade fed v1 subgraphs to be compatible with fed v2
3. validate subgraphs - run subgraph validations
4. merge subgraphs - generates supergraph
4. validate satisfiability - ensure we can generate plan for any query
---
**Checklist**
**Exceptions**
**Notes** …
=> federation: implement composition stubs

apollo-federation/cli/src/main.rs, apollo-federation/src/composition/mod.rs, apollo-federation/src/schema/blueprint.rs, apollo-federation/src/subgraph/mod.rs, apollo-federation/src/subgraph/typestate.rs
This avoids mutating the schema during the validation phase. `FederationBlueprint` no longer needs to hold the state of whether root type names should be normalized, and it now takes immutable references to the schema and subgraph metadata. The renaming behavior is covered by existing tests.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is an important part of …
=> Hoist root type normalization up to expanded subgraph stage

apollo-federation/src/schema/blueprint.rs, apollo-federation/src/schema/validators/interface_object.rs, apollo-federation/src/schema/validators/merged.rs, apollo-federation/src/schema/validators/mod.rs, apollo-federation/src/utils/human_readable.rs
This PR implements post-merge validations for composition. Note that:
- These validations are placed in `apollo-federation/src/schema/validators` instead of on `Merger` as would be the case in JS, since (as the TODO notes) there's logic shared with subgraph validations that we'd like to refactor out in the future. (Also, the current Rust `Merger` struct is for the old composition code.)
- Unrelatedly, we also move interface object validations to `apollo-federation/src/schema/validators` to adhere to existing patterns.
=> Implement post-merge validations

apollo-federation/src/link/federation_spec_definition.rs, apollo-federation/src/link/link_spec_definition.rs, apollo-federation/src/schema/blueprint.rs, apollo-federation/src/schema/mod.rs, apollo-federation/src/schema/subgraph_metadata.rs, apollo-federation/src/subgraph/mod.rs, apollo-federation/src/subgraph/typestate.rs, apollo-federation/tests/subgraph/subgraph_validation_tests.rs
* updated `into_fed2_subgraph` to match the JS behavior.
* fixed `DirectiveDefinitionInvalid` errors in tests.
* ported `completeSubgraphSchema`'s behavior more closely.
* ported `setSchemaAsFed2Subgraph`
* renamed the previous `into_fed2_subgraph` to `into_fed2_test_subgraph`.
* updated `LinkSpecDefinition::add_to_schema` to set the correct origin value.
* added `SchemaElement` trait to help compute the origin value to use.
* fixed `add_fed1_link_to_schema` to use the correct origin value.
* (refactor) Also, moved it to `typestate.rs` to group related functions together.
=> fix(federation/composition): updated spec link bootstrapping to match JS version

.circleci/config.yml
We no longer need `gh` installed at this step, but i accidientally re-introduced it in my merge conflict resolution when releasing 2.2.1
=> merge-error: inadvertent preserval of unnecessary orb use

.circleci/config.yml, .config/mise/config.ci.toml
There seem to be some sporadic `mise install` failures happening in CI that seem directly attriubted to `cargo-fuzz`.  There are a few theories here (e.g., is it a combination of nightly builds and `cargo binstall` usage?), but to just eliminate them for now, we'll try disabling it and not installing it.  This should give us an angle on which to figure out next steps.
Let's give it a week.
=> Temporarily disable cargo-fuzz

apollo-federation/tests/subgraph/subgraph_validation_tests.rs
This PR changed those tests to call `build_for_errors_with_option`.
Also, dropped an `ignore` annotation by changing the `should_panic` annotation to match the current status.
---
**Checklist**
**Exceptions**
This PR only changes test annotations.
=> chore(federation/composition): fixed a few `custom_error_message_for_misnamed_directives` tests

Cargo.lock, Cargo.toml, apollo-federation/Cargo.toml, apollo-federation/src/link/context_spec_definition.rs, apollo-federation/src/link/federation_spec_definition.rs, apollo-federation/src/link/inaccessible_spec_definition.rs, apollo-federation/src/link/link_spec_definition.rs, apollo-federation/src/link/mod.rs, apollo-federation/src/link/spec.rs, apollo-federation/src/link/tag_spec_definition.rs, apollo-federation/src/schema/position.rs, apollo-federation/src/schema/schema_upgrader.rs, apollo-federation/src/subgraph/typestate.rs, apollo-federation/tests/subgraph/subgraph_validation_tests.rs, apollo-router/Cargo.toml
* Ports directive specifications for `@inaccessible` and `@tag`.
* Ensures that injected `@link` to the link spec is always first
* Fixes missing composes/supergraph spec config for `@context`
Had some issues with insta snapshot file names being too long, so I updated a few tests comparing long strings to output a text diff via `similar` on failure.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, so use your judgement as to how and when …
=> Port specs for inaccessible and tag

apollo-federation/src/composition/mod.rs, apollo-federation/src/supergraph/mod.rs
* Update `Supergraph<Merged>` state to expose and hold `Valid<Schema>`
* Adds pre_/post_ merge validation steps
=> chore: update composition stubs

apollo-federation/src/sources/connect/validation/connect/http.rs, apollo-federation/src/sources/connect/validation/test_data/uri_templates/valid_connect_absolute_url.graphql
Motivating case is spaces, but this also handles other symbols we will automatically encode at runtime.
[CNN-804]: https://apollographql.atlassian.net/browse/CNN-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix validating pre-encoded symbols before the first expression in an absolute URL

docs/source/routing/customization/rhai/reference.mdx
The docs currently state:
> Your Rhai script can terminate the associated client request that triggered it. To do so, it must throw an exception from the supergraph service.
This is misleading as they can _also_ be terminated from the request service, which can be ideal for some cases since the router service request stage executes before the body is parsed of the operation is validated. So things like rejecting based on a missing header are likely better to be done here.
This PR attempts to update the docs to make it clear that the request can be terminated in the router service.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may …
=> Update Router request termination docs

docs/source/routing/customization/rhai-reference.mdx
The docs currently state:
> Your Rhai script can terminate the associated client request that triggered it. To do so, it must throw an exception from the supergraph service.
This is misleading as they can _also_ be terminated from the request service, which can be ideal for some cases since the router service request stage executes before the body is parsed of the operation is validated. So things like rejecting based on a missing header are likely better to be done here.
This PR attempts to update the docs to make it clear that the request can be terminated in the router service.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may …
=> Update Router request termination docs (backport #7523)

Cargo.lock, apollo-router/Cargo.toml
Because it's part of the `tracing-` dependency group, renovate won't
update this independently.
`tracing-subscriber` already uses `tracing-serde` 0.2.0, so upgrading
our own dependency removes a duplicate crate from the dep tree.
The breaking change is in a part of the API that we don't use, and it
does not affect the serialization format: https://github.com/tokio-rs/tracing/releases/tag/tracing-serde-0.2.0
=> chore: update tracing-serde

docs/source/routing/observability/telemetry/trace-exporters/datadog.mdx
=> docs: fix spelling of `probabilistic_sampling` option

docs/source/routing/observability/telemetry/trace-exporters/datadog.mdx
no comment<hr>This is an automatic backport of pull request #7530 done by [Mergify](https://mergify.com).
=> docs: fix spelling of `probabilistic_sampling` option (backport #7530)

xtask/Cargo.lock, xtask/Cargo.toml
This prevents automated updates of reqwest right now, and it seems
unnecessary as our xtask commands compile just fine without the feature.
https://github.com/apollographql/router/pull/7478
`graphql-client` is used to populate changesets from the GitHub API.
I verified that this still works by generating a changeset for this PR (but
I'm not committing it because this is not a user-facing change).
=> chore: remove unused transitive reqwest dependency from xtask

apollo-federation/src/sources/connect/validation/schema.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch__batch_incorrect_context_key.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch__batch_missing_key.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch__batch_missing_nested_key.graphql.snap, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch__batch_nested_keys.graphql.snap
Adds error locations to new batch validation errors so they will show up correctly in IDE extensions. 
The error location points to the `@connect` directive within which the problem arose as it is not currently possible to point to the correct location within the connector. This will be updated in future work to point to a more exact location within the connector.
---
**Checklist**
**Exceptions**
**Notes** …
=> [Batch] Add connector location as  validation location

apollo-router/Cargo.toml
https://github.com/apollographql/router/pull/7159 doesn't quite work and
I'm not sure how to solve it right now. It might be a hyper-util bug but
it might also be on our end. It compiles and runs fine but the tracing
tests fail.
Our `test_updated` job is also failing because it's attempting to use
hyper-util 0.1.11. By pinning the dependency that should start working
again.
=> chore: pin hyper-util

docs/source/routing/graphos-reporting.mdx
Re-applying https://github.com/apollographql/router/pull/6821 but hopefully without any bugs!
This was reverted initially because it introduced an MDX syntax error. That should now be fixed but let's confirm with the preview build.<hr>This is an automatic backport of pull request #6882 done by [Mergify](https://mergify.com).
=> docs: tweak language around GraphOS + OTLP trace reporting (backport #6882)

apollo-federation/src/sources/connect/models.rs, apollo-federation/src/sources/connect/validation/mod.rs, apollo-federation/src/sources/connect/validation/schema.rs, apollo-federation/src/sources/connect/validation/schema/keys.rs, apollo-federation/src/sources/connect/validation/snapshots/validation_tests@batch__batch_incorrect_field.graphql.snap, apollo-federation/src/sources/connect/validation/test_data/batch/batch_incorrect_field.graphql
Adds the connector directive as the location of variable field error so these errors will show up correctly in IDEs.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: Tick whichever testing boxes are applicable. If you are adding Manual Tests, please document …
=> [Connectors] Ensure variable field error has location

.circleci/config.yml, .config/mise/config.ci-mac.toml, DEVELOPMENT.md
This makes CI work on macOS on *nightly* builds.  Overall, the process of
running codecov on Rust codebases of this size is pretty slow.
It roughly doubled the test run on macOS when it was part of the tests
directly, and it wouldn't even run on most of our Linux boxes due to the
amount of memory that llvm-cov chews up in the process.
To account for that, but still get some coverage numbers, we'll go ahead and
introduce this as a nightly step that lets us get the code coverage once a
day, or on demand as we need it.  To do it on demand on a particular pull
request, this commit also introduces a "triggerable" job on CircleCI called
"coverage_only".
Developers can of course run codecov locally using `cargo llvm-cov nextest`.
=> chore(ci): codecov on macOS in CI nightlies

.changesets/docs_baby_fellow_hard_historian.md, docs/source/routing/security/demand-control.mdx
[ROUTER-1306]: https://apollographql.atlassian.net/browse/ROUTER-1306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(demand-control): Rhai reference for cost measurements as response headers

docs/source/routing/operations/subscriptions/configuration.mdx
This pull request updates the documentation for configuring GraphQL subscriptions in the router. The changes clarify how the router communicates with subgraphs and emphasizes using secure communication practices.  Of course, actual deployments vary and it may not be necessary to use `wss://` over `ws://` (much like `https://` vs `http://`) if you're on a secure local network.
Documentation updates:
* [`docs/source/routing/operations/subscriptions/configuration.mdx`](diffhunk://#diff-83cd99e381c9151daff89360ab08516eae44ec545bcbe38d4d8dbc634cc84d1bL46-R50): Updated the description to specify that the router uses routing URLs defined in the supergraph or the router's YAML configuration. Added a note recommending the use of `wss://` (WebSocket Secure) instead of `ws://` to ensure encrypted …
=> docs: Recommend wss over ws for WebSocket communication with subgraphs.

apollo-federation/src/link/federation_spec_definition.rs, apollo-federation/src/query_graph/condition_resolver.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_graph/graph_path/transition.rs, apollo-federation/src/query_graph/mod.rs
This PR ports `advancePathWithDirectTransition()` from the JS codebase, along with any currently un-ported  downstream functions. It is stacked on [the refactor PR](https://github.com/apollographql/router/pull/7547).
=> feat(federation/composition): port `advancePathWithDirectTransition()` 

apollo-federation/cli/src/main.rs, apollo-federation/examples/api_schema.rs, apollo-federation/src/error/mod.rs, apollo-federation/src/lib.rs, apollo-federation/src/link/spec.rs, apollo-federation/src/link/spec_definition.rs, apollo-federation/src/sources/connect/expand/mod.rs, apollo-federation/src/sources/connect/spec/mod.rs, apollo-federation/tests/core_test.rs, apollo-federation/tests/main.rs, apollo-federation/tests/query_plan/build_query_plan_support.rs, apollo-router/src/spec/schema.rs, apollo-router/src/uplink/testdata/schema_enforcement_spec_version_out_of_range.graphql
This PR ports the `checkFeatureSupport` function and its tests (`core.tests.ts` file).
* The router now checks if all link specs w/ purpose argument are supported.
* Updated query planner tests to check supported links.
---
**Checklist**
**Exceptions**
This PR is intended to match the JS federation's behavior. So, the new behavior is expected and no changeset will be necessary.
=> feat(federation): ported `checkFeatureSupport` function and its tests

CHANGELOG.md
The attribute was renamed for the initial 1.61.1 release but the change of name did not make it into the changelog.
I have already updated the release notes
---
**Checklist**
**Exceptions**
**Notes**
There are no material changes here, it's just the changelog …
=> Fix changelog apollo.router.open_connections -> http.connection.state attribute

.gitleaks.toml
When I merged #7595, I squashed it and so my .gitleaks.toml updates were no longer correct.
This fixes things.
=> Fix the commit for gitleaks

.changesets/fix_bnjjj_add_operation_name_subscription_metric.md, apollo-router/src/metrics/mod.rs, apollo-router/src/notification.rs, apollo-router/src/plugins/subscription.rs, apollo-router/src/services/subgraph_service.rs, apollo-router/src/services/supergraph/tests.rs, apollo-router/tests/integration/mod.rs, apollo-router/tests/integration/subscription_load_test.rs, dev-docs/metrics.md, docs/source/routing/observability/telemetry/instrumentation/standard-instruments.mdx
This PR adds a new label on `apollo.router.opened.subscriptions` metric to know exactly which subscription is still opened.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level …
=> feat(subscription): add operation_name label to apollo.router.opened.subscriptions counter (backport #7606)

apollo-router/src/context/deprecated.rs, apollo-router/src/context/mod.rs, apollo-router/src/plugins/authentication/mod.rs, apollo-router/src/plugins/authorization/mod.rs, apollo-router/src/plugins/demand_control/mod.rs, apollo-router/src/plugins/expose_query_plan.rs, apollo-router/src/plugins/progressive_override/mod.rs, apollo-router/src/plugins/telemetry/mod.rs, apollo-router/src/query_planner/caching_query_planner.rs, apollo-router/src/services/layers/apq.rs, apollo-router/src/services/supergraph/service.rs
Also use a macro to declare the functions so we're sure that the conversion is always implemented both ways.
[ROUTER-1077]: https://apollographql.atlassian.net/browse/ROUTER-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Move the deprecated context key names into a single module

xtask/src/commands/test.rs
Just a small enhancement, if you use `cargo xtask test` you can pass a
filter in command-line arguments, just like with `cargo test` and `cargo
nextest run`.
Ideally we'd just support any and all arguments to `cargo test` and
`cargo nextest run` here. But I'm not sure how to achieve that and this
is the one I miss the most often by far.
=> chore(xtask): pass through test name filters

apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap, apollo-router/src/lib.rs, apollo-router/src/plugins/mock_subgraphs/execution/engine.rs, apollo-router/src/plugins/mock_subgraphs/execution/mod.rs, apollo-router/src/plugins/mock_subgraphs/execution/resolver.rs, apollo-router/src/plugins/mock_subgraphs/execution/result_coercion.rs, apollo-router/src/plugins/mock_subgraphs/mod.rs, apollo-router/src/plugins/mod.rs, apollo-router/tests/integration/mock_subgraphs.rs, apollo-router/tests/integration/mod.rs
---
**Checklist**
**Exceptions**
**Notes** …
=> Let subgraph mocks specify extensions.apollo(Entity)SurrogateKeys

apollo-federation/src/schema/position.rs, apollo-federation/src/schema/referencer.rs, apollo-federation/src/schema/schema_upgrader.rs
While upgrading subgraphs we don't need to recompute this metadata.
=> fix(composition): remove unnecessary metadata recomputation

xtask/src/commands/release.rs
The release script failed to replace a string in a file that did not exist, and there was no information about what failed.
The replacement in has been removed as this has not been effective for a long time as the source docs changed.
I have checked the source docs and the wording is generic enough that we don't need to update on every release.
The PR that broke the release script was: https://github.com/apollographql/router/pull/7497
---
**Checklist**
**Exceptions**
**Notes** …
=> chore: Fix release process

xtask/src/commands/release.rs
Rendering the helm chart for the release was not working.
This PR sets the missing parameter required and updated the file that should be rendered.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in …
=> chore: Fix rendering helm chart for release process

.changesets/feat_caroline_consistent_on_error.md, apollo-router/src/plugins/telemetry/config_new/fixtures/router/attribute.on_graphql_error/metrics.snap, apollo-router/src/plugins/telemetry/config_new/fixtures/router/attribute.on_graphql_error/test.yaml, apollo-router/src/plugins/telemetry/config_new/router/selectors.rs, apollo-router/src/plugins/telemetry/config_new/router/spans.rs, apollo-router/src/plugins/telemetry/config_new/supergraph/selectors.rs
Currently the `subgraph_on_graphql_error` selector will return `true` or `false` while the `on_graphql_error` selector will return `true` or `None`. This updates the `on_graphql_error` selector to return `true` or `false` to align with `subgraph_on_graphql_error`.
---
**Checklist**
**Exceptions**
**Notes** …
=> Align `on_graphql_error` selector return values with `subgraph_on_graphql_error`

apollo-router/src/graphql/request.rs, apollo-router/src/services/router/service.rs
When sending an operation as a GET request, like `/graphql?query={ user { id } }`, you cannot send a batch request.
We use `serde_urlencoded` to parse such requests, and the behaviour is like this:
```rust
use serde_json::Value;
use serde_json::json;
assert_eq!(
serde_urlencoded::from_str::<Value>("query=graphql").unwrap(),
json!({ "query": "graphql" }),
);
assert_eq!(
serde_urlencoded::from_str::<Value>("query=graphql&query=other").unwrap(),
json!({ "query": "other" }),
);
assert_eq!(
serde_urlencoded::from_str::<Value>("query[]=graphql&query[]=other").unwrap(),
json!({ "query[]": "other" }),
);
```
That is, there is no way for `batch_from_urlencoded_query` to ever parse a `serde_json::Value::Array` from the query string.
That means that parsing a batch from a query string is essentially …
=> Batching is not supported for GET requests

apollo-federation/src/lib.rs, apollo-federation/src/link/context_spec_definition.rs, apollo-federation/src/subgraph/mod.rs
Implement a function which accepts an initial schema as a `String`, expands that schema, and returns the diff as a `String`.
This is the first of two changes toward exposing an endpoint for this purpose in the CLI tool.
Context for this change including example input and output can be found here: [Federation LSP Schema-Diffing Endpoint Overview](https://apollographql.atlassian.net/wiki/x/gYC0Y).
---
**Checklist**
- Tests added and passing[^2]
**Exceptions**
**Notes** …
=> Create schema-differ function for LSP

Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/executable.rs, apollo-router/src/lib.rs, apollo-router/src/registry/mod.rs, apollo-router/src/router/event/schema.rs, docs/source/routing/configuration/cli.mdx, docs/source/routing/self-hosted/containerization/docker.mdx
Support fetching the supergraph schema from Apollo OCI Registry, instead of uplink. We also aren't supporting hot-reloading of supergraph schemas as part of this workflow. 
---
**Checklist**
**Exceptions**
**Notes** …
=> Add OCI schema store

renovate.json5
Fixes several problems with automatic rustc updates:
- rustc updates in `mise` were opened as separate PRs (https://github.com/apollographql/router/pull/7506)
- MSRV was not bumped when the mise/docker rustc versions are bumped, causing cargo failures on dependency updates (https://app.circleci.com/pipelines/github/apollographql/router/36356/workflows/d1064bf3-df77-4698-9c0e-4f6ccca4a54b/jobs/269920)
While there, added a dependency group for rand crates as they must be updated together but are not auto-detected as a monorepo (https://github.com/apollographql/router/pull/6979 + https://github.com/apollographql/router/pull/7477)
---
**Checklist**
**Exceptions**
No …
=> fix(deps): add missing files to rustc update configuration

.changesets/feat_glasser_pq_error_include_extensions.md, apollo-router/src/services/layers/persisted_queries/mod.rs
We have found that during migrations to PQ-based safelisting, it is helpful to have a bit more information about what operation the client is trying to run than just the hashed PQ ID, to help find the client app that is being blocked. While the client name can be found in the context, the operation name (if provided explicitly in the body's `operationName` field by the client) is helpful. We now provide this as an extension on the error.
(It is both directly helpful in that it is available in the JSON error response if you're looking at individual failures, and it also makes it easy for a router_service-level Rust or Rhai plugin that's trying to provide more observability into PQ errors to look at the error for the extra data. This error occurs before supergraph_service runs, which means …
=> pq: include operation name in "PQ not found" error

apollo-federation/src/link/federation_spec_definition.rs, apollo-federation/src/schema/schema_upgrader.rs, apollo-federation/src/subgraph/mod.rs, apollo-federation/src/subgraph/spec.rs
Due to the long-standing `subgraph-js` bug we'll continue to define name argument as nullable and rely on validations to ensure that value is set.
=> fix(composition): make compose directive argument nullable

RELEASE_CHECKLIST.md
We don't need to manually publish to crates.io when releasing an `rc`, so this step is now removed from RELEASE_CHECKLIST.md.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level …
=> chore(release_checklist): rc gets published to crates.io in circleci

apollo-federation/src/composition/satisfiability.rs, apollo-federation/src/composition/satisfiability/validation_state.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_graph/graph_path/transition.rs, apollo-federation/src/query_plan/query_planning_traversal.rs, apollo-federation/src/query_plan/query_planning_traversal/non_local_selections_estimation.rs
This PR ports `ValidationState()` from the JS codebase, except `validateTransition()`. Note that:
1. We've skipped `currentSubgraphs()`, as Rust composition doesn't currently at least give node information.
2. The subgraph context keys were strings in JS, but that was just because they needed to be used in JS `Map`s efficiently. We don't have that restriction in Rust, so we use actual data structures for the keys.
- As part of this, we don't need actually need a map from subgraph names to subgraph enum values (that was used in JS to avoid issues with separator characters in the keys potentially being in the subgraph names). 
3. We did not port any fixes from https://github.com/apollographql/federation/pull/3277 yet to this code.
=> feat(federation/composition): port `ValidationState`, except `validateTransition()`

apollo-federation/src/link/context_spec_definition.rs
Updated `ContextSpecDefinition::field_argument_specification` to retrieve the referenced type name using the provided `link` argument to the `get_type` closure. Also, refactored to share the argument name constant from the federation spec module.
Note: The `ContextSpecDefinition` is used for both federation spec and context spec. The `link` argument provides the correct context to the closure.
---
**Checklist**
=> fix(federation/composition): fixed context spec's argument type computation

apollo-router/Cargo.toml, apollo-router/src/axum_factory/axum_http_server_factory.rs, apollo-router/src/axum_factory/metrics.rs
Sorry Zelda. I misled you. You have to create the gauge outside of the layer and then reference the gauge from the layer.
With these small changes, things are working.
=> Turns out you can't create the gauges in the layer fn

apollo-federation/src/link/federation_spec_definition.rs
these definitions are equivalent to 2.9, but they're tied to connect 0.1 and 0.2
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level logs. Please read [this …
=> add FederationSpecDefinition for 2.10 and 2.11

apollo-router/src/plugins/response_cache/postgres.rs
These changes were a bit cumbersome to add as suggestions on #7797, so I created a separate branch. Feel free to reject (they're mostly stylistic)!
* Make use of `rstest` to create simpler parameterized tests. I hadn't used this crate before but it seems to be in use in federation and I think it makes it easier to see what's being tested - but happy to revert if you prefer the existing style.
* Nit: I believe the existing implementation would not work if the user specified `12 months` - `humantime` would convert that to 365 days and the router would reject it with the error `interval bigger than 1 year is not supported` as the current upper bound is `12*28=336`.
=> response cache: suggestions for #7797

.changesets/fix_fix_removing_non_utf_8_headers_with_rhai.md, apollo-router/src/plugins/rhai/engine.rs, apollo-router/src/plugins/rhai/tests.rs, apollo-router/tests/fixtures/non_utf8_header_removal.rhai
When trying to remove non-UTF-8 headers from a Rhai plugin, users were faced with an unhelpful error. Now, non-UTF-8 values will be lossy converted to UTF-8 when accessed from Rhai. This change affects `get`, `get_all`, and `remove` operations.
---
**Checklist**
**Exceptions**
**Notes** …
=> Fix error when removing non-UTF-8 headers with Rhai plugin

Cargo.lock, apollo-router/Cargo.toml, apollo-router/tests/integration/subscription_load_test.rs, apollo-router/tests/integration/subscriptions/mod.rs, apollo-router/tests/integration/subscriptions/ws_passthrough.rs
Follow-up to #7731.
Use the multer crate for parsing subscription `multipart/mixed` streams
instead of a hand-rolled implementation. multer technically is for
`multipart/form-data`, which is sort of the successor format to
`multipart/mixed` if i understand the RFCs correctly. But the format is
essentially identical.
This implementation is mostly stricter than before. These things now
cause test failures:
- Final `--graphql--` boundaries in the middle of the stream
- Omitting the final `--graphql--` boundary
- Not draining the entire subscription
- Non-JSON response chunks
But these benign things will not:
- Having multiple headers on a chunk (we don't do this, but it sounds
valid)
- A chunk boundary occurring at the edge of an HTTP frame from hyper
=> chore: use multer to test subscription responses

.changesets/fix_bryn_subscriptions_integration_tests.md, Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap, apollo-router/src/plugins/coprocessor/execution.rs, apollo-router/src/plugins/coprocessor/mod.rs, apollo-router/src/plugins/coprocessor/supergraph.rs, apollo-router/src/plugins/coprocessor/test.rs, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__it_prints_messages_to_log@logs.snap, apollo-router/src/plugins/rhai/tests.rs, apollo-router/src/services/subgraph_service.rs, apollo-router/tests/common.rs, apollo-router/tests/integration/mod.rs, apollo-router/tests/integration/rhai.rs, apollo-router/tests/integration/subscriptions/callback.rs, apollo-router/tests/integration/subscriptions/fixtures/callback.router.yaml, apollo-router/tests/integration/subscriptions/fixtures/subscription.router.yaml, apollo-router/tests/integration/subscriptions/fixtures/subscription_coprocessor.router.yaml, apollo-router/tests/integration/subscriptions/fixtures/supergraph.graphql, apollo-router/tests/integration/subscriptions/mod.rs, apollo-router/tests/integration/subscriptions/ws_passthrough.rs
Fix handling of invalid GraphQL responses returned from coprocessors, particularly when used with subscriptions. Added conditional response validation and improved testing to ensure correctness.
The router was creating invalid GraphQL responses internally, especially when subscriptions terminate. When a coprocessor is configured, it validates all responses for correctness, causing errors to be logged when the router generates invalid internal responses. This affects the reliability of subscription workflows with coprocessors.
- Added conditional response validation that only validates coprocessor responses when the incoming payload was valid
- Added `response_validation` configuration option (defaults to true) for backward compatibility
- Improved handling of invalid responses to prevent …
=> fix(coprocessor): improve handling of invalid GraphQL responses with conditional validation (backport #7731)

apollo-federation/src/composition/satisfiability/satisfiability_error.rs, apollo-federation/src/composition/satisfiability/validation_state.rs, apollo-federation/src/error/mod.rs, apollo-federation/src/query_graph/build_query_graph.rs, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_graph/graph_path/operation.rs, apollo-federation/src/query_graph/graph_path/transition.rs, apollo-federation/src/query_graph/mod.rs, apollo-federation/src/query_plan/query_planner.rs, apollo-federation/src/query_plan/query_planning_traversal.rs, apollo-federation/src/utils/human_readable.rs
This PR ports `ValidationState.validateTransition()` from the JS codebase. Note that:
1. During the query planner port, we converted the override conditions to a data structure that assumed that each label was either `true` or `false`. In composition, we need to support a third possibility (the JS `undefined`), so I've updated the query planning/composition code to all use a map from labels to booleans instead, as it was in the JS code.
- As part of this, I updated the code to use `Arc<str>` instead of `String` for labels.
- The actual `build_query_plan()` signature was not changed as part of this (the old data structure is just converted to the new one).
2. Downstream functions of `validate_transition()` have been switched to use `CompositionError` instead of `SingleFederationError` …
=> feat(federation/composition): Port `validate_transition()`

apollo-federation/src/link/authenticated_spec_definition.rs, apollo-federation/src/link/database.rs, apollo-federation/src/link/policy_spec_definition.rs, apollo-federation/src/link/requires_scopes_spec_definition.rs, apollo-federation/src/merger/merge_enum.rs, apollo-federation/src/schema/blueprint.rs, apollo-federation/src/subgraph/mod.rs, apollo-federation/src/subgraph/spec.rs, apollo-federation/src/subgraph/typestate.rs, apollo-federation/tests/dhat_profiling/supergraph.rs, apollo-federation/tests/subgraph/subgraph_validation_tests.rs
This PR fixes a bug where Rust composition does not accept newer federation directives like `@authenticated`.
* Fixed validate_federation_imports to use the actual federation spec, instead of hardcoded names.
* Also fixed subgraph tests to auto-import all latest federation directives and not to use supergraph spec links.
* `into_fed2_test_subgraph` was updated to have a `bool` argument that allow auto-importing all federation directives into test subgraph schemas.
* With that, subgraph tests don't need to have spec `@links` any more.
---
**Checklist**
=> fix(federation/composition): fixed `validate_federation_imports` to use the actual federation spec

apollo-federation/src/link/context_spec_definition.rs, apollo-federation/src/subgraph/mod.rs
Currently we rely on `apollo-rs` to compare directive locations. While semantically the same, current implementation compares ordered Vec which means we have to match the same order in the args and location definitions.
=> fix: @context locations should match JS definition

renovate.json5
- Add a group for axum crates (usually released together)
- Add a group for nom crates (versions usually interdependent)
- Narrow the apollo-rs group (apollo-environment-detector &
apollo-federation are unrelated)
Also closes #7845 by renaming `fileMatch` -> `managerFilePatterns`
=> chore: tweak renovate groups

docker-compose.yml, dockerfiles/docker-compose-redis.yml
In our docker compose files (used for integration testing):
- Enable no-new-privileges to prevent privilege escalation attacks.
- Make root file systems read-only where possible
[OE-826]: https://apollographql.atlassian.net/browse/OE-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OE-827]: https://apollographql.atlassian.net/browse/OE-827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ<hr>This is an automatic backport of pull request #7681 done by [Mergify](https://mergify.com).
=> Tighten up security on docker compose files (backport #7681)

apollo-router/Cargo.toml
It turns out that `serde_regex` is sneakily used behind a
`cfg(any(test, feature = "snapshot"))`, so it actually must also be
listed in `[dev-dependencies]` and not only as an optional
feature-flagged dependency.
Add it back & add a comment so we know this for the future
---
**Checklist**
- Tests added and passing
=> fix: make `cargo test` work again after #7860

apollo-router/tests/integration/subscription_load_test.rs
This test is no longer useful since we have other integration tests for subscription in place now.
=> remove useless test

renovate.json5
Cargo dependencies pinned with an exact version (using '=' prefix) will now:
- Be handled in individual PRs (not grouped with other updates)
- Require dashboard approval before a PR is opened
- Never be automerged
This fixes an issue where pinned dependencies like 'rhai' were still being
included in dependency update PRs despite being explicitly pinned for stability
reasons (example: https://github.com/apollographql/router/pull/7863).
=> chore(deps): configure Renovate to handle exact version pins separately

renovate.json5
Version 0.9.x has breaking changes and the underlying package is deprecated. The package works as-is and we can consider replacing it in the future. We'll allow 0.8.x just in case there are any security updates that we need to be aware of.
See: https://github.com/dtolnay/serde-yaml/releases/tag/0.9.34
This resolves the Renovate complaints about this package on the [Dependency Dashboard](https://github.com/apollographql/router/issues/57).
=> chore: pin serde_yaml to 0.8.x range

apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/query_graph/graph_path/operation.rs, apollo-federation/src/query_graph/graph_path/transition.rs
- added `get_op_path_element` method to the `GraphPathTriggerVariant` trait.
- Using that trait method avoids a downcast from `TTrigger` to `GraphPathTrigger` type.
- removed `enum GraphPathTrigger`, which is no longer necessary.
---
**Checklist**
**Exceptions**
This is a pure refactoring.
=> refactor(federation): simplified `GraphPath::add` using `GraphPathTriggerVariant` trait

apollo-router/src/plugins/response_cache/invalidation_endpoint.rs
Make sure to return `content-type: application/json` in response headers from the invalidation endpoint.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level logs. Please read …
=> fix(response_cache): add content-type header in invalidation responses

.changesets/fix_bnjjj_rh_924.md, apollo-router/src/services/subgraph_service.rs, apollo-router/tests/integration/subscriptions/mod.rs, apollo-router/tests/integration/subscriptions/ws_passthrough.rs
Address a regression in subscription deduplication introduced in #5505. The client connection close event does not need handling in this task because it is managed elsewhere. Additionally, part of #5505 resolved the issue related to closing the websocket connection. This PR also includes tests to ensure no future regressions related to subscription deduplication and websocket close events.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this before seeking PR approval. The mechanism for doing this will vary considerably, …
=> Fix the subscription duplication problem when the client terminates the original subscription. (backport #7879)

fuzz/Cargo.toml
This `rand` version must be aligned with the `bnf` version used, as we pass a random number generator to `bnf::Grammar::generate`.
In the next version of `bnf`, we can remove our `rand` dependency thanks to https://github.com/shnewto/bnf/pull/175.
Until then, we should pin it with `=` syntax so renovate stops making PRs for it that can't be merged.
https://github.com/apollographql/router/pull/7857 should be closed by renovate after landing this
---
**Checklist**
**Notes** …
=> chore: pin `rand` version used for fuzzing

apollo-federation/src/connectors/expand/tests/snapshots/connectors@batch.graphql.snap, apollo-federation/src/connectors/expand/tests/snapshots/connectors@carryover.graphql.snap, apollo-federation/src/connectors/expand/tests/snapshots/connectors@interface-object.graphql.snap, apollo-federation/src/connectors/expand/tests/snapshots/connectors@keys.graphql.snap, apollo-federation/src/connectors/expand/tests/snapshots/connectors@nested_inputs.graphql.snap, apollo-federation/src/connectors/expand/tests/snapshots/connectors@normalize_names.graphql.snap, apollo-federation/src/connectors/expand/tests/snapshots/connectors@realistic.graphql.snap, apollo-federation/src/connectors/expand/tests/snapshots/connectors@sibling_fields.graphql.snap, apollo-federation/src/connectors/expand/tests/snapshots/connectors@simple.graphql.snap, apollo-federation/src/connectors/expand/tests/snapshots/connectors@steelthread.graphql.snap, apollo-federation/src/connectors/expand/tests/snapshots/connectors@types_used_twice.graphql.snap, apollo-federation/src/connectors/models.rs, apollo-federation/src/connectors/snapshots/apollo_federation__connectors__models__tests__from_schema_v0_2.snap, apollo-federation/src/connectors/spec/connect.rs, apollo-federation/src/connectors/spec/source.rs, apollo-federation/src/connectors/spec/type_and_directive_specifications.rs, apollo-federation/src/connectors/tests/schemas/is-success-source.graphql, apollo-federation/src/connectors/tests/schemas/is-success-source.yaml, apollo-federation/src/connectors/tests/schemas/is-success.graphql, apollo-federation/src/connectors/tests/schemas/is-success.yaml
Adds a new `isSuccess` argument to the `@source` and `@connect` directive definitions. 
This parameter will allow users to override the success conditions for connector responses. For example, a user might want to include 404 response data in the data returned from the connector rather than treating the response as an error.
Note: Validation and Error handling functionality related to this argument will be added in separate PR to keep the reviews relatively small.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes to the attention of other (impacted) groups. Please endeavour to do this …
=> Add isSuccess argument to @source and @connect directives

apollo-federation/cli/src/main.rs, apollo-federation/src/merger/merger.rs, apollo-federation/src/schema/argument_composition_strategies.rs, apollo-federation/src/schema/type_and_directive_specification.rs
* `ArgumentComposition` implementations shall return a default value, instead of `panic!`.
* The original JS code is here ([github](https://github.com/apollographql/federation/blob/4653320016ed4202a229d9ab5933ad3f13e5b6c0/internals-js/src/argumentCompositionStrategies.ts#L57)).
* Also, removed a panic in `ArgumentMerger` struct and CLI,
---
**Checklist**
**Exceptions**
This PR is just a refactoring. Those eliminated panic weren't expected to occur in practice.
[FED-170]: https://apollographql.atlassian.net/browse/FED-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(federation): eliminated panics from `ArgumentComposition` implementations

DEVELOPMENT.md, apollo-router/src/plugin/mod.rs
---
Small doc corrections:
1. Correction to the `router_service` description and small style update to the `supergraph_service` description to keep them consistent
2. Update the command to run code coverage locally
**Checklist**
**Exceptions**
**Notes**
[^3]: …
=> fix: Small doc corrections

apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/supergraph/mod.rs, apollo-federation/tests/query_plan/build_query_plan_tests/overrides.rs, apollo-federation/tests/query_plan/supergraphs/override_a_field_from_an_interface.graphql
This PR addresses an issue from the porting of the query planner. Some edges in the query graph were being incorrectly treated as external. This caused them to be removed from the query graph and for building a plan to fail.
---
**Checklist**
**Exceptions**
**Notes** …
=> Fixed FED 644

apollo-federation/src/connectors/json_selection/helpers.rs, apollo-federation/src/connectors/json_selection/methods.rs, apollo-federation/src/connectors/json_selection/methods/public/join_not_null.rs, apollo-federation/src/connectors/json_selection/methods/public/mod.rs, apollo-federation/src/connectors/json_selection/methods/public/to_string.rs, apollo-federation/src/connectors/json_selection/mod.rs, apollo-federation/src/connectors/string_template.rs
---
**Checklist**
**Exceptions**
**Notes** …
=> Implement toString connectors method

apollo-federation/src/error/mod.rs
This PR adds an error code for the `SubgraphError` variant of `CompositionError` rather than panicking.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level logs. Please read …
=> Added an error code for CompositionError::SubgraphError

apollo-federation/src/link/cost_spec_definition.rs, apollo-federation/src/merger/merger.rs, apollo-federation/src/schema/argument_composition_strategies.rs, apollo-federation/src/schema/type_and_directive_specification.rs
Since the initial port of `argumentCompositionStrategies.ts`, 3 new strategies were added ([code](https://github.com/apollographql/federation/blob/4653320016ed4202a229d9ab5933ad3f13e5b6c0/internals-js/src/argumentCompositionStrategies.ts#L92)). This PR ported them.
---
**Checklist**
**Exceptions**
This is an incremental implementation of native composition.
[FED-170]: https://apollographql.atlassian.net/browse/FED-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(federation): ported NullableMax, NullableAnd, NullableUnion argument composition strategies

apollo-router/src/plugins/response_cache/plugin.rs, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__failure_mode_reconnect-2.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__failure_mode_reconnect-4.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__insert-3.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__insert.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__insert_with_nested_field_set-3.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__insert_with_nested_field_set.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__insert_with_requires-3.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__insert_with_requires.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__invalidate_by_cache_tag-3.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__invalidate_by_cache_tag.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__invalidate_by_type-3.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__invalidate_by_type-5.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__invalidate_by_type.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__no_data.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__private-5.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__private.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__private_without_private_id-3.snap, apollo-router/src/plugins/response_cache/snapshots/apollo_router__plugins__response_cache__tests__private_without_private_id.snap, apollo-router/src/plugins/response_cache/tests.rs, apollo-router/tests/integration/snapshots/integration_tests__integration__postgres__entity_cache_basic-4.snap, apollo-router/tests/integration/snapshots/integration_tests__integration__postgres__entity_cache_basic.snap
Make sure the data passed in debugger data is always consistent and contains `data` field. And add debugger data even if it's a known private query.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in …
=> response_cache: add private entries in debugger data and make data consistent

apollo-federation/src/composition/satisfiability.rs, apollo-federation/src/query_graph/build_query_graph.rs, apollo-federation/src/query_graph/mod.rs
This PR fixes the failing satisfiability test `test_satisfiability_basic()` in `satisfiability.rs`. The specific bugs being fixed are:
1. The `QueryGraph::non_trivial_followup_edges` map was only being computed for federated query graphs and not API schema/supergraph query graphs (the JS code computes it for both).
2. The `QueryGraphEdgeTransition::matches_supergraph_transition()` function was mistakenly bailing when the `self` transition did not collect elements, when it should have been bailing when the `other` transition did not collect elements (as the JS code does).
=> fix(federation/composition): Fix the failing test `test_satisfiability_basic()`

apollo-federation/src/query_graph/mod.rs, apollo-federation/src/query_plan/query_planner.rs
`QueryPlanner`'s `override_condition_labels` field contains all override labels in the supergraph. This PR just make it publicly readable. The field is going to be used by test harness and other tools in the future.
---
**Checklist**
**Exceptions**
This is a minor refactoring.
=> refactor(federation): expose `override_condition_labels` from `QueryPlanner`

apollo-federation/src/connectors/runtime/responses.rs, apollo-router/src/plugins/connectors/handle_responses.rs, apollo-router/src/services/connector/request_service.rs
The goal is to be able to share this code elsewhere, which means pulling out the router-specific otel stuff. Along the way I cleaned up some minor style issues and I think removed one extra clone of the body.
[CNN-926]: https://apollographql.atlassian.net/browse/CNN-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove router-specific code from `deserialize_response`

.circleci/config.yml
Fixes 404s during mise install.<hr>This is an automatic backport of pull request #7965 done by [Mergify](https://mergify.com).
=> ci: update mise version (backport #7965)

.changesets/fix_tylerb_fed_644.md, apollo-federation/src/query_graph/graph_path.rs, apollo-federation/src/supergraph/mod.rs, apollo-federation/tests/query_plan/build_query_plan_tests/overrides.rs, apollo-federation/tests/query_plan/supergraphs/override_a_field_from_an_interface.graphql
This PR addresses an issue from the porting of the query planner. Some edges in the query graph were being incorrectly treated as external. This caused them to be removed from the query graph and for building a plan to fail.
---
**Checklist**
**Exceptions**
**Notes** …
=> Fixed FED 644 (backport #7929)

.changesets/fix_simon_router_1200.md, apollo-router/src/plugins/cache/entity.rs, apollo-router/src/plugins/response_cache/plugin.rs, apollo-router/tests/integration/entity_cache.rs, apollo-router/tests/integration/response_cache.rs
When the [Subgraph Entity Caching] feature is in use, it determines the `Cache-Control` HTTP response header sent to supergraph clients based on those received from subgraph servers.
In this process, Apollo Router only emits the `max-age` [directive] and not `s-maxage`.
This PR fixes a bug where, for a query that involved a single subgraph fetch that was not already cached, the subgraph response’s `Cache-Control` header would be forwarded as-is.
Instead, it now goes through the same algorithm as other cases.
[Subgraph Entity Caching]: https://www.apollographql.com/docs/graphos/routing/performance/caching/entity
[directive]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cache-Control#response_directives
---
**Checklist**
Complete the checklist (and note appropriate …
=> Entity caching: fix inconsistency in cache-control header handling

apollo-federation/src/connectors/json_selection/methods/future/arithmetic.rs
This PR builds on #7932 and supersedes #7623, including only the improvements to `math_shape` and not the other preliminary commits, which have now been moved into #7932.
The math methods (`->add`, `->sub`, `->mul`, `->div`, and `->mod`) still need to be promoted to `methods::public` rather than `methods::future`, before we can call them fully shipped. However, all `->` methods are available in tests, which is why the tests are passing before we've publicly released the new methods.
=> Fully implement `math_shape` again

.changesets/fix_renee_router_1343.md, .config/nextest.toml, apollo-router/src/protocols/multipart.rs, apollo-router/src/query_planner/execution.rs, apollo-router/src/services/supergraph/service.rs, apollo-router/src/services/supergraph/snapshots/apollo_router__services__supergraph__tests__subscription_callback_schema_reload-3.snap, apollo-router/tests/integration/subscriptions/ws_passthrough.rs
Using a GraphQL response extension to mark "fatal" errors that should be reported as a top-level `{errors}` key in the subscriptions chunk, while letting non-fatal errors through as `{payload: {errors}}` chunks. In the past, we tried to detect this "magically" by seeing if the error is the _final_ response in the stream, which isn't 100% accurate and can also be flaky depending on when the subgraph closes the connection.
I wanted to use a `Result` type here to enforce that fatal errors would be marked and handled correctly, but that would be a breaking change to our response types and every plugin. So instead, responses that are subscription fatal errors have a GraphQL extension `apollo::subscriptions::fatal_error`. The multipart serialisation code uses only that extension to decide how …
=> Reliably distinguish GraphQL errors and transport errors in subscriptions

Cargo.toml
This PR loosens the version requirement of the `encoding_rs` dependency from "0.8.35" to "0.8". The prior version conflicts with fed-core's testing harness.
=> Loosen encoding_rs dep version

.changesets/feat_zelda_jemalloc_metrics.md, Cargo.lock, apollo-router/Cargo.toml, apollo-router/src/axum_factory/axum_http_server_factory.rs, apollo-router/src/axum_factory/metrics.rs, apollo-router/src/axum_factory/mod.rs, apollo-router/tests/integration/metrics.rs, apollo-router/tests/integration/mod.rs
This PR backports #7735
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level logs. Please read [this guidance](https://github.com/apollographql/router/blob/dev/dev-docs/metrics.md …
=> Backport: #7735 Jemalloc metrics

Cargo.lock, apollo-federation/cli/Cargo.toml, apollo-federation/cli/src/main.rs
The `apollo-federation-cli` had "compose" command, but it used the old composition prototype.
This PR updates the command to use the new Rust composition implementation.
Additional changes:
* Since composition function returns `Vec<CompositionError>`, instead of `FederationError` as other functions do, this PR changed all command-line handles to return `anyhow::Error`.
**Checklist**
**Exceptions**
This PR only updates the internal CLI command.
=> test(federation): updated the "compose" CLI command to use the new native composition

xtask/src/commands/release.rs
Changes nightly versions from:
```
0.0.0-nightly.<date>+<commithash>
```
to:
```
0.0.0-nightly-<version>.<date>+<commithash>
```
This will make it easier to identify versions in the big list of
nightlies. The version number is appended in the prerelease
metadata part of the semver version, because nightlies actually do _not_
have to be in any way semver-compatible with that version (they can even
include major breaking changes).
<hr>This is an automatic backport of pull request #8009 done by [Mergify](https://mergify.com).
=> Include base version in nightly versioning scheme (backport #8009)

.circleci/config.yml, dockerfiles/Dockerfile.router, dockerfiles/diy/build_docker_image.sh, dockerfiles/download_and_validate_router.sh
We recently encountered data corruption where a file in a Docker build had the correct size but wrong checksum, resulting in a broken Router image. This adds checksum validation to prevent such issues.
Adds SHA256 validation for both nightly and release builds:
* Nightly builds: Validates local artifacts, remote artifacts in more than one way — inside CI, and within the Docker build
* Release builds: Downloads and validates against published sha256sums.txt from GitHub releases
Both paths fail with error messages if checksums don't match.
- https://github.com/apollographql/router/pull/7634
- [See this run](https://app.circleci.com/pipelines/github/apollographql/router/38179/workflows/b8012ab2-be5a-435c-8832-95b9baa2c020/jobs/286527/parallel-runs/0/steps/0-116)
- I'm also just starting …
=> Docker build improvements (sha256sums and `BASE_VERSION`),  (backport #8056, #7634)

apollo-federation/src/composition/mod.rs, apollo-federation/src/link/database.rs, apollo-federation/src/subgraph/typestate.rs
Previously in `is_bootstrap_directive` function, `@link` directive recognition rule was more strict than `@core`.
```rust
/// Returns true if the given definition matches the @core definition.
///
/// Either of these definitions are accepted:
/// ```graphql
/// directive @_ANY_NAME_(feature: String!, as: String) repeatable on SCHEMA
/// directive @_ANY_NAME_(feature: String, as: String) repeatable on SCHEMA
/// directive @_ANY_NAME_(feature: String!) repeatable on SCHEMA
/// directive @_ANY_NAME_(feature: String) repeatable on SCHEMA
/// ```
fn is_core_directive_definition(definition: &DirectiveDefinition) -> bool {
```
```rust
/// Returns true if the given definition matches the @link definition.
///
/// Either of these definitions are accepted:
/// ```graphql
/// directive …
=> fix(federation/composition): fixed `is_link_directive_definition` to be consistent with the JS version

.changesets/feat_zelda_enable_jemalloc_on_macos.md, apollo-router/Cargo.toml, apollo-router/src/axum_factory/axum_http_server_factory.rs, apollo-router/src/axum_factory/metrics.rs, apollo-router/src/executable.rs, apollo-router/tests/integration/metrics.rs
This PR enables the jemalloc allocator on MacOS by default. Previously, this was only done for Linux. We're making this change because it will make memory profiling easier than it currently is.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not …
=> Enable jemalloc on MacOS

.changesets/docs_add_dockerhub_runtime_container.md, docs/source/routing/self-hosted/index.mdx
As per title, updates the documentation to add reference to our new DockerHub repo for the Runtime Container
=> Add DockerHub References To The Documentation

apollo-router/tests/integration/batching.rs, apollo-router/tests/integration/connectors.rs, apollo-router/tests/integration/file_upload.rs, apollo-router/tests/integration/telemetry/metrics.rs, apollo-router/tests/samples_tests.rs
=> Always use `graph_os_enabled` helper for GraphOS tests

docs/source/routing/observability/telemetry/instrumentation/standard-instruments.mdx
see [DXM-215](https://apollographql.atlassian.net/browse/DXM-215)
[DXM-215]: https://apollographql.atlassian.net/browse/DXM-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update router metric names (underscore -> dot separator) in docs

.circleci/config.yml
We have a lot of OOMs happening on windows CI. the easiest way to fix it would seem to be to just download a bunch more ram.
https://www.youtube.com/watch?v=MbclRNm_ANY
=> ci: beefier windows machines

docs/source/routing/cloud/migrate-to-dedicated.mdx, docs/source/routing/configuration/cli.mdx, docs/source/routing/configuration/envvars.mdx, docs/source/routing/graphos-features.mdx, docs/source/routing/security/persisted-queries.mdx
Found some broken (or missing) links to the Offline Mode docs. Snapped those to what it looks like everything else is using.
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and `debug`-level …
=> Fix: Broken or missing Offline Mode links

.changesets/fix_duckki_fed_678.md, apollo-federation/src/operation/rebase.rs, apollo-federation/tests/query_plan/build_query_plan_tests/requires.rs, apollo-federation/tests/query_plan/supergraphs/allows_post_requires_input_with_typename_on_interface_object_type.graphql
- The `rebase_on` method was prohibiting __typename field from being rebased on an interface object type by raising `InterfaceObjectTypename` error.
- But, it seemed unnecessarily prohibitive, rejecting plannable queries.
- Although it's odd to fetch `__typename` from interface object types, there are already several other cases where such `__typename` selections are added to interface object types.
- Such `__typename` selections are benign and we currently don't plan to remove all of those cases at this time.
- Thus, this PR removes the error variant and the check for the error altogether.
- Also, added a regression test that caused the error previously.
---
**Checklist**
- Tests added and …
=> fix(federation): removed `RebaseError::InterfaceObjectTypename` error

apollo-federation/src/connectors/runtime.rs, apollo-federation/src/connectors/runtime/cache.rs, apollo-federation/src/connectors/runtime/http_json_transport.rs, apollo-router/src/plugin/test/mod.rs, apollo-router/src/plugin/test/service.rs, apollo-router/src/plugins/connectors/handle_responses.rs, apollo-router/src/plugins/connectors/make_requests.rs, apollo-router/src/plugins/connectors/make_requests/graphql_utils.rs, apollo-router/src/plugins/connectors/tests/mod.rs, apollo-router/src/plugins/headers/mod.rs, apollo-router/src/services/connect.rs, apollo-router/src/services/connector_service.rs, apollo-router/src/services/fetch_service.rs
- Refactor make_requests to take explicit parameters instead of connect::Request
- Update connect::Request to contain prepared_requests vector
- Move request preparation to happen before connector service call
- Update connector service execute function to use prepared_requests
- Add backward compatibility layer for tests with deprecated fields
- Keep make_requests tests unchanged via legacy function wrappers
This simplifies the connect::Request structure and moves request preparation earlier in the pipeline, setting up for caching support.
---
**Checklist**
**Exceptions**
**Notes**
[^1]: It may be appropriate to bring upcoming changes …
=> refactor: move request preparation to connect::Request constructor

apollo-federation/src/connectors/validation/snapshots/validation_tests@uri_templates__invalid_source_url_template.graphql.snap, apollo-federation/src/connectors/validation/snapshots/validation_tests@uri_templates__valid_source_url_template.graphql.snap, apollo-federation/src/connectors/validation/source.rs, apollo-federation/src/connectors/validation/test_data/uri_templates/valid_source_url_template.graphql
With expressions, we don't know the values at composition time so we can't tell if it is valid. This can result in us saying it is NOT valid when at run time it would be.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit …
=> Fix: Avoid baseUrl validation when it contains expressions

apollo-federation/tests/composition/mod.rs, apollo-federation/tests/composition/subscription.rs
Ports the three tests from [compose.subscription.test.ts](https://github.com/apollographql/federation/blob/main/composition-js/src/__tests__/compose.subscription.test.ts) around merging root subscriptions. These tests are currently set to ignore until the merge implementation can execute without panicking on todos.
---
**Checklist**
**Exceptions**
**Notes**
[^2]: Configuration is …
=> Port subscription merging integration tests

apollo-router/src/configuration/mod.rs, apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap, apollo-router/src/plugins/chaos/mod.rs, apollo-router/src/plugins/chaos/reload.rs, apollo-router/src/plugins/mod.rs, apollo-router/src/router/event/configuration.rs, apollo-router/src/router/event/mod.rs, apollo-router/src/router/event/reload.rs, apollo-router/src/router/mod.rs, apollo-router/src/state_machine.rs, apollo-router/src/uplink/schema.rs, apollo-router/tests/integration/lifecycle.rs
The experimental chaos plugin was not actually useful because the router detects that a schema reload event is the same as the last seen schema and skips reloading.
This PR fixes and enhances the chaos plugin so that we can actually use it for testing.
Changes:
- Split out chaos reload and sighup reload into separate units of functionality.
- Chaos plugin:
- Fix ineffective schema reload.
- Add force_schema_reload and force_config_reload with independent timers
- Automatically capture and replay events with modifications to force reloads:
- Schema events: inject timestamp comments into SDL
- Config events: clone and re-emit configuration
As experimental chaos is not officially supported there is no changeset, documentation and the config is allowed to have breaking changes.
--- …
=> (feat) Enhance chaos plugin (backport #8083)

apollo-federation/src/link/database.rs, apollo-federation/src/link/link_spec_definition.rs, apollo-federation/src/schema/position.rs, apollo-federation/src/schema/schema_upgrader.rs, apollo-federation/src/subgraph/typestate.rs, apollo-federation/tests/composition/demand_control.rs
The schema upgrader didn't recognize renamed link directives previously.
Also, the upgrader used to call`add_federation_link_to_schema`, which was meant for testing and didn't handle link directive name conflicts.
- fixed schema upgrader to correctly remove renamed link specs from the original schema
- fixed schema upgrader to avoid link directive name conflicts in the upgraded schemas (using `schema_as_fed2_subgraph`)
- fixed `add_definitions_to_schema` not to add an unnecessary `Import` type spec for `@core`
- fixed `add_fed1_link_to_schema` not to add fed1 spec ahead of the link spec itself.
This PR has 3 commits and it will be easier to review commit by commit:
- The first is a pure refactoring intended for making it easier to implement the fix.
- The second commit is for tests. This …
=> fix(federation/composition): fixed link alias handling in schema upgrading

.changesets/fix_bnjjj_fix_subs_closing.md, apollo-router/src/notification.rs, apollo-router/src/plugins/subscription.rs, apollo-router/src/services/subgraph_service.rs, apollo-router/src/services/supergraph/tests.rs, apollo-router/tests/integration/subscriptions/ws_passthrough.rs
A regression was introduced in https://github.com/apollographql/router/pull/7879 while attempting to fix an earlier regression. In this PR, we removed the client connection closing signal, which had been unnecessary and was causing deduplicated subscriptions to stop receiving events when the original (first) matching subscription was closed from the client to the router. However, eliminating this channel led to a new issue: subscriptions between the router and subgraph were not closed correctly. Although all client-to-router connections closed as expected, the connection from the router to the subgraph remained open until an event was received for that subscription.
This PR resolves the problem by introducing a closing signal channel in `Notify`, which automatically sends a notification …
=> fix(subscription): fix deduplication and websocket stream termination (backport #8104)

Cargo.lock, apollo-router/Cargo.toml
To prevent warnings about RUSTSEC-2025-0055 update tracing subscriber. This is unlikely to be an an issue for users, but silences the warning. 
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability …
=> deps: RUSTSEC-2025-0055 Update tracing-subscriber

docs/source/routing/observability/client-id-enforcement.mdx
Accidentally introduced in #7516. Doc-only non-semantic change.
See https://www.apollographql.com/docs/graphos/routing/observability/client-id-enforcement#via-router-customization for what it looks like now.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A …
=> docs: fix missing end of code block

dockerfiles/Dockerfile.router, dockerfiles/download_and_validate_router.sh
When making #8056, I missed an important detail in my analysis of the CircleCI script responsible for building the router releases.  In particular, I failed to observe that the `--platform` argument was variable and could be both arm64 and amd64 varieties and actually requests [BOTH], which packages two within one container [multi-build style].
This change updates the `download_and_validate.sh` script to make use of a Docker provided `TARGETPLATFORM` variable in deciding which release tarball to place within the built image, depending on the platform.
Overall the thing to run to reproduce the regression on an Arm Mac is: `docker run -ti --platform=linux/arm64 ghcr.io/apollographql/router:v2.6.0`.  You can replace this tag with any version you'd like, but v2.6.0 is broken and others work. …
=> fix: release builds of docker images should utilize correct target platform (backport #8187)

.changesets/fix_glasser_helm_deployment_annotations.md, docs/shared/helm-show-router-output.mdx, helm/chart/router/README.md, helm/chart/router/templates/deployment.yaml, helm/chart/router/values.yaml
This lets you put annotations on the deployment itself (as opposed to the pods within it, which is done with podAnnotations).
For example, you could use this to have
https://github.com/stakater/Reloader reload router when config maps or secrets change.
---
**Checklist**
**Exceptions**
**Notes** …
=> fix(helm): deploymentAnnotations value (backport #8164)

.changesets/fix_bryn_connection_cancellation_race.md, apollo-router/src/axum_factory/listeners.rs
Previously we were using Notify to indicate to connections that they should shut down when a reload happens. However, this creates a race condition where if a connection is being established at the moment that shutdown is called the new connection will never receive the shutdown notification. Notify only notifies current waiters and will not immediately resolve if new waiters are added.
This PR switches to CancellationToken which once cancelled will always yield cancelled immediately.
This would manifest for users as ever growing memory use over hot reloads as a connection could potentially hold onto a pipeline forever.
**Note: there is no unit test**
The reason for this is that to trgger this it requires an enormous number of iterations, it's not possible to trigger it as part of a …
=> Connection cancellation race (backport #8169)

.changesets/fix_bnjjj_fix_subs_closing.md, .changesets/fix_glasser_helm_deployment_annotations.md, .changesets/fix_princess_cantaloupe.md, .changesets/fix_rreg_fix_entities_errors_missing_service.md, CHANGELOG.md, Cargo.lock, apollo-federation/Cargo.toml, apollo-router-benchmarks/Cargo.toml, apollo-router/Cargo.toml, docs/shared/k8s-manual-config.mdx, helm/chart/router/Chart.yaml, helm/chart/router/README.md, scripts/install.sh
> **Note**
>
> When approved, this PR will merge into **the `2.6.1` branch** which will — upon being approved itself — merge into `main`.
>
>  - That it targets the right release branch (`2.6.1` in this case!).
>
---
The error counting feature introduced in [PR #7712](https://github.com/apollographql/router/pull/7712) caused a bug where `_entities` errors from subgraph fetches no longer included a service (subgraph or connector) attribute. This incorrectly categorized these errors as originating from the router instead of their actual service in the Apollo Studio UI.
This fix restores the …
=> prep release: v2.6.1

.changesets/fix_bryn_connection_cancellation_race.md, CHANGELOG.md, Cargo.lock, apollo-federation/Cargo.toml, apollo-router-benchmarks/Cargo.toml, apollo-router/Cargo.toml, docs/shared/k8s-manual-config.mdx, helm/chart/router/Chart.yaml, helm/chart/router/README.md, licenses.html, scripts/install.sh
> **Note**
>
> When approved, this PR will merge into **the `2.6.2` branch** which will — upon being approved itself — merge into `dev`.
>
>  - That it targets the right release branch (`2.6.2` in this case!).
>
---
A race condition in connection shutdown during a hot reload event occasionally left some connections in an active state instead of entering terminating state. This could cause out-of-memory errors over time as multiple pipelines remained active.
Connections that open during shutdown now immediately terminate.
By [@BrynCooke](https://github.com/BrynCooke) in …
=> prep release: v2.6.2

apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap, apollo-router/src/plugins/telemetry/config_new/selectors.rs, apollo-router/src/plugins/telemetry/config_new/subgraph/selectors.rs
This gives us the abililty to configure subgraph instruments like this:
```yaml
telemetry:
events:
subgraph:
response:
level: info
condition:
all:
- eq:
- subgraph_name: true
- static: posts
- eq:
- response_cache_status: status
- miss
instruments:
subgraph:
http.client.request.duration:
attributes:
subgraph.name: true
http.response.status_code:
subgraph_response_status: code
response.cache.hit:
response_cache: hit
response.cache.status:
response_cache_status: status
```
and will be easier to filter on a subgraph coming from cache or not or partially.
=> feat(response_cache): add new selector to get cache status

apollo-federation/src/error/mod.rs, apollo-federation/src/merger/merger.rs, apollo-federation/tests/composition/mod.rs, apollo-federation/tests/composition/override_directive.rs
Ports over [override.compose.tests.ts](github.com/apollographql/federation/blob/main/composition-js/src/__tests__/override.compose.test.ts).
* All tests are currently failing due to unimplemented composition methods.
* Added missing CompositionError enum values
[FED-694]: https://apollographql.atlassian.net/browse/FED-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(composition): port override.compose.test.ts

apollo-federation/src/connectors/json_selection/apply_to.rs, apollo-federation/src/connectors/validation/expression.rs
One possible answer to the problems with checking named shapes + `??` or `?!`.
=> Treat `ShapeCase::Name` in `??` and `?!` expressions as `Unknown`, relaxing validation

apollo-federation/src/connectors/json_selection/methods/future/has.rs, apollo-federation/src/connectors/json_selection/methods/future/match_if.rs, apollo-federation/src/connectors/json_selection/methods/public/and.rs, apollo-federation/src/connectors/json_selection/methods/public/arithmetic.rs, apollo-federation/src/connectors/json_selection/methods/public/contains.rs, apollo-federation/src/connectors/json_selection/methods/public/echo.rs, apollo-federation/src/connectors/json_selection/methods/public/entries.rs, apollo-federation/src/connectors/json_selection/methods/public/eq.rs, apollo-federation/src/connectors/json_selection/methods/public/filter.rs, apollo-federation/src/connectors/json_selection/methods/public/find.rs, apollo-federation/src/connectors/json_selection/methods/public/get.rs, apollo-federation/src/connectors/json_selection/methods/public/gt.rs, apollo-federation/src/connectors/json_selection/methods/public/gte.rs, apollo-federation/src/connectors/json_selection/methods/public/in.rs, apollo-federation/src/connectors/json_selection/methods/public/join_not_null.rs, apollo-federation/src/connectors/json_selection/methods/public/lt.rs, apollo-federation/src/connectors/json_selection/methods/public/lte.rs, apollo-federation/src/connectors/json_selection/methods/public/map.rs, apollo-federation/src/connectors/json_selection/methods/public/match.rs, apollo-federation/src/connectors/json_selection/methods/public/ne.rs, apollo-federation/src/connectors/json_selection/methods/public/or.rs, apollo-federation/src/connectors/json_selection/methods/public/parse_int.rs, apollo-federation/src/connectors/json_selection/methods/public/size.rs, apollo-federation/src/connectors/json_selection/methods/public/slice.rs, apollo-federation/src/connectors/validation/expression.rs
Similar in spirit to the `Unknown` audit I did in PR #8298 (whose branch this PR targets), this PR audits all arrow methods to ensure they evaluate to `None` (at runtime and at shape processing time) if any of their **arguments** evaluate to `None`.
Previously and currently, arrow methods follow a policy of never executing if their input value is `None`/missing, but this PR strengthens that promise to apply to arguments as well.
Remember that you can use `??` to default a `None` value to anything else (see #8082, #8090).
=> Ensure all arrow methods produce `None` if any argument evaluates to `None`

apollo-federation/src/error/mod.rs, apollo-federation/src/merger/merger.rs
This was inlined in the JS version in the Merger constructor and has no direct analog
=> implement validate_query_root

apollo-router/src/configuration/mod.rs, apollo-router/src/configuration/tests.rs, apollo-router/src/router_factory.rs, apollo-router/src/uplink/snapshots/apollo_router__uplink__license_enforcement__test__restricted_features_via_config_allowed_features_empty.snap, apollo-router/src/uplink/snapshots/apollo_router__uplink__license_enforcement__test__restricted_features_via_config_unlicensed.snap, apollo-router/src/uplink/testdata/restricted.router.yaml
Entity cache and response cache plugins should not be used simultaneously; enforce this in the router configuration validation process.
---
**Checklist**
**Exceptions**
**Notes**
[^3]: A lot of (if not most) features benefit from built-in observability and …
=> feat(response_cache): prevent simultaneous usage of entity and response cache plugins

docs/source/routing/upgrade/from-router-v1.mdx
This PR updates the migration guide to properly document that `apollo.router.open_connections` is the replacement for the deprecated `apollo_router_session_count_total` metric. 
The deprecated metric was removed in v2.0.0, but its replacement was introduced in v2.1.0. The migration guide previously stated there was no equivalent, which was only true initially.
[ROUTER-1460]: https://apollographql.atlassian.net/browse/ROUTER-1460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add apollo_router_session_count_total to apollo.router.open_connections to migration guide

apollo-federation/src/subgraph/typestate.rs
JS composition (based on GraphQL-js) accepts duplicate field argument definitions, choosing the last definition if there are multiple duplicate definitions. For example,
```graphql
type Query {
test_root_field(
arg1: Boolean
"some description"
arg1: Boolean # duplicate
): Int
}
```
Note that duplicate argument definitions weren't invalid in the previous GraphQL specs before September 2025 revision.
This PR updates `Subgraph::parse` method to simulate graphql-js behavior by removing duplicate argument definitions leaving the last one. Since that removal happens before the subgraph expansion and validation steps, those steps won't produce duplicate argument errors.
---
**Checklist**
- Tests …
=> fix(federation/composition): accept duplicate field arguments

apollo-router/src/plugins/authorization/policy.rs, apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__policy__tests__interface_with_implementers_directive_not_defined.snap, apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__policy__tests__interface_with_implementor_not_defining_field_level_policy.snap, apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__policy__tests__interface_with_implementor_not_defining_field_level_policy_empty_doc.snap, apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__policy__tests__interface_with_implementor_not_defining_field_level_policy_with_request_not_sending_policies.snap, apollo-router/src/plugins/authorization/snapshots/apollo_router__plugins__authorization__policy__tests__interface_with_implementor_not_defining_type_level_policy.snap, apollo-router/tests/fixtures/directives/policy/policy_basic_schema.graphql, apollo-router/tests/fixtures/directives/policy/policy_schema_with_interfaces.graphql, apollo-router/tests/integration/directives/mod.rs, apollo-router/tests/integration/directives/policy.rs, apollo-router/tests/integration/mod.rs
---
**Checklist**
**Exceptions**
**Notes** …
=> chore(tests): backfilling tests for the `@policy` directive

docs/shared/native-plugin-notice.mdx
Emphasize that Apollo supports Rhai scripts and external coprocessors for router customizations, but not custom binaries
=> [docs] Update native plugin notice with support details

apollo-router/src/executable.rs, docs/source/routing/configuration/cli.mdx, docs/source/routing/self-hosted/containerization/docker-router-only.mdx, docs/source/routing/self-hosted/containerization/docker.mdx
This PR updates router documentation for the graph artifacts preview. It also fixes some broken documentation links.
Jira story: [[VUL-1427] [GrAr] Add documentation to router for Graph Artifacts](https://apollographql.atlassian.net/browse/VUL-1427)
Pages to review the changes:
* CLI: https://www.apollographql.com/docs/deploy-preview/b5a223e694f2c188a7ccac1f/graphos/routing/configuration/cli#--graph-artifact-reference
* Docker: https://www.apollographql.com/docs/deploy-preview/b5a223e694f2c188a7ccac1f/graphos/routing/self-hosted/containerization/docker#using-a-graph-artifact-reference
* Docker-Router-Only: https://www.apollographql.com/docs/deploy-preview/b5a223e694f2c188a7ccac1f/graphos/routing/self-hosted/containerization/docker-router-only#using-a-graph-artifact-reference
--- …
=> Update docs for graph artifacts

apollo-federation/src/connectors/header.rs, apollo-federation/src/connectors/mod.rs, apollo-federation/src/connectors/spec/source.rs
We can deploy https://connectors-mapping.netlify.app from a local branch if we have to, but it would be nice to have a stable `apollo-federation` version that is fully usable by the playground, as-is. We are about to cut a final preview build from the `dev` branch of this repository, so I'm hoping we can still get this PR in.
The last time I investigated updating the playground to `ConnectSpec::V0_3` (to enable the new language features), I found these changes to be necessary: https://github.com/apollographql/connectors-mapping-playground/pull/76
Those changes in turn require making `HeaderValue::parse_with_spec` and `SourceHTTPArguments::from_directive` public in the `apollo-federation` crate, so they can be used by the mapping playground.
=> Visibility tweaks for the connectors mapping playground

.changesets/fix_fix_sachin_fed_544.md, .changesets/fix_sachin_fed_544.md, apollo-federation/src/query_plan/fetch_dependency_graph.rs, apollo-federation/tests/query_plan/build_query_plan_tests/requires.rs, apollo-federation/tests/query_plan/supergraphs/avoids_selecting_inapplicable_key_from_parent_node.graphql
When a `@requires` edge needs a subgraph jump during fetch dependency graph processing, this would sometimes cause the locally satisfiable key fields needed by that jump to be fetched from the parent node instead of the current node (which apparently was done as an optimization). This can be a problem, since `GraphPath::can_satisfy_conditions()` only really guarantees the current node has those key fields.
This PR updates the code using the parent node to now explicitly check whether the locally satisfiable key can be fetched from that node, and if not, falls back to the current node (adding it as a parent, if needed). This lets us keep the optimization and avoid unnecessarily changing query plans.
This PR mirrors its JS equivalent at https://github.com/apollographql/federation/pull/3293 …
=> fix(federation/query-planning): Fix bug where subgraph jump key fields are fetched from the wrong node

apollo-federation/src/merger/merge_field.rs, apollo-federation/src/merger/merger.rs
Ports [Merger.addMissingInterfaceObjectFieldsToImplementations](https://github.com/apollographql/federation/blob/8cdd1f01f663f77c921e261d3704830152dd7587/composition-js/src/merging/merge.ts#L1165) from JS. After merging objects and interfaces, we need to make sure that interface objects correctly contribute their fields to relevant object types. We do this by looping over all object types, checking if their interfaces are actually interface objects, and then merging any fields which haven't already been copied over.
---
**Checklist**
[FED-795]: https://apollographql.atlassian.net/browse/FED-795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
=> feat(composition): Implement add_missing_interface_object_fields_to_implementations

.changesets/fix_bryn_rhai_logging.md, apollo-router/src/plugins/rhai/mod.rs, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__error_logging_with_body@logs.snap, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__error_logging_without_body@logs.snap, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__execution_error_logging_with_body@logs.snap, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__execution_error_logging_without_body@logs.snap, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__router_error_logging_with_body@logs.snap, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__router_error_logging_without_body@logs.snap, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__subgraph_error_logging_with_body@logs.snap, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__subgraph_error_logging_without_body@logs.snap, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__supergraph_error_logging_with_body@logs.snap, apollo-router/src/plugins/rhai/snapshots/apollo_router__plugins__rhai__tests__supergraph_error_logging_without_body@logs.snap, apollo-router/src/plugins/rhai/tests.rs, apollo-router/src/services/layers/persisted_queries/snapshots/apollo_router__services__layers__persisted_queries__tests__pq_layer_freeform_graphql_with_safelist_log_unknown_true@logs.snap, apollo-router/tests/fixtures/error_with_body.rhai, apollo-router/tests/fixtures/error_without_body.rhai, docs/source/routing/customization/rhai/index.mdx
In Rhai we use throw to indicate that the pipeline should no longer proceed and should instead immediately return to the user.
Previously wherever this happened this would log an error.
However, when a user wants to return an error response it is not helpful to always log the entire body as an error, and causes a flood of logs.
This PR adds logic to only log if there is no body associated with the response.
For example the following will NOT log
```
throw #{
status: 403,
body: #{
errors: [#{
message: "Custom error with body",
extensions: #{
code: "FORBIDDEN"
}
}]
}
};
```
For example the following WILL log
```
throw "An error occurred without a body";
```
---
**Checklist**
- Tests added and …
=> (fix) Prevent log on rhai scripts that short circuit

Cargo.lock, apollo-federation/Cargo.toml, apollo-federation/src/merger/merge_argument.rs, apollo-federation/src/merger/merge_directive.rs, apollo-federation/src/merger/merge_enum.rs, apollo-federation/src/merger/merger.rs, apollo-federation/src/schema/position.rs, apollo-federation/tests/composition/compose_basic.rs, apollo-federation/tests/composition/snapshots/main__composition__compose_basic__preserves_descriptions.snap
This change reintroduces the calls to `merge_description` and `record_applied_directives_to_merge` inside the `merge_enum` logic. The enum merging logic operates on AST nodes, which diverges from our position-based APIs in other locations. While not ideal, I have re-created positions from the AST nodes for use with these two new helper calls.
Including the call to `merge_descriptions` meant that we were now trying to index into `Merger::subgraphs`, which unfortunately wasn't populated inside the test merger created for the enum tests, resulting in index out of bounds errors for all of those. Since these were difficult to set up and primarily operating in-memory (instead of on schemas), I have removed these tests in favor of our integration tests. The description merging logic is verified …
=> feat(composition): Description merging for enum values

apollo-federation/src/link/federation_spec_definition.rs, apollo-federation/src/link/spec_definition.rs, apollo-federation/src/merger/merge_directive.rs, apollo-federation/src/merger/merge_interface.rs, apollo-federation/src/merger/merge_links.rs, apollo-federation/src/merger/merger.rs, apollo-federation/tests/composition/compose_auth.rs
This enables the first of the `compose_auth` integration tests and applies the following fixes:
- If there is no static argument transform registered for a directive, record the existing unchanged applications for merging (they were being dropped)
- When validating interface keys, gracefully exit if there is no `@key` directive in the schema
- Added the federation spec to the spec registry because we need to look up the composition/merge strategy for imported directives
- Added Fed v1.0 to the static federation versions to fix schema upgrader errors after adding federation to the spec registry
---
**Checklist**
[FED-825]: …
=> fix(composition): Record cloned directive applications when there is no static transform
